<?php
//Афганистан 48
$libaf = array ( 
"1"=>array("name_ru"=>"Кабул","name_en"=>"Kabul","name_href" => "af/population-of-kabul","count" => "3 071 400","real_id" =>1,),
"2"=>array("name_ru"=>"Мазари-Шариф","name_en"=>"Mazar-i-Sharif","name_href" => "af/population-of-mazar-i-sharif","count" => "693 000","real_id" =>2,),
"3"=>array("name_ru"=>"Асмар","name_en"=>"Asmara","name_href" => "af/population-of-asmara","count" => "649 000","real_id" =>3,),
"4"=>array("name_ru"=>"Кандагар","name_en"=>"Kandahar","name_href" => "af/population-of-kandahar","count" => "491 500","real_id" =>4,),
"5"=>array("name_ru"=>"Герат","name_en"=>"Herat","name_href" => "af/population-of-herat","count" => "436 300","real_id" =>5,),
"6"=>array("name_ru"=>"Джелалабад","name_en"=>"Jalalabad","name_href" => "af/population-of-jalalabad","count" => "205 423","real_id" =>6,),
"7"=>array("name_ru"=>"Талукан","name_en"=>"Taloqan","name_href" => "af/population-of-taloqan","count" => "196 400","real_id" =>7,),
"8"=>array("name_ru"=>"Меймене","name_en"=>"Maymana","name_href" => "af/population-of-maymana","count" => "149 040","real_id" =>8,),
"9"=>array("name_ru"=>"Баглан","name_en"=>"Baghlan","name_href" => "af/population-of-baghlan","count" => "119 607","real_id" =>9,),
"10"=>array("name_ru"=>"Кундуз","name_en"=>"Kunduz","name_href" => "af/population-of-kunduz","count" => "112 689","real_id" =>10,),
"11"=>array("name_ru"=>"Чарикар","name_en"=>"Charikar","name_href" => "af/population-of-charikar","count" => "100 000","real_id" =>11,),
"12"=>array("name_ru"=>"Марджа","name_en"=>"Marjah","name_href" => "af/population-of-marjah","count" => "85 000","real_id" =>12,),
"13"=>array("name_ru"=>"Шибарган","name_en"=>"Sheberghan","name_href" => "af/population-of-sheberghan","count" => "78 300","real_id" =>13,),
"14"=>array("name_ru"=>"Балх","name_en"=>"Balkh","name_href" => "af/population-of-balkh","count" => "77 000","real_id" =>14,),
"15"=>array("name_ru"=>"Гардез","name_en"=>"Gardez","name_href" => "af/population-of-gardez","count" => "70 000","real_id" =>15,),
"16"=>array("name_ru"=>"Бамиан","name_en"=>"Bamyan","name_href" => "af/population-of-bamyan","count" => "61 863","real_id" =>16,),
"17"=>array("name_ru"=>"Асадабад","name_en"=>"Asadabad","name_href" => "af/population-of-asadabad","count" => "61 235","real_id" =>17,),
"18"=>array("name_ru"=>"Пули-Хумри","name_en"=>"Puli Khumri","name_href" => "af/population-of-puli-khumri","count" => "58 300","real_id" =>18,),
"19"=>array("name_ru"=>"Газни","name_en"=>"Ghazni","name_href" => "af/population-of-ghazni","count" => "57 800","real_id" =>19,),
"20"=>array("name_ru"=>"Зарандж","name_en"=>"Zaranj","name_href" => "af/population-of-zaranj","count" => "49 851","real_id" =>20,),
"21"=>array("name_ru"=>"Андараб","name_en"=>"Andarab ","name_href" => "af/population-of-andarab-","count" => "47 000","real_id" =>21,),
"22"=>array("name_ru"=>"Лашкаргах","name_en"=>"Lashkar Gah","name_href" => "af/population-of-lashkar-gah","count" => "45 846","real_id" =>22,),
"23"=>array("name_ru"=>"Файзабад","name_en"=>"Fayzabad","name_href" => "af/population-of-fayzabad","count" => "44 421","real_id" =>23,),
"24"=>array("name_ru"=>"Гиришк","name_en"=>"Girishk","name_href" => "af/population-of-girishk","count" => "43 588","real_id" =>24,),
"25"=>array("name_ru"=>"Фарах","name_en"=>"Farah","name_href" => "af/population-of-farah","count" => "35 800","real_id" =>25,),
"26"=>array("name_ru"=>"Акча","name_en"=>"Aqcha","name_href" => "af/population-of-aqcha","count" => "35 300","real_id" =>26,),
"27"=>array("name_ru"=>"Майданшахр","name_en"=>"Maidan Shar","name_href" => "af/population-of-maidan-shar","count" => "35 008","real_id" =>27,),
"28"=>array("name_ru"=>"Ташкурган","name_en"=>"Tashkurgan","name_href" => "af/population-of-tashkurgan","count" => "33 000","real_id" =>28,),
"29"=>array("name_ru"=>"Нили","name_en"=>"Neely","name_href" => "af/population-of-neely","count" => "30 058","real_id" =>29,),
"30"=>array("name_ru"=>"Сари-Пуль","name_en"=>"Sar-e Pol","name_href" => "af/population-of-sar-e-pol","count" => "29 500","real_id" =>30,),
"31"=>array("name_ru"=>"Шинданд","name_en"=>"Shindand","name_href" => "af/population-of-shindand","count" => "29 264","real_id" =>31,),
"32"=>array("name_ru"=>"Андхой","name_en"=>"Andkhoy","name_href" => "af/population-of-andkhoy","count" => "26 700","real_id" =>32,),
"33"=>array("name_ru"=>"Базарак","name_en"=>"Bazarak","name_href" => "af/population-of-bazarak","count" => "24 723","real_id" =>33,),
"34"=>array("name_ru"=>"Муса-Кала","name_en"=>"Musa Qala","name_href" => "af/population-of-musa-qala","count" => "20 000","real_id" =>34,),
"35"=>array("name_ru"=>"Ат-Кхвейджх","name_en"=>"At-Khvajeh","name_href" => "af/population-of-at-khvajeh","count" => "18 623","real_id" =>35,),
"36"=>array("name_ru"=>"Мукур","name_en"=>"Mukur","name_href" => "af/population-of-mukur","count" => "16 522","real_id" =>36,),
"37"=>array("name_ru"=>"Джабаль -ус- Сарадж","name_en"=>"Jabal -us - Sarraj","name_href" => "af/population-of-jabal-us-sarraj","count" => "16 000","real_id" =>37,),
"38"=>array("name_ru"=>"Ачин","name_en"=>"Acin","name_href" => "af/population-of-acin","count" => "15 098","real_id" =>38,),
"39"=>array("name_ru"=>"Пули-Алам","name_en"=>"Puli-Alam","name_href" => "af/population-of-puli-alam","count" => "13 247","real_id" =>39,),
"40"=>array("name_ru"=>"Калайи Нау","name_en"=>"Qala i Naw","name_href" => "af/population-of-qala-i-naw","count" => "12 300","real_id" =>40,),
"41"=>array("name_ru"=>"Ишкашим","name_en"=>"Ishkashim","name_href" => "af/population-of-ishkashim","count" => "12001","real_id" =>41,),
"42"=>array("name_ru"=>"Хост","name_en"=>"Khost","name_href" => "af/population-of-khost","count" => "11 200","real_id" =>42,),
"43"=>array("name_ru"=>"Калат","name_en"=>"Qalat","name_href" => "af/population-of-qalat","count" => "9 900","real_id" =>43,),
"44"=>array("name_ru"=>"Айбак","name_en"=>"Samangan","name_href" => "af/population-of-samangan","count" => "9 000","real_id" =>44,),
"45"=>array("name_ru"=>"Махмудраки","name_en"=>"Mahmud-i-Raqi","name_href" => "af/population-of-mahmud-i-raqi","count" => "7 407","real_id" =>45,),
"46"=>array("name_ru"=>"Мехтарлам","name_en"=>"Mihtarlam","name_href" => "af/population-of-mihtarlam","count" => "4 250","real_id" =>46,),
"47"=>array("name_ru"=>"Анар-Даррех","name_en"=>"Anar Dara","name_href" => "af/population-of-anar-dara","count" => "3 400","real_id" =>47,),
"48"=>array("name_ru"=>"Парун","name_en"=>"Parun","name_href" => "af/population-of-parun","count" => "1 000","real_id" =>48,),
"49"=>array("name_ru"=>"Кабул","name_en"=>"Kabul","name_href" => "af/population-of-kabul","count" => "3 071 400","real_id" =>49,),
"50"=>array("name_ru"=>"Мазари-Шариф","name_en"=>"Mazar-i-Sharif","name_href" => "af/population-of-mazar-i-sharif","count" => "693 000","real_id" =>50,),
"51"=>array("name_ru"=>"Асмар","name_en"=>"Asmara","name_href" => "af/population-of-asmara","count" => "649 000","real_id" =>51,),
"52"=>array("name_ru"=>"Кандагар","name_en"=>"Kandahar","name_href" => "af/population-of-kandahar","count" => "491 500","real_id" =>52,),
"53"=>array("name_ru"=>"Герат","name_en"=>"Herat","name_href" => "af/population-of-herat","count" => "436 300","real_id" =>53,)
);

?>