<?php
//Азербайджан 67 
$libaz = array ( 
"1"=>array("name_ru"=>"Баку","name_en"=>"Baku","name_href" => "az/population-of-baku","count" => "2 092 000","real_id" =>1,),
"2"=>array("name_ru"=>"Гянджа","name_en"=>"Ganja","name_href" => "az/population-of-ganja","count" => "315 100","real_id" =>2,),
"3"=>array("name_ru"=>"Сумгайыт ","name_en"=>"Sumqayit","name_href" => "az/population-of-sumqayit","count" => "280 100","real_id" =>3,),
"4"=>array("name_ru"=>"Мингечевир","name_en"=>"Mingachevir","name_href" => "az/population-of-mingachevir","count" => "98 100","real_id" =>4,),
"5"=>array("name_ru"=>"Нахчыван","name_en"=>"Nakhchivan","name_href" => "az/population-of-nakhchivan","count" => "72 100","real_id" =>5,),
"6"=>array("name_ru"=>"Евлах","name_en"=>"Yevlakh","name_href" => "az/population-of-yevlakh","count" => "58 100","real_id" =>6,),
"7"=>array("name_ru"=>"Ханкенди","name_en"=>"Stepanakert","name_href" => "az/population-of-stepanakert","count" => "53 400","real_id" =>7,),
"8"=>array("name_ru"=>"Ленкорань","name_en"=>"Lankaran","name_href" => "az/population-of-lankaran","count" => "50 100","real_id" =>8,),
"9"=>array("name_ru"=>"Джалилабад","name_en"=>"Jalilabad","name_href" => "az/population-of-jalilabad","count" => "43 000","real_id" =>9,),
"10"=>array("name_ru"=>"Агджабеди","name_en"=>"Agcabadi","name_href" => "az/population-of-agcabadi","count" => "39 100","real_id" =>10,),
"11"=>array("name_ru"=>"Хачмаз","name_en"=>"Khachmaz","name_href" => "az/population-of-khachmaz","count" => "39 100","real_id" =>11,),
"12"=>array("name_ru"=>"Барда","name_en"=>"Bard","name_href" => "az/population-of-bard","count" => "38 100","real_id" =>12,),
"13"=>array("name_ru"=>"Салян ","name_en"=>"Salyan","name_href" => "az/population-of-salyan","count" => "36 100","real_id" =>13,),
"14"=>array("name_ru"=>"Гёйчай ","name_en"=>"Goychay ","name_href" => "az/population-of-goychay","count" => "35 100","real_id" =>14,),
"15"=>array("name_ru"=>"Имишли","name_en"=>"Imishli","name_href" => "az/population-of-imishli","count" => "33 000","real_id" =>15,),
"16"=>array("name_ru"=>"Агдаш","name_en"=>"Agdash","name_href" => "az/population-of-agdash","count" => "29 400","real_id" =>16,),
"17"=>array("name_ru"=>"Сабирабад","name_en"=>"Sabirabad","name_href" => "az/population-of-sabirabad","count" => "28 100","real_id" =>17,),
"18"=>array("name_ru"=>"Аджигабул","name_en"=>"Qazimammad","name_href" => "az/population-of-qazimammad","count" => "25 100","real_id" =>18,),
"19"=>array("name_ru"=>"Сиазань","name_en"=>"Siyəzən","name_href" => "az/population-of-siyəzən","count" => "24 100","real_id" =>19,),
"20"=>array("name_ru"=>"Губа (Куба)","name_en"=>"Quba","name_href" => "az/population-of-quba","count" => "23 100","real_id" =>20,),
"21"=>array("name_ru"=>"Газах (Казах)","name_en"=>"Gases ","name_href" => "az/population-of-gases","count" => "21 000","real_id" =>21,),
"22"=>array("name_ru"=>"Ахсу","name_en"=>"Ascha","name_href" => "az/population-of-ascha","count" => "20 100","real_id" =>22,),
"23"=>array("name_ru"=>"Билясувар","name_en"=>"Bilasuvar","name_href" => "az/population-of-bilasuvar","count" => "20 100","real_id" =>23,),
"24"=>array("name_ru"=>"Загатала","name_en"=>"Zagatala ","name_href" => "az/population-of-zagatala","count" => "20 100","real_id" =>24,),
"25"=>array("name_ru"=>"Нефтечала","name_en"=>"Neftçala","name_href" => "az/population-of-neftçala","count" => "20 100","real_id" =>25,),
"26"=>array("name_ru"=>"Тертер","name_en"=>"Tartar","name_href" => "az/population-of-tartar","count" => "19 100","real_id" =>26,),
"27"=>array("name_ru"=>"Кюрдамир","name_en"=>"Kürdəmir","name_href" => "az/population-of-kürdəmir","count" => "18 100","real_id" =>27,),
"28"=>array("name_ru"=>"Гёйгёль","name_en"=>"Goygol","name_href" => "az/population-of-goygol","count" => "17 100","real_id" =>28,),
"29"=>array("name_ru"=>"Саатлы","name_en"=>"Saatlı","name_href" => "az/population-of-saatlı","count" => "17 100","real_id" =>29,),
"30"=>array("name_ru"=>"Физули","name_en"=>"Füzuli","name_href" => "az/population-of-füzuli","count" => "17 100","real_id" =>30,),
"31"=>array("name_ru"=>"Уджары","name_en"=>"Ucar","name_href" => "az/population-of-ucar","count" => "17 000","real_id" =>31,),
"32"=>array("name_ru"=>"Астара","name_en"=>"Astara","name_href" => "az/population-of-astara","count" => "16 100","real_id" =>32,),
"33"=>array("name_ru"=>"Гусар ","name_en"=>"Qusar","name_href" => "az/population-of-qusar","count" => "16 100","real_id" =>33,),
"34"=>array("name_ru"=>"Бейлаган","name_en"=>"Beylagan","name_href" => "az/population-of-beylagan","count" => "15 100","real_id" =>34,),
"35"=>array("name_ru"=>"Исмаиллы","name_en"=>"Ismayilli","name_href" => "az/population-of-ismayilli","count" => "15 100","real_id" =>35,),
"36"=>array("name_ru"=>"Худат","name_en"=>"Khudat","name_href" => "az/population-of-khudat","count" => "15 100","real_id" =>36,),
"37"=>array("name_ru"=>"Говлар","name_en"=>"Govlar","name_href" => "az/population-of-govlar","count" => "14 100","real_id" =>37,),
"38"=>array("name_ru"=>"Гёйтепе","name_en"=>"Goytapa","name_href" => "az/population-of-goytapa","count" => "13 100","real_id" =>38,),
"39"=>array("name_ru"=>"Тауз","name_en"=>"Tovuz","name_href" => "az/population-of-tovuz","count" => "13 100","real_id" =>39,),
"40"=>array("name_ru"=>"Агстафа ","name_en"=>"Ağstafa ","name_href" => "az/population-of-ağstafa","count" => "12 100","real_id" =>40,),
"41"=>array("name_ru"=>"Габала","name_en"=>"Gabala","name_href" => "az/population-of-gabala","count" => "12 100","real_id" =>41,),
"42"=>array("name_ru"=>"Джульфа","name_en"=>"Julfa","name_href" => "az/population-of-julfa","count" => "12 100","real_id" =>42,),
"43"=>array("name_ru"=>"Гах (Кахи)","name_en"=>"Gah ","name_href" => "az/population-of-gah","count" => "12 100","real_id" =>43,),
"44"=>array("name_ru"=>"Дашкесан","name_en"=>"Dashkesan","name_href" => "az/population-of-dashkesan","count" => "10 100","real_id" =>44,),
"45"=>array("name_ru"=>"Зардоб","name_en"=>"Zardab","name_href" => "az/population-of-zardab","count" => "10 100","real_id" =>45,),
"46"=>array("name_ru"=>"Кедабек","name_en"=>"Gǝdǝbǝy","name_href" => "az/population-of-gǝdǝbǝy","count" => "10 100","real_id" =>46,),
"47"=>array("name_ru"=>"Лиман","name_en"=>"Liman","name_href" => "az/population-of-liman","count" => "10 100","real_id" =>47,),
"48"=>array("name_ru"=>"Ордубад","name_en"=>"Ordubad","name_href" => "az/population-of-ordubad","count" => "10 100","real_id" =>48,),
"49"=>array("name_ru"=>"Балакен","name_en"=>"Balakǝn","name_href" => "az/population-of-balakǝn","count" => "9 100","real_id" =>49,),
"50"=>array("name_ru"=>"Масаллы","name_en"=>"Masallı","name_href" => "az/population-of-masallı","count" => "9 100","real_id" =>50,),
"51"=>array("name_ru"=>"Самух","name_en"=>"Nəbiağalı","name_href" => "az/population-of-nəbiağalı","count" => "9 100","real_id" =>51,),
"52"=>array("name_ru"=>"Гобустан","name_en"=>"Gobustan","name_href" => "az/population-of-gobustan","count" => "7 100","real_id" =>52,),
"53"=>array("name_ru"=>"Горадиз","name_en"=>"Horadiz","name_href" => "az/population-of-horadiz","count" => "7 100","real_id" =>53,),
"54"=>array("name_ru"=>"Лерик","name_en"=>"Lerik","name_href" => "az/population-of-lerik","count" => "7 100","real_id" =>54,),
"55"=>array("name_ru"=>"Нафталан","name_en"=>"Naftalan","name_href" => "az/population-of-naftalan","count" => "7 100","real_id" =>55,),
"56"=>array("name_ru"=>"Огуз","name_en"=>"Oghuz","name_href" => "az/population-of-oghuz","count" => "7 000","real_id" =>56,),
"57"=>array("name_ru"=>"Джебраил","name_en"=>"Cabrayil","name_href" => "az/population-of-cabrayil","count" => "6 300","real_id" =>57,),
"58"=>array("name_ru"=>"Геранбой","name_en"=>"Goranboy","name_href" => "az/population-of-goranboy","count" => "6 100","real_id" =>58,),
"59"=>array("name_ru"=>"Ходжавенд","name_en"=>"Khojavend","name_href" => "az/population-of-khojavend","count" => "5 800","real_id" =>59,),
"60"=>array("name_ru"=>"Далимамедли","name_en"=>"Dalimamedli","name_href" => "az/population-of-dalimamedli","count" => "5 100","real_id" =>60,),
"61"=>array("name_ru"=>"Агдере","name_en"=>"Agder","name_href" => "az/population-of-agder","count" => "5 000","real_id" =>61,),
"62"=>array("name_ru"=>"Лачин","name_en"=>"Lachin","name_href" => "az/population-of-lachin","count" => "2 190","real_id" =>62,),
"63"=>array("name_ru"=>"Ходжалы","name_en"=>"Khojaly","name_href" => "az/population-of-khojaly","count" => "1 021","real_id" =>63,),
"64"=>array("name_ru"=>"Кельбаджар","name_en"=>"Kalbajar","name_href" => "az/population-of-kalbajar","count" => "500","real_id" =>64,),
"65"=>array("name_ru"=>"Зангелан","name_en"=>"Zangelan","name_href" => "az/population-of-zangelan","count" => "383","real_id" =>65,),
"66"=>array("name_ru"=>"Агдам","name_en"=>"Agdam","name_href" => "az/population-of-agdam","count" => "360","real_id" =>66,),
"67"=>array("name_ru"=>"Губадлы ","name_en"=>"Qubadlı","name_href" => "az/population-of-qubadli","count" => "73","real_id" =>67,),
"68"=>array("name_ru"=>"Баку","name_en"=>"Baku","name_href" => "az/population-of-baku","count" => "2 092 000","real_id" =>68,),
"69"=>array("name_ru"=>"Гянджа","name_en"=>"Ganja","name_href" => "az/population-of-ganja","count" => "315 100","real_id" =>69,),
"70"=>array("name_ru"=>"Сумгайыт ","name_en"=>"Sumqayit","name_href" => "az/population-of-sumqayit","count" => "280 100","real_id" =>70,),
"71"=>array("name_ru"=>"Мингечевир","name_en"=>"Mingachevir","name_href" => "az/population-of-mingachevir","count" => "98 100","real_id" =>71,),
"72"=>array("name_ru"=>"Нахчыван","name_en"=>"Nakhchivan","name_href" => "az/population-of-nakhchivan","count" => "72 100","real_id" =>72,)
);

?>