<?php
//Австралия 86 
$libau = array ( 
"1"=>array("name_ru"=>"Сидней","name_en"=>"Sydney","name_href" => "au/population-of-sydney","count" => "4 575 532","real_id" =>1,),
"2"=>array("name_ru"=>"Мельбурн","name_en"=>"Melbourne","name_href" => "au/population-of-melbourne","count" => "4 077 036","real_id" =>2,),
"3"=>array("name_ru"=>"Брисбен","name_en"=>"Brisbane","name_href" => "au/population-of-brisbane","count" => "2 043 185","real_id" =>3,),
"4"=>array("name_ru"=>"Перт","name_en"=>"Perth","name_href" => "au/population-of-perth","count" => "1 696 065","real_id" =>4,),
"5"=>array("name_ru"=>"Аделаида","name_en"=>"Adelaide","name_href" => "au/population-of-adelaide","count" => "1 203 873","real_id" =>5,),
"6"=>array("name_ru"=>"Голд-Кост","name_en"=>"Gold Coast","name_href" => "au/population-of-gold-coast","count" => "591 473","real_id" =>6,),
"7"=>array("name_ru"=>"Вуллонгонг","name_en"=>"Wollongong","name_href" => "au/population-of-wollongong","count" => "292 190","real_id" =>7,),
"8"=>array("name_ru"=>"Ньюкасл","name_en"=>"Newcastle","name_href" => "au/population-of-newcastle","count" => "288 732","real_id" =>8,),
"9"=>array("name_ru"=>"Саншайн-Кост","name_en"=>"Sunshine Coast","name_href" => "au/population-of-sunshine-coast","count" => "251 081","real_id" =>9,),
"10"=>array("name_ru"=>"Хобарт","name_en"=>"Hobart","name_href" => "au/population-of-hobart","count" => "214 705","real_id" =>10,),
"11"=>array("name_ru"=>"Лейк-Маккуори","name_en"=>"Lake Macquarie","name_href" => "au/population-of-lake-macquarie","count" => "199 277","real_id" =>11,),
"12"=>array("name_ru"=>"Таунсвилл","name_en"=>"Townsville","name_href" => "au/population-of-townsville","count" => "185 768","real_id" =>12,),
"13"=>array("name_ru"=>"Ипсуич","name_en"=>"Ipswich","name_href" => "au/population-of-ipswich","count" => "168 131","real_id" =>13,),
"14"=>array("name_ru"=>"Джилонг","name_en"=>"Geelong","name_href" => "au/population-of-geelong","count" => "160 991","real_id" =>14,),
"15"=>array("name_ru"=>"Госфорд","name_en"=>"Gosford","name_href" => "au/population-of-gosford","count" => "155 271","real_id" =>15,),
"16"=>array("name_ru"=>"Кэрнс","name_en"=>"Cairns","name_href" => "au/population-of-cairns","count" => "150 920","real_id" =>16,),
"17"=>array("name_ru"=>"Тувумба","name_en"=>"Toowoomba","name_href" => "au/population-of-toowoomba","count" => "128 600","real_id" =>17,),
"18"=>array("name_ru"=>"Дарвин","name_en"=>"Darwin","name_href" => "au/population-of-darwin","count" => "124 800","real_id" =>18,),
"19"=>array("name_ru"=>"Лонсестон","name_en"=>"Launceston","name_href" => "au/population-of-launceston","count" => "106 153","real_id" =>19,),
"20"=>array("name_ru"=>"Балларат","name_en"=>"Ballarat","name_href" => "au/population-of-ballarat","count" => "96 097","real_id" =>20,),
"21"=>array("name_ru"=>"Бендиго","name_en"=>"Bendigo","name_href" => "au/population-of-bendigo","count" => "91 713","real_id" =>21,),
"22"=>array("name_ru"=>"Манджера","name_en"=>"Mandurah","name_href" => "au/population-of-mandurah","count" => "85 814","real_id" =>22,),
"23"=>array("name_ru"=>"Маккай","name_en"=>"Mackay","name_href" => "au/population-of-mackay","count" => "85 700","real_id" =>23,),
"24"=>array("name_ru"=>"Рокгемптон","name_en"=>"Rockhampton","name_href" => "au/population-of-rockhampton","count" => "76 729","real_id" =>24,),
"25"=>array("name_ru"=>"Латроб-Сити","name_en"=>"La Trobe","name_href" => "au/population-of-la-trobe","count" => "75 259","real_id" =>25,),
"26"=>array("name_ru"=>"Бандаберг","name_en"=>"Bundaberg","name_href" => "au/population-of-bundaberg","count" => "71 000","real_id" =>26,),
"27"=>array("name_ru"=>"Банбери","name_en"=>"Bunbury","name_href" => "au/population-of-bunbury","count" => "68 248","real_id" =>27,),
"28"=>array("name_ru"=>"Мейтленд","name_en"=>"Maitland","name_href" => "au/population-of-maitland","count" => "61 431","real_id" =>28,),
"29"=>array("name_ru"=>"Харви-Бей","name_en"=>"Hervey Bay","name_href" => "au/population-of-hervey-bay","count" => "60 000","real_id" =>29,),
"30"=>array("name_ru"=>"Олбери","name_en"=>"Albury","name_href" => "au/population-of-albury","count" => "53 507","real_id" =>30,),
"31"=>array("name_ru"=>"Тамуэрт ","name_en"=>"Tamworth","name_href" => "au/population-of-tamworth","count" => "47 595","real_id" =>31,),
"32"=>array("name_ru"=>"Уогга-Уогга","name_en"=>"Wagga Wagga","name_href" => "au/population-of-wagga-wagga","count" => "46 735","real_id" =>32,),
"33"=>array("name_ru"=>"Порт-Маккуори ","name_en"=>"Port Macquarie","name_href" => "au/population-of-port-macquarie","count" => "44 313","real_id" =>33,),
"34"=>array("name_ru"=>"Калаундра","name_en"=>"Caloundra","name_href" => "au/population-of-caloundra","count" => "41 293","real_id" =>34,),
"35"=>array("name_ru"=>"Ориндж","name_en"=>"Orange","name_href" => "au/population-of-orange","count" => "39 329","real_id" =>35,),
"36"=>array("name_ru"=>"Шеппартон","name_en"=>"Shepparton","name_href" => "au/population-of-shepparton","count" => "38 773","real_id" =>36,),
"37"=>array("name_ru"=>"Даббо","name_en"=>"Dubbo","name_href" => "au/population-of-dubbo","count" => "38 037","real_id" =>37,),
"38"=>array("name_ru"=>"Джералдтон","name_en"=>"Geraldton","name_href" => "au/population-of-geraldton","count" => "36 958","real_id" =>38,),
"39"=>array("name_ru"=>"Наура","name_en"=>"Nowra","name_href" => "au/population-of-nowra","count" => "34 479","real_id" =>39,),
"40"=>array("name_ru"=>"Батерст","name_en"=>"Bathurst","name_href" => "au/population-of-bathurst","count" => "34 303","real_id" =>40,),
"41"=>array("name_ru"=>"Калгурли","name_en"=>"Kalgoorlie","name_href" => "au/population-of-kalgoorlie","count" => "32 390","real_id" =>41,),
"42"=>array("name_ru"=>"Лисмор","name_en"=>"Lismore","name_href" => "au/population-of-lismore","count" => "30 086","real_id" =>42,),
"43"=>array("name_ru"=>"Милдьюра","name_en"=>"Mildura","name_href" => "au/population-of-mildura","count" => "30 016","real_id" =>43,),
"44"=>array("name_ru"=>"Уодонга","name_en"=>"Wodonga","name_href" => "au/population-of-wodonga","count" => "29 710","real_id" =>44,),
"45"=>array("name_ru"=>"Гладстон","name_en"=>"Gladstone","name_href" => "au/population-of-gladstone","count" => "28 808","real_id" =>45,),
"46"=>array("name_ru"=>"Алис-Спрингс","name_en"=>"Alice Springs","name_href" => "au/population-of-alice-springs","count" => "27 481","real_id" =>46,),
"47"=>array("name_ru"=>"Коффс-Харбор ","name_en"=>"Coffs Harbour","name_href" => "au/population-of-coffs-harbour","count" => "26 353","real_id" =>47,),
"48"=>array("name_ru"=>"Куинбиан","name_en"=>"Queanbeyan","name_href" => "au/population-of-queanbeyan","count" => "26 353","real_id" =>48,),
"49"=>array("name_ru"=>"Албани","name_en"=>"Albany","name_href" => "au/population-of-albany","count" => "25 196","real_id" =>49,),
"50"=>array("name_ru"=>"Палмерстон ","name_en"=>"Palmerston","name_href" => "au/population-of-palmerston","count" => "23 614","real_id" =>50,),
"51"=>array("name_ru"=>"Маунт-Гамбир","name_en"=>"Mount Gambier","name_href" => "au/population-of-mount-gambier","count" => "23 494","real_id" =>51,),
"52"=>array("name_ru"=>"Маунт-Айза","name_en"=>"Mount Isa","name_href" => "au/population-of-mount-isa","count" => "23 000","real_id" =>52,),
"53"=>array("name_ru"=>"Уайалла","name_en"=>"Whyalla","name_href" => "au/population-of-whyalla","count" => "22 612","real_id" =>53,),
"54"=>array("name_ru"=>"Девонпорт","name_en"=>"Devonport","name_href" => "au/population-of-devonport","count" => "22 315","real_id" =>54,),
"55"=>array("name_ru"=>"Мэриборо","name_en"=>"Maryborough","name_href" => "au/population-of-maryborough","count" => "21 501","real_id" =>55,),
"56"=>array("name_ru"=>"Гоулберн","name_en"=>"Goulburn","name_href" => "au/population-of-goulburn","count" => "20 127","real_id" =>56,),
"57"=>array("name_ru"=>"Армидейл","name_en"=>"Armidale","name_href" => "au/population-of-armidale","count" => "19 485","real_id" =>57,),
"58"=>array("name_ru"=>"Берни","name_en"=>"Burnie","name_href" => "au/population-of-burnie","count" => "19 160","real_id" =>58,),
"59"=>array("name_ru"=>"Брокен-Хилл","name_en"=>"Broken Hill","name_href" => "au/population-of-broken-hill","count" => "18 854","real_id" =>59,),
"60"=>array("name_ru"=>"Сеснок ","name_en"=>"Cessnock","name_href" => "au/population-of-cessnock","count" => "18 316","real_id" =>60,),
"61"=>array("name_ru"=>"Туид-Хедс ","name_en"=>"Tweed Heads","name_href" => "au/population-of-tweed-heads","count" => "18 316","real_id" =>61,),
"62"=>array("name_ru"=>"Графтон ","name_en"=>"Grafton","name_href" => "au/population-of-grafton","count" => "17 501","real_id" =>62,),
"63"=>array("name_ru"=>"Гриффит","name_en"=>"Griffith","name_href" => "au/population-of-griffith","count" => "17 501","real_id" =>63,),
"64"=>array("name_ru"=>"Марри-Бридж","name_en"=>"Murray Bridge","name_href" => "au/population-of-murray-bridge","count" => "14 048","real_id" =>64,),
"65"=>array("name_ru"=>"Порт-Огаста","name_en"=>"Port Augusta","name_href" => "au/population-of-port-augusta","count" => "13 257","real_id" =>65,),
"66"=>array("name_ru"=>"Порт-Пири","name_en"=>"Port Pirie","name_href" => "au/population-of-port-pirie","count" => "13 206","real_id" =>66,),
"67"=>array("name_ru"=>"Порт-Линкольн","name_en"=>"Port Lincoln","name_href" => "au/population-of-port-lincoln","count" => "13 044","real_id" =>67,),
"68"=>array("name_ru"=>"Порт-Хедленд","name_en"=>"Port Hedland","name_href" => "au/population-of-port-hedland","count" => "11 557","real_id" =>68,),
"69"=>array("name_ru"=>"Брум","name_en"=>"Broome","name_href" => "au/population-of-broome","count" => "11 547","real_id" =>69,),
"70"=>array("name_ru"=>"Гимпи","name_en"=>"Gympie","name_href" => "au/population-of-gympie","count" => "10 933","real_id" =>70,),
"71"=>array("name_ru"=>"Виктор-Харбор","name_en"=>"Victor Harbor","name_href" => "au/population-of-victor-harbor","count" => "10 380","real_id" =>71,),
"72"=>array("name_ru"=>"Намбор","name_en"=>"Nambour","name_href" => "au/population-of-nambour","count" => "9 774","real_id" =>72,),
"73"=>array("name_ru"=>"Суон-Хилл","name_en"=>"Swan Hill","name_href" => "au/population-of-swan-hill","count" => "9 684","real_id" =>73,),
"74"=>array("name_ru"=>"Эсперанс","name_en"=>"Esperance","name_href" => "au/population-of-esperance","count" => "9 536","real_id" =>74,),
"75"=>array("name_ru"=>"Редклифф","name_en"=>"Redcliffe","name_href" => "au/population-of-redcliffe","count" => "8 981","real_id" =>75,),
"76"=>array("name_ru"=>"Чартерс-Тауэрс","name_en"=>"Charters Towers","name_href" => "au/population-of-charters-towers","count" => "7 979","real_id" =>76,),
"77"=>array("name_ru"=>"Катумба","name_en"=>"Katoomba","name_href" => "au/population-of-katoomba","count" => "7 623","real_id" =>77,),
"78"=>array("name_ru"=>"Карнарвон","name_en"=>"Carnarvon","name_href" => "au/population-of-carnarvon","count" => "5 283","real_id" =>78,),
"79"=>array("name_ru"=>"Уэйпа","name_en"=>"Weipa","name_href" => "au/population-of-weipa","count" => "3 291","real_id" =>79,),
"80"=>array("name_ru"=>"Теннант-Крик","name_en"=>"Tennant Creek","name_href" => "au/population-of-tennant-creek","count" => "3 185","real_id" =>80,),
"81"=>array("name_ru"=>"Вайонг","name_en"=>"Wyong","name_href" => "au/population-of-wyong","count" => "3 116","real_id" =>81,),
"82"=>array("name_ru"=>"Бродфорд","name_en"=>"Broadford","name_href" => "au/population-of-broadford","count" => "3 054","real_id" =>82,),
"83"=>array("name_ru"=>"Том-Прайс","name_en"=>"Tom Price","name_href" => "au/population-of-tom-price","count" => "2 721","real_id" =>83,),
"84"=>array("name_ru"=>"Микатарра","name_en"=>"Meekatharra","name_href" => "au/population-of-meekatharra","count" => "798","real_id" =>84,),
"85"=>array("name_ru"=>"Уилуна","name_en"=>"Wiluna","name_href" => "au/population-of-wiluna","count" => "681","real_id" =>85,),
"86"=>array("name_ru"=>"Леонора","name_en"=>"Leonora","name_href" => "au/population-of-leonora","count" => "401","real_id" =>86,),
"87"=>array("name_ru"=>"Сидней","name_en"=>"Sydney","name_href" => "au/population-of-sydney","count" => "4 575 532","real_id" =>87,),
"88"=>array("name_ru"=>"Мельбурн","name_en"=>"Melbourne","name_href" => "au/population-of-melbourne","count" => "4 077 036","real_id" =>88,),
"89"=>array("name_ru"=>"Брисбен","name_en"=>"Brisbane","name_href" => "au/population-of-brisbane","count" => "2 043 185","real_id" =>89,),
"90"=>array("name_ru"=>"Перт","name_en"=>"Perth","name_href" => "au/population-of-perth","count" => "1 696 065","real_id" =>90,),
"91"=>array("name_ru"=>"Аделаида","name_en"=>"Adelaide","name_href" => "au/population-of-adelaide","count" => "1 203 873","real_id" =>91,)
);

?>