<?php
//Армения 59 
$libam = array ( 
"1"=>array("name_ru"=>"Ереван","name_en"=>"Yerevan","name_href" => "am/population-of-yerevan","count" => "1 068 300","real_id" =>1,),
"2"=>array("name_ru"=>"Армавир","name_en"=>"Armavir ","name_href" => "am/population-of-armavir","count" => "265 770","real_id" =>2,),
"3"=>array("name_ru"=>"Арарат","name_en"=>"Ararat ","name_href" => "am/population-of-ararat","count" => "260 367","real_id" =>3,),
"4"=>array("name_ru"=>"Котайк","name_en"=>"Kotajko","name_href" => "am/population-of-kotajko","count" => "254 397","real_id" =>4,),
"5"=>array("name_ru"=>"Ширак","name_en"=>"Shirak ","name_href" => "am/population-of-shirak","count" => "251 941","real_id" =>5,),
"6"=>array("name_ru"=>"Лори","name_en"=>"Lori ","name_href" => "am/population-of-lori","count" => "235 537","real_id" =>6,),
"7"=>array("name_ru"=>"Гегаркуник","name_en"=>"Gegharkunik ","name_href" => "am/population-of-gegharkunik","count" => "235 075","real_id" =>7,),
"8"=>array("name_ru"=>"Сюник","name_en"=>"Syunik ","name_href" => "am/population-of-syunik","count" => "141 771","real_id" =>8,),
"9"=>array("name_ru"=>"Арагацотн","name_en"=>"Aragatsotn ","name_href" => "am/population-of-aragatsotn","count" => "132 925","real_id" =>9,),
"10"=>array("name_ru"=>"Тавуш","name_en"=>"Tavush ","name_href" => "am/population-of-tavush","count" => "128 609","real_id" =>10,),
"11"=>array("name_ru"=>"Гюмри","name_en"=>"Gyumri","name_href" => "am/population-of-gyumri","count" => "119 900","real_id" =>11,),
"12"=>array("name_ru"=>"Ванадзор","name_en"=>"Vanadzor","name_href" => "am/population-of-vanadzor","count" => "84 300","real_id" =>12,),
"13"=>array("name_ru"=>"Вайоц Дзор","name_en"=>"Vayots Dzor","name_href" => "am/population-of-vayots-dzor","count" => "52 324","real_id" =>13,),
"14"=>array("name_ru"=>"Вагаршапат","name_en"=>"Vagharshapat","name_href" => "am/population-of-vagharshapat","count" => "46 800","real_id" =>14,),
"15"=>array("name_ru"=>"Абовян","name_en"=>"Abovyan","name_href" => "am/population-of-abovyan","count" => "44 000","real_id" =>15,),
"16"=>array("name_ru"=>"Раздан","name_en"=>"Hrazdan","name_href" => "am/population-of-hrazdan","count" => "41 800","real_id" =>16,),
"17"=>array("name_ru"=>"Капан","name_en"=>"Kapan","name_href" => "am/population-of-kapan","count" => "34 857","real_id" =>17,),
"18"=>array("name_ru"=>"Армавир","name_en"=>"Armavir","name_href" => "am/population-of-armavir","count" => "29 300","real_id" =>18,),
"19"=>array("name_ru"=>"Чаренцаван","name_en"=>"Charentsavan","name_href" => "am/population-of-charentsavan","count" => "25 039","real_id" =>19,),
"20"=>array("name_ru"=>"Степанаван","name_en"=>"Stepanavan","name_href" => "am/population-of-stepanavan","count" => "23 782","real_id" =>20,),
"21"=>array("name_ru"=>"Арташат","name_en"=>"Artashat","name_href" => "am/population-of-artashat","count" => "22 000","real_id" =>21,),
"22"=>array("name_ru"=>"Горис","name_en"=>"Goris","name_href" => "am/population-of-goris","count" => "21 932","real_id" =>22,),
"23"=>array("name_ru"=>"Иджеван","name_en"=>"Ijevan","name_href" => "am/population-of-ijevan","count" => "20 509","real_id" =>23,),
"24"=>array("name_ru"=>"Масис","name_en"=>"Masis","name_href" => "am/population-of-masis","count" => "20 500","real_id" =>24,),
"25"=>array("name_ru"=>"Арарат","name_en"=>"Ararat","name_href" => "am/population-of-ararat","count" => "20 300","real_id" =>25,),
"26"=>array("name_ru"=>"Гавар","name_en"=>"Gavar","name_href" => "am/population-of-gavar","count" => "20 300","real_id" =>26,),
"27"=>array("name_ru"=>"Севан","name_en"=>"Sevan","name_href" => "am/population-of-sevan","count" => "19 300","real_id" =>27,),
"28"=>array("name_ru"=>"Аштарак","name_en"=>"Ashtarak","name_href" => "am/population-of-ashtarak","count" => "18 700","real_id" =>28,),
"29"=>array("name_ru"=>"Спитак","name_en"=>"Spitak","name_href" => "am/population-of-spitak","count" => "18 237","real_id" =>29,),
"30"=>array("name_ru"=>"Сисиан","name_en"=>"Sisian","name_href" => "am/population-of-sisian","count" => "16 823","real_id" =>30,),
"31"=>array("name_ru"=>"Алаверди","name_en"=>"Alaverdi","name_href" => "am/population-of-alaverdi","count" => "16 600","real_id" =>31,),
"32"=>array("name_ru"=>"Артик","name_en"=>"Artik","name_href" => "am/population-of-artik","count" => "15 985","real_id" =>32,),
"33"=>array("name_ru"=>"Дилижан","name_en"=>"Dilijan","name_href" => "am/population-of-dilijan","count" => "15 656","real_id" =>33,),
"34"=>array("name_ru"=>"Варденис","name_en"=>"Vardenis","name_href" => "am/population-of-vardenis","count" => "12 753","real_id" =>34,),
"35"=>array("name_ru"=>"Мартуни","name_en"=>"Martuni","name_href" => "am/population-of-martuni","count" => "11 987","real_id" =>35,),
"36"=>array("name_ru"=>"Веди","name_en"=>"Vedi","name_href" => "am/population-of-vedi","count" => "11 600","real_id" =>36,),
"37"=>array("name_ru"=>"Егвард","name_en"=>"Yeghvard","name_href" => "am/population-of-yeghvard","count" => "10 566","real_id" =>37,),
"38"=>array("name_ru"=>"Нор Ачин","name_en"=>"Nor Hachen","name_href" => "am/population-of-nor-hachen","count" => "10 198","real_id" =>38,),
"39"=>array("name_ru"=>"Каджаран","name_en"=>"Kajaran","name_href" => "am/population-of-kajaran","count" => "9 475","real_id" =>39,),
"40"=>array("name_ru"=>"Мецамор","name_en"=>"Metsamor","name_href" => "am/population-of-metsamor","count" => "9 200","real_id" =>40,),
"41"=>array("name_ru"=>"Ташир","name_en"=>"Tashir","name_href" => "am/population-of-tashir","count" => "8 700","real_id" =>41,),
"42"=>array("name_ru"=>"Берд","name_en"=>"Berd","name_href" => "am/population-of-berd","count" => "8 561","real_id" =>42,),
"43"=>array("name_ru"=>"Бюрегаван","name_en"=>"Byureghavan","name_href" => "am/population-of-byureghavan","count" => "8 152","real_id" =>43,),
"44"=>array("name_ru"=>"Джермук","name_en"=>"Jermuk","name_href" => "am/population-of-jermuk","count" => "8 013","real_id" =>44,),
"45"=>array("name_ru"=>"Ехегнадзор","name_en"=>"Yeghegnadzor","name_href" => "am/population-of-yeghegnadzor","count" => "7 633","real_id" =>45,),
"46"=>array("name_ru"=>"Апаран","name_en"=>"Aparan","name_href" => "am/population-of-aparan","count" => "6 158","real_id" =>46,),
"47"=>array("name_ru"=>"Ноемберян","name_en"=>"Noyemberyan","name_href" => "am/population-of-noyemberyan","count" => "5 529","real_id" =>47,),
"48"=>array("name_ru"=>"Маралик","name_en"=>"Maralik","name_href" => "am/population-of-maralik","count" => "5 386","real_id" =>48,),
"49"=>array("name_ru"=>"Вайк","name_en"=>"Vayk","name_href" => "am/population-of-vayk","count" => "5 364","real_id" =>49,),
"50"=>array("name_ru"=>"Агарак","name_en"=>"Agarak","name_href" => "am/population-of-agarak","count" => "5 112","real_id" =>50,),
"51"=>array("name_ru"=>"Мегри","name_en"=>"Meghri","name_href" => "am/population-of-meghri","count" => "5 034","real_id" =>51,),
"52"=>array("name_ru"=>"Талин","name_en"=>"Talin","name_href" => "am/population-of-talin","count" => "4 981","real_id" =>52,),
"53"=>array("name_ru"=>"Ахтала","name_en"=>"Akhtala","name_href" => "am/population-of-akhtala","count" => "2 400","real_id" =>53,),
"54"=>array("name_ru"=>"Айрум","name_en"=>"Ayrum","name_href" => "am/population-of-ayrum","count" => "2 389","real_id" =>54,),
"55"=>array("name_ru"=>"Туманян","name_en"=>"Tumanyan","name_href" => "am/population-of-tumanyan","count" => "1 838","real_id" =>55,),
"56"=>array("name_ru"=>"Цахкадзор","name_en"=>"Tsaghkadzor","name_href" => "am/population-of-tsaghkadzor","count" => "1 618","real_id" =>56,),
"57"=>array("name_ru"=>"Чамбарак","name_en"=>"Chambarak","name_href" => "am/population-of-chambarak","count" => "1 115","real_id" =>57,),
"58"=>array("name_ru"=>"Шамлуг","name_en"=>"Shamlugh","name_href" => "am/population-of-shamlugh","count" => "800","real_id" =>58,),
"59"=>array("name_ru"=>"Дастакерт","name_en"=>"Dastakert","name_href" => "am/population-of-dastakert","count" => "303","real_id" =>59,),
"60"=>array("name_ru"=>"Ереван","name_en"=>"Yerevan","name_href" => "am/population-of-yerevan","count" => "1 068 300","real_id" =>60,),
"61"=>array("name_ru"=>"Армавир","name_en"=>"Armavir ","name_href" => "am/population-of-armavir","count" => "265 770","real_id" =>61,),
"62"=>array("name_ru"=>"Арарат","name_en"=>"Ararat ","name_href" => "am/population-of-ararat","count" => "260 367","real_id" =>62,),
"63"=>array("name_ru"=>"Котайк","name_en"=>"Kotajko","name_href" => "am/population-of-kotajko","count" => "254 397","real_id" =>63,),
"64"=>array("name_ru"=>"Ширак","name_en"=>"Shirak ","name_href" => "am/population-of-shirak","count" => "251 941","real_id" =>64,)
);

?>