<?php
//Андорра 45
$libad = array ( 
"1"=>array("name_ru"=>"Андорра-ла-Велья","name_en"=>"Andorra la Vella","name_href" => "ad/population-of-andorra-la-vella","count" => "22615","real_id" =>1,),
"2"=>array("name_ru"=>"Эскальдес-Энгордань","name_en"=>"Escaldes-Engordany","name_href" => "ad/population-of-escaldes-engordany","count" => "14282","real_id" =>2,),
"3"=>array("name_ru"=>"Энкам","name_en"=>"Encamp","name_href" => "ad/population-of-encamp","count" => "12051","real_id" =>3,),
"4"=>array("name_ru"=>"Ла-Масана","name_en"=>"La Massana","name_href" => "ad/population-of-la-massana","count" => "9902","real_id" =>4,),
"5"=>array("name_ru"=>"Сан-Жулиа-де-Лория","name_en"=>"Sant Julià de Lòria","name_href" => "ad/population-of-sant-julià-de-lòria","count" => "9063","real_id" =>5,),
"6"=>array("name_ru"=>"Ордино","name_en"=>"Ordino","name_href" => "ad/population-of-ordino","count" => "4417","real_id" =>6,),
"7"=>array("name_ru"=>"Канильо","name_en"=>"Canillo","name_href" => "ad/population-of-canillo","count" => "4133","real_id" =>7,),
"8"=>array("name_ru"=>"Санта-Колома","name_en"=>"Santa Coloma","name_href" => "ad/population-of-santa-coloma","count" => "2991","real_id" =>8,),
"9"=>array("name_ru"=>"Пас-де-ла-Каса","name_en"=>"El Pas de la Casa","name_href" => "ad/population-of-el-pas-de-la-casa","count" => "2439","real_id" =>9,),
"10"=>array("name_ru"=>"Канильо","name_en"=>"Canillo","name_href" => "ad/population-of-canillo","count" => "1896","real_id" =>10,),
"11"=>array("name_ru"=>"Аринсаль","name_en"=>"Arinsal","name_href" => "ad/population-of-arinsal","count" => "1590","real_id" =>11,),
"12"=>array("name_ru"=>"Лес-Бонс","name_en"=>"Les-Bons","name_href" => "ad/population-of-les-bons","count" => "1082","real_id" =>12,),
"13"=>array("name_ru"=>"Сиспони","name_en"=>"Sispony","name_href" => "ad/population-of-sispony","count" => "1045","real_id" =>13,),
"14"=>array("name_ru"=>"Вила","name_en"=>"Vila","name_href" => "ad/population-of-vila","count" => "1037","real_id" =>14,),
"15"=>array("name_ru"=>"Ашириваль","name_en"=>"Aixirivall","name_href" => "ad/population-of-aixirivall","count" => "821","real_id" =>15,),
"16"=>array("name_ru"=>"Альдоса","name_en"=>" 'Aldosa","name_href" => "ad/population-of-aldosa","count" => "784","real_id" =>16,),
"17"=>array("name_ru"=>"Аньос","name_en"=>"Anyós","name_href" => "ad/population-of-anyós","count" => "749","real_id" =>17,),
"18"=>array("name_ru"=>"Ла-Кортинада","name_en"=>"La Cortinada","name_href" => "ad/population-of-la-cortinada","count" => "743","real_id" =>18,),
"19"=>array("name_ru"=>"Эль-Тартер","name_en"=>"El Tarter","name_href" => "ad/population-of-el-tarter","count" => "722","real_id" =>19,),
"20"=>array("name_ru"=>"Сольдеу","name_en"=>"Soldeu","name_href" => "ad/population-of-soldeu","count" => "588","real_id" =>20,),
"21"=>array("name_ru"=>"Эртс","name_en"=>"ERTS","name_href" => "ad/population-of-erts","count" => "445","real_id" =>21,),
"22"=>array("name_ru"=>"Инклес","name_en"=>"Incles","name_href" => "ad/population-of-incles","count" => "366","real_id" =>22,),
"23"=>array("name_ru"=>"Паль","name_en"=>"PAL","name_href" => "ad/population-of-pal","count" => "236","real_id" =>23,),
"24"=>array("name_ru"=>"Аранс","name_en"=>"Arans","name_href" => "ad/population-of-arans","count" => "231","real_id" =>24,),
"25"=>array("name_ru"=>"л’Альдоза","name_en"=>"I'Aldosa","name_href" => "ad/population-of-i-aldosa","count" => "193","real_id" =>25,),
"26"=>array("name_ru"=>"Аубинья","name_en"=>"Aubigny","name_href" => "ad/population-of-aubigny","count" => "188","real_id" =>26,),
"27"=>array("name_ru"=>"Сорнас","name_en"=>"Sornàs","name_href" => "ad/population-of-sornàs","count" => "184","real_id" =>27,),
"28"=>array("name_ru"=>"Джуберри","name_en"=>"Juberri","name_href" => "ad/population-of-juberri","count" => "182","real_id" =>28,),
"29"=>array("name_ru"=>"Рансоль","name_en"=>"Ransol","name_href" => "ad/population-of-ransol","count" => "169","real_id" =>29,),
"30"=>array("name_ru"=>"Льортс","name_en"=>"Llorts","name_href" => "ad/population-of-llorts","count" => "154","real_id" =>30,),
"31"=>array("name_ru"=>"Эль-Серрат","name_en"=>"El Serrat","name_href" => "ad/population-of-el-serrat","count" => "153","real_id" =>31,),
"32"=>array("name_ru"=>"Фонтанеда","name_en"=>"Fontaneda","name_href" => "ad/population-of-fontaneda","count" => "103","real_id" =>32,),
"33"=>array("name_ru"=>"Ашаваль","name_en"=>"Aixovall","name_href" => "ad/population-of-aixovall","count" => "95","real_id" =>33,),
"34"=>array("name_ru"=>"Сертерс","name_en"=>"Certers","name_href" => "ad/population-of-certers","count" => "73","real_id" =>34,),
"35"=>array("name_ru"=>"Эскас","name_en"=>"Eskas","name_href" => "ad/population-of-eskas","count" => "68","real_id" =>35,),
"36"=>array("name_ru"=>"Эль-Форн","name_en"=>"El Forn","name_href" => "ad/population-of-el-forn","count" => "57","real_id" =>36,),
"37"=>array("name_ru"=>"Меричель","name_en"=>"Maricel","name_href" => "ad/population-of-maricel","count" => "56","real_id" =>37,),
"38"=>array("name_ru"=>"Ансалонга","name_en"=>"Ansalonga","name_href" => "ad/population-of-ansalonga","count" => "55","real_id" =>38,),
"39"=>array("name_ru"=>"Наголь","name_en"=>"Villages","name_href" => "ad/population-of-villages","count" => "54","real_id" =>39,),
"40"=>array("name_ru"=>"Пратс","name_en"=>"Prats","name_href" => "ad/population-of-prats","count" => "48","real_id" =>40,),
"41"=>array("name_ru"=>"Бишесарри","name_en"=>"Bixessarri","name_href" => "ad/population-of-bixessarri","count" => "45","real_id" =>41,),
"42"=>array("name_ru"=>"Сегудет","name_en"=>"Segudet","name_href" => "ad/population-of-segudet","count" => "44","real_id" =>42,),
"43"=>array("name_ru"=>"Эльс-Планс","name_en"=>"Playa ELS Plans","name_href" => "ad/population-of-playa-els-plans","count" => "19","real_id" =>43,),
"44"=>array("name_ru"=>"Эль-Вилар","name_en"=>"El Vilar","name_href" => "ad/population-of-el-vilar","count" => "9","real_id" =>44,),
"45"=>array("name_ru"=>"Льюменерес","name_en"=>"Luminaires","name_href" => "ad/population-of-luminaires","count" => "1","real_id" =>45,),
"46"=>array("name_ru"=>"Андорра-ла-Велья","name_en"=>"Andorra la Vella","name_href" => "ad/population-of-andorra-la-vella","count" => "22615","real_id" =>46,),
"47"=>array("name_ru"=>"Эскальдес-Энгордань","name_en"=>"Escaldes-Engordany","name_href" => "ad/population-of-escaldes-engordany","count" => "14282","real_id" =>47,),
"48"=>array("name_ru"=>"Энкам","name_en"=>"Encamp","name_href" => "ad/population-of-encamp","count" => "12051","real_id" =>48,),
"49"=>array("name_ru"=>"Ла-Масана","name_en"=>"La Massana","name_href" => "ad/population-of-la-massana","count" => "9902","real_id" =>49,),
"50"=>array("name_ru"=>"Сан-Жулиа-де-Лория","name_en"=>"Sant Julià de Lòria","name_href" => "ad/population-of-sant-julià-de-lòria","count" => "9063","real_id" =>50,)
);

?>