<?php
//Австрия 77
$libat = array ( 
"1"=>array("name_ru"=>"Вена","name_en"=>"Vienna ","name_href" => "at/population-of-vienna","count" => "1 765 649","real_id" =>1,),
"2"=>array("name_ru"=>"Грац","name_en"=>"Graz ","name_href" => "at/population-of-graz","count" => "269 997","real_id" =>2,),
"3"=>array("name_ru"=>"Линц","name_en"=>"Linz ","name_href" => "at/population-of-linz","count" => "193 814","real_id" =>3,),
"4"=>array("name_ru"=>"Зальцбург","name_en"=>"Salzburg ","name_href" => "at/population-of-salzburg","count" => "146 631","real_id" =>4,),
"5"=>array("name_ru"=>"Инсбрук","name_en"=>"Innsbruck ","name_href" => "at/population-of-innsbruck","count" => "124 579","real_id" =>5,),
"6"=>array("name_ru"=>"Клагенфурт-ам-Вёртерзе","name_en"=>"Klagenfurt am Wörthersee","name_href" => "at/population-of-klagenfurt-am-wörthersee","count" => "96 640","real_id" =>6,),
"7"=>array("name_ru"=>"Филлах","name_en"=>"Villach ","name_href" => "at/population-of-villach","count" => "60 004","real_id" =>7,),
"8"=>array("name_ru"=>"Вельс","name_en"=>"Wels ","name_href" => "at/population-of-wels","count" => "59 339","real_id" =>8,),
"9"=>array("name_ru"=>"Санкт-Пёльтен","name_en"=>"Sankt Pölten","name_href" => "at/population-of-sankt-pölten","count" => "52 145","real_id" =>9,),
"10"=>array("name_ru"=>"Дорнбирн","name_en"=>"Dornbirn ","name_href" => "at/population-of-dornbirn","count" => "46 883","real_id" =>10,),
"11"=>array("name_ru"=>"Винер-Нойштадт","name_en"=>"Wiener Neustadt","name_href" => "at/population-of-wiener-neustadt","count" => "42 273","real_id" =>11,),
"12"=>array("name_ru"=>"Штайр","name_en"=>"Steyr ","name_href" => "at/population-of-steyr","count" => "38 120","real_id" =>12,),
"13"=>array("name_ru"=>"Фельдкирх","name_en"=>"Feldkirch ","name_href" => "at/population-of-feldkirch","count" => "31 428","real_id" =>13,),
"14"=>array("name_ru"=>"Брегенц","name_en"=>"Bregenz ","name_href" => "at/population-of-bregenz","count" => "28 412","real_id" =>14,),
"15"=>array("name_ru"=>"Леондинг","name_en"=>"Leonding ","name_href" => "at/population-of-leonding","count" => "26 395","real_id" =>15,),
"16"=>array("name_ru"=>"Клостернойбург","name_en"=>"Klosterneuburg ","name_href" => "at/population-of-klosterneuburg","count" => "26 174","real_id" =>16,),
"17"=>array("name_ru"=>"Баден","name_en"=>"Baden ","name_href" => "at/population-of-baden","count" => "25 229","real_id" =>17,),
"18"=>array("name_ru"=>"Вольфсберг","name_en"=>"Wolfsberg ","name_href" => "at/population-of-wolfsberg","count" => "24 993","real_id" =>18,),
"19"=>array("name_ru"=>"Леобен","name_en"=>"Leoben","name_href" => "at/population-of-leoben","count" => "24 466","real_id" =>19,),
"20"=>array("name_ru"=>"Кремс","name_en"=>"Krems an der Donau","name_href" => "at/population-of-krems-an-der-donau","count" => "24 085","real_id" =>20,),
"21"=>array("name_ru"=>"Траун","name_en"=>"Traun ","name_href" => "at/population-of-traun","count" => "23 834","real_id" =>21,),
"22"=>array("name_ru"=>"Амштеттен","name_en"=>"Amstetten ","name_href" => "at/population-of-amstetten","count" => "23 050","real_id" =>22,),
"23"=>array("name_ru"=>"Лустенау","name_en"=>"Lustenau ","name_href" => "at/population-of-lustenau","count" => "21 655","real_id" =>23,),
"24"=>array("name_ru"=>"Капфенберг","name_en"=>"Kapfenberg ","name_href" => "at/population-of-kapfenberg","count" => "21 503","real_id" =>24,),
"25"=>array("name_ru"=>"Мёдлинг","name_en"=>"Mödling ","name_href" => "at/population-of-mödling","count" => "20 495","real_id" =>25,),
"26"=>array("name_ru"=>"Халлайн","name_en"=>"Hallein ","name_href" => "at/population-of-hallein","count" => "20 378","real_id" =>26,),
"27"=>array("name_ru"=>"Куфштайн","name_en"=>"Kufstein ","name_href" => "at/population-of-kufstein","count" => "18 215","real_id" =>27,),
"28"=>array("name_ru"=>"Трайскирхен","name_en"=>"Traiskirchen ","name_href" => "at/population-of-traiskirchen","count" => "17 634","real_id" =>28,),
"29"=>array("name_ru"=>"Швехат","name_en"=>"Schwechat ","name_href" => "at/population-of-schwechat","count" => "17 032","real_id" =>29,),
"30"=>array("name_ru"=>"Браунау-ам-Инн","name_en"=>"Braunau am Inn","name_href" => "at/population-of-braunau-am-inn","count" => "16 255","real_id" =>30,),
"31"=>array("name_ru"=>"Штоккерау","name_en"=>"Stockerau ","name_href" => "at/population-of-stockerau","count" => "16 127","real_id" =>31,),
"32"=>array("name_ru"=>"Зальфельден","name_en"=>"Saalfelden","name_href" => "at/population-of-saalfelden","count" => "16 100","real_id" =>32,),
"33"=>array("name_ru"=>"Ансфельден","name_en"=>"Ansfelden ","name_href" => "at/population-of-ansfelden-","count" => "15 658","real_id" =>33,),
"34"=>array("name_ru"=>"Тульн-ан-дер-Донау","name_en"=>"Tulln an der Donau ","name_href" => "at/population-of-tulln-an-der-donau","count" => "15 582","real_id" =>34,),
"35"=>array("name_ru"=>"Хоэнемс","name_en"=>"Hohenems ","name_href" => "at/population-of-hohenems","count" => "15 579","real_id" =>35,),
"36"=>array("name_ru"=>"Шпитталь-ан-дер-Драу","name_en"=>"Spittal an der Drau","name_href" => "at/population-of-spittal-an-der-drau","count" => "15 555","real_id" =>36,),
"37"=>array("name_ru"=>"Тельфс","name_en"=>"Telfs ","name_href" => "at/population-of-telfs","count" => "14 986","real_id" =>37,),
"38"=>array("name_ru"=>"Терниц","name_en"=>"Ternitz ","name_href" => "at/population-of-ternitz","count" => "14 833","real_id" =>38,),
"39"=>array("name_ru"=>"Перхтольдсдорф","name_en"=>"Perchtoldsdorf ","name_href" => "at/population-of-perchtoldsdorf","count" => "14 754","real_id" =>39,),
"40"=>array("name_ru"=>"Фельдкирхен-ин-Кернтен","name_en"=>"Feldkirchen in Kärnten ","name_href" => "at/population-of-feldkirchen-in-kärnten","count" => "14 278","real_id" =>40,),
"41"=>array("name_ru"=>"Блуденц","name_en"=>"Bludenz ","name_href" => "at/population-of-bludenz","count" => "13 858","real_id" =>41,),
"42"=>array("name_ru"=>"Бад-Ишль","name_en"=>"Bad Ischl","name_href" => "at/population-of-bad-ischl","count" => "13 759","real_id" =>42,),
"43"=>array("name_ru"=>"Айзенштадт","name_en"=>"Eisenstadt ","name_href" => "at/population-of-eisenstadt","count" => "13 485","real_id" =>43,),
"44"=>array("name_ru"=>"Швац","name_en"=>"Schwaz ","name_href" => "at/population-of-schwaz","count" => "13 187","real_id" =>44,),
"45"=>array("name_ru"=>"Халль-ин-Тироль","name_en"=>"Hall in Tirol","name_href" => "at/population-of-hall-in-tirol","count" => "13 171","real_id" =>45,),
"46"=>array("name_ru"=>"Гмунден","name_en"=>"Gmunden ","name_href" => "at/population-of-gmunden","count" => "13 021","real_id" =>46,),
"47"=>array("name_ru"=>"Вёргль","name_en"=>"Wörgl ","name_href" => "at/population-of-wörgl","count" => "12 980","real_id" =>47,),
"48"=>array("name_ru"=>"Вальс-Зиценхайм","name_en"=>"Wals-Siezenheim ","name_href" => "at/population-of-wals-siezenheim","count" => "12 665","real_id" =>48,),
"49"=>array("name_ru"=>"Мархтренк","name_en"=>"Marchtrenk ","name_href" => "at/population-of-marchtrenk","count" => "12 618","real_id" =>49,),
"50"=>array("name_ru"=>"Брук-ан-дер-Мур","name_en"=>"Bruck an der Mur ","name_href" => "at/population-of-bruck-an-der-mur","count" => "12 541","real_id" =>50,),
"51"=>array("name_ru"=>"Санкт-Файт-ан-дер-Глан","name_en"=>"Sankt Veit an der Glan","name_href" => "at/population-of-sankt-veit-an-der-glan","count" => "12 473","real_id" =>51,),
"52"=>array("name_ru"=>"Корнойбург","name_en"=>"Korneuburg ","name_href" => "at/population-of-korneuburg","count" => "12 473","real_id" =>52,),
"53"=>array("name_ru"=>"Нойнкирхен","name_en"=>"Neunkirchen ","name_href" => "at/population-of-neunkirchen","count" => "12 376","real_id" =>53,),
"54"=>array("name_ru"=>"Хард","name_en"=>"Hard ","name_href" => "at/population-of-hard","count" => "12 051","real_id" =>54,),
"55"=>array("name_ru"=>"Фёклабрукк","name_en"=>"Vöcklabruck","name_href" => "at/population-of-vöcklabruck","count" => "11 945","real_id" =>55,),
"56"=>array("name_ru"=>"Лиенц","name_en"=>"Lienz ","name_href" => "at/population-of-lienz","count" => "11 903","real_id" =>56,),
"57"=>array("name_ru"=>"Ранквайль","name_en"=>"Rankweil ","name_href" => "at/population-of-rankweil","count" => "11 716","real_id" =>57,),
"58"=>array("name_ru"=>"Холлабрунн","name_en"=>"Hollabrunn","name_href" => "at/population-of-hollabrunn","count" => "11 563","real_id" =>58,),
"59"=>array("name_ru"=>"Энс","name_en"=>"Enns ","name_href" => "at/population-of-enns","count" => "11 523","real_id" =>59,),
"60"=>array("name_ru"=>"Брунн-ам-Гебирге","name_en"=>"Brunn am Gebirge","name_href" => "at/population-of-brunn-am-gebirge","count" => "11 509","real_id" =>60,),
"61"=>array("name_ru"=>"Рид-им-Иннкрайс","name_en"=>"Ried im Innkreis","name_href" => "at/population-of-ried-im-innkreis","count" => "11 444","real_id" =>61,),
"62"=>array("name_ru"=>"Бад-Фёслау","name_en"=>"Bad Vöslau","name_href" => "at/population-of-bad-vöslau","count" => "11 368","real_id" =>62,),
"63"=>array("name_ru"=>"Вайдхофен-ан-дер-Ибс","name_en"=>"Waidhofen an der Ybbs","name_href" => "at/population-of-waidhofen-an-der-ybbs","count" => "11 341","real_id" =>63,),
"64"=>array("name_ru"=>"Книттельфельд","name_en"=>"Knittelfeld","name_href" => "at/population-of-knittelfeld","count" => "11 301","real_id" =>64,),
"65"=>array("name_ru"=>"Трофайах","name_en"=>"Trofaiach","name_href" => "at/population-of-trofaiach","count" => "11 190","real_id" =>65,),
"66"=>array("name_ru"=>"Мистельбах-ан-дер-Цайя","name_en"=>"Mistelbach an der Zaya ","name_href" => "at/population-of-mistelbach-an-der-zaya","count" => "11 136","real_id" =>66,),
"67"=>array("name_ru"=>"Цветль","name_en"=>"Zwettl ","name_href" => "at/population-of-zwettl","count" => "11 097","real_id" =>67,),
"68"=>array("name_ru"=>"Фёлькермаркт","name_en"=>"Völkermarkt ","name_href" => "at/population-of-völkermarkt","count" => "11 024","real_id" =>68,),
"69"=>array("name_ru"=>"Гётцис","name_en"=>"Götzis ","name_href" => "at/population-of-götzis","count" => "10 994","real_id" =>69,),
"70"=>array("name_ru"=>"Санкт-Иоганн-им-Понгау","name_en"=>"St. Johann im Pongau ","name_href" => "at/population-of-st.-johann-im-pongau","count" => "10 760","real_id" =>70,),
"71"=>array("name_ru"=>"Гензерндорф","name_en"=>"Gänserndorf ","name_href" => "at/population-of-gänserndorf","count" => "10 747","real_id" =>71,),
"72"=>array("name_ru"=>"Бишофсхофен","name_en"=>"Bischofshofen ","name_href" => "at/population-of-bischofshofen","count" => "10 310","real_id" =>72,),
"73"=>array("name_ru"=>"Герасдорф-Вин","name_en"=>"Gerasdorf bei Wien","name_href" => "at/population-of-gerasdorf-bei-wien","count" => "10 307","real_id" =>73,),
"74"=>array("name_ru"=>"Эбрайхсдорф","name_en"=>"Ebreichsdorf ","name_href" => "at/population-of-ebreichsdorf","count" => "10 228","real_id" =>74,),
"75"=>array("name_ru"=>"Зекирхен-ам-Валлерзе","name_en"=>"Seekirchen am Wallersee","name_href" => "at/population-of-seekirchen-am-wallersee","count" => "10 226","real_id" =>75,),
"76"=>array("name_ru"=>"Санкт-Андре","name_en"=>"Sankt Andrä","name_href" => "at/population-of-sankt-andrä","count" => "10 135","real_id" =>76,),
"77"=>array("name_ru"=>"Гросэнцерсдорф","name_en"=>"Groß-Enzersdorf","name_href" => "at/population-of-groß-enzersdorf","count" => "10 033","real_id" =>77,),
"78"=>array("name_ru"=>"Вена","name_en"=>"Vienna ","name_href" => "at/population-of-vienna","count" => "1 765 649","real_id" =>78,),
"79"=>array("name_ru"=>"Грац","name_en"=>"Graz ","name_href" => "at/population-of-graz","count" => "269 997","real_id" =>79,),
"80"=>array("name_ru"=>"Линц","name_en"=>"Linz ","name_href" => "at/population-of-linz","count" => "193 814","real_id" =>80,),
"81"=>array("name_ru"=>"Зальцбург","name_en"=>"Salzburg ","name_href" => "at/population-of-salzburg","count" => "146 631","real_id" =>81,),
"82"=>array("name_ru"=>"Инсбрук","name_en"=>"Innsbruck ","name_href" => "at/population-of-innsbruck","count" => "124 579","real_id" =>82,)
);

?>