<?php
//Болгария 78
$libbg = array ( 

"1"=>array("name_ru"=>"София","name_en"=>"Sofia","name_href" => "bg/population-of-sofia","count" => "1 196 389","real_id" =>1,),
"2"=>array("name_ru"=>"Пловдив","name_en"=>"Plovdiv","name_href" => "bg/population-of-plovdiv","count" => "340 638","real_id" =>2,),
"3"=>array("name_ru"=>"Варна","name_en"=>"Varna","name_href" => "bg/population-of-varna","count" => "314 539","real_id" =>3,),
"4"=>array("name_ru"=>"Бургас","name_en"=>"Burgas","name_href" => "bg/population-of-burgas","count" => "210 316","real_id" =>4,),
"5"=>array("name_ru"=>"Русе","name_en"=>"Ruse","name_href" => "bg/population-of-ruse","count" => "162 128","real_id" =>5,),
"6"=>array("name_ru"=>"Стара-Загора","name_en"=>"Stara Zagora","name_href" => "bg/population-of-stara-zagora","count" => "143 989","real_id" =>6,),
"7"=>array("name_ru"=>"Плевен","name_en"=>"Pleven","name_href" => "bg/population-of-pleven","count" => "122 149","real_id" =>7,),
"8"=>array("name_ru"=>"Сливен","name_en"=>"Sliven","name_href" => "bg/population-of-sliven","count" => "100 695","real_id" =>8,),
"9"=>array("name_ru"=>"Добрич","name_en"=>"Dobrich","name_href" => "bg/population-of-dobrich","count" => "100 379","real_id" =>9,),
"10"=>array("name_ru"=>"Шумен","name_en"=>"Shumen","name_href" => "bg/population-of-shumen","count" => "89 054","real_id" =>10,),
"11"=>array("name_ru"=>"Перник","name_en"=>"Pernik","name_href" => "bg/population-of-pernik","count" => "86 341","real_id" =>11,),
"12"=>array("name_ru"=>"Ямбол","name_en"=>"Yambol","name_href" => "bg/population-of-yambol","count" => "85 517","real_id" =>12,),
"13"=>array("name_ru"=>"Хасково","name_en"=>"Haskovo","name_href" => "bg/population-of-haskovo","count" => "82 886","real_id" =>13,),
"14"=>array("name_ru"=>"Пазарджик","name_en"=>"Pazardzhik","name_href" => "bg/population-of-pazardzhik","count" => "80 797","real_id" =>14,),
"15"=>array("name_ru"=>"Благоевград","name_en"=>"Blagoevgrad","name_href" => "bg/population-of-blagoevgrad","count" => "76 829","real_id" =>15,),
"16"=>array("name_ru"=>"Велико-Тырново","name_en"=>"Veliko Tarnovo","name_href" => "bg/population-of-veliko-tarnovo","count" => "71 755","real_id" =>16,),
"17"=>array("name_ru"=>"Враца","name_en"=>"Vratsa","name_href" => "bg/population-of-vratsa","count" => "70 806","real_id" =>17,),
"18"=>array("name_ru"=>"Габрово","name_en"=>"Gabrovo","name_href" => "bg/population-of-gabrovo","count" => "67 833","real_id" =>18,),
"19"=>array("name_ru"=>"Видин","name_en"=>"Vidin","name_href" => "bg/population-of-vidin","count" => "59 728","real_id" =>19,),
"20"=>array("name_ru"=>"Асеновград","name_en"=>"Asenovgrad","name_href" => "bg/population-of-asenovgrad","count" => "55 819","real_id" =>20,),
"21"=>array("name_ru"=>"Кюстендил","name_en"=>"Kyustendil","name_href" => "bg/population-of-kyustendil","count" => "52 346","real_id" =>21,),
"22"=>array("name_ru"=>"Кырджали","name_en"=>"Kardjali","name_href" => "bg/population-of-kardjali","count" => "50 811","real_id" =>22,),
"23"=>array("name_ru"=>"Казанлык","name_en"=>"Kazanlak","name_href" => "bg/population-of-kazanlak","count" => "50 759","real_id" =>23,),
"24"=>array("name_ru"=>"Монтана","name_en"=>"Montana","name_href" => "bg/population-of-montana","count" => "50 200","real_id" =>24,),
"25"=>array("name_ru"=>"Димитровград","name_en"=>"Dimitrovgrad","name_href" => "bg/population-of-dimitrovgrad","count" => "45 591","real_id" =>25,),
"26"=>array("name_ru"=>"Ловеч","name_en"=>"Lovech","name_href" => "bg/population-of-lovech","count" => "43 391","real_id" =>26,),
"27"=>array("name_ru"=>"Тырговиште","name_en"=>"Targovishte","name_href" => "bg/population-of-targovishte","count" => "43 263","real_id" =>27,),
"28"=>array("name_ru"=>"Силистра","name_en"=>"Silistra","name_href" => "bg/population-of-silistra","count" => "42 937","real_id" =>28,),
"29"=>array("name_ru"=>"Дупница","name_en"=>"Dupnitsa","name_href" => "bg/population-of-dupnitsa","count" => "40 756","real_id" =>29,),
"30"=>array("name_ru"=>"Разград","name_en"=>"Razgrad","name_href" => "bg/population-of-razgrad","count" => "39 029","real_id" =>30,),
"31"=>array("name_ru"=>"Горна-Оряховица","name_en"=>"Gorna Oryahovitsa","name_href" => "bg/population-of-gorna-oryahovitsa","count" => "36 661","real_id" =>31,),
"32"=>array("name_ru"=>"Свиштов","name_en"=>"Svishtov","name_href" => "bg/population-of-svishtov","count" => "35 547","real_id" =>32,),
"33"=>array("name_ru"=>"Смолян","name_en"=>"Smolyan","name_href" => "bg/population-of-smolyan","count" => "32 951","real_id" =>33,),
"34"=>array("name_ru"=>"Петрич","name_en"=>"Petrich","name_href" => "bg/population-of-petrich","count" => "31 821","real_id" =>34,),
"35"=>array("name_ru"=>"Сандански","name_en"=>"Sandanski","name_href" => "bg/population-of-sandanski","count" => "29 215","real_id" =>35,),
"36"=>array("name_ru"=>"Самоков","name_en"=>"Samokov","name_href" => "bg/population-of-samokov","count" => "28 541","real_id" =>36,),
"37"=>array("name_ru"=>"Лом","name_en"=>"Scrap","name_href" => "bg/population-of-scrap","count" => "27 480","real_id" =>37,),
"38"=>array("name_ru"=>"Севлиево","name_en"=>"Sevlievo","name_href" => "bg/population-of-sevlievo","count" => "26 675","real_id" =>38,),
"39"=>array("name_ru"=>"Карлово","name_en"=>"Karlovo","name_href" => "bg/population-of-karlovo","count" => "26 543","real_id" =>39,),
"40"=>array("name_ru"=>"Нова-Загора","name_en"=>"Nova Zagora","name_href" => "bg/population-of-nova-zagora","count" => "26 015","real_id" =>40,),
"41"=>array("name_ru"=>"Велинград","name_en"=>"Velingrad","name_href" => "bg/population-of-velingrad","count" => "25 996","real_id" =>41,),
"42"=>array("name_ru"=>"Троян","name_en"=>"Trojan","name_href" => "bg/population-of-trojan","count" => "24 628","real_id" =>42,),
"43"=>array("name_ru"=>"Айтос","name_en"=>"Aytos","name_href" => "bg/population-of-aytos","count" => "23 290","real_id" =>43,),
"44"=>array("name_ru"=>"Ботевград","name_en"=>"Botevgrad","name_href" => "bg/population-of-botevgrad","count" => "22 191","real_id" =>44,),
"45"=>array("name_ru"=>"Гоце Делчев","name_en"=>"Gotse Delchev","name_href" => "bg/population-of-gotse-delchev","count" => "21 170","real_id" =>45,),
"46"=>array("name_ru"=>"Пештера","name_en"=>"Peshtera","name_href" => "bg/population-of-peshtera","count" => "21 010","real_id" =>46,),
"47"=>array("name_ru"=>"Харманли","name_en"=>"Harmanli","name_href" => "bg/population-of-harmanli","count" => "20 715","real_id" =>47,),
"48"=>array("name_ru"=>"Поморие","name_en"=>"Pomorie","name_href" => "bg/population-of-pomorie","count" => "14 331","real_id" =>48,),
"49"=>array("name_ru"=>"Балчик","name_en"=>"Balchik","name_href" => "bg/population-of-balchik","count" => "13 107","real_id" =>49,),
"50"=>array("name_ru"=>"Каварна","name_en"=>"Kavarna","name_href" => "bg/population-of-kavarna","count" => "12 043","real_id" =>50,),
"51"=>array("name_ru"=>"Несебыр","name_en"=>"Nessebar","name_href" => "bg/population-of-nessebar","count" => "11 044","real_id" =>51,),
"52"=>array("name_ru"=>"Трявна","name_en"=>"Tryavna","name_href" => "bg/population-of-tryavna","count" => "10 977","real_id" =>52,),
"53"=>array("name_ru"=>"Банкя","name_en"=>"Bankya","name_href" => "bg/population-of-bankya","count" => "10 425","real_id" =>53,),
"54"=>array("name_ru"=>"Тутракан","name_en"=>"Tutrakan","name_href" => "bg/population-of-tutrakan","count" => "10 239","real_id" =>54,),
"55"=>array("name_ru"=>"Велики-Преслав","name_en"=>"Veliki Preslav","name_href" => "bg/population-of-veliki-preslav","count" => "9 780","real_id" =>55,),
"56"=>array("name_ru"=>"Банско","name_en"=>"Bansko","name_href" => "bg/population-of-bansko","count" => "8 538","real_id" =>56,),
"57"=>array("name_ru"=>"Хисаря","name_en"=>"Hisarya","name_href" => "bg/population-of-hisarya","count" => "8 227","real_id" =>57,),
"58"=>array("name_ru"=>"Выршец","name_en"=>"Varshets","name_href" => "bg/population-of-varshets","count" => "6 749","real_id" =>58,),
"59"=>array("name_ru"=>"Царево","name_en"=>"Tsarevo","name_href" => "bg/population-of-tsarevo","count" => "6 170","real_id" =>59,),
"60"=>array("name_ru"=>"Белоградчик","name_en"=>"Belogradchik","name_href" => "bg/population-of-belogradchik","count" => "6 038","real_id" =>60,),
"61"=>array("name_ru"=>"Созопол","name_en"=>"Sozopol","name_href" => "bg/population-of-sozopol","count" => "5 024","real_id" =>61,),
"62"=>array("name_ru"=>"Ардино","name_en"=>"Ardino","name_href" => "bg/population-of-ardino","count" => "3 955","real_id" =>62,),
"63"=>array("name_ru"=>"Шабла","name_en"=>"Shabla","name_href" => "bg/population-of-shabla","count" => "3 863","real_id" =>63,),
"64"=>array("name_ru"=>"Батак","name_en"=>"Batak","name_href" => "bg/population-of-batak","count" => "3 859","real_id" =>64,),
"65"=>array("name_ru"=>"Приморско","name_en"=>"Primorsko","name_href" => "bg/population-of-primorsko","count" => "3 241","real_id" =>65,),
"66"=>array("name_ru"=>"Априлци","name_en"=>"Apriltsi","name_href" => "bg/population-of-apriltsi","count" => "3 160","real_id" =>66,),
"67"=>array("name_ru"=>"Свети-Влас","name_en"=>"Sveti Vlas","name_href" => "bg/population-of-sveti-vlas","count" => "2 773","real_id" =>67,),
"68"=>array("name_ru"=>"Копривштица","name_en"=>"Koprivshtitsa","name_href" => "bg/population-of-koprivshtitsa","count" => "2 604","real_id" =>68,),
"69"=>array("name_ru"=>"Бяла","name_en"=>"Byala","name_href" => "bg/population-of-byala","count" => "2 197","real_id" =>69,),
"70"=>array("name_ru"=>"Обзор","name_en"=>"Overview","name_href" => "bg/population-of-overview","count" => "2 053","real_id" =>70,),
"71"=>array("name_ru"=>"Алфатар","name_en"=>"Alfatar","name_href" => "bg/population-of-alfatar","count" => "1 726","real_id" =>71,),
"72"=>array("name_ru"=>"Антоново","name_en"=>"Antonovo","name_href" => "bg/population-of-antonovo","count" => "1 503","real_id" =>72,),
"73"=>array("name_ru"=>"Шипка","name_en"=>"Shipka","name_href" => "bg/population-of-shipka","count" => "1 481","real_id" =>73,),
"74"=>array("name_ru"=>"Ахтопол","name_en"=>"Ahtopol","name_href" => "bg/population-of-ahtopol","count" => "1 425","real_id" =>74,),
"75"=>array("name_ru"=>"Ахтопол","name_en"=>"Ahtopol","name_href" => "bg/population-of-ahtopol","count" => "1 421","real_id" =>75,),
"76"=>array("name_ru"=>"Плиска","name_en"=>"Pliska","name_href" => "bg/population-of-pliska","count" => "1 129","real_id" =>76,),
"77"=>array("name_ru"=>"Китен","name_en"=>"Kiten","name_href" => "bg/population-of-kiten","count" => "1 067","real_id" =>77,),
"78"=>array("name_ru"=>"Мелник","name_en"=>"Melnik","name_href" => "bg/population-of-melnik","count" => "269","real_id" =>78,),
"79"=>array("name_ru"=>"София","name_en"=>"Sofia","name_href" => "bg/population-of-sofia","count" => "1 196 389","real_id" =>79,),
"80"=>array("name_ru"=>"Пловдив","name_en"=>"Plovdiv","name_href" => "bg/population-of-plovdiv","count" => "340 638","real_id" =>80,),
"81"=>array("name_ru"=>"Варна","name_en"=>"Varna","name_href" => "bg/population-of-varna","count" => "314 539","real_id" =>81,),
"82"=>array("name_ru"=>"Бургас","name_en"=>"Burgas","name_href" => "bg/population-of-burgas","count" => "210 316","real_id" =>82,),
"83"=>array("name_ru"=>"Русе","name_en"=>"Ruse","name_href" => "bg/population-of-ruse","count" => "162 128","real_id" =>83,)
);

?>