<?php
//Бельгия 135 
$libbe = array ( 

"1"=>array("name_ru"=>"Антверпен","name_en"=>"Antwerpen","name_href" => "be/population-of-antwerpen","count" => "472 526","real_id" =>1,),
"2"=>array("name_ru"=>"Гент","name_en"=>"Gent","name_href" => "be/population-of-gent","count" => "233 120","real_id" =>2,),
"3"=>array("name_ru"=>"Шарлеруа","name_en"=>"Charleroi","name_href" => "be/population-of-charleroi","count" => "201 300","real_id" =>3,),
"4"=>array("name_ru"=>"Льеж","name_en"=>"Liege","name_href" => "be/population-of-liege","count" => "186 805","real_id" =>4,),
"5"=>array("name_ru"=>"Брюссель","name_en"=>"Bruxelles, Brussel","name_href" => "be/population-of-bruxelles,-brussel","count" => "144 784","real_id" =>5,),
"6"=>array("name_ru"=>"Брюгге","name_en"=>"Brugge","name_href" => "be/population-of-brugge","count" => "117 224","real_id" =>6,),
"7"=>array("name_ru"=>"Намюр","name_en"=>"Namur","name_href" => "be/population-of-namur","count" => "107 178","real_id" =>7,),
"8"=>array("name_ru"=>"Монс","name_en"=>"Mons","name_href" => "be/population-of-mons","count" => "91 221","real_id" =>8,),
"9"=>array("name_ru"=>"Лёвен","name_en"=>"Leuven","name_href" => "be/population-of-leuven","count" => "90 706","real_id" =>9,),
"10"=>array("name_ru"=>"Мехелен","name_en"=>"Mechelen","name_href" => "be/population-of-mechelen","count" => "78 268","real_id" =>10,),
"11"=>array("name_ru"=>"Алст","name_en"=>"Aalst","name_href" => "be/population-of-aalst","count" => "77 360","real_id" =>11,),
"12"=>array("name_ru"=>"Ла-Лувьер","name_en"=>"La Louviere","name_href" => "be/population-of-la-louviere","count" => "77 210","real_id" =>12,),
"13"=>array("name_ru"=>"Кортрейк","name_en"=>"Kortrijk","name_href" => "be/population-of-kortrijk","count" => "73 657","real_id" =>13,),
"14"=>array("name_ru"=>"Хасселт","name_en"=>"Hasselt","name_href" => "be/population-of-hasselt","count" => "70 035","real_id" =>14,),
"15"=>array("name_ru"=>"Синт-Никлас","name_en"=>"Sint-Niklaas","name_href" => "be/population-of-sint-niklaas","count" => "69 725","real_id" =>15,),
"16"=>array("name_ru"=>"Остенде","name_en"=>"Oostende","name_href" => "be/population-of-oostende","count" => "68 931","real_id" =>16,),
"17"=>array("name_ru"=>"Турне","name_en"=>"Tournai","name_href" => "be/population-of-tournai","count" => "67 534","real_id" =>17,),
"18"=>array("name_ru"=>"Генк","name_en"=>"Genk","name_href" => "be/population-of-genk","count" => "63 787","real_id" =>18,),
"19"=>array("name_ru"=>"Серен","name_en"=>"Seraing","name_href" => "be/population-of-seraing","count" => "60 740","real_id" =>19,),
"20"=>array("name_ru"=>"Руселаре","name_en"=>"Roeselare","name_href" => "be/population-of-roeselare","count" => "55 775","real_id" =>20,),
"21"=>array("name_ru"=>"Вервье","name_en"=>"Verviers","name_href" => "be/population-of-verviers","count" => "53 597","real_id" =>21,),
"22"=>array("name_ru"=>"Мускрон","name_en"=>"Mouscron","name_href" => "be/population-of-mouscron","count" => "52 825","real_id" =>22,),
"23"=>array("name_ru"=>"Дендермонде","name_en"=>"Dendermonde","name_href" => "be/population-of-dendermonde","count" => "43 347","real_id" =>23,),
"24"=>array("name_ru"=>"Беринген","name_en"=>"Beringen","name_href" => "be/population-of-beringen","count" => "41 072","real_id" =>24,),
"25"=>array("name_ru"=>"Тюрнхаут","name_en"=>"Turnhout","name_href" => "be/population-of-turnhout","count" => "39 791","real_id" =>25,),
"26"=>array("name_ru"=>"Синт-Трёйден","name_en"=>"Sint-Truiden","name_href" => "be/population-of-sint-truiden","count" => "38 247","real_id" =>26,),
"27"=>array("name_ru"=>"Локерен","name_en"=>"Lokeren","name_href" => "be/population-of-lokeren","count" => "37 850","real_id" =>27,),
"28"=>array("name_ru"=>"Эрсталь","name_en"=>"Herstal","name_href" => "be/population-of-herstal","count" => "37 685","real_id" =>28,),
"29"=>array("name_ru"=>"Вилворде","name_en"=>"Vilvoorde","name_href" => "be/population-of-vilvoorde","count" => "37 324","real_id" =>29,),
"30"=>array("name_ru"=>"Варегем","name_en"=>"Waregem","name_href" => "be/population-of-waregem","count" => "35 852","real_id" =>30,),
"31"=>array("name_ru"=>"Нинове","name_en"=>"Ninove","name_href" => "be/population-of-ninove","count" => "35 651","real_id" =>31,),
"32"=>array("name_ru"=>"Шатле","name_en"=>"Chatelet","name_href" => "be/population-of-chatelet","count" => "35 621","real_id" =>32,),
"33"=>array("name_ru"=>"Гел","name_en"=>"Geel","name_href" => "be/population-of-geel","count" => "35 189","real_id" =>33,),
"34"=>array("name_ru"=>"Ипр","name_en"=>"Ieper","name_href" => "be/population-of-ieper","count" => "34 897","real_id" =>34,),
"35"=>array("name_ru"=>"Халле","name_en"=>"Halle","name_href" => "be/population-of-halle","count" => "34 882","real_id" =>35,),
"36"=>array("name_ru"=>"Лир","name_en"=>"Lier","name_href" => "be/population-of-lier","count" => "33 272","real_id" =>36,),
"37"=>array("name_ru"=>"Менен","name_en"=>"Menen","name_href" => "be/population-of-menen","count" => "32 413","real_id" =>37,),
"38"=>array("name_ru"=>"Бинш","name_en"=>"Binche","name_href" => "be/population-of-binche","count" => "32 409","real_id" =>38,),
"39"=>array("name_ru"=>"Вавр","name_en"=>"Wavre","name_href" => "be/population-of-wavre","count" => "32 201","real_id" =>39,),
"40"=>array("name_ru"=>"Ломмел","name_en"=>"Lommel","name_href" => "be/population-of-lommel","count" => "31 898","real_id" =>40,),
"41"=>array("name_ru"=>"Тинен","name_en"=>"Tienen","name_href" => "be/population-of-tienen","count" => "31 835","real_id" =>41,),
"42"=>array("name_ru"=>"Герардсберген","name_en"=>"Geraardsbergen","name_href" => "be/population-of-geraardsbergen","count" => "31 380","real_id" =>42,),
"43"=>array("name_ru"=>"Билзен","name_en"=>"Bilzen","name_href" => "be/population-of-bilzen","count" => "30 057","real_id" =>43,),
"44"=>array("name_ru"=>"Тонгерен","name_en"=>"Tongeren","name_href" => "be/population-of-tongeren","count" => "29 687","real_id" =>44,),
"45"=>array("name_ru"=>"Оттиньи-Лувен-ла-Нёв","name_en"=>"Ottignies-Louvain-la-Neuve","name_href" => "be/population-of-ottignies-louvain-la-neuve","count" => "29 521","real_id" =>45,),
"46"=>array("name_ru"=>"Ауденарде","name_en"=>"Oudenaarde","name_href" => "be/population-of-oudenaarde","count" => "28 517","real_id" =>46,),
"47"=>array("name_ru"=>"Дейнзе","name_en"=>"Deinze","name_href" => "be/population-of-deinze","count" => "28 320","real_id" =>47,),
"48"=>array("name_ru"=>"Арсхот","name_en"=>"Aarschot","name_href" => "be/population-of-aarschot","count" => "27 864","real_id" =>48,),
"49"=>array("name_ru"=>"Ат","name_en"=>"Ath","name_href" => "be/population-of-ath","count" => "26 799","real_id" =>49,),
"50"=>array("name_ru"=>"Изегем","name_en"=>"Izegem","name_href" => "be/population-of-izegem","count" => "26 544","real_id" =>50,),
"51"=>array("name_ru"=>"Арлон","name_en"=>"Arlon","name_href" => "be/population-of-arlon","count" => "26 367","real_id" =>51,),
"52"=>array("name_ru"=>"Харелбеке","name_en"=>"Harelbeke","name_href" => "be/population-of-harelbeke","count" => "26 172","real_id" =>52,),
"53"=>array("name_ru"=>"Херенталс","name_en"=>"Herentals","name_href" => "be/population-of-herentals","count" => "26 071","real_id" =>53,),
"54"=>array("name_ru"=>"Анденн","name_en"=>"Andenne","name_href" => "be/population-of-andenne","count" => "25 624","real_id" =>54,),
"55"=>array("name_ru"=>"Суаньи","name_en"=>"Soignies","name_href" => "be/population-of-soignies","count" => "25 420","real_id" =>55,),
"56"=>array("name_ru"=>"Зоттегем","name_en"=>"Zottegem","name_href" => "be/population-of-zottegem","count" => "24 548","real_id" =>56,),
"57"=>array("name_ru"=>"Мортсел","name_en"=>"Mortsel","name_href" => "be/population-of-mortsel","count" => "24 427","real_id" =>57,),
"58"=>array("name_ru"=>"Нивель","name_en"=>"Nivelles","name_href" => "be/population-of-nivelles","count" => "24 290","real_id" =>58,),
"59"=>array("name_ru"=>"Ронсе","name_en"=>"Ronse","name_href" => "be/population-of-ronse","count" => "24 158","real_id" =>59,),
"60"=>array("name_ru"=>"Маасейк","name_en"=>"Maaseik","name_href" => "be/population-of-maaseik","count" => "23 631","real_id" =>60,),
"61"=>array("name_ru"=>"Дист","name_en"=>"Diest","name_href" => "be/population-of-diest","count" => "22 740","real_id" =>61,),
"62"=>array("name_ru"=>"Сен-Гислен","name_en"=>"Saint-Ghislain","name_href" => "be/population-of-saint-ghislain","count" => "22 466","real_id" =>62,),
"63"=>array("name_ru"=>"Флёрюс","name_en"=>"Fleurus","name_href" => "be/population-of-fleurus","count" => "22 221","real_id" =>63,),
"64"=>array("name_ru"=>"Схерпенхёвел-Зихем","name_en"=>"Scherpenheuvel-Zichem","name_href" => "be/population-of-scherpenheuvel-zichem","count" => "22 064","real_id" =>64,),
"65"=>array("name_ru"=>"Жамблу","name_en"=>"Gembloux","name_href" => "be/population-of-gembloux","count" => "21 964","real_id" =>65,),
"66"=>array("name_ru"=>"Брен-ле-Конт","name_en"=>"Braine-le-Comte","name_href" => "be/population-of-braine-le-comte","count" => "20 305","real_id" =>66,),
"67"=>array("name_ru"=>"Юи","name_en"=>"Hui","name_href" => "be/population-of-hui","count" => "20 071","real_id" =>67,),
"68"=>array("name_ru"=>"Поперинге","name_en"=>"Poperinge","name_href" => "be/population-of-poperinge","count" => "19 623","real_id" =>68,),
"69"=>array("name_ru"=>"Экло","name_en"=>"Eeklo","name_href" => "be/population-of-eeklo","count" => "19 535","real_id" =>69,),
"70"=>array("name_ru"=>"Торхаут","name_en"=>"Torhout","name_href" => "be/population-of-torhout","count" => "19 453","real_id" =>70,),
"71"=>array("name_ru"=>"Тилт","name_en"=>"Tielt","name_href" => "be/population-of-tielt","count" => "19 269","real_id" =>71,),
"72"=>array("name_ru"=>"Дилсен-Стоккем","name_en"=>"Dilsen-Stokkem","name_href" => "be/population-of-dilsen-stokkem","count" => "19 106","real_id" =>72,),
"73"=>array("name_ru"=>"Хогстратен","name_en"=>"Hoogstraten","name_href" => "be/population-of-hoogstraten","count" => "18 582","real_id" =>73,),
"74"=>array("name_ru"=>"Эйпен","name_en"=>"Eupen","name_href" => "be/population-of-eupen","count" => "18 248","real_id" =>74,),
"75"=>array("name_ru"=>"Бланкенберге","name_en"=>"Blankenberge","name_href" => "be/population-of-blankenberge","count" => "18 175","real_id" =>75,),
"76"=>array("name_ru"=>"Лессин","name_en"=>"Lessines","name_href" => "be/population-of-lessines","count" => "17 848","real_id" =>76,),
"77"=>array("name_ru"=>"Вервик","name_en"=>"Wervik","name_href" => "be/population-of-wervik","count" => "17 607","real_id" =>77,),
"78"=>array("name_ru"=>"Комин-Варнетон","name_en"=>"Comines-Warneton","name_href" => "be/population-of-comines-warneton","count" => "17 562","real_id" =>78,),
"79"=>array("name_ru"=>"Валькур","name_en"=>"Walcourt","name_href" => "be/population-of-walcourt","count" => "17 516","real_id" =>79,),
"80"=>array("name_ru"=>"Марш-ан-Фаменн","name_en"=>"Marche-en-Famenne","name_href" => "be/population-of-marche-en-famenne","count" => "16 994","real_id" =>80,),
"81"=>array("name_ru"=>"Перувельз","name_en"=>"Peruwelz","name_href" => "be/population-of-peruwelz","count" => "16 843","real_id" =>81,),
"82"=>array("name_ru"=>"Визе","name_en"=>"Vise","name_href" => "be/population-of-vise","count" => "16 817","real_id" =>82,),
"83"=>array("name_ru"=>"Эрв","name_en"=>"Herve","name_href" => "be/population-of-herve","count" => "16 772","real_id" =>83,),
"84"=>array("name_ru"=>"Фонтен-л'Эвек","name_en"=>"Fontaine-l'Eveque","name_href" => "be/population-of-fontaine-leveque","count" => "16 687","real_id" =>84,),
"85"=>array("name_ru"=>"Пер","name_en"=>"Peer","name_href" => "be/population-of-peer","count" => "15 810","real_id" =>85,),
"86"=>array("name_ru"=>"Диксмёйде","name_en"=>"Diksmuide","name_href" => "be/population-of-diksmuide","count" => "15 733","real_id" =>86,),
"87"=>array("name_ru"=>"Сине","name_en"=>"Ciney","name_href" => "be/population-of-ciney","count" => "14 958","real_id" =>87,),
"88"=>array("name_ru"=>"Ланден","name_en"=>"Landen","name_href" => "be/population-of-landen","count" => "14 682","real_id" =>88,),
"89"=>array("name_ru"=>"Тюэн","name_en"=>"Thuin","name_href" => "be/population-of-thuin","count" => "14 625","real_id" =>89,),
"90"=>array("name_ru"=>"Бре","name_en"=>"Bree","name_href" => "be/population-of-bree","count" => "14 503","real_id" =>90,),
"91"=>array("name_ru"=>"Анню","name_en"=>"Hannut","name_href" => "be/population-of-hannut","count" => "14 291","real_id" =>91,),
"92"=>array("name_ru"=>"Бастонь","name_en"=>"Bastogne","name_href" => "be/population-of-bastogne","count" => "14 144","real_id" =>92,),
"93"=>array("name_ru"=>"Женап","name_en"=>"Genappe","name_href" => "be/population-of-genappe","count" => "14 136","real_id" =>93,),
"94"=>array("name_ru"=>"Варем","name_en"=>"Waremme","name_href" => "be/population-of-waremme","count" => "14 050","real_id" =>94,),
"95"=>array("name_ru"=>"Хамонт-Ахел","name_en"=>"Hamont-Achel","name_href" => "be/population-of-hamont-achel","count" => "13 770","real_id" =>95,),
"96"=>array("name_ru"=>"Кувен","name_en"=>"Couvin","name_href" => "be/population-of-couvin","count" => "13 476","real_id" =>96,),
"97"=>array("name_ru"=>"Лёз-ан-Эно","name_en"=>"Leuze-en-Hainaut","name_href" => "be/population-of-leuze-en-hainaut","count" => "13 223","real_id" =>97,),
"98"=>array("name_ru"=>"Динан","name_en"=>"Dinant","name_href" => "be/population-of-dinant","count" => "13 012","real_id" =>98,),
"99"=>array("name_ru"=>"Жодуань","name_en"=>"Jodoigne","name_href" => "be/population-of-jodoigne","count" => "12 440","real_id" =>99,),
"100"=>array("name_ru"=>"Рошфор","name_en"=>"Rochefort","name_href" => "be/population-of-rochefort","count" => "12 038","real_id" =>100,),
"101"=>array("name_ru"=>"Ангьен","name_en"=>"Enghien","name_href" => "be/population-of-enghien","count" => "11 980","real_id" =>101,),
"102"=>array("name_ru"=>"Вёрне","name_en"=>"Veurne","name_href" => "be/population-of-veurne","count" => "11 843","real_id" =>102,),
"103"=>array("name_ru"=>"Мальмеди","name_en"=>"Malmedy","name_href" => "be/population-of-malmedy","count" => "11 829","real_id" =>103,),
"104"=>array("name_ru"=>"Херк-де-Стад","name_en"=>"Herk-de-Stad","name_href" => "be/population-of-herk-de-stad","count" => "11 795","real_id" =>104,),
"105"=>array("name_ru"=>"Виртон","name_en"=>"Virton","name_href" => "be/population-of-virton","count" => "11 165","real_id" =>105,),
"106"=>array("name_ru"=>"Гистел","name_en"=>"Gistel","name_href" => "be/population-of-gistel","count" => "11 125","real_id" =>106,),
"107"=>array("name_ru"=>"Дамме","name_en"=>"Damme","name_href" => "be/population-of-damme","count" => "10 899","real_id" =>107,),
"108"=>array("name_ru"=>"Ньивпорт","name_en"=>"Nieuwpoort","name_href" => "be/population-of-nieuwpoort","count" => "10 855","real_id" =>108,),
"109"=>array("name_ru"=>"Спа","name_en"=>"Spa","name_href" => "be/population-of-spa","count" => "10 543","real_id" =>109,),
"110"=>array("name_ru"=>"Дюрбюи","name_en"=>"Durbuy","name_href" => "be/population-of-durbuy","count" => "10 531","real_id" =>110,),
"111"=>array("name_ru"=>"Борглон","name_en"=>"Borgloon","name_href" => "be/population-of-borgloon","count" => "10 152","real_id" =>111,),
"112"=>array("name_ru"=>"Шиме","name_en"=>"Chimay","name_href" => "be/population-of-chimay","count" => "9 774","real_id" =>112,),
"113"=>array("name_ru"=>"Фос-ля-Виль","name_en"=>"Fosses-la-Ville","name_href" => "be/population-of-fosses-la-ville","count" => "9 311","real_id" =>113,),
"114"=>array("name_ru"=>"Санкт-Вит","name_en"=>"Sankt Vith","name_href" => "be/population-of-sankt-vith","count" => "9 169","real_id" =>114,),
"115"=>array("name_ru"=>"Ауденбюрг","name_en"=>"Аudenburg","name_href" => "be/population-of-аudenburg","count" => "8 929","real_id" =>115,),
"116"=>array("name_ru"=>"Ленник","name_en"=>"Lennik","name_href" => "be/population-of-lennik","count" => "8 925","real_id" =>116,),
"117"=>array("name_ru"=>"Хален","name_en"=>"Halen","name_href" => "be/population-of-halen","count" => "8 624","real_id" =>117,),
"118"=>array("name_ru"=>"Борень","name_en"=>"Beauraing","name_href" => "be/population-of-beauraing","count" => "8 344","real_id" =>118,),
"119"=>array("name_ru"=>"Филипвиль","name_en"=>"Philippeville","name_href" => "be/population-of-philippeville","count" => "8 320","real_id" =>119,),
"120"=>array("name_ru"=>"Ле-Рёлс","name_en"=>"Le R?ulx","name_href" => "be/population-of-le-rulx","count" => "7 977","real_id" =>120,),
"121"=>array("name_ru"=>"Заутлеув","name_en"=>"Zoutleeuw","name_href" => "be/population-of-zoutleeuw","count" => "7 947","real_id" =>121,),
"122"=>array("name_ru"=>"Антуэн","name_en"=>"Antoing","name_href" => "be/population-of-antoing","count" => "7 549","real_id" =>122,),
"123"=>array("name_ru"=>"Бомон","name_en"=>"Beaumont","name_href" => "be/population-of-beaumont","count" => "6 698","real_id" =>123,),
"124"=>array("name_ru"=>"Ставело","name_en"=>"Stavelot","name_href" => "be/population-of-stavelot","count" => "6 671","real_id" =>124,),
"125"=>array("name_ru"=>"Нёшато","name_en"=>"Neufchateau","name_href" => "be/population-of-neufchateau","count" => "6 539","real_id" =>125,),
"126"=>array("name_ru"=>"Шьевр","name_en"=>"Chievres","name_href" => "be/population-of-chievres","count" => "6 198","real_id" =>126,),
"127"=>array("name_ru"=>"Сен-Юбер","name_en"=>"Saint-Hubert","name_href" => "be/population-of-saint-hubert","count" => "5 718","real_id" =>127,),
"128"=>array("name_ru"=>"Лимбур","name_en"=>"Limbourg","name_href" => "be/population-of-limbourg","count" => "5 616","real_id" =>128,),
"129"=>array("name_ru"=>"Буйон","name_en"=>"Bouillon","name_href" => "be/population-of-bouillon","count" => "5 455","real_id" =>129,),
"130"=>array("name_ru"=>"Флоренвиль","name_en"=>"Florenville","name_href" => "be/population-of-florenville","count" => "5 449","real_id" =>130,),
"131"=>array("name_ru"=>"Шини","name_en"=>"Chiny","name_href" => "be/population-of-chiny","count" => "5 013","real_id" =>131,),
"132"=>array("name_ru"=>"Уффализ","name_en"=>"Houffalize","name_href" => "be/population-of-houffalize","count" => "4 749","real_id" =>132,),
"133"=>array("name_ru"=>"Ла-Рош-ан-Арденн","name_en"=>"La Roche-en-Ardenne","name_href" => "be/population-of-la-roche-en-ardenne","count" => "4 267","real_id" =>133,),
"134"=>array("name_ru"=>"Ло-Ренинге","name_en"=>"Lo-Reninge","name_href" => "be/population-of-lo-reninge","count" => "3 306","real_id" =>134,),
"135"=>array("name_ru"=>"Месен","name_en"=>"Mesen","name_href" => "be/population-of-mesen","count" => "952","real_id" =>135,),
"136"=>array("name_ru"=>"Антверпен","name_en"=>"Antwerpen","name_href" => "be/population-of-antwerpen","count" => "472 526","real_id" =>136,),
"137"=>array("name_ru"=>"Гент","name_en"=>"Gent","name_href" => "be/population-of-gent","count" => "233 120","real_id" =>137,),
"138"=>array("name_ru"=>"Шарлеруа","name_en"=>"Charleroi","name_href" => "be/population-of-charleroi","count" => "201 300","real_id" =>138,),
"139"=>array("name_ru"=>"Льеж","name_en"=>"Liege","name_href" => "be/population-of-liege","count" => "186 805","real_id" =>139,),
"140"=>array("name_ru"=>"Брюссель","name_en"=>"Bruxelles, Brussel","name_href" => "be/population-of-bruxelles,-brussel","count" => "144 784","real_id" =>140,)
);

?>