<?php
//Бразилия 110 
$libbr = array ( 
"1"=>array("name_ru"=>"Сан-Паулу","name_en"=>"Sao Paulo","name_href" => "br/population-of-sao-paulo","count" => "11 895 893","real_id" =>1,),
"2"=>array("name_ru"=>"Рио-де-Жанейро","name_en"=>"Rio de Janeiro","name_href" => "br/population-of-rio-de-janeiro","count" => "6 453 682","real_id" =>2,),
"3"=>array("name_ru"=>"Салвадор","name_en"=>"Salvador","name_href" => "br/population-of-salvador","count" => "2 902 927","real_id" =>3,),
"4"=>array("name_ru"=>"Бразилиа","name_en"=>"Brasilia","name_href" => "br/population-of-brasilia","count" => "2 852 372","real_id" =>4,),
"5"=>array("name_ru"=>"Форталеза","name_en"=>"Fortaleza","name_href" => "br/population-of-fortaleza","count" => "2 571 896","real_id" =>5,),
"6"=>array("name_ru"=>"Белу-Оризонти","name_en"=>"Belo Horizonte","name_href" => "br/population-of-belo-horizonte","count" => "2 491 109","real_id" =>6,),
"7"=>array("name_ru"=>"Манаус","name_en"=>"Manaus","name_href" => "br/population-of-manaus","count" => "2 020 301","real_id" =>7,),
"8"=>array("name_ru"=>"Куритиба","name_en"=>"Curitiba","name_href" => "br/population-of-curitiba","count" => "1 864 416","real_id" =>8,),
"9"=>array("name_ru"=>"Ресифи","name_en"=>"Recife","name_href" => "br/population-of-recife","count" => "1 608 488","real_id" =>9,),
"10"=>array("name_ru"=>"Порту-Алегри","name_en"=>"Porto Alegre","name_href" => "br/population-of-porto-alegre","count" => "1 472 482","real_id" =>10,),
"11"=>array("name_ru"=>"Белен","name_en"=>"Belen","name_href" => "br/population-of-belen","count" => "1 432 844","real_id" =>11,),
"12"=>array("name_ru"=>"Гояния","name_en"=>"Goiania","name_href" => "br/population-of-goiania","count" => "1 412 364","real_id" =>12,),
"13"=>array("name_ru"=>"Гуарульюс","name_en"=>"Guarulhos","name_href" => "br/population-of-guarulhos","count" => "1 312 197","real_id" =>13,),
"14"=>array("name_ru"=>"Кампинас","name_en"=>"Campinas","name_href" => "br/population-of-campinas","count" => "1 154 617","real_id" =>14,),
"15"=>array("name_ru"=>"Сан-Луис","name_en"=>"San Luis","name_href" => "br/population-of-san-luis","count" => "1 064 197","real_id" =>15,),
"16"=>array("name_ru"=>"Сан-Гонсалу","name_en"=>"Sao Goncalo","name_href" => "br/population-of-sao-goncalo","count" => "1 031 903","real_id" =>16,),
"17"=>array("name_ru"=>"Масейо","name_en"=>"Maceio","name_href" => "br/population-of-maceio","count" => "1 005 319","real_id" =>17,),
"18"=>array("name_ru"=>"Дуки-ди-Кашиас","name_en"=>"Duque de Caxias","name_href" => "br/population-of-duque-de-caxias","count" => "878 402","real_id" =>18,),
"19"=>array("name_ru"=>"Натал","name_en"=>"Natal","name_href" => "br/population-of-natal","count" => "862 044","real_id" =>19,),
"20"=>array("name_ru"=>"Кампу-Гранди","name_en"=>"Campo Grande","name_href" => "br/population-of-campo-grande","count" => "843 120","real_id" =>20,),
"21"=>array("name_ru"=>"Терезина","name_en"=>"Teresina","name_href" => "br/population-of-teresina","count" => "840 600","real_id" =>21,),
"22"=>array("name_ru"=>"Сан-Бернарду-ду-Кампу","name_en"=>"Sao Bernardo do Campo","name_href" => "br/population-of-sao-bernardo-do-campo","count" => "811 489","real_id" =>22,),
"23"=>array("name_ru"=>"Нова-Игуасу","name_en"=>"Nova Iguaçu","name_href" => "br/population-of-nova-iguaçu","count" => "806 177","real_id" =>23,),
"24"=>array("name_ru"=>"Жуан-Песоа","name_en"=>"Joao Pessoa","name_href" => "br/population-of-joao-pessoa","count" => "780 738","real_id" =>24,),
"25"=>array("name_ru"=>"Санту-Андре","name_en"=>"Santo André","name_href" => "br/population-of-santo-andré","count" => "707 613","real_id" =>25,),
"26"=>array("name_ru"=>"Озаску","name_en"=>"Osasco","name_href" => "br/population-of-osasco","count" => "693 271","real_id" =>26,),
"27"=>array("name_ru"=>"Сан-Жозе-дус-Кампус","name_en"=>"São josé DOS Campos","name_href" => "br/population-of-são-josé-dos-campos","count" => "681 036","real_id" =>27,),
"28"=>array("name_ru"=>"Жабуатан-дус-Гуарарапис","name_en"=>"Jabatan DOS Guararapes","name_href" => "br/population-of-jabatan-dos-guararapes","count" => "680 943","real_id" =>28,),
"29"=>array("name_ru"=>"Рибейран-Прету","name_en"=>"Ribeirão Preto","name_href" => "br/population-of-ribeirão-preto","count" => "658 059","real_id" =>29,),
"30"=>array("name_ru"=>"Уберландия","name_en"=>"Uberlândia","name_href" => "br/population-of-uberlândia","count" => "654 681","real_id" =>30,),
"31"=>array("name_ru"=>"Контажен","name_en"=>"Contagem","name_href" => "br/population-of-contagem","count" => "643 476","real_id" =>31,),
"32"=>array("name_ru"=>"Сорокаба","name_en"=>"Sorocaba","name_href" => "br/population-of-sorocaba","count" => "637 187","real_id" =>32,),
"33"=>array("name_ru"=>"Аракажу","name_en"=>"Aracaju","name_href" => "br/population-of-aracaju","count" => "623 766","real_id" =>33,),
"34"=>array("name_ru"=>"Фейра-ди-Сантана","name_en"=>"Feira de Santana","name_href" => "br/population-of-feira-de-santana","count" => "612 000","real_id" =>34,),
"35"=>array("name_ru"=>"Куяба","name_en"=>"Cuiaba","name_href" => "br/population-of-cuiaba","count" => "575 480","real_id" =>35,),
"36"=>array("name_ru"=>"Жоинвили","name_en"=>"Joinville","name_href" => "br/population-of-joinville","count" => "554 601","real_id" =>36,),
"37"=>array("name_ru"=>"Жуис-ди-Фора","name_en"=>"The most popular locales-di-fora","name_href" => "br/population-of-the-most-popular-locales-di-fora","count" => "550 710","real_id" =>37,),
"38"=>array("name_ru"=>"Лондрина","name_en"=>"Londrina","name_href" => "br/population-of-londrina","count" => "543 003","real_id" =>38,),
"39"=>array("name_ru"=>"Апаресида-ди-Гояния","name_en"=>"Aparecida de Goiania","name_href" => "br/population-of-aparecida-de-goiania","count" => "511 323","real_id" =>39,),
"40"=>array("name_ru"=>"Ананиндеуа","name_en"=>"Ananindeua","name_href" => "br/population-of-ananindeua","count" => "499 776","real_id" =>40,),
"41"=>array("name_ru"=>"Нитерой","name_en"=>"Niteroi","name_href" => "br/population-of-niteroi","count" => "495 470","real_id" =>41,),
"42"=>array("name_ru"=>"Порту-Велью","name_en"=>"Porto Velho","name_href" => "br/population-of-porto-velho","count" => "494 013","real_id" =>42,),
"43"=>array("name_ru"=>"Кампус-дус-Гойтаказис","name_en"=>"Campos DOS Goytacazes","name_href" => "br/population-of-campos-dos-goytacazes","count" => "480 648","real_id" =>43,),
"44"=>array("name_ru"=>"Белфорд-Рошу","name_en"=>"Belford Roxo","name_href" => "br/population-of-belford-roxo","count" => "479 386","real_id" =>44,),
"45"=>array("name_ru"=>"Серра","name_en"=>"Serra","name_href" => "br/population-of-serra","count" => "476 428","real_id" =>45,),
"46"=>array("name_ru"=>"Кашиас-ду-Сул","name_en"=>"Caxias do Sul","name_href" => "br/population-of-caxias-do-sul","count" => "470 223","real_id" =>46,),
"47"=>array("name_ru"=>"Вила-Велья","name_en"=>"Vila Velha","name_href" => "br/population-of-vila-velha","count" => "465 690","real_id" =>47,),
"48"=>array("name_ru"=>"Флорианополис","name_en"=>"Florianopolis","name_href" => "br/population-of-florianopolis","count" => "461 524","real_id" =>48,),
"49"=>array("name_ru"=>"Сан-Жуан-ди-Мерити","name_en"=>"San-Juan-de-Meriti","name_href" => "br/population-of-san-juan-de-meriti","count" => "460 711","real_id" =>49,),
"50"=>array("name_ru"=>"Мауа","name_en"=>"Maua","name_href" => "br/population-of-maua","count" => "448 776","real_id" =>50,),
"51"=>array("name_ru"=>"Макапа","name_en"=>"Macapá","name_href" => "br/population-of-macapá","count" => "446 757","real_id" =>51,),
"52"=>array("name_ru"=>"Сан-Жозе-ду-Риу-Прету","name_en"=>"Sao Jose do Rio Preto","name_href" => "br/population-of-sao-jose-do-rio-preto","count" => "438 354","real_id" =>52,),
"53"=>array("name_ru"=>"Сантус","name_en"=>"Santos","name_href" => "br/population-of-santos","count" => "433 565","real_id" =>53,),
"54"=>array("name_ru"=>"Можи-дас-Крузис","name_en"=>"Mogi das Cruzes","name_href" => "br/population-of-mogi-das-cruzes","count" => "419 839","real_id" =>54,),
"55"=>array("name_ru"=>"Бетин","name_en"=>"Betin","name_href" => "br/population-of-betin","count" => "412 003","real_id" =>55,),
"56"=>array("name_ru"=>"Диадема","name_en"=>"Diadema","name_href" => "br/population-of-diadema","count" => "409 613","real_id" =>56,),
"57"=>array("name_ru"=>"Кампина-Гранди","name_en"=>"Campina Grande","name_href" => "br/population-of-campina-grande","count" => "402 912","real_id" =>57,),
"58"=>array("name_ru"=>"Жундиаи","name_en"=>"Jundiaí","name_href" => "br/population-of-jundiaí","count" => "397 965","real_id" =>58,),
"59"=>array("name_ru"=>"Маринга","name_en"=>"Maringa","name_href" => "br/population-of-maringa","count" => "391 698","real_id" =>59,),
"60"=>array("name_ru"=>"Монтис-Кларус","name_en"=>"Montes Claros","name_href" => "br/population-of-montes-claros","count" => "390 212","real_id" =>60,),
"61"=>array("name_ru"=>"Карапикуиба","name_en"=>"Carapicuiba","name_href" => "br/population-of-carapicuiba","count" => "390 073","real_id" =>61,),
"62"=>array("name_ru"=>"Олинда","name_en"=>"Olinda","name_href" => "br/population-of-olinda","count" => "388 821","real_id" =>62,),
"63"=>array("name_ru"=>"Пирасикаба","name_en"=>"Piracicaba","name_href" => "br/population-of-piracicaba","count" => "388 412","real_id" =>63,),
"64"=>array("name_ru"=>"Кариасика","name_en"=>"Cariacica","name_href" => "br/population-of-cariacica","count" => "378 915","real_id" =>64,),
"65"=>array("name_ru"=>"Бауру","name_en"=>"Bauru","name_href" => "br/population-of-bauru","count" => "364 562","real_id" =>65,),
"66"=>array("name_ru"=>"Риу-Бранку","name_en"=>"Rio Branco","name_href" => "br/population-of-rio-branco","count" => "363 928","real_id" =>66,),
"67"=>array("name_ru"=>"Анаполис","name_en"=>"Annapolis","name_href" => "br/population-of-annapolis","count" => "361 991","real_id" =>67,),
"68"=>array("name_ru"=>"Сан-Висенти","name_en"=>"San Vicente","name_href" => "br/population-of-san-vicente","count" => "353 040","real_id" =>68,),
"69"=>array("name_ru"=>"Витория","name_en"=>"Vitoria","name_href" => "br/population-of-vitoria","count" => "352 104","real_id" =>69,),
"70"=>array("name_ru"=>"Каукая","name_en"=>"Caucaia","name_href" => "br/population-of-caucaia","count" => "349 526","real_id" =>70,),
"71"=>array("name_ru"=>"Итакуакесетуба","name_en"=>"Itaquaquecetuba","name_href" => "br/population-of-itaquaquecetuba","count" => "348 739","real_id" =>71,),
"72"=>array("name_ru"=>"Каруару","name_en"=>"Caruaru","name_href" => "br/population-of-caruaru","count" => "342 328","real_id" =>72,),
"73"=>array("name_ru"=>"Пелотас","name_en"=>"Pelotas","name_href" => "br/population-of-pelotas","count" => "342 053","real_id" =>73,),
"74"=>array("name_ru"=>"Витория-да-Конкиста","name_en"=>"Vitoria da Conquista","name_href" => "br/population-of-vitoria-da-conquista","count" => "340 199","real_id" =>74,),
"75"=>array("name_ru"=>"Каноас","name_en"=>"Canoas","name_href" => "br/population-of-canoas","count" => "339 979","real_id" =>75,),
"76"=>array("name_ru"=>"Франка","name_en"=>"Frank","name_href" => "br/population-of-frank","count" => "339 461","real_id" =>76,),
"77"=>array("name_ru"=>"Понта-Гросса","name_en"=>"Ponta Grossa","name_href" => "br/population-of-ponta-grossa","count" => "334 535","real_id" =>77,),
"78"=>array("name_ru"=>"Блуменау","name_en"=>"Blumenau","name_href" => "br/population-of-blumenau","count" => "334 002","real_id" =>78,),
"79"=>array("name_ru"=>"Петролина","name_en"=>"Petrolina","name_href" => "br/population-of-petrolina","count" => "326 017","real_id" =>79,),
"80"=>array("name_ru"=>"Паулиста","name_en"=>"Paulista","name_href" => "br/population-of-paulista","count" => "319 769","real_id" =>80,),
"81"=>array("name_ru"=>"Рибейран-дас-Невис","name_en"=>"Ribeirao das Neves","name_href" => "br/population-of-ribeirao-das-neves","count" => "319 310","real_id" =>81,),
"82"=>array("name_ru"=>"Убераба","name_en"=>"Uberaba","name_href" => "br/population-of-uberaba","count" => "318 813","real_id" =>82,),
"83"=>array("name_ru"=>"Боа-Виста","name_en"=>"Boa Vista","name_href" => "br/population-of-boa-vista","count" => "314 900","real_id" =>83,),
"84"=>array("name_ru"=>"Каскавел","name_en"=>"Cascavel","name_href" => "br/population-of-cascavel","count" => "309 259","real_id" =>84,),
"85"=>array("name_ru"=>"Гуаружа","name_en"=>"Guaruja","name_href" => "br/population-of-guaruja","count" => "308 989","real_id" =>85,),
"86"=>array("name_ru"=>"Таубате","name_en"=>"Taubate","name_href" => "br/population-of-taubate","count" => "299 423","real_id" =>86,),
"87"=>array("name_ru"=>"Петрополис","name_en"=>"Petropolis","name_href" => "br/population-of-petropolis","count" => "298 017","real_id" =>87,),
"88"=>array("name_ru"=>"Лимейра","name_en"=>"Limeira","name_href" => "br/population-of-limeira","count" => "294 128","real_id" =>88,),
"89"=>array("name_ru"=>"Прая-Гранди","name_en"=>"Praia Grande","name_href" => "br/population-of-praia-grande","count" => "293 695","real_id" =>89,),
"90"=>array("name_ru"=>"Сан-Жозе-дус-Пиньяйс","name_en"=>"Sao Jose DOS Pinhais","name_href" => "br/population-of-sao-jose-dos-pinhais","count" => "292 934","real_id" =>90,),
"91"=>array("name_ru"=>"Сантарен","name_en"=>"Santarem","name_href" => "br/population-of-santarem","count" => "290 521","real_id" =>91,),
"92"=>array("name_ru"=>"Мосоро","name_en"=>"Mossoró","name_href" => "br/population-of-mossoró","count" => "284 288","real_id" =>92,),
"93"=>array("name_ru"=>"Сузану","name_en"=>"Suzano","name_href" => "br/population-of-suzano","count" => "282 441","real_id" =>93,),
"94"=>array("name_ru"=>"Камасари","name_en"=>"Camacari","name_href" => "br/population-of-camacari","count" => "281 413","real_id" =>94,),
"95"=>array("name_ru"=>"Говернадор-Валадарис","name_en"=>"Governador Valadares","name_href" => "br/population-of-governador-valadares","count" => "276 995","real_id" =>95,),
"96"=>array("name_ru"=>"Санта-Мария","name_en"=>"Santa Maria","name_href" => "br/population-of-santa-maria","count" => "274 838","real_id" =>96,),
"97"=>array("name_ru"=>"Граватаи","name_en"=>"Gravatai","name_href" => "br/population-of-gravatai","count" => "270 689","real_id" =>97,),
"98"=>array("name_ru"=>"Табоан-да-Серра","name_en"=>"Taboao da Serra","name_href" => "br/population-of-taboao-da-serra","count" => "268 321","real_id" =>98,),
"99"=>array("name_ru"=>"Варзеа-Гранди","name_en"=>"Várzea Grande","name_href" => "br/population-of-várzea-grande","count" => "265 775","real_id" =>99,),
"100"=>array("name_ru"=>"Палмас","name_en"=>"Palmas","name_href" => "br/population-of-palmas","count" => "265 409","real_id" =>100,),
"101"=>array("name_ru"=>"Жуазейру-ду-Норти","name_en"=>"Juazeiro do Norte","name_href" => "br/population-of-juazeiro-do-norte","count" => "263 704","real_id" =>101,),
"102"=>array("name_ru"=>"Фос-ду-Игуасу","name_en"=>"Foz do iguaçu","name_href" => "br/population-of-foz-do-iguaçu","count" => "263 647","real_id" =>102,),
"103"=>array("name_ru"=>"Сумаре","name_en"=>"Sumare","name_href" => "br/population-of-sumare","count" => "262 308","real_id" =>103,),
"104"=>array("name_ru"=>"Волта-Редонда","name_en"=>"Volta Redonda","name_href" => "br/population-of-volta-redonda","count" => "262 259","real_id" =>104,),
"105"=>array("name_ru"=>"Баруэри","name_en"=>"Barueri","name_href" => "br/population-of-barueri","count" => "259 555","real_id" =>105,),
"106"=>array("name_ru"=>"Эмбу","name_en"=>"Embu","name_href" => "br/population-of-embu","count" => "259 053","real_id" =>106,),
"107"=>array("name_ru"=>"Мараба","name_en"=>"Maraba","name_href" => "br/population-of-maraba","count" => "257 062","real_id" =>107,),
"108"=>array("name_ru"=>"Ипатинга","name_en"=>"Ipatinga","name_href" => "br/population-of-ipatinga","count" => "255 266","real_id" =>108,),
"109"=>array("name_ru"=>"Императрис","name_en"=>"Imperatriz","name_href" => "br/population-of-imperatriz","count" => "252 320","real_id" =>109,),
"110"=>array("name_ru"=>"Виаман","name_en"=>"Viamao","name_href" => "br/population-of-viamao","count" => "251 033","real_id" =>110,),
"111"=>array("name_ru"=>"Сан-Паулу","name_en"=>"Sao Paulo","name_href" => "br/population-of-sao-paulo","count" => "11 895 893","real_id" =>111,),
"112"=>array("name_ru"=>"Рио-де-Жанейро","name_en"=>"Rio de Janeiro","name_href" => "br/population-of-rio-de-janeiro","count" => "6 453 682","real_id" =>112,),
"113"=>array("name_ru"=>"Салвадор","name_en"=>"Salvador","name_href" => "br/population-of-salvador","count" => "2 902 927","real_id" =>113,),
"114"=>array("name_ru"=>"Бразилиа","name_en"=>"Brasilia","name_href" => "br/population-of-brasilia","count" => "2 852 372","real_id" =>114,),
"115"=>array("name_ru"=>"Форталеза","name_en"=>"Fortaleza","name_href" => "br/population-of-fortaleza","count" => "2 571 896","real_id" =>115,)
);

?>