<?php
//БуркинаФасо 43 
$libbf = array ( 

"1"=>array("name_ru"=>"Уагадугу","name_en"=>"Ouagadougou","name_href" => "bf/population-of-ouagadougou","count" => "1 181 702","real_id" =>1,),
"2"=>array("name_ru"=>"Бобо-Диуласо","name_en"=>"Bobo-Dioulasso","name_href" => "bf/population-of-bobo-dioulasso","count" => "435 543","real_id" =>2,),
"3"=>array("name_ru"=>"Кудугу","name_en"=>"Koudougou","name_href" => "bf/population-of-koudougou","count" => "82 720","real_id" =>3,),
"4"=>array("name_ru"=>"Банфора","name_en"=>"Banfora","name_href" => "bf/population-of-banfora","count" => "72 144","real_id" =>4,),
"5"=>array("name_ru"=>"Уахигуя","name_en"=>"Ouahigouya","name_href" => "bf/population-of-ouahigouya","count" => "70 957","real_id" =>5,),
"6"=>array("name_ru"=>"Пуйтенга","name_en"=>"Pouytenga","name_href" => "bf/population-of-pouytenga","count" => "55 000","real_id" =>6,),
"7"=>array("name_ru"=>"Кая","name_en"=>"Kai","name_href" => "bf/population-of-kai","count" => "51 778","real_id" =>7,),
"8"=>array("name_ru"=>"Тенкодого","name_en"=>"Tenkodogo","name_href" => "bf/population-of-tenkodogo","count" => "40 839","real_id" =>8,),
"9"=>array("name_ru"=>"Фада-Нгурма","name_en"=>"Fada-Ngurma","name_href" => "bf/population-of-fada-ngurma","count" => "40 815","real_id" =>9,),
"10"=>array("name_ru"=>"Дедугу","name_en"=>"Dedugu","name_href" => "bf/population-of-dedugu","count" => "37 793","real_id" =>10,),
"11"=>array("name_ru"=>"Гаранго","name_en"=>"Garango","name_href" => "bf/population-of-garango","count" => "36 000","real_id" =>11,),
"12"=>array("name_ru"=>"Хунде","name_en"=>"Honda","name_href" => "bf/population-of-honda","count" => "34 669","real_id" =>12,),
"13"=>array("name_ru"=>"Джибо","name_en"=>"Djibo","name_href" => "bf/population-of-djibo","count" => "29 162","real_id" =>13,),
"14"=>array("name_ru"=>"Купела","name_en"=>"Kupala","name_href" => "bf/population-of-kupala","count" => "28 000","real_id" =>14,),
"15"=>array("name_ru"=>"Рео","name_en"=>"REO","name_href" => "bf/population-of-reo","count" => "27 209","real_id" =>15,),
"16"=>array("name_ru"=>"Лео","name_en"=>"Leo","name_href" => "bf/population-of-leo","count" => "26 183","real_id" =>16,),
"17"=>array("name_ru"=>"Конгуси","name_en"=>"Congue","name_href" => "bf/population-of-congue","count" => "24 583","real_id" =>17,),
"18"=>array("name_ru"=>"Гауа","name_en"=>"Granville lake","name_href" => "bf/population-of-granville-lake","count" => "24 414","real_id" =>18,),
"19"=>array("name_ru"=>"Гурси","name_en"=>"Gorse","name_href" => "bf/population-of-gorse","count" => "24 240","real_id" =>19,),
"20"=>array("name_ru"=>"По","name_en"=>"At","name_href" => "bf/population-of-at","count" => "23 842","real_id" =>20,),
"21"=>array("name_ru"=>"Комбисири","name_en"=>"Kombissiri","name_href" => "bf/population-of-kombissiri","count" => "22 585","real_id" =>21,),
"22"=>array("name_ru"=>"Яко","name_en"=>"Yako","name_href" => "bf/population-of-yako","count" => "21 338","real_id" =>22,),
"23"=>array("name_ru"=>"Ньянголоко","name_en"=>"Niangoloko","name_href" => "bf/population-of-niangoloko","count" => "20 377","real_id" =>23,),
"24"=>array("name_ru"=>"Дори","name_en"=>"Dori","name_href" => "bf/population-of-dori","count" => "20 244","real_id" =>24,),
"25"=>array("name_ru"=>"Ородара","name_en"=>"Orodara","name_href" => "bf/population-of-orodara","count" => "19 490","real_id" =>25,),
"26"=>array("name_ru"=>"Зорго","name_en"=>"Sorgo","name_href" => "bf/population-of-sorgo","count" => "19 278","real_id" =>26,),
"27"=>array("name_ru"=>"Манга","name_en"=>"Manga","name_href" => "bf/population-of-manga","count" => "18 861","real_id" =>27,),
"28"=>array("name_ru"=>"Титао","name_en"=>"Tito","name_href" => "bf/population-of-tito","count" => "18 762","real_id" =>28,),
"29"=>array("name_ru"=>"Нуна","name_en"=>"Noona","name_href" => "bf/population-of-noona","count" => "18 440","real_id" =>29,),
"30"=>array("name_ru"=>"Туган","name_en"=>"Tugan","name_href" => "bf/population-of-tugan","count" => "17 548","real_id" =>30,),
"31"=>array("name_ru"=>"Диебугу","name_en"=>"Diebugu","name_href" => "bf/population-of-diebugu","count" => "17 226","real_id" =>31,),
"32"=>array("name_ru"=>"Зиниари","name_en"=>"Siniari","name_href" => "bf/population-of-siniari","count" => "17 056","real_id" =>32,),
"33"=>array("name_ru"=>"Булса","name_en"=>"Bulls","name_href" => "bf/population-of-bulls","count" => "16 753","real_id" =>33,),
"34"=>array("name_ru"=>"Дано","name_en"=>"Given","name_href" => "bf/population-of-given","count" => "16 085","real_id" =>34,),
"35"=>array("name_ru"=>"Битту","name_en"=>"Beatty","name_href" => "bf/population-of-beatty","count" => "15 000","real_id" =>35,),
"36"=>array("name_ru"=>"Боромо","name_en"=>"Boromo","name_href" => "bf/population-of-boromo","count" => "14 885","real_id" =>36,),
"37"=>array("name_ru"=>"Буссе","name_en"=>"Busse","name_href" => "bf/population-of-busse","count" => "14 189","real_id" =>37,),
"38"=>array("name_ru"=>"Соленцо","name_en"=>"Solenzo","name_href" => "bf/population-of-solenzo","count" => "12 597","real_id" =>38,),
"39"=>array("name_ru"=>"Тома","name_en"=>"Tom","name_href" => "bf/population-of-tom","count" => "11 950","real_id" =>39,),
"40"=>array("name_ru"=>"Боганде","name_en"=>"Bogande","name_href" => "bf/population-of-bogande","count" => "11 913","real_id" =>40,),
"41"=>array("name_ru"=>"Сапоу","name_en"=>"Sapo","name_href" => "bf/population-of-sapo","count" => "11 368","real_id" =>41,),
"42"=>array("name_ru"=>"Батие","name_en"=>"Batie","name_href" => "bf/population-of-batie","count" => "10 135","real_id" =>42,),
"43"=>array("name_ru"=>"Уаргайе","name_en"=>"Ouargaye","name_href" => "bf/population-of-ouargaye","count" => "10 100","real_id" =>43,),
"44"=>array("name_ru"=>"Уагадугу","name_en"=>"Ouagadougou","name_href" => "bf/population-of-ouagadougou","count" => "1 181 702","real_id" =>44,),
"45"=>array("name_ru"=>"Бобо-Диуласо","name_en"=>"Bobo-Dioulasso","name_href" => "bf/population-of-bobo-dioulasso","count" => "435 543","real_id" =>45,),
"46"=>array("name_ru"=>"Кудугу","name_en"=>"Koudougou","name_href" => "bf/population-of-koudougou","count" => "82 720","real_id" =>46,),
"47"=>array("name_ru"=>"Банфора","name_en"=>"Banfora","name_href" => "bf/population-of-banfora","count" => "72 144","real_id" =>47,),
"48"=>array("name_ru"=>"Уахигуя","name_en"=>"Ouahigouya","name_href" => "bf/population-of-ouahigouya","count" => "70 957","real_id" =>48,)
);

?>