<?php
//Бангладеш 43 
$libbd = array ( 

"1"=>array("name_ru"=>"Дакка","name_en"=>"Dhaka","name_href" => "bd/population-of-dhaka","count" => "8 906 039","real_id" =>1,),
"2"=>array("name_ru"=>"Читтагонг","name_en"=>"Chittagong","name_href" => "bd/population-of-chittagong","count" => "2 592 439","real_id" =>2,),
"3"=>array("name_ru"=>"Кхулна","name_en"=>"Khulna","name_href" => "bd/population-of-khulna","count" => "664 728","real_id" =>3,),
"4"=>array("name_ru"=>"Силхет","name_en"=>"Sylhet","name_href" => "bd/population-of-sylhet","count" => "526 412","real_id" =>4,),
"5"=>array("name_ru"=>"Раджшахи","name_en"=>"Rajshahi","name_href" => "bd/population-of-rajshahi","count" => "451 425","real_id" =>5,),
"6"=>array("name_ru"=>"Тонги","name_en"=>"Tongi","name_href" => "bd/population-of-tongi","count" => "406 420","real_id" =>6,),
"7"=>array("name_ru"=>"Богра","name_en"=>"Bogra","name_href" => "bd/population-of-bogra","count" => "400 983","real_id" =>7,),
"8"=>array("name_ru"=>"Мименсингх","name_en"=>"Mymensingh","name_href" => "bd/population-of-mymensingh","count" => "389 918","real_id" =>8,),
"9"=>array("name_ru"=>"Барисал","name_en"=>"Barisal","name_href" => "bd/population-of-barisal","count" => "339 308","real_id" =>9,),
"10"=>array("name_ru"=>"Рангпур","name_en"=>"Rangpur ","name_href" => "bd/population-of-rangpur","count" => "307 053","real_id" =>10,),
"11"=>array("name_ru"=>"Савар","name_en"=>"Savar","name_href" => "bd/population-of-savar","count" => "296 851","real_id" =>11,),
"12"=>array("name_ru"=>"Комилла","name_en"=>"Comilla","name_href" => "bd/population-of-comilla","count" => "296 010","real_id" =>12,),
"13"=>array("name_ru"=>"Нараянгандж","name_en"=>"Narayanganj","name_href" => "bd/population-of-narayanganj","count" => "286 330","real_id" =>13,),
"14"=>array("name_ru"=>"Шиддхиргандж","name_en"=>"Siddhirganj","name_href" => "bd/population-of-siddhirganj","count" => "256 760","real_id" =>14,),
"15"=>array("name_ru"=>"Джессор","name_en"=>"Jessore ","name_href" => "bd/population-of-jessore","count" => "237 478","real_id" =>15,),
"16"=>array("name_ru"=>"Кокс-Базар","name_en"=>"Cox's Bazar","name_href" => "bd/population-of-coxs-bazar","count" => "223 522","real_id" =>16,),
"17"=>array("name_ru"=>"Газипур","name_en"=>"Gazipur ","name_href" => "bd/population-of-gazipur","count" => "213 061","real_id" =>17,),
"18"=>array("name_ru"=>"Брахманбария","name_en"=>"Brahmanbaria","name_href" => "bd/population-of-brahmanbaria","count" => "193 814","real_id" =>18,),
"19"=>array("name_ru"=>"Динаджпур","name_en"=>"Dinajpur","name_href" => "bd/population-of-dinajpur","count" => "191 329","real_id" =>19,),
"20"=>array("name_ru"=>"Нарсингди","name_en"=>"Narsingdi","name_href" => "bd/population-of-narsingdi","count" => "185 128","real_id" =>20,),
"21"=>array("name_ru"=>"Навабгандж","name_en"=>"Nawabganj ","name_href" => "bd/population-of-nawabganj","count" => "180 731","real_id" =>21,),
"22"=>array("name_ru"=>"Чандпур","name_en"=>"Chandpur ","name_href" => "bd/population-of-chandpur","count" => "171 065","real_id" =>22,),
"23"=>array("name_ru"=>"Тангайл","name_en"=>"Tangail","name_href" => "bd/population-of-tangail","count" => "167 412","real_id" =>23,),
"24"=>array("name_ru"=>"Сираджгандж","name_en"=>"Sirajganj","name_href" => "bd/population-of-sirajganj","count" => "167 200","real_id" =>24,),
"25"=>array("name_ru"=>"Кадам-Расул ","name_en"=>"Kadam-Rasul","name_href" => "bd/population-of-kadam-rasul","count" => "166 291","real_id" =>25,),
"26"=>array("name_ru"=>"Калиакаир","name_en"=>"Kaliakair","name_href" => "bd/population-of-kaliakair","count" => "163 498","real_id" =>26,),
"27"=>array("name_ru"=>"Фени","name_en"=>"Feni","name_href" => "bd/population-of-feni","count" => "156 971","real_id" =>27,),
"28"=>array("name_ru"=>"Тарабо","name_en"=>"Taraba","name_href" => "bd/population-of-taraba","count" => "150 709","real_id" =>28,),
"29"=>array("name_ru"=>"Наогаон","name_en"=>"Naogaon","name_href" => "bd/population-of-naogaon","count" => "150 549","real_id" =>29,),
"30"=>array("name_ru"=>"Джамалпур","name_en"=>"Jamalpur","name_href" => "bd/population-of-jamalpur","count" => "150 172","real_id" =>30,),
"31"=>array("name_ru"=>"Пабна","name_en"=>"Pabna","name_href" => "bd/population-of-pabna","count" => "144 442","real_id" =>31,),
"32"=>array("name_ru"=>"Саидпур","name_en"=>"Saidpur","name_href" => "bd/population-of-saidpur","count" => "133 433","real_id" =>32,),
"33"=>array("name_ru"=>"Бегумгандж","name_en"=>"Begumganj","name_href" => "bd/population-of-begumganj","count" => "132 948","real_id" =>33,),
"34"=>array("name_ru"=>"Ноакхали","name_en"=>"Noakhali","name_href" => "bd/population-of-noakhali","count" => "130 842","real_id" =>34,),
"35"=>array("name_ru"=>"Чуаданга","name_en"=>"In Barisal","name_href" => "bd/population-of-in-barisal","count" => "128 865","real_id" =>35,),
"36"=>array("name_ru"=>"Шрипур","name_en"=>"Sripur","name_href" => "bd/population-of-sripur","count" => "126 249","real_id" =>36,),
"37"=>array("name_ru"=>"Фаридпур","name_en"=>"Faridpur","name_href" => "bd/population-of-faridpur","count" => "122 425","real_id" =>37,),
"38"=>array("name_ru"=>"Бхайраб","name_en"=>"Bhairab","name_href" => "bd/population-of-bhairab","count" => "118 992","real_id" =>38,),
"39"=>array("name_ru"=>"Саткхира","name_en"=>"Satkhira","name_href" => "bd/population-of-satkhira","count" => "113 322","real_id" =>39,),
"40"=>array("name_ru"=>"Комилла-Садар-Дакшин","name_en"=>"Comilla-Sadar Dakshin","name_href" => "bd/population-of-comilla-sadar-dakshin","count" => "111 891","real_id" =>40,),
"41"=>array("name_ru"=>"Дженайда","name_en"=>"Jessore","name_href" => "bd/population-of-jessore","count" => "110 541","real_id" =>41,),
"42"=>array("name_ru"=>"Куштия","name_en"=>"Kushtia","name_href" => "bd/population-of-kushtia","count" => "108 423","real_id" =>42,),
"43"=>array("name_ru"=>"Кишоргандж","name_en"=>"Kishoreganj","name_href" => "bd/population-of-kishoreganj","count" => "103 798","real_id" =>43,),
"44"=>array("name_ru"=>"Дакка","name_en"=>"Dhaka","name_href" => "bd/population-of-dhaka","count" => "8 906 039","real_id" =>44,),
"45"=>array("name_ru"=>"Читтагонг","name_en"=>"Chittagong","name_href" => "bd/population-of-chittagong","count" => "2 592 439","real_id" =>45,),
"46"=>array("name_ru"=>"Кхулна","name_en"=>"Khulna","name_href" => "bd/population-of-khulna","count" => "664 728","real_id" =>46,),
"47"=>array("name_ru"=>"Силхет","name_en"=>"Sylhet","name_href" => "bd/population-of-sylhet","count" => "526 412","real_id" =>47,),
"48"=>array("name_ru"=>"Раджшахи","name_en"=>"Rajshahi","name_href" => "bd/population-of-rajshahi","count" => "451 425","real_id" =>48,)
);

?>