<?php
//Боливия 35 
$libbo = array ( 
"1"=>array("name_ru"=>"Санта-Крус-де-ла-Сьерра","name_en"=>"Santa Cruz de La Sierra","name_href" => "bo/population-of-santa-cruz-de-la-sierra","count" => "1 545 161","real_id" =>1,),
"2"=>array("name_ru"=>"Эль-Альто","name_en"=>"El Alto","name_href" => "bo/population-of-el-alto","count" => "907 887","real_id" =>2,),
"3"=>array("name_ru"=>"Ла-Пас — фактическая столица","name_en"=>"La Paz is the actual capital","name_href" => "bo/population-of-la-paz-is-the-actual-capital","count" => "877 363","real_id" =>3,),
"4"=>array("name_ru"=>"Кочабамба","name_en"=>"Cochabamba","name_href" => "bo/population-of-cochabamba","count" => "608 276","real_id" =>4,),
"5"=>array("name_ru"=>"Сукре — столица","name_en"=>"Sucre is the capital","name_href" => "bo/population-of-sucre-is-the-capital","count" => "281 240","real_id" =>5,),
"6"=>array("name_ru"=>"Оруро","name_en"=>"Oruro","name_href" => "bo/population-of-oruro","count" => "228 624","real_id" =>6,),
"7"=>array("name_ru"=>"Тариха","name_en"=>"Tarija","name_href" => "bo/population-of-tarija","count" => "194 768","real_id" =>7,),
"8"=>array("name_ru"=>"Потоси","name_en"=>"Potosi","name_href" => "bo/population-of-potosi","count" => "160 648","real_id" =>8,),
"9"=>array("name_ru"=>"Сакаба","name_en"=>"Sakaba","name_href" => "bo/population-of-sakaba","count" => "104 285","real_id" =>9,),
"10"=>array("name_ru"=>"Монтеро","name_en"=>"Montero","name_href" => "bo/population-of-montero","count" => "98 078","real_id" =>10,),
"11"=>array("name_ru"=>"Тринидад","name_en"=>"Trinidad","name_href" => "bo/population-of-trinidad","count" => "92 050","real_id" =>11,),
"12"=>array("name_ru"=>"Риберальта","name_en"=>"Riberalta","name_href" => "bo/population-of-riberalta","count" => "84 888","real_id" =>12,),
"13"=>array("name_ru"=>"Якуиба","name_en"=>"Yacuiba","name_href" => "bo/population-of-yacuiba","count" => "84 779","real_id" =>13,),
"14"=>array("name_ru"=>"Кильякольо","name_en"=>"Quillacollo","name_href" => "bo/population-of-quillacollo","count" => "84 548","real_id" =>14,),
"15"=>array("name_ru"=>"Колькапируа","name_en"=>"Colcapirhua","name_href" => "bo/population-of-colcapirhua","count" => "47 041","real_id" =>15,),
"16"=>array("name_ru"=>"Кобиха","name_en"=>"Cobija","name_href" => "bo/population-of-cobija","count" => "40 125","real_id" =>16,),
"17"=>array("name_ru"=>"Гуаярамерин","name_en"=>"Guayaramerin","name_href" => "bo/population-of-guayaramerin","count" => "37 121","real_id" =>17,),
"18"=>array("name_ru"=>"Вьяча","name_en"=>"Viaca","name_href" => "bo/population-of-viaca","count" => "35 102","real_id" =>18,),
"19"=>array("name_ru"=>"Вильясон","name_en"=>"Villazón","name_href" => "bo/population-of-villazón","count" => "33 943","real_id" =>19,),
"20"=>array("name_ru"=>"Камири","name_en"=>"Camiri","name_href" => "bo/population-of-camiri","count" => "32 670","real_id" =>20,),
"21"=>array("name_ru"=>"Бермехо","name_en"=>"Bermejo","name_href" => "bo/population-of-bermejo","count" => "32 140","real_id" =>21,),
"22"=>array("name_ru"=>"Тикипая","name_en"=>"Ticipa","name_href" => "bo/population-of-ticipa","count" => "30 227","real_id" =>22,),
"23"=>array("name_ru"=>"Льяльягуа","name_en"=>"Llallagua","name_href" => "bo/population-of-llallagua","count" => "28 069","real_id" =>23,),
"24"=>array("name_ru"=>"Эль-Кармен","name_en"=>"El Carmen","name_href" => "bo/population-of-el-carmen","count" => "26 548","real_id" =>24,),
"25"=>array("name_ru"=>"Сан-Игнасио-де-Веласко","name_en"=>"San Ignacio de Velasco","name_href" => "bo/population-of-san-ignacio-de-velasco","count" => "26 535","real_id" =>25,),
"26"=>array("name_ru"=>"Варнес","name_en"=>"Varnes","name_href" => "bo/population-of-varnes","count" => "25 619","real_id" =>26,),
"27"=>array("name_ru"=>"Туписа","name_en"=>"Tupiza","name_href" => "bo/population-of-tupiza","count" => "24 491","real_id" =>27,),
"28"=>array("name_ru"=>"Сан-Борха","name_en"=>"San Borja","name_href" => "bo/population-of-san-borja","count" => "22 736","real_id" =>28,),
"29"=>array("name_ru"=>"Вилья-Монтес","name_en"=>"Villamontes","name_href" => "bo/population-of-villamontes","count" => "22 675","real_id" =>29,),
"30"=>array("name_ru"=>"Котока","name_en"=>"Kotoka","name_href" => "bo/population-of-kotoka","count" => "21 764","real_id" =>30,),
"31"=>array("name_ru"=>"Япакани","name_en"=>"Villa yapacaní","name_href" => "bo/population-of-villa-yapacaní","count" => "21 428","real_id" =>31,),
"32"=>array("name_ru"=>"Асенсьон","name_en"=>"Asencion","name_href" => "bo/population-of-asencion","count" => "14 429","real_id" =>32,),
"33"=>array("name_ru"=>"Менерос","name_en"=>"Mineros","name_href" => "bo/population-of-mineros","count" => "14 385","real_id" =>33,),
"34"=>array("name_ru"=>"Портагуэло","name_en"=>"Portachuelo","name_href" => "bo/population-of-portachuelo","count" => "11 485","real_id" =>34,),
"35"=>array("name_ru"=>"Ла-Бельхика","name_en"=>"La Belgica","name_href" => "bo/population-of-la-belgica","count" => "5 501","real_id" =>35,),
"36"=>array("name_ru"=>"Санта-Крус-де-ла-Сьерра","name_en"=>"Santa Cruz de La Sierra","name_href" => "bo/population-of-santa-cruz-de-la-sierra","count" => "1 545 161","real_id" =>36,),
"37"=>array("name_ru"=>"Эль-Альто","name_en"=>"El Alto","name_href" => "bo/population-of-el-alto","count" => "907 887","real_id" =>37,),
"38"=>array("name_ru"=>"Ла-Пас — фактическая столица","name_en"=>"La Paz is the actual capital","name_href" => "bo/population-of-la-paz-is-the-actual-capital","count" => "877 363","real_id" =>38,),
"39"=>array("name_ru"=>"Кочабамба","name_en"=>"Cochabamba","name_href" => "bo/population-of-cochabamba","count" => "608 276","real_id" =>39,),
"40"=>array("name_ru"=>"Сукре — столица","name_en"=>"Sucre is the capital","name_href" => "bo/population-of-sucre-is-the-capital","count" => "281 240","real_id" =>40,)
);

?>