<?php
//Центральная африка "центральноафриканская республика) 37
$libcf = array ( 
"1"=>array("name_ru"=>"Банги","name_en"=>"Bangui","name_href" => "cf/population-of-bangui","count" => "542 393","real_id" =>1,),
"2"=>array("name_ru"=>"Бимбо","name_en"=>"Bimbo","name_href" => "cf/population-of-bimbo","count" => "129 655","real_id" =>2,),
"3"=>array("name_ru"=>"Мбаики","name_en"=>"Mbaiki","name_href" => "cf/population-of-mbaiki","count" => "67 132","real_id" =>3,),
"4"=>array("name_ru"=>"Берберати","name_en"=>"Berberati","name_href" => "cf/population-of-berberati","count" => "61 815","real_id" =>4,),
"5"=>array("name_ru"=>"Кага-Бандоро","name_en"=>"Kaga-Bandoro","name_href" => "cf/population-of-kaga-bandoro","count" => "56 520","real_id" =>5,),
"6"=>array("name_ru"=>"Бозум","name_en"=>"Bozoum","name_href" => "cf/population-of-bozoum","count" => "40 201","real_id" =>6,),
"7"=>array("name_ru"=>"Карно","name_en"=>"Carnot","name_href" => "cf/population-of-carnot","count" => "38 071","real_id" =>7,),
"8"=>array("name_ru"=>"Сибю","name_en"=>"Sibut","name_href" => "cf/population-of-sibut","count" => "34 267","real_id" =>8,),
"9"=>array("name_ru"=>"Бамбари","name_en"=>"Bambari","name_href" => "cf/population-of-bambari","count" => "32 547","real_id" =>9,),
"10"=>array("name_ru"=>"Бриа","name_en"=>"Bria","name_href" => "cf/population-of-bria","count" => "29 027","real_id" =>10,),
"11"=>array("name_ru"=>"Буар","name_en"=>"Bouar","name_href" => "cf/population-of-bouar","count" => "28 581","real_id" =>11,),
"12"=>array("name_ru"=>"Босангоа","name_en"=>"Bossangoa","name_href" => "cf/population-of-bossangoa","count" => "27 428","real_id" =>12,),
"13"=>array("name_ru"=>"Нола","name_en"=>"Nola","name_href" => "cf/population-of-nola","count" => "26 809","real_id" =>13,),
"14"=>array("name_ru"=>"Бангасу","name_en"=>"Bangassou","name_href" => "cf/population-of-bangassou","count" => "24 361","real_id" =>14,),
"15"=>array("name_ru"=>"Дамара","name_en"=>"Damara","name_href" => "cf/population-of-damara","count" => "20 093","real_id" =>15,),
"16"=>array("name_ru"=>"Мобае","name_en"=>"Mobaye","name_href" => "cf/population-of-mobaye","count" => "19 431","real_id" =>16,),
"17"=>array("name_ru"=>"Пауа","name_en"=>"paua","name_href" => "cf/population-of-paua","count" => "18 441","real_id" =>17,),
"18"=>array("name_ru"=>"Бода","name_en"=>"Boda","name_href" => "cf/population-of-boda","count" => "16 655","real_id" =>18,),
"19"=>array("name_ru"=>"Иппи","name_en"=>"Ippy","name_href" => "cf/population-of-ippy","count" => "16 571","real_id" =>19,),
"20"=>array("name_ru"=>"Батангафо","name_en"=>"Batangafo","name_href" => "cf/population-of-batangafo","count" => "15 310","real_id" =>20,),
"21"=>array("name_ru"=>"Алиндао","name_en"=>"alindao","name_href" => "cf/population-of-alindao","count" => "14 234","real_id" =>21,),
"22"=>array("name_ru"=>"Кабо","name_en"=>"Cape","name_href" => "cf/population-of-cape","count" => "13 637","real_id" =>22,),
"23"=>array("name_ru"=>"Рафаи","name_en"=>"Rafai","name_href" => "cf/population-of-rafai","count" => "13 459","real_id" =>23,),
"24"=>array("name_ru"=>"Бука","name_en"=>"Buka","name_href" => "cf/population-of-buka","count" => "13 250","real_id" =>24,),
"25"=>array("name_ru"=>"Обо","name_en"=>"About","name_href" => "cf/population-of-about","count" => "12 887","real_id" =>25,),
"26"=>array("name_ru"=>"Нделе","name_en"=>"Ndele","name_href" => "cf/population-of-ndele","count" => "11 764","real_id" =>26,),
"27"=>array("name_ru"=>"Кембе","name_en"=>"Kembo","name_href" => "cf/population-of-kembo","count" => "11 513","real_id" =>27,),
"28"=>array("name_ru"=>"Монгумба","name_en"=>"Mongoumba","name_href" => "cf/population-of-mongoumba","count" => "10 885","real_id" =>28,),
"29"=>array("name_ru"=>"Яколе","name_en"=>"Yakol","name_href" => "cf/population-of-yakol","count" => "10 634","real_id" =>29,),
"30"=>array("name_ru"=>"Бирао","name_en"=>"Birao","name_href" => "cf/population-of-birao","count" => "10 178","real_id" =>30,),
"31"=>array("name_ru"=>"Гамбула","name_en"=>"Gambula","name_href" => "cf/population-of-gambula","count" => "7 646","real_id" =>31,),
"32"=>array("name_ru"=>"Куанго","name_en"=>"Cuango","name_href" => "cf/population-of-cuango","count" => "7 529","real_id" =>32,),
"33"=>array("name_ru"=>"Баоро","name_en"=>"Baoro","name_href" => "cf/population-of-baoro","count" => "6 319","real_id" =>33,),
"34"=>array("name_ru"=>"Боали","name_en"=>"Boali","name_href" => "cf/population-of-boali","count" => "5 876","real_id" =>34,),
"35"=>array("name_ru"=>"Удда","name_en"=>"Udd","name_href" => "cf/population-of-udd","count" => "5 434","real_id" =>35,),
"36"=>array("name_ru"=>"Гамбо","name_en"=>"Gumbo","name_href" => "cf/population-of-gumbo","count" => "4 971","real_id" =>36,),
"37"=>array("name_ru"=>"Уанго","name_en"=>"Whang","name_href" => "cf/population-of-whang","count" => "4 365","real_id" =>37,),
"38"=>array("name_ru"=>"Банги","name_en"=>"Bangui","name_href" => "cf/population-of-bangui","count" => "542 393","real_id" =>38,),
"39"=>array("name_ru"=>"Бимбо","name_en"=>"Bimbo","name_href" => "cf/population-of-bimbo","count" => "129 655","real_id" =>39,),
"40"=>array("name_ru"=>"Мбаики","name_en"=>"Mbaiki","name_href" => "cf/population-of-mbaiki","count" => "67 132","real_id" =>40,),
"41"=>array("name_ru"=>"Берберати","name_en"=>"Berberati","name_href" => "cf/population-of-berberati","count" => "61 815","real_id" =>41,),
"42"=>array("name_ru"=>"Кага-Бандоро","name_en"=>"Kaga-Bandoro","name_href" => "cf/population-of-kaga-bandoro","count" => "56 520","real_id" =>42,)
);

?>