<?php
//Канада 100 
$libca = array ( 
"1"=>array("name_ru"=>"Торонто","name_en"=>"Toronto","name_href" => "ca/population-of-toronto","count" => "2 503 281","real_id" =>1,),
"2"=>array("name_ru"=>"Монреаль","name_en"=>"Montreal","name_href" => "ca/population-of-montreal","count" => "1 620 693","real_id" =>2,),
"3"=>array("name_ru"=>"Калгари","name_en"=>"Calgary","name_href" => "ca/population-of-calgary","count" => "988 193","real_id" =>3,),
"4"=>array("name_ru"=>"Оттава","name_en"=>"Ottawa","name_href" => "ca/population-of-ottawa","count" => "812 129","real_id" =>4,),
"5"=>array("name_ru"=>"Эдмонтон","name_en"=>"Edmonton","name_href" => "ca/population-of-edmonton","count" => "730 372","real_id" =>5,),
"6"=>array("name_ru"=>"Миссиссога","name_en"=>"Mississauga","name_href" => "ca/population-of-mississauga","count" => "668 549","real_id" =>6,),
"7"=>array("name_ru"=>"Виннипег","name_en"=>"Winnipeg","name_href" => "ca/population-of-winnipeg","count" => "633 451","real_id" =>7,),
"8"=>array("name_ru"=>"Ванкувер","name_en"=>"Vancouver","name_href" => "ca/population-of-vancouver","count" => "578 041","real_id" =>8,),
"9"=>array("name_ru"=>"Гамильтон","name_en"=>"Hamilton","name_href" => "ca/population-of-hamilton","count" => "504 559","real_id" =>9,),
"10"=>array("name_ru"=>"Квебек","name_en"=>"Quebec","name_href" => "ca/population-of-quebec","count" => "491 142","real_id" =>10,),
"11"=>array("name_ru"=>"Брамптон","name_en"=>"Brampton","name_href" => "ca/population-of-brampton","count" => "433 806","real_id" =>11,),
"12"=>array("name_ru"=>"Саррей","name_en"=>"Surrey","name_href" => "ca/population-of-surrey","count" => "394 976","real_id" =>12,),
"13"=>array("name_ru"=>"Галифакс","name_en"=>"Halifax","name_href" => "ca/population-of-halifax","count" => "372 679","real_id" =>13,),
"14"=>array("name_ru"=>"Лаваль","name_en"=>"Laval","name_href" => "ca/population-of-laval","count" => "368 709","real_id" =>14,),
"15"=>array("name_ru"=>"Лондон","name_en"=>"London","name_href" => "ca/population-of-london","count" => "352 395","real_id" =>15,),
"16"=>array("name_ru"=>"Маркем","name_en"=>"Markham","name_href" => "ca/population-of-markham","count" => "261 573","real_id" =>16,),
"17"=>array("name_ru"=>"Гатино","name_en"=>"Gatineau","name_href" => "ca/population-of-gatineau","count" => "242 124","real_id" =>17,),
"18"=>array("name_ru"=>"Вон","name_en"=>"Vaughn","name_href" => "ca/population-of-vaughn","count" => "238 866","real_id" =>18,),
"19"=>array("name_ru"=>"Лонгёй","name_en"=>"Longueuil","name_href" => "ca/population-of-longueuil","count" => "229 330","real_id" =>19,),
"20"=>array("name_ru"=>"Уинсор","name_en"=>"Windsor","name_href" => "ca/population-of-windsor","count" => "216 473","real_id" =>20,),
"21"=>array("name_ru"=>"Китченер","name_en"=>"Kitchener","name_href" => "ca/population-of-kitchener","count" => "204 668","real_id" =>21,),
"22"=>array("name_ru"=>"Бернаби","name_en"=>"Burnaby","name_href" => "ca/population-of-burnaby","count" => "202 799","real_id" =>22,),
"23"=>array("name_ru"=>"Саскатун","name_en"=>"Saskatoon","name_href" => "ca/population-of-saskatoon","count" => "202 340","real_id" =>23,),
"24"=>array("name_ru"=>"Реджайна","name_en"=>"Regina","name_href" => "ca/population-of-regina","count" => "179 246","real_id" =>24,),
"25"=>array("name_ru"=>"Ричмонд","name_en"=>"Richmond","name_href" => "ca/population-of-richmond","count" => "174 461","real_id" =>25,),
"26"=>array("name_ru"=>"Оквилл","name_en"=>"Oakville","name_href" => "ca/population-of-oakville","count" => "165 613","real_id" =>26,),
"27"=>array("name_ru"=>"Берлингтон","name_en"=>"Burlington","name_href" => "ca/population-of-burlington","count" => "164 415","real_id" =>27,),
"28"=>array("name_ru"=>"Ричмонд-Хилл","name_en"=>"Richmond Hill","name_href" => "ca/population-of-richmond-hill","count" => "162 704","real_id" =>28,),
"29"=>array("name_ru"=>"Большой Садбери","name_en"=>"Greater Sudbury","name_href" => "ca/population-of-greater-sudbury","count" => "157 857","real_id" =>29,),
"30"=>array("name_ru"=>"Шербрук","name_en"=>"Sherbrooke","name_href" => "ca/population-of-sherbrooke","count" => "147 427","real_id" =>30,),
"31"=>array("name_ru"=>"Сагеней","name_en"=>"Saguenay","name_href" => "ca/population-of-saguenay","count" => "143 692","real_id" =>31,),
"32"=>array("name_ru"=>"Ошава","name_en"=>"Oshawa","name_href" => "ca/population-of-oshawa","count" => "141 590","real_id" =>32,),
"33"=>array("name_ru"=>"Сент-Катаринс","name_en"=>"St. Catharines","name_href" => "ca/population-of-st.-catharines","count" => "131 989","real_id" =>33,),
"34"=>array("name_ru"=>"Леви","name_en"=>"Levi","name_href" => "ca/population-of-levi","count" => "130 006","real_id" =>34,),
"35"=>array("name_ru"=>"Барри","name_en"=>"Barry","name_href" => "ca/population-of-barry","count" => "128 430","real_id" =>35,),
"36"=>array("name_ru"=>"Труа-Ривьер","name_en"=>"Trois-Rivières","name_href" => "ca/population-of-trois-rivières","count" => "126 323","real_id" =>36,),
"37"=>array("name_ru"=>"Абботсфорд","name_en"=>"Abbotsford","name_href" => "ca/population-of-abbotsford","count" => "123 864","real_id" =>37,),
"38"=>array("name_ru"=>"Кеймбридж","name_en"=>"Cambridge","name_href" => "ca/population-of-cambridge","count" => "120 371","real_id" =>38,),
"39"=>array("name_ru"=>"Кингстон","name_en"=>"Kingston","name_href" => "ca/population-of-kingston","count" => "117 207","real_id" =>39,),
"40"=>array("name_ru"=>"Гуэлф","name_en"=>"Guelph","name_href" => "ca/population-of-guelph","count" => "114 943","real_id" =>40,),
"41"=>array("name_ru"=>"Кокуитлам","name_en"=>"Kingston","name_href" => "ca/population-of-kingston","count" => "114 565","real_id" =>41,),
"42"=>array("name_ru"=>"Уитби","name_en"=>"Whitby","name_href" => "ca/population-of-whitby","count" => "111 184","real_id" =>42,),
"43"=>array("name_ru"=>"Тандер-Бей","name_en"=>"Thunder Bay","name_href" => "ca/population-of-thunder-bay","count" => "109 140","real_id" =>43,),
"44"=>array("name_ru"=>"Саанич","name_en"=>"Saanich","name_href" => "ca/population-of-saanich","count" => "108 265","real_id" =>44,),
"45"=>array("name_ru"=>"Чатем-Кент","name_en"=>"Chatham-Kent","name_href" => "ca/population-of-chatham-kent","count" => "108 177","real_id" =>45,),
"46"=>array("name_ru"=>"Келоуна","name_en"=>"Kelowna","name_href" => "ca/population-of-kelowna","count" => "106 707","real_id" =>46,),
"47"=>array("name_ru"=>"Кейп-Бретон","name_en"=>"Cape Breton","name_href" => "ca/population-of-cape-breton","count" => "102 250","real_id" =>47,),
"48"=>array("name_ru"=>"Сент-Джонс","name_en"=>"St. John's","name_href" => "ca/population-of-st.-johns","count" => "100 646","real_id" =>48,),
"49"=>array("name_ru"=>"Уотерлу","name_en"=>"Waterloo","name_href" => "ca/population-of-waterloo","count" => "97 475","real_id" =>49,),
"50"=>array("name_ru"=>"Делта","name_en"=>"Delta","name_href" => "ca/population-of-delta","count" => "96 723","real_id" =>50,),
"51"=>array("name_ru"=>"Тербон","name_en"=>"Terrebonne","name_href" => "ca/population-of-terrebonne","count" => "94 703","real_id" =>51,),
"52"=>array("name_ru"=>"Лангли","name_en"=>"Langley","name_href" => "ca/population-of-langley","count" => "93 726","real_id" =>52,),
"53"=>array("name_ru"=>"Брантфорд","name_en"=>"Brantford","name_href" => "ca/population-of-brantford","count" => "90 192","real_id" =>53,),
"54"=>array("name_ru"=>"Эйджакс","name_en"=>"Ajax","name_href" => "ca/population-of-ajax","count" => "90 167","real_id" =>54,),
"55"=>array("name_ru"=>"Пикеринг","name_en"=>"Pickering","name_href" => "ca/population-of-pickering","count" => "87 838","real_id" =>55,),
"56"=>array("name_ru"=>"Сен-Жан-сюр-Ришелье","name_en"=>"Saint-Jean-sur-Richelieu","name_href" => "ca/population-of-saint-jean-sur-richelieu","count" => "87 492","real_id" =>56,),
"57"=>array("name_ru"=>"Ред-Дир","name_en"=>"Red Deer","name_href" => "ca/population-of-red-deer","count" => "82 772","real_id" =>57,),
"58"=>array("name_ru"=>"Норт-Ванкувер","name_en"=>"North Vancouver","name_href" => "ca/population-of-north-vancouver","count" => "82 562","real_id" =>58,),
"59"=>array("name_ru"=>"Графство Страткона","name_en"=>"Strathcona County","name_href" => "ca/population-of-strathcona-county","count" => "82 511","real_id" =>59,),
"60"=>array("name_ru"=>"Ниагара-Фолс","name_en"=>"Niagara Falls","name_href" => "ca/population-of-niagara-falls","count" => "82 184","real_id" =>60,),
"61"=>array("name_ru"=>"Камлупс","name_en"=>"Kamloops","name_href" => "ca/population-of-kamloops","count" => "80 376","real_id" =>61,),
"62"=>array("name_ru"=>"Нанаймо","name_en"=>"Nanaimo","name_href" => "ca/population-of-nanaimo","count" => "78 692","real_id" =>62,),
"63"=>array("name_ru"=>"Виктория","name_en"=>"Victoria","name_href" => "ca/population-of-victoria","count" => "78 057","real_id" =>63,),
"64"=>array("name_ru"=>"Клэрингтон","name_en"=>"Clarington","name_href" => "ca/population-of-clarington","count" => "77 820","real_id" =>64,),
"65"=>array("name_ru"=>"Репантиньи","name_en"=>"Repentigny","name_href" => "ca/population-of-repentigny","count" => "76 237","real_id" =>65,),
"66"=>array("name_ru"=>"Су-Сент-Мари","name_en"=>"Sous-Sainte-Marie","name_href" => "ca/population-of-sous-sainte-marie","count" => "74 948","real_id" =>66,),
"67"=>array("name_ru"=>"Питерборо","name_en"=>"Peterborough","name_href" => "ca/population-of-peterborough","count" => "74 898","real_id" =>67,),
"68"=>array("name_ru"=>"Летбридж","name_en"=>"Lethbridge","name_href" => "ca/population-of-lethbridge","count" => "74 637","real_id" =>68,),
"69"=>array("name_ru"=>"Каварта-Лейкс","name_en"=>"Kawartha Lakes","name_href" => "ca/population-of-kawartha-lakes","count" => "74 561","real_id" =>69,),
"70"=>array("name_ru"=>"Ньюмаркет","name_en"=>"Newmarket","name_href" => "ca/population-of-newmarket","count" => "74 295","real_id" =>70,),
"71"=>array("name_ru"=>"Сарния","name_en"=>"Sarnia","name_href" => "ca/population-of-sarnia","count" => "71 419","real_id" =>71,),
"72"=>array("name_ru"=>"Броссар","name_en"=>"Brossard","name_href" => "ca/population-of-brossard","count" => "71 154","real_id" =>72,),
"73"=>array("name_ru"=>"Принс-Джордж","name_en"=>"Prince George","name_href" => "ca/population-of-prince-george","count" => "70 981","real_id" =>73,),
"74"=>array("name_ru"=>"Чилливак","name_en"=>"Chilliwack","name_href" => "ca/population-of-chilliwack","count" => "69 217","real_id" =>74,),
"75"=>array("name_ru"=>"Мейпл-Ридж","name_en"=>"Maple Ridge","name_href" => "ca/population-of-maple-ridge","count" => "68 949","real_id" =>75,),
"76"=>array("name_ru"=>"Сент-Джон","name_en"=>"Saint John","name_href" => "ca/population-of-saint-john","count" => "68 043","real_id" =>76,),
"77"=>array("name_ru"=>"Драммондвилл","name_en"=>"Drummondville","name_href" => "ca/population-of-drummondville","count" => "67 392","real_id" =>77,),
"78"=>array("name_ru"=>"Монктон","name_en"=>"Moncton","name_href" => "ca/population-of-moncton","count" => "64 128","real_id" =>78,),
"79"=>array("name_ru"=>"Сен-Жером","name_en"=>"Saint-Jérôme","name_href" => "ca/population-of-saint-jérôme","count" => "63 729","real_id" =>79,),
"80"=>array("name_ru"=>"Норфолк","name_en"=>"Norfolk","name_href" => "ca/population-of-norfolk","count" => "62 563","real_id" =>80,),
"81"=>array("name_ru"=>"Нью-Вестминстер","name_en"=>"New Westminster","name_href" => "ca/population-of-new-westminster","count" => "58 549","real_id" =>81,),
"82"=>array("name_ru"=>"Сент-Альберт","name_en"=>"St. Albert","name_href" => "ca/population-of-st.-albert","count" => "57 719","real_id" =>82,),
"83"=>array("name_ru"=>"Каледон","name_en"=>"Caledon","name_href" => "ca/population-of-caledon","count" => "57 050","real_id" =>83,),
"84"=>array("name_ru"=>"Медисин-Хат","name_en"=>"Medicine Hat","name_href" => "ca/population-of-medicine-hat","count" => "56 997","real_id" =>84,),
"85"=>array("name_ru"=>"Холтон-Хиллс","name_en"=>"Halton Hills","name_href" => "ca/population-of-halton-hills","count" => "55 289","real_id" =>85,),
"86"=>array("name_ru"=>"Норт-Бей","name_en"=>"North Bay","name_href" => "ca/population-of-north-bay","count" => "53 966","real_id" =>86,),
"87"=>array("name_ru"=>"Милтон","name_en"=>"Milton","name_href" => "ca/population-of-milton","count" => "53 939","real_id" =>87,),
"88"=>array("name_ru"=>"Порт-Кокуитлам","name_en"=>"Port Richmond","name_href" => "ca/population-of-port-richmond","count" => "52 687","real_id" =>88,),
"89"=>array("name_ru"=>"Шавиниган","name_en"=>"Shawinigan","name_href" => "ca/population-of-shawinigan","count" => "51 904","real_id" =>89,),
"90"=>array("name_ru"=>"Сент-Иасент","name_en"=>"Saint-Hyacinthe","name_href" => "ca/population-of-saint-hyacinthe","count" => "51 616","real_id" =>90,),
"91"=>array("name_ru"=>"Вуд-Баффало","name_en"=>"Wood Buffalo","name_href" => "ca/population-of-wood-buffalo","count" => "51 496","real_id" =>91,),
"92"=>array("name_ru"=>"Фредериктон","name_en"=>"Fredericton","name_href" => "ca/population-of-fredericton","count" => "50 535","real_id" =>92,),
"93"=>array("name_ru"=>"Уэлленд","name_en"=>"Welland","name_href" => "ca/population-of-welland","count" => "50 331","real_id" =>93,),
"94"=>array("name_ru"=>"Доллар-Дез-Ормо","name_en"=>"The Dollar-Des-Ormo","name_href" => "ca/population-of-the-dollar-des-ormo","count" => "48 930","real_id" =>94,),
"95"=>array("name_ru"=>"Белвилл","name_en"=>"Belleville","name_href" => "ca/population-of-belleville","count" => "48 821","real_id" =>95,),
"96"=>array("name_ru"=>"Гранби","name_en"=>"Granby","name_href" => "ca/population-of-granby","count" => "47 637","real_id" =>96,),
"97"=>array("name_ru"=>"Орора","name_en"=>"Aurora","name_href" => "ca/population-of-aurora","count" => "47 629","real_id" =>97,),
"98"=>array("name_ru"=>"Гранд-Прери","name_en"=>"Grande Prairie","name_href" => "ca/population-of-grande-prairie","count" => "47 076","real_id" =>98,),
"99"=>array("name_ru"=>"Бленвиль","name_en"=>"Blainville","name_href" => "ca/population-of-blainville","count" => "46 493","real_id" =>99,),
"100"=>array("name_ru"=>"Корнуолл","name_en"=>"Cornwall","name_href" => "ca/population-of-cornwall","count" => "45 965","real_id" =>100,),
"101"=>array("name_ru"=>"Торонто","name_en"=>"Toronto","name_href" => "ca/population-of-toronto","count" => "2 503 281","real_id" =>101,),
"102"=>array("name_ru"=>"Монреаль","name_en"=>"Montreal","name_href" => "ca/population-of-montreal","count" => "1 620 693","real_id" =>102,),
"103"=>array("name_ru"=>"Калгари","name_en"=>"Calgary","name_href" => "ca/population-of-calgary","count" => "988 193","real_id" =>103,),
"104"=>array("name_ru"=>"Оттава","name_en"=>"Ottawa","name_href" => "ca/population-of-ottawa","count" => "812 129","real_id" =>104,),
"105"=>array("name_ru"=>"Эдмонтон","name_en"=>"Edmonton","name_href" => "ca/population-of-edmonton","count" => "730 372","real_id" =>105,)
);

?>