<?php
//Китай 137
$libcn = array (


"1"=>array("name_ru"=>"Чунцин","name_en"=>"Chongqing","name_href" => "page_cities/cities","count" => "29 914 000","real_id" =>1,),
"2"=>array("name_ru"=>"Шанхай","name_en"=>"Shanghai","name_href" => "cn/population-of-shanghai","count" => "24 150 000","real_id" =>2,),
"3"=>array("name_ru"=>"Пекин","name_en"=>"Beijing","name_href" => "cn/population-of-beijing","count" => "21 705 000","real_id" =>3,),
"4"=>array("name_ru"=>"Тяньцзинь","name_en"=>"Tianjin","name_href" => "cn/population-of-tianjin","count" => "14 425 000","real_id" =>4,),
"5"=>array("name_ru"=>"Наньян","name_en"=>"Nanyang","name_href" => "cn/population-of-nanyang","count" => "12 010 000","real_id" =>5,),
"6"=>array("name_ru"=>"Баодин","name_en"=>"Baoding","name_href" => "cn/population-of-baoding","count" => "10 700 000","real_id" =>6,),
"7"=>array("name_ru"=>"Харбин","name_en"=>"Harbin","name_href" => "cn/population-of-harbin","count" => "10 635 971","real_id" =>7,),
"8"=>array("name_ru"=>"Шэньчжэнь","name_en"=>"Shenzhen","name_href" => "cn/population-of-shenzhen","count" => "10 357 938","real_id" =>8,),
"9"=>array("name_ru"=>"Ухань","name_en"=>"Wuhan","name_href" => "cn/population-of-wuhan","count" => "10 220 000","real_id" =>9,),
"10"=>array("name_ru"=>"Гуанчжоу","name_en"=>"Guangzhou","name_href" => "cn/population-of-guangzhou","count" => "10 000 000","real_id" =>10,),
"11"=>array("name_ru"=>"Шицзячжуан","name_en"=>"Shijiazhuang","name_href" => "cn/population-of-shijiazhuang","count" => "9 600 000","real_id" =>11,),
"12"=>array("name_ru"=>"Сюйчжоу","name_en"=>"Xuzhou","name_href" => "cn/population-of-xuzhou","count" => "9 468 000","real_id" =>12,),
"13"=>array("name_ru"=>"Ханчжоу","name_en"=>"Hangzhou","name_href" => "cn/population-of-hangzhou","count" => "8 700 000","real_id" =>13,),
"14"=>array("name_ru"=>"Чжэнчжоу","name_en"=>"Zhengzhou","name_href" => "cn/population-of-zhengzhou","count" => "8 626 505","real_id" =>14,),
"15"=>array("name_ru"=>"Вэйфан","name_en"=>"Weifang","name_href" => "cn/population-of-weifang","count" => "8 500 000","real_id" =>15,),
"16"=>array("name_ru"=>"Фуян","name_en"=>"Fuyang","name_href" => "cn/population-of-fuyang","count" => "8 360 000","real_id" =>16,),
"17"=>array("name_ru"=>"Ганьчжоу","name_en"=>"Ganzhou","name_href" => "cn/population-of-ganzhou","count" => "8 300 000","real_id" =>17,),
"18"=>array("name_ru"=>"Цзинин","name_en"=>"Jining","name_href" => "cn/population-of-jining","count" => "8 023 000","real_id" =>18,),
"19"=>array("name_ru"=>"Шэньян ","name_en"=>"Shenyang ","name_href" => "cn/population-of-shenyang","count" => "7 760 000","real_id" =>19,),
"20"=>array("name_ru"=>"Чжумадянь","name_en"=>"Zhumadian","name_href" => "cn/population-of-zhumadian","count" => "7 640 000","real_id" =>20,),
"21"=>array("name_ru"=>"Сиань","name_en"=>"XI'an","name_href" => "cn/population-of-xian","count" => "7 270 000","real_id" =>21,),
"22"=>array("name_ru"=>"Гонконг","name_en"=>"Hong Kong","name_href" => "cn/population-of-hong-kong","count" => "7 182 724","real_id" =>22,),
"23"=>array("name_ru"=>"Чэнду","name_en"=>"Chengdu","name_href" => "cn/population-of-chengdu","count" => "7 123 000","real_id" =>23,),
"24"=>array("name_ru"=>"Таншань","name_en"=>"Tangshan","name_href" => "cn/population-of-tangshan","count" => "7 100 000","real_id" =>24,),
"25"=>array("name_ru"=>"Шанцю","name_en"=>"Shangqiu","name_href" => "cn/population-of-shangqiu","count" => "7 000 000","real_id" =>25,),
"26"=>array("name_ru"=>"Чжаньцзян","name_en"=>"Zhanjiang","name_href" => "cn/population-of-zhanjiang","count" => "6 900 000","real_id" =>26,),
"27"=>array("name_ru"=>"Цзуньи","name_en"=>"Zunyi","name_href" => "cn/population-of-zunyi","count" => "6 838 000","real_id" =>27,),
"28"=>array("name_ru"=>"Фучжоу","name_en"=>"Fuzhou","name_href" => "cn/population-of-fuzhou","count" => "6 830 000","real_id" =>28,),
"29"=>array("name_ru"=>"Чанчунь","name_en"=>"Changchun","name_href" => "cn/population-of-changchun","count" => "6 830 000","real_id" =>29,),
"30"=>array("name_ru"=>"Наньнин","name_en"=>"Nanning","name_href" => "cn/population-of-nanning","count" => "6 825 000","real_id" =>30,),
"31"=>array("name_ru"=>"Шаоян","name_en"=>"Shaoyang","name_href" => "cn/population-of-shaoyang","count" => "6 739 000","real_id" =>31,),
"32"=>array("name_ru"=>"Далянь","name_en"=>"Dalian","name_href" => "cn/population-of-dalian","count" => "6 690 432","real_id" =>32,),
"33"=>array("name_ru"=>"Синьян","name_en"=>"Xinyang","name_href" => "cn/population-of-xinyang","count" => "6 634 000","real_id" =>33,),
"34"=>array("name_ru"=>"Куньмин","name_en"=>"Kunming","name_href" => "cn/population-of-kunming","count" => "6 250 000","real_id" =>34,),
"35"=>array("name_ru"=>"Цицикар","name_en"=>"Qiqihar","name_href" => "cn/population-of-qiqihar","count" => "6 011 000","real_id" =>35,),
"36"=>array("name_ru"=>"Чандэ","name_en"=>"Changde","name_href" => "cn/population-of-changde","count" => "5 717 000","real_id" =>36,),
"37"=>array("name_ru"=>"Аньцин","name_en"=>"Anqing","name_href" => "cn/population-of-anqing","count" => "5 590 000","real_id" =>37,),
"38"=>array("name_ru"=>"Ичунь ","name_en"=>"Yichun ","name_href" => "cn/population-of-yichun","count" => "5 400 000","real_id" =>38,),
"39"=>array("name_ru"=>"Хуайань","name_en"=>"Huai'an","name_href" => "cn/population-of-huaian","count" => "5 340 000","real_id" =>39,),
"40"=>array("name_ru"=>"Чжаотун","name_en"=>"Zhaotong","name_href" => "cn/population-of-zhaotong","count" => "5 252 000","real_id" =>40,),
"41"=>array("name_ru"=>"Аньян","name_en"=>"Anyang","name_href" => "cn/population-of-anyang","count" => "5 250 000","real_id" =>41,),
"42"=>array("name_ru"=>"Юэян","name_en"=>"Yueyang","name_href" => "cn/population-of-yueyang","count" => "5 158 000","real_id" =>42,),
"43"=>array("name_ru"=>"Гуйлинь","name_en"=>"Guilin","name_href" => "cn/population-of-guilin","count" => "5 046 000","real_id" =>43,),
"44"=>array("name_ru"=>"Наньчан","name_en"=>"Nanchang","name_href" => "cn/population-of-nanchang","count" => "5 042 565","real_id" =>44,),
"45"=>array("name_ru"=>"Мэйчжоу","name_en"=>"Meizhou","name_href" => "cn/population-of-meizhou","count" => "5 001 000","real_id" =>45,),
"46"=>array("name_ru"=>"Шаньтоу","name_en"=>"Shantou","name_href" => "cn/population-of-shantou","count" => "4 972 000","real_id" =>46,),
"47"=>array("name_ru"=>"Мяньян","name_en"=>"Mianyang","name_href" => "cn/population-of-mianyang","count" => "4 945 000","real_id" =>47,),
"48"=>array("name_ru"=>"Хэфэй","name_en"=>"Hefei","name_href" => "cn/population-of-hefei","count" => "4 867 000","real_id" =>48,),
"49"=>array("name_ru"=>"Юньчэн","name_en"=>"Yuncheng","name_href" => "cn/population-of-yuncheng","count" => "4 860 000","real_id" =>49,),
"50"=>array("name_ru"=>"Кайфын","name_en"=>"Kaifeng","name_href" => "cn/population-of-kaifeng","count" => "4 800 000","real_id" =>50,),
"51"=>array("name_ru"=>"Ляньжань","name_en"=>"Lianran","name_href" => "cn/population-of-lianran","count" => "4 790 000","real_id" =>51,),
"52"=>array("name_ru"=>"Хуайхуа","name_en"=>"Huaihua","name_href" => "cn/population-of-huaihua","count" => "4 558 000","real_id" =>52,),
"53"=>array("name_ru"=>"Ибинь","name_en"=>"Yibin","name_href" => "cn/population-of-yibin","count" => "4 456 000","real_id" =>53,),
"54"=>array("name_ru"=>"Чэньчжоу","name_en"=>"Chenzhou","name_href" => "cn/population-of-chenzhou","count" => "4 385 000","real_id" =>54,),
"55"=>array("name_ru"=>"Чифэн","name_en"=>"Chifeng","name_href" => "cn/population-of-chifeng","count" => "4 376 600","real_id" =>55,),
"56"=>array("name_ru"=>"Чжанцзякоу","name_en"=>"Zhangjiakou","name_href" => "cn/population-of-zhangjiakou","count" => "4 345 491","real_id" =>56,),
"57"=>array("name_ru"=>"Нэйцзян","name_en"=>"Neijiang","name_href" => "cn/population-of-neijiang","count" => "4 238 000","real_id" =>57,),
"58"=>array("name_ru"=>"Ичан","name_en"=>"Yichang","name_href" => "cn/population-of-yichang","count" => "4 040 000","real_id" =>58,),
"59"=>array("name_ru"=>"Гуйян","name_en"=>"Guiyang","name_href" => "cn/population-of-guiyang","count" => "3 921 000","real_id" =>59,),
"60"=>array("name_ru"=>"Баоцзи","name_en"=>"Baoji","name_href" => "cn/population-of-baoji","count" => "3 738 700","real_id" =>60,),
"61"=>array("name_ru"=>"Ханьчжун","name_en"=>"Hanzhong","name_href" => "cn/population-of-hanzhong","count" => "3 700 000","real_id" =>61,),
"62"=>array("name_ru"=>"Дэян","name_en"=>"Deyang","name_href" => "cn/population-of-deyang","count" => "3 636 000","real_id" =>62,),
"63"=>array("name_ru"=>"Лючжоу","name_en"=>"Liuzhou","name_href" => "cn/population-of-liuzhou","count" => "3 625 000","real_id" =>63,),
"64"=>array("name_ru"=>"Чанша","name_en"=>"Changsha","name_href" => "cn/population-of-changsha","count" => "3 617 000","real_id" =>64,),
"65"=>array("name_ru"=>"Чэндэ","name_en"=>"Chengde","name_href" => "cn/population-of-chengde","count" => "3 610 000","real_id" =>65,),
"66"=>array("name_ru"=>"Сямынь","name_en"=>"Xiamen","name_href" => "cn/population-of-xiamen","count" => "3 530 000","real_id" =>66,),
"67"=>array("name_ru"=>"Бэнбу","name_en"=>"Bengbu","name_href" => "cn/population-of-bengbu","count" => "3 525 000","real_id" =>67,),
"68"=>array("name_ru"=>"Тайюань","name_en"=>"Taiyuan","name_href" => "cn/population-of-taiyuan","count" => "3 398 000","real_id" =>68,),
"69"=>array("name_ru"=>"Чаоян","name_en"=>"Chaoyang","name_href" => "cn/population-of-chaoyang","count" => "3 370 000","real_id" =>69,),
"70"=>array("name_ru"=>"Ланьчжоу","name_en"=>"Lanzhou","name_href" => "cn/population-of-lanzhou","count" => "3 310 000","real_id" =>70,),
"71"=>array("name_ru"=>"Сыпин","name_en"=>"The siping","name_href" => "cn/population-of-the-siping","count" => "3 300 000","real_id" =>71,),
"72"=>array("name_ru"=>"Цзинань","name_en"=>"Jinan","name_href" => "cn/population-of-jinan","count" => "3 250 000","real_id" =>72,),
"73"=>array("name_ru"=>"Датун","name_en"=>"Datong","name_href" => "cn/population-of-datong","count" => "3 160 000","real_id" =>73,),
"74"=>array("name_ru"=>"Шаогуань","name_en"=>"Shaoguan","name_href" => "cn/population-of-shaoguan","count" => "3 148 000","real_id" =>74,),
"75"=>array("name_ru"=>"Урумчи","name_en"=>"Urumqi","name_href" => "cn/population-of-urumqi","count" => "3 112 559","real_id" =>75,),
"76"=>array("name_ru"=>"Учжоу","name_en"=>"Wuzhou","name_href" => "cn/population-of-wuzhou","count" => "3 101 000","real_id" =>76,),
"77"=>array("name_ru"=>"Тунляо","name_en"=>"Tongliao","name_href" => "cn/population-of-tongliao","count" => "3 094 600","real_id" =>77,),
"78"=>array("name_ru"=>"Цзиньчжоу","name_en"=>"Jinzhou","name_href" => "cn/population-of-jinzhou","count" => "3 000 000","real_id" =>78,),
"79"=>array("name_ru"=>"Шаньвэй","name_en"=>"Shanwei","name_href" => "cn/population-of-shanwei","count" => "2 990 000","real_id" =>79,),
"80"=>array("name_ru"=>"Анькан","name_en"=>"Ankang","name_href" => "cn/population-of-ankang","count" => "2 930 000","real_id" =>80,),
"81"=>array("name_ru"=>"Наньпин","name_en"=>"Nanping","name_href" => "cn/population-of-nanping","count" => "2 890 000","real_id" =>81,),
"82"=>array("name_ru"=>"Цзинмэнь","name_en"=>"Jingmen","name_href" => "cn/population-of-jingmen","count" => "2 839 000","real_id" =>82,),
"83"=>array("name_ru"=>"Муданьцзян","name_en"=>"Mudanjiang","name_href" => "cn/population-of-mudanjiang","count" => "2 790 000","real_id" =>83,),
"84"=>array("name_ru"=>"Лунъянь ","name_en"=>"Longyan ","name_href" => "cn/population-of-longyan","count" => "2 770 000","real_id" =>84,),
"85"=>array("name_ru"=>"Гаосюн","name_en"=>"Kaohsiung","name_href" => "cn/population-of-kaohsiung","count" => "2 769 072","real_id" =>85,),
"86"=>array("name_ru"=>"Циндао","name_en"=>"Qingdao","name_href" => "cn/population-of-qingdao","count" => "2 755 500","real_id" =>86,),
"87"=>array("name_ru"=>"Жичжао","name_en"=>"Rizhao","name_href" => "cn/population-of-rizhao","count" => "2 720 000","real_id" =>87,),
"88"=>array("name_ru"=>"Хух-Хото","name_en"=>"Hohhot","name_href" => "cn/population-of-hohhot","count" => "2 635 000","real_id" =>88,),
"89"=>array("name_ru"=>"Тайбэй","name_en"=>"Taipei","name_href" => "cn/population-of-taipei","count" => "2 612 605","real_id" =>89,),
"90"=>array("name_ru"=>"Лишуй","name_en"=>"Lishui","name_href" => "cn/population-of-lishui","count" => "2 510 000","real_id" =>90,),
"91"=>array("name_ru"=>"Даньдун","name_en"=>"Dandong","name_href" => "cn/population-of-dandong","count" => "2 400 000","real_id" =>91,),
"92"=>array("name_ru"=>"Янцзян","name_en"=>"Yangjiang","name_href" => "cn/population-of-yangjiang","count" => "2 357 000","real_id" =>92,),
"93"=>array("name_ru"=>"Уху","name_en"=>"Ear","name_href" => "cn/population-of-ear","count" => "2 260 000","real_id" =>93,),
"94"=>array("name_ru"=>"Пинлян","name_en"=>"Pingliang","name_href" => "cn/population-of-pingliang","count" => "2 190 000","real_id" =>94,),
"95"=>array("name_ru"=>"Синин","name_en"=>"Xining","name_href" => "cn/population-of-xining","count" => "2 154 000","real_id" =>95,),
"96"=>array("name_ru"=>"Коулун","name_en"=>"Kowloon","name_href" => "cn/population-of-kowloon","count" => "2 019 533","real_id" =>96,),
"97"=>array("name_ru"=>"Цзиси","name_en"=>"Jixi","name_href" => "cn/population-of-jixi","count" => "1 950 000","real_id" =>97,),
"98"=>array("name_ru"=>"Ляоян","name_en"=>"Liaoyang","name_href" => "cn/population-of-liaoyang","count" => "1 800 000","real_id" =>98,),
"99"=>array("name_ru"=>"Иньчуань","name_en"=>"Yinchuan","name_href" => "cn/population-of-yinchuan","count" => "1 616 000","real_id" =>99,),
"100"=>array("name_ru"=>"Бэйхай","name_en"=>"Beihai","name_href" => "cn/population-of-beihai","count" => "1 573 000","real_id" =>100,),
"101"=>array("name_ru"=>"Бэньси","name_en"=>"Benxi","name_href" => "cn/population-of-benxi","count" => "1 567 000","real_id" =>101,),
"102"=>array("name_ru"=>"Цзиндэчжэнь","name_en"=>"Jingdezhen","name_href" => "cn/population-of-jingdezhen","count" => "1 554 000","real_id" =>102,),
"103"=>array("name_ru"=>"Хэби","name_en"=>"Hebi","name_href" => "cn/population-of-hebi","count" => "1 419 000","real_id" =>103,),
"104"=>array("name_ru"=>"Чжанъе","name_en"=>"Zhangye","name_href" => "cn/population-of-zhangye","count" => "1 270 000","real_id" =>104,),
"105"=>array("name_ru"=>"Ичунь ","name_en"=>"Yichun ","name_href" => "cn/population-of-yichun","count" => "1 250 000","real_id" =>105,),
"106"=>array("name_ru"=>"Дунтай","name_en"=>"Dongtai","name_href" => "cn/population-of-dongtai","count" => "1 130 000","real_id" =>106,),
"107"=>array("name_ru"=>"Гунчжулин","name_en"=>"Gongzhuling","name_href" => "cn/population-of-gongzhuling","count" => "1 070 000","real_id" =>107,),
"108"=>array("name_ru"=>"Аньцю ","name_en"=>"Anqiu ","name_href" => "cn/population-of-anqiu","count" => "1 050 000","real_id" =>108,),
"109"=>array("name_ru"=>"Хайкоу","name_en"=>"Haikou","name_href" => "cn/population-of-haikou","count" => "830 192","real_id" =>109,),
"110"=>array("name_ru"=>"Шуанчэн","name_en"=>"Shuangcheng","name_href" => "cn/population-of-shuangcheng","count" => "826 000","real_id" =>110,),
"111"=>array("name_ru"=>"Хайлунь","name_en"=>"Hailun","name_href" => "cn/population-of-hailun","count" => "820 000","real_id" =>111,),
"112"=>array("name_ru"=>"Санья","name_en"=>"Sanya","name_href" => "cn/population-of-sanya","count" => "685 408","real_id" =>112,),
"113"=>array("name_ru"=>"Яркенд","name_en"=>"Yarkand","name_href" => "cn/population-of-yarkand","count" => "621 000","real_id" =>113,),
"114"=>array("name_ru"=>"Сичан","name_en"=>"Xichang","name_href" => "cn/population-of-xichang","count" => "620 000","real_id" =>114,),
"115"=>array("name_ru"=>"Турфан","name_en"=>"Turpan","name_href" => "cn/population-of-turpan","count" => "589 609","real_id" =>115,),
"116"=>array("name_ru"=>"Аксу","name_en"=>"Aksu","name_href" => "cn/population-of-aksu","count" => "560 000","real_id" =>116,),
"117"=>array("name_ru"=>"Макао","name_en"=>"Macau","name_href" => "cn/population-of-macau","count" => "541 200","real_id" =>117,),
"118"=>array("name_ru"=>"Корла","name_en"=>"Korla","name_href" => "cn/population-of-korla","count" => "527 000","real_id" =>118,),
"119"=>array("name_ru"=>"Аньда","name_en"=>"Anda","name_href" => "cn/population-of-anda","count" => "520 000","real_id" =>119,),
"120"=>array("name_ru"=>"Линьхэ","name_en"=>"Linga","name_href" => "cn/population-of-linga","count" => "520 000","real_id" =>120,),
"121"=>array("name_ru"=>"Лхаса","name_en"=>"Lhasa","name_href" => "cn/population-of-lhasa","count" => "464 736","real_id" =>121,),
"122"=>array("name_ru"=>"Кульджа","name_en"=>"Ghulja","name_href" => "cn/population-of-ghulja","count" => "430 000","real_id" =>122,),
"123"=>array("name_ru"=>"Хами","name_en"=>"Hami","name_href" => "cn/population-of-hami","count" => "404 000","real_id" =>123,),
"124"=>array("name_ru"=>"Хуадянь","name_en"=>"Huadian","name_href" => "cn/population-of-huadian","count" => "400 000","real_id" =>124,),
"125"=>array("name_ru"=>"Яньцзи","name_en"=>"Yanji","name_href" => "cn/population-of-yanji","count" => "400 000","real_id" =>125,),
"126"=>array("name_ru"=>"Кашгар","name_en"=>"Kashgar","name_href" => "cn/population-of-kashgar","count" => "352 000","real_id" =>126,),
"127"=>array("name_ru"=>"Хайлар","name_en"=>"Hailar","name_href" => "cn/population-of-hailar","count" => "280 000","real_id" =>127,),
"128"=>array("name_ru"=>"Карамай","name_en"=>"Karamay","name_href" => "cn/population-of-karamay","count" => "262 157","real_id" =>128,),
"129"=>array("name_ru"=>"Линься","name_en"=>"Linxia","name_href" => "cn/population-of-linxia","count" => "230 000","real_id" =>129,),
"130"=>array("name_ru"=>"Алтай","name_en"=>"Altay","name_href" => "cn/population-of-altay","count" => "170 000","real_id" =>130,),
"131"=>array("name_ru"=>"Чугучак","name_en"=>"Chuguchak","name_href" => "cn/population-of-chuguchak","count" => "157 000","real_id" =>131,),
"132"=>array("name_ru"=>"Хотан","name_en"=>"Hotan","name_href" => "cn/population-of-hotan","count" => "114 000","real_id" =>132,),
"133"=>array("name_ru"=>"Хуалянь","name_en"=>"Hualien","name_href" => "cn/population-of-hualien","count" => "110 000","real_id" =>133,),
"134"=>array("name_ru"=>"Куча","name_en"=>"A bunch","name_href" => "cn/population-of-a-bunch","count" => "70 305","real_id" =>134,),
"135"=>array("name_ru"=>"Цзегу","name_en"=>"Czego","name_href" => "cn/population-of-czego","count" => "50 000","real_id" =>135,),
"136"=>array("name_ru"=>"Карашар","name_en"=>"Karashar","name_href" => "cn/population-of-karashar","count" => "31 773","real_id" =>136,),
"137"=>array("name_ru"=>"Нанкин ","name_en"=>"Nanjing ","name_href" => "cn/population-of-nanjing","count" => "8 118","real_id" =>137,),
"138"=>array("name_ru"=>"Чунцин","name_en"=>"Chongqing","name_href" => "cn/population-of-chongqing","count" => "29 914 000","real_id" =>138,),
"139"=>array("name_ru"=>"Шанхай","name_en"=>"Shanghai","name_href" => "cn/population-of-shanghai","count" => "24 150 000","real_id" =>139,),
"140"=>array("name_ru"=>"Пекин","name_en"=>"Beijing","name_href" => "cn/population-of-beijing","count" => "21 705 000","real_id" =>140,),
"141"=>array("name_ru"=>"Тяньцзинь","name_en"=>"Tianjin","name_href" => "cn/population-of-tianjin","count" => "14 425 000","real_id" =>141,),
"142"=>array("name_ru"=>"Наньян","name_en"=>"Nanyang","name_href" => "cn/population-of-nanyang","count" => "12 010 000","real_id" =>142,)


);

?>




<?php 
//Белоруссия 100 
$libby = array ( 
"1"=>array("name_ru"=>"Минск","name_en"=>"Minsk","name_href" => "by/population-of-minsk","count" => "1 949 059","real_id" =>1,),
"2"=>array("name_ru"=>"Гомель","name_en"=>"Gomel","name_href" => "by/population-of-gomel","count" => "526 873","real_id" =>2,),
"3"=>array("name_ru"=>"Могилёв","name_en"=>"Mogilev","name_href" => "by/population-of-mogilev","count" => "374 644","real_id" =>3,),
"4"=>array("name_ru"=>"Витебск","name_en"=>"Vitebsk","name_href" => "by/population-of-vitebsk","count" => "373 764","real_id" =>4,),
"5"=>array("name_ru"=>"Гродно","name_en"=>"Grodno","name_href" => "by/population-of-grodno","count" => "361 358","real_id" =>5,),
"6"=>array("name_ru"=>"Брест","name_en"=>"Brest","name_href" => "by/population-of-brest","count" => "337 428","real_id" =>6,),
"7"=>array("name_ru"=>"Бобруйск","name_en"=>"Bobruisk","name_href" => "by/population-of-bobruisk","count" => "217 127","real_id" =>7,),
"8"=>array("name_ru"=>"Барановичи","name_en"=>"Baranavichy","name_href" => "by/population-of-baranavichy","count" => "170 685","real_id" =>8,),
"9"=>array("name_ru"=>"Борисов","name_en"=>"Borisov","name_href" => "by/population-of-borisov","count" => "145 659","real_id" =>9,),
"10"=>array("name_ru"=>"Пинск","name_en"=>"Pinsk","name_href" => "by/population-of-pinsk","count" => "135 619","real_id" =>10,),
"11"=>array("name_ru"=>"Орша","name_en"=>"Orsha","name_href" => "by/population-of-orsha","count" => "116 611","real_id" =>11,),
"12"=>array("name_ru"=>"Мозырь","name_en"=>"Mozyr","name_href" => "by/population-of-mozyr","count" => "111 324","real_id" =>12,),
"13"=>array("name_ru"=>"Новополоцк","name_en"=>"Novopolotsk","name_href" => "by/population-of-novopolotsk","count" => "108 176","real_id" =>13,),
"14"=>array("name_ru"=>"Солигорск","name_en"=>"Soligorsk","name_href" => "by/population-of-soligorsk","count" => "104 745","real_id" =>14,),
"15"=>array("name_ru"=>"Лида","name_en"=>"Lida","name_href" => "by/population-of-lida","count" => "99 430","real_id" =>15,),
"16"=>array("name_ru"=>"Молодечно","name_en"=>"Molodechno","name_href" => "by/population-of-molodechno","count" => "93 802","real_id" =>16,),
"17"=>array("name_ru"=>"Полоцк","name_en"=>"Polotsk","name_href" => "by/population-of-polotsk","count" => "84 786","real_id" =>17,),
"18"=>array("name_ru"=>"Жлобин","name_en"=>"Zhlobin","name_href" => "by/population-of-zhlobin","count" => "75 377","real_id" =>18,),
"19"=>array("name_ru"=>"Светлогорск","name_en"=>"Svetlogorsk","name_href" => "by/population-of-svetlogorsk","count" => "69 028","real_id" =>19,),
"20"=>array("name_ru"=>"Речица","name_en"=>"Rechitsa","name_href" => "by/population-of-rechitsa","count" => "65 289","real_id" =>20,),
"21"=>array("name_ru"=>"Жодино","name_en"=>"Zhodino","name_href" => "by/population-of-zhodino","count" => "62 696","real_id" =>21,),
"22"=>array("name_ru"=>"Слуцк","name_en"=>"Slutsk","name_href" => "by/population-of-slutsk","count" => "61 847","real_id" =>22,),
"23"=>array("name_ru"=>"Кобрин","name_en"=>"Kobrin","name_href" => "by/population-of-kobrin","count" => "52 001","real_id" =>23,),
"24"=>array("name_ru"=>"Слоним","name_en"=>"Slonim","name_href" => "by/population-of-slonim","count" => "48 977","real_id" =>24,),
"25"=>array("name_ru"=>"Волковыск","name_en"=>"Volkovysk","name_href" => "by/population-of-volkovysk","count" => "43 839","real_id" =>25,),
"26"=>array("name_ru"=>"Калинковичи","name_en"=>"Kalinkovichi","name_href" => "by/population-of-kalinkovichi","count" => "39 220","real_id" =>26,),
"27"=>array("name_ru"=>"Сморгонь","name_en"=>"Smorgon","name_href" => "by/population-of-smorgon","count" => "36 942","real_id" =>27,),
"28"=>array("name_ru"=>"Рогачёв","name_en"=>"Rogachev","name_href" => "by/population-of-rogachev","count" => "34 476","real_id" =>28,),
"29"=>array("name_ru"=>"Осиповичи","name_en"=>"Osipovichi","name_href" => "by/population-of-osipovichi","count" => "31 629","real_id" =>29,),
"30"=>array("name_ru"=>"Горки","name_en"=>"Hills","name_href" => "by/population-of-hills","count" => "31 432","real_id" =>30,),
"31"=>array("name_ru"=>"Берёза","name_en"=>"Birch","name_href" => "by/population-of-birch","count" => "29 328","real_id" =>31,),
"32"=>array("name_ru"=>"Новогрудок","name_en"=>"Novogrudok","name_href" => "by/population-of-novogrudok","count" => "29 065","real_id" =>32,),
"33"=>array("name_ru"=>"Вилейка","name_en"=>"Vileika","name_href" => "by/population-of-vileika","count" => "26 874","real_id" =>33,),
"34"=>array("name_ru"=>"Кричев","name_en"=>"Krichev","name_href" => "by/population-of-krichev","count" => "26 513","real_id" =>34,),
"35"=>array("name_ru"=>"Дзержинск","name_en"=>"Dzerzhinsk","name_href" => "by/population-of-dzerzhinsk","count" => "26 052","real_id" =>35,),
"36"=>array("name_ru"=>"Лунинец","name_en"=>"Luninets","name_href" => "by/population-of-luninets","count" => "24 095","real_id" =>36,),
"37"=>array("name_ru"=>"Ивацевичи","name_en"=>"Ivatsevichi","name_href" => "by/population-of-ivatsevichi","count" => "23 278","real_id" =>37,),
"38"=>array("name_ru"=>"Марьина Горка","name_en"=>"Marina Gorka","name_href" => "by/population-of-marina-gorka","count" => "21 107","real_id" =>38,),
"39"=>array("name_ru"=>"Поставы","name_en"=>"Postavy","name_href" => "by/population-of-postavy","count" => "19 897","real_id" =>39,),
"40"=>array("name_ru"=>"Пружаны","name_en"=>"Pruzhany","name_href" => "by/population-of-pruzhany","count" => "18 884","real_id" =>40,),
"41"=>array("name_ru"=>"Глубокое","name_en"=>"Deep","name_href" => "by/population-of-deep","count" => "18 534","real_id" =>41,),
"42"=>array("name_ru"=>"Добруш","name_en"=>"Dobrush","name_href" => "by/population-of-dobrush","count" => "18 183","real_id" =>42,),
"43"=>array("name_ru"=>"Лепель","name_en"=>"Lepel","name_href" => "by/population-of-lepel","count" => "17 577","real_id" =>43,),
"44"=>array("name_ru"=>"Быхов","name_en"=>"Byhov","name_href" => "by/population-of-byhov","count" => "16 818","real_id" =>44,),
"45"=>array("name_ru"=>"Иваново","name_en"=>"Ivanovo","name_href" => "by/population-of-ivanovo","count" => "16 456","real_id" =>45,),
"46"=>array("name_ru"=>"Климовичи","name_en"=>"Klimovichi","name_href" => "by/population-of-klimovichi","count" => "16 383","real_id" =>46,),
"47"=>array("name_ru"=>"Шклов","name_en"=>"Shklov","name_href" => "by/population-of-shklov","count" => "16 353","real_id" =>47,),
"48"=>array("name_ru"=>"Столбцы","name_en"=>"Columns","name_href" => "by/population-of-columns","count" => "16 283","real_id" =>48,),
"49"=>array("name_ru"=>"Костюковичи","name_en"=>"Kostiukovichi","name_href" => "by/population-of-kostiukovichi","count" => "15 879","real_id" =>49,),
"50"=>array("name_ru"=>"Житковичи","name_en"=>"Zhitkovichi","name_href" => "by/population-of-zhitkovichi","count" => "15 828","real_id" =>50,),
"51"=>array("name_ru"=>"Мосты","name_en"=>"Bridges","name_href" => "by/population-of-bridges","count" => "15 721","real_id" =>51,),
"52"=>array("name_ru"=>"Ошмяны","name_en"=>"Oshmyany","name_href" => "by/population-of-oshmyany","count" => "15 668","real_id" =>52,),
"53"=>array("name_ru"=>"Смолевичи","name_en"=>"Smolevichi","name_href" => "by/population-of-smolevichi","count" => "15 449","real_id" =>53,),
"54"=>array("name_ru"=>"Щучин","name_en"=>"Schuchin","name_href" => "by/population-of-schuchin","count" => "15 283","real_id" =>54,),
"55"=>array("name_ru"=>"Дрогичин","name_en"=>"Drogichin","name_href" => "by/population-of-drogichin","count" => "14 651","real_id" =>55,),
"56"=>array("name_ru"=>"Несвиж","name_en"=>"Nesvizh","name_href" => "by/population-of-nesvizh","count" => "14 612","real_id" =>56,),
"57"=>array("name_ru"=>"Заславль","name_en"=>"Zaslavl","name_href" => "by/population-of-zaslavl","count" => "14 551","real_id" =>57,),
"58"=>array("name_ru"=>"Ганцевичи","name_en"=>"Gantsevichi","name_href" => "by/population-of-gantsevichi","count" => "13 897","real_id" =>58,),
"59"=>array("name_ru"=>"Хойники","name_en"=>"Khoiniki","name_href" => "by/population-of-khoiniki","count" => "13 320","real_id" =>59,),
"60"=>array("name_ru"=>"Фаниполь","name_en"=>"Fanipol","name_href" => "by/population-of-fanipol","count" => "13 260","real_id" =>60,),
"61"=>array("name_ru"=>"Жабинка","name_en"=>"Jig","name_href" => "by/population-of-jig","count" => "13 201","real_id" =>61,),
"62"=>array("name_ru"=>"Новолукомль","name_en"=>"Novolukoml","name_href" => "by/population-of-novolukoml","count" => "13 141","real_id" =>62,),
"63"=>array("name_ru"=>"Микашевичи","name_en"=>"Mikashevichi","name_href" => "by/population-of-mikashevichi","count" => "12 896","real_id" =>63,),
"64"=>array("name_ru"=>"Белоозёрска","name_en"=>"Beloozersk","name_href" => "by/population-of-beloozersk","count" => "12 462","real_id" =>64,),
"65"=>array("name_ru"=>"Столин","name_en"=>"Stolin","name_href" => "by/population-of-stolin","count" => "12 439","real_id" =>65,),
"66"=>array("name_ru"=>"Городок","name_en"=>"Town","name_href" => "by/population-of-town","count" => "12 058","real_id" =>66,),
"67"=>array("name_ru"=>"Березино","name_en"=>"Berezino","name_href" => "by/population-of-berezino","count" => "11 984","real_id" =>67,),
"68"=>array("name_ru"=>"Логойск","name_en"=>"Logoisk","name_href" => "by/population-of-logoisk","count" => "11 825","real_id" =>68,),
"69"=>array("name_ru"=>"Малорита","name_en"=>"Malorita","name_href" => "by/population-of-malorita","count" => "11 727","real_id" =>69,),
"70"=>array("name_ru"=>"Барань","name_en"=>"Ram","name_href" => "by/population-of-ram","count" => "11 453","real_id" =>70,),
"71"=>array("name_ru"=>"Любань","name_en"=>"Luban","name_href" => "by/population-of-luban","count" => "11 186","real_id" =>71,),
"72"=>array("name_ru"=>"Клецк","name_en"=>"Kletsk","name_href" => "by/population-of-kletsk","count" => "11 021","real_id" =>72,),
"73"=>array("name_ru"=>"Ляховичи","name_en"=>"Lyakhovichi","name_href" => "by/population-of-lyakhovichi","count" => "11 007","real_id" =>73,),
"74"=>array("name_ru"=>"Старые Дороги","name_en"=>"Old Roads","name_href" => "by/population-of-old-roads","count" => "10 774","real_id" =>74,),
"75"=>array("name_ru"=>"Чаусы","name_en"=>"Chauses","name_href" => "by/population-of-chauses","count" => "10 749","real_id" =>75,),
"76"=>array("name_ru"=>"Скидель","name_en"=>"Skidel","name_href" => "by/population-of-skidel","count" => "10 604","real_id" =>76,),
"77"=>array("name_ru"=>"Мстиславль","name_en"=>"Mstislavl","name_href" => "by/population-of-mstislavl","count" => "10 596","real_id" =>77,),
"78"=>array("name_ru"=>"Берёзовка","name_en"=>"Berezovka","name_href" => "by/population-of-berezovka","count" => "10 559","real_id" =>78,),
"79"=>array("name_ru"=>"Воложин","name_en"=>"Volozhin","name_href" => "by/population-of-volozhin","count" => "10 483","real_id" =>79,),
"80"=>array("name_ru"=>"Петриков","name_en"=>"Petrikov","name_href" => "by/population-of-petrikov","count" => "10 382","real_id" =>80,),
"81"=>array("name_ru"=>"Толочин","name_en"=>"Tolochin","name_href" => "by/population-of-tolochin","count" => "9 894","real_id" =>81,),
"82"=>array("name_ru"=>"Узда","name_en"=>"Bridle","name_href" => "by/population-of-bridle","count" => "9 870","real_id" =>82,),
"83"=>array("name_ru"=>"Копыль","name_en"=>"Copper","name_href" => "by/population-of-copper","count" => "9 858","real_id" =>83,),
"84"=>array("name_ru"=>"Червень","name_en"=>"Cherven","name_href" => "by/population-of-cherven","count" => "9 842","real_id" =>84,),
"85"=>array("name_ru"=>"Браслав","name_en"=>"Braslav","name_href" => "by/population-of-braslav","count" => "9 593","real_id" =>85,),
"86"=>array("name_ru"=>"Ельск","name_en"=>"Yelsk","name_href" => "by/population-of-yelsk","count" => "9 369","real_id" =>86,),
"87"=>array("name_ru"=>"Чашники","name_en"=>"Chashniki","name_href" => "by/population-of-chashniki","count" => "9 009","real_id" =>87,),
"88"=>array("name_ru"=>"Островец","name_en"=>"Astravets","name_href" => "by/population-of-astravets","count" => "8 733","real_id" =>88,),
"89"=>array("name_ru"=>"Кировск","name_en"=>"Kirovsk","name_href" => "by/population-of-kirovsk","count" => "8 660","real_id" =>89,),
"90"=>array("name_ru"=>"Крупки","name_en"=>"Krupki","name_href" => "by/population-of-krupki","count" => "8 607","real_id" =>90,),
"91"=>array("name_ru"=>"Буда-Кошелёво","name_en"=>"Buda-Kosheljevo","name_href" => "by/population-of-buda-kosheljevo","count" => "8 539","real_id" =>91,),
"92"=>array("name_ru"=>"Каменец","name_en"=>"Kamianets","name_href" => "by/population-of-kamianets","count" => "8 418","real_id" =>92,),
"93"=>array("name_ru"=>"Чериков","name_en"=>"Cherikov","name_href" => "by/population-of-cherikov","count" => "8 247","real_id" =>93,),
"94"=>array("name_ru"=>"Ветка","name_en"=>"Branch","name_href" => "by/population-of-branch","count" => "8 138","real_id" =>94,),
"95"=>array("name_ru"=>"Миоры","name_en"=>"Miory","name_href" => "by/population-of-miory","count" => "8 094","real_id" =>95,),
"96"=>array("name_ru"=>"Чечерск","name_en"=>"Chechersk","name_href" => "by/population-of-chechersk","count" => "8 059","real_id" =>96,),
"97"=>array("name_ru"=>"Наровля","name_en"=>"Narovlya","name_href" => "by/population-of-narovlya","count" => "8 026","real_id" =>97,),
"98"=>array("name_ru"=>"Ивье","name_en"=>"Ivier","name_href" => "by/population-of-ivier","count" => "7 888","real_id" =>98,),
"99"=>array("name_ru"=>"Славгород","name_en"=>"Slavgorod","name_href" => "by/population-of-slavgorod","count" => "7 767","real_id" =>99,),
"100"=>array("name_ru"=>"Сенно","name_en"=>"Senno","name_href" => "by/population-of-senno","count" => "7 601","real_id" =>100,),
"101"=>array("name_ru"=>"Минск","name_en"=>"Minsk","name_href" => "by/population-of-minsk","count" => "1 949 059","real_id" =>101,),
"102"=>array("name_ru"=>"Гомель","name_en"=>"Gomel","name_href" => "by/population-of-gomel","count" => "526 873","real_id" =>102,),
"103"=>array("name_ru"=>"Могилёв","name_en"=>"Mogilev","name_href" => "by/population-of-mogilev","count" => "374 644","real_id" =>103,),
"104"=>array("name_ru"=>"Витебск","name_en"=>"Vitebsk","name_href" => "by/population-of-vitebsk","count" => "373 764","real_id" =>104,),
"105"=>array("name_ru"=>"Гродно","name_en"=>"Grodno","name_href" => "by/population-of-grodno","count" => "361 358","real_id" =>105,)
);

// print_r($_SERVER);

// print $_SERVER['REQUEST_URI'];

// print $libby[ltrim($_SERVER['REQUEST_URI'], '/')]['name_ru'].' <br/>';
// print $libby[ltrim($_SERVER['REQUEST_URI'], '/')]['name_en'].' <br/>';
// print $libby[ltrim($_SERVER['REQUEST_URI'], '/')]['name_href'].' <br/>';
// print $libby[ltrim($_SERVER['REQUEST_URI'], '/')]['count'].' <br/>';
// print $libby[ltrim($_SERVER['REQUEST_URI'], '/')]['real_id'].' <br/>';
?>


