<?php
//Камерун 43
$libcm = array ( 
"1"=>array("name_ru"=>"Яунде","name_en"=>"Yaounde","name_href" => "cm/population-of-yaounde","count" => "1 926 496","real_id" =>1,),
"2"=>array("name_ru"=>"Дуала","name_en"=>"Douala","name_href" => "cm/population-of-douala","count" => "1 884 802","real_id" =>2,),
"3"=>array("name_ru"=>"Гаруа","name_en"=>"Garoua","name_href" => "cm/population-of-garoua","count" => "287 586","real_id" =>3,),
"4"=>array("name_ru"=>"Баменда","name_en"=>"Bamenda","name_href" => "cm/population-of-bamenda","count" => "229 109","real_id" =>4,),
"5"=>array("name_ru"=>"Маруа","name_en"=>"Maroua","name_href" => "cm/population-of-maroua","count" => "205 635","real_id" =>5,),
"6"=>array("name_ru"=>"Бафусам","name_en"=>"Bafoussam","name_href" => "cm/population-of-bafoussam","count" => "185 635","real_id" =>6,),
"7"=>array("name_ru"=>"Куссери","name_en"=>"Kousseri","name_href" => "cm/population-of-kousseri","count" => "176 241","real_id" =>7,),
"8"=>array("name_ru"=>"Нгаундере","name_en"=>"Ngaoundéré","name_href" => "cm/population-of-ngaoundéré","count" => "143 030","real_id" =>8,),
"9"=>array("name_ru"=>"Кумба","name_en"=>"Kumba","name_href" => "cm/population-of-kumba","count" => "143 014","real_id" =>9,),
"10"=>array("name_ru"=>"Лум","name_en"=>"Lum","name_href" => "cm/population-of-lum","count" => "131 319","real_id" =>10,),
"11"=>array("name_ru"=>"Нконгсамба","name_en"=>"Nkongsamba","name_href" => "cm/population-of-nkongsamba","count" => "114 986","real_id" =>11,),
"12"=>array("name_ru"=>"Лимбе","name_en"=>"Limbe","name_href" => "cm/population-of-limbe","count" => "96 629","real_id" =>12,),
"13"=>array("name_ru"=>"Эдеа","name_en"=>"Edéa","name_href" => "cm/population-of-edéa","count" => "91 917","real_id" =>13,),
"14"=>array("name_ru"=>"Фумбан","name_en"=>"Fumban","name_href" => "cm/population-of-fumban","count" => "88 362","real_id" =>14,),
"15"=>array("name_ru"=>"Моколо","name_en"=>"Mokolo","name_href" => "cm/population-of-mokolo","count" => "86 822","real_id" =>15,),
"16"=>array("name_ru"=>"Бертуа","name_en"=>"Bertoua","name_href" => "cm/population-of-bertoua","count" => "78 198","real_id" =>16,),
"17"=>array("name_ru"=>"Мбальмайо","name_en"=>"Mbalmayo","name_href" => "cm/population-of-mbalmayo","count" => "73 307","real_id" =>17,),
"18"=>array("name_ru"=>"Нкотенг","name_en"=>"Nkoteng","name_href" => "cm/population-of-nkoteng","count" => "71 011","real_id" =>18,),
"19"=>array("name_ru"=>"Бафанг","name_en"=>"Bafang","name_href" => "cm/population-of-bafang","count" => "69 565","real_id" =>19,),
"20"=>array("name_ru"=>"Джанг","name_en"=>"Jang","name_href" => "cm/population-of-jang","count" => "65 291","real_id" =>20,),
"21"=>array("name_ru"=>"Бафиа","name_en"=>"Bafia","name_href" => "cm/population-of-bafia","count" => "63 154","real_id" =>21,),
"22"=>array("name_ru"=>"Кумбо","name_en"=>"Kumbo","name_href" => "cm/population-of-kumbo","count" => "62 239","real_id" =>22,),
"23"=>array("name_ru"=>"Эболова","name_en"=>"East Tawas","name_href" => "cm/population-of-east-tawas","count" => "60 360","real_id" =>23,),
"24"=>array("name_ru"=>"Мбуда","name_en"=>"Buea","name_href" => "cm/population-of-buea","count" => "59 765","real_id" =>24,),
"25"=>array("name_ru"=>"Гидер","name_en"=>"Hider","name_href" => "cm/population-of-hider","count" => "56 888","real_id" =>25,),
"26"=>array("name_ru"=>"Мейганга","name_en"=>"Maganga","name_href" => "cm/population-of-maganga","count" => "54 096","real_id" =>26,),
"27"=>array("name_ru"=>"Буэа","name_en"=>"Of Buea","name_href" => "cm/population-of-of-buea","count" => "51 469","real_id" =>27,),
"28"=>array("name_ru"=>"Ягуа","name_en"=>"Yagua","name_href" => "cm/population-of-yagua","count" => "50 706","real_id" =>28,),
"29"=>array("name_ru"=>"Фумбот","name_en"=>"Foumbot","name_href" => "cm/population-of-foumbot","count" => "49 463","real_id" =>29,),
"30"=>array("name_ru"=>"Тико","name_en"=>"Tico","name_href" => "cm/population-of-tico","count" => "48 220","real_id" =>30,),
"31"=>array("name_ru"=>"Сангмелима","name_en"=>"Sangmelima","name_href" => "cm/population-of-sangmelima","count" => "46 958","real_id" =>31,),
"32"=>array("name_ru"=>"Бали","name_en"=>"Bali","name_href" => "cm/population-of-bali","count" => "46 028","real_id" =>32,),
"33"=>array("name_ru"=>"Бангангте","name_en"=>"Bangangte","name_href" => "cm/population-of-bangangte","count" => "44 735","real_id" =>33,),
"34"=>array("name_ru"=>"Вум","name_en"=>"VUM","name_href" => "cm/population-of-vum","count" => "42 321","real_id" =>34,),
"35"=>array("name_ru"=>"Мора","name_en"=>"Mora","name_href" => "cm/population-of-mora","count" => "38 995","real_id" =>35,),
"36"=>array("name_ru"=>"Баньо","name_en"=>"Bagno","name_href" => "cm/population-of-bagno","count" => "37 798","real_id" =>36,),
"37"=>array("name_ru"=>"Криби","name_en"=>"Kribi","name_href" => "cm/population-of-kribi","count" => "37 411","real_id" =>37,),
"38"=>array("name_ru"=>"Батури","name_en"=>"Batura","name_href" => "cm/population-of-batura","count" => "36 258","real_id" =>38,),
"39"=>array("name_ru"=>"Тибати","name_en"=>"Tibati","name_href" => "cm/population-of-tibati","count" => "33 093","real_id" =>39,),
"40"=>array("name_ru"=>"Мелонг","name_en"=>"Belong","name_href" => "cm/population-of-belong","count" => "33 001","real_id" =>40,),
"41"=>array("name_ru"=>"Мутенгене","name_en"=>"Mutengene","name_href" => "cm/population-of-mutengene","count" => "32 936","real_id" =>41,),
"42"=>array("name_ru"=>"Гаруа Булаи","name_en"=>"Garoua Bulai","name_href" => "cm/population-of-garoua-bulai","count" => "31 682","real_id" =>42,),
"43"=>array("name_ru"=>"Мбанга","name_en"=>"Manga","name_href" => "cm/population-of-manga","count" => "30 278","real_id" =>43,),
"44"=>array("name_ru"=>"Яунде","name_en"=>"Yaounde","name_href" => "cm/population-of-yaounde","count" => "1 926 496","real_id" =>44,),
"45"=>array("name_ru"=>"Дуала","name_en"=>"Douala","name_href" => "cm/population-of-douala","count" => "1 884 802","real_id" =>45,),
"46"=>array("name_ru"=>"Гаруа","name_en"=>"Garoua","name_href" => "cm/population-of-garoua","count" => "287 586","real_id" =>46,),
"47"=>array("name_ru"=>"Баменда","name_en"=>"Bamenda","name_href" => "cm/population-of-bamenda","count" => "229 109","real_id" =>47,),
"48"=>array("name_ru"=>"Маруа","name_en"=>"Maroua","name_href" => "cm/population-of-maroua","count" => "205 635","real_id" =>48,)
);

?>