<?php
//Швейцария 143 
$libch = array ( 
"1"=>array("name_ru"=>"Цюрих ","name_en"=>"Zurich","name_href" => "ch/population-of-zurich","count" => "402 275","real_id" =>1,),
"2"=>array("name_ru"=>"Женева ","name_en"=>"Geneva","name_href" => "ch/population-of-geneva","count" => "196 150","real_id" =>2,),
"3"=>array("name_ru"=>"Базель ","name_en"=>"Basel","name_href" => "ch/population-of-basel","count" => "173 960","real_id" =>3,),
"4"=>array("name_ru"=>"Лозанна ","name_en"=>"Lausanne","name_href" => "ch/population-of-lausanne","count" => "132 626","real_id" =>4,),
"5"=>array("name_ru"=>"Берн ","name_en"=>"Berne","name_href" => "ch/population-of-berne","count" => "128 848","real_id" =>5,),
"6"=>array("name_ru"=>"Винтертур ","name_en"=>"Winterthur","name_href" => "ch/population-of-winterthur","count" => "105 676","real_id" =>6,),
"7"=>array("name_ru"=>"Люцерн ","name_en"=>"Lucerne","name_href" => "ch/population-of-lucerne","count" => "80 501","real_id" =>7,),
"8"=>array("name_ru"=>"Санкт-Галлен ","name_en"=>"St. Gallen","name_href" => "ch/population-of-st-gallen","count" => "74 581","real_id" =>8,),
"9"=>array("name_ru"=>"Лугано ","name_en"=>"Lugano","name_href" => "ch/population-of-lugano","count" => "62 792","real_id" =>9,),
"10"=>array("name_ru"=>"Биль / Бьен ","name_en"=>"Biel / Bienne","name_href" => "ch/population-of-biel-bienne","count" => "53 031","real_id" =>10,),
"11"=>array("name_ru"=>"Тун ","name_en"=>"Thun","name_href" => "ch/population-of-thun","count" => "42 929","real_id" =>11,),
"12"=>array("name_ru"=>"Кёниц","name_en"=>"Könitz","name_href" => "ch/population-of-könitz","count" => "39 794","real_id" =>12,),
"13"=>array("name_ru"=>"Ла-Шо-де-Фон","name_en"=>"La Chaux-de-Fonds","name_href" => "ch/population-of-la-chaux-de-fonds","count" => "38 694","real_id" =>13,),
"14"=>array("name_ru"=>"Фрибур","name_en"=>"Friborg","name_href" => "ch/population-of-friborg","count" => "37 485","real_id" =>14,),
"15"=>array("name_ru"=>"Шаффхаузен ","name_en"=>"Schaffhausen","name_href" => "ch/population-of-schaffhausen","count" => "35 613","real_id" =>15,),
"16"=>array("name_ru"=>"Кур","name_en"=>"Cour","name_href" => "ch/population-of-cour","count" => "34 350","real_id" =>16,),
"17"=>array("name_ru"=>"Верньер","name_en"=>"Vernier","name_href" => "ch/population-of-vernier","count" => "34 235","real_id" =>17,),
"18"=>array("name_ru"=>"Невшатель ","name_en"=>"Neuchatel","name_href" => "ch/population-of-neuchatel","count" => "33 641","real_id" =>18,),
"19"=>array("name_ru"=>"Устер","name_en"=>"Uster","name_href" => "ch/population-of-uster","count" => "33 097","real_id" =>19,),
"20"=>array("name_ru"=>"Сьон","name_en"=>"Sion","name_href" => "ch/population-of-sion","count" => "32 797","real_id" =>20,),
"21"=>array("name_ru"=>"Ланси","name_en"=>"Lancy","name_href" => "ch/population-of-lancy","count" => "29 350","real_id" =>21,),
"22"=>array("name_ru"=>"Эммен","name_en"=>"Emmen","name_href" => "ch/population-of-emmen","count" => "28 926","real_id" =>22,),
"23"=>array("name_ru"=>"Ивердон-ле-Бен ","name_en"=>"Yverdon-les-Bains","name_href" => "ch/population-of-yverdon-les-bains","count" => "28 377","real_id" =>23,),
"24"=>array("name_ru"=>"Цуг","name_en"=>"Zug","name_href" => "ch/population-of-zug","count" => "27 961","real_id" =>24,),
"25"=>array("name_ru"=>"Кринс","name_en"=>"Kriens","name_href" => "ch/population-of-kriens","count" => "26 957","real_id" =>25,),
"26"=>array("name_ru"=>"Рапперсвиль-Йона","name_en"=>"Rapperswil-Jonah","name_href" => "ch/population-of-rapperswil-jonah","count" => "26 542","real_id" =>26,),
"27"=>array("name_ru"=>"Дюбендорф","name_en"=>"Dubendorf","name_href" => "ch/population-of-dubendorf","count" => "25 801","real_id" =>27,),
"28"=>array("name_ru"=>"Монтрё","name_en"=>"Montreux","name_href" => "ch/population-of-montreux","count" => "25 440","real_id" =>28,),
"29"=>array("name_ru"=>"Дитикон","name_en"=>"Dietikon","name_href" => "ch/population-of-dietikon","count" => "25 426","real_id" =>29,),
"30"=>array("name_ru"=>"Фрауэнфельд ","name_en"=>"Frauenfeld","name_href" => "ch/population-of-frauenfeld","count" => "24 409","real_id" =>30,),
"31"=>array("name_ru"=>"Бар","name_en"=>"Bar","name_href" => "ch/population-of-bar","count" => "23 776","real_id" =>31,),
"32"=>array("name_ru"=>"Ветцикон","name_en"=>"Wetzikon","name_href" => "ch/population-of-wetzikon","count" => "23 726","real_id" =>32,),
"33"=>array("name_ru"=>"Виль ","name_en"=>"Wil","name_href" => "ch/population-of-wil","count" => "23 563","real_id" =>33,),
"34"=>array("name_ru"=>"Мерен","name_en"=>"Meren","name_href" => "ch/population-of-meren","count" => "21 866","real_id" =>34,),
"35"=>array("name_ru"=>"Кройцлинген","name_en"=>"Kreuzlingen","name_href" => "ch/population-of-kreuzlingen","count" => "21 212","real_id" =>35,),
"36"=>array("name_ru"=>"Веденсвиль","name_en"=>"Vedenswil","name_href" => "ch/population-of-vedenswil","count" => "21 189","real_id" =>36,),
"37"=>array("name_ru"=>"Риен","name_en"=>"Rien","name_href" => "ch/population-of-rien","count" => "20 970","real_id" =>37,),
"38"=>array("name_ru"=>"Бюль","name_en"=>"Bühl","name_href" => "ch/population-of-bühl","count" => "20 824","real_id" =>38,),
"39"=>array("name_ru"=>"Каруж ","name_en"=>"Carouge","name_href" => "ch/population-of-carouge","count" => "20 630","real_id" =>39,),
"40"=>array("name_ru"=>"Веттинген","name_en"=>"Wettingen","name_href" => "ch/population-of-wettingen","count" => "20 265","real_id" =>40,),
"41"=>array("name_ru"=>"Альшвиль","name_en"=>"Alshawil","name_href" => "ch/population-of-alshawil","count" => "20 249","real_id" =>41,),
"42"=>array("name_ru"=>"Ренан","name_en"=>"Renan","name_href" => "ch/population-of-renan","count" => "20 131","real_id" =>42,),
"43"=>array("name_ru"=>"Арау","name_en"=>"Arau","name_href" => "ch/population-of-arau","count" => "20 130","real_id" =>43,),
"44"=>array("name_ru"=>"Хорген","name_en"=>"Horgen","name_href" => "ch/population-of-horgen","count" => "19 608","real_id" =>44,),
"45"=>array("name_ru"=>"Ньон","name_en"=>"Nyon","name_href" => "ch/population-of-nyon","count" => "19 016","real_id" =>45,),
"46"=>array("name_ru"=>"Веве ","name_en"=>"Vevey","name_href" => "ch/population-of-vevey","count" => "18 854","real_id" =>46,),
"47"=>array("name_ru"=>"Райнах","name_en"=>"Reinach","name_href" => "ch/population-of-reinach","count" => "18 839","real_id" =>47,),
"48"=>array("name_ru"=>"Баден ","name_en"=>"Baden","name_href" => "ch/population-of-baden","count" => "18 523","real_id" =>48,),
"49"=>array("name_ru"=>"Бюлах ","name_en"=>"Byulah","name_href" => "ch/population-of-byulah","count" => "18 408","real_id" =>49,),
"50"=>array("name_ru"=>"Клотен","name_en"=>"Kloten","name_href" => "ch/population-of-kloten","count" => "18 400","real_id" =>50,),
"51"=>array("name_ru"=>"Адлисвиль","name_en"=>"Adliswil","name_href" => "ch/population-of-adliswil","count" => "18 262","real_id" =>51,),
"52"=>array("name_ru"=>"Фолькетсвиль","name_en"=>"Folketesville","name_href" => "ch/population-of-folketesville","count" => "18 099","real_id" =>52,),
"53"=>array("name_ru"=>"Госсау","name_en"=>"Gossau","name_href" => "ch/population-of-gossau","count" => "18 087","real_id" =>53,),
"54"=>array("name_ru"=>"Оне","name_en"=>"Ona","name_href" => "ch/population-of-ona","count" => "18 029","real_id" =>54,),
"55"=>array("name_ru"=>"Беллинцона ","name_en"=>"Bellinzona","name_href" => "ch/population-of-bellinzona","count" => "17 962","real_id" =>55,),
"56"=>array("name_ru"=>"Шлирен","name_en"=>"Schlieren","name_href" => "ch/population-of-schlieren","count" => "17 652","real_id" =>56,),
"57"=>array("name_ru"=>"Пули","name_en"=>"Bullets","name_href" => "ch/population-of-bullets","count" => "17 569","real_id" =>57,),
"58"=>array("name_ru"=>"Тальвиль","name_en"=>"Thalwil","name_href" => "ch/population-of-thalwil","count" => "17 554","real_id" =>58,),
"59"=>array("name_ru"=>"Муттенц","name_en"=>"Muttenz","name_href" => "ch/population-of-muttenz","count" => "17 370","real_id" =>59,),
"60"=>array("name_ru"=>"Ольтен ","name_en"=>"Olten","name_href" => "ch/population-of-olten","count" => "17 280","real_id" =>60,),
"61"=>array("name_ru"=>"Мартиньи ","name_en"=>"Martigny","name_href" => "ch/population-of-martigny","count" => "17 215","real_id" =>61,),
"62"=>array("name_ru"=>"Регенсдорф","name_en"=>"Regensdorf","name_href" => "ch/population-of-regensdorf","count" => "17 179","real_id" =>62,),
"63"=>array("name_ru"=>"Монте","name_en"=>"Monte","name_href" => "ch/population-of-monte","count" => "17 113","real_id" =>63,),
"64"=>array("name_ru"=>"Золотурн ","name_en"=>"Solothurn","name_href" => "ch/population-of-solothurn","count" => "16 599","real_id" =>64,),
"65"=>array("name_ru"=>"Опфикон","name_en"=>"Opticon","name_href" => "ch/population-of-opticon","count" => "16 403","real_id" =>65,),
"66"=>array("name_ru"=>"Гренхен","name_en"=>"Grenchen","name_href" => "ch/population-of-grenchen","count" => "16 401","real_id" =>66,),
"67"=>array("name_ru"=>"Сьер","name_en"=>"Sier","name_href" => "ch/population-of-sier","count" => "16 332","real_id" =>67,),
"68"=>array("name_ru"=>"Ильнау-Эффретикон","name_en"=>"Ilnau-Effretikon","name_href" => "ch/population-of-ilnau-effretikon","count" => "16 279","real_id" =>68,),
"69"=>array("name_ru"=>"Остермундиген","name_en"=>"Ostermundigen","name_href" => "ch/population-of-ostermundigen","count" => "16 185","real_id" =>69,),
"70"=>array("name_ru"=>"Бургдорф ","name_en"=>"Burgdorf","name_href" => "ch/population-of-burgdorf","count" => "15 907","real_id" =>70,),
"71"=>array("name_ru"=>"Фрайенбах","name_en"=>"Freienbach","name_href" => "ch/population-of-freienbach","count" => "15 870","real_id" =>71,),
"72"=>array("name_ru"=>"Локарно ","name_en"=>"Locarno","name_href" => "ch/population-of-locarno","count" => "15 671","real_id" =>72,),
"73"=>array("name_ru"=>"Штеффисбург","name_en"=>"Steffisburg","name_href" => "ch/population-of-steffisburg","count" => "15 585","real_id" =>73,),
"74"=>array("name_ru"=>"Хам","name_en"=>"Ham","name_href" => "ch/population-of-ham","count" => "15 375","real_id" =>74,),
"75"=>array("name_ru"=>"Херизау","name_en"=>"Herisau","name_href" => "ch/population-of-herisau","count" => "15 342","real_id" =>75,),
"76"=>array("name_ru"=>"Праттельн","name_en"=>"Pratteln","name_href" => "ch/population-of-pratteln","count" => "15 323","real_id" =>76,),
"77"=>array("name_ru"=>"Лангенталь","name_en"=>"Langenthal","name_href" => "ch/population-of-langenthal","count" => "15 291","real_id" =>77,),
"78"=>array("name_ru"=>"Морж ","name_en"=>"Walrus","name_href" => "ch/population-of-walrus","count" => "15 228","real_id" =>78,),
"79"=>array("name_ru"=>"Волен","name_en"=>"Free","name_href" => "ch/population-of-free","count" => "15 139","real_id" =>79,),
"80"=>array("name_ru"=>"Биннинген","name_en"=>"Binningen","name_href" => "ch/population-of-binningen","count" => "14 905","real_id" =>80,),
"81"=>array("name_ru"=>"Айнзидельн","name_en"=>"Einsiedeln","name_href" => "ch/population-of-einsiedeln","count" => "14 878","real_id" =>81,),
"82"=>array("name_ru"=>"Валлизеллен","name_en"=>"Wallisellen","name_href" => "ch/population-of-wallisellen","count" => "14 858","real_id" =>82,),
"83"=>array("name_ru"=>"Мендризио","name_en"=>"Mendrisio","name_href" => "ch/population-of-mendrisio","count" => "14 789","real_id" =>83,),
"84"=>array("name_ru"=>"Швиц","name_en"=>"Schwyz","name_href" => "ch/population-of-schwyz","count" => "14 785","real_id" =>84,),
"85"=>array("name_ru"=>"Лис","name_en"=>"Lis","name_href" => "ch/population-of-lis","count" => "14 200","real_id" =>85,),
"86"=>array("name_ru"=>"Арбон ","name_en"=>"Arbon","name_href" => "ch/population-of-arbon","count" => "14 154","real_id" =>86,),
"87"=>array("name_ru"=>"Штефа","name_en"=>"Stefa","name_href" => "ch/population-of-stefa","count" => "13 931","real_id" =>87,),
"88"=>array("name_ru"=>"Листаль ","name_en"=>"Liestal","name_href" => "ch/population-of-liestal","count" => "13 807","real_id" =>88,),
"89"=>array("name_ru"=>"Хорв","name_en"=>"Horw","name_href" => "ch/population-of-horw","count" => "13 790","real_id" =>89,),
"90"=>array("name_ru"=>"Тоне","name_en"=>"Tone","name_href" => "ch/population-of-tone","count" => "13 756","real_id" =>90,),
"91"=>array("name_ru"=>"Кюснахт","name_en"=>"Küsnacht","name_href" => "ch/population-of-küsnacht","count" => "13 658","real_id" =>91,),
"92"=>array("name_ru"=>"Майлен","name_en"=>"Mailen","name_href" => "ch/population-of-mailen","count" => "13 082","real_id" =>92,),
"93"=>array("name_ru"=>"Офтринген","name_en"=>"Oftringen","name_href" => "ch/population-of-oftringen","count" => "13 073","real_id" =>93,),
"94"=>array("name_ru"=>"Рихтерсвиль","name_en"=>"Richterswil","name_href" => "ch/population-of-richterswil","count" => "13 022","real_id" =>94,),
"95"=>array("name_ru"=>"Версуа","name_en"=>"Versoix","name_href" => "ch/population-of-versoix","count" => "13 021","real_id" =>95,),
"96"=>array("name_ru"=>"Мури-Берн","name_en"=>"Muri-Berne","name_href" => "ch/population-of-muri-berne","count" => "12 901","real_id" =>96,),
"97"=>array("name_ru"=>"Бриг","name_en"=>"Brig","name_href" => "ch/population-of-brig","count" => "12 823","real_id" =>97,),
"98"=>array("name_ru"=>"Амрисвиль","name_en"=>"Amriswil","name_href" => "ch/population-of-amriswil","count" => "12 763","real_id" =>98,),
"99"=>array("name_ru"=>"Уцвиль","name_en"=>"Utsvil","name_href" => "ch/population-of-utsvil","count" => "12 698","real_id" =>99,),
"100"=>array("name_ru"=>"Эбикон","name_en"=>"Ebikon","name_href" => "ch/population-of-ebikon","count" => "12 602","real_id" =>100,),
"101"=>array("name_ru"=>"Шпиц","name_en"=>"Spitz","name_href" => "ch/population-of-spitz","count" => "12 577","real_id" =>101,),
"102"=>array("name_ru"=>"Райнфельден","name_en"=>"Rheinfelden","name_href" => "ch/population-of-rheinfelden","count" => "12 552","real_id" =>102,),
"103"=>array("name_ru"=>"Гларус","name_en"=>"Glarus","name_href" => "ch/population-of-glarus","count" => "12 422","real_id" =>103,),
"104"=>array("name_ru"=>"Цолликон","name_en"=>"Zollikon","name_href" => "ch/population-of-zollikon","count" => "12 324","real_id" =>104,),
"105"=>array("name_ru"=>"Делемон","name_en"=>"Delemont","name_href" => "ch/population-of-delemont","count" => "12 186","real_id" =>105,),
"106"=>array("name_ru"=>"Виллар-сюр-Глан","name_en"=>"Villars sur Glane","name_href" => "ch/population-of-villars-sur-glane","count" => "12 057","real_id" =>106,),
"107"=>array("name_ru"=>"Экубленс","name_en"=>"Ecublens","name_href" => "ch/population-of-ecublens","count" => "12 009","real_id" =>107,),
"108"=>array("name_ru"=>"Рюти","name_en"=>"Ryti","name_href" => "ch/population-of-ryti","count" => "11 993","real_id" =>108,),
"109"=>array("name_ru"=>"Гланд","name_en"=>"Gland","name_href" => "ch/population-of-gland","count" => "11 947","real_id" =>109,),
"110"=>array("name_ru"=>"Букс","name_en"=>"Bucs","name_href" => "ch/population-of-bucs","count" => "11 938","real_id" =>110,),
"111"=>array("name_ru"=>"Саконне","name_en"=>"Saconnex","name_href" => "ch/population-of-saconnex","count" => "11 911","real_id" =>111,),
"112"=>array("name_ru"=>"Мюнхенштайн","name_en"=>"Münchenstein","name_href" => "ch/population-of-münchenstein","count" => "11 688","real_id" =>112,),
"113"=>array("name_ru"=>"Мюнзинген","name_en"=>"Munsingen","name_href" => "ch/population-of-munsingen","count" => "11 651","real_id" =>113,),
"114"=>array("name_ru"=>"Прилли","name_en"=>"Prilly","name_href" => "ch/population-of-prilly","count" => "11 609","real_id" =>114,),
"115"=>array("name_ru"=>"Ворб","name_en"=>"Worb","name_href" => "ch/population-of-worb","count" => "11 370","real_id" =>115,),
"116"=>array("name_ru"=>"Аффольтерн-на-Альбисе","name_en"=>"Affoltern-on-Albis","name_href" => "ch/population-of-affoltern-on-albis","count" => "11 363","real_id" =>116,),
"117"=>array("name_ru"=>"Бассерсдорф","name_en"=>"Bassersdorf","name_href" => "ch/population-of-bassersdorf","count" => "11 350","real_id" =>117,),
"118"=>array("name_ru"=>"Бельп","name_en"=>"Belp","name_href" => "ch/population-of-belp","count" => "11 346","real_id" =>118,),
"119"=>array("name_ru"=>"Давос","name_en"=>"Davos","name_href" => "ch/population-of-davos","count" => "11 211","real_id" =>119,),
"120"=>array("name_ru"=>"Альтштеттен","name_en"=>"Altstetten","name_href" => "ch/population-of-altstetten","count" => "11 168","real_id" =>120,),
"121"=>array("name_ru"=>"Пфеффикон","name_en"=>"Pfaffikon","name_href" => "ch/population-of-pfaffikon","count" => "11 105","real_id" =>121,),
"122"=>array("name_ru"=>"Цофинген ","name_en"=>"Zofingen","name_href" => "ch/population-of-zofingen","count" => "11 070","real_id" =>122,),
"123"=>array("name_ru"=>"Иттиген","name_en"=>"Ittigen","name_href" => "ch/population-of-ittigen","count" => "11 067","real_id" =>123,),
"124"=>array("name_ru"=>"Арт","name_en"=>"Art","name_href" => "ch/population-of-art","count" => "11 062","real_id" =>124,),
"125"=>array("name_ru"=>"Шпрайтенбах","name_en"=>"Spreitenbach","name_href" => "ch/population-of-spreitenbach","count" => "10 982","real_id" =>125,),
"126"=>array("name_ru"=>"Ла тур де-Пеилз","name_en"=>"La Tour de Peiles","name_href" => "ch/population-of-la-tour-de-peiles","count" => "10 974","real_id" =>126,),
"127"=>array("name_ru"=>"Валь-де-Траверс","name_en"=>"Val de Traverse","name_href" => "ch/population-of-val-de-traverse","count" => "10 913","real_id" =>127,),
"128"=>array("name_ru"=>"Бругг ","name_en"=>"Brugg","name_href" => "ch/population-of-brugg","count" => "10 889","real_id" =>128,),
"129"=>array("name_ru"=>"Вайнфельден","name_en"=>"Weinfelden","name_href" => "ch/population-of-weinfelden","count" => "10 877","real_id" =>129,),
"130"=>array("name_ru"=>"Вейриер","name_en"=>"Weirier","name_href" => "ch/population-of-weirier","count" => "10 799","real_id" =>130,),
"131"=>array("name_ru"=>"Обервиль","name_en"=>"Oberwil","name_href" => "ch/population-of-oberwil","count" => "10 775","real_id" =>131,),
"132"=>array("name_ru"=>"Хинвиль","name_en"=>"Hinwil","name_href" => "ch/population-of-hinwil","count" => "10 751","real_id" =>132,),
"133"=>array("name_ru"=>"Мёлин","name_en"=>"Möhlin","name_href" => "ch/population-of-möhlin","count" => "10 617","real_id" =>133,),
"134"=>array("name_ru"=>"Шен-Боуджерис","name_en"=>"Shen-Bougheris","name_href" => "ch/population-of-shen-bougheris","count" => "10 559","real_id" =>134,),
"135"=>array("name_ru"=>"Романсхорн","name_en"=>"Romanshorn","name_href" => "ch/population-of-romanshorn","count" => "10 535","real_id" =>135,),
"136"=>array("name_ru"=>"Меннедорф","name_en"=>"Mennedorf","name_href" => "ch/population-of-mennedorf","count" => "10 492","real_id" =>136,),
"137"=>array("name_ru"=>"Ле Локль","name_en"=>"Le Locle","name_href" => "ch/population-of-le-locle","count" => "10 422","real_id" =>137,),
"138"=>array("name_ru"=>"Нойхаузен-ам-Райнфалль","name_en"=>"Neuhausen am Rheinfall","name_href" => "ch/population-of-neuhausen-am-rheinfall","count" => "10 362","real_id" =>138,),
"139"=>array("name_ru"=>"Флавиль","name_en"=>"Flaville","name_href" => "ch/population-of-flaville","count" => "10 279","real_id" =>139,),
"140"=>array("name_ru"=>"Риш","name_en"=>"Rish","name_href" => "ch/population-of-rish","count" => "10 274","real_id" =>140,),
"141"=>array("name_ru"=>"План-лез-Уат","name_en"=>"Plan-les-Ouat","name_href" => "ch/population-of-plan-les-ouat","count" => "10 261","real_id" =>141,),
"142"=>array("name_ru"=>"Бирсфельден","name_en"=>"Birsfelden","name_href" => "ch/population-of-birsfelden","count" => "10 234","real_id" =>142,),
"143"=>array("name_ru"=>"Эш","name_en"=>"Ash","name_href" => "ch/population-of-ash","count" => "10 211","real_id" =>143,),
"144"=>array("name_ru"=>"Цюрих ","name_en"=>"Zurich","name_href" => "ch/population-of-zurich","count" => "402 275","real_id" =>144,),
"145"=>array("name_ru"=>"Женева ","name_en"=>"Geneva","name_href" => "ch/population-of-geneva","count" => "196 150","real_id" =>145,),
"146"=>array("name_ru"=>"Базель ","name_en"=>"Basel","name_href" => "ch/population-of-basel","count" => "173 960","real_id" =>146,),
"147"=>array("name_ru"=>"Лозанна ","name_en"=>"Lausanne","name_href" => "ch/population-of-lausanne","count" => "132 626","real_id" =>147,),
"148"=>array("name_ru"=>"Берн ","name_en"=>"Berne","name_href" => "ch/population-of-berne","count" => "128 848","real_id" =>148,)
);

?>