<?php
//Чехия 132
$libcz = array ( 
"1"=>array("name_ru"=>"Прага","name_en"=>"Praha","name_href" => "cz/population-of-praha","count" => "1 272 690","real_id" =>1,),
"2"=>array("name_ru"=>"Брно","name_en"=>"Brno","name_href" => "cz/population-of-brno","count" => "384 277","real_id" =>2,),
"3"=>array("name_ru"=>"Острава","name_en"=>"Ostrava","name_href" => "cz/population-of-ostrava","count" => "302 456","real_id" =>3,),
"4"=>array("name_ru"=>"Пльзень","name_en"=>"Pilsen","name_href" => "cz/population-of-pilsen","count" => "169 688","real_id" =>4,),
"5"=>array("name_ru"=>"Либерец","name_en"=>"Liberec","name_href" => "cz/population-of-liberec","count" => "102 247","real_id" =>5,),
"6"=>array("name_ru"=>"Оломоуц","name_en"=>"Olomouc","name_href" => "cz/population-of-olomouc","count" => "100 043","real_id" =>6,),
"7"=>array("name_ru"=>"Усти-над-Лабем","name_en"=>"Ústí nad Labem","name_href" => "cz/population-of-ústí-nad-labem","count" => "95 003","real_id" =>7,),
"8"=>array("name_ru"=>"Градец Кралове","name_en"=>"Hradec Králové","name_href" => "cz/population-of-hradec-králové","count" => "94 242","real_id" =>8,),
"9"=>array("name_ru"=>"Ческе-Будеевице","name_en"=>"České Budějovice","name_href" => "cz/population-of-české-budějovice","count" => "93 883","real_id" =>9,),
"10"=>array("name_ru"=>"Пардубице","name_en"=>"Pardubice","name_href" => "cz/population-of-pardubice","count" => "91 073","real_id" =>10,),
"11"=>array("name_ru"=>"Гавиров","name_en"=>"Havířov","name_href" => "cz/population-of-havířov","count" => "79 679","real_id" =>11,),
"12"=>array("name_ru"=>"Злин","name_en"=>"Zlín","name_href" => "cz/population-of-zlín","count" => "76 010","real_id" =>12,),
"13"=>array("name_ru"=>"Кладно","name_en"=>"Kladno","name_href" => "cz/population-of-kladno","count" => "69 178","real_id" =>13,),
"14"=>array("name_ru"=>"Мост","name_en"=>"Most","name_href" => "cz/population-of-most","count" => "67 030","real_id" =>14,),
"15"=>array("name_ru"=>"Карвина","name_en"=>"Karviná","name_href" => "cz/population-of-karviná","count" => "59 627","real_id" =>15,),
"16"=>array("name_ru"=>"Опава","name_en"=>"Opava","name_href" => "cz/population-of-opava","count" => "58 643","real_id" =>16,),
"17"=>array("name_ru"=>"Фридек-Мистек","name_en"=>"Frýdek-Místek","name_href" => "cz/population-of-frýdek-místek","count" => "58 193","real_id" =>17,),
"18"=>array("name_ru"=>"Карловы Вары","name_en"=>"Karlovy Vary","name_href" => "cz/population-of-karlovy-vary","count" => "53 737","real_id" =>18,),
"19"=>array("name_ru"=>"Йиглава","name_en"=>"Jihlava","name_href" => "cz/population-of-jihlava","count" => "50 760","real_id" =>19,),
"20"=>array("name_ru"=>"Теплице","name_en"=>"Teplice","name_href" => "cz/population-of-teplice","count" => "50 728","real_id" =>20,),
"21"=>array("name_ru"=>"Дечин","name_en"=>"Děčín","name_href" => "cz/population-of-děčín","count" => "50 620","real_id" =>21,),
"22"=>array("name_ru"=>"Хомутов","name_en"=>"Chomutov","name_href" => "cz/population-of-chomutov","count" => "49 784","real_id" =>22,),
"23"=>array("name_ru"=>"Преров","name_en"=>"Přerov","name_href" => "cz/population-of-přerov","count" => "45 438","real_id" =>23,),
"24"=>array("name_ru"=>"Яблонец-над-Нисой","name_en"=>"Jablonec nad Nisou","name_href" => "cz/population-of-jablonec-nad-nisou","count" => "45 255","real_id" =>24,),
"25"=>array("name_ru"=>"Млада-Болеслав","name_en"=>"Mladá Boleslav","name_href" => "cz/population-of-mladá-boleslav","count" => "44 778","real_id" =>25,),
"26"=>array("name_ru"=>"Про́стеёв","name_en"=>"Prostějov","name_href" => "cz/population-of-prostějov","count" => "44 526","real_id" =>26,),
"27"=>array("name_ru"=>"Тршебич","name_en"=>"Třebíč","name_href" => "cz/population-of-třebíč","count" => "37 781","real_id" =>27,),
"28"=>array("name_ru"=>"Ческа-Липа","name_en"=>"Česká Lípa","name_href" => "cz/population-of-česká-lípa","count" => "37 510","real_id" =>28,),
"29"=>array("name_ru"=>"Тршинец","name_en"=>"Třinec","name_href" => "cz/population-of-třinec","count" => "37 056","real_id" =>29,),
"30"=>array("name_ru"=>"Та́бор","name_en"=>"Tábor","name_href" => "cz/population-of-tábor","count" => "35 198","real_id" =>30,),
"31"=>array("name_ru"=>"Зноймо","name_en"=>"Znojmo","name_href" => "cz/population-of-znojmo","count" => "34 097","real_id" =>31,),
"32"=>array("name_ru"=>"Прши́брам","name_en"=>"Příbram","name_href" => "cz/population-of-příbram","count" => "34 022","real_id" =>32,),
"33"=>array("name_ru"=>"Хеб","name_en"=>"Cheb","name_href" => "cz/population-of-cheb","count" => "33 446","real_id" =>33,),
"34"=>array("name_ru"=>"Орлова","name_en"=>"Orlová","name_href" => "cz/population-of-orlová","count" => "31 342","real_id" =>34,),
"35"=>array("name_ru"=>"Ко́лин","name_en"=>"Kolín","name_href" => "cz/population-of-kolín","count" => "31 207","real_id" =>35,),
"36"=>array("name_ru"=>"Трутнов","name_en"=>"Trutnov","name_href" => "cz/population-of-trutnov","count" => "31 085","real_id" =>36,),
"37"=>array("name_ru"=>"Пи́сек","name_en"=>"Písek","name_href" => "cz/population-of-písek","count" => "29 880","real_id" =>37,),
"38"=>array("name_ru"=>"Кромержиж","name_en"=>"Kroměříž","name_href" => "cz/population-of-kroměříž","count" => "29 076","real_id" =>38,),
"39"=>array("name_ru"=>"Шумперк","name_en"=>"Šumperk","name_href" => "cz/population-of-šumperk","count" => "27 182","real_id" =>39,),
"40"=>array("name_ru"=>"Всетин","name_en"=>"Vsetín","name_href" => "cz/population-of-vsetín","count" => "27 150","real_id" =>40,),
"41"=>array("name_ru"=>"Валашске-Мезиржичи","name_en"=>"Valasske Mezirici","name_href" => "cz/population-of-valasske-mezirici","count" => "26 930","real_id" =>41,),
"42"=>array("name_ru"=>"Литвинов","name_en"=>"Litvínov","name_href" => "cz/population-of-litvínov","count" => "26 241","real_id" =>42,),
"43"=>array("name_ru"=>"У́герске-Гра́диште","name_en"=>"Uherske Hradiste","name_href" => "cz/population-of-uherske-hradiste","count" => "25 597","real_id" =>43,),
"44"=>array("name_ru"=>"Годонин","name_en"=>"Hodonín","name_href" => "cz/population-of-hodonín","count" => "25 479","real_id" =>44,),
"45"=>array("name_ru"=>"Чески-Тешин","name_en"=>"Czech Teschen","name_href" => "cz/population-of-czech-teschen","count" => "25 234","real_id" =>45,),
"46"=>array("name_ru"=>"Бржецлав","name_en"=>"Břeclav","name_href" => "cz/population-of-břeclav","count" => "25 098","real_id" =>46,),
"47"=>array("name_ru"=>"Крнов","name_en"=>"Krnov","name_href" => "cz/population-of-krnov","count" => "24 831","real_id" =>47,),
"48"=>array("name_ru"=>"Литоме́ржице","name_en"=>"Litoměřice","name_href" => "cz/population-of-litoměřice","count" => "24 405","real_id" =>48,),
"49"=>array("name_ru"=>"Соколов","name_en"=>"Sokolov","name_href" => "cz/population-of-sokolov","count" => "24 177","real_id" =>49,),
"50"=>array("name_ru"=>"Но́ви-Йи́чин","name_en"=>"Novi-Jičín","name_href" => "cz/population-of-novi-jičín","count" => "23 909","real_id" =>50,),
"51"=>array("name_ru"=>"Га́вличкув-Брод","name_en"=>"Havlickuv Brod","name_href" => "cz/population-of-havlickuv-brod","count" => "23 723","real_id" =>51,),
"52"=>array("name_ru"=>"Хрудим","name_en"=>"Chrudim","name_href" => "cz/population-of-chrudim","count" => "23 369","real_id" =>52,),
"53"=>array("name_ru"=>"Страконице","name_en"=>"Strakonice","name_href" => "cz/population-of-strakonice","count" => "23 096","real_id" =>53,),
"54"=>array("name_ru"=>"Копршивнице","name_en"=>"Kopřivnice","name_href" => "cz/population-of-kopřivnice","count" => "22 899","real_id" =>54,),
"55"=>array("name_ru"=>"Клатовы","name_en"=>"Klatovy","name_href" => "cz/population-of-klatovy","count" => "22 567","real_id" =>55,),
"56"=>array("name_ru"=>"Ждяр-над-Сазавой","name_en"=>"Zdar nad Sazavou","name_href" => "cz/population-of-zdar-nad-sazavou","count" => "22 275","real_id" =>56,),
"57"=>array("name_ru"=>"Богумин","name_en"=>"Bohumín","name_href" => "cz/population-of-bohumín","count" => "22 044","real_id" =>57,),
"58"=>array("name_ru"=>"Йиндржихув-Градец","name_en"=>"Jindrichuv Hradec","name_href" => "cz/population-of-jindrichuv-hradec","count" => "22 036","real_id" =>58,),
"59"=>array("name_ru"=>"Ви́шков","name_en"=>"Vyškov","name_href" => "cz/population-of-vyškov","count" => "21 687","real_id" =>59,),
"60"=>array("name_ru"=>"Бланско","name_en"=>"Blansko","name_href" => "cz/population-of-blansko","count" => "20 852","real_id" =>60,),
"61"=>array("name_ru"=>"Кутна Гора","name_en"=>"Kutná Hora","name_href" => "cz/population-of-kutná-hora","count" => "20 839","real_id" =>61,),
"62"=>array("name_ru"=>"Наход","name_en"=>"Náchod","name_href" => "cz/population-of-náchod","count" => "20 763","real_id" =>62,),
"63"=>array("name_ru"=>"Йирков","name_en"=>"Jirkov","name_href" => "cz/population-of-jirkov","count" => "20 473","real_id" =>63,),
"64"=>array("name_ru"=>"Мельник","name_en"=>"Mělník","name_href" => "cz/population-of-mělník","count" => "19 612","real_id" =>64,),
"65"=>array("name_ru"=>"Жатец","name_en"=>"Žatec","name_href" => "cz/population-of-žatec","count" => "19 208","real_id" =>65,),
"66"=>array("name_ru"=>"Границе","name_en"=>"Hranice","name_href" => "cz/population-of-hranice","count" => "18 933","real_id" =>66,),
"67"=>array("name_ru"=>"Бероун","name_en"=>"Beroun","name_href" => "cz/population-of-beroun","count" => "18 741","real_id" =>67,),
"68"=>array("name_ru"=>"Ло́уны","name_en"=>"Louny","name_href" => "cz/population-of-louny","count" => "18 680","real_id" =>68,),
"69"=>array("name_ru"=>"Отроковице","name_en"=>"Otrokovice","name_href" => "cz/population-of-otrokovice","count" => "18 524","real_id" =>69,),
"70"=>array("name_ru"=>"Кралупи-над-Влтавоу","name_en"=>"Kralupy nad Vltavou","name_href" => "cz/population-of-kralupy-nad-vltavou","count" => "18 453","real_id" =>70,),
"71"=>array("name_ru"=>"Кадань","name_en"=>"Kadaň","name_href" => "cz/population-of-kadaň","count" => "18 147","real_id" =>71,),
"72"=>array("name_ru"=>"Бра́ндис-над-Ла́бем-Ста́ра-Бо́леслав","name_en"=>"Brandýs nad Labem-Stará Boleslav","name_href" => "cz/population-of-brandýs-nad-labem-stará-boleslav","count" => "17 683","real_id" =>72,),
"73"=>array("name_ru"=>"Остров","name_en"=>"Ostrov","name_href" => "cz/population-of-ostrov","count" => "17 373","real_id" =>73,),
"74"=>array("name_ru"=>"Свитавы","name_en"=>"Svitavy","name_href" => "cz/population-of-svitavy","count" => "17 090","real_id" =>74,),
"75"=>array("name_ru"=>"Брунталь","name_en"=>"Bruntál","name_href" => "cz/population-of-bruntál","count" => "17 030","real_id" =>75,),
"76"=>array("name_ru"=>"У́герски-Брод","name_en"=>"Uherský Brod","name_href" => "cz/population-of-uherský-brod","count" => "16 956","real_id" =>76,),
"77"=>array("name_ru"=>"Рожнов-под-Радгоштем","name_en"=>"Rožnov pod Radhoštěm","name_href" => "cz/population-of-rožnov-pod-radhoštěm","count" => "16 942","real_id" =>77,),
"78"=>array("name_ru"=>"Йи́чин","name_en"=>"Jičín","name_href" => "cz/population-of-jičín","count" => "16 792","real_id" =>78,),
"79"=>array("name_ru"=>"Раковник","name_en"=>"Rakovník","name_href" => "cz/population-of-rakovník","count" => "16 731","real_id" =>79,),
"80"=>array("name_ru"=>"Нератовице","name_en"=>"Neratovice","name_href" => "cz/population-of-neratovice","count" => "16 662","real_id" =>80,),
"81"=>array("name_ru"=>"Бенешов","name_en"=>"Benešov","name_href" => "cz/population-of-benešov","count" => "16 484","real_id" =>81,),
"82"=>array("name_ru"=>"Пельгржимов","name_en"=>"Pelhřimov","name_href" => "cz/population-of-pelhřimov","count" => "16 339","real_id" =>82,),
"83"=>array("name_ru"=>"Двур-Кралове-над-Лабем","name_en"=>"Dvůr Králové nad Labem","name_href" => "cz/population-of-dvůr-králové-nad-labem","count" => "16 137","real_id" =>83,),
"84"=>array("name_ru"=>"Ческа-Тршебова","name_en"=>"Česká Třebová","name_href" => "cz/population-of-česká-třebová","count" => "16 069","real_id" =>84,),
"85"=>array("name_ru"=>"Билина","name_en"=>"Bílina","name_href" => "cz/population-of-bílina","count" => "15 901","real_id" =>85,),
"86"=>array("name_ru"=>"Ва́рнсдорф","name_en"=>"Varnsdorf","name_href" => "cz/population-of-varnsdorf","count" => "15 788","real_id" =>86,),
"87"=>array("name_ru"=>"Сла́ни","name_en"=>"Slaný","name_href" => "cz/population-of-slaný","count" => "15 306","real_id" =>87,),
"88"=>array("name_ru"=>"Клаштерец-над-Огржи","name_en"=>"Klášterec nad Ohří","name_href" => "cz/population-of-klášterec-nad-ohří","count" => "15 222","real_id" =>88,),
"89"=>array("name_ru"=>"Ма́рианске-Ла́зне","name_en"=>"Mariánské Lázně","name_href" => "cz/population-of-mariánské-lázně","count" => "15 105","real_id" =>89,),
"90"=>array("name_ru"=>"Нимбурк","name_en"=>"Nymburk","name_href" => "cz/population-of-nymburk","count" => "14 782","real_id" =>90,),
"91"=>array("name_ru"=>"Усти-над-Орлици","name_en"=>"Ústí nad Orlicí","name_href" => "cz/population-of-ústí-nad-orlicí","count" => "14 662","real_id" =>91,),
"92"=>array("name_ru"=>"Турнов","name_en"=>"Turnov","name_href" => "cz/population-of-turnov","count" => "14 395","real_id" =>92,),
"93"=>array("name_ru"=>"Ходов","name_en"=>"Chodov","name_href" => "cz/population-of-chodov","count" => "14 257","real_id" =>93,),
"94"=>array("name_ru"=>"Рокицаны","name_en"=>"Rokycany","name_href" => "cz/population-of-rokycany","count" => "14 173","real_id" =>94,),
"95"=>array("name_ru"=>"Глучи́н","name_en"=>"Hlučín","name_href" => "cz/population-of-hlučín","count" => "14 114","real_id" =>95,),
"96"=>array("name_ru"=>"Подебрады","name_en"=>"Poděbrady","name_href" => "cz/population-of-poděbrady","count" => "14 005","real_id" =>96,),
"97"=>array("name_ru"=>"Забрех","name_en"=>"Zábřeh","name_href" => "cz/population-of-zábřeh","count" => "13 990","real_id" =>97,),
"98"=>array("name_ru"=>"Штернберк","name_en"=>"Šternberk","name_href" => "cz/population-of-šternberk","count" => "13 677","real_id" =>98,),
"99"=>array("name_ru"=>"Крупка","name_en"=>"Krupka","name_href" => "cz/population-of-krupka","count" => "13 658","real_id" =>99,),
"100"=>array("name_ru"=>"Ржичани","name_en"=>"Říčany","name_href" => "cz/population-of-říčany","count" => "13 637","real_id" =>100,),
"101"=>array("name_ru"=>"Че́ски-Кру́млов","name_en"=>"Český Krumlov","name_href" => "cz/population-of-český-krumlov","count" => "13 557","real_id" =>101,),
"102"=>array("name_ru"=>"Рoуднице-над-Лабем","name_en"=>"Roudnice nad Labem","name_href" => "cz/population-of-roudnice-nad-labem","count" => "13 114","real_id" =>102,),
"103"=>array("name_ru"=>"Аш","name_en"=>"Aš","name_href" => "cz/population-of-aš","count" => "13 093","real_id" =>103,),
"104"=>array("name_ru"=>"Тахов","name_en"=>"Tachov","name_href" => "cz/population-of-tachov","count" => "12 801","real_id" =>104,),
"105"=>array("name_ru"=>"Врхлаби","name_en"=>"Vrchlabí","name_href" => "cz/population-of-vrchlabí","count" => "12 674","real_id" =>105,),
"106"=>array("name_ru"=>"Я́ромерж","name_en"=>"Jaroměř","name_href" => "cz/population-of-jaroměř","count" => "12 638","real_id" =>106,),
"107"=>array("name_ru"=>"Високе-Мито","name_en"=>"Vysoké Mýto","name_href" => "cz/population-of-vysoké-mýto","count" => "12 553","real_id" =>107,),
"108"=>array("name_ru"=>"Нови-Бор","name_en"=>"Nový Bor","name_href" => "cz/population-of-nový-bor","count" => "12 117","real_id" =>108,),
"109"=>array("name_ru"=>"Голешов","name_en"=>"Holešov","name_href" => "cz/population-of-holešov","count" => "11 951","real_id" =>109,),
"110"=>array("name_ru"=>"Влашим","name_en"=>"Vlašim","name_href" => "cz/population-of-vlašim","count" => "11 923","real_id" =>110,),
"111"=>array("name_ru"=>"Уницов","name_en"=>"Uničov","name_href" => "cz/population-of-uničov","count" => "11 891","real_id" =>111,),
"112"=>array("name_ru"=>"Есеник","name_en"=>"Jeseník","name_href" => "cz/population-of-jeseník","count" => "11 890","real_id" =>112,),
"113"=>array("name_ru"=>"Велики Мезиричи","name_en"=>"Veliki Mezirici","name_href" => "cz/population-of-veliki-mezirici","count" => "11 800","real_id" =>113,),
"114"=>array("name_ru"=>"Челаковице","name_en"=>"Čelákovice","name_href" => "cz/population-of-čelákovice","count" => "11 638","real_id" =>114,),
"115"=>array("name_ru"=>"Киёв","name_en"=>"Kyjov","name_href" => "cz/population-of-kyjov","count" => "11 599","real_id" =>115,),
"116"=>array("name_ru"=>"Весели-над-Моравою","name_en"=>"Veselí nad Moravou","name_href" => "cz/population-of-veselí-nad-moravou","count" => "11 598","real_id" =>116,),
"117"=>array("name_ru"=>"Босковице","name_en"=>"Boskovice","name_href" => "cz/population-of-boskovice","count" => "11 454","real_id" =>117,),
"118"=>array("name_ru"=>"Прахатице","name_en"=>"Prachatice","name_href" => "cz/population-of-prachatice","count" => "11 420","real_id" =>118,),
"119"=>array("name_ru"=>"Рихнов-над-Кнежноу","name_en"=>"Rychnov nad Kněžnou","name_href" => "cz/population-of-rychnov-nad-kněžnou","count" => "11 392","real_id" =>119,),
"120"=>array("name_ru"=>"Сушице","name_en"=>"Sušice","name_href" => "cz/population-of-sušice","count" => "11 331","real_id" =>120,),
"121"=>array("name_ru"=>"Румбурк","name_en"=>"Rumburk","name_href" => "cz/population-of-rumburk","count" => "11 250","real_id" =>121,),
"122"=>array("name_ru"=>"Домажлице","name_en"=>"Domažlice","name_href" => "cz/population-of-domažlice","count" => "11 055","real_id" =>122,),
"123"=>array("name_ru"=>"Френштат под Радхостем","name_en"=>"Frenštát pod Radhoštěm","name_href" => "cz/population-of-frenštát-pod-radhoštěm","count" => "11 040","real_id" =>123,),
"124"=>array("name_ru"=>"Гумполец","name_en"=>"Humpolec","name_href" => "cz/population-of-humpolec","count" => "10 945","real_id" =>124,),
"125"=>array("name_ru"=>"Курим","name_en"=>"Kuřim","name_href" => "cz/population-of-kuřim","count" => "10 804","real_id" =>125,),
"126"=>array("name_ru"=>"Моравска-Тршебова","name_en"=>"Moravská Třebová","name_href" => "cz/population-of-moravská-třebová","count" => "10 708","real_id" =>126,),
"127"=>array("name_ru"=>"Нове-Место-на-Мораве","name_en"=>"Nové Město na Moravě","name_href" => "cz/population-of-nové-město-na-moravě","count" => "10 277","real_id" =>127,),
"128"=>array("name_ru"=>"Ли́томишль","name_en"=>"Litomyšl","name_href" => "cz/population-of-litomyšl","count" => "10 233","real_id" =>128,),
"129"=>array("name_ru"=>"Ланшкроун","name_en"=>"Lanskron","name_href" => "cz/population-of-lanskron","count" => "10 133","real_id" =>129,),
"130"=>array("name_ru"=>"Часлав","name_en"=>"Čáslav","name_href" => "cz/population-of-čáslav","count" => "10 100","real_id" =>130,),
"131"=>array("name_ru"=>"Глинско","name_en"=>"Hlinsko","name_href" => "cz/population-of-hlinsko","count" => "10 072","real_id" =>131,),
"132"=>array("name_ru"=>"Студенка","name_en"=>"Studénka","name_href" => "cz/population-of-studénka","count" => "10 026","real_id" =>132,),
"133"=>array("name_ru"=>"Прага","name_en"=>"Praha","name_href" => "cz/population-of-praha","count" => "1 272 690","real_id" =>133,),
"134"=>array("name_ru"=>"Брно","name_en"=>"Brno","name_href" => "cz/population-of-brno","count" => "384 277","real_id" =>134,),
"135"=>array("name_ru"=>"Острава","name_en"=>"Ostrava","name_href" => "cz/population-of-ostrava","count" => "302 456","real_id" =>135,),
"136"=>array("name_ru"=>"Пльзень","name_en"=>"Pilsen","name_href" => "cz/population-of-pilsen","count" => "169 688","real_id" =>136,),
"137"=>array("name_ru"=>"Либерец","name_en"=>"Liberec","name_href" => "cz/population-of-liberec","count" => "102 247","real_id" =>137,)
);

?>