<?php
//Чили 48 
$libcl = array ( 
"1"=>array("name_ru"=>"Сантьяго","name_en"=>"Santiago","name_href" => "cl/population-of-santiago","count" => "5 279 190","real_id" =>1,),
"2"=>array("name_ru"=>"Пуэнте-Альто","name_en"=>"Puente Alto","name_href" => "cl/population-of-puente-alto","count" => "886 132","real_id" =>2,),
"3"=>array("name_ru"=>"Антофагаста","name_en"=>"Antofagasta","name_href" => "cl/population-of-antofagasta","count" => "369 855","real_id" =>3,),
"4"=>array("name_ru"=>"Сан-Бернардо","name_en"=>"San Bernardo","name_href" => "cl/population-of-san-bernardo","count" => "325 241","real_id" =>4,),
"5"=>array("name_ru"=>"Винья-дель-Мар","name_en"=>"Viña del Mar","name_href" => "cl/population-of-viña-del-mar","count" => "285 513","real_id" =>5,),
"6"=>array("name_ru"=>"Вальпараисо","name_en"=>"Valparaiso","name_href" => "cl/population-of-valparaiso","count" => "267 213","real_id" =>6,),
"7"=>array("name_ru"=>"Темуко","name_en"=>"Temuco","name_href" => "cl/population-of-temuco","count" => "257 556","real_id" =>7,),
"8"=>array("name_ru"=>"Ранкагуа","name_en"=>"Rancagua","name_href" => "cl/population-of-rancagua","count" => "252 819","real_id" =>8,),
"9"=>array("name_ru"=>"Икике","name_en"=>"Iquique","name_href" => "cl/population-of-iquique","count" => "245 299","real_id" =>9,),
"10"=>array("name_ru"=>"Талька","name_en"=>"Talca","name_href" => "cl/population-of-talca","count" => "236 774","real_id" =>10,),
"11"=>array("name_ru"=>"Пуэрто-Монт","name_en"=>"Puerto Montt","name_href" => "cl/population-of-puerto-montt","count" => "218 903","real_id" =>11,),
"12"=>array("name_ru"=>"Консепсьон","name_en"=>"Concepcion","name_href" => "cl/population-of-concepcion","count" => "210 718","real_id" =>12,),
"13"=>array("name_ru"=>"Ла-Серена","name_en"=>"La Serena","name_href" => "cl/population-of-la-serena","count" => "207 979","real_id" =>13,),
"14"=>array("name_ru"=>"Кокимбо","name_en"=>"Coquimbo","name_href" => "cl/population-of-coquimbo","count" => "206 944","real_id" =>14,),
"15"=>array("name_ru"=>"Арика","name_en"=>"Arica","name_href" => "cl/population-of-arica","count" => "197 009","real_id" =>15,),
"16"=>array("name_ru"=>"Кильпуэ","name_en"=>"quilpué","name_href" => "cl/population-of-quilpué","count" => "165 174","real_id" =>16,),
"17"=>array("name_ru"=>"Копьяпо","name_en"=>"Copiapo","name_href" => "cl/population-of-copiapo","count" => "164 773","real_id" =>17,),
"18"=>array("name_ru"=>"Осорно","name_en"=>"Osorno","name_href" => "cl/population-of-osorno","count" => "159 216","real_id" =>18,),
"19"=>array("name_ru"=>"Чильян","name_en"=>"Chillan","name_href" => "cl/population-of-chillan","count" => "157 122","real_id" =>19,),
"20"=>array("name_ru"=>"Лос-Анхелес","name_en"=>"Los Angeles","name_href" => "cl/population-of-los-angeles","count" => "154 152","real_id" =>20,),
"21"=>array("name_ru"=>"Калама","name_en"=>"Calama","name_href" => "cl/population-of-calama","count" => "154 092","real_id" =>21,),
"22"=>array("name_ru"=>"Вальдивия","name_en"=>"Valdivia","name_href" => "cl/population-of-valdivia","count" => "151 743","real_id" =>22,),
"23"=>array("name_ru"=>"Талькауано","name_en"=>"Talcahuano","name_href" => "cl/population-of-talcahuano","count" => "144 484","real_id" =>23,),
"24"=>array("name_ru"=>"Вилья-Алемана","name_en"=>"Villa Alemana","name_href" => "cl/population-of-villa-alemana","count" => "132 706","real_id" =>24,),
"25"=>array("name_ru"=>"Пунта-Аренас","name_en"=>"Punta Arenas","name_href" => "cl/population-of-punta-arenas","count" => "129 692","real_id" =>25,),
"26"=>array("name_ru"=>"Курико","name_en"=>"Curico","name_href" => "cl/population-of-curico","count" => "118 317","real_id" =>26,),
"27"=>array("name_ru"=>"Альто-Осписио","name_en"=>"Alto Hospicio","name_href" => "cl/population-of-alto-hospicio","count" => "114 840","real_id" =>27,),
"28"=>array("name_ru"=>"Коронель","name_en"=>"Coronel","name_href" => "cl/population-of-coronel","count" => "111 313","real_id" =>28,),
"29"=>array("name_ru"=>"Колина","name_en"=>"Colin","name_href" => "cl/population-of-colin","count" => "103 639","real_id" =>29,),
"30"=>array("name_ru"=>"Уальпен","name_en"=>"Hualpén","name_href" => "cl/population-of-hualpén","count" => "98 702","real_id" =>30,),
"31"=>array("name_ru"=>"Сан-Антонио","name_en"=>"San Antonio","name_href" => "cl/population-of-san-antonio","count" => "97 567","real_id" =>31,),
"32"=>array("name_ru"=>"Чигуаянте","name_en"=>"chiguayante","name_href" => "cl/population-of-chiguayante","count" => "93 314","real_id" =>32,),
"33"=>array("name_ru"=>"Сан-Педро-де-ла-Пас","name_en"=>"San Pedro de la Paz","name_href" => "cl/population-of-san-pedro-de-la-paz","count" => "92 075","real_id" =>33,),
"34"=>array("name_ru"=>"Пеньяфлор","name_en"=>"Peñaflor","name_href" => "cl/population-of-peñaflor","count" => "88 668","real_id" =>34,),
"35"=>array("name_ru"=>"Овалье","name_en"=>"Ovalle","name_href" => "cl/population-of-ovalle","count" => "85 729","real_id" =>35,),
"36"=>array("name_ru"=>"Кильота","name_en"=>"Quillota","name_href" => "cl/population-of-quillota","count" => "76 203","real_id" =>36,),
"37"=>array("name_ru"=>"Линарес","name_en"=>"Linares","name_href" => "cl/population-of-linares","count" => "75 232","real_id" =>37,),
"38"=>array("name_ru"=>"Лос-Андес","name_en"=>"Los Andes","name_href" => "cl/population-of-los-andes","count" => "72 337","real_id" =>38,),
"39"=>array("name_ru"=>"Талаганте","name_en"=>"Talagante","name_href" => "cl/population-of-talagante","count" => "69 639","real_id" =>39,),
"40"=>array("name_ru"=>"Сан-Фелипе","name_en"=>"San Felipe","name_href" => "cl/population-of-san-felipe","count" => "66 876","real_id" =>40,),
"41"=>array("name_ru"=>"Мелипилья","name_en"=>"Melipilla","name_href" => "cl/population-of-melipilla","count" => "65 186","real_id" =>41,),
"42"=>array("name_ru"=>"Сан-Фернандо","name_en"=>"San Fernando","name_href" => "cl/population-of-san-fernando","count" => "60 904","real_id" =>42,),
"43"=>array("name_ru"=>"Койайке","name_en"=>"Coihaique","name_href" => "cl/population-of-coihaique","count" => "57 050","real_id" =>43,),
"44"=>array("name_ru"=>"Пенко","name_en"=>"Penko","name_href" => "cl/population-of-penko","count" => "55 159","real_id" =>44,),
"45"=>array("name_ru"=>"Ла-Калера","name_en"=>"La Calera","name_href" => "cl/population-of-la-calera","count" => "54 663","real_id" =>45,),
"46"=>array("name_ru"=>"Анголь","name_en"=>"Angol","name_href" => "cl/population-of-angol","count" => "51 343","real_id" =>46,),
"47"=>array("name_ru"=>"Лота","name_en"=>"lot","name_href" => "cl/population-of-lot","count" => "51 049","real_id" =>47,),
"48"=>array("name_ru"=>"Буин","name_en"=>"Buin","name_href" => "cl/population-of-buin","count" => "50 691","real_id" =>48,),
"49"=>array("name_ru"=>"Сантьяго","name_en"=>"Santiago","name_href" => "cl/population-of-santiago","count" => "5 279 190","real_id" =>49,),
"50"=>array("name_ru"=>"Пуэнте-Альто","name_en"=>"Puente Alto","name_href" => "cl/population-of-puente-alto","count" => "886 132","real_id" =>50,),
"51"=>array("name_ru"=>"Антофагаста","name_en"=>"Antofagasta","name_href" => "cl/population-of-antofagasta","count" => "369 855","real_id" =>51,),
"52"=>array("name_ru"=>"Сан-Бернардо","name_en"=>"San Bernardo","name_href" => "cl/population-of-san-bernardo","count" => "325 241","real_id" =>52,),
"53"=>array("name_ru"=>"Винья-дель-Мар","name_en"=>"Viña del Mar","name_href" => "cl/population-of-viña-del-mar","count" => "285 513","real_id" =>53,)
);

?>