<?php
//Германия 100 
$libde = array ( 
"1"=>array("name_ru"=>"Берлин","name_en"=>"Berlin","name_href" => "de/population-of-berlin","count" => "3 326 002","real_id" =>1,),
"2"=>array("name_ru"=>"Гамбург","name_en"=>"Hamburg","name_href" => "de/population-of-hamburg","count" => "1 718 187","real_id" =>2,),
"3"=>array("name_ru"=>"Мюнхен","name_en"=>"Munich","name_href" => "de/population-of-munich","count" => "1 364 920","real_id" =>3,),
"4"=>array("name_ru"=>"Кёльн","name_en"=>"Cologne","name_href" => "de/population-of-cologne","count" => "1 013 665","real_id" =>4,),
"5"=>array("name_ru"=>"Франкфурт-на-Майне","name_en"=>"Frankfurt am main","name_href" => "de/population-of-frankfurt-am-main","count" => "676 533","real_id" =>5,),
"6"=>array("name_ru"=>"Штутгарт","name_en"=>"Stuttgart","name_href" => "de/population-of-stuttgart","count" => "591 015","real_id" =>6,),
"7"=>array("name_ru"=>"Дюссельдорф","name_en"=>"Dusseldorf","name_href" => "de/population-of-dusseldorf","count" => "589 649","real_id" =>7,),
"8"=>array("name_ru"=>"Дортмунд","name_en"=>"Dortmund","name_href" => "de/population-of-dortmund","count" => "571 403","real_id" =>8,),
"9"=>array("name_ru"=>"Эссен","name_en"=>"Essen","name_href" => "de/population-of-essen","count" => "565 900","real_id" =>9,),
"10"=>array("name_ru"=>"Бремен","name_en"=>"Bremen","name_href" => "de/population-of-bremen","count" => "544 043","real_id" =>10,),
"11"=>array("name_ru"=>"Дрезден","name_en"=>"Dresden","name_href" => "de/population-of-dresden","count" => "517 765","real_id" =>11,),
"12"=>array("name_ru"=>"Лейпциг","name_en"=>"Leipzig","name_href" => "de/population-of-leipzig","count" => "510 043","real_id" =>12,),
"13"=>array("name_ru"=>"Ганновер","name_en"=>"Hanover","name_href" => "de/population-of-hanover","count" => "509 485","real_id" =>13,),
"14"=>array("name_ru"=>"Нюрнберг","name_en"=>"Nuremberg","name_href" => "de/population-of-nuremberg","count" => "490 085","real_id" =>14,),
"15"=>array("name_ru"=>"Дуйсбург","name_en"=>"Duisburg","name_href" => "de/population-of-duisburg","count" => "487 470","real_id" =>15,),
"16"=>array("name_ru"=>"Бохум","name_en"=>"Bochum","name_href" => "de/population-of-bochum","count" => "362 585","real_id" =>16,),
"17"=>array("name_ru"=>"Вупперталь","name_en"=>"Wuppertal","name_href" => "de/population-of-wuppertal","count" => "342 570","real_id" =>17,),
"18"=>array("name_ru"=>"Билефельд","name_en"=>"Bielefeld","name_href" => "de/population-of-bielefeld","count" => "327 199","real_id" =>18,),
"19"=>array("name_ru"=>"Бонн","name_en"=>"Bonn","name_href" => "de/population-of-bonn","count" => "307 530","real_id" =>19,),
"20"=>array("name_ru"=>"Мюнстер","name_en"=>"Munster","name_href" => "de/population-of-munster","count" => "293 393","real_id" =>20,),
"21"=>array("name_ru"=>"Карлсруэ","name_en"=>"Karlsruhe","name_href" => "de/population-of-karlsruhe","count" => "291 995","real_id" =>21,),
"22"=>array("name_ru"=>"Маннгейм","name_en"=>"Mannheim","name_href" => "de/population-of-mannheim","count" => "291 458","real_id" =>22,),
"23"=>array("name_ru"=>"Висбаден","name_en"=>"Wiesbaden","name_href" => "de/population-of-wiesbaden","count" => "270 952","real_id" =>23,),
"24"=>array("name_ru"=>"Аугсбург","name_en"=>"Augsburg","name_href" => "de/population-of-augsburg","count" => "269 402","real_id" =>24,),
"25"=>array("name_ru"=>"Гельзенкирхен","name_en"=>"Gelsenkirchen","name_href" => "de/population-of-gelsenkirchen","count" => "257 994","real_id" =>25,),
"26"=>array("name_ru"=>"Мёнхенгладбах","name_en"=>"Monchengladbach","name_href" => "de/population-of-monchengladbach","count" => "254 834","real_id" =>26,),
"27"=>array("name_ru"=>"Брауншвейг","name_en"=>"Braunschweig","name_href" => "de/population-of-braunschweig","count" => "243 829","real_id" =>27,),
"28"=>array("name_ru"=>"Хемниц","name_en"=>"Chemnitz","name_href" => "de/population-of-chemnitz","count" => "240 543","real_id" =>28,),
"29"=>array("name_ru"=>"Ахен","name_en"=>"Aachen","name_href" => "de/population-of-aachen","count" => "238 665","real_id" =>29,),
"30"=>array("name_ru"=>"Киль","name_en"=>"Kiel","name_href" => "de/population-of-kiel","count" => "237 667","real_id" =>30,),
"31"=>array("name_ru"=>"Галле","name_en"=>"Galle","name_href" => "de/population-of-galle","count" => "230 494","real_id" =>31,),
"32"=>array("name_ru"=>"Магдебург","name_en"=>"Magdeburg","name_href" => "de/population-of-magdeburg","count" => "228 910","real_id" =>32,),
"33"=>array("name_ru"=>"Крефельд","name_en"=>"Krefeld","name_href" => "de/population-of-krefeld","count" => "221 864","real_id" =>33,),
"34"=>array("name_ru"=>"Фрайбург-в-Брайсгау","name_en"=>"Freiburg im Breisgau","name_href" => "de/population-of-freiburg-im-breisgau","count" => "214 234","real_id" =>34,),
"35"=>array("name_ru"=>"Любек","name_en"=>"Lubeck","name_href" => "de/population-of-lubeck","count" => "210 679","real_id" =>35,),
"36"=>array("name_ru"=>"Оберхаузен","name_en"=>"Oberhausen","name_href" => "de/population-of-oberhausen","count" => "210 256","real_id" =>36,),
"37"=>array("name_ru"=>"Эрфурт","name_en"=>"Erfurt","name_href" => "de/population-of-erfurt","count" => "201 952","real_id" =>37,),
"38"=>array("name_ru"=>"Росток","name_en"=>"Rostock","name_href" => "de/population-of-rostock","count" => "201 813","real_id" =>38,),
"39"=>array("name_ru"=>"Майнц","name_en"=>"Mainz","name_href" => "de/population-of-mainz","count" => "201 002","real_id" =>39,),
"40"=>array("name_ru"=>"Кассель","name_en"=>"Kassel","name_href" => "de/population-of-kassel","count" => "191 854","real_id" =>40,),
"41"=>array("name_ru"=>"Хаген","name_en"=>"Hagen","name_href" => "de/population-of-hagen","count" => "187 333","real_id" =>41,),
"42"=>array("name_ru"=>"Саарбрюккен","name_en"=>"Saarbrucken","name_href" => "de/population-of-saarbrucken","count" => "176 497","real_id" =>42,),
"43"=>array("name_ru"=>"Хамм","name_en"=>"Hamm","name_href" => "de/population-of-hamm","count" => "176 474","real_id" =>43,),
"44"=>array("name_ru"=>"Мюльхайм-на-Руре","name_en"=>"Mulheim-on-Ruhr","name_href" => "de/population-of-mulheim-on-ruhr","count" => "166 804","real_id" =>44,),
"45"=>array("name_ru"=>"Леверкузен","name_en"=>"Leverkusen","name_href" => "de/population-of-leverkusen","count" => "159 373","real_id" =>45,),
"46"=>array("name_ru"=>"Людвигсхафен-на-Рейне","name_en"=>"Ludwigshafen am Rhein","name_href" => "de/population-of-ludwigshafen-am-rhein","count" => "158 637","real_id" =>46,),
"47"=>array("name_ru"=>"Ольденбург","name_en"=>"Oldenburg","name_href" => "de/population-of-oldenburg","count" => "157 706","real_id" =>47,),
"48"=>array("name_ru"=>"Потсдам","name_en"=>"Potsdam","name_href" => "de/population-of-potsdam","count" => "157 603","real_id" =>48,),
"49"=>array("name_ru"=>"Золинген","name_en"=>"Solingen","name_href" => "de/population-of-solingen","count" => "155 080","real_id" =>49,),
"50"=>array("name_ru"=>"Херне","name_en"=>"Shit","name_href" => "de/population-of-shit","count" => "154 887","real_id" =>50,),
"51"=>array("name_ru"=>"Оснабрюк","name_en"=>"Osnabrück","name_href" => "de/population-of-osnabrück","count" => "154 513","real_id" =>51,),
"52"=>array("name_ru"=>"Нойс","name_en"=>"Neuss","name_href" => "de/population-of-neuss","count" => "151 070","real_id" =>52,),
"53"=>array("name_ru"=>"Гейдельберг","name_en"=>"Heidelberg","name_href" => "de/population-of-heidelberg","count" => "148 415","real_id" =>53,),
"54"=>array("name_ru"=>"Дармштадт","name_en"=>"Darmstadt","name_href" => "de/population-of-darmstadt","count" => "145 845","real_id" =>54,),
"55"=>array("name_ru"=>"Падерборн","name_en"=>"Paderborn","name_href" => "de/population-of-paderborn","count" => "143 174","real_id" =>55,),
"56"=>array("name_ru"=>"Регенсбург","name_en"=>"Regensburg","name_href" => "de/population-of-regensburg","count" => "136 352","real_id" =>56,),
"57"=>array("name_ru"=>"Ингольштадт","name_en"=>"Ingolstadt","name_href" => "de/population-of-ingolstadt","count" => "126 076","real_id" =>57,),
"58"=>array("name_ru"=>"Вюрцбург","name_en"=>"Würzburg","name_href" => "de/population-of-würzburg","count" => "124 449","real_id" =>58,),
"59"=>array("name_ru"=>"Вольфсбург","name_en"=>"Wolfsburg","name_href" => "de/population-of-wolfsburg","count" => "120 889","real_id" =>59,),
"60"=>array("name_ru"=>"Ульм","name_en"=>"Ulm","name_href" => "de/population-of-ulm","count" => "117 541","real_id" =>60,),
"61"=>array("name_ru"=>"Ботроп","name_en"=>"Bottrop","name_href" => "de/population-of-bottrop","count" => "117 074","real_id" =>61,),
"62"=>array("name_ru"=>"Хайльбронн","name_en"=>"Heilbronn","name_href" => "de/population-of-heilbronn","count" => "116 716","real_id" =>62,),
"63"=>array("name_ru"=>"Фюрт","name_en"=>"Furth","name_href" => "de/population-of-furth","count" => "116 640","real_id" =>63,),
"64"=>array("name_ru"=>"Гёттинген","name_en"=>"Göttingen","name_href" => "de/population-of-göttingen","count" => "116 052","real_id" =>64,),
"65"=>array("name_ru"=>"Реклингхаузен","name_en"=>"Recklinghausen","name_href" => "de/population-of-recklinghausen","count" => "115 648","real_id" =>65,),
"66"=>array("name_ru"=>"Пфорцхайм","name_en"=>"Pforzheim","name_href" => "de/population-of-pforzheim","count" => "115 211","real_id" =>66,),
"67"=>array("name_ru"=>"Оффенбах","name_en"=>"Offenbach","name_href" => "de/population-of-offenbach","count" => "114 855","real_id" =>67,),
"68"=>array("name_ru"=>"Ремшайд","name_en"=>"Remscheid","name_href" => "de/population-of-remscheid","count" => "110 132","real_id" =>68,),
"69"=>array("name_ru"=>"Ройтлинген","name_en"=>"Reutlingen","name_href" => "de/population-of-reutlingen","count" => "110 084","real_id" =>69,),
"70"=>array("name_ru"=>"Бергиш-Гладбах","name_en"=>"Bergisch Gladbach","name_href" => "de/population-of-bergisch-gladbach","count" => "109 026","real_id" =>70,),
"71"=>array("name_ru"=>"Бремерхафен","name_en"=>"Bremerhaven","name_href" => "de/population-of-bremerhaven","count" => "108 139","real_id" =>71,),
"72"=>array("name_ru"=>"Кобленц","name_en"=>"Koblenz","name_href" => "de/population-of-koblenz","count" => "107 954","real_id" =>72,),
"73"=>array("name_ru"=>"Йена","name_en"=>"Ian","name_href" => "de/population-of-ian","count" => "106 428","real_id" =>73,),
"74"=>array("name_ru"=>"Трир","name_en"=>"Trier","name_href" => "de/population-of-trier","count" => "106 284","real_id" =>74,),
"75"=>array("name_ru"=>"Эрланген","name_en"=>"Erlangen","name_href" => "de/population-of-erlangen","count" => "104 312","real_id" =>75,),
"76"=>array("name_ru"=>"Мёрс","name_en"=>"Mercedes","name_href" => "de/population-of-mercedes","count" => "103 831","real_id" =>76,),
"77"=>array("name_ru"=>"Котбус","name_en"=>"Cottbus","name_href" => "de/population-of-cottbus","count" => "99 974","real_id" =>77,),
"78"=>array("name_ru"=>"Хильдесхайм","name_en"=>"Hildesheim","name_href" => "de/population-of-hildesheim","count" => "99 267","real_id" =>78,),
"79"=>array("name_ru"=>"Зиген","name_en"=>"Siegen","name_href" => "de/population-of-siegen","count" => "99 230","real_id" =>79,),
"80"=>array("name_ru"=>"Зальцгиттер","name_en"=>"Salzgitter","name_href" => "de/population-of-salzgitter","count" => "98 588","real_id" =>80,),
"81"=>array("name_ru"=>"Кайзерслаутерн","name_en"=>"Kaiserslautern","name_href" => "de/population-of-kaiserslautern","count" => "96 963","real_id" =>81,),
"82"=>array("name_ru"=>"Виттен","name_en"=>"Witten","name_href" => "de/population-of-witten","count" => "96 221","real_id" =>82,),
"83"=>array("name_ru"=>"Гера","name_en"=>"Gera","name_href" => "de/population-of-gera","count" => "95 746","real_id" =>83,),
"84"=>array("name_ru"=>"Изерлон","name_en"=>"Iserlohn","name_href" => "de/population-of-iserlohn","count" => "94 367","real_id" =>84,),
"85"=>array("name_ru"=>"Гютерсло","name_en"=>"Gütersloh","name_href" => "de/population-of-gütersloh","count" => "94 290","real_id" =>85,),
"86"=>array("name_ru"=>"Цвикау","name_en"=>"Zwickau","name_href" => "de/population-of-zwickau","count" => "92 826","real_id" =>86,),
"87"=>array("name_ru"=>"Шверин","name_en"=>"Schwerin","name_href" => "de/population-of-schwerin","count" => "91 327","real_id" =>87,),
"88"=>array("name_ru"=>"Дюрен","name_en"=>"Duren","name_href" => "de/population-of-duren","count" => "88 567","real_id" =>88,),
"89"=>array("name_ru"=>"Ханау","name_en"=>"Hanau","name_href" => "de/population-of-hanau","count" => "87 521","real_id" =>89,),
"90"=>array("name_ru"=>"Эсслинген-на-Неккаре","name_en"=>"Esslingen am Neckar","name_href" => "de/population-of-esslingen-am-neckar","count" => "87 519","real_id" =>90,),
"91"=>array("name_ru"=>"Людвигсбург","name_en"=>"Ludwigsburg","name_href" => "de/population-of-ludwigsburg","count" => "86 939","real_id" =>91,),
"92"=>array("name_ru"=>"Ратинген","name_en"=>"Ratingen","name_href" => "de/population-of-ratingen","count" => "86 882","real_id" =>92,),
"93"=>array("name_ru"=>"Люнен","name_en"=>"Lünen","name_href" => "de/population-of-lünen","count" => "85 554","real_id" =>93,),
"94"=>array("name_ru"=>"Дессау","name_en"=>"Dessau","name_href" => "de/population-of-dessau","count" => "85 488","real_id" =>94,),
"95"=>array("name_ru"=>"Марль","name_en"=>"Marl","name_href" => "de/population-of-marl","count" => "84 680","real_id" =>95,),
"96"=>array("name_ru"=>"Тюбинген","name_en"=>"Tübingen","name_href" => "de/population-of-tübingen","count" => "83 248","real_id" =>96,),
"97"=>array("name_ru"=>"Фленсбург","name_en"=>"Flensburg","name_href" => "de/population-of-flensburg","count" => "82 801","real_id" =>97,),
"98"=>array("name_ru"=>"Фельберт","name_en"=>"Velbert","name_href" => "de/population-of-velbert","count" => "81 192","real_id" =>98,),
"99"=>array("name_ru"=>"Филлинген-Швеннинген","name_en"=>"Villingen-Schwenningen","name_href" => "de/population-of-villingen-schwenningen","count" => "80 268","real_id" =>99,),
"100"=>array("name_ru"=>"Минден","name_en"=>"Minden","name_href" => "de/population-of-minden","count" => "79 940","real_id" =>100,),
"101"=>array("name_ru"=>"Берлин","name_en"=>"Berlin","name_href" => "de/population-of-berlin","count" => "3 326 002","real_id" =>101,),
"102"=>array("name_ru"=>"Гамбург","name_en"=>"Hamburg","name_href" => "de/population-of-hamburg","count" => "1 718 187","real_id" =>102,),
"103"=>array("name_ru"=>"Мюнхен","name_en"=>"Munich","name_href" => "de/population-of-munich","count" => "1 364 920","real_id" =>103,),
"104"=>array("name_ru"=>"Кёльн","name_en"=>"Cologne","name_href" => "de/population-of-cologne","count" => "1 013 665","real_id" =>104,),
"105"=>array("name_ru"=>"Франкфурт-на-Майне","name_en"=>"Frankfurt am main","name_href" => "de/population-of-frankfurt-am-main","count" => "676 533","real_id" =>105,)
);

?>