<?php
//Алжир 50
$libdz = array ( 
"1"=>array("name_ru"=>"Алжир","name_en"=>"Algiers","name_href" => "dz/population-of-algiers-city","count" => "3 335 418","real_id" =>1,),
"2"=>array("name_ru"=>"Оран","name_en"=>"Oran","name_href" => "dz/population-of-oran","count" => "641 240","real_id" =>2,),
"3"=>array("name_ru"=>"Константина","name_en"=>"Constantine","name_href" => "dz/population-of-constantine","count" => "465 138","real_id" =>3,),
"4"=>array("name_ru"=>"Джельфа","name_en"=>"Djelfa","name_href" => "dz/population-of-djelfa","count" => "373 547","real_id" =>4,),
"5"=>array("name_ru"=>"Батна","name_en"=>"Batna","name_href" => "dz/population-of-batna","count" => "324 897","real_id" =>5,),
"6"=>array("name_ru"=>"Сетиф","name_en"=>"Sétif","name_href" => "dz/population-of-sétif","count" => "324 502","real_id" =>6,),
"7"=>array("name_ru"=>"Аннаба","name_en"=>"Annaba","name_href" => "dz/population-of-annaba","count" => "272 807","real_id" =>7,),
"8"=>array("name_ru"=>"Сиди-Бель-Аббес","name_en"=>"Sidi Bel Abbès","name_href" => "dz/population-of-sidi-bel-abbès","count" => "233 771","real_id" =>8,),
"9"=>array("name_ru"=>"Эль-Хруб","name_en"=>"El Khroub","name_href" => "dz/population-of-el-khroub","count" => "232 636","real_id" =>9,),
"10"=>array("name_ru"=>"Тиарет","name_en"=>"Tiaret","name_href" => "dz/population-of-tiaret","count" => "229 376","real_id" =>10,),
"11"=>array("name_ru"=>"Бискра","name_en"=>"Biskra","name_href" => "dz/population-of-biskra","count" => "228 869","real_id" =>11,),
"12"=>array("name_ru"=>"Тебесса","name_en"=>"Tébessa","name_href" => "dz/population-of-tébessa","count" => "222 824","real_id" =>12,),
"13"=>array("name_ru"=>"Шлеф","name_en"=>"Chlef","name_href" => "dz/population-of-chlef","count" => "203 329","real_id" =>13,),
"14"=>array("name_ru"=>"Бир-эль-Джир","name_en"=>"Bir El Djir","name_href" => "dz/population-of-bir-el-djir","count" => "203 092","real_id" =>14,),
"15"=>array("name_ru"=>"Беджая","name_en"=>"Béjaïa","name_href" => "dz/population-of-béjaïa","count" => "198 312","real_id" =>15,),
"16"=>array("name_ru"=>"Бордж-Бу-Арреридж","name_en"=>"Bordj Bou Arréridj","name_href" => "dz/population-of-bordj-bou-arréridj","count" => "193 153","real_id" =>16,),
"17"=>array("name_ru"=>"Бешар","name_en"=>"Béchar","name_href" => "dz/population-of-béchar","count" => "186 547","real_id" =>17,),
"18"=>array("name_ru"=>"Мсила","name_en"=>"M'Sila","name_href" => "dz/population-of-msila","count" => "181 511","real_id" =>18,),
"19"=>array("name_ru"=>"Сук-Ахрас","name_en"=>"Souk Ahras","name_href" => "dz/population-of-souk-ahras","count" => "180 572","real_id" =>19,),
"20"=>array("name_ru"=>"Эль-Эулма","name_en"=>"El Eulma","name_href" => "dz/population-of-el-eulma","count" => "180 303","real_id" =>20,),
"21"=>array("name_ru"=>"Блида","name_en"=>"Blida","name_href" => "dz/population-of-blida","count" => "178 986","real_id" =>21,),
"22"=>array("name_ru"=>"Скикда","name_en"=>"Skikda","name_href" => "dz/population-of-skikda","count" => "174 554","real_id" =>22,),
"23"=>array("name_ru"=>"Лагуат","name_en"=>"Laghouat","name_href" => "dz/population-of-laghouat","count" => "170 693","real_id" =>23,),
"24"=>array("name_ru"=>"Мостаганем","name_en"=>"Mostaganem","name_href" => "dz/population-of-mostaganem","count" => "158 443","real_id" =>24,),
"25"=>array("name_ru"=>"Эль-Уэд","name_en"=>"El Oued","name_href" => "dz/population-of-el-oued","count" => "155 433","real_id" =>25,),
"26"=>array("name_ru"=>"Медеа","name_en"=>"Médéa","name_href" => "dz/population-of-médéa","count" => "152 658","real_id" =>26,),
"27"=>array("name_ru"=>"Джиджель","name_en"=>"Jijel","name_href" => "dz/population-of-jijel","count" => "152 281","real_id" =>27,),
"28"=>array("name_ru"=>"Тлемсен","name_en"=>"Tlemcen","name_href" => "dz/population-of-tlemcen","count" => "150 335","real_id" =>28,),
"29"=>array("name_ru"=>"Уаргла","name_en"=>"Ouargla","name_href" => "dz/population-of-ouargla","count" => "149 795","real_id" =>29,),
"30"=>array("name_ru"=>"Тизи-Узу","name_en"=>"Tizi Ouzou","name_href" => "dz/population-of-tizi-ouzou","count" => "149 542","real_id" =>30,),
"31"=>array("name_ru"=>"Релизан","name_en"=>"Relizane","name_href" => "dz/population-of-relizane","count" => "145 131","real_id" =>31,),
"32"=>array("name_ru"=>"Бу-Саада","name_en"=>"Bou Saâda","name_href" => "dz/population-of-bou-saâda","count" => "142 545","real_id" =>32,),
"33"=>array("name_ru"=>"Саида","name_en"=>"Saïda","name_href" => "dz/population-of-saïda","count" => "141 020","real_id" =>33,),
"34"=>array("name_ru"=>"Сиди-Шами","name_en"=>"Sidi Chami","name_href" => "dz/population-of-sidi-chami","count" => "138 671","real_id" =>34,),
"35"=>array("name_ru"=>"Эль-Буни","name_en"=>"El Bouni","name_href" => "dz/population-of-el-bouni","count" => "137 730","real_id" =>35,),
"36"=>array("name_ru"=>"Айн-Бейда","name_en"=>"Aïn Beïda","name_href" => "dz/population-of-aïn-beïda","count" => "136 756","real_id" =>36,),
"37"=>array("name_ru"=>"Афлу","name_en"=>"Aflou","name_href" => "dz/population-of-aflou","count" => "135 379","real_id" =>37,),
"38"=>array("name_ru"=>"Гельма","name_en"=>"Guelma","name_href" => "dz/population-of-guelma","count" => "131 606","real_id" =>38,),
"39"=>array("name_ru"=>"Магния","name_en"=>"Maghnia","name_href" => "dz/population-of-maghnia","count" => "129 396","real_id" =>39,),
"40"=>array("name_ru"=>"Маскара","name_en"=>"Mascara","name_href" => "dz/population-of-mascara","count" => "123 162","real_id" =>40,),
"41"=>array("name_ru"=>"Хеншела","name_en"=>"Khenchela","name_href" => "dz/population-of-khenchela","count" => "123 113","real_id" =>41,),
"42"=>array("name_ru"=>"Мессад","name_en"=>"Messaâd","name_href" => "dz/population-of-messaad","count" => "120 584","real_id" =>42,),
"43"=>array("name_ru"=>"Эс-Сения","name_en"=>"Es Sénia","name_href" => "dz/population-of-es-sénia","count" => "119 876","real_id" =>43,),
"44"=>array("name_ru"=>"Барика","name_en"=>"Barika","name_href" => "dz/population-of-barika","count" => "118 610","real_id" =>44,),
"45"=>array("name_ru"=>"Айн-Уссера","name_en"=>"Aïn Oussera","name_href" => "dz/population-of-aïn-oussera","count" => "116 961","real_id" =>45,),
"46"=>array("name_ru"=>"Улед-Яиш","name_en"=>"Ouled Yaïch","name_href" => "dz/population-of-ouled-yaïch","count" => "109 180","real_id" =>46,),
"47"=>array("name_ru"=>"Таманрассет","name_en"=>"Tamanrasset","name_href" => "dz/population-of-tamanrasset","count" => "108 289","real_id" =>47,),
"48"=>array("name_ru"=>"Эль-Баяд","name_en"=>"El Bayadh","name_href" => "dz/population-of-el-bayadh","count" => "107 987","real_id" =>48,),
"49"=>array("name_ru"=>"Хасси-Бахбах","name_en"=>"Hassi Bahbah","name_href" => "dz/population-of-hassi-bahbah","count" => "104 168","real_id" =>49,),
"50"=>array("name_ru"=>"Айн-Млила","name_en"=>"Aïn M'lila","name_href" => "dz/population-of-aïn-mlila","count" => "102 738","real_id" =>50,),
"51"=>array("name_ru"=>"Алжир","name_en"=>"Algiers","name_href" => "dz/population-of-algiers-city","count" => "3 335 418","real_id" =>51,),
"52"=>array("name_ru"=>"Оран","name_en"=>"Oran","name_href" => "dz/population-of-oran","count" => "641 240","real_id" =>52,),
"53"=>array("name_ru"=>"Константина","name_en"=>"Constantine","name_href" => "dz/population-of-constantine","count" => "465 138","real_id" =>53,),
"54"=>array("name_ru"=>"Джельфа","name_en"=>"Djelfa","name_href" => "dz/population-of-djelfa","count" => "373 547","real_id" =>54,),
"55"=>array("name_ru"=>"Батна","name_en"=>"Batna","name_href" => "dz/population-of-batna","count" => "324 897","real_id" =>55,)
);

?>