<?php
//Доминиканская республика 34 
$libdo = array ( 
"1"=>array("name_ru"=>"Санто-Доминго","name_en"=>"Santo Domingo","name_href" => "do/population-of-santo-domingo","count" => "3 339 410","real_id" =>1,),
"2"=>array("name_ru"=>"Сантьяго-де-лос-Трейнта-Кабальерос","name_en"=>"Santiago de Los Treinta Caballeros","name_href" => "do/population-of-santiago-de-los-treinta-caballeros","count" => "691 262","real_id" =>2,),
"3"=>array("name_ru"=>"Лос-Алькаррисос","name_en"=>"Los Alcarrizos","name_href" => "do/population-of-los-alcarrizos","count" => "272 766","real_id" =>3,),
"4"=>array("name_ru"=>"Игуэй","name_en"=>"Higuey","name_href" => "do/population-of-higuey","count" => "251 243","real_id" =>4,),
"5"=>array("name_ru"=>"Консепсион-де-ла-Вега","name_en"=>"Concepcion de La VEGA","name_href" => "do/population-of-concepcion-de-la-vega","count" => "248 089","real_id" =>5,),
"6"=>array("name_ru"=>"Сан-Кристобаль","name_en"=>"San Cristobal","name_href" => "do/population-of-san-cristobal","count" => "232 769","real_id" =>6,),
"7"=>array("name_ru"=>"Сан-Педро-де-Макорис","name_en"=>"San Pedro de Macoris","name_href" => "do/population-of-san-pedro-de-macoris","count" => "195 307","real_id" =>7,),
"8"=>array("name_ru"=>"Сан-Франсиско-де-Макорис","name_en"=>"San Francisco de Macoris","name_href" => "do/population-of-san-francisco-de-macoris","count" => "188 118","real_id" =>8,),
"9"=>array("name_ru"=>"Мока","name_en"=>"Moka","name_href" => "do/population-of-moka","count" => "179 829","real_id" =>9,),
"10"=>array("name_ru"=>"Сан-Фелипе-де-Пуэрто-Плата","name_en"=>"San Felipe de Puerto Plata","name_href" => "do/population-of-san-felipe-de-puerto-plata","count" => "158 756","real_id" =>10,),
"11"=>array("name_ru"=>"Бани","name_en"=>"Baths","name_href" => "do/population-of-baths","count" => "157 316","real_id" =>11,),
"12"=>array("name_ru"=>"Бока-Чика","name_en"=>"Boca Chica","name_href" => "do/population-of-boca-chica","count" => "142 019","real_id" =>12,),
"13"=>array("name_ru"=>"Ла-Романа","name_en"=>"La Romana","name_href" => "do/population-of-la-romana","count" => "139 671","real_id" =>13,),
"14"=>array("name_ru"=>"Сан-Хуан-де-ла-Магуана","name_en"=>"San Juan de La Maguana","name_href" => "do/population-of-san-juan-de-la-maguana","count" => "132 177","real_id" =>14,),
"15"=>array("name_ru"=>"Бонао","name_en"=>"Bonao","name_href" => "do/population-of-bonao","count" => "125 338","real_id" =>15,),
"16"=>array("name_ru"=>"Бахос-де-Айна","name_en"=>"Bajos de ain","name_href" => "do/population-of-bajos-de-ain","count" => "124 193","real_id" =>16,),
"17"=>array("name_ru"=>"Асуа-де-Компостела","name_en"=>"Azua de Compostela","name_href" => "do/population-of-azua-de-compostela","count" => "91 345","real_id" =>17,),
"18"=>array("name_ru"=>"Вилья-Альтаграсия","name_en"=>"Villa Altagracia","name_href" => "do/population-of-villa-altagracia","count" => "84 312","real_id" =>18,),
"19"=>array("name_ru"=>"Санта-Крус-де-Бараона","name_en"=>"Santa Cruz de Barahona","name_href" => "do/population-of-santa-cruz-de-barahona","count" => "83 619","real_id" =>19,),
"20"=>array("name_ru"=>"Нагуа","name_en"=>"Nagua","name_href" => "do/population-of-nagua","count" => "76 993","real_id" =>20,),
"21"=>array("name_ru"=>"Санта-Крус-де-Мао","name_en"=>"Santa Cruz de Mao","name_href" => "do/population-of-santa-cruz-de-mao","count" => "76 863","real_id" =>21,),
"22"=>array("name_ru"=>"Котуи","name_en"=>"Cotui","name_href" => "do/population-of-cotui","count" => "76 554","real_id" =>22,),
"23"=>array("name_ru"=>"Педро-Бранд","name_en"=>"Pedro Brand","name_href" => "do/population-of-pedro-brand","count" => "74 016","real_id" =>23,),
"24"=>array("name_ru"=>"Санта-Круз-дель-Сейбо","name_en"=>"Santa Cruz del Seibo","name_href" => "do/population-of-santa-cruz-del-seibo","count" => "66 867","real_id" =>24,),
"25"=>array("name_ru"=>"Эсперанса","name_en"=>"Esperanza","name_href" => "do/population-of-esperanza","count" => "62 205","real_id" =>25,),
"26"=>array("name_ru"=>"Ато-Майор-дель-Реи","name_en"=>"Hato Mayor del Rei","name_href" => "do/population-of-hato-mayor-del-rei","count" => "61 517","real_id" =>26,),
"27"=>array("name_ru"=>"Констанса","name_en"=>"Constance","name_href" => "do/population-of-constance","count" => "59 052","real_id" =>27,),
"28"=>array("name_ru"=>"Харабакоа","name_en"=>"Jarabacoa","name_href" => "do/population-of-jarabacoa","count" => "56 803","real_id" =>28,),
"29"=>array("name_ru"=>"Тамборил","name_en"=>"Tamboril","name_href" => "do/population-of-tamboril","count" => "51 695","real_id" =>29,),
"30"=>array("name_ru"=>"Лас-Матас-де-Фарфан","name_en"=>"Las Matas de Farfan","name_href" => "do/population-of-las-matas-de-farfan","count" => "44 163","real_id" =>30,),
"31"=>array("name_ru"=>"Вилья-Бисоно","name_en"=>"Villa Bisono","name_href" => "do/population-of-villa-bisono","count" => "42 092","real_id" =>31,),
"32"=>array("name_ru"=>"Сан-Хосе-де-Окоа","name_en"=>"San-Jose-de-Ocoa","name_href" => "do/population-of-san-jose-de-ocoa","count" => "39 451","real_id" =>32,),
"33"=>array("name_ru"=>"Баягуана","name_en"=>"Bayaguana","name_href" => "do/population-of-bayaguana","count" => "31 889","real_id" =>33,),
"34"=>array("name_ru"=>"Консуэло","name_en"=>"Consuelo","name_href" => "do/population-of-consuelo","count" => "30 051","real_id" =>34,),
"35"=>array("name_ru"=>"Санто-Доминго","name_en"=>"Santo Domingo","name_href" => "do/population-of-santo-domingo","count" => "3 339 410","real_id" =>35,),
"36"=>array("name_ru"=>"Сантьяго-де-лос-Трейнта-Кабальерос","name_en"=>"Santiago de Los Treinta Caballeros","name_href" => "do/population-of-santiago-de-los-treinta-caballeros","count" => "691 262","real_id" =>36,),
"37"=>array("name_ru"=>"Лос-Алькаррисос","name_en"=>"Los Alcarrizos","name_href" => "do/population-of-los-alcarrizos","count" => "272 766","real_id" =>37,),
"38"=>array("name_ru"=>"Игуэй","name_en"=>"Higuey","name_href" => "do/population-of-higuey","count" => "251 243","real_id" =>38,),
"39"=>array("name_ru"=>"Консепсион-де-ла-Вега","name_en"=>"Concepcion de La VEGA","name_href" => "do/population-of-concepcion-de-la-vega","count" => "248 089","real_id" =>39,)
);

?>