<?php
//Дания 56 
$libdk = array ( 
"1"=>array("name_ru"=>"Копенгаген ","name_en"=>"Copenhagen ","name_href" => "dk/population-of-copenhagen","count" => "1 246 611","real_id" =>1,),
"2"=>array("name_ru"=>"Орхус ","name_en"=>"Aarhus ","name_href" => "dk/population-of-aarhus","count" => "259 754","real_id" =>2,),
"3"=>array("name_ru"=>"Оденсе ","name_en"=>"Odense ","name_href" => "dk/population-of-odense","count" => "172 512","real_id" =>3,),
"4"=>array("name_ru"=>"Ольборг ","name_en"=>"Aalborg ","name_href" => "dk/population-of-aalborg","count" => "109 092","real_id" =>4,),
"5"=>array("name_ru"=>"Фредериксберг ","name_en"=>"FREDERICKSBURG ","name_href" => "dk/population-of-fredericksburg","count" => "95 029","real_id" =>5,),
"6"=>array("name_ru"=>"Эсбьерг ","name_en"=>"Esbjerg ","name_href" => "dk/population-of-esbjerg","count" => "71 618","real_id" =>6,),
"7"=>array("name_ru"=>"Раннерс","name_en"=>"Randers","name_href" => "dk/population-of-randers","count" => "61 163","real_id" =>7,),
"8"=>array("name_ru"=>"Хельсингёр ","name_en"=>"Helsingor ","name_href" => "dk/population-of-helsingor","count" => "60 927","real_id" =>8,),
"9"=>array("name_ru"=>"Кольдинг ","name_en"=>"Kolding ","name_href" => "dk/population-of-kolding","count" => "58 021","real_id" =>9,),
"10"=>array("name_ru"=>"Хорсенс ","name_en"=>"Horsens ","name_href" => "dk/population-of-horsens","count" => "55 884","real_id" =>10,),
"11"=>array("name_ru"=>"Вайле ","name_en"=>"Vejle ","name_href" => "dk/population-of-vejle","count" => "53 230","real_id" =>11,),
"12"=>array("name_ru"=>"Роскилле ","name_en"=>"Roskilde","name_href" => "dk/population-of-roskilde","count" => "46 292","real_id" =>12,),
"13"=>array("name_ru"=>"Хернинг ","name_en"=>"Herning ","name_href" => "dk/population-of-herning","count" => "45 890","real_id" =>13,),
"14"=>array("name_ru"=>"Нествед ","name_en"=>"Næstved ","name_href" => "dk/population-of-næstved","count" => "41 857","real_id" =>14,),
"15"=>array("name_ru"=>"Силькеборг ","name_en"=>"Silkeborg ","name_href" => "dk/population-of-silkeborg","count" => "41 300","real_id" =>15,),
"16"=>array("name_ru"=>"Греве Странн ","name_en"=>"Greve Strand ","name_href" => "dk/population-of-greve-strand","count" => "40 901","real_id" =>16,),
"17"=>array("name_ru"=>"Фредерисия ","name_en"=>"Fredericia ","name_href" => "dk/population-of-fredericia","count" => "39 391","real_id" =>17,),
"18"=>array("name_ru"=>"Виборг","name_en"=>"Viborg","name_href" => "dk/population-of-viborg","count" => "37 309","real_id" =>18,),
"19"=>array("name_ru"=>"Кёге ","name_en"=>"Køge ","name_href" => "dk/population-of-køge","count" => "35 295","real_id" =>19,),
"20"=>array("name_ru"=>"Хольстебро ","name_en"=>"Holstebro","name_href" => "dk/population-of-holstebro","count" => "34 062","real_id" =>20,),
"21"=>array("name_ru"=>"Тоструп ","name_en"=>"TAASTRUP ","name_href" => "dk/population-of-taastrup","count" => "32 260","real_id" =>21,),
"22"=>array("name_ru"=>"Слагельсе ","name_en"=>"Slagelse ","name_href" => "dk/population-of-slagelse","count" => "31 918","real_id" =>22,),
"23"=>array("name_ru"=>"Хиллерёд ","name_en"=>"Hillerød ","name_href" => "dk/population-of-hillerød","count" => "29 683","real_id" =>23,),
"24"=>array("name_ru"=>"Свенборг ","name_en"=>"Svendborg ","name_href" => "dk/population-of-svendborg","count" => "27 199","real_id" =>24,),
"25"=>array("name_ru"=>"Сённерборг ","name_en"=>"Sonderborg ","name_href" => "dk/population-of-sonderborg","count" => "27 194","real_id" =>25,),
"26"=>array("name_ru"=>"Хольбек ","name_en"=>"Holbaek ","name_href" => "dk/population-of-holbaek","count" => "26 961","real_id" =>26,),
"27"=>array("name_ru"=>"Хьёрринг ","name_en"=>"Hjørring ","name_href" => "dk/population-of-hjørring","count" => "24 813","real_id" =>27,),
"28"=>array("name_ru"=>"Хёрсхольм ","name_en"=>"Hørsholm ","name_href" => "dk/population-of-hørsholm","count" => "24 378","real_id" =>28,),
"29"=>array("name_ru"=>"Хёрсхольм","name_en"=>"Hørsholm","name_href" => "dk/population-of-hørsholm","count" => "24 378","real_id" =>29,),
"30"=>array("name_ru"=>"Фредериксхавн ","name_en"=>"Frederikshavn ","name_href" => "dk/population-of-frederikshavn","count" => "23 636","real_id" =>30,),
"31"=>array("name_ru"=>"Хадерслев ","name_en"=>"Haderslev ","name_href" => "dk/population-of-haderslev","count" => "21 140","real_id" =>31,),
"32"=>array("name_ru"=>"Скиве ","name_en"=>"Skive","name_href" => "dk/population-of-skive","count" => "20 505","real_id" =>32,),
"33"=>array("name_ru"=>"Фарум","name_en"=>"Farum","name_href" => "dk/population-of-farum","count" => "18 091","real_id" =>33,),
"34"=>array("name_ru"=>"Нюкёбинг ","name_en"=>"Nykøbing ","name_href" => "dk/population-of-nykøbing","count" => "16 405","real_id" =>34,),
"35"=>array("name_ru"=>"Калуннборг","name_en"=>"Kalundborg","name_href" => "dk/population-of-kalundborg","count" => "16 303","real_id" =>35,),
"36"=>array("name_ru"=>"Нюборг","name_en"=>"Nyborg","name_href" => "dk/population-of-nyborg","count" => "16 043","real_id" =>36,),
"37"=>array("name_ru"=>"Фредерикссунн","name_en"=>"Frederikssund","name_href" => "dk/population-of-frederikssund","count" => "15 468","real_id" =>37,),
"38"=>array("name_ru"=>"Корсёр","name_en"=>"Korsør","name_href" => "dk/population-of-korsør","count" => "14 501","real_id" =>38,),
"39"=>array("name_ru"=>"Грено","name_en"=>"Grenaa","name_href" => "dk/population-of-grenaa","count" => "14 308","real_id" =>39,),
"40"=>array("name_ru"=>"Рённе","name_en"=>"Rennes","name_href" => "dk/population-of-rennes","count" => "13 579","real_id" =>40,),
"41"=>array("name_ru"=>"Наксков","name_en"=>"Nakskov","name_href" => "dk/population-of-nakskov","count" => "13 243","real_id" =>41,),
"42"=>array("name_ru"=>"Вордингборг","name_en"=>"Vordingborg","name_href" => "dk/population-of-vordingborg","count" => "11 643","real_id" =>42,),
"43"=>array("name_ru"=>"Струэр","name_en"=>"Struer","name_href" => "dk/population-of-struer","count" => "10 572","real_id" =>43,),
"44"=>array("name_ru"=>"Скаген","name_en"=>"Skagen","name_href" => "dk/population-of-skagen","count" => "8 198","real_id" =>44,),
"45"=>array("name_ru"=>"Сорё ","name_en"=>"Sora ","name_href" => "dk/population-of-sora","count" => "7 805","real_id" =>45,),
"46"=>array("name_ru"=>"Войенс","name_en"=>"Vojens","name_href" => "dk/population-of-vojens","count" => "7 650","real_id" =>46,),
"47"=>array("name_ru"=>"Норборг","name_en"=>"Nordborg","name_href" => "dk/population-of-nordborg","count" => "7 248","real_id" =>47,),
"48"=>array("name_ru"=>"Фоборг","name_en"=>"Faaborg","name_href" => "dk/population-of-faaborg","count" => "7 234","real_id" =>48,),
"49"=>array("name_ru"=>"Биллунн","name_en"=>"Billund","name_href" => "dk/population-of-billund","count" => "6 146","real_id" =>49,),
"50"=>array("name_ru"=>"Хадсунн","name_en"=>"Hadsund","name_href" => "dk/population-of-hadsund","count" => "4 994","real_id" =>50,),
"51"=>array("name_ru"=>"Сакскёбинг","name_en"=>"Sakskobing","name_href" => "dk/population-of-sakskobing","count" => "4 701","real_id" =>51,),
"52"=>array("name_ru"=>"Еллинг","name_en"=>"Jelling","name_href" => "dk/population-of-jelling","count" => "3 370","real_id" =>52,),
"53"=>array("name_ru"=>"Марсталь","name_en"=>"Marstal","name_href" => "dk/population-of-marstal","count" => "2 395","real_id" =>53,),
"54"=>array("name_ru"=>"Стуббекёбинг","name_en"=>"Stubbekøbing","name_href" => "dk/population-of-stubbekøbing","count" => "2 298","real_id" =>54,),
"55"=>array("name_ru"=>"Вардё","name_en"=>"Varde","name_href" => "dk/population-of-varde","count" => "1 930","real_id" =>55,),
"56"=>array("name_ru"=>"Сунд","name_en"=>"Sund","name_href" => "dk/population-of-sund","count" => "1 035","real_id" =>56,),
"57"=>array("name_ru"=>"Копенгаген ","name_en"=>"Copenhagen ","name_href" => "dk/population-of-copenhagen","count" => "1 246 611","real_id" =>57,),
"58"=>array("name_ru"=>"Орхус ","name_en"=>"Aarhus ","name_href" => "dk/population-of-aarhus","count" => "259 754","real_id" =>58,),
"59"=>array("name_ru"=>"Оденсе ","name_en"=>"Odense ","name_href" => "dk/population-of-odense","count" => "172 512","real_id" =>59,),
"60"=>array("name_ru"=>"Ольборг ","name_en"=>"Aalborg ","name_href" => "dk/population-of-aalborg","count" => "109 092","real_id" =>60,),
"61"=>array("name_ru"=>"Фредериксберг ","name_en"=>"FREDERICKSBURG ","name_href" => "dk/population-of-fredericksburg","count" => "95 029","real_id" =>61,)
);

?>