<?php
//Эфиопия 40
$libet = array ( 
"1"=>array("name_ru"=>"Аддис-Абеба","name_en"=>"Addis Ababa","name_href" => "et/population-of-addis-ababa","count" => "3 480 229","real_id" =>1,),
"2"=>array("name_ru"=>"Дыре-Дауа","name_en"=>"Dire Dawa","name_href" => "et/population-of-dire-dawa","count" => "355 641","real_id" =>2,),
"3"=>array("name_ru"=>"Назрет","name_en"=>"Nazret","name_href" => "et/population-of-nazret","count" => "299 621","real_id" =>3,),
"4"=>array("name_ru"=>"Гондэр","name_en"=>"Gondar","name_href" => "et/population-of-gondar","count" => "252 537","real_id" =>4,),
"5"=>array("name_ru"=>"Мэкэле","name_en"=>"Mekele","name_href" => "et/population-of-mekele","count" => "219 818","real_id" =>5,),
"6"=>array("name_ru"=>"Дэссе","name_en"=>"Desse","name_href" => "et/population-of-desse","count" => "219 423","real_id" =>6,),
"7"=>array("name_ru"=>"Бахр-Дар","name_en"=>"Bahir Dar","name_href" => "et/population-of-bahir-dar","count" => "218 429","real_id" =>7,),
"8"=>array("name_ru"=>"Джимма","name_en"=>"Jimma","name_href" => "et/population-of-jimma","count" => "207 573","real_id" =>8,),
"9"=>array("name_ru"=>"Дэбрэ-Зэйт","name_en"=>"Bishoftu","name_href" => "et/population-of-bishoftu","count" => "171 115","real_id" =>9,),
"10"=>array("name_ru"=>"Ауаса","name_en"=>"Awasa","name_href" => "et/population-of-awasa","count" => "165 275","real_id" =>10,),
"11"=>array("name_ru"=>"Харэр","name_en"=>"Harar","name_href" => "et/population-of-harar","count" => "151 977","real_id" =>11,),
"12"=>array("name_ru"=>"Джиджига","name_en"=>"Jijiga","name_href" => "et/population-of-jijiga","count" => "129 993","real_id" =>12,),
"13"=>array("name_ru"=>"Шашэмэнне","name_en"=>"Shashamane","name_href" => "et/population-of-shashamane","count" => "122 046","real_id" =>13,),
"14"=>array("name_ru"=>"Нэкэмте","name_en"=>"nekemte","name_href" => "et/population-of-nekemte","count" => "110 688","real_id" =>14,),
"15"=>array("name_ru"=>"Дэбрэ-Маркос","name_en"=>"Debre Marcos","name_href" => "et/population-of-debre-marcos","count" => "110 636","real_id" =>15,),
"16"=>array("name_ru"=>"Асэлла","name_en"=>"asella","name_href" => "et/population-of-asella","count" => "110 088","real_id" =>16,),
"17"=>array("name_ru"=>"Арба-Мынч","name_en"=>"Arba Minch","name_href" => "et/population-of-arba-minch","count" => "95 373","real_id" =>17,),
"18"=>array("name_ru"=>"Комбольча","name_en"=>"kombolcha","name_href" => "et/population-of-kombolcha","count" => "90 769","real_id" =>18,),
"19"=>array("name_ru"=>"Годе","name_en"=>"Gaudet","name_href" => "et/population-of-gaudet","count" => "88 552","real_id" =>19,),
"20"=>array("name_ru"=>"Дэбрэ-Бырхан","name_en"=>"Debre Berhan","name_href" => "et/population-of-debre-berhan","count" => "87 408","real_id" =>20,),
"21"=>array("name_ru"=>"Соддо","name_en"=>"Soddy","name_href" => "et/population-of-soddy","count" => "86 050","real_id" =>21,),
"22"=>array("name_ru"=>"Адди-Грат","name_en"=>"Adigrat","name_href" => "et/population-of-adigrat","count" => "85 705","real_id" =>22,),
"23"=>array("name_ru"=>"Дилла","name_en"=>"Dill","name_href" => "et/population-of-dill","count" => "79 892","real_id" =>23,),
"24"=>array("name_ru"=>"Хосаына","name_en"=>"Hosaena","name_href" => "et/population-of-hosaena","count" => "75 963","real_id" =>24,),
"25"=>array("name_ru"=>"Гоба","name_en"=>"Goba","name_href" => "et/population-of-goba","count" => "65 789","real_id" =>25,),
"26"=>array("name_ru"=>"Амбо","name_en"=>"Ambo","name_href" => "et/population-of-ambo","count" => "64 684","real_id" =>26,),
"27"=>array("name_ru"=>"Аксум","name_en"=>"Aksum","name_href" => "et/population-of-aksum","count" => "61 429","real_id" =>27,),
"28"=>array("name_ru"=>"Аламата","name_en"=>"Alamat","name_href" => "et/population-of-alamat","count" => "59 584","real_id" =>28,),
"29"=>array("name_ru"=>"Гыйон","name_en"=>"Waliso","name_href" => "et/population-of-waliso","count" => "59 500","real_id" =>29,),
"30"=>array("name_ru"=>"Ында-Сылласе","name_en"=>"Ynda-Syllase","name_href" => "et/population-of-ynda-syllase","count" => "57 486","real_id" =>30,),
"31"=>array("name_ru"=>"Йирга-Алем","name_en"=>"Irgalem","name_href" => "et/population-of-irgalem","count" => "45 908","real_id" =>31,),
"32"=>array("name_ru"=>"Нэгэле","name_en"=>"Negele Arsi","name_href" => "et/population-of-negele-arsi","count" => "45 007","real_id" =>32,),
"33"=>array("name_ru"=>"Адуа","name_en"=>"Adua","name_href" => "et/population-of-adua","count" => "44 658","real_id" =>33,),
"34"=>array("name_ru"=>"Уольдыя","name_en"=>"Weldiya","name_href" => "et/population-of-weldiya","count" => "44 734","real_id" =>34,),
"35"=>array("name_ru"=>"Дэгэх-Бур","name_en"=>"Degehabur zone","name_href" => "et/population-of-degehabur-zone","count" => "44 738","real_id" =>35,),
"36"=>array("name_ru"=>"Нэгэле","name_en"=>"Negele Arsi","name_href" => "et/population-of-negele-arsi","count" => "44 059","real_id" =>36,),
"37"=>array("name_ru"=>"Агаро","name_en"=>"agar","name_href" => "et/population-of-agar","count" => "43 602","real_id" =>37,),
"38"=>array("name_ru"=>"Моджо","name_en"=>"Mojo","name_href" => "et/population-of-mojo","count" => "41 191","real_id" =>38,),
"39"=>array("name_ru"=>"Дэбрэ-Табор","name_en"=>"Debre Tabor","name_href" => "et/population-of-debre-tabor","count" => "40 901","real_id" =>39,),
"40"=>array("name_ru"=>"Роби","name_en"=>"Roby","name_href" => "et/population-of-roby","count" => "40 316","real_id" =>40,),
"41"=>array("name_ru"=>"Аддис-Абеба","name_en"=>"Addis Ababa","name_href" => "et/population-of-addis-ababa","count" => "3 480 229","real_id" =>41,),
"42"=>array("name_ru"=>"Дыре-Дауа","name_en"=>"Dire Dawa","name_href" => "et/population-of-dire-dawa","count" => "355 641","real_id" =>42,),
"43"=>array("name_ru"=>"Назрет","name_en"=>"Nazret","name_href" => "et/population-of-nazret","count" => "299 621","real_id" =>43,),
"44"=>array("name_ru"=>"Гондэр","name_en"=>"Gondar","name_href" => "et/population-of-gondar","count" => "252 537","real_id" =>44,),
"45"=>array("name_ru"=>"Мэкэле","name_en"=>"Mekele","name_href" => "et/population-of-mekele","count" => "219 818","real_id" =>45,)
);

?>