<?php
//Англия 194
$libeng = array ( 
"1"=>array("name_ru"=>"Лондон","name_en"=>"London","name_href" => "eng/population-of-london","count" => "8 173 900","real_id" =>1,),
"2"=>array("name_ru"=>"Бирмингем","name_en"=>"Birmingham","name_href" => "eng/population-of-birmingham","count" => "1 010 000","real_id" =>2,),
"3"=>array("name_ru"=>"Лидс","name_en"=>"Leeds","name_href" => "eng/population-of-leeds","count" => "761 100","real_id" =>3,),
"4"=>array("name_ru"=>"Глазго","name_en"=>"Glasgow","name_href" => "eng/population-of-glasgow","count" => "580 690","real_id" =>4,),
"5"=>array("name_ru"=>"Белфаст","name_en"=>"Belfast","name_href" => "eng/population-of-belfast","count" => "579 554","real_id" =>5,),
"6"=>array("name_ru"=>"Шеффилд","name_en"=>"Sheffield","name_href" => "eng/population-of-sheffield","count" => "530 300","real_id" =>6,),
"7"=>array("name_ru"=>"Манчестер","name_en"=>"Manchester","name_href" => "eng/population-of-manchester","count" => "502 900","real_id" =>7,),
"8"=>array("name_ru"=>"Брадфорд","name_en"=>"Bradford","name_href" => "eng/population-of-bradford","count" => "497 400","real_id" =>8,),
"9"=>array("name_ru"=>"Эдинбург","name_en"=>"Edinburgh","name_href" => "eng/population-of-edinburgh","count" => "468 070","real_id" =>9,),
"10"=>array("name_ru"=>"Ливерпуль","name_en"=>"Liverpool","name_href" => "eng/population-of-liverpool","count" => "435 500","real_id" =>10,),
"11"=>array("name_ru"=>"Бристоль","name_en"=>"Bristol","name_href" => "eng/population-of-bristol","count" => "416 400","real_id" =>11,),
"12"=>array("name_ru"=>"Уэйкфилд","name_en"=>"Wakefield","name_href" => "eng/population-of-wakefield","count" => "321 600","real_id" =>12,),
"13"=>array("name_ru"=>"Кардифф","name_en"=>"Cardiff","name_href" => "eng/population-of-cardiff","count" => "317 500","real_id" =>13,),
"14"=>array("name_ru"=>"Ковентри","name_en"=>"Coventry","name_href" => "eng/population-of-coventry","count" => "316 900","real_id" =>14,),
"15"=>array("name_ru"=>"Лестер","name_en"=>"Leicester","name_href" => "eng/population-of-leicester","count" => "292 600","real_id" =>15,),
"16"=>array("name_ru"=>"Ноттингем","name_en"=>"Nottingham","name_href" => "eng/population-of-nottingham","count" => "288 700","real_id" =>16,),
"17"=>array("name_ru"=>"Сандерленд","name_en"=>"Sunderland","name_href" => "eng/population-of-sunderland","count" => "280 300","real_id" =>17,),
"18"=>array("name_ru"=>"Белфаст","name_en"=>"Belfast","name_href" => "eng/population-of-belfast","count" => "276 460","real_id" =>18,),
"19"=>array("name_ru"=>"Ньюкасл-апон-Тайн(Ньюкасл)","name_en"=>"Newcastle upon Tyne (Newcastle)","name_href" => "eng/population-of-newcastle-upon-tyne","count" => "271 600","real_id" =>19,),
"20"=>array("name_ru"=>"Кингстон-апон-Халл","name_en"=>"Kingston upon Hull","name_href" => "eng/population-of-kingston upon hull","count" => "257 000","real_id" =>20,),
"21"=>array("name_ru"=>"Брайтон и Хоув","name_en"=>"Brighton & Hove","name_href" => "eng/population-of-brighton & hove","count" => "253 500","real_id" =>21,),
"22"=>array("name_ru"=>"Плимут","name_en"=>"Plymouth","name_href" => "eng/population-of-plymouth","count" => "250 700","real_id" =>22,),
"23"=>array("name_ru"=>"Сток-он-Трент","name_en"=>"Stoke-on-Trent","name_href" => "eng/population-of-stoke-on-trent","count" => "239 700","real_id" =>23,),
"24"=>array("name_ru"=>"Дерби","name_en"=>"Derby","name_href" => "eng/population-of-derby","count" => "236 300","real_id" =>24,),
"25"=>array("name_ru"=>"Вулвергемптон","name_en"=>"Wolverhampton","name_href" => "eng/population-of-wolverhampton","count" => "236 000","real_id" =>25,),
"26"=>array("name_ru"=>"Вестминстер(Уэстминстер)","name_en"=>"Westminster (Westminster)","name_href" => "eng/population-of-westminster","count" => "234 100","real_id" =>26,),
"27"=>array("name_ru"=>"Саутгемптон","name_en"=>"Southampton","name_href" => "eng/population-of-southampton","count" => "228 600","real_id" =>27,),
"28"=>array("name_ru"=>"Суонси","name_en"=>"Swansea","name_href" => "eng/population-of-swansea","count" => "228 100","real_id" =>28,),
"29"=>array("name_ru"=>"Солфорд","name_en"=>"Salford","name_href" => "eng/population-of-salford","count" => "219 200","real_id" =>29,),
"30"=>array("name_ru"=>"Портсмут","name_en"=>"Portsmouth","name_href" => "eng/population-of-portsmouth","count" => "197 700","real_id" =>30,),
"31"=>array("name_ru"=>"Нортгемптон","name_en"=>"Northampton","name_href" => "eng/population-of-northampton","count" => "195 000","real_id" =>31,),
"32"=>array("name_ru"=>"Дадли","name_en"=>"Dudley","name_href" => "eng/population-of-dudley","count" => "194 919","real_id" =>32,),
"33"=>array("name_ru"=>"Йорк","name_en"=>"York","name_href" => "eng/population-of-york","count" => "193 300","real_id" =>33,),
"34"=>array("name_ru"=>"Абердин","name_en"=>"Aberdeen","name_href" => "eng/population-of-aberdeen","count" => "192 080","real_id" =>34,),
"35"=>array("name_ru"=>"Милтон-Кинс","name_en"=>"Milton Keynes","name_href" => "eng/population-of-milton-keynes","count" => "192 000","real_id" =>35,),
"36"=>array("name_ru"=>"Лутон","name_en"=>"Luton","name_href" => "eng/population-of-luton","count" => "184 900","real_id" =>36,),
"37"=>array("name_ru"=>"Питерборо","name_en"=>"Peterborough","name_href" => "eng/population-of-peterborough","count" => "183 600","real_id" =>37,),
"38"=>array("name_ru"=>"Уолсолл","name_en"=>"Walsall","name_href" => "eng/population-of-walsall","count" => "170 994","real_id" =>38,),
"39"=>array("name_ru"=>"Борнмут","name_en"=>"Bournemouth","name_href" => "eng/population-of-bournemouth","count" => "163 500","real_id" =>39,),
"40"=>array("name_ru"=>"Телфорд","name_en"=>"Telford","name_href" => "eng/population-of-telford","count" => "162 300","real_id" =>40,),
"41"=>array("name_ru"=>"Саутенд-он-Си","name_en"=>"Southend-on-Sea","name_href" => "eng/population-of-southend-on-sea","count" => "159 300","real_id" =>41,),
"42"=>array("name_ru"=>"Рипон","name_en"=>"Ripon","name_href" => "eng/population-of-ripon","count" => "159 200","real_id" =>42,),
"43"=>array("name_ru"=>"Брайтон","name_en"=>"Brighton","name_href" => "eng/population-of-brighton","count" => "155 919","real_id" =>43,),
"44"=>array("name_ru"=>"Суиндон","name_en"=>"Swindon","name_href" => "eng/population-of-swindon","count" => "155 432","real_id" =>44,),
"45"=>array("name_ru"=>"Оксфорд","name_en"=>"Oxford","name_href" => "eng/population-of-oxford","count" => "151 000","real_id" =>45,),
"46"=>array("name_ru"=>"Кентербери","name_en"=>"Canterbury","name_href" => "eng/population-of-canterbury","count" => "148 000","real_id" =>46,),
"47"=>array("name_ru"=>"Хаддерсфилд","name_en"=>"Huddersfield","name_href" => "eng/population-of-huddersfield","count" => "146 234","real_id" =>47,),
"48"=>array("name_ru"=>"Рединг","name_en"=>"Reading","name_href" => "eng/population-of-reading","count" => "143 096","real_id" =>48,),
"49"=>array("name_ru"=>"Мидлсбро","name_en"=>"Middlesbrough","name_href" => "eng/population-of-middlesbrough","count" => "142 691","real_id" =>49,),
"50"=>array("name_ru"=>"Блэкпул","name_en"=>"Blackpool","name_href" => "eng/population-of-blackpool","count" => "142 100","real_id" =>50,),
"51"=>array("name_ru"=>"Данди","name_en"=>"Dundee","name_href" => "eng/population-of-dundee","count" => "141 930","real_id" =>51,),
"52"=>array("name_ru"=>"Ньюпорт","name_en"=>"Newport","name_href" => "eng/population-of-newport","count" => "140 200","real_id" =>52,),
"53"=>array("name_ru"=>"Болтон","name_en"=>"Bolton","name_href" => "eng/population-of-bolton","count" => "139 403","real_id" =>53,),
"54"=>array("name_ru"=>"Пул","name_en"=>"Pool","name_href" => "eng/population-of-pool","count" => "138 800","real_id" =>54,),
"55"=>array("name_ru"=>"Стокпорт","name_en"=>"Stockport","name_href" => "eng/population-of-stockport","count" => "136 082","real_id" =>55,),
"56"=>array("name_ru"=>"Ипсуич","name_en"=>"Ipswich","name_href" => "eng/population-of-ipswich","count" => "133 384","real_id" =>56,),
"57"=>array("name_ru"=>"Норвич","name_en"=>"Norwich","name_href" => "eng/population-of-norwich","count" => "132 200","real_id" =>57,),
"58"=>array("name_ru"=>"Престон","name_en"=>"Preston","name_href" => "eng/population-of-preston","count" => "131 900","real_id" =>58,),
"59"=>array("name_ru"=>"Норидж","name_en"=>"Norwich","name_href" => "eng/population-of-norwich","count" => "129 500","real_id" =>59,),
"60"=>array("name_ru"=>"Глостер","name_en"=>"Gloucester","name_href" => "eng/population-of-gloucester","count" => "123 210","real_id" =>60,),
"61"=>array("name_ru"=>"Эксетер","name_en"=>"Exeter","name_href" => "eng/population-of-exeter","count" => "122 400","real_id" =>61,),
"62"=>array("name_ru"=>"Кембридж","name_en"=>"Cambridge","name_href" => "eng/population-of-cambridge","count" => "120 000","real_id" =>62,),
"63"=>array("name_ru"=>"Честер","name_en"=>"Chester","name_href" => "eng/population-of-chester","count" => "119 900","real_id" =>63,),
"64"=>array("name_ru"=>"Слау","name_en"=>"Slough","name_href" => "eng/population-of-slough","count" => "119 067","real_id" =>64,),
"65"=>array("name_ru"=>"Ротерем","name_en"=>"Rotherham","name_href" => "eng/population-of-rotherham","count" => "117 262","real_id" =>65,),
"66"=>array("name_ru"=>"Винчестер","name_en"=>"Winchester","name_href" => "eng/population-of-winchester","count" => "111 300","real_id" =>66,),
"67"=>array("name_ru"=>"Саттон-Колфилд","name_en"=>"Sutton Caulfield","name_href" => "eng/population-of-sutton-caulfield","count" => "105 452","real_id" =>67,),
"68"=>array("name_ru"=>"Блэкберн","name_en"=>"Blackburn","name_href" => "eng/population-of-blackburn","count" => "105 085","real_id" =>68,),
"69"=>array("name_ru"=>"Колчестер","name_en"=>"Colchester","name_href" => "eng/population-of-colchester","count" => "104 390","real_id" =>69,),
"70"=>array("name_ru"=>"Честерфилд","name_en"=>"Chesterfield","name_href" => "eng/population-of-chesterfield","count" => "103 800","real_id" =>70,),
"71"=>array("name_ru"=>"Олдем","name_en"=>"Oldham","name_href" => "eng/population-of-oldham","count" => "103 544","real_id" =>71,),
"72"=>array("name_ru"=>"Карлайл","name_en"=>"Carlisle","name_href" => "eng/population-of-carlisle","count" => "103 500","real_id" =>72,),
"73"=>array("name_ru"=>"Сент-Хеленс","name_en"=>"St. Helens","name_href" => "eng/population-of-st-helens","count" => "102 629","real_id" =>73,),
"74"=>array("name_ru"=>"Кроли","name_en"=>"Crawley","name_href" => "eng/population-of-crawley","count" => "100 547","real_id" =>74,),
"75"=>array("name_ru"=>"Дарем","name_en"=>"Durham","name_href" => "eng/population-of-durham","count" => "94 300","real_id" =>75,),
"76"=>array("name_ru"=>"Вустер","name_en"=>"Worcester","name_href" => "eng/population-of-worcester","count" => "93 700","real_id" =>76,),
"77"=>array("name_ru"=>"Линкольн","name_en"=>"Lincoln","name_href" => "eng/population-of-lincoln","count" => "87 800","real_id" =>77,),
"78"=>array("name_ru"=>"Дерри(Лондондерри)","name_en"=>"Derry (Londonderry)","name_href" => "eng/population-of-derry","count" => "83 650","real_id" =>78,),
"79"=>array("name_ru"=>"Бат","name_en"=>"Bath","name_href" => "eng/population-of-bath","count" => "80 000","real_id" =>79,),
"80"=>array("name_ru"=>"Бангор","name_en"=>"Bangor","name_href" => "eng/population-of-bangor","count" => "76 403","real_id" =>80,),
"81"=>array("name_ru"=>"Лисберн","name_en"=>"Lisburn","name_href" => "eng/population-of-lisburn","count" => "76 068","real_id" =>81,),
"82"=>array("name_ru"=>"Сент-Олбанс","name_en"=>"Saint Albans","name_href" => "eng/population-of-saint-albans","count" => "64 040","real_id" =>82,),
"83"=>array("name_ru"=>"Ньютаунабби","name_en"=>"Newtownabbi","name_href" => "eng/population-of-newtownabbi","count" => "62 056","real_id" =>83,),
"84"=>array("name_ru"=>"Крейгавон","name_en"=>"Craigavon","name_href" => "eng/population-of-craigavon","count" => "57 685","real_id" =>84,),
"85"=>array("name_ru"=>"Инвернесс","name_en"=>"Inverness","name_href" => "eng/population-of-inverness","count" => "51 830","real_id" =>85,),
"86"=>array("name_ru"=>"Херефорд","name_en"=>"Hereford","name_href" => "eng/population-of-hereford","count" => "50 400","real_id" =>86,),
"87"=>array("name_ru"=>"Единбург","name_en"=>"Edinburgh","name_href" => "eng/population-of-edinburgh","count" => "46 499","real_id" =>87,),
"88"=>array("name_ru"=>"Лланелли","name_en"=>"Llanelli","name_href" => "eng/population-of-llanelli","count" => "46 358","real_id" =>88,),
"89"=>array("name_ru"=>"Ланкастер","name_en"=>"Lancaster","name_href" => "eng/population-of-lancaster","count" => "45 950","real_id" =>89,),
"90"=>array("name_ru"=>"Нит","name_en"=>"Nit","name_href" => "eng/population-of-nit","count" => "45 898","real_id" =>90,),
"91"=>array("name_ru"=>"Солсбери","name_en"=>"Salisbury","name_href" => "eng/population-of-salisbury","count" => "45 000","real_id" =>91,),
"92"=>array("name_ru"=>"Перт","name_en"=>"Perth","name_href" => "eng/population-of-perth","count" => "44 000","real_id" =>92,),
"93"=>array("name_ru"=>"Рексем","name_en"=>"Wrexham","name_href" => "eng/population-of-wrexham","count" => "42 576","real_id" =>93,),
"94"=>array("name_ru"=>"Стерлинг","name_en"=>"Sterling","name_href" => "eng/population-of-sterling","count" => "41 240","real_id" =>94,),
"95"=>array("name_ru"=>"Порт-Толбот","name_en"=>"Port Talbot","name_href" => "eng/population-of-port-talbot","count" => "35 633","real_id" =>95,),
"96"=>array("name_ru"=>"Абердэр","name_en"=>"Aberdare","name_href" => "eng/population-of-aberdare","count" => "31 705","real_id" =>96,),
"97"=>array("name_ru"=>"Понтиприт","name_en"=>"Pontyprit","name_href" => "eng/population-of-pontyprit","count" => "29 781","real_id" =>97,),
"98"=>array("name_ru"=>"Баллимина","name_en"=>"BALLIMINE","name_href" => "eng/population-of-ballimine","count" => "28 717","real_id" =>98,),
"99"=>array("name_ru"=>"Ньютаунардс","name_en"=>"Newtownards","name_href" => "eng/population-of-newtownards","count" => "27 821","real_id" =>99,),
"100"=>array("name_ru"=>"Ньюри","name_en"=>"Newry","name_href" => "eng/population-of-newry","count" => "27 430","real_id" =>100,),
"101"=>array("name_ru"=>"Каррикфергус","name_en"=>"Carrickfergus","name_href" => "eng/population-of-carrickfergus","count" => "27 201","real_id" =>101,),
"102"=>array("name_ru"=>"Колрейн","name_en"=>"Coleraine","name_href" => "eng/population-of-coleraine","count" => "24 042","real_id" =>102,),
"103"=>array("name_ru"=>"Чичестер","name_en"=>"Chichester","name_href" => "eng/population-of-chichester","count" => "23 730","real_id" =>103,),
"104"=>array("name_ru"=>"Лурган","name_en"=>"Lurgan","name_href" => "eng/population-of-lurgan","count" => "23 000","real_id" =>104,),
"105"=>array("name_ru"=>"Ома","name_en"=>"Ohm","name_href" => "eng/population-of-ohm","count" => "22 182","real_id" =>105,),
"106"=>array("name_ru"=>"Портадаун","name_en"=>"Portadown","name_href" => "eng/population-of-portadown","count" => "22 000","real_id" =>106,),
"107"=>array("name_ru"=>"Труро","name_en"=>"Truro","name_href" => "eng/population-of-truro","count" => "20 920","real_id" =>107,),
"108"=>array("name_ru"=>"Лландидно","name_en"=>"Llandudno","name_href" => "eng/population-of-llandudno","count" => "20 090","real_id" =>108,),
"109"=>array("name_ru"=>"Дундональд","name_en"=>"Dundonald","name_href" => "eng/population-of-dundonald","count" => "20 000","real_id" =>109,),
"110"=>array("name_ru"=>"Антрим","name_en"=>"Antrim","name_href" => "eng/population-of-antrim","count" => "19 986","real_id" =>110,),
"111"=>array("name_ru"=>"Ларн","name_en"=>"Larne","name_href" => "eng/population-of-larne","count" => "18 228","real_id" =>111,),
"112"=>array("name_ru"=>"Страбан","name_en"=>"Strabban","name_href" => "eng/population-of-strabban","count" => "17 000","real_id" =>112,),
"113"=>array("name_ru"=>"Или","name_en"=>"Or","name_href" => "eng/population-of-or","count" => "15 100","real_id" =>113,),
"114"=>array("name_ru"=>"Банбридж","name_en"=>"Banbridge","name_href" => "eng/population-of-banbridge","count" => "14 744","real_id" =>114,),
"115"=>array("name_ru"=>"Арма","name_en"=>"Armagh","name_href" => "eng/population-of-armagh","count" => "14 590","real_id" =>115,),
"116"=>array("name_ru"=>"Абергавенни","name_en"=>"Abergavenny","name_href" => "eng/population-of-abergavenny","count" => "14 211","real_id" =>116,),
"117"=>array("name_ru"=>"Конуи","name_en"=>"Conwy","name_href" => "eng/population-of-conwy","count" => "14 208","real_id" =>117,),
"118"=>array("name_ru"=>"Эннискиллен","name_en"=>"Enniskillen","name_href" => "eng/population-of-enniskillen","count" => "13 757","real_id" =>118,),
"119"=>array("name_ru"=>"Баргойд","name_en"=>"Bargoyd","name_href" => "eng/population-of-bargoyd","count" => "13 721","real_id" =>119,),
"120"=>array("name_ru"=>"Кармартен","name_en"=>"Carmarthen","name_href" => "eng/population-of-carmarthen","count" => "13 148","real_id" =>120,),
"121"=>array("name_ru"=>"Аберистуит","name_en"=>"Aberystwyth","name_href" => "eng/population-of-aberystwyth","count" => "12 250","real_id" =>121,),
"122"=>array("name_ru"=>"Лимавади","name_en"=>"Limavadi","name_href" => "eng/population-of-limavadi","count" => "12 135","real_id" =>122,),
"123"=>array("name_ru"=>"Холивуд","name_en"=>"Holywood","name_href" => "eng/population-of-holywood","count" => "12 037","real_id" =>123,),
"124"=>array("name_ru"=>"Калдикот","name_en"=>"Caldicott","name_href" => "eng/population-of-caldicott","count" => "11 373","real_id" =>124,),
"125"=>array("name_ru"=>"Холихед","name_en"=>"Holyhead","name_href" => "eng/population-of-holyhead","count" => "11 237","real_id" =>125,),
"126"=>array("name_ru"=>"Данганнон","name_en"=>"Dungannon","name_href" => "eng/population-of-dungannon","count" => "11 139","real_id" =>126,),
"127"=>array("name_ru"=>"Чепстоу","name_en"=>"Chepstow","name_href" => "eng/population-of-chepstow","count" => "10 821","real_id" =>127,),
"128"=>array("name_ru"=>"Хаверфордвест","name_en"=>"Haverfordwest","name_href" => "eng/population-of-haverfordwest","count" => "10 808","real_id" =>128,),
"129"=>array("name_ru"=>"Кукстаун","name_en"=>"Cookstown","name_href" => "eng/population-of-cookstown","count" => "10 646","real_id" =>129,),
"130"=>array("name_ru"=>"Абергеле","name_en"=>"Abergele","name_href" => "eng/population-of-abergele","count" => "10 577","real_id" =>130,),
"131"=>array("name_ru"=>"Уэлс","name_en"=>"Wells","name_href" => "eng/population-of-wells","count" => "10 410","real_id" =>131,),
"132"=>array("name_ru"=>"Даунпатрик","name_en"=>"Downpatrick","name_href" => "eng/population-of-downpatrick","count" => "10 316","real_id" =>132,),
"133"=>array("name_ru"=>"Абербаргойд","name_en"=>"Aberbrogoyd","name_href" => "eng/population-of-aberbrogoyd","count" => "9 184","real_id" =>133,),
"134"=>array("name_ru"=>"Брекон","name_en"=>"Brecon","name_href" => "eng/population-of-brecon","count" => "7 901","real_id" =>134,),
"135"=>array("name_ru"=>"Пейсли","name_en"=>"Paisley","name_href" => "eng/population-of-paisley","count" => "7 622","real_id" =>135,),
"136"=>array("name_ru"=>"Ист Килбрайд","name_en"=>"East Kilbride","name_href" => "eng/population-of-east-kilbride","count" => "7 474","real_id" =>136,),
"137"=>array("name_ru"=>"Ливингстон","name_en"=>"Livingston","name_href" => "eng/population-of-livingston","count" => "5 657","real_id" =>137,),
"138"=>array("name_ru"=>"Аберавон","name_en"=>"Aberavon","name_href" => "eng/population-of-aberavon","count" => "5 452","real_id" =>138,),
"139"=>array("name_ru"=>"Камбернолд","name_en"=>"Cumbernauld","name_href" => "eng/population-of-cumbernauld","count" => "5 161","real_id" =>139,),
"140"=>array("name_ru"=>"Данфермлин","name_en"=>"Dunfermline","name_href" => "eng/population-of-dunfermline","count" => "5 038","real_id" =>140,),
"141"=>array("name_ru"=>"Керколди","name_en"=>"Kirkcaldy","name_href" => "eng/population-of-kirkcaldy","count" => "4 946","real_id" =>141,),
"142"=>array("name_ru"=>"Блайнай-Фестиниог","name_en"=>"Blaynay-Festiniog","name_href" => "eng/population-of-blaynay-festiniog","count" => "4 875","real_id" =>142,),
"143"=>array("name_ru"=>"Аберкарн","name_en"=>"Abercarn","name_href" => "eng/population-of-abercarn","count" => "4 793","real_id" =>143,),
"144"=>array("name_ru"=>"Эр","name_en"=>"Ayr","name_href" => "eng/population-of-ayr","count" => "4 719","real_id" =>144,),
"145"=>array("name_ru"=>"Килмарнок","name_en"=>"Kilmarnock","name_href" => "eng/population-of-kilmarnock","count" => "4 635","real_id" =>145,),
"146"=>array("name_ru"=>"Коатбридж","name_en"=>"Coatbridge","name_href" => "eng/population-of-coatbridge","count" => "4 397","real_id" =>146,),
"147"=>array("name_ru"=>"Гринок","name_en"=>"Greenock","name_href" => "eng/population-of-greenock","count" => "4 369","real_id" =>147,),
"148"=>array("name_ru"=>"Лланголлен","name_en"=>"Llangollen","name_href" => "eng/population-of-llangollen","count" => "3 884","real_id" =>148,),
"149"=>array("name_ru"=>"Эдри","name_en"=>"Edri","name_href" => "eng/population-of-edri","count" => "3 713","real_id" =>149,),
"150"=>array("name_ru"=>"Фолкерк","name_en"=>"Falkirk","name_href" => "eng/population-of-falkirk","count" => "3 531","real_id" =>150,),
"151"=>array("name_ru"=>"Амлух","name_en"=>"Amlouh","name_href" => "eng/population-of-amlouh","count" => "3 438","real_id" =>151,),
"152"=>array("name_ru"=>"Эрвин","name_en"=>"Erwin","name_href" => "eng/population-of-erwin","count" => "3 374","real_id" =>152,),
"153"=>array("name_ru"=>"Дамфрис","name_en"=>"Dumfries","name_href" => "eng/population-of-dumfries","count" => "3 328","real_id" =>153,),
"154"=>array("name_ru"=>"Мотеруэлл","name_en"=>"Motherwell","name_href" => "eng/population-of-motherwell","count" => "3 212","real_id" =>154,),
"155"=>array("name_ru"=>"Рутерглен","name_en"=>"Rutherglen","name_href" => "eng/population-of-rutherglen","count" => "3 118","real_id" =>155,),
"156"=>array("name_ru"=>"Личфилд","name_en"=>"Lichfield","name_href" => "eng/population-of-lichfield","count" => "3 100","real_id" =>156,),
"157"=>array("name_ru"=>"Вишоу","name_en"=>"Wishaw","name_href" => "eng/population-of-wishaw","count" => "3 051","real_id" =>157,),
"158"=>array("name_ru"=>"Камбусленг","name_en"=>"Cabunes","name_href" => "eng/population-of-cabunes","count" => "2 761","real_id" =>158,),
"159"=>array("name_ru"=>"Берсден","name_en"=>"Bersden","name_href" => "eng/population-of-bersden","count" => "2 734","real_id" =>159,),
"160"=>array("name_ru"=>"Клайдбанк","name_en"=>"Clydebank","name_href" => "eng/population-of-clydebank","count" => "2 664","real_id" =>160,),
"161"=>array("name_ru"=>"Бармут","name_en"=>"Barmouth","name_href" => "eng/population-of-barmouth","count" => "2 522","real_id" =>161,),
"162"=>array("name_ru"=>"Ньютон-Мирнс","name_en"=>"Newton-Mirns","name_href" => "eng/population-of-newton-mirns","count" => "2 465","real_id" =>162,),
"163"=>array("name_ru"=>"Арброт","name_en"=>"Arbroath","name_href" => "eng/population-of-arbroath","count" => "2 364","real_id" =>163,),
"164"=>array("name_ru"=>"Масселборо","name_en"=>"Musselborough","name_href" => "eng/population-of-musselborough","count" => "2 362","real_id" =>164,),
"165"=>array("name_ru"=>"Бишопбриггс","name_en"=>"Bishopbriggs","name_href" => "eng/population-of-bishopbriggs","count" => "2 343","real_id" =>165,),
"166"=>array("name_ru"=>"Бенллех","name_en"=>"Benlech","name_href" => "eng/population-of-benlech","count" => "2 332","real_id" =>166,),
"167"=>array("name_ru"=>"Аск","name_en"=>"Ask","name_href" => "eng/population-of-ask","count" => "2 318","real_id" =>167,),
"168"=>array("name_ru"=>"Элгин","name_en"=>"Elgin","name_href" => "eng/population-of-elgin","count" => "2 298","real_id" =>168,),
"169"=>array("name_ru"=>"Ренфру","name_en"=>"Renfrew","name_href" => "eng/population-of-renfrew","count" => "2 201","real_id" =>169,),
"170"=>array("name_ru"=>"Батгейт","name_en"=>"Bathgate","name_href" => "eng/population-of-bathgate","count" => "2 107","real_id" =>170,),
"171"=>array("name_ru"=>"Белсхилл","name_en"=>"Belshill","name_href" => "eng/population-of-belshill","count" => "2 065","real_id" =>171,),
"172"=>array("name_ru"=>"Бомарис","name_en"=>"Bomaris","name_href" => "eng/population-of-bomaris","count" => "2 040","real_id" =>172,),
"173"=>array("name_ru"=>"Аллоа","name_en"=>"Alloa","name_href" => "eng/population-of-alloa","count" => "2 039","real_id" =>173,),
"174"=>array("name_ru"=>"Дамбартон","name_en"=>"Dumbarton","name_href" => "eng/population-of-dumbarton","count" => "1 995","real_id" =>174,),
"175"=>array("name_ru"=>"Керкинтиллох","name_en"=>"Kirkillilloch","name_href" => "eng/population-of-kirkillilloch","count" => "1 963","real_id" =>175,),
"176"=>array("name_ru"=>"Питерхед","name_en"=>"Peterhead","name_href" => "eng/population-of-peterhead","count" => "1 845","real_id" =>176,),
"177"=>array("name_ru"=>"Баррхед","name_en"=>"Barrhead","name_href" => "eng/population-of-barrhead","count" => "1 762","real_id" =>177,),
"178"=>array("name_ru"=>"Гренджмут","name_en"=>"Grencjmut","name_href" => "eng/population-of-grencjmut","count" => "1 728","real_id" =>178,),
"179"=>array("name_ru"=>"Блантайр","name_en"=>"Blantyre","name_href" => "eng/population-of-blantyre","count" => "1 709","real_id" =>179,),
"180"=>array("name_ru"=>"Килуиннинг","name_en"=>"Kiluining","name_href" => "eng/population-of-kiluining","count" => "1 642","real_id" =>180,),
"181"=>array("name_ru"=>"Джонстон","name_en"=>"Johnston","name_href" => "eng/population-of-johnston","count" => "1 639","real_id" =>181,),
"182"=>array("name_ru"=>"Бонниригг","name_en"=>"Bonnirigg","name_href" => "eng/population-of-bonnirigg","count" => "1 636","real_id" =>182,),
"183"=>array("name_ru"=>"Пенік","name_en"=>"Penik","name_href" => "eng/population-of-penik","count" => "1 611","real_id" =>183,),
"184"=>array("name_ru"=>"Вьюпарк","name_en"=>"View Park","name_href" => "eng/population-of-view-park","count" => "1 602","real_id" =>184,),
"185"=>array("name_ru"=>"Эрскин","name_en"=>"Erskine","name_href" => "eng/population-of-erskine","count" => "1 553","real_id" =>185,),
"186"=>array("name_ru"=>"Броксберн","name_en"=>"Broxburn","name_href" => "eng/population-of-broxburn","count" => "1 536","real_id" =>186,),
"187"=>array("name_ru"=>"Аберайрон","name_en"=>"Aberrayron","name_href" => "eng/population-of-aberrayron","count" => "1 520","real_id" =>187,),
"188"=>array("name_ru"=>"Порт-Глазго","name_en"=>"Port Glasgow","name_href" => "eng/population-of-port-glasgow","count" => "1 519","real_id" =>188,),
"189"=>array("name_ru"=>"Ларкхолл","name_en"=>"Larkhall","name_href" => "eng/population-of-larkhall","count" => "1 502","real_id" =>189,),
"190"=>array("name_ru"=>"Куинсферри","name_en"=>"Queensferry","name_href" => "eng/population-of-queensferry","count" => "1 500","real_id" =>190,),
"191"=>array("name_ru"=>"Лланвиллин","name_en"=>"Llanvillin","name_href" => "eng/population-of-llanvillin","count" => "1 407","real_id" =>191,),
"192"=>array("name_ru"=>"Гамильтон","name_en"=>"Hamilton","name_href" => "eng/population-of-hamilton","count" => "532","real_id" =>192,),
"193"=>array("name_ru"=>"Гленротес","name_en"=>"Glenrothes","name_href" => "eng/population-of-glenrothes","count" => "391","real_id" =>193,),
"194"=>array("name_ru"=>"Сент-Андрус","name_en"=>"Saint Andrus","name_href" => "eng/population-of-saint-andrus","count" => "168","real_id" =>194,),
"195"=>array("name_ru"=>"Лондон","name_en"=>"London","name_href" => "eng/population-of-london","count" => "8 173 900","real_id" =>195,),
"196"=>array("name_ru"=>"Бирмингем","name_en"=>"Birmingham","name_href" => "eng/population-of-birmingham","count" => "1 010 000","real_id" =>196,),
"197"=>array("name_ru"=>"Лидс","name_en"=>"Leeds","name_href" => "eng/population-of-leeds","count" => "761 100","real_id" =>197,),
"198"=>array("name_ru"=>"Глазго","name_en"=>"Glasgow","name_href" => "eng/population-of-glasgow","count" => "580 690","real_id" =>198,),
"199"=>array("name_ru"=>"Белфаст","name_en"=>"Belfast","name_href" => "eng/population-of-belfast","count" => "579 554","real_id" =>199,)
);

?>