<?php
//Испания 29
$libes = array ( 
"1"=>array("name_ru"=>"Мадрид","name_en"=>"Madrid","name_href" => "es/population-of-madrid","count" => "3 155 360","real_id" =>1,),
"2"=>array("name_ru"=>"Барселона","name_en"=>"Barcelona","name_href" => "es/population-of-barcelona","count" => "1 593 075","real_id" =>2,),
"3"=>array("name_ru"=>"Валенсия","name_en"=>"Valencia","name_href" => "es/population-of-valencia","count" => "796 549","real_id" =>3,),
"4"=>array("name_ru"=>"Севилья","name_en"=>"Sevilla","name_href" => "es/population-of-sevilla","count" => "704 154","real_id" =>4,),
"5"=>array("name_ru"=>"Сарагоса","name_en"=>"Zaragoza","name_href" => "es/population-of-zaragoza","count" => "647 373","real_id" =>5,),
"6"=>array("name_ru"=>"Малага","name_en"=>"Málaga","name_href" => "es/population-of-málaga","count" => "558 287","real_id" =>6,),
"7"=>array("name_ru"=>"Мурсия","name_en"=>"Murcia","name_href" => "es/population-of-murcia","count" => "409 810","real_id" =>7,),
"8"=>array("name_ru"=>"Пальма-де-Майорка","name_en"=>"Palma","name_href" => "es/population-of-palma","count" => "375 773","real_id" =>8,),
"9"=>array("name_ru"=>"Лас-Пальмас-де-Гран-Канария","name_en"=>"Las Palmas de Gran Canaria","name_href" => "es/population-of-las-palmas-de-gran-canaria","count" => "378 628","real_id" =>9,),
"10"=>array("name_ru"=>"Бильбао","name_en"=>"Bilbao","name_href" => "es/population-of-bilbao","count" => "353 173","real_id" =>10,),
"11"=>array("name_ru"=>"Аликанте","name_en"=>"Alicante","name_href" => "es/population-of-alicante","count" => "319 380","real_id" =>11,),
"12"=>array("name_ru"=>"Кордова","name_en"=>"Córdoba","name_href" => "es/population-of-córdoba","count" => "321 164","real_id" =>12,),
"13"=>array("name_ru"=>"Вальядолид","name_en"=>"Valladolid","name_href" => "es/population-of-valladolid","count" => "321 001","real_id" =>13,),
"14"=>array("name_ru"=>"Виго","name_en"=>"Vigo","name_href" => "es/population-of-vigo","count" => "293 725","real_id" =>14,),
"15"=>array("name_ru"=>"Хихон","name_en"=>"Gijón","name_href" => "es/population-of-gijón","count" => "273 931","real_id" =>15,),
"16"=>array("name_ru"=>"Оспиталет","name_en"=>"L’Hospitalet de Llobregat","name_href" => "es/population-of-l’hospitalet-de-llobregat","count" => "252 884","real_id" =>16,),
"17"=>array("name_ru"=>"Ла-Корунья","name_en"=>"La Coruña","name_href" => "es/population-of-la-coruña","count" => "243 349","real_id" =>17,),
"18"=>array("name_ru"=>"Гранада","name_en"=>"Granada","name_href" => "es/population-of-granada","count" => "236 982","real_id" =>18,),
"19"=>array("name_ru"=>"Витория","name_en"=>"Vitoria","name_href" => "es/population-of-vitoria","count" => "226 490","real_id" =>19,),
"20"=>array("name_ru"=>"Эльче","name_en"=>"Elche","name_href" => "es/population-of-elche","count" => "215 137","real_id" =>20,),
"21"=>array("name_ru"=>"Овьедо","name_en"=>"Oviedo","name_href" => "es/population-of-oviedo","count" => "212 174","real_id" =>21,),
"22"=>array("name_ru"=>"Санта-Крус-де-Тенерифе","name_en"=>"Santa Cruz de Tenerife","name_href" => "es/population-of-santa-cruz-de-tenerife","count" => "221 567","real_id" =>22,),
"23"=>array("name_ru"=>"Бадалона","name_en"=>"Badalona","name_href" => "es/population-of-badalona","count" => "218 553","real_id" =>23,),
"24"=>array("name_ru"=>"Картахена","name_en"=>"Cartagena","name_href" => "es/population-of-cartagena","count" => "203 945","real_id" =>24,),
"25"=>array("name_ru"=>"Террасса","name_en"=>"Tarrasa","name_href" => "es/population-of-tarrasa","count" => "194 947","real_id" =>25,),
"26"=>array("name_ru"=>"Херес-де-ла-Фронтера","name_en"=>"Jerez de la Frontera","name_href" => "es/population-of-jerez-de-la-frontera","count" => "196 275","real_id" =>26,),
"27"=>array("name_ru"=>"Сабадель","name_en"=>"Sabadell","name_href" => "es/population-of-sabadell","count" => "196 971","real_id" =>27,),
"28"=>array("name_ru"=>"Мостолес","name_en"=>"Móstoles","name_href" => "es/population-of-móstoles","count" => "204 463","real_id" =>28,),
"29"=>array("name_ru"=>"Алькала-де-Энарес","name_en"=>"Alcalá de Henares","name_href" => "es/population-of-alcalá-de-henares","count" => "197 804","real_id" =>29,),
"30"=>array("name_ru"=>"Мадрид","name_en"=>"Madrid","name_href" => "es/population-of-madrid","count" => "3 155 360","real_id" =>30,),
"31"=>array("name_ru"=>"Барселона","name_en"=>"Barcelona","name_href" => "es/population-of-barcelona","count" => "1 593 075","real_id" =>31,),
"32"=>array("name_ru"=>"Валенсия","name_en"=>"Valencia","name_href" => "es/population-of-valencia","count" => "796 549","real_id" =>32,),
"33"=>array("name_ru"=>"Севилья","name_en"=>"Sevilla","name_href" => "es/population-of-sevilla","count" => "704 154","real_id" =>33,),
"34"=>array("name_ru"=>"Сарагоса","name_en"=>"Zaragoza","name_href" => "es/population-of-zaragoza","count" => "647 373","real_id" =>34,)
);

?>