<?php
//Египет 191 
$libeg = array ( 
"1"=>array("name_ru"=>"Каир","name_en"=>"Cairo","name_href" =>"eg/population-of-cairo","count" =>"8 105 071","real_id" =>1,),
"2"=>array("name_ru"=>"Александрия","name_en"=>"Alexandria","name_href" =>"eg/population-of-alexandria","count" =>"4 388 219","real_id" =>2,),
"3"=>array("name_ru"=>"Гиза","name_en"=>"Giza","name_href" =>"eg/population-of-giza","count" =>"3 438 401","real_id" =>3,),
"4"=>array("name_ru"=>"Шубра-эль-Хейма","name_en"=>"Shubra El-kheima","name_href" =>"eg/population-of-shubra-el-kheima","count" =>"1 072 951","real_id" =>4,),
"5"=>array("name_ru"=>"Порт-Саид","name_en"=>"Port Said","name_href" =>"eg/population-of-port-said","count" =>"607 353","real_id" =>5,),
"6"=>array("name_ru"=>"Суэц","name_en"=>"Suez","name_href" =>"eg/population-of-suez","count" =>"547 352","real_id" =>6,),
"7"=>array("name_ru"=>"Луксор","name_en"=>"Luxor","name_href" =>"eg/population-of-luxor","count" =>"487 896","real_id" =>7,),
"8"=>array("name_ru"=>"Эль-Мансура","name_en"=>"Al Manşūrah","name_href" =>"eg/population-of-al-manşūrah","count" =>"480 494","real_id" =>8,),
"9"=>array("name_ru"=>"Эль-Махалла-эль-Кубра","name_en"=>"El-mahalla El-Kubra","name_href" =>"eg/population-of-el-mahalla-el-kubra","count" =>"458 297","real_id" =>9,),
"10"=>array("name_ru"=>"Танта","name_en"=>"Tanta","name_href" =>"eg/population-of-tanta","count" =>"437 793","real_id" =>10,),
"11"=>array("name_ru"=>"Асьют","name_en"=>"Assiut","name_href" =>"eg/population-of-assiut","count" =>"403 202","real_id" =>11,),
"12"=>array("name_ru"=>"Исмаилия","name_en"=>"Ismailia","name_href" =>"eg/population-of-ismailia","count" =>"352 411","real_id" =>12,),
"13"=>array("name_ru"=>"Файюм","name_en"=>"Fayoum","name_href" =>"eg/population-of-fayoum","count" =>"338 959","real_id" =>13,),
"14"=>array("name_ru"=>"Заказик","name_en"=>"Zagazig","name_href" =>"eg/population-of-zagazig","count" =>"314 331","real_id" =>14,),
"15"=>array("name_ru"=>"Думьят","name_en"=>"Damietta","name_href" =>"eg/population-of-damietta","count" =>"299 926","real_id" =>15,),
"16"=>array("name_ru"=>"Асуан","name_en"=>"Aswan","name_href" =>"eg/population-of-aswan","count" =>"281 891","real_id" =>16,),
"17"=>array("name_ru"=>"Эль-Минья","name_en"=>"El-Minya","name_href" =>"eg/population-of-el-minya","count" =>"253 767","real_id" =>17,),
"18"=>array("name_ru"=>"Даманхур","name_en"=>"Damanhur","name_href" =>"eg/population-of-damanhur","count" =>"252 017","real_id" =>18,),
"19"=>array("name_ru"=>"Бени-Суэйф","name_en"=>"Beni Suef","name_href" =>"eg/population-of-beni-suef","count" =>"225 789","real_id" =>19,),
"20"=>array("name_ru"=>"Эль-Гурдака","name_en"=>"El Ghardaka","name_href" =>"eg/population-of-el-ghardaka","count" =>"223 124","real_id" =>20,),
"21"=>array("name_ru"=>"Кена","name_en"=>"Ken","name_href" =>"eg/population-of-ken","count" =>"222 724","real_id" =>21,),
"22"=>array("name_ru"=>"Медина-Ситтат-Октобер","name_en"=>"Medina-Sittat-Oktober","name_href" =>"eg/population-of-medina-sittat-oktober","count" =>"215 650","real_id" =>22,),
"23"=>array("name_ru"=>"Сохаг","name_en"=>"Sohag","name_href" =>"eg/population-of-sohag","count" =>"197 819","real_id" =>23,),
"24"=>array("name_ru"=>"Шибин-Эль-Ком","name_en"=>"Shibin El-Kom","name_href" =>"eg/population-of-shibin-el-kom","count" =>"183 553","real_id" =>24,),
"25"=>array("name_ru"=>"Эль-Ашир-мин-Рамадан","name_en"=>"El-Ashir-min-Ramadan","name_href" =>"eg/population-of-el-ashir-min-ramadan","count" =>"167 215","real_id" =>25,),
"26"=>array("name_ru"=>"Бенха","name_en"=>"Benha","name_href" =>"eg/population-of-benha","count" =>"163 774","real_id" =>26,),
"27"=>array("name_ru"=>"Мерса-Матрух","name_en"=>"Mersa Matruh","name_href" =>"eg/population-of-mersa-matruh","count" =>"156 947","real_id" =>27,),
"28"=>array("name_ru"=>"Кафр-эш-Шейх","name_en"=>"Kafr El-Sheikh","name_href" =>"eg/population-of-kafr-el-sheikh","count" =>"156 078","real_id" =>28,),
"29"=>array("name_ru"=>"Эль-Ариш","name_en"=>"El-Arish","name_href" =>"eg/population-of-el-arish","count" =>"155 639","real_id" =>29,),
"30"=>array("name_ru"=>"Маллави","name_en"=>"Mallawi","name_href" =>"eg/population-of-mallawi","count" =>"148 327","real_id" =>30,),
"31"=>array("name_ru"=>"Бильбейс","name_en"=>"Bilbeis","name_href" =>"eg/population-of-bilbeis","count" =>"145 232","real_id" =>31,),
"32"=>array("name_ru"=>"Эдфу","name_en"=>"Edfu","name_href" =>"eg/population-of-edfu","count" =>"128 004","real_id" =>32,),
"33"=>array("name_ru"=>"Мит-Гамр","name_en"=>"Mit-Ghamr","name_href" =>"eg/population-of-mit-ghamr","count" =>"120 954","real_id" =>33,),
"34"=>array("name_ru"=>"Эль-Хавамедия","name_en"=>"El Javamedia","name_href" =>"eg/population-of-el-javamedia","count" =>"116 702","real_id" =>34,),
"35"=>array("name_ru"=>"Дисук","name_en"=>"Disuq","name_href" =>"eg/population-of-disuq","count" =>"112 625","real_id" =>35,),
"36"=>array("name_ru"=>"Кальюб","name_en"=>"Qalyub","name_href" =>"eg/population-of-qalyub","count" =>"110 156","real_id" =>36,),
"37"=>array("name_ru"=>"Абу-Кебир","name_en"=>"Abu-Kebir","name_href" =>"eg/population-of-abu-kebir","count" =>"109 448","real_id" =>37,),
"38"=>array("name_ru"=>"Ахмим","name_en"=>"Akhmim","name_href" =>"eg/population-of-akhmim","count" =>"107 608","real_id" =>38,),
"39"=>array("name_ru"=>"Гирга","name_en"=>"Girga","name_href" =>"eg/population-of-girga","count" =>"106 451","real_id" =>39,),
"40"=>array("name_ru"=>"Матарийя","name_en"=>"Malaria","name_href" =>"eg/population-of-malaria","count" =>"105 413","real_id" =>40,),
"41"=>array("name_ru"=>"Идку","name_en"=>"Idku","name_href" =>"eg/population-of-idku","count" =>"101 227","real_id" =>41,),
"42"=>array("name_ru"=>"Зифта","name_en"=>"Zifta","name_href" =>"eg/population-of-zifta","count" =>"100 671","real_id" =>42,),
"43"=>array("name_ru"=>"Миньят-эн-Наср","name_en"=>"Miniat-EN-Nasr","name_href" =>"eg/population-of-miniat-en-nasr","count" =>"99 523","real_id" =>43,),
"44"=>array("name_ru"=>"Билкас","name_en"=>"Bylkas","name_href" =>"eg/population-of-bylkas","count" =>"97 566","real_id" =>44,),
"45"=>array("name_ru"=>"Кафр-эд-Даввар","name_en"=>"Kafr ed-Dawar","name_href" =>"eg/population-of-kafr-ed-dawar","count" =>"97 200","real_id" =>45,),
"46"=>array("name_ru"=>"Самалут","name_en"=>"Samalut","name_href" =>"eg/population-of-samalut","count" =>"96 640","real_id" =>46,),
"47"=>array("name_ru"=>"Эс-Синбиллавейн","name_en"=>"Es-Senbellawein","name_href" =>"eg/population-of-es-senbellawein","count" =>"92 099","real_id" =>47,),
"48"=>array("name_ru"=>"Насер","name_en"=>"Nasser","name_href" =>"eg/population-of-nasser","count" =>"91 400","real_id" =>48,),
"49"=>array("name_ru"=>"Ашмун","name_en"=>"Aschmoun","name_href" =>"eg/population-of-aschmoun","count" =>"91 397","real_id" =>49,),
"50"=>array("name_ru"=>"Минуф","name_en"=>"Monufia","name_href" =>"eg/population-of-monufia","count" =>"91 265","real_id" =>50,),
"51"=>array("name_ru"=>"Бени-Мазар","name_en"=>"Beni-Mazar","name_href" =>"eg/population-of-beni-mazar","count" =>"90 867","real_id" =>51,),
"52"=>array("name_ru"=>"Тахта","name_en"=>"Ottoman","name_href" =>"eg/population-of-ottoman","count" =>"89 947","real_id" =>52,),
"53"=>array("name_ru"=>"Манфалут","name_en"=>"Manfalut","name_href" =>"eg/population-of-manfalut","count" =>"89 629","real_id" =>53,),
"54"=>array("name_ru"=>"Факус","name_en"=>"Focus","name_href" =>"eg/population-of-focus","count" =>"88 230","real_id" =>54,),
"55"=>array("name_ru"=>"Синнурис","name_en"=>"Sinnuris","name_href" =>"eg/population-of-sinnuris","count" =>"87 641","real_id" =>55,),
"56"=>array("name_ru"=>"Дар-эс-Салам","name_en"=>"Dar es Salaam","name_href" =>"eg/population-of-dar-es-salaam","count" =>"87 019","real_id" =>56,),
"57"=>array("name_ru"=>"Кирдаса","name_en"=>"Kerdasa","name_href" =>"eg/population-of-kerdasa","count" =>"84 516","real_id" =>57,),
"58"=>array("name_ru"=>"Магага","name_en"=>"Eldoret","name_href" =>"eg/population-of-eldoret","count" =>"81 493","real_id" =>58,),
"59"=>array("name_ru"=>"Армант","name_en"=>"Armant","name_href" =>"eg/population-of-armant","count" =>"80 962","real_id" =>59,),
"60"=>array("name_ru"=>"Дейрут","name_en"=>"Darut","name_href" =>"eg/population-of-darut","count" =>"80 684","real_id" =>60,),
"61"=>array("name_ru"=>"Эль-Манзала","name_en"=>"El-Manzala","name_href" =>"eg/population-of-el-manzala","count" =>"80 193","real_id" =>61,),
"62"=>array("name_ru"=>"Кафр-аз-Зият","name_en"=>"Kafr AZ-Ziat","name_href" =>"eg/population-of-kafr-az-ziat","count" =>"77 940","real_id" =>62,),
"63"=>array("name_ru"=>"Абу-Тиг","name_en"=>"Abu TIG","name_href" =>"eg/population-of-abu-tig","count" =>"75 355","real_id" =>63,),
"64"=>array("name_ru"=>"Эль-Кусия","name_en"=>"El-Kusiya","name_href" =>"eg/population-of-el-kusiya","count" =>"75 173","real_id" =>64,),
"65"=>array("name_ru"=>"Ком-Омбо","name_en"=>"Kom Ombo","name_href" =>"eg/population-of-kom-ombo","count" =>"75 128","real_id" =>65,),
"66"=>array("name_ru"=>"Тальха","name_en"=>"Talha","name_href" =>"eg/population-of-talha","count" =>"74 659","real_id" =>66,),
"67"=>array("name_ru"=>"Рашид","name_en"=>"Rashid","name_href" =>"eg/population-of-rashid","count" =>"73 931","real_id" =>67,),
"68"=>array("name_ru"=>"Аусим","name_en"=>"Ausim","name_href" =>"eg/population-of-ausim","count" =>"73 835","real_id" =>68,),
"69"=>array("name_ru"=>"Эль-Манша","name_en"=>"El-Mansha","name_href" =>"eg/population-of-el-mansha","count" =>"73 739","real_id" =>69,),
"70"=>array("name_ru"=>"Абнуб","name_en"=>"Abnub","name_href" =>"eg/population-of-abnub","count" =>"71 868","real_id" =>70,),
"71"=>array("name_ru"=>"Бияла","name_en"=>"Biala","name_href" =>"eg/population-of-biala","count" =>"71 351","real_id" =>71,),
"72"=>array("name_ru"=>"Эль-Фашн","name_en"=>"El Fashn","name_href" =>"eg/population-of-el-fashn","count" =>"71 249","real_id" =>72,),
"73"=>array("name_ru"=>"Эль-Канатир-эль-Хейрия","name_en"=>"El Kanater El Haria","name_href" =>"eg/population-of-el-kanater-el-haria","count" =>"70 971","real_id" =>73,),
"74"=>array("name_ru"=>"Тима","name_en"=>"Tim","name_href" =>"eg/population-of-tim","count" =>"70 931","real_id" =>74,),
"75"=>array("name_ru"=>"Эсна","name_en"=>"Esna","name_href" =>"eg/population-of-esna","count" =>"70 920","real_id" =>75,),
"76"=>array("name_ru"=>"Эль-Курейн","name_en"=>"El Kuran","name_href" =>"eg/population-of-el-kuran","count" =>"69 763","real_id" =>76,),
"77"=>array("name_ru"=>"Эль-Бадрашейн","name_en"=>"El Badrashin","name_href" =>"eg/population-of-el-badrashin","count" =>"67 690","real_id" =>77,),
"78"=>array("name_ru"=>"Фува","name_en"=>"Fuwa","name_href" =>"eg/population-of-fuwa","count" =>"66 836","real_id" =>78,),
"79"=>array("name_ru"=>"Эль-Харга","name_en"=>"El Kharga","name_href" =>"eg/population-of-el-kharga","count" =>"65 486","real_id" =>79,),
"80"=>array("name_ru"=>"Эль-Гамалия","name_en"=>"El-Gamal","name_href" =>"eg/population-of-el-gamal","count" =>"65 336","real_id" =>80,),
"81"=>array("name_ru"=>"Минья-эль-Камх","name_en"=>"Minya-al-Qamhah","name_href" =>"eg/population-of-minya-al-qamhah","count" =>"64 851","real_id" =>81,),
"82"=>array("name_ru"=>"Дикирнис","name_en"=>"Dikirnis","name_href" =>"eg/population-of-dikirnis","count" =>"64 391","real_id" =>82,),
"83"=>array("name_ru"=>"Кус","name_en"=>"Kus","name_href" =>"eg/population-of-kus","count" =>"64 320","real_id" =>83,),
"84"=>array("name_ru"=>"Эль-Ханка","name_en"=>"El-Khanka","name_href" =>"eg/population-of-el-khanka","count" =>"63 598","real_id" =>84,),
"85"=>array("name_ru"=>"Ибшавей","name_en"=>"Ibshaway","name_href" =>"eg/population-of-ibshaway","count" =>"60 989","real_id" =>85,),
"86"=>array("name_ru"=>"Биба","name_en"=>"Biba","name_href" =>"eg/population-of-biba","count" =>"60 970","real_id" =>86,),
"87"=>array("name_ru"=>"Саманнуд","name_en"=>"Samannud","name_href" =>"eg/population-of-samannud","count" =>"60 620","real_id" =>87,),
"88"=>array("name_ru"=>"Абу-Куркас","name_en"=>"Abu Kurkas","name_href" =>"eg/population-of-abu-kurkas","count" =>"60 506","real_id" =>88,),
"89"=>array("name_ru"=>"Кафр-Саад","name_en"=>"Kafr Saad","name_href" =>"eg/population-of-kafr-saad","count" =>"57 909","real_id" =>89,),
"90"=>array("name_ru"=>"Диярб-Нигм","name_en"=>"Derb-Nigm","name_href" =>"eg/population-of-derb-nigm","count" =>"57 549","real_id" =>90,),
"91"=>array("name_ru"=>"Шибин-эль-Канатир","name_en"=>"Shibin El-Kanatir","name_href" =>"eg/population-of-shibin-el-kanatir","count" =>"57 456","real_id" =>91,),
"92"=>array("name_ru"=>"Ширбин","name_en"=>"Serbin","name_href" =>"eg/population-of-serbin","count" =>"57 225","real_id" =>92,),
"93"=>array("name_ru"=>"Эль-Хамуль","name_en"=>"El Hamoul","name_href" =>"eg/population-of-el-hamoul","count" =>"56 479","real_id" =>93,),
"94"=>array("name_ru"=>"Сирс-эль-Лайяна","name_en"=>"Sirs-El-Layan","name_href" =>"eg/population-of-sirs-el-layan","count" =>"56 061","real_id" =>94,),
"95"=>array("name_ru"=>"Дишна","name_en"=>"Dieschen","name_href" =>"eg/population-of-dieschen","count" =>"55 630","real_id" =>95,),
"96"=>array("name_ru"=>"Басьюн","name_en"=>"Basun","name_href" =>"eg/population-of-basun","count" =>"54 591","real_id" =>96,),
"97"=>array("name_ru"=>"Фарискур","name_en"=>"Farskur","name_href" =>"eg/population-of-farskur","count" =>"54 360","real_id" =>97,),
"98"=>array("name_ru"=>"Эль-Кантара","name_en"=>"El Qantara","name_href" =>"eg/population-of-el-qantara","count" =>"54 199","real_id" =>98,),
"99"=>array("name_ru"=>"Фаршут","name_en"=>"Farshut","name_href" =>"eg/population-of-farshut","count" =>"53 818","real_id" =>99,),
"100"=>array("name_ru"=>"Шарм-эш-Шейх","name_en"=>"Sharm El-Sheikh","name_href" =>"eg/population-of-sharm-el-sheikh","count" =>"53 658","real_id" =>100,),
"101"=>array("name_ru"=>"Тамия","name_en"=>"Tamiya","name_href" =>"eg/population-of-tamiya","count" =>"53 073","real_id" =>101,),
"102"=>array("name_ru"=>"Эш-Шухада","name_en"=>"Esh-Shuhada","name_href" =>"eg/population-of-esh-shuhada","count" =>"52 957","real_id" =>102,),
"103"=>array("name_ru"=>"Маштуль-эс-Сук","name_en"=>"Mastel es Souk","name_href" =>"eg/population-of-mastel-es-souk","count" =>"52 957","real_id" =>103,),
"104"=>array("name_ru"=>"Эль-Ганайим","name_en"=>"El Ghanayim","name_href" =>"eg/population-of-el-ghanayim","count" =>"51 904","real_id" =>104,),
"105"=>array("name_ru"=>"Тала","name_en"=>"Tala","name_href" =>"eg/population-of-tala","count" =>"51 469","real_id" =>105,),
"106"=>array("name_ru"=>"Матаи","name_en"=>"Matai","name_href" =>"eg/population-of-matai","count" =>"50 806","real_id" =>106,),
"107"=>array("name_ru"=>"Итса","name_en"=>"Its","name_href" =>"eg/population-of-its","count" =>"50 578","real_id" =>107,),
"108"=>array("name_ru"=>"Мадинат-эс-Садат","name_en"=>"Madinat-es-Sadat","name_href" =>"eg/population-of-madinat-es-sadat","count" =>"50 380","real_id" =>108,),
"109"=>array("name_ru"=>"Эс-Сафф","name_en"=>"Es-Saff","name_href" =>"eg/population-of-es-saff","count" =>"50 237","real_id" =>109,),
"110"=>array("name_ru"=>"Гахина","name_en"=>"Gachina","name_href" =>"eg/population-of-gachina","count" =>"49 897","real_id" =>110,),
"111"=>array("name_ru"=>"Эль-Бальяна","name_en"=>"El Balyana","name_href" =>"eg/population-of-el-balyana","count" =>"49 870","real_id" =>111,),
"112"=>array("name_ru"=>"Наг-Хаммади","name_en"=>"Nag Hammadi","name_href" =>"eg/population-of-nag-hammadi","count" =>"49 829","real_id" =>112,),
"113"=>array("name_ru"=>"Абу-эль-Матамир","name_en"=>"Abu-El-Matamir","name_href" =>"eg/population-of-abu-el-matamir","count" =>"48 424","real_id" =>113,),
"114"=>array("name_ru"=>"Кувейсина","name_en"=>"Quwaysina","name_href" =>"eg/population-of-quwaysina","count" =>"48 222","real_id" =>114,),
"115"=>array("name_ru"=>"Хихья","name_en"=>"Hiha","name_href" =>"eg/population-of-hiha","count" =>"47 761","real_id" =>115,),
"116"=>array("name_ru"=>"Эль-Убур","name_en"=>"Al-Ubur","name_href" =>"eg/population-of-al-ubur","count" =>"47 715","real_id" =>116,),
"117"=>array("name_ru"=>"Эль-Хаммам","name_en"=>"El Hammam","name_href" =>"eg/population-of-el-hammam","count" =>"46 841","real_id" =>117,),
"118"=>array("name_ru"=>"Сиди-Салим","name_en"=>"Sidi Salim","name_href" =>"eg/population-of-sidi-salim","count" =>"46 283","real_id" =>118,),
"119"=>array("name_ru"=>"Эль-Бадари","name_en"=>"El-Badari","name_href" =>"eg/population-of-el-badari","count" =>"45 508","real_id" =>119,),
"120"=>array("name_ru"=>"Эль-Багур","name_en"=>"El-Bagur","name_href" =>"eg/population-of-el-bagur","count" =>"45 394","real_id" =>120,),
"121"=>array("name_ru"=>"Эль-Канаят","name_en"=>"El Kanat","name_href" =>"eg/population-of-el-kanat","count" =>"45 221","real_id" =>121,),
"122"=>array("name_ru"=>"Эд-Дилингат","name_en"=>"Ed-Dilingat","name_href" =>"eg/population-of-ed-dilingat","count" =>"44 813","real_id" =>122,),
"123"=>array("name_ru"=>"Эт-Тель-эль-Кебир","name_en"=>"At tel-El-Kebir","name_href" =>"eg/population-of-at-tel-el-kebir","count" =>"44 738","real_id" =>123,),
"124"=>array("name_ru"=>"Эль-Кусейр","name_en"=>"El Quseir","name_href" =>"eg/population-of-el-quseir","count" =>"44 441","real_id" =>124,),
"125"=>array("name_ru"=>"Абу-Хуммус","name_en"=>"Abu Hummus","name_href" =>"eg/population-of-abu-hummus","count" =>"44 054","real_id" =>125,),
"126"=>array("name_ru"=>"Дейр-Мавас","name_en"=>"Deir-Mavas","name_href" =>"eg/population-of-deir-mavas","count" =>"43 653","real_id" =>126,),
"127"=>array("name_ru"=>"Тух","name_en"=>"Tuh","name_href" =>"eg/population-of-tuh","count" =>"42 803","real_id" =>127,),
"128"=>array("name_ru"=>"Итай-эль-Баруд","name_en"=>"Itai El Barud","name_href" =>"eg/population-of-itai-el-barud","count" =>"42 733","real_id" =>128,),
"129"=>array("name_ru"=>"Балтим","name_en"=>"Baltim","name_href" =>"eg/population-of-baltim","count" =>"42 460","real_id" =>129,),
"130"=>array("name_ru"=>"Хуш-Иса","name_en"=>"Cush-ISA","name_href" =>"eg/population-of-cush-isa","count" =>"42 186","real_id" =>130,),
"131"=>array("name_ru"=>"Абу-Хаммад","name_en"=>"Abu-Hammad","name_href" =>"eg/population-of-abu-hammad","count" =>"41 925","real_id" =>131,),
"132"=>array("name_ru"=>"Эль-Марага","name_en"=>"El-Maragha","name_href" =>"eg/population-of-el-maragha","count" =>"41 296","real_id" =>132,),
"133"=>array("name_ru"=>"Набару","name_en"=>"The Nabarro","name_href" =>"eg/population-of-the-nabarro","count" =>"41 133","real_id" =>133,),
"134"=>array("name_ru"=>"Васта","name_en"=>"Vasta","name_href" =>"eg/population-of-vasta","count" =>"40 941","real_id" =>134,),
"135"=>array("name_ru"=>"Сафага","name_en"=>"Safaga","name_href" =>"eg/population-of-safaga","count" =>"40 903","real_id" =>135,),
"136"=>array("name_ru"=>"Сумуста","name_en"=>"Sumusţā","name_href" =>"eg/population-of-sumusţā","count" =>"40 735","real_id" =>136,),
"137"=>array("name_ru"=>"Дарау","name_en"=>"Draw","name_href" =>"eg/population-of-draw","count" =>"40 709","real_id" =>137,),
"138"=>array("name_ru"=>"Эз-Зарка","name_en"=>"Zarka","name_href" =>"eg/population-of-zarka","count" =>"39 898","real_id" =>138,),
"139"=>array("name_ru"=>"Каллин","name_en"=>"Callen","name_href" =>"eg/population-of-callen","count" =>"39 889","real_id" =>139,),
"140"=>array("name_ru"=>"Ихнасия","name_en"=>"Ignacia","name_href" =>"eg/population-of-ignacia","count" =>"39 465","real_id" =>140,),
"141"=>array("name_ru"=>"Ком-Хамада","name_en"=>"Kom-Hamada","name_href" =>"eg/population-of-kom-hamada","count" =>"38 345","real_id" =>141,),
"142"=>array("name_ru"=>"Рас-Гариб","name_en"=>"Gharib","name_href" =>"eg/population-of-gharib","count" =>"38 312","real_id" =>142,),
"143"=>array("name_ru"=>"Биркат-эс-Саба","name_en"=>"Birkat-es-Saba","name_href" =>"eg/population-of-birkat-es-saba","count" =>"35 883","real_id" =>143,),
"144"=>array("name_ru"=>"Эль-Айят","name_en"=>"El Ayyatu","name_href" =>"eg/population-of-el-ayyatu","count" =>"35 267","real_id" =>144,),
"145"=>array("name_ru"=>"Сахиль-Салим","name_en"=>"Sahil Salim","name_href" =>"eg/population-of-sahil-salim","count" =>"35 114","real_id" =>145,),
"146"=>array("name_ru"=>"Эль-Хусейния","name_en"=>"El-Hussein","name_href" =>"eg/population-of-el-hussein","count" =>"34 106","real_id" =>146,),
"147"=>array("name_ru"=>"Рафах","name_en"=>"Rafah","name_href" =>"eg/population-of-rafah","count" =>"34 055","real_id" =>147,),
"148"=>array("name_ru"=>"Эс-Санта","name_en"=>"Es-Santa","name_href" =>"eg/population-of-es-santa","count" =>"33 975","real_id" =>148,),
"149"=>array("name_ru"=>"Эль-Ибрахимия","name_en"=>"El Ibrahimia","name_href" =>"eg/population-of-el-ibrahimia","count" =>"33 405","real_id" =>149,),
"150"=>array("name_ru"=>"Мит-Сильсиль","name_en"=>"Mit-Silsil","name_href" =>"eg/population-of-mit-silsil","count" =>"32 574","real_id" =>150,),
"151"=>array("name_ru"=>"Эль-Махмудия","name_en"=>"El-Mahmudia","name_href" =>"eg/population-of-el-mahmudia","count" =>"31 867","real_id" =>151,),
"152"=>array("name_ru"=>"Бени-Убейд","name_en"=>"Beni Obaid","name_href" =>"eg/population-of-beni-obaid","count" =>"31 643","real_id" =>152,),
"153"=>array("name_ru"=>"Эр-Рахмания","name_en"=>"Er-Rahmaniya","name_href" =>"eg/population-of-er-rahmaniya","count" =>"31 337","real_id" =>153,),
"154"=>array("name_ru"=>"Кафр-Сакр","name_en"=>"Kafr Saqr","name_href" =>"eg/population-of-kafr-saqr","count" =>"30 717","real_id" =>154,),
"155"=>array("name_ru"=>"Шубра-Хайт","name_en"=>"Shubra Hythe","name_href" =>"eg/population-of-shubra-hythe","count" =>"29 560","real_id" =>155,),
"156"=>array("name_ru"=>"Эль-Вакф","name_en"=>"El-Waqf","name_href" =>"eg/population-of-el-waqf","count" =>"29 468","real_id" =>156,),
"157"=>array("name_ru"=>"Мутубис","name_en"=>"Mucous","name_href" =>"eg/population-of-mucous","count" =>"29 394","real_id" =>157,),
"158"=>array("name_ru"=>"Каха","name_en"=>"Kakha","name_href" =>"eg/population-of-kakha","count" =>"29 007","real_id" =>158,),
"159"=>array("name_ru"=>"Эт-Тур","name_en"=>"Et-Tur","name_href" =>"eg/population-of-et-tur","count" =>"28 276","real_id" =>159,),
"160"=>array("name_ru"=>"Новый Думьят","name_en"=>"New Damietta","name_href" =>"eg/population-of-new-damietta","count" =>"27 522","real_id" =>160,),
"161"=>array("name_ru"=>"Кутур","name_en"=>"Kutur","name_href" =>"eg/population-of-kutur","count" =>"25 793","real_id" =>161,),
"162"=>array("name_ru"=>"Кафр-Шукр","name_en"=>"Kafr Shukr","name_href" =>"eg/population-of-kafr-shukr","count" =>"25 406","real_id" =>162,),
"163"=>array("name_ru"=>"Сиди-Баррани","name_en"=>"Sidi Barrani","name_href" =>"eg/population-of-sidi-barrani","count" =>"24 271","real_id" =>163,),
"164"=>array("name_ru"=>"Файид","name_en"=>"Fayed","name_href" =>"eg/population-of-fayed","count" =>"23 286","real_id" =>164,),
"165"=>array("name_ru"=>"Сакульта","name_en"=>"Sakulta","name_href" =>"eg/population-of-sakulta","count" =>"23 082","real_id" =>165,),
"166"=>array("name_ru"=>"Ауляд-Сакр","name_en"=>"Awlad-Sakr","name_href" =>"eg/population-of-awlad-sakr","count" =>"22 916","real_id" =>166,),
"167"=>array("name_ru"=>"Кифт","name_en"=>"Kieft","name_href" =>"eg/population-of-kieft","count" =>"22 846","real_id" =>167,),
"168"=>array("name_ru"=>"Бадр","name_en"=>"Badr","name_href" =>"eg/population-of-badr","count" =>"22 622","real_id" =>168,),
"169"=>array("name_ru"=>"Накада","name_en"=>"Nakada","name_href" =>"eg/population-of-nakada","count" =>"22 575","real_id" =>169,),
"170"=>array("name_ru"=>"Судфа","name_en"=>"Sudha","name_href" =>"eg/population-of-sudha","count" =>"22 443","real_id" =>170,),
"171"=>array("name_ru"=>"Эль-Дахла","name_en"=>"El-Dakhla","name_href" =>"eg/population-of-el-dakhla","count" =>"22 260","real_id" =>171,),
"172"=>array("name_ru"=>"Эр-Рахмания","name_en"=>"Er-Rahmaniya","name_href" =>"eg/population-of-er-rahmaniya","count" =>"21 081","real_id" =>172,),
"173"=>array("name_ru"=>"Эс-Салихия-эль-Гедида","name_en"=>"Es-Salihia El Gedida","name_href" =>"eg/population-of-es-salihia-el-gedida","count" =>"20 412","real_id" =>173,),
"174"=>array("name_ru"=>"Эш-Шейх-Зауид","name_en"=>"Ash-Sheikh-Sawed","name_href" =>"eg/population-of-ash-sheikh-sawed","count" =>"19 684","real_id" =>174,),
"175"=>array("name_ru"=>"Эр-Рияд","name_en"=>"Riyadh","name_href" =>"eg/population-of-riyadh","count" =>"19 344","real_id" =>175,),
"176"=>array("name_ru"=>"Эд-Дабаа","name_en"=>"Ed-Daba","name_href" =>"eg/population-of-ed-daba","count" =>"18 715","real_id" =>176,),
"177"=>array("name_ru"=>"Сива","name_en"=>"Siwa","name_href" =>"eg/population-of-siwa","count" =>"18 625","real_id" =>177,),
"178"=>array("name_ru"=>"Эль-Идва","name_en"=>"El-Idva","name_href" =>"eg/population-of-el-idva","count" =>"17 110","real_id" =>178,),
"179"=>array("name_ru"=>"Ага","name_en"=>"Yeah","name_href" =>"eg/population-of-yeah","count" =>"17 055","real_id" =>179,),
"180"=>array("name_ru"=>"Юсуф-эс-Саддик","name_en"=>"Yusuf-es-Saddik","name_href" =>"eg/population-of-yusuf-es-saddik","count" =>"16 536","real_id" =>180,),
"181"=>array("name_ru"=>"Бир-эль-Абд","name_en"=>"Bir-El-Abd","name_href" =>"eg/population-of-bir-el-abd","count" =>"15 574","real_id" =>181,),
"182"=>array("name_ru"=>"Атфих","name_en"=>"Attic","name_href" =>"eg/population-of-attic","count" =>"15 158","real_id" =>182,),
"183"=>array("name_ru"=>"Эль-Фатх","name_en"=>"El-Fatah","name_href" =>"eg/population-of-el-fatah","count" =>"14 778","real_id" =>183,),
"184"=>array("name_ru"=>"Тимай-эль-Амдид","name_en"=>"Timai El Emdid","name_href" =>"eg/population-of-timai-el-emdid","count" =>"14 713","real_id" =>184,),
"185"=>array("name_ru"=>"Абу-Тишт","name_en"=>"Abu Tisht","name_href" =>"eg/population-of-abu-tisht","count" =>"13 977","real_id" =>185,),
"186"=>array("name_ru"=>"Абу-Рудейс","name_en"=>"Abu-Rudeis","name_href" =>"eg/population-of-abu-rudeis","count" =>"13 150","real_id" =>186,),
"187"=>array("name_ru"=>"Эс-Саллум","name_en"=>"Es-Salloum","name_href" =>"eg/population-of-es-salloum","count" =>"12 722","real_id" =>187,),
"188"=>array("name_ru"=>"Имбаба","name_en"=>"Imbaba","name_href" =>"eg/population-of-imbaba","count" =>"12 671","real_id" =>188,),
"189"=>array("name_ru"=>"Рас-аль-Барр","name_en"=>"RAS al-Barr","name_href" =>"eg/population-of-ras-al-barr","count" =>"12 635","real_id" =>189,),
"190"=>array("name_ru"=>"Шалатин","name_en"=>"Salatin","name_href" =>"eg/population-of-salatin","count" =>"11 703","real_id" =>190,),
"191"=>array("name_ru"=>"Эль-Ваха-эль-Бахария","name_en"=>"El-Waha El-Bahariya","name_href" =>"eg/population-of-el-waha-el-bahariya","count" =>"11 176","real_id" =>191,),
"192"=>array("name_ru"=>"Каир","name_en"=>"Cairo","name_href" =>"eg/population-of-cairo","count" =>"8 105 071","real_id" =>192,),
"193"=>array("name_ru"=>"Александрия","name_en"=>"Alexandria","name_href" =>"eg/population-of-alexandria","count" =>"4 388 219","real_id" =>193,),
"194"=>array("name_ru"=>"Гиза","name_en"=>"Giza","name_href" =>"eg/population-of-giza","count" =>"3 438 401","real_id" =>194,),
"195"=>array("name_ru"=>"Шубра-эль-Хейма","name_en"=>"Shubra El-kheima","name_href" =>"eg/population-of-shubra-el-kheima","count" =>"1 072 951","real_id" =>195,),
"196"=>array("name_ru"=>"Порт-Саид","name_en"=>"Port Said","name_href" =>"eg/population-of-port-said","count" =>"607 353","real_id" =>196,)
);

?>