<?php
//Эстония 47 
$libee = array ( 
"1"=>array("name_ru"=>"Таллин","name_en"=>"Tallinn","name_href" => "ee/population-of-tallinn","count" => "395 392","real_id" =>1,),
"2"=>array("name_ru"=>"Тарту","name_en"=>"Tartu","name_href" => "ee/population-of-tartu","count" => "97 117","real_id" =>2,),
"3"=>array("name_ru"=>"Нарва","name_en"=>"Narva","name_href" => "ee/population-of-narva","count" => "57 650","real_id" =>3,),
"4"=>array("name_ru"=>"Пярну","name_en"=>"Parnu","name_href" => "ee/population-of-parnu","count" => "39 276","real_id" =>4,),
"5"=>array("name_ru"=>"Кохтла-Ярве","name_en"=>"Kohtla-Jarve","name_href" => "ee/population-of-kohtla-jarve","count" => "36 377","real_id" =>5,),
"6"=>array("name_ru"=>"Маарду","name_en"=>"Maardu","name_href" => "ee/population-of-maardu","count" => "17 292","real_id" =>6,),
"7"=>array("name_ru"=>"Вильянди","name_en"=>"Viljandi","name_href" => "ee/population-of-viljandi","count" => "17 215","real_id" =>7,),
"8"=>array("name_ru"=>"Раквере","name_en"=>"Rakvere","name_href" => "ee/population-of-rakvere","count" => "15 102","real_id" =>8,),
"9"=>array("name_ru"=>"Силламяэ","name_en"=>"Sillamae","name_href" => "ee/population-of-sillamae","count" => "13 942","real_id" =>9,),
"10"=>array("name_ru"=>"Курессааре","name_en"=>"Kuressaare","name_href" => "ee/population-of-kuressaare","count" => "12 968","real_id" =>10,),
"11"=>array("name_ru"=>"Выру","name_en"=>"Võru","name_href" => "ee/population-of-võru","count" => "12 379","real_id" =>11,),
"12"=>array("name_ru"=>"Валга","name_en"=>"Valga","name_href" => "ee/population-of-valga","count" => "12 030","real_id" =>12,),
"13"=>array("name_ru"=>"Йыхви","name_en"=>"Jõhvi","name_href" => "ee/population-of-jõhvi","count" => "10 612","real_id" =>13,),
"14"=>array("name_ru"=>"Хаапсалу","name_en"=>"Haapsalu","name_href" => "ee/population-of-haapsalu","count" => "10 146","real_id" =>14,),
"15"=>array("name_ru"=>"Кейла","name_en"=>"Kayla","name_href" => "ee/population-of-kayla","count" => "9 683","real_id" =>15,),
"16"=>array("name_ru"=>"Пайде","name_en"=>"Paid","name_href" => "ee/population-of-paid","count" => "8 053","real_id" =>16,),
"17"=>array("name_ru"=>"Тапа","name_en"=>"Thapa","name_href" => "ee/population-of-thapa","count" => "5 766","real_id" =>17,),
"18"=>array("name_ru"=>"Пылва","name_en"=>"Polva","name_href" => "ee/population-of-polva","count" => "5 678","real_id" =>18,),
"19"=>array("name_ru"=>"Сауэ","name_en"=>"Saue","name_href" => "ee/population-of-saue","count" => "5 528","real_id" =>19,),
"20"=>array("name_ru"=>"Элва","name_en"=>"Elva","name_href" => "ee/population-of-elva","count" => "5 499","real_id" =>20,),
"21"=>array("name_ru"=>"Кивиыли","name_en"=>"Kiviõli","name_href" => "ee/population-of-kiviõli","count" => "5 485","real_id" =>21,),
"22"=>array("name_ru"=>"Йыгева","name_en"=>"Jõgeva","name_href" => "ee/population-of-jõgeva","count" => "5 406","real_id" =>22,),
"23"=>array("name_ru"=>"Тюри","name_en"=>"Thury","name_href" => "ee/population-of-thury","count" => "5 292","real_id" =>23,),
"24"=>array("name_ru"=>"Рапла","name_en"=>"Rapla","name_href" => "ee/population-of-rapla","count" => "5 182","real_id" =>24,),
"25"=>array("name_ru"=>"Пылтсамаа","name_en"=>"Põltsamaa","name_href" => "ee/population-of-põltsamaa","count" => "4 107","real_id" =>25,),
"26"=>array("name_ru"=>"Синди","name_en"=>"Cindy","name_href" => "ee/population-of-cindy","count" => "4 060","real_id" =>26,),
"27"=>array("name_ru"=>"Палдиски","name_en"=>"Paldiski","name_href" => "ee/population-of-paldiski","count" => "4 000","real_id" =>27,),
"28"=>array("name_ru"=>"Кунда","name_en"=>"Kunda","name_href" => "ee/population-of-kunda","count" => "3 332","real_id" =>28,),
"29"=>array("name_ru"=>"Кярдла","name_en"=>"Kärdla","name_href" => "ee/population-of-kärdla","count" => "3 000","real_id" =>29,),
"30"=>array("name_ru"=>"Кехра","name_en"=>"Kehra","name_href" => "ee/population-of-kehra","count" => "2 797","real_id" =>30,),
"31"=>array("name_ru"=>"Тырва","name_en"=>"Tõrva","name_href" => "ee/population-of-tõrva","count" => "2 660","real_id" =>31,),
"32"=>array("name_ru"=>"Локса","name_en"=>"Loksa","name_href" => "ee/population-of-loksa","count" => "2 636","real_id" =>32,),
"33"=>array("name_ru"=>"Нарва-Йыэсуу","name_en"=>"Narva-Jõesuu","name_href" => "ee/population-of-narva-jõesuu","count" => "2 569","real_id" =>33,),
"34"=>array("name_ru"=>"Ряпина","name_en"=>"Räpina","name_href" => "ee/population-of-räpina","count" => "2 443","real_id" =>34,),
"35"=>array("name_ru"=>"Тамсалу","name_en"=>"Tamsalu","name_href" => "ee/population-of-tamsalu","count" => "2 168","real_id" =>35,),
"36"=>array("name_ru"=>"Отепя","name_en"=>"Otepaa","name_href" => "ee/population-of-otepaa","count" => "1 916","real_id" =>36,),
"37"=>array("name_ru"=>"Килинги-Нымме","name_en"=>"Kilingi-Nõmme","name_href" => "ee/population-of-kilingi-nõmme","count" => "1 709","real_id" =>37,),
"38"=>array("name_ru"=>"Каркси-Нуйа","name_en"=>"Karksi-Nuia","name_href" => "ee/population-of-karksi-nuia","count" => "1 536","real_id" =>38,),
"39"=>array("name_ru"=>"Антсла","name_en"=>"Antsla","name_href" => "ee/population-of-antsla","count" => "1 364","real_id" =>39,),
"40"=>array("name_ru"=>"Муствеэ","name_en"=>"Mustvee","name_href" => "ee/population-of-mustvee","count" => "1 339","real_id" =>40,),
"41"=>array("name_ru"=>"Лихула","name_en"=>"Lihula","name_href" => "ee/population-of-lihula","count" => "1 310","real_id" =>41,),
"42"=>array("name_ru"=>"Выхма","name_en"=>"Võhma","name_href" => "ee/population-of-võhma","count" => "1 271","real_id" =>42,),
"43"=>array("name_ru"=>"Абья-Палуоя","name_en"=>"Abja-Paluoja","name_href" => "ee/population-of-abja-paluoja","count" => "1 050","real_id" =>43,),
"44"=>array("name_ru"=>"Сууре-Яани","name_en"=>"Suure-Jaani","name_href" => "ee/population-of-suure-jaani","count" => "1 026","real_id" =>44,),
"45"=>array("name_ru"=>"Пюсси","name_en"=>"Püssi","name_href" => "ee/population-of-püssi","count" => "1 007","real_id" =>45,),
"46"=>array("name_ru"=>"Калласте","name_en"=>"Kallaste","name_href" => "ee/population-of-kallaste","count" => "814","real_id" =>46,),
"47"=>array("name_ru"=>"Мыйзакюла","name_en"=>"Mõisaküla","name_href" => "ee/population-of-mõisaküla","count" => "813","real_id" =>47,),
"48"=>array("name_ru"=>"Таллин","name_en"=>"Tallinn","name_href" => "ee/population-of-tallinn","count" => "395 392","real_id" =>48,),
"49"=>array("name_ru"=>"Тарту","name_en"=>"Tartu","name_href" => "ee/population-of-tartu","count" => "97 117","real_id" =>49,),
"50"=>array("name_ru"=>"Нарва","name_en"=>"Narva","name_href" => "ee/population-of-narva","count" => "57 650","real_id" =>50,),
"51"=>array("name_ru"=>"Пярну","name_en"=>"Parnu","name_href" => "ee/population-of-parnu","count" => "39 276","real_id" =>51,),
"52"=>array("name_ru"=>"Кохтла-Ярве","name_en"=>"Kohtla-Jarve","name_href" => "ee/population-of-kohtla-jarve","count" => "36 377","real_id" =>52,)
);

?>