<?php
//Франция 288 
$libfr = array ( 
"1"=>array("name_ru"=>"Париж","name_en"=>"Paris","name_href" => "fr/population-of-paris","count" => "2 240 621","real_id" =>1,),
"2"=>array("name_ru"=>"Марсель","name_en"=>"Marseilles","name_href" => "fr/population-of-marseilles","count" => "852 516","real_id" =>2,),
"3"=>array("name_ru"=>"Лион","name_en"=>"Lyon","name_href" => "fr/population-of-lyon","count" => "496 343","real_id" =>3,),
"4"=>array("name_ru"=>"Тулуза","name_en"=>"Toulouse","name_href" => "fr/population-of-toulouse","count" => "453 317","real_id" =>4,),
"5"=>array("name_ru"=>"Ницца","name_en"=>"Nice","name_href" => "fr/population-of-nice","count" => "343 629","real_id" =>5,),
"6"=>array("name_ru"=>"Нант","name_en"=>"Nantes","name_href" => "fr/population-of-nantes","count" => "291 604","real_id" =>6,),
"7"=>array("name_ru"=>"Страсбург","name_en"=>"Strasbourg","name_href" => "fr/population-of-strasbourg","count" => "274 394","real_id" =>7,),
"8"=>array("name_ru"=>"Монпелье","name_en"=>"Montpellier","name_href" => "fr/population-of-montpellier","count" => "268 456","real_id" =>8,),
"9"=>array("name_ru"=>"Бордо","name_en"=>"Bordeaux","name_href" => "fr/population-of-bordeaux","count" => "241 287","real_id" =>9,),
"10"=>array("name_ru"=>"Лилль ","name_en"=>"Lille","name_href" => "fr/population-of-lille","count" => "228 652","real_id" =>10,),
"11"=>array("name_ru"=>"Ренн","name_en"=>"Rennes","name_href" => "fr/population-of-rennes","count" => "209 860","real_id" =>11,),
"12"=>array("name_ru"=>"Реймс","name_en"=>"Reims","name_href" => "fr/population-of-reims","count" => "181 893","real_id" =>12,),
"13"=>array("name_ru"=>"Гавр","name_en"=>"Le Havre","name_href" => "fr/population-of-le-havre","count" => "173 142","real_id" =>13,),
"14"=>array("name_ru"=>"Сент-Этьен","name_en"=>"Saint-Etienne","name_href" => "fr/population-of-saint-etienne","count" => "171 483","real_id" =>14,),
"15"=>array("name_ru"=>"Тулон","name_en"=>"Toulon","name_href" => "fr/population-of-toulon","count" => "164 899","real_id" =>15,),
"16"=>array("name_ru"=>"Гренобль","name_en"=>"Grenoble","name_href" => "fr/population-of-grenoble","count" => "158 346","real_id" =>16,),
"17"=>array("name_ru"=>"Дижон","name_en"=>"Dijon","name_href" => "fr/population-of-dijon","count" => "152 071","real_id" =>17,),
"18"=>array("name_ru"=>"Анжер","name_en"=>"Angers","name_href" => "fr/population-of-angers","count" => "149 017","real_id" =>18,),
"19"=>array("name_ru"=>"Ним","name_en"=>"Nîmes","name_href" => "fr/population-of-nîmes","count" => "146 709","real_id" =>19,),
"20"=>array("name_ru"=>"Виллёрба́нн","name_en"=>"Willerbanne","name_href" => "fr/population-of-willerbanne","count" => "146 282","real_id" =>20,),
"21"=>array("name_ru"=>"Сен-Дени","name_en"=>"Saint-Denis","name_href" => "fr/population-of-saint-denis","count" => "145 238","real_id" =>21,),
"22"=>array("name_ru"=>"Ле-Ман","name_en"=>"Le Mans","name_href" => "fr/population-of-le-mans","count" => "143 599","real_id" =>22,),
"23"=>array("name_ru"=>"Клермон-Ферран","name_en"=>"Clermont-Ferrand","name_href" => "fr/population-of-clermont-ferrand","count" => "141 569","real_id" =>23,),
"24"=>array("name_ru"=>"Экс-ан-Прованс","name_en"=>"Aix-en-Provence","name_href" => "fr/population-of-aix-en-provence","count" => "141 148","real_id" =>24,),
"25"=>array("name_ru"=>"Брест","name_en"=>"Brest","name_href" => "fr/population-of-brest","count" => "139 676","real_id" =>25,),
"26"=>array("name_ru"=>"Лимож","name_en"=>"Limoges","name_href" => "fr/population-of-limoges","count" => "136 221","real_id" =>26,),
"27"=>array("name_ru"=>"Тур","name_en"=>"Tour","name_href" => "fr/population-of-tour","count" => "134 978","real_id" =>27,),
"28"=>array("name_ru"=>"Амьен","name_en"=>"Amiens","name_href" => "fr/population-of-amiens","count" => "132 727","real_id" =>28,),
"29"=>array("name_ru"=>"Перпиньян","name_en"=>"Perpignan","name_href" => "fr/population-of-perpignan","count" => "120 489","real_id" =>29,),
"30"=>array("name_ru"=>"Мец","name_en"=>"Mets","name_href" => "fr/population-of-mets","count" => "119 551","real_id" =>30,),
"31"=>array("name_ru"=>"Булонь-Бийанкур","name_en"=>"Boulogne-Billancourt","name_href" => "fr/population-of-boulogne-billancourt","count" => "117 126","real_id" =>31,),
"32"=>array("name_ru"=>"Безансон","name_en"=>"Besancon","name_href" => "fr/population-of-besancon","count" => "116 353","real_id" =>32,),
"33"=>array("name_ru"=>"Орлеан","name_en"=>"Orleans","name_href" => "fr/population-of-orleans","count" => "114 286","real_id" =>33,),
"34"=>array("name_ru"=>"Руан","name_en"=>"Rouen","name_href" => "fr/population-of-rouen","count" => "111 557","real_id" =>34,),
"35"=>array("name_ru"=>"Мюлуз","name_en"=>"Mulhouse","name_href" => "fr/population-of-mulhouse","count" => "110 755","real_id" =>35,),
"36"=>array("name_ru"=>"Кан","name_en"=>"Caen","name_href" => "fr/population-of-caen","count" => "108 365","real_id" =>36,),
"37"=>array("name_ru"=>"Сен-Дени","name_en"=>"Saint-Denis","name_href" => "fr/population-of-saint-denis","count" => "108 274","real_id" =>37,),
"38"=>array("name_ru"=>"Нэнси","name_en"=>"Nancy","name_href" => "fr/population-of-nancy","count" => "105 067","real_id" =>38,),
"39"=>array("name_ru"=>"Аржантей","name_en"=>"Argenteuil","name_href" => "fr/population-of-argenteuil","count" => "104 962","real_id" =>39,),
"40"=>array("name_ru"=>"Сен-Поль","name_en"=>"St. Paul","name_href" => "fr/population-of-st-paul","count" => "104 646","real_id" =>40,),
"41"=>array("name_ru"=>"Монтрей","name_en"=>"Montreuil","name_href" => "fr/population-of-montreuil","count" => "103 520","real_id" =>41,),
"42"=>array("name_ru"=>"Нумеа","name_en"=>"Noumea","name_href" => "fr/population-of-noumea","count" => "99 926","real_id" =>42,),
"43"=>array("name_ru"=>"Рубе","name_en"=>"Roubaix","name_href" => "fr/population-of-roubaix","count" => "94 536","real_id" =>43,),
"44"=>array("name_ru"=>"Туркуэн","name_en"=>"Tourcoing","name_href" => "fr/population-of-tourcoing","count" => "92 707","real_id" =>44,),
"45"=>array("name_ru"=>"Дюнкерк ","name_en"=>"Dunkirk","name_href" => "fr/population-of-dunkirk","count" => "90 995","real_id" =>45,),
"46"=>array("name_ru"=>"Нантер","name_en"=>"Nanterre","name_href" => "fr/population-of-nanterre","count" => "90 722","real_id" =>46,),
"47"=>array("name_ru"=>"Кретей","name_en"=>"Creteil","name_href" => "fr/population-of-creteil","count" => "89 845","real_id" =>47,),
"48"=>array("name_ru"=>"Авиньон","name_en"=>"Avignon","name_href" => "fr/population-of-avignon","count" => "89 380","real_id" =>48,),
"49"=>array("name_ru"=>"Витри-сюр-Сен","name_en"=>"Vitry-sur-Seine","name_href" => "fr/population-of-vitry-sur-seine","count" => "88 102","real_id" =>49,),
"50"=>array("name_ru"=>"Пуатье","name_en"=>"Poitiers","name_href" => "fr/population-of-poitiers","count" => "87 646","real_id" =>50,),
"51"=>array("name_ru"=>"Курбевуа","name_en"=>"Courbevoie","name_href" => "fr/population-of-courbevoie","count" => "86 854","real_id" =>51,),
"52"=>array("name_ru"=>"Фор-де-Франс","name_en"=>"Fort-de-France","name_href" => "fr/population-of-fort-de-france","count" => "85 667","real_id" =>52,),
"53"=>array("name_ru"=>"Версаль","name_en"=>"Versailles","name_href" => "fr/population-of-versailles","count" => "85 424","real_id" =>53,),
"54"=>array("name_ru"=>"Коломб","name_en"=>"Colomb","name_href" => "fr/population-of-colomb","count" => "85 357","real_id" =>54,),
"55"=>array("name_ru"=>"Аньер-сюр-Сен","name_en"=>"Asnieres-sur-Seine","name_href" => "fr/population-of-asnieres-sur-seine","count" => "83 845","real_id" =>55,),
"56"=>array("name_ru"=>"Оне-су-Буа","name_en"=>"Ones-sous-Bois","name_href" => "fr/population-of-ones-sous-bois","count" => "81 899","real_id" =>56,),
"57"=>array("name_ru"=>"Сен-Пьерр","name_en"=>"Saint-Pierre","name_href" => "fr/population-of-saint-pierre","count" => "80 823","real_id" =>57,),
"58"=>array("name_ru"=>"Рюэй-Мальмезон","name_en"=>"Rueil-Malmaison","name_href" => "fr/population-of-rueil-malmaison","count" => "79 563","real_id" =>58,),
"59"=>array("name_ru"=>"По","name_en"=>"By","name_href" => "fr/population-of-by","count" => "78 506","real_id" =>59,),
"60"=>array("name_ru"=>"Обервилье","name_en"=>"Oberville","name_href" => "fr/population-of-oberville","count" => "77 032","real_id" =>60,),
"61"=>array("name_ru"=>"Шампиньи-сюр-Марн","name_en"=>"Champigny-sur-Marne","name_href" => "fr/population-of-champigny-sur-marne","count" => "75 869","real_id" =>61,),
"62"=>array("name_ru"=>"Ле Тампон","name_en"=>"Le Tampon","name_href" => "fr/population-of-le-tampon","count" => "75 631","real_id" =>62,),
"63"=>array("name_ru"=>"Антиб","name_en"=>"Antibes","name_href" => "fr/population-of-antibes","count" => "75 568","real_id" =>63,),
"64"=>array("name_ru"=>"Сен-Мор-де-Фоссе","name_en"=>"Saint-Maur-de-Fosse","name_href" => "fr/population-of-saint-maur-de-fosse","count" => "74 176","real_id" =>64,),
"65"=>array("name_ru"=>"Ла-Рошель","name_en"=>"La Rochelle","name_href" => "fr/population-of-la-rochelle","count" => "74 123","real_id" =>65,),
"66"=>array("name_ru"=>"Канн","name_en"=>"Cannes","name_href" => "fr/population-of-cannes","count" => "73 603","real_id" =>66,),
"67"=>array("name_ru"=>"Безье","name_en"=>"Bézier","name_href" => "fr/population-of-bézier","count" => "72 970","real_id" =>67,),
"68"=>array("name_ru"=>"Кале","name_en"=>"Calais","name_href" => "fr/population-of-calais","count" => "72 589","real_id" =>68,),
"69"=>array("name_ru"=>"Сен-Назер","name_en"=>"Saint-Nazaire","name_href" => "fr/population-of-saint-nazaire","count" => "67 940","real_id" =>69,),
"70"=>array("name_ru"=>"Кольмар","name_en"=>"Colmar","name_href" => "fr/population-of-colmar","count" => "67 257","real_id" =>70,),
"71"=>array("name_ru"=>"Дранси","name_en"=>"Drancy","name_href" => "fr/population-of-drancy","count" => "67 181","real_id" =>71,),
"72"=>array("name_ru"=>"Бурж","name_en"=>"Bourges","name_href" => "fr/population-of-bourges","count" => "66 666","real_id" =>72,),
"73"=>array("name_ru"=>"Мериньяк","name_en"=>"Merignac","name_href" => "fr/population-of-merignac","count" => "66 660","real_id" =>73,),
"74"=>array("name_ru"=>"Аяччо","name_en"=>"Ajaccio","name_href" => "fr/population-of-ajaccio","count" => "66 245","real_id" =>74,),
"75"=>array("name_ru"=>"Исси-ле-Мулино","name_en"=>"Issy-les-Moulineaux","name_href" => "fr/population-of-issy-les-moulineaux","count" => "65 322","real_id" =>75,),
"76"=>array("name_ru"=>"Левалуа-Пере","name_en"=>"Levallois-Perret","name_href" => "fr/population-of-levallois-perret","count" => "64 654","real_id" =>76,),
"77"=>array("name_ru"=>"Ла-Сейн-сюр-Мер","name_en"=>"La Seyne-sur-Mer","name_href" => "fr/population-of-la-seyne-sur-mer","count" => "63 902","real_id" =>77,),
"78"=>array("name_ru"=>"Кемпер","name_en"=>"Camper","name_href" => "fr/population-of-camper","count" => "63 360","real_id" =>78,),
"79"=>array("name_ru"=>"Нуази-ле-Гран","name_en"=>"Noisy-le-Grand","name_href" => "fr/population-of-noisy-le-grand","count" => "62 592","real_id" =>79,),
"80"=>array("name_ru"=>"Вала́́нс","name_en"=>"Valance","name_href" => "fr/population-of-valance","count" => "62 481","real_id" =>80,),
"81"=>array("name_ru"=>"Вильнев д'Аск","name_en"=>"Villeneuve d'Ascq","name_href" => "fr/population-of-villeneuve-dascq","count" => "62 308","real_id" =>81,),
"82"=>array("name_ru"=>"Нейи-сюр-Сен","name_en"=>"Neuilly-sur-Seine","name_href" => "fr/population-of-neuilly-sur-seine","count" => "62 021","real_id" =>82,),
"83"=>array("name_ru"=>"Антони","name_en"=>"Anthony","name_href" => "fr/population-of-anthony","count" => "61 624","real_id" =>83,),
"84"=>array("name_ru"=>"Венисьё","name_en"=>"Venissieu","name_href" => "fr/population-of-venissieu","count" => "61 183","real_id" =>84,),
"85"=>array("name_ru"=>"Сержи","name_en"=>"Cergy","name_href" => "fr/population-of-cergy","count" => "60 528","real_id" =>85,),
"86"=>array("name_ru"=>"Труа","name_en"=>"Troyes","name_href" => "fr/population-of-troyes","count" => "60 009","real_id" =>86,),
"87"=>array("name_ru"=>"Клиши","name_en"=>"Clichy","name_href" => "fr/population-of-clichy","count" => "59 240","real_id" =>87,),
"88"=>array("name_ru"=>"Пессак","name_en"=>"Pessac","name_href" => "fr/population-of-pessac","count" => "59 223","real_id" =>88,),
"89"=>array("name_ru"=>"Лез-Абим","name_en"=>"Les Abim","name_href" => "fr/population-of-les-abim","count" => "58 606","real_id" =>89,),
"90"=>array("name_ru"=>"Иври-сюр-Сен","name_en"=>"Ivry-sur-Seine","name_href" => "fr/population-of-ivry-sur-seine","count" => "58 579","real_id" =>90,),
"91"=>array("name_ru"=>"Шамбери","name_en"=>"Chambery","name_href" => "fr/population-of-chambery","count" => "58 039","real_id" =>91,),
"92"=>array("name_ru"=>"Лорьян","name_en"=>"Lorient","name_href" => "fr/population-of-lorient","count" => "57 706","real_id" =>92,),
"93"=>array("name_ru"=>"Ньор","name_en"=>"Nyor","name_href" => "fr/population-of-nyor","count" => "57 607","real_id" =>93,),
"94"=>array("name_ru"=>"Сарсель","name_en"=>"Sarcelles","name_href" => "fr/population-of-sarcelles","count" => "57 499","real_id" =>94,),
"95"=>array("name_ru"=>"Мамуцу","name_en"=>"Mamutsu","name_href" => "fr/population-of-mamutsu","count" => "57 281","real_id" =>95,),
"96"=>array("name_ru"=>"Монтобан","name_en"=>"Montauban","name_href" => "fr/population-of-montauban","count" => "56 887","real_id" =>96,),
"97"=>array("name_ru"=>"Вильжюиф","name_en"=>"Villejuif","name_href" => "fr/population-of-villejuif","count" => "56 504","real_id" =>97,),
"98"=>array("name_ru"=>"Сен-Кантен","name_en"=>"Saint-Quentin","name_href" => "fr/population-of-saint-quentin","count" => "56 217","real_id" =>98,),
"99"=>array("name_ru"=>"Йер","name_en"=>"Hyère","name_href" => "fr/population-of-hyère","count" => "55 402","real_id" =>99,),
"100"=>array("name_ru"=>"Кайенна ","name_en"=>"Cayenne","name_href" => "fr/population-of-cayenne","count" => "55 198","real_id" =>100,),
"101"=>array("name_ru"=>"Эпине-сюр-Сен","name_en"=>"Epine-sur-Seine","name_href" => "fr/population-of-epine-sur-seine","count" => "55 140","real_id" =>101,),
"102"=>array("name_ru"=>"Сент-Андре","name_en"=>"Saint-Andre","name_href" => "fr/population-of-saint-andre","count" => "54 721","real_id" =>102,),
"103"=>array("name_ru"=>"Бове","name_en"=>"Beauvais","name_href" => "fr/population-of-beauvais","count" => "54 289","real_id" =>103,),
"104"=>array("name_ru"=>"Мезон-Альфор","name_en"=>"Maisons-Alfort","name_href" => "fr/population-of-maisons-alfort","count" => "54 186","real_id" =>104,),
"105"=>array("name_ru"=>"Шоле","name_en"=>"Cholet","name_href" => "fr/population-of-cholet","count" => "54 181","real_id" =>105,),
"106"=>array("name_ru"=>"Мо","name_en"=>"Mo","name_href" => "fr/population-of-mo","count" => "53 623","real_id" =>106,),
"107"=>array("name_ru"=>"Шель","name_en"=>"Shel","name_href" => "fr/population-of-shel","count" => "53 247","real_id" =>107,),
"108"=>array("name_ru"=>"Панте́н","name_en"=>"Panten","name_href" => "fr/population-of-panten","count" => "53 060","real_id" =>108,),
"109"=>array("name_ru"=>"Фонтене-су-Буа","name_en"=>"Fontenay-sous-Bois","name_href" => "fr/population-of-fontenay-sous-bois","count" => "52 998","real_id" =>109,),
"110"=>array("name_ru"=>"Ла-Рош-сюр-Йон","name_en"=>"La Roche-sur-Yonne","name_href" => "fr/population-of-la-roche-sur-yonne","count" => "52 808","real_id" =>110,),
"111"=>array("name_ru"=>"Бонди","name_en"=>"Bondi","name_href" => "fr/population-of-bondi","count" => "52 787","real_id" =>111,),
"112"=>array("name_ru"=>"Ван","name_en"=>"Wang","name_href" => "fr/population-of-wang","count" => "52 648","real_id" =>112,),
"113"=>array("name_ru"=>"Сен-Луи","name_en"=>"St. Louis","name_href" => "fr/population-of-st--louis","count" => "52 614","real_id" =>113,),
"114"=>array("name_ru"=>"Фрежюс","name_en"=>"Frejus","name_href" => "fr/population-of-frejus","count" => "52 532","real_id" =>114,),
"115"=>array("name_ru"=>"Арль","name_en"=>"Arles","name_href" => "fr/population-of-arles","count" => "52 439","real_id" =>115,),
"116"=>array("name_ru"=>"Кламар","name_en"=>"Klamar","name_href" => "fr/population-of-klamar","count" => "52 408","real_id" =>116,),
"117"=>array("name_ru"=>"Эври","name_en"=>"Evry","name_href" => "fr/population-of-evry","count" => "52 349","real_id" =>117,),
"118"=>array("name_ru"=>"Ле-Блан-Мениль","name_en"=>"Le Blanc-Mesnil","name_href" => "fr/population-of-le-blanc-mesnil","count" => "52 213","real_id" =>118,),
"119"=>array("name_ru"=>"Нарбон","name_en"=>"Narbonne","name_href" => "fr/population-of-narbonne","count" => "51 869","real_id" =>119,),
"120"=>array("name_ru"=>"Сартрувиль","name_en"=>"Sartruville","name_href" => "fr/population-of-sartruville","count" => "51 713","real_id" =>120,),
"121"=>array("name_ru"=>"Грас","name_en"=>"Grasse","name_href" => "fr/population-of-grasse","count" => "51 021","real_id" =>121,),
"122"=>array("name_ru"=>"Анси́","name_en"=>"Annecy","name_href" => "fr/population-of-annecy","count" => "50 943","real_id" =>122,),
"123"=>array("name_ru"=>"Лаваль","name_en"=>"Laval","name_href" => "fr/population-of-laval","count" => "50 658","real_id" =>123,),
"124"=>array("name_ru"=>"Бельфор","name_en"=>"Belfort","name_href" => "fr/population-of-belfort","count" => "50 102","real_id" =>124,),
"125"=>array("name_ru"=>"Венсен","name_en"=>"Vincent","name_href" => "fr/population-of-vincent","count" => "49 831","real_id" =>125,),
"126"=>array("name_ru"=>"Шарлевиль Мезьер","name_en"=>"Charleville Mezière","name_href" => "fr/population-of-charleville-mezière","count" => "49 759","real_id" =>126,),
"127"=>array("name_ru"=>"Эврё","name_en"=>"Evreux","name_href" => "fr/population-of-evreux","count" => "49 634","real_id" =>127,),
"128"=>array("name_ru"=>"Севран","name_en"=>"Sevran","name_href" => "fr/population-of-sevran","count" => "49 442","real_id" =>128,),
"129"=>array("name_ru"=>"Альби","name_en"=>"Albi","name_href" => "fr/population-of-albi","count" => "49 231","real_id" =>129,),
"130"=>array("name_ru"=>"Монруж","name_en"=>"Montrouge","name_href" => "fr/population-of-montrouge","count" => "48 909","real_id" =>130,),
"131"=>array("name_ru"=>"Бобиньи","name_en"=>"Bobigny","name_href" => "fr/population-of-bobigny","count" => "48 496","real_id" =>131,),
"132"=>array("name_ru"=>"Мартиг","name_en"=>"Martigues","name_href" => "fr/population-of-martigues","count" => "47 624","real_id" =>132,),
"133"=>array("name_ru"=>"Сент-Уэн","name_en"=>"Saint-Ouen","name_href" => "fr/population-of-saint-ouen","count" => "47 499","real_id" =>133,),
"134"=>array("name_ru"=>"Брив-ла-Гайард","name_en"=>"Brive-la-Gaillarde","name_href" => "fr/population-of-brive-la-gaillarde","count" => "47 411","real_id" =>134,),
"135"=>array("name_ru"=>"Сюрен","name_en"=>"Suresnes","name_href" => "fr/population-of-suresnes","count" => "47 263","real_id" =>135,),
"136"=>array("name_ru"=>"Каркассон","name_en"=>"Carcassonne","name_href" => "fr/population-of-carcassonne","count" => "47 068","real_id" =>136,),
"137"=>array("name_ru"=>"Кань-сюр-Мер","name_en"=>"Cagnes-sur-Mer","name_href" => "fr/population-of-cagnes-sur-mer","count" => "46 686","real_id" =>137,),
"138"=>array("name_ru"=>"Корбей-Эсон","name_en"=>"Corbeil-Eson","name_href" => "fr/population-of-corbeil-eson","count" => "46 017","real_id" =>138,),
"139"=>array("name_ru"=>"Сен-Бриё","name_en"=>"Saint-Brieuc","name_href" => "fr/population-of-saint-brieuc","count" => "45 936","real_id" =>139,),
"140"=>array("name_ru"=>"Блуа","name_en"=>"Blois","name_href" => "fr/population-of-blois","count" => "45 903","real_id" =>140,),
"141"=>array("name_ru"=>"Байонна","name_en"=>"Bayonne","name_href" => "fr/population-of-bayonne","count" => "45 855","real_id" =>141,),
"142"=>array("name_ru"=>"Обань","name_en"=>"Aubagne","name_href" => "fr/population-of-aubagne","count" => "45 243","real_id" =>142,),
"143"=>array("name_ru"=>"Шалон-ан-Шампань","name_en"=>"Chalon-en-Champagne","name_href" => "fr/population-of-chalon-en-champagne","count" => "45 225","real_id" =>143,),
"144"=>array("name_ru"=>"Медон","name_en"=>"Meudon","name_href" => "fr/population-of-meudon","count" => "45 107","real_id" =>144,),
"145"=>array("name_ru"=>"Шатору","name_en"=>"Château","name_href" => "fr/population-of-château","count" => "44 960","real_id" =>145,),
"146"=>array("name_ru"=>"Сен-Мало","name_en"=>"Saint-Malo","name_href" => "fr/population-of-saint-malo","count" => "44 620","real_id" =>146,),
"147"=>array("name_ru"=>"Шалон-сюр-Сон","name_en"=>"Chalon-sur-Saone","name_href" => "fr/population-of-chalon-sur-saone","count" => "44 564","real_id" =>147,),
"148"=>array("name_ru"=>"Сет","name_en"=>"Set","name_href" => "fr/population-of-set","count" => "44 558","real_id" =>148,),
"149"=>array("name_ru"=>"Пюто","name_en"=>"Puteaux","name_href" => "fr/population-of-puteaux","count" => "44 514","real_id" =>149,),
"150"=>array("name_ru"=>"Альфортвиль","name_en"=>"Alfortville","name_href" => "fr/population-of-alfortville","count" => "44 397","real_id" =>150,),
"151"=>array("name_ru"=>"Салон-де-Прованс","name_en"=>"Salon de Provence","name_href" => "fr/population-of-salon-de-provence","count" => "43 771","real_id" =>151,),
"152"=>array("name_ru"=>"Масси","name_en"=>"Massi","name_href" => "fr/population-of-massi","count" => "43 524","real_id" =>152,),
"153"=>array("name_ru"=>"Мант-ла-Жоли","name_en"=>"Mant-la-Joli","name_href" => "fr/population-of-mant-la-joli","count" => "43 515","real_id" =>153,),
"154"=>array("name_ru"=>"Бастия","name_en"=>"Bastia","name_href" => "fr/population-of-bastia","count" => "43 479","real_id" =>154,),
"155"=>array("name_ru"=>"Во-ан-Велен","name_en"=>"Va-en-Velen","name_href" => "fr/population-of-va-en-velen","count" => "43 394","real_id" =>155,),
"156"=>array("name_ru"=>"Сен-Ерблен","name_en"=>"Saint-Erblain","name_href" => "fr/population-of-saint-erblain","count" => "43 287","real_id" =>156,),
"157"=>array("name_ru"=>"Ле-Канне","name_en"=>"Le Cannet","name_href" => "fr/population-of-le-cannet","count" => "43 115","real_id" =>157,),
"158"=>array("name_ru"=>"Валансьен","name_en"=>"Valenciennes","name_href" => "fr/population-of-valenciennes","count" => "42 989","real_id" =>158,),
"159"=>array("name_ru"=>"Истр","name_en"=>"Istra","name_href" => "fr/population-of-istra","count" => "42 944","real_id" =>159,),
"160"=>array("name_ru"=>"Женнвилье","name_en"=>"Gennevilliers","name_href" => "fr/population-of-gennevilliers","count" => "42 919","real_id" =>160,),
"161"=>array("name_ru"=>"Булонь-сюр-Мер","name_en"=>"Boulogne-sur-Mer","name_href" => "fr/population-of-boulogne-sur-mer","count" => "42 785","real_id" =>161,),
"162"=>array("name_ru"=>"Ливри-Гарган","name_en"=>"Livry-Gargan","name_href" => "fr/population-of-livry-gargan","count" => "42 699","real_id" =>162,),
"163"=>array("name_ru"=>"Сен-Прие","name_en"=>"Saint-Prieu","name_href" => "fr/population-of-saint-prieu","count" => "42 488","real_id" =>163,),
"164"=>array("name_ru"=>"Рони-су-Буа","name_en"=>"Roni-sous-Bois","name_href" => "fr/population-of-roni-sous-bois","count" => "42 080","real_id" =>164,),
"165"=>array("name_ru"=>"Калюир-э-Кюир","name_en"=>"Caluire-et-Cuir","name_href" => "fr/population-of-caluire-et-cuir","count" => "42 038","real_id" =>165,),
"166"=>array("name_ru"=>"Ангулем","name_en"=>"Angouleme","name_href" => "fr/population-of-angouleme","count" => "42 014","real_id" =>166,),
"167"=>array("name_ru"=>"Дуэ","name_en"=>"Douai","name_href" => "fr/population-of-douai","count" => "41 732","real_id" =>167,),
"168"=>array("name_ru"=>"Тарб","name_en"=>"Tarbes","name_href" => "fr/population-of-tarbes","count" => "41 664","real_id" =>168,),
"169"=>array("name_ru"=>"Ватрело","name_en"=>"Watrelo","name_href" => "fr/population-of-watrelo","count" => "41 633","real_id" =>169,),
"170"=>array("name_ru"=>"Кастр","name_en"=>"Castres","name_href" => "fr/population-of-castres","count" => "41 529","real_id" =>170,),
"171"=>array("name_ru"=>"Шуази-ле-Руа","name_en"=>"Choisy-le-Roi","name_href" => "fr/population-of-choisy-le-roi","count" => "41 507","real_id" =>171,),
"172"=>array("name_ru"=>"Таланс","name_en"=>"Talence","name_href" => "fr/population-of-talence","count" => "41 358","real_id" =>172,),
"173"=>array("name_ru"=>"Тьонвиль","name_en"=>"Thionville","name_href" => "fr/population-of-thionville","count" => "41 325","real_id" =>173,),
"174"=>array("name_ru"=>"Аррас","name_en"=>"Arras","name_href" => "fr/population-of-arras","count" => "41 239","real_id" =>174,),
"175"=>array("name_ru"=>"Алес","name_en"=>"Ales","name_href" => "fr/population-of-ales","count" => "41 031","real_id" =>175,),
"176"=>array("name_ru"=>"Гарж-ле-Гонесс","name_en"=>"Garges-le-Goness","name_href" => "fr/population-of-garges-le-goness","count" => "41 001","real_id" =>176,),
"177"=>array("name_ru"=>"Гап","name_en"=>"Gap","name_href" => "fr/population-of-gap","count" => "40 761","real_id" =>177,),
"178"=>array("name_ru"=>"Сен-Лоран-дю-Марони","name_en"=>"Saint-Laurent-du-Maroni","name_href" => "fr/population-of-saint-laurent-du-maroni","count" => "40 597","real_id" =>178,),
"179"=>array("name_ru"=>"Мелён","name_en"=>"Melen","name_href" => "fr/population-of-melen","count" => "40 503","real_id" =>179,),
"180"=>array("name_ru"=>"Бурк-ан-Брес","name_en"=>"Bourg-en-Bresse","name_href" => "fr/population-of-bourg-en-bresse","count" => "40 171","real_id" =>180,),
"181"=>array("name_ru"=>"Нуази-ле-Сек","name_en"=>"Noisy-le-Sec","name_href" => "fr/population-of-noisy-le-sec","count" => "40 161","real_id" =>181,),
"182"=>array("name_ru"=>"Компьень","name_en"=>"Compiègne","name_href" => "fr/population-of-compiègne","count" => "40 028","real_id" =>182,),
"183"=>array("name_ru"=>"Ла-Курнёв","name_en"=>"La Courneuve","name_href" => "fr/population-of-la-courneuve","count" => "39 859","real_id" =>183,),
"184"=>array("name_ru"=>"Ле-Ламантен","name_en"=>"Le Lamantine","name_href" => "fr/population-of-le-lamantine","count" => "39 700","real_id" =>184,),
"185"=>array("name_ru"=>"Марк-ан-Барёль","name_en"=>"Marc-en-Baroel","name_href" => "fr/population-of-marc-en-baroel","count" => "39 600","real_id" =>185,),
"186"=>array("name_ru"=>"Сен-Жермен-ан-Ле","name_en"=>"Saint-Germain-en-Laye","name_href" => "fr/population-of-saint-germain-en-laye","count" => "39 476","real_id" =>186,),
"187"=>array("name_ru"=>"Резе","name_en"=>"Reze","name_href" => "fr/population-of-reze","count" => "39 377","real_id" =>187,),
"188"=>array("name_ru"=>"Брон","name_en"=>"Bron","name_href" => "fr/population-of-bron","count" => "39 232","real_id" =>188,),
"189"=>array("name_ru"=>"Англет","name_en"=>"Anglet","name_href" => "fr/population-of-anglet","count" => "39 223","real_id" =>189,),
"190"=>array("name_ru"=>"Ганьи","name_en"=>"Gagni","name_href" => "fr/population-of-gagni","count" => "39 172","real_id" =>190,),
"191"=>array("name_ru"=>"Шартр","name_en"=>"Chartres","name_href" => "fr/population-of-chartres","count" => "38 889","real_id" =>191,),
"192"=>array("name_ru"=>"Баньё","name_en"=>"Banyo","name_href" => "fr/population-of-banyo","count" => "38 398","real_id" =>192,),
"193"=>array("name_ru"=>"Сен-Мартен-д’Эр","name_en"=>"Saint-Martin-d'Aer","name_href" => "fr/population-of-saint-martin-daer","count" => "38 105","real_id" =>193,),
"194"=>array("name_ru"=>"Монлюсон","name_en"=>"Montlucon","name_href" => "fr/population-of-montlucon","count" => "38 072","real_id" =>194,),
"195"=>array("name_ru"=>"Понто-Комбо","name_en"=>"Ponto-Combo","name_href" => "fr/population-of-ponto-combo","count" => "37 631","real_id" =>195,),
"196"=>array("name_ru"=>"Пуасси","name_en"=>"Poissy","name_href" => "fr/population-of-poissy","count" => "37 597","real_id" =>196,),
"197"=>array("name_ru"=>"Драгиньян","name_en"=>"Draguignan","name_href" => "fr/population-of-draguignan","count" => "37 476","real_id" =>197,),
"198"=>array("name_ru"=>"Жуэ-ле-Тур","name_en"=>"Joue-le-Tours","name_href" => "fr/population-of-joue-le-tours","count" => "37 196","real_id" =>198,),
"199"=>array("name_ru"=>"Савиньи-сюр-Орж","name_en"=>"Savigny-sur-Orge","name_href" => "fr/population-of-savigny-sur-orge","count" => "37 135","real_id" =>199,),
"200"=>array("name_ru"=>"Шербур-Октевиль","name_en"=>"Cherbourg-Octeville","name_href" => "fr/population-of-cherbourg-octeville","count" => "37 121","real_id" =>200,),
"201"=>array("name_ru"=>"Сен-Жозеф ","name_en"=>"Saint-Joseph","name_href" => "fr/population-of-saint-joseph","count" => "37 069","real_id" =>201,),
"202"=>array("name_ru"=>"Ле-Пор","name_en"=>"Le Por","name_href" => "fr/population-of-le-por","count" => "36 952","real_id" =>202,),
"203"=>array("name_ru"=>"Коломье","name_en"=>"Colomiers","name_href" => "fr/population-of-colomiers","count" => "36 699","real_id" =>203,),
"204"=>array("name_ru"=>"Сен-Мартен","name_en"=>"Saint-Martin","name_href" => "fr/population-of-saint-martin","count" => "36 622","real_id" =>204,),
"205"=>array("name_ru"=>"Вильфранш-сюр-Сон","name_en"=>"Villefranche-sur-Saone","name_href" => "fr/population-of-villefranche-sur-saone","count" => "36 241","real_id" =>205,),
"206"=>array("name_ru"=>"Стен","name_en"=>"Walls","name_href" => "fr/population-of-walls","count" => "36 155","real_id" =>206,),
"207"=>array("name_ru"=>"Сен-Бенуа","name_en"=>"Saint-Benoit","name_href" => "fr/population-of-saint-benoit","count" => "36 025","real_id" =>207,),
"208"=>array("name_ru"=>"Эшироль","name_en"=>"Echirol","name_href" => "fr/population-of-echirol","count" => "35 826","real_id" =>208,),
"209"=>array("name_ru"=>"Вильпент","name_en"=>"Villepinte","name_href" => "fr/population-of-villepinte","count" => "35 820","real_id" =>209,),
"210"=>array("name_ru"=>"Роан","name_en"=>"Roan","name_href" => "fr/population-of-roan","count" => "35 799","real_id" =>210,),
"211"=>array("name_ru"=>"Монтелимар","name_en"=>"Montélimar","name_href" => "fr/population-of-montélimar","count" => "35 704","real_id" =>211,),
"212"=>array("name_ru"=>"Сен-Шамон","name_en"=>"Saint-Chamond","name_href" => "fr/population-of-saint-chamond","count" => "35 564","real_id" =>212,),
"213"=>array("name_ru"=>"Невер","name_en"=>"Nevers","name_href" => "fr/population-of-nevers","count" => "35 327","real_id" =>213,),
"214"=>array("name_ru"=>"Конфлан-Сент-Онорин","name_en"=>"Conflans-Saint-Honorine","name_href" => "fr/population-of-conflans-saint-honorine","count" => "35 135","real_id" =>214,),
"215"=>array("name_ru"=>"Осер","name_en"=>"Auxerre","name_href" => "fr/population-of-auxerre","count" => "35 096","real_id" =>215,),
"216"=>array("name_ru"=>"Сент-Женевьев-де-Буа","name_en"=>"Sainte-Geneviève-des-Bois","name_href" => "fr/population-of-sainte-geneviève-des-bois","count" => "35 035","real_id" =>216,),
"217"=>array("name_ru"=>"Шатийон","name_en"=>"Châtillon","name_href" => "fr/population-of-châtillon","count" => "34 960","real_id" =>217,),
"218"=>array("name_ru"=>"Баньоле","name_en"=>"Bagnolet","name_href" => "fr/population-of-bagnolet","count" => "34 920","real_id" =>218,),
"219"=>array("name_ru"=>"Витроль","name_en"=>"Vitrolles","name_href" => "fr/population-of-vitrolles","count" => "34 843","real_id" =>219,),
"220"=>array("name_ru"=>"Тонон-ле-Бен","name_en"=>"Thonon-les-Bains","name_href" => "fr/population-of-thonon-les-bains","count" => "34 661","real_id" =>220,),
"221"=>array("name_ru"=>"Нёйи-сюр-Марн","name_en"=>"Neuilly-sur-Marne","name_href" => "fr/population-of-neuilly-sur-marne","count" => "34 658","real_id" =>221,),
"222"=>array("name_ru"=>"Агно","name_en"=>"Agno","name_href" => "fr/population-of-agno","count" => "34 406","real_id" =>222,),
"223"=>array("name_ru"=>"Мариньян","name_en"=>"Marignane","name_href" => "fr/population-of-marignane","count" => "34 405","real_id" =>223,),
"224"=>array("name_ru"=>"Сен-Рафаэль","name_en"=>"Saint-Raphael","name_href" => "fr/population-of-saint-raphael","count" => "34 115","real_id" =>224,),
"225"=>array("name_ru"=>"Трамбле-ан-Франс","name_en"=>"Tremblay-en-France","name_href" => "fr/population-of-tremblay-en-france","count" => "34 081","real_id" =>225,),
"226"=>array("name_ru"=>"Ля-Сьота","name_en"=>"La Ciotat","name_href" => "fr/population-of-la-ciotat","count" => "34 063","real_id" =>226,),
"227"=>array("name_ru"=>"Сис-Фур-ле-Плаж","name_en"=>"Sis-Fours-le-Plage","name_href" => "fr/population-of-sis-fours-le-plage","count" => "34 057","real_id" =>227,),
"228"=>array("name_ru"=>"Крей","name_en"=>"Cray","name_href" => "fr/population-of-cray","count" => "33 936","real_id" =>228,),
"229"=>array("name_ru"=>"Ажен","name_en"=>"Agen","name_href" => "fr/population-of-agen","count" => "33 730","real_id" =>229,),
"230"=>array("name_ru"=>"Роман-сюр-Изер","name_en"=>"Roman-sur-Isere","name_href" => "fr/population-of-roman-sur-isere","count" => "33 701","real_id" =>230,),
"231"=>array("name_ru"=>"Монтиньи-ле-Бретонё","name_en"=>"Montigny-le-Bretonneux","name_href" => "fr/population-of-montigny-le-bretonneux","count" => "33 680","real_id" =>231,),
"232"=>array("name_ru"=>"Ле-Перре-сюр-Марн","name_en"=>"Le Perret-sur-Marne","name_href" => "fr/population-of-le-perret-sur-marne","count" => "33 248","real_id" =>232,),
"233"=>array("name_ru"=>"Франконвиль","name_en"=>"Franconville","name_href" => "fr/population-of-franconville","count" => "33 196","real_id" =>233,),
"234"=>array("name_ru"=>"Аннмасс","name_en"=>"Annmass","name_href" => "fr/population-of-annmass","count" => "33 166","real_id" =>234,),
"235"=>array("name_ru"=>"Вильнёв-Сен-Жорж","name_en"=>"Villeneuve-Saint-Georges","name_href" => "fr/population-of-villeneuve-saint-georges","count" => "32 994","real_id" =>235,),
"236"=>array("name_ru"=>"Сен-Ле","name_en"=>"Saint-Lés","name_href" => "fr/population-of-saint-lés","count" => "32 971","real_id" =>236,),
"237"=>array("name_ru"=>"Макон","name_en"=>"Macon","name_href" => "fr/population-of-macon","count" => "32 917","real_id" =>237,),
"238"=>array("name_ru"=>"Камбре","name_en"=>"Cambrai","name_href" => "fr/population-of-cambrai","count" => "32 847","real_id" =>238,),
"239"=>array("name_ru"=>"Ланс","name_en"=>"Lance","name_href" => "fr/population-of-lance","count" => "32 663","real_id" =>239,),
"240"=>array("name_ru"=>"Уй","name_en"=>"Ou","name_href" => "fr/population-of-ou","count" => "32 399","real_id" =>240,),
"241"=>array("name_ru"=>"Эпиналь","name_en"=>"Epinal","name_href" => "fr/population-of-epinal","count" => "32 387","real_id" =>241,),
"242"=>array("name_ru"=>"Шатне-Малабри","name_en"=>"Shatne-Malabry","name_href" => "fr/population-of-shatne-malabry","count" => "32 198","real_id" =>242,),
"243"=>array("name_ru"=>"Шильтигайм","name_en"=>"Schiltigheim","name_href" => "fr/population-of-schiltigheim","count" => "31 691","real_id" =>243,),
"244"=>array("name_ru"=>"Сент-Мари","name_en"=>"Saint-marie","name_href" => "fr/population-of-saint-marie","count" => "31 596","real_id" =>244,),
"245"=>array("name_ru"=>"Льевен","name_en"=>"Leuven","name_href" => "fr/population-of-leuven","count" => "31 580","real_id" =>245,),
"246"=>array("name_ru"=>"Шательро","name_en"=>"Châtellerault","name_href" => "fr/population-of-châtellerault","count" => "31 537","real_id" =>246,),
"247"=>array("name_ru"=>"Меизье","name_en"=>"Meisier","name_href" => "fr/population-of-meisier","count" => "31 493","real_id" =>247,),
"248"=>array("name_ru"=>"Гуссенвиль","name_en"=>"Goossenville","name_href" => "fr/population-of-goossenville","count" => "31 255","real_id" =>248,),
"249"=>array("name_ru"=>"Вири-Шатийон","name_en"=>"Viry-Chatillon","name_href" => "fr/population-of-viry-chatillon","count" => "31 221","real_id" =>249,),
"250"=>array("name_ru"=>"Дрё","name_en"=>"Dreux","name_href" => "fr/population-of-dreux","count" => "31 195","real_id" =>250,),
"251"=>array("name_ru"=>"Л’Э-ле-Роз","name_en"=>"L'E-le-Rose","name_href" => "fr/population-of-le-le-rose","count" => "31 168","real_id" =>251,),
"252"=>array("name_ru"=>"Плезир","name_en"=>"Plesir","name_href" => "fr/population-of-plesir","count" => "31 119","real_id" =>252,),
"253"=>array("name_ru"=>"Мон-де-Марсан","name_en"=>"Mont-de-Marsan","name_href" => "fr/population-of-mont-de-marsan","count" => "31 018","real_id" =>253,),
"254"=>array("name_ru"=>"Мобёж","name_en"=>"Maubeuge","name_href" => "fr/population-of-maubeuge","count" => "30 994","real_id" =>254,),
"255"=>array("name_ru"=>"Ножан-сюр-Марн","name_en"=>"Nogent-sur-Marne","name_href" => "fr/population-of-nogent-sur-marne","count" => "30 884","real_id" =>255,),
"256"=>array("name_ru"=>"Ле-Мюро","name_en"=>"Le Mureaux","name_href" => "fr/population-of-le-mureaux","count" => "30 760","real_id" =>256,),
"257"=>array("name_ru"=>"Клиши-су-Буа","name_en"=>"Clichy-sous-Bois","name_href" => "fr/population-of-clichy-sous-bois","count" => "30 720","real_id" =>257,),
"258"=>array("name_ru"=>"Ла-Поссесьйон","name_en"=>"La Poschseillon","name_href" => "fr/population-of-la-poschseillon","count" => "30 653","real_id" =>258,),
"259"=>array("name_ru"=>"Дьеп","name_en"=>"Dieppe","name_href" => "fr/population-of-dieppe","count" => "30 632","real_id" =>259,),
"260"=>array("name_ru"=>"Шату","name_en"=>"Chatou","name_href" => "fr/population-of-chatou","count" => "30 585","real_id" =>260,),
"261"=>array("name_ru"=>"Вандёвр-ле-Нанси","name_en"=>"Vandoeuvre-Nancy","name_href" => "fr/population-of-vandoeuvre-nancy","count" => "30 569","real_id" =>261,),
"262"=>array("name_ru"=>"Малакофф","name_en"=>"Malakoff","name_href" => "fr/population-of-malakoff","count" => "30 420","real_id" =>262,),
"263"=>array("name_ru"=>"Палезо","name_en"=>"Palaiseau","name_href" => "fr/population-of-palaiseau","count" => "30 268","real_id" =>263,),
"264"=>array("name_ru"=>"Понтуаз","name_en"=>"Pontoise","name_href" => "fr/population-of-pontoise","count" => "30 164","real_id" =>264,),
"265"=>array("name_ru"=>"Шарантон-ле-Пон","name_en"=>"Charenton-le-Pont","name_href" => "fr/population-of-charenton-le-pont","count" => "30 148","real_id" =>265,),
"266"=>array("name_ru"=>"Рийє-ла-Пап","name_en"=>"Riye-la-Pap","name_href" => "fr/population-of-riye-la-pap","count" => "30 140","real_id" =>266,),
"267"=>array("name_ru"=>"Баи-Мао","name_en"=>"Bai-Mao","name_href" => "fr/population-of-bai-mao","count" => "29 976","real_id" =>267,),
"268"=>array("name_ru"=>"Перигё","name_en"=>"Perigueux","name_href" => "fr/population-of-perigueux","count" => "29 906","real_id" =>268,),
"269"=>array("name_ru"=>"Трапп","name_en"=>"Trap","name_href" => "fr/population-of-trap","count" => "29 774","real_id" =>269,),
"270"=>array("name_ru"=>"Атис-Монс","name_en"=>"Atis-Mons","name_href" => "fr/population-of-atis-mons","count" => "29 482","real_id" =>270,),
"271"=>array("name_ru"=>"Сен-Лоран-дю-Вар","name_en"=>"Saint-Laurent-du-Var","name_href" => "fr/population-of-saint-laurent-du-var","count" => "29 343","real_id" =>271,),
"272"=>array("name_ru"=>"Вьен","name_en"=>"Vien","name_href" => "fr/population-of-vien","count" => "29 077","real_id" =>272,),
"273"=>array("name_ru"=>"Соттевиль-ле-Руан","name_en"=>"Sotteville-les-Rouen","name_href" => "fr/population-of-sotteville-les-rouen","count" => "28 622","real_id" =>273,),
"274"=>array("name_ru"=>"Сент-Этьен-дю-Рувре","name_en"=>"Saint-Etienne-du-Rouvray","name_href" => "fr/population-of-saint-etienne-du-rouvray","count" => "28 616","real_id" =>274,),
"275"=>array("name_ru"=>"Суасон","name_en"=>"Soissons","name_href" => "fr/population-of-soissons","count" => "28 309","real_id" =>275,),
"276"=>array("name_ru"=>"Сомюр","name_en"=>"Saumur","name_href" => "fr/population-of-saumur","count" => "27 523","real_id" =>276,),
"277"=>array("name_ru"=>"Вьерзон","name_en"=>"Vierzon","name_href" => "fr/population-of-vierzon","count" => "27 081","real_id" =>277,),
"278"=>array("name_ru"=>"Орийак","name_en"=>"Aurillac","name_href" => "fr/population-of-aurillac","count" => "27 074","real_id" =>278,),
"279"=>array("name_ru"=>"Валлорис","name_en"=>"Walloris","name_href" => "fr/population-of-walloris","count" => "26 595","real_id" =>279,),
"280"=>array("name_ru"=>"Алансон","name_en"=>"Alençon","name_href" => "fr/population-of-alençon","count" => "26 305","real_id" =>280,),
"281"=>array("name_ru"=>"Монбельяр","name_en"=>"Montbéliard","name_href" => "fr/population-of-montbéliard","count" => "26 084","real_id" =>281,),
"282"=>array("name_ru"=>"Биарриц","name_en"=>"Biarritz","name_href" => "fr/population-of-biarritz","count" => "25 330","real_id" =>282,),
"283"=>array("name_ru"=>"Виши","name_en"=>"Vichy","name_href" => "fr/population-of-vichy","count" => "25 315","real_id" =>283,),
"284"=>array("name_ru"=>"Сен-Дизье","name_en"=>"Saint-Dizier","name_href" => "fr/population-of-saint-dizier","count" => "25 280","real_id" =>284,),
"285"=>array("name_ru"=>"Ле-Гран-Кевилли","name_en"=>"Le Grand-Cavilli","name_href" => "fr/population-of-le-grand-cavilli","count" => "24 563","real_id" =>285,),
"286"=>array("name_ru"=>"Брюэ-ла-Бюисьер","name_en"=>"Brewe-la-Boussières","name_href" => "fr/population-of-brewe-la-boussières","count" => "23 035","real_id" =>286,),
"287"=>array("name_ru"=>"Ле-Крёзо","name_en"=>"Le Creusot","name_href" => "fr/population-of-le-creusot","count" => "22 574","real_id" =>287,),
"288"=>array("name_ru"=>"Орли","name_en"=>"Orly","name_href" => "fr/population-of-orly","count" => "21 628","real_id" =>288,),
"289"=>array("name_ru"=>"Париж","name_en"=>"Paris","name_href" => "fr/population-of-paris","count" => "2 240 621","real_id" =>289,),
"290"=>array("name_ru"=>"Марсель","name_en"=>"Marseilles","name_href" => "fr/population-of-marseilles","count" => "852 516","real_id" =>290,),
"291"=>array("name_ru"=>"Лион","name_en"=>"Lyon","name_href" => "fr/population-of-lyon","count" => "496 343","real_id" =>291,),
"292"=>array("name_ru"=>"Тулуза","name_en"=>"Toulouse","name_href" => "fr/population-of-toulouse","count" => "453 317","real_id" =>292,),
"293"=>array("name_ru"=>"Ницца","name_en"=>"Nice","name_href" => "fr/population-of-nice","count" => "343 629","real_id" =>293,)
);

?>