<?php
//Грузия 62
$libge = array ( 
"1"=>array("name_ru"=>"Тбилиси","name_en"=>"Tbilisi","name_href"=> "ge/population-of-tbilisi","count"=> "1 062 282","real_id"=>1,),
"2"=>array("name_ru"=>"Батуми","name_en"=>"Batumi","name_href"=> "ge/population-of-batumi","count"=> "152 839","real_id"=>2,),
"3"=>array("name_ru"=>"Кутаиси","name_en"=>"Kutaisi","name_href"=> "ge/population-of-kutaisi","count"=> "147 635","real_id"=>3,),
"4"=>array("name_ru"=>"Рустави","name_en"=>"Rustavi","name_href"=> "ge/population-of-rustavi","count"=> "125 103","real_id"=>4,),
"5"=>array("name_ru"=>"Сухум","name_en"=>"Sukhum","name_href"=> "ge/population-of-sukhum","count"=> "62 914","real_id"=>5,),
"6"=>array("name_ru"=>"Гори","name_en"=>"Gori","name_href"=> "ge/population-of-gori","count"=> "48 143","real_id"=>6,),
"7"=>array("name_ru"=>"Зугдиди","name_en"=>"Zugdidi","name_href"=> "ge/population-of-zugdidi","count"=> "42 998","real_id"=>7,),
"8"=>array("name_ru"=>"Поти","name_en"=>"Poti","name_href"=> "ge/population-of-poti","count"=> "41 465","real_id"=>8,),
"9"=>array("name_ru"=>"Цхинвал","name_en"=>"Tskhinvali","name_href"=> "ge/population-of-tskhinvali","count"=> "30 456","real_id"=>9,),
"10"=>array("name_ru"=>"Хашури","name_en"=>"Khashuri","name_href"=> "ge/population-of-khashuri","count"=> "26 135","real_id"=>10,),
"11"=>array("name_ru"=>"Самтредиа","name_en"=>"Samtredia","name_href"=> "ge/population-of-samtredia","count"=> "25 318","real_id"=>11,),
"12"=>array("name_ru"=>"Сенаки","name_en"=>"Senaki","name_href"=> "ge/population-of-senaki","count"=> "21 596","real_id"=>12,),
"13"=>array("name_ru"=>"Зестафони","name_en"=>"Zestafoni","name_href"=> "ge/population-of-zestafoni","count"=> "20 814","real_id"=>13,),
"14"=>array("name_ru"=>"Марнеули","name_en"=>"Marneuli","name_href"=> "ge/population-of-marneuli","count"=> "20 211","real_id"=>14,),
"15"=>array("name_ru"=>"Телави","name_en"=>"Telavi","name_href"=> "ge/population-of-telavi","count"=> "19 629","real_id"=>15,),
"16"=>array("name_ru"=>"Ахалцихе","name_en"=>"Akhaltsikhe","name_href"=> "ge/population-of-akhaltsikhe","count"=> "17 903","real_id"=>16,),
"17"=>array("name_ru"=>"Кобулети","name_en"=>"Kobuleti","name_href"=> "ge/population-of-kobuleti","count"=> "16 546","real_id"=>17,),
"18"=>array("name_ru"=>"Озургети","name_en"=>"Ozurgeti","name_href"=> "ge/population-of-ozurgeti","count"=> "14 785","real_id"=>18,),
"19"=>array("name_ru"=>"Каспи","name_en"=>"Kaspi","name_href"=> "ge/population-of-kaspi","count"=> "13 423","real_id"=>19,),
"20"=>array("name_ru"=>"Чиатура","name_en"=>"Chiatura","name_href"=> "ge/population-of-chiatura","count"=> "12 803","real_id"=>20,),
"21"=>array("name_ru"=>"Гагра","name_en"=>"Gagra","name_href"=> "ge/population-of-gagra","count"=> "12 364","real_id"=>21,),
"22"=>array("name_ru"=>"Цхалтубо","name_en"=>"Tsqaltubo","name_href"=> "ge/population-of-tsqaltubo","count"=> "11 281","real_id"=>22,),
"23"=>array("name_ru"=>"Сагареджо","name_en"=>"Sagarejo","name_href"=> "ge/population-of-sagarejo","count"=> "10 871","real_id"=>23,),
"24"=>array("name_ru"=>"Гардабани","name_en"=>"Gardabani","name_href"=> "ge/population-of-gardabani","count"=> "10 753","real_id"=>24,),
"25"=>array("name_ru"=>"Боржоми","name_en"=>"Borjomi","name_href"=> "ge/population-of-borjomi","count"=> "10 546","real_id"=>25,),
"26"=>array("name_ru"=>"Ткибули","name_en"=>"Tqibuli","name_href"=> "ge/population-of-tqibuli","count"=> "9 770","real_id"=>26,),
"27"=>array("name_ru"=>"Хони","name_en"=>"Khoni","name_href"=> "ge/population-of-khoni","count"=> "8 987","real_id"=>27,),
"28"=>array("name_ru"=>"Болниси","name_en"=>"Bolnisi","name_href"=> "ge/population-of-bolnisi","count"=> "8 967","real_id"=>28,),
"29"=>array("name_ru"=>"Ахалкалаки","name_en"=>"Akhalkalaki","name_href"=> "ge/population-of-akhalkalaki","count"=> "8 295","real_id"=>29,),
"30"=>array("name_ru"=>"Гурджаани","name_en"=>"Gurjaani","name_href"=> "ge/population-of-gurjaani","count"=> "8 024","real_id"=>30,),
"31"=>array("name_ru"=>"Мцхета","name_en"=>"Mtskheta","name_href"=> "ge/population-of-mtskheta","count"=> "7 940","real_id"=>31,),
"32"=>array("name_ru"=>"Кварели","name_en"=>"Kvareli","name_href"=> "ge/population-of-kvareli","count"=> "7 739","real_id"=>32,),
"33"=>array("name_ru"=>"Гудаута","name_en"=>"Gudauta","name_href"=> "ge/population-of-gudauta","count"=> "7 738","real_id"=>33,),
"34"=>array("name_ru"=>"Гали","name_en"=>"Gali","name_href"=> "ge/population-of-gali","count"=> "7 605","real_id"=>34,),
"35"=>array("name_ru"=>"Ахмета","name_en"=>"Ahmet","name_href"=> "ge/population-of-ahmet","count"=> "7 105","real_id"=>35,),
"36"=>array("name_ru"=>"Карели","name_en"=>"Kareli","name_href"=> "ge/population-of-kareli","count"=> "6 654","real_id"=>36,),
"37"=>array("name_ru"=>"Ланчхути","name_en"=>"Lanchkhuti","name_href"=> "ge/population-of-lanchkhuti","count"=> "6 395","real_id"=>37,),
"38"=>array("name_ru"=>"Душети","name_en"=>"Dusheti","name_href"=> "ge/population-of-dusheti","count"=> "6 167","real_id"=>38,),
"39"=>array("name_ru"=>"Сачхере","name_en"=>"Sachkhere","name_href"=> "ge/population-of-sachkhere","count"=> "6 140","real_id"=>39,),
"40"=>array("name_ru"=>"Дедоплис-Цкаро","name_en"=>"Dedoplis-Tskaro","name_href"=> "ge/population-of-dedoplis-tskaro","count"=> "5 940","real_id"=>40,),
"41"=>array("name_ru"=>"Лагодехи","name_en"=>"Lagodekhi","name_href"=> "ge/population-of-lagodekhi","count"=> "5 918","real_id"=>41,),
"42"=>array("name_ru"=>"Очамчыра","name_en"=>"Ochamchira","name_href"=> "ge/population-of-ochamchira","count"=> "5 280","real_id"=>42,),
"43"=>array("name_ru"=>"Ниноцминда","name_en"=>"Ninotsminda","name_href"=> "ge/population-of-ninotsminda","count"=> "5 144","real_id"=>43,),
"44"=>array("name_ru"=>"Ткуарчал","name_en"=>"Tkuarchal","name_href"=> "ge/population-of-tkuarchal","count"=> "5 013","real_id"=>44,),
"45"=>array("name_ru"=>"Абаша","name_en"=>"Abasha","name_href"=> "ge/population-of-abasha","count"=> "4 941","real_id"=>45,),
"46"=>array("name_ru"=>"Цнори","name_en"=>"Tsnori","name_href"=> "ge/population-of-tsnori","count"=> "4 815","real_id"=>46,),
"47"=>array("name_ru"=>"Тержола","name_en"=>"Terjola","name_href"=> "ge/population-of-terjola","count"=> "4 644","real_id"=>47,),
"48"=>array("name_ru"=>"Мартвили","name_en"=>"Martvili","name_href"=> "ge/population-of-martvili","count"=> "4 425","real_id"=>48,),
"49"=>array("name_ru"=>"Хоби","name_en"=>"Hobie","name_href"=> "ge/population-of-hobie","count"=> "4 242","real_id"=>49,),
"50"=>array("name_ru"=>"Цаленджиха","name_en"=>"Tsalenjikha","name_href"=> "ge/population-of-tsalenjikha","count"=> "3 847","real_id"=>50,),
"51"=>array("name_ru"=>"Вани","name_en"=>"Vani","name_href"=> "ge/population-of-vani","count"=> "3 744","real_id"=>51,),
"52"=>array("name_ru"=>"Багдати","name_en"=>"Baghdadi","name_href"=> "ge/population-of-baghdadi","count"=> "3 707","real_id"=>52,),
"53"=>array("name_ru"=>"Вале","name_en"=>"Vale","name_href"=> "ge/population-of-vale","count"=> "3 646","real_id"=>53,),
"54"=>array("name_ru"=>"Тетри-Цкаро","name_en"=>"Tetri-Tskaro","name_href"=> "ge/population-of-tetri-tskaro","count"=> "3 093","real_id"=>54,),
"55"=>array("name_ru"=>"Дманиси","name_en"=>"Dmanisi","name_href"=> "ge/population-of-dmanisi","count"=> "2 661","real_id"=>55,),
"56"=>array("name_ru"=>"Они","name_en"=>"They","name_href"=> "ge/population-of-they","count"=> "2 656","real_id"=>56,),
"57"=>array("name_ru"=>"Цалка","name_en"=>"Tsalka","name_href"=> "ge/population-of-tsalka","count"=> "2 326","real_id"=>57,),
"58"=>array("name_ru"=>"Амбролаури","name_en"=>"Ambrolauri","name_href"=> "ge/population-of-ambrolauri","count"=> "2 047","real_id"=>58,),
"59"=>array("name_ru"=>"Новый Афон","name_en"=>"New Athos","name_href"=> "ge/population-of-newathos","count"=> "1 518","real_id"=>59,),
"60"=>array("name_ru"=>"Сигнахи","name_en"=>"Sighnaghi","name_href"=> "ge/population-of-sighnaghi","count"=> "1 485","real_id"=>60,),
"61"=>array("name_ru"=>"Цагери","name_en"=>"Tsageri","name_href"=> "ge/population-of-tsageri","count"=> "1 320","real_id"=>61,),
"62"=>array("name_ru"=>"Джвари","name_en"=>"Jvari","name_href"=> "ge/population-of-jvari","count"=> "763","real_id"=>62,),
"63"=>array("name_ru"=>"Тбилиси","name_en"=>"Tbilisi","name_href"=> "ge/population-of-tbilisi","count"=> "1 062 282","real_id"=>63,),
"64"=>array("name_ru"=>"Батуми","name_en"=>"Batumi","name_href"=> "ge/population-of-batumi","count"=> "152 839","real_id"=>64,),
"65"=>array("name_ru"=>"Кутаиси","name_en"=>"Kutaisi","name_href"=> "ge/population-of-kutaisi","count"=> "147 635","real_id"=>65,),
"66"=>array("name_ru"=>"Рустави","name_en"=>"Rustavi","name_href"=> "ge/population-of-rustavi","count"=> "125 103","real_id"=>66,),
"67"=>array("name_ru"=>"Сухум","name_en"=>"Sukhum","name_href"=> "ge/population-of-sukhum","count"=> "62 914","real_id"=>67,)
);

?>