<?php
//Греция 65 
$libgr = array ( 
"1"=>array("name_ru"=>"Афины","name_en"=>"Athens","name_href" => "gr/population-of-athens","count" => "3 168 846","real_id" =>1,),
"2"=>array("name_ru"=>"Салоники","name_en"=>"Thessaloniki","name_href" => "gr/population-of-thessaloniki","count" => "806 635","real_id" =>2,),
"3"=>array("name_ru"=>"Патры","name_en"=>"Patras","name_href" => "gr/population-of-patras","count" => "195 265","real_id" =>3,),
"4"=>array("name_ru"=>"Ираклион","name_en"=>"Heraklion","name_href" => "gr/population-of-heraklion","count" => "157 452","real_id" =>4,),
"5"=>array("name_ru"=>"Лариса","name_en"=>"Larissa","name_href" => "gr/population-of-larissa","count" => "144 651","real_id" =>5,),
"6"=>array("name_ru"=>"Волос","name_en"=>"Hair","name_href" => "gr/population-of-hair","count" => "130 994","real_id" =>6,),
"7"=>array("name_ru"=>"Ахарнес","name_en"=>"Acharnes","name_href" => "gr/population-of-acharnes","count" => "100 723","real_id" =>7,),
"8"=>array("name_ru"=>"Ханья","name_en"=>"Chania","name_href" => "gr/population-of-chania","count" => "88 525","real_id" =>8,),
"9"=>array("name_ru"=>"Янина","name_en"=>"Ioannina","name_href" => "gr/population-of-ioannina","count" => "85 803","real_id" =>9,),
"10"=>array("name_ru"=>"Халкида","name_en"=>"Chalkida","name_href" => "gr/population-of-chalkida","count" => "74 564","real_id" =>10,),
"11"=>array("name_ru"=>"Трикала","name_en"=>"Trikala","name_href" => "gr/population-of-trikala","count" => "61 653","real_id" =>11,),
"12"=>array("name_ru"=>"Агринион","name_en"=>"Agrinio","name_href" => "gr/population-of-agrinio","count" => "61 349","real_id" =>12,),
"13"=>array("name_ru"=>"Катерини","name_en"=>"Katerinis","name_href" => "gr/population-of-katerinis","count" => "60 854","real_id" =>13,),
"14"=>array("name_ru"=>"Каламата","name_en"=>"Kalamata","name_href" => "gr/population-of-kalamata","count" => "59 625","real_id" =>14,),
"15"=>array("name_ru"=>"Серре","name_en"=>"Serra","name_href" => "gr/population-of-serra","count" => "58 287","real_id" =>15,),
"16"=>array("name_ru"=>"Александруполис","name_en"=>"Alexandroupolis","name_href" => "gr/population-of-alexandroupolis","count" => "57 812","real_id" =>16,),
"17"=>array("name_ru"=>"Ксанти","name_en"=>"Xanthi","name_href" => "gr/population-of-xanthi","count" => "56 122","real_id" =>17,),
"18"=>array("name_ru"=>"Кавала","name_en"=>"Kavala","name_href" => "gr/population-of-kavala","count" => "54 027","real_id" =>18,),
"19"=>array("name_ru"=>"Ламия","name_en"=>"Lamia","name_href" => "gr/population-of-lamia","count" => "52 006","real_id" =>19,),
"20"=>array("name_ru"=>"Комотини","name_en"=>"Komotini","name_href" => "gr/population-of-komotini","count" => "50 990","real_id" =>20,),
"21"=>array("name_ru"=>"Родос","name_en"=>"Rhodes","name_href" => "gr/population-of-rhodes","count" => "49 541","real_id" =>21,),
"22"=>array("name_ru"=>"Драма","name_en"=>"Drama","name_href" => "gr/population-of-drama","count" => "44 823","real_id" =>22,),
"23"=>array("name_ru"=>"Верия","name_en"=>"Veria","name_href" => "gr/population-of-veria","count" => "43 158","real_id" =>23,),
"24"=>array("name_ru"=>"Козани","name_en"=>"Kozani","name_href" => "gr/population-of-kozani","count" => "41 066","real_id" =>24,),
"25"=>array("name_ru"=>"Керкира","name_en"=>"Corfu","name_href" => "gr/population-of-corfu","count" => "39 330","real_id" =>25,),
"26"=>array("name_ru"=>"Кардица","name_en"=>"Karditsa","name_href" => "gr/population-of-karditsa","count" => "38 554","real_id" =>26,),
"27"=>array("name_ru"=>"Саламина","name_en"=>"Salamina","name_href" => "gr/population-of-salamina","count" => "36 774","real_id" =>27,),
"28"=>array("name_ru"=>"Ретимнон","name_en"=>"Rethymno","name_href" => "gr/population-of-rethymno","count" => "35 715","real_id" =>28,),
"29"=>array("name_ru"=>"Хиос","name_en"=>"Chios","name_href" => "gr/population-of-chios","count" => "35 479","real_id" =>29,),
"30"=>array("name_ru"=>"Ано-Лиосия","name_en"=>"ANO-Liosia","name_href" => "gr/population-of-ano-liosia","count" => "33 565","real_id" =>30,),
"31"=>array("name_ru"=>"Птолемаида","name_en"=>"Ptolemais","name_href" => "gr/population-of-ptolemais","count" => "32 127","real_id" =>31,),
"32"=>array("name_ru"=>"Триполи","name_en"=>"Tripoli","name_href" => "gr/population-of-tripoli","count" => "30 866","real_id" =>32,),
"33"=>array("name_ru"=>"Аспропиргос","name_en"=>"Aspropyrgos","name_href" => "gr/population-of-aspropyrgos","count" => "30 251","real_id" =>33,),
"34"=>array("name_ru"=>"Коринф","name_en"=>"Corinth","name_href" => "gr/population-of-corinth","count" => "30 176","real_id" =>34,),
"35"=>array("name_ru"=>"Янница","name_en"=>"Giannitsa","name_href" => "gr/population-of-giannitsa","count" => "29 789","real_id" =>35,),
"36"=>array("name_ru"=>"Митилини","name_en"=>"Mytilene","name_href" => "gr/population-of-mytilene","count" => "27 871","real_id" =>36,),
"37"=>array("name_ru"=>"Эгио","name_en"=>"Aigio","name_href" => "gr/population-of-aigio","count" => "26 652","real_id" =>37,),
"38"=>array("name_ru"=>"Элевсин","name_en"=>"Eleusis","name_href" => "gr/population-of-eleusis","count" => "24 910","real_id" =>38,),
"39"=>array("name_ru"=>"Пиргос","name_en"=>"Pyrgos","name_href" => "gr/population-of-pyrgos","count" => "24 359","real_id" =>39,),
"40"=>array("name_ru"=>"Мегара","name_en"=>"Megara","name_href" => "gr/population-of-megara","count" => "23 456","real_id" =>40,),
"41"=>array("name_ru"=>"Килкис","name_en"=>"Kilkis","name_href" => "gr/population-of-kilkis","count" => "22 914","real_id" =>41,),
"42"=>array("name_ru"=>"Фивы","name_en"=>"Thebes","name_href" => "gr/population-of-thebes","count" => "22 883","real_id" =>42,),
"43"=>array("name_ru"=>"Аргос","name_en"=>"Argos","name_href" => "gr/population-of-argos","count" => "22 209","real_id" =>43,),
"44"=>array("name_ru"=>"Арта","name_en"=>"Art","name_href" => "gr/population-of-art","count" => "21 895","real_id" =>44,),
"45"=>array("name_ru"=>"Артемида","name_en"=>"Artemis","name_href" => "gr/population-of-artemis","count" => "21 488","real_id" =>45,),
"46"=>array("name_ru"=>"Левадия","name_en"=>"Levádeia","name_href" => "gr/population-of-levádeia","count" => "21 379","real_id" =>46,),
"47"=>array("name_ru"=>"Ореокастро","name_en"=>"Oraiókastro","name_href" => "gr/population-of-oraiókastro","count" => "20 852","real_id" =>47,),
"48"=>array("name_ru"=>"Кос","name_en"=>"KOs","name_href" => "gr/population-of-kos","count" => "19 432","real_id" =>48,),
"49"=>array("name_ru"=>"Коропи","name_en"=>"Koropi","name_href" => "gr/population-of-koropi","count" => "19 164","real_id" =>49,),
"50"=>array("name_ru"=>"Превеза","name_en"=>"Preveza","name_href" => "gr/population-of-preveza","count" => "19 042","real_id" =>50,),
"51"=>array("name_ru"=>"Спарта","name_en"=>"Sparta","name_href" => "gr/population-of-sparta","count" => "18 926","real_id" =>51,),
"52"=>array("name_ru"=>"Науса","name_en"=>"Naousa","name_href" => "gr/population-of-naousa","count" => "18 882","real_id" =>52,),
"53"=>array("name_ru"=>"Перея","name_en"=>"Perea","name_href" => "gr/population-of-perea","count" => "18 546","real_id" =>53,),
"54"=>array("name_ru"=>"Орестиада","name_en"=>"Orestiada","name_href" => "gr/population-of-orestiada","count" => "18 426","real_id" =>54,),
"55"=>array("name_ru"=>"Эдесса","name_en"=>"Edessa","name_href" => "gr/population-of-edessa","count" => "18 229","real_id" =>55,),
"56"=>array("name_ru"=>"Флорина","name_en"=>"Florina","name_href" => "gr/population-of-florina","count" => "17 686","real_id" =>56,),
"57"=>array("name_ru"=>"Амалиада","name_en"=>"Amaliada","name_href" => "gr/population-of-amaliada","count" => "16 763","real_id" =>57,),
"58"=>array("name_ru"=>"Паллини","name_en"=>"Pallini","name_href" => "gr/population-of-pallini","count" => "16 415","real_id" =>58,),
"59"=>array("name_ru"=>"Ферми","name_en"=>"Fermi","name_href" => "gr/population-of-fermi","count" => "16 004","real_id" =>59,),
"60"=>array("name_ru"=>"Эрмуполис","name_en"=>"Ermoupolis","name_href" => "gr/population-of-ermoupolis","count" => "15 870","real_id" =>60,),
"61"=>array("name_ru"=>"Неа-Макри","name_en"=>"Néa Mákri","name_href" => "gr/population-of-néa-mákri","count" => "15 554","real_id" =>61,),
"62"=>array("name_ru"=>"Александрия","name_en"=>"Alexandria","name_href" => "gr/population-of-alexandria","count" => "14 821","real_id" =>62,),
"63"=>array("name_ru"=>"Пеания","name_en"=>"Peania","name_href" => "gr/population-of-peania","count" => "14 595","real_id" =>63,),
"64"=>array("name_ru"=>"Каливия-Торику","name_en"=>"Kalývia Thorikoú","name_href" => "gr/population-of-kalývia-thorikoú","count" => "14 424","real_id" =>64,),
"65"=>array("name_ru"=>"Нафплион","name_en"=>"Nafplio","name_href" => "gr/population-of-nafplio","count" => "14 203","real_id" =>65,),
"66"=>array("name_ru"=>"Афины","name_en"=>"Athens","name_href" => "gr/population-of-athens","count" => "3 168 846","real_id" =>66,),
"67"=>array("name_ru"=>"Салоники","name_en"=>"Thessaloniki","name_href" => "gr/population-of-thessaloniki","count" => "806 635","real_id" =>67,),
"68"=>array("name_ru"=>"Патры","name_en"=>"Patras","name_href" => "gr/population-of-patras","count" => "195 265","real_id" =>68,),
"69"=>array("name_ru"=>"Ираклион","name_en"=>"Heraklion","name_href" => "gr/population-of-heraklion","count" => "157 452","real_id" =>69,),
"70"=>array("name_ru"=>"Лариса","name_en"=>"Larissa","name_href" => "gr/population-of-larissa","count" => "144 651","real_id" =>70,)
);

?>