<?php
//Габон 33 
$libga = array ( 
"1"=>array("name_ru"=>"Либревиль","name_en"=>"Libreville","name_href" => "ga/population-of-libreville","count" => "753 550","real_id" =>1,),
"2"=>array("name_ru"=>"Порт-Жантиль","name_en"=>"Port-Gentil","name_href" => "ga/population-of-port-gentil","count" => "142 280","real_id" =>2,),
"3"=>array("name_ru"=>"Франсвиль","name_en"=>"Franceville","name_href" => "ga/population-of-franceville","count" => "56 002","real_id" =>3,),
"4"=>array("name_ru"=>"Оем","name_en"=>"OEM","name_href" => "ga/population-of-oem","count" => "40 235","real_id" =>4,),
"5"=>array("name_ru"=>"Моанда","name_en"=>"Moanda","name_href" => "ga/population-of-moanda","count" => "39 298","real_id" =>5,),
"6"=>array("name_ru"=>"Муила","name_en"=>"Mouila","name_href" => "ga/population-of-mouila","count" => "29 286","real_id" =>6,),
"7"=>array("name_ru"=>"Ламбарене","name_en"=>"Lambaréné","name_href" => "ga/population-of-lambaréné","count" => "26 998","real_id" =>7,),
"8"=>array("name_ru"=>"Чибанга","name_en"=>"Chibanga","name_href" => "ga/population-of-chibanga","count" => "25 239","real_id" =>8,),
"9"=>array("name_ru"=>"Куламуту","name_en"=>"Kulamutu","name_href" => "ga/population-of-kulamutu","count" => "21 143","real_id" =>9,),
"10"=>array("name_ru"=>"Макоку","name_en"=>"Makoko","name_href" => "ga/population-of-makoko","count" => "17 688","real_id" =>10,),
"11"=>array("name_ru"=>"Битам","name_en"=>"Bits","name_href" => "ga/population-of-bits","count" => "13 421","real_id" =>11,),
"12"=>array("name_ru"=>"Тсогни","name_en"=>"Sogni","name_href" => "ga/population-of-sogni","count" => "12 977","real_id" =>12,),
"13"=>array("name_ru"=>"Гамба","name_en"=>"Gamba","name_href" => "ga/population-of-gamba","count" => "12 939","real_id" =>13,),
"14"=>array("name_ru"=>"Мунана","name_en"=>"Mounana","name_href" => "ga/population-of-mounana","count" => "11 443","real_id" =>14,),
"15"=>array("name_ru"=>"Нтум","name_en"=>"Ntoum","name_href" => "ga/population-of-ntoum","count" => "11 169","real_id" =>15,),
"16"=>array("name_ru"=>"Нкан","name_en"=>"Nkan","name_href" => "ga/population-of-nkan","count" => "11 113","real_id" =>16,),
"17"=>array("name_ru"=>"Ластурвиль","name_en"=>"Lastourville","name_href" => "ga/population-of-lastourville","count" => "10 871","real_id" =>17,),
"18"=>array("name_ru"=>"Оконджа","name_en"=>"Okonjo","name_href" => "ga/population-of-okonjo","count" => "9 326","real_id" =>18,),
"19"=>array("name_ru"=>"Нденде","name_en"=>"Ndende","name_href" => "ga/population-of-ndende","count" => "8 082","real_id" =>19,),
"20"=>array("name_ru"=>"Буе","name_en"=>"Buoy","name_href" => "ga/population-of-buoy","count" => "7 543","real_id" =>20,),
"21"=>array("name_ru"=>"Фугаму","name_en"=>"Fugamu","name_href" => "ga/population-of-fugamu","count" => "7 363","real_id" =>21,),
"22"=>array("name_ru"=>"Нджоле","name_en"=>"Ndjole","name_href" => "ga/population-of-ndjole","count" => "6 645","real_id" =>22,),
"23"=>array("name_ru"=>"Мбигу","name_en"=>"Mbigu","name_href" => "ga/population-of-mbigu","count" => "5 388","real_id" =>23,),
"24"=>array("name_ru"=>"Маюмба","name_en"=>"Mayumba","name_href" => "ga/population-of-mayumba","count" => "5 208","real_id" =>24,),
"25"=>array("name_ru"=>"Митзик","name_en"=>"Mitzic","name_href" => "ga/population-of-mitzic","count" => "5 064","real_id" =>25,),
"26"=>array("name_ru"=>"Мекамбо","name_en"=>"Mekambo","name_href" => "ga/population-of-mekambo","count" => "5 029","real_id" =>26,),
"27"=>array("name_ru"=>"Лекони","name_en"=>"Lekoni","name_href" => "ga/population-of-lekoni","count" => "4 669","real_id" =>27,),
"28"=>array("name_ru"=>"Мимонго","name_en"=>"Mimongo","name_href" => "ga/population-of-mimongo","count" => "4 310","real_id" =>28,),
"29"=>array("name_ru"=>"Минвул","name_en"=>"Minvul","name_href" => "ga/population-of-minvul","count" => "3 771","real_id" =>29,),
"30"=>array("name_ru"=>"Медунью","name_en"=>"Medouneu","name_href" => "ga/population-of-medouneu","count" => "2 514","real_id" =>30,),
"31"=>array("name_ru"=>"Омбуе","name_en"=>"Ombue","name_href" => "ga/population-of-ombue","count" => "2 173","real_id" =>31,),
"32"=>array("name_ru"=>"Кокобич","name_en"=>"Cocobeach","name_href" => "ga/population-of-cocobeach","count" => "2 155","real_id" =>32,),
"33"=>array("name_ru"=>"Канго","name_en"=>"Cango","name_href" => "ga/population-of-cango","count" => "1 975","real_id" =>33,),
"34"=>array("name_ru"=>"Либревиль","name_en"=>"Libreville","name_href" => "ga/population-of-libreville","count" => "753 550","real_id" =>34,),
"35"=>array("name_ru"=>"Порт-Жантиль","name_en"=>"Port-Gentil","name_href" => "ga/population-of-port-gentil","count" => "142 280","real_id" =>35,),
"36"=>array("name_ru"=>"Франсвиль","name_en"=>"Franceville","name_href" => "ga/population-of-franceville","count" => "56 002","real_id" =>36,),
"37"=>array("name_ru"=>"Оем","name_en"=>"OEM","name_href" => "ga/population-of-oem","count" => "40 235","real_id" =>37,),
"38"=>array("name_ru"=>"Моанда","name_en"=>"Moanda","name_href" => "ga/population-of-moanda","count" => "39 298","real_id" =>38,)
);

?>