<?php
//Венгрия 85
$libhu = array ( 
"1"=>array("name_ru"=>"Будапешт","name_en"=>"Budapest","name_href" => "hu/population-of-budapest","count" => "1 744 665","real_id" =>1,),
"2"=>array("name_ru"=>"Дебрецен","name_en"=>"Debrecen","name_href" => "hu/population-of-debrecen","count" => "203 914","real_id" =>2,),
"3"=>array("name_ru"=>"Сегед","name_en"=>"Szeged","name_href" => "hu/population-of-szeged","count" => "161 921","real_id" =>3,),
"4"=>array("name_ru"=>"Мишкольц","name_en"=>"Miskolc","name_href" => "hu/population-of-miskolc","count" => "161 265","real_id" =>4,),
"5"=>array("name_ru"=>"Печ","name_en"=>"PECs","name_href" => "hu/population-of-pecs","count" => "146 581","real_id" =>5,),
"6"=>array("name_ru"=>"Дьёр","name_en"=>"Gyor","name_href" => "hu/population-of-gyor","count" => "128 902","real_id" =>6,),
"7"=>array("name_ru"=>"Ньиредьхаза","name_en"=>"Nyíregyháza","name_href" => "hu/population-of-nyíregyháza","count" => "118 164","real_id" =>7,),
"8"=>array("name_ru"=>"Кечкемет","name_en"=>"Kecskemet","name_href" => "hu/population-of-kecskemet","count" => "112 071","real_id" =>8,),
"9"=>array("name_ru"=>"Секешфехервар","name_en"=>"Székesfehérvár","name_href" => "hu/population-of-székesfehérvár","count" => "99 060","real_id" =>9,),
"10"=>array("name_ru"=>"Сомбатхей","name_en"=>"Szombathely","name_href" => "hu/population-of-szombathely","count" => "77 566","real_id" =>10,),
"11"=>array("name_ru"=>"Сольнок","name_en"=>"Szolnok","name_href" => "hu/population-of-szolnok","count" => "73 106","real_id" =>11,),
"12"=>array("name_ru"=>"Татабанья","name_en"=>"Tatabánya","name_href" => "hu/population-of-tatabánya","count" => "67 043","real_id" =>12,),
"13"=>array("name_ru"=>"Капошвар","name_en"=>"Kaposvar","name_href" => "hu/population-of-kaposvar","count" => "64 872","real_id" =>13,),
"14"=>array("name_ru"=>"Эрд","name_en"=>"ERD","name_href" => "hu/population-of-erd","count" => "63 294","real_id" =>14,),
"15"=>array("name_ru"=>"Шопрон","name_en"=>"Sopron","name_href" => "hu/population-of-sopron","count" => "61 249","real_id" =>15,),
"16"=>array("name_ru"=>"Веспрем","name_en"=>"Veszprém","name_href" => "hu/population-of-veszprém","count" => "60 788","real_id" =>16,),
"17"=>array("name_ru"=>"Бекешчаба","name_en"=>"Békéscsaba","name_href" => "hu/population-of-békéscsaba","count" => "60 571","real_id" =>17,),
"18"=>array("name_ru"=>"Залаэгерсег","name_en"=>"Zalaegerszeg","name_href" => "hu/population-of-zalaegerszeg","count" => "59 275","real_id" =>18,),
"19"=>array("name_ru"=>"Эгер","name_en"=>"Eger","name_href" => "hu/population-of-eger","count" => "54 527","real_id" =>19,),
"20"=>array("name_ru"=>"Ходмезевашархей","name_en"=>"Hodmezovasarhely","name_href" => "hu/population-of-hodmezovasarhely","count" => "48 909","real_id" =>20,),
"21"=>array("name_ru"=>"Надьканижа","name_en"=>"Nagykanizsa","name_href" => "hu/population-of-nagykanizsa","count" => "48 664","real_id" =>21,),
"22"=>array("name_ru"=>"Дунауйварош","name_en"=>"Dunaújváros","name_href" => "hu/population-of-dunaújváros","count" => "46 320","real_id" =>22,),
"23"=>array("name_ru"=>"Хайдусобосло","name_en"=>"Hajdúszoboszló","name_href" => "hu/population-of-hajdúszoboszló","count" => "44 795","real_id" =>23,),
"24"=>array("name_ru"=>"Цеглед","name_en"=>"Cegled","name_href" => "hu/population-of-cegled","count" => "38 220","real_id" =>24,),
"25"=>array("name_ru"=>"Байя","name_en"=>"Bahia","name_href" => "hu/population-of-bahia","count" => "37 690","real_id" =>25,),
"26"=>array("name_ru"=>"Шальготарьян","name_en"=>"Salgotarjan","name_href" => "hu/population-of-salgotarjan","count" => "37 166","real_id" =>26,),
"27"=>array("name_ru"=>"Озд","name_en"=>"Ued","name_href" => "hu/population-of-ued","count" => "37 040","real_id" =>27,),
"28"=>array("name_ru"=>"Сексард","name_en"=>"Szekszárd","name_href" => "hu/population-of-szekszárd","count" => "33 720","real_id" =>28,),
"29"=>array("name_ru"=>"Дьёндьёш","name_en"=>"Gyöngyös","name_href" => "hu/population-of-gyöngyös","count" => "33 553","real_id" =>29,),
"30"=>array("name_ru"=>"Вац","name_en"=>"VAC","name_href" => "hu/population-of-vac","count" => "33 323","real_id" =>30,),
"31"=>array("name_ru"=>"Папа","name_en"=>"Dad","name_href" => "hu/population-of-dad","count" => "33 080","real_id" =>31,),
"32"=>array("name_ru"=>"Гёдёллё","name_en"=>"Gödöllő","name_href" => "hu/population-of-gödöllő","count" => "32 495","real_id" =>32,),
"33"=>array("name_ru"=>"Дьюла","name_en"=>"Gyula","name_href" => "hu/population-of-gyula","count" => "32 239","real_id" =>33,),
"34"=>array("name_ru"=>"Хайдубёсёрмень","name_en"=>"Hajduboszormeny","name_href" => "hu/population-of-hajduboszormeny","count" => "32 228","real_id" =>34,),
"35"=>array("name_ru"=>"Сентеш","name_en"=>"Szentes","name_href" => "hu/population-of-szentes","count" => "31 082","real_id" =>35,),
"36"=>array("name_ru"=>"Кишкунфеледьхаза","name_en"=>"Kiskunfélegyháza","name_href" => "hu/population-of-kiskunfélegyháza","count" => "30 946","real_id" =>36,),
"37"=>array("name_ru"=>"Мошонмадьяровар","name_en"=>"Mosonmagyaróvár","name_href" => "hu/population-of-mosonmagyaróvár","count" => "30 840","real_id" =>37,),
"38"=>array("name_ru"=>"Казинцбарцика","name_en"=>"Kazincbarcika","name_href" => "hu/population-of-kazincbarcika","count" => "30 709","real_id" =>38,),
"39"=>array("name_ru"=>"Орошхаза","name_en"=>"Orosháza","name_href" => "hu/population-of-orosháza","count" => "30 688","real_id" =>39,),
"40"=>array("name_ru"=>"Айка","name_en"=>"IKE","name_href" => "hu/population-of-ike","count" => "29 685","real_id" =>40,),
"41"=>array("name_ru"=>"Эстергом","name_en"=>"Esztergom","name_href" => "hu/population-of-esztergom","count" => "28 412","real_id" =>41,),
"42"=>array("name_ru"=>"Будаёрш","name_en"=>"Budaors","name_href" => "hu/population-of-budaors","count" => "27 655","real_id" =>42,),
"43"=>array("name_ru"=>"Шиофок","name_en"=>"Siófok","name_href" => "hu/population-of-siófok","count" => "25 355","real_id" =>43,),
"44"=>array("name_ru"=>"Мако","name_en"=>"Mako","name_href" => "hu/population-of-mako","count" => "24 403","real_id" =>44,),
"45"=>array("name_ru"=>"Сентендре","name_en"=>"Szentendre","name_href" => "hu/population-of-szentendre","count" => "24 010","real_id" =>45,),
"46"=>array("name_ru"=>"Кестхей","name_en"=>"Keszthely","name_href" => "hu/population-of-keszthely","count" => "20 215","real_id" =>46,),
"47"=>array("name_ru"=>"Пакш","name_en"=>"Paks","name_href" => "hu/population-of-paks","count" => "19 387","real_id" =>47,),
"48"=>array("name_ru"=>"Сарваш","name_en"=>"Szarvas","name_href" => "hu/population-of-szarvas","count" => "18 653","real_id" =>48,),
"49"=>array("name_ru"=>"Калоча","name_en"=>"Kalocsa","name_href" => "hu/population-of-kalocsa","count" => "18 187","real_id" =>49,),
"50"=>array("name_ru"=>"Шаторальяуйхей","name_en"=>"Sátoraljaújhely","name_href" => "hu/population-of-sátoraljaújhely","count" => "17 992","real_id" =>50,),
"51"=>array("name_ru"=>"Мезёкёвешд","name_en"=>"Mezőkövesd","name_href" => "hu/population-of-mezőkövesd","count" => "17 841","real_id" =>51,),
"52"=>array("name_ru"=>"Чонград","name_en"=>"Csongrad","name_href" => "hu/population-of-csongrad","count" => "17 686","real_id" =>52,),
"53"=>array("name_ru"=>"Тапольца","name_en"=>"Tapolca","name_href" => "hu/population-of-tapolca","count" => "15 823","real_id" =>53,),
"54"=>array("name_ru"=>"Абонь","name_en"=>"Abony","name_href" => "hu/population-of-abony","count" => "15 814","real_id" =>54,),
"55"=>array("name_ru"=>"Шарвар","name_en"=>"Sárvár","name_href" => "hu/population-of-sárvár","count" => "15 545","real_id" =>55,),
"56"=>array("name_ru"=>"Кишкёрёш","name_en"=>"Kiskoros","name_href" => "hu/population-of-kiskoros","count" => "15 131","real_id" =>56,),
"57"=>array("name_ru"=>"Шарошпатак","name_en"=>"Sárospatak","name_href" => "hu/population-of-sárospatak","count" => "14 505","real_id" =>57,),
"58"=>array("name_ru"=>"Балатонфюред","name_en"=>"Balatonfüred","name_href" => "hu/population-of-balatonfüred","count" => "13 306","real_id" =>58,),
"59"=>array("name_ru"=>"Ньирбатор","name_en"=>"Nyirbator","name_href" => "hu/population-of-nyirbator","count" => "13 191","real_id" =>59,),
"60"=>array("name_ru"=>"Будакеси","name_en"=>"Budakeszi","name_href" => "hu/population-of-budakeszi","count" => "12 924","real_id" =>60,),
"61"=>array("name_ru"=>"Бичке","name_en"=>"Bicske","name_href" => "hu/population-of-bicske","count" => "12 767","real_id" =>61,),
"62"=>array("name_ru"=>"Альбертирша","name_en"=>"Albertirsa","name_href" => "hu/population-of-albertirsa","count" => "12 416","real_id" =>62,),
"63"=>array("name_ru"=>"Верешедьхаз","name_en"=>"Veresegyhaz","name_href" => "hu/population-of-veresegyhaz","count" => "11 348","real_id" =>63,),
"64"=>array("name_ru"=>"Капувар","name_en"=>"Kapuvar","name_href" => "hu/population-of-kapuvar","count" => "10 684","real_id" =>64,),
"65"=>array("name_ru"=>"Сегхалом","name_en"=>"Szeghalom","name_href" => "hu/population-of-szeghalom","count" => "10 151","real_id" =>65,),
"66"=>array("name_ru"=>"Биаторбадь","name_en"=>"Biatorbágy","name_href" => "hu/population-of-biatorbágy","count" => "9 523","real_id" =>66,),
"67"=>array("name_ru"=>"Дунафёльдвар","name_en"=>"Dunaföldvár","name_href" => "hu/population-of-dunaföldvár","count" => "9 320","real_id" =>67,),
"68"=>array("name_ru"=>"Балатоналмади","name_en"=>"Balatonalmadi","name_href" => "hu/population-of-balatonalmadi","count" => "8 542","real_id" =>68,),
"69"=>array("name_ru"=>"Заласентгрот","name_en"=>"Zalaszentgrót","name_href" => "hu/population-of-zalaszentgrót","count" => "7 881","real_id" =>69,),
"70"=>array("name_ru"=>"Зирц","name_en"=>"Zirc","name_href" => "hu/population-of-zirc","count" => "7 445","real_id" =>70,),
"71"=>array("name_ru"=>"Киштелек","name_en"=>"Kistelek","name_href" => "hu/population-of-kistelek","count" => "7 156","real_id" =>71,),
"72"=>array("name_ru"=>"Дони-Михоляц","name_en"=>"Doni-Miholjac","name_href" => "hu/population-of-doni-miholjac","count" => "6 680","real_id" =>72,),
"73"=>array("name_ru"=>"Асод","name_en"=>"Asod","name_href" => "hu/population-of-asod","count" => "6 026","real_id" =>73,),
"74"=>array("name_ru"=>"Жамбек","name_en"=>"Zsámbék","name_href" => "hu/population-of-zsámbék","count" => "5 395","real_id" =>74,),
"75"=>array("name_ru"=>"Абадсалок","name_en"=>"Abádszalók","name_href" => "hu/population-of-abádszalók","count" => "5 079","real_id" =>75,),
"76"=>array("name_ru"=>"Токай","name_en"=>"Tokai","name_href" => "hu/population-of-tokai","count" => "4 514","real_id" =>76,),
"77"=>array("name_ru"=>"Балатонфюзфе","name_en"=>"Balatonfuzfo","name_href" => "hu/population-of-balatonfuzfo","count" => "4 223","real_id" =>77,),
"78"=>array("name_ru"=>"Абауйсанто","name_en"=>"Abaújszántó","name_href" => "hu/population-of-abaújszántó","count" => "3 407","real_id" =>78,),
"79"=>array("name_ru"=>"Залалёвё","name_en"=>"Zalalövő","name_href" => "hu/population-of-zalalövő","count" => "3 258","real_id" =>79,),
"80"=>array("name_ru"=>"Белапатфальва","name_en"=>"Belapatfalva","name_href" => "hu/population-of-belapatfalva","count" => "3 041","real_id" =>80,),
"81"=>array("name_ru"=>"Замарди","name_en"=>"Zamárdi","name_href" => "hu/population-of-zamárdi","count" => "2 438","real_id" =>81,),
"82"=>array("name_ru"=>"Балатонфельвар","name_en"=>"Balatonfeldvar","name_href" => "hu/population-of-balatonfeldvar","count" => "2 069","real_id" =>82,),
"83"=>array("name_ru"=>"Балатоншемес","name_en"=>"Balatonszemes","name_href" => "hu/population-of-balatonszemes","count" => "1 774","real_id" =>83,),
"84"=>array("name_ru"=>"Балатонендред","name_en"=>"Balachandran","name_href" => "hu/population-of-balachandran","count" => "1 370","real_id" =>84,),
"85"=>array("name_ru"=>"Балатонакали","name_en"=>"Balatonakali","name_href" => "hu/population-of-balatonakali","count" => "743","real_id" =>85,),
"86"=>array("name_ru"=>"Будапешт","name_en"=>"Budapest","name_href" => "hu/population-of-budapest","count" => "1 744 665","real_id" =>86,),
"87"=>array("name_ru"=>"Дебрецен","name_en"=>"Debrecen","name_href" => "hu/population-of-debrecen","count" => "203 914","real_id" =>87,),
"88"=>array("name_ru"=>"Сегед","name_en"=>"Szeged","name_href" => "hu/population-of-szeged","count" => "161 921","real_id" =>88,),
"89"=>array("name_ru"=>"Мишкольц","name_en"=>"Miskolc","name_href" => "hu/population-of-miskolc","count" => "161 265","real_id" =>89,),
"90"=>array("name_ru"=>"Печ","name_en"=>"PECs","name_href" => "hu/population-of-pecs","count" => "146 581","real_id" =>90,)
);

?>