<?php
//Ирландия 85
$libie = array ( 
"1"=>array("name_ru"=>"Дублин","name_en"=>"Dublin","name_href" =>"ie/population-of-dublin","count" =>"506 211","real_id" =>1,),
"2"=>array("name_ru"=>"Корк","name_en"=>"Cork","name_href" =>"ie/population-of-cork","count" =>"190 384","real_id" =>2,),
"3"=>array("name_ru"=>"Лимерик","name_en"=>"Limerick","name_href" =>"ie/population-of-limerick","count" =>"90 757","real_id" =>3,),
"4"=>array("name_ru"=>"Голуэй","name_en"=>"Galway","name_href" =>"ie/population-of-galway","count" =>"71 983","real_id" =>4,),
"5"=>array("name_ru"=>"Уотерфорд","name_en"=>"Waterford","name_href" =>"ie/population-of-waterford","count" =>"49 213","real_id" =>5,),
"6"=>array("name_ru"=>"Дроэда","name_en"=>"Drogheda","name_href" =>"ie/population-of-drogheda","count" =>"35 090","real_id" =>6,),
"7"=>array("name_ru"=>"Дандолк","name_en"=>"Dundalk","name_href" =>"ie/population-of-dundalk","count" =>"35 085","real_id" =>7,),
"8"=>array("name_ru"=>"Брей","name_en"=>"Bray","name_href" =>"ie/population-of-bray","count" =>"31 901","real_id" =>8,),
"9"=>array("name_ru"=>"Ан-Уавь","name_en"=>"Navan","name_href" =>"ie/population-of-navan","count" =>"24 851","real_id" =>9,),
"10"=>array("name_ru"=>"Эннис","name_en"=>"Ennis","name_href" =>"ie/population-of-ennis","count" =>"24 253","real_id" =>10,),
"11"=>array("name_ru"=>"Килкенни","name_en"=>"Kilkenny","name_href" =>"ie/population-of-kilkenny","count" =>"22 179","real_id" =>11,),
"12"=>array("name_ru"=>"Карлоу","name_en"=>"Carlow","name_href" =>"ie/population-of-carlow","count" =>"20 724","real_id" =>12,),
"13"=>array("name_ru"=>"Трали","name_en"=>"Tralee","name_href" =>"ie/population-of-tralee","count" =>"20 288","real_id" =>13,),
"14"=>array("name_ru"=>"Нейс","name_en"=>"Naas","name_href" =>"ie/population-of-naas","count" =>"20 044","real_id" =>14,),
"15"=>array("name_ru"=>"Слайго","name_en"=>"Sligo","name_href" =>"ie/population-of-sligo","count" =>"19 402","real_id" =>15,),
"16"=>array("name_ru"=>"Дрихад-Нуа","name_en"=>"Newbridge","name_href" =>"ie/population-of-newbridge","count" =>"18 520","real_id" =>16,),
"17"=>array("name_ru"=>"Маллингар","name_en"=>"Mullingar","name_href" =>"ie/population-of-mullingar","count" =>"18 416","real_id" =>17,),
"18"=>array("name_ru"=>"Уэксфорд","name_en"=>"Wexford","name_href" =>"ie/population-of-wexford","count" =>"18 163","real_id" =>18,),
"19"=>array("name_ru"=>"Леттеркенни","name_en"=>"Letterkenny","name_href" =>"ie/population-of-letterkenny","count" =>"17 586","real_id" =>19,),
"20"=>array("name_ru"=>"Атлон","name_en"=>"Athlone","name_href" =>"ie/population-of-athlone","count" =>"17 544","real_id" =>20,),
"21"=>array("name_ru"=>"Клонмел","name_en"=>"Clonmel","name_href" =>"ie/population-of-clonmel","count" =>"17 008","real_id" =>21,),
"22"=>array("name_ru"=>"Баллинколлиг","name_en"=>"Ballincollig","name_href" =>"ie/population-of-ballincollig","count" =>"16 308","real_id" =>22,),
"23"=>array("name_ru"=>"Балбригган","name_en"=>"Balbriggan","name_href" =>"ie/population-of-balbriggan","count" =>"15 559","real_id" =>23,),
"24"=>array("name_ru"=>"Лейкслип","name_en"=>"Leixlip","name_href" =>"ie/population-of-leixlip","count" =>"14 676","real_id" =>24,),
"25"=>array("name_ru"=>"Порт-Лиише","name_en"=>"Portlaoise","name_href" =>"ie/population-of-portlaoise","count" =>"14 613","real_id" =>25,),
"26"=>array("name_ru"=>"Грейстонс","name_en"=>"Greystones","name_href" =>"ie/population-of-greystones","count" =>"14 569","real_id" =>26,),
"27"=>array("name_ru"=>"Килларни","name_en"=>"Killarney","name_href" =>"ie/population-of-killarney","count" =>"13 426","real_id" =>27,),
"28"=>array("name_ru"=>"Талламор","name_en"=>"Tullamore","name_href" =>"ie/population-of-tullamore","count" =>"12 927","real_id" =>28,),
"29"=>array("name_ru"=>"Каслбар","name_en"=>"Castlebar","name_href" =>"ie/population-of-castlebar","count" =>"11 891","real_id" =>29,),
"30"=>array("name_ru"=>"Арклоу","name_en"=>"Arklow","name_href" =>"ie/population-of-arklow","count" =>"11 759","real_id" =>30,),
"31"=>array("name_ru"=>"Ков","name_en"=>"Cobh","name_href" =>"ie/population-of-cobh","count" =>"11 303","real_id" =>31,),
"32"=>array("name_ru"=>"Баллина","name_en"=>"Ballina","name_href" =>"ie/population-of-ballina","count" =>"10 409","real_id" =>32,),
"33"=>array("name_ru"=>"Маллоу","name_en"=>"Mallow","name_href" =>"ie/population-of-mallow","count" =>"10 241","real_id" =>33,),
"34"=>array("name_ru"=>"Уиклоу","name_en"=>"Wicklow","name_href" =>"ie/population-of-wicklow","count" =>"10 070","real_id" =>34,),
"35"=>array("name_ru"=>"Мидлтон","name_en"=>"Midleton","name_href" =>"ie/population-of-midleton","count" =>"10 048","real_id" =>35,),
"36"=>array("name_ru"=>"Трамор","name_en"=>"Tramore","name_href" =>"ie/population-of-tramore","count" =>"9 634","real_id" =>36,),
"37"=>array("name_ru"=>"Эннискорти","name_en"=>"Enniscorthy","name_href" =>"ie/population-of-enniscorthy","count" =>"9 538","real_id" =>37,),
"38"=>array("name_ru"=>"Шаннон","name_en"=>"Shannon","name_href" =>"ie/population-of-shannon","count" =>"9 222","real_id" =>38,),
"39"=>array("name_ru"=>"Лонгфорд","name_en"=>"Longford","name_href" =>"ie/population-of-longford","count" =>"8 836","real_id" =>39,),
"40"=>array("name_ru"=>"Дангарван","name_en"=>"Dungarvan","name_href" =>"ie/population-of-dungarvan","count" =>"8 362","real_id" =>40,),
"41"=>array("name_ru"=>"Атай","name_en"=>"Athy","name_href" =>"ie/population-of-athy","count" =>"8 218","real_id" =>41,),
"42"=>array("name_ru"=>"Каван","name_en"=>"Cavan","name_href" =>"ie/population-of-cavan","count" =>"7 883","real_id" =>42,),
"43"=>array("name_ru"=>"Нина","name_en"=>"Nenagh","name_href" =>"ie/population-of-nenagh","count" =>"7 751","real_id" =>43,),
"44"=>array("name_ru"=>"Нью-Росс","name_en"=>"New Ross","name_href" =>"ie/population-of-new-ross","count" =>"7 709","real_id" =>44,),
"45"=>array("name_ru"=>"Тёрлс","name_en"=>"Thurles","name_href" =>"ie/population-of-thurles","count" =>"7 682","real_id" =>45,),
"46"=>array("name_ru"=>"Гори","name_en"=>"Gorey","name_href" =>"ie/population-of-gorey","count" =>"7 193","real_id" =>46,),
"47"=>array("name_ru"=>"Трим","name_en"=>"Trim","name_href" =>"ie/population-of-trim","count" =>"6 870","real_id" =>47,),
"48"=>array("name_ru"=>"Йол","name_en"=>"Youghal","name_href" =>"ie/population-of-youghal","count" =>"6 785","real_id" =>48,),
"49"=>array("name_ru"=>"Монахан","name_en"=>"Monaghan","name_href" =>"ie/population-of-monaghan","count" =>"6 710","real_id" =>49,),
"50"=>array("name_ru"=>"Баллинасло","name_en"=>"Ballinasloe","name_href" =>"ie/population-of-ballinasloe","count" =>"6 303","real_id" =>50,),
"51"=>array("name_ru"=>"Банкрана","name_en"=>"Buncrana","name_href" =>"ie/population-of-buncrana","count" =>"5 911","real_id" =>51,),
"52"=>array("name_ru"=>"Каррик-он-Шур","name_en"=>"Carrick-on-Suir","name_href" =>"ie/population-of-carrick-on-suir","count" =>"5 906","real_id" =>52,),
"53"=>array("name_ru"=>"Идендерри","name_en"=>"Edenderry","name_href" =>"ie/population-of-edenderry","count" =>"5 888","real_id" =>53,),
"54"=>array("name_ru"=>"Фермой","name_en"=>"Fermoy","name_href" =>"ie/population-of-fermoy","count" =>"5 873","real_id" =>54,),
"55"=>array("name_ru"=>"Бандон","name_en"=>"Bandon","name_href" =>"ie/population-of-bandon","count" =>"5 822","real_id" =>55,),
"56"=>array("name_ru"=>"Уэстпорт","name_en"=>"Westport","name_href" =>"ie/population-of-westport","count" =>"5 475","real_id" =>56,),
"57"=>array("name_ru"=>"Келс","name_en"=>"Kells","name_href" =>"ie/population-of-kells","count" =>"5 248","real_id" =>57,),
"58"=>array("name_ru"=>"Пассидж-Уэст","name_en"=>"Passage West","name_href" =>"ie/population-of-passage-west","count" =>"5 203","real_id" =>58,),
"59"=>array("name_ru"=>"Бирр","name_en"=>"Birr","name_href" =>"ie/population-of-birr","count" =>"5 081","real_id" =>59,),
"60"=>array("name_ru"=>"Типперэри","name_en"=>"Tipperary","name_href" =>"ie/population-of-tipperary","count" =>"5 065","real_id" =>60,),
"61"=>array("name_ru"=>"Лохрей","name_en"=>"Loughrea","name_href" =>"ie/population-of-loughrea","count" =>"4 532","real_id" =>61,),
"62"=>array("name_ru"=>"Каррикмакросс","name_en"=>"Carrickmacross","name_href" =>"ie/population-of-carrickmacross","count" =>"4 387","real_id" =>62,),
"63"=>array("name_ru"=>"Арди","name_en"=>"Ardee","name_href" =>"ie/population-of-ardee","count" =>"4 318","real_id" =>63,),
"64"=>array("name_ru"=>"Клонакилти","name_en"=>"Clonakilty","name_href" =>"ie/population-of-clonakilty","count" =>"4 154","real_id" =>64,),
"65"=>array("name_ru"=>"Кинсейл","name_en"=>"Kinsale","name_href" =>"ie/population-of-kinsale","count" =>"4 099","real_id" =>65,),
"66"=>array("name_ru"=>"Маунтмеллик","name_en"=>"Mountmellick","name_href" =>"ie/population-of-mountmellick","count" =>"4 069","real_id" =>66,),
"67"=>array("name_ru"=>"Листоуэл","name_en"=>"Listowel","name_href" =>"ie/population-of-listowel","count" =>"3 900","real_id" =>67,),
"68"=>array("name_ru"=>"Макрум","name_en"=>"Macroom","name_href" =>"ie/population-of-macroom","count" =>"3 553","real_id" =>68,),
"69"=>array("name_ru"=>"Бантри","name_en"=>"Bantry","name_href" =>"ie/population-of-bantry","count" =>"3 309","real_id" =>69,),
"70"=>array("name_ru"=>"Каслблейни","name_en"=>"Castleblayney","name_href" =>"ie/population-of-castleblayney","count" =>"3 124","real_id" =>70,),
"71"=>array("name_ru"=>"Туам","name_en"=>"Tuam","name_href" =>"ie/population-of-tuam","count" =>"2 997","real_id" =>71,),
"72"=>array("name_ru"=>"Кашел","name_en"=>"Cashel","name_href" =>"ie/population-of-cashel","count" =>"2 936","real_id" =>72,),
"73"=>array("name_ru"=>"Мине-Бег","name_en"=>"Muine Bheag","name_href" =>"ie/population-of-muine-bheag","count" =>"2 735","real_id" =>73,),
"74"=>array("name_ru"=>"Килраш","name_en"=>"Kilrush","name_href" =>"ie/population-of-kilrush","count" =>"2 694","real_id" =>74,),
"75"=>array("name_ru"=>"Баллишаннон","name_en"=>"Ballyshannon","name_href" =>"ie/population-of-ballyshannon","count" =>"2 686","real_id" =>75,),
"76"=>array("name_ru"=>"Темплмор","name_en"=>"Templemore","name_href" =>"ie/population-of-templemore","count" =>"2 384","real_id" =>76,),
"77"=>array("name_ru"=>"Скибберин","name_en"=>"Skibbereen","name_href" =>"ie/population-of-skibbereen","count" =>"2 338","real_id" =>77,),
"78"=>array("name_ru"=>"Бандоран","name_en"=>"Bundoran","name_href" =>"ie/population-of-bundoran","count" =>"1 964","real_id" =>78,),
"79"=>array("name_ru"=>"Кутхилл","name_en"=>"Cootehill","name_href" =>"ie/population-of-cootehill","count" =>"1 892","real_id" =>79,),
"80"=>array("name_ru"=>"Клонс","name_en"=>"Clones","name_href" =>"ie/population-of-clones","count" =>"1 767","real_id" =>80,),
"81"=>array("name_ru"=>"Белтёрбет","name_en"=>"Belturbet","name_href" =>"ie/population-of-belturbet","count" =>"1 395","real_id" =>81,),
"82"=>array("name_ru"=>"Килки","name_en"=>"Kilkee","name_href" =>"ie/population-of-kilkee","count" =>"1 325","real_id" =>82,),
"83"=>array("name_ru"=>"Лисмор","name_en"=>"Lismore","name_href" =>"ie/population-of-lismore","count" =>"1 240","real_id" =>83,),
"84"=>array("name_ru"=>"Баллибей","name_en"=>"Ballybay","name_href" =>"ie/population-of-ballybay","count" =>"1 217","real_id" =>84,),
"85"=>array("name_ru"=>"Гранард","name_en"=>"Granard","name_href" =>"ie/population-of-granard","count" =>"933","real_id" =>85,),
"86"=>array("name_ru"=>"Дублин","name_en"=>"Dublin","name_href" =>"ie/population-of-dublin","count" =>"506 211","real_id" =>86,),
"87"=>array("name_ru"=>"Корк","name_en"=>"Cork","name_href" =>"ie/population-of-cork","count" =>"190 384","real_id" =>87,),
"88"=>array("name_ru"=>"Лимерик","name_en"=>"Limerick","name_href" =>"ie/population-of-limerick","count" =>"90 757","real_id" =>88,),
"89"=>array("name_ru"=>"Голуэй","name_en"=>"Galway","name_href" =>"ie/population-of-galway","count" =>"71 983","real_id" =>89,),
"90"=>array("name_ru"=>"Уотерфорд","name_en"=>"Waterford","name_href" =>"ie/population-of-waterford","count" =>"49 213","real_id" =>90,)
);

?>