<?php
//Индонезия 94 
$libid = array ( 
"1"=>array("name_ru"=>"Джакарта","name_en"=>"Jakarta","name_href" => "id/population-of-jakarta","count" => "10 135 030","real_id" =>1,),
"2"=>array("name_ru"=>"Сурабая","name_en"=>"Surabaya","name_href" => "id/population-of-surabaya","count" => "2 843 144","real_id" =>2,),
"3"=>array("name_ru"=>"Бандунг","name_en"=>"Bandung","name_href" => "id/population-of-bandung","count" => "2 575 478","real_id" =>3,),
"4"=>array("name_ru"=>"Бекаси","name_en"=>"Bekasi","name_href" => "id/population-of-bekasi","count" => "2 510 951","real_id" =>4,),
"5"=>array("name_ru"=>"Медан","name_en"=>"Medan","name_href" => "id/population-of-medan","count" => "2 185 789","real_id" =>5,),
"6"=>array("name_ru"=>"Тангеранг","name_en"=>"Tangerang","name_href" => "id/population-of-tangerang","count" => "2 001 925","real_id" =>6,),
"7"=>array("name_ru"=>"Депок","name_en"=>"Depok","name_href" => "id/population-of-depok","count" => "1 869 681","real_id" =>7,),
"8"=>array("name_ru"=>"Семаранг","name_en"=>"Semarang","name_href" => "id/population-of-semarang","count" => "1 575 068","real_id" =>8,),
"9"=>array("name_ru"=>"Палембанг","name_en"=>"Palembang","name_href" => "id/population-of-palembang","count" => "1 561 959","real_id" =>9,),
"10"=>array("name_ru"=>"Макасар","name_en"=>"Makassar","name_href" => "id/population-of-makassar","count" => "1 398 804","real_id" =>10,),
"11"=>array("name_ru"=>"Тангеранг-Селатан","name_en"=>"Tangerang Selatan","name_href" => "id/population-of-tangerang-selatan","count" => "1 436 187","real_id" =>11,),
"12"=>array("name_ru"=>"Богор","name_en"=>"Bogor","name_href" => "id/population-of-bogor","count" => "1 022 002","real_id" =>12,),
"13"=>array("name_ru"=>"Батам","name_en"=>"Batam","name_href" => "id/population-of-batam","count" => "1 142 646","real_id" =>13,),
"14"=>array("name_ru"=>"Пеканбару","name_en"=>"Pekanbaru","name_href" => "id/population-of-pekanbaru","count" => "1 030 732","real_id" =>14,),
"15"=>array("name_ru"=>"Бандар-Лампунг","name_en"=>"Bandar Lampung","name_href" => "id/population-of-bandar-lampung","count" => "923 970","real_id" =>15,),
"16"=>array("name_ru"=>"Маланг","name_en"=>"Malang","name_href" => "id/population-of-malang","count" => "843 284","real_id" =>16,),
"17"=>array("name_ru"=>"Паданг","name_en"=>"Padang","name_href" => "id/population-of-padang","count" => "876 880","real_id" =>17,),
"18"=>array("name_ru"=>"Денпасар","name_en"=>"Denpasar","name_href" => "id/population-of-denpasar","count" => "856 412","real_id" =>18,),
"19"=>array("name_ru"=>"Самаринда","name_en"=>"Samarinda","name_href" => "id/population-of-samarinda","count" => "842 691","real_id" =>19,),
"20"=>array("name_ru"=>"Серанг","name_en"=>"Serang","name_href" => "id/population-of-serang","count" => "643 103","real_id" =>20,),
"21"=>array("name_ru"=>"Банджармасин","name_en"=>"Banjarmasin","name_href" => "id/population-of-banjarmasin","count" => "675 030","real_id" =>21,),
"22"=>array("name_ru"=>"Тасикмалая","name_en"=>"Tasikmalaya","name_href" => "id/population-of-tasikmalaya","count" => "683 386","real_id" =>22,),
"23"=>array("name_ru"=>"Понтианак","name_en"=>"Pontianak","name_href" => "id/population-of-pontianak","count" => "573 751","real_id" =>23,),
"24"=>array("name_ru"=>"Чимахи","name_en"=>"Cimahi","name_href" => "id/population-of-cimahi","count" => "581 989","real_id" =>24,),
"25"=>array("name_ru"=>"Баликпапан","name_en"=>"Balikpapan","name_href" => "id/population-of-balikpapan","count" => "645 866","real_id" =>25,),
"26"=>array("name_ru"=>"Джамби","name_en"=>"Jambi","name_href" => "id/population-of-jambi","count" => "586 930","real_id" =>26,),
"27"=>array("name_ru"=>"Суракарта","name_en"=>"Surakarta","name_href" => "id/population-of-surakarta","count" => "505 461","real_id" =>27,),
"28"=>array("name_ru"=>"Матарам","name_en"=>"Mataram","name_href" => "id/population-of-mataram","count" => "420 941","real_id" =>28,),
"29"=>array("name_ru"=>"Манадо","name_en"=>"Manado","name_href" => "id/population-of-manado","count" => "430 790","real_id" =>29,),
"30"=>array("name_ru"=>"Джокьякарта","name_en"=>"Yogyakarta","name_href" => "id/population-of-yogyakarta","count" => "404 003","real_id" =>30,),
"31"=>array("name_ru"=>"Чилегон","name_en"=>"Cilegon","name_href" => "id/population-of-cilegon","count" => "416 901","real_id" =>31,),
"32"=>array("name_ru"=>"Купанг","name_en"=>"Kupang","name_href" => "id/population-of-kupang","count" => "364 014","real_id" =>32,),
"33"=>array("name_ru"=>"Палу","name_en"=>"Palu","name_href" => "id/population-of-palu","count" => "362 621","real_id" =>33,),
"34"=>array("name_ru"=>"Амбон","name_en"=>"Ambon","name_href" => "id/population-of-ambon","count" => "368 987","real_id" =>34,),
"35"=>array("name_ru"=>"Таракан","name_en"=>"Tarakan","name_href" => "id/population-of-tarakan","count" => "223 988","real_id" =>35,),
"36"=>array("name_ru"=>"Сукабуми","name_en"=>"Sukabumi","name_href" => "id/population-of-sukabumi","count" => "321 205","real_id" =>36,),
"37"=>array("name_ru"=>"Чиребон","name_en"=>"Cirebon","name_href" => "id/population-of-cirebon","count" => "318 741","real_id" =>37,),
"38"=>array("name_ru"=>"Бенкулу","name_en"=>"Bengkulu","name_href" => "id/population-of-bengkulu","count" => "328 827","real_id" =>38,),
"39"=>array("name_ru"=>"Кендари","name_en"=>"Kendari","name_href" => "id/population-of-kendari","count" => "314 042","real_id" =>39,),
"40"=>array("name_ru"=>"Пекалонган","name_en"=>"Pekalongan","name_href" => "id/population-of-pekalongan","count" => "284 886","real_id" =>40,),
"41"=>array("name_ru"=>"Кедири","name_en"=>"Kediri","name_href" => "id/population-of-kediri","count" => "276 051","real_id" =>41,),
"42"=>array("name_ru"=>"Тегал","name_en"=>"Tegal","name_href" => "id/population-of-tegal","count" => "242 539","real_id" =>42,),
"43"=>array("name_ru"=>"Бинджай","name_en"=>"Binjai","name_href" => "id/population-of-binjai","count" => "256 502","real_id" =>43,),
"44"=>array("name_ru"=>"Пематангсиантар","name_en"=>"Pematangsiantar","name_href" => "id/population-of-pematangsiantar","count" => "244 564","real_id" =>44,),
"45"=>array("name_ru"=>"Джаяпура","name_en"=>"Jayapura","name_href" => "id/population-of-jayapura","count" => "315 872","real_id" =>45,),
"46"=>array("name_ru"=>"Банда-Ачех","name_en"=>"Banda Aceh","name_href" => "id/population-of-banda-aceh","count" => "235 245","real_id" =>46,),
"47"=>array("name_ru"=>"Паланкарая","name_en"=>"Palangkaraya","name_href" => "id/population-of-palangkaraya","count" => "236 601","real_id" =>47,),
"48"=>array("name_ru"=>"Проболинго","name_en"=>"Probolinggo","name_href" => "id/population-of-probolinggo","count" => "223 159","real_id" =>48,),
"49"=>array("name_ru"=>"Банджарбару","name_en"=>"Banjarbaru","name_href" => "id/population-of-banjarbaru","count" => "215 440","real_id" =>49,),
"50"=>array("name_ru"=>"Пасуруан","name_en"=>"Pasuruan","name_href" => "id/population-of-pasuruan","count" => "191 494","real_id" =>50,),
"51"=>array("name_ru"=>"Танджунгпинанг","name_en"=>"Tanjungpinang","name_href" => "id/population-of-tanjungpinang","count" => "226 716","real_id" =>51,),
"52"=>array("name_ru"=>"Горонтало","name_en"=>"Gorontalo","name_href" => "id/population-of-gorontalo","count" => "196 464","real_id" =>52,),
"53"=>array("name_ru"=>"Думай","name_en"=>"Dumai","name_href" => "id/population-of-dumai","count" => "291 393","real_id" =>53,),
"54"=>array("name_ru"=>"Мадиун","name_en"=>"Madiun","name_href" => "id/population-of-madiun","count" => "175 767","real_id" =>54,),
"55"=>array("name_ru"=>"Бату","name_en"=>"Batu","name_href" => "id/population-of-batu","count" => "195 526","real_id" =>55,),
"56"=>array("name_ru"=>"Салатига","name_en"=>"Salatiga","name_href" => "id/population-of-salatiga","count" => "172 421","real_id" =>56,),
"57"=>array("name_ru"=>"Панкалпинанг","name_en"=>"Pangkal Pinang","name_href" => "id/population-of-pangkal-pinang","count" => "159 689","real_id" =>57,),
"58"=>array("name_ru"=>"Лубуклингау","name_en"=>"Lubuklinggau","name_href" => "id/population-of-lubuklinggau","count" => "216 064","real_id" =>58,),
"59"=>array("name_ru"=>"Тернате","name_en"=>"Ternate","name_href" => "id/population-of-ternate","count" => "204 215","real_id" =>59,),
"60"=>array("name_ru"=>"Битунг","name_en"=>"Bitung","name_href" => "id/population-of-bitung","count" => "196 936","real_id" =>60,),
"61"=>array("name_ru"=>"Танджунгбалай","name_en"=>"Tanjungbalai","name_href" => "id/population-of-tanjungbalai","count" => "160 941","real_id" =>61,),
"62"=>array("name_ru"=>"Тебингтинги","name_en"=>"Tebingtinggi","name_href" => "id/population-of-tebingtinggi","count" => "151 354","real_id" =>62,),
"63"=>array("name_ru"=>"Метро","name_en"=>"Metro","name_href" => "id/population-of-metro","count" => "152 428","real_id" =>63,),
"64"=>array("name_ru"=>"Бонтанг","name_en"=>"Bontang","name_href" => "id/population-of-bontang","count" => "166 433","real_id" =>64,),
"65"=>array("name_ru"=>"Падангсидемпуан","name_en"=>"Padang Sidempuan","name_href" => "id/population-of-padang-sidempuan","count" => "199 582","real_id" =>65,),
"66"=>array("name_ru"=>"Блитар","name_en"=>"Blitar","name_href" => "id/population-of-blitar","count" => "135 675","real_id" =>66,),
"67"=>array("name_ru"=>"Лхоксёмаве","name_en"=>"Lhokseumawe","name_href" => "id/population-of-lhokseumawe","count" => "180 200","real_id" =>67,),
"68"=>array("name_ru"=>"Синкаванг","name_en"=>"Singkawang","name_href" => "id/population-of-singkawang","count" => "192 844","real_id" =>68,),
"69"=>array("name_ru"=>"Гунунгситоли","name_en"=>"Gunungsitoli","name_href" => "id/population-of-gunungsitoli","count" => "131 507","real_id" =>69,),
"70"=>array("name_ru"=>"Пагаралам","name_en"=>"Pagar Alam","name_href" => "id/population-of-pagar-alam","count" => "135 431","real_id" =>70,),
"71"=>array("name_ru"=>"Парепаре","name_en"=>"Parepare","name_href" => "id/population-of-parepare","count" => "135 069","real_id" =>71,),
"72"=>array("name_ru"=>"Лангса","name_en"=>"Langsa","name_href" => "id/population-of-langsa","count" => "156 809","real_id" =>72,),
"73"=>array("name_ru"=>"Банджар","name_en"=>"Banjar","name_href" => "id/population-of-banjar","count" => "188 365","real_id" =>73,),
"74"=>array("name_ru"=>"Прабумулих","name_en"=>"Prabumulih","name_href" => "id/population-of-prabumulih","count" => "173 857","real_id" =>74,),
"75"=>array("name_ru"=>"Моджокерто","name_en"=>"Mojokerto","name_href" => "id/population-of-mojokerto","count" => "123 572","real_id" =>75,),
"76"=>array("name_ru"=>"Магеланг","name_en"=>"Magelang","name_href" => "id/population-of-magelang","count" => "119 677","real_id" =>76,),
"77"=>array("name_ru"=>"Соронг","name_en"=>"Sorong","name_href" => "id/population-of-sorong","count" => "219 958","real_id" =>77,),
"78"=>array("name_ru"=>"Паякумбух","name_en"=>"Payakumbuh","name_href" => "id/population-of-payakumbuh","count" => "122 896","real_id" =>78,),
"79"=>array("name_ru"=>"Палопо","name_en"=>"Palopo","name_href" => "id/population-of-palopo","count" => "154 579","real_id" =>79,),
"80"=>array("name_ru"=>"Бима","name_en"=>"Bima","name_href" => "id/population-of-bima","count" => "148 984","real_id" =>80,),
"81"=>array("name_ru"=>"Букиттинги","name_en"=>"Bukittinggi","name_href" => "id/population-of-bukittinggi","count" => "117 097","real_id" =>81,),
"82"=>array("name_ru"=>"Котамобагу","name_en"=>"Kotamobagu","name_href" => "id/population-of-kotamobagu","count" => "112 776","real_id" =>82,),
"83"=>array("name_ru"=>"Баубау","name_en"=>"Bau-Bau","name_href" => "id/population-of-bau-bau","count" => "148 366","real_id" =>83,),
"84"=>array("name_ru"=>"Томохон","name_en"=>"Tomohon","name_href" => "id/population-of-tomohon","count" => "96 083","real_id" =>84,),
"85"=>array("name_ru"=>"Тидоре","name_en"=>"Tidore Kepulauan","name_href" => "id/population-of-tidore-kepulauan","count" => "99 031","real_id" =>85,),
"86"=>array("name_ru"=>"Сиболга","name_en"=>"Sibolga","name_href" => "id/population-of-sibolga","count" => "88 032","real_id" =>86,),
"87"=>array("name_ru"=>"Сунгайпенух","name_en"=>"Sungaipenuh","name_href" => "id/population-of-sungaipenuh","count" => "90 814","real_id" =>87,),
"88"=>array("name_ru"=>"Париаман","name_en"=>"Pariaman","name_href" => "id/population-of-pariaman","count" => "83 151","real_id" =>88,),
"89"=>array("name_ru"=>"Субулассалам","name_en"=>"Subulussalam","name_href" => "id/population-of-subulussalam","count" => "71 007","real_id" =>89,),
"90"=>array("name_ru"=>"Солок","name_en"=>"Solok","name_href" => "id/population-of-solok","count" => "62 483","real_id" =>90,),
"91"=>array("name_ru"=>"Туал","name_en"=>"Tual","name_href" => "id/population-of-tual","count" => "64 698","real_id" =>91,),
"92"=>array("name_ru"=>"Савахлунто","name_en"=>"Sawahlunto","name_href" => "id/population-of-sawahlunto","count" => "59 821","real_id" =>92,),
"93"=>array("name_ru"=>"Падангпанджанг","name_en"=>"Padang Panjang","name_href" => "id/population-of-padang-panjang","count" => "49 451","real_id" =>93,),
"94"=>array("name_ru"=>"Сабанг","name_en"=>"Sabang","name_href" => "id/population-of-sabang","count" => "32 271","real_id" =>94,),
"95"=>array("name_ru"=>"Джакарта","name_en"=>"Jakarta","name_href" => "id/population-of-jakarta","count" => "10 135 030","real_id" =>95,),
"96"=>array("name_ru"=>"Сурабая","name_en"=>"Surabaya","name_href" => "id/population-of-surabaya","count" => "2 843 144","real_id" =>96,),
"97"=>array("name_ru"=>"Бандунг","name_en"=>"Bandung","name_href" => "id/population-of-bandung","count" => "2 575 478","real_id" =>97,),
"98"=>array("name_ru"=>"Бекаси","name_en"=>"Bekasi","name_href" => "id/population-of-bekasi","count" => "2 510 951","real_id" =>98,),
"99"=>array("name_ru"=>"Медан","name_en"=>"Medan","name_href" => "id/population-of-medan","count" => "2 185 789","real_id" =>99,)
);

?>