<?php
//Италия 46 
$libit = array ( 
"1"=>array("name_ru"=>"Рим","name_en"=>"Rome","name_href" => "it/population-of-rome","count" => "2 870 493","real_id" =>1,),
"2"=>array("name_ru"=>"Милан","name_en"=>"Milan","name_href" => "it/population-of-milan","count" => "1 331 586","real_id" =>2,),
"3"=>array("name_ru"=>"Неаполь","name_en"=>"Naples","name_href" => "it/population-of-naples","count" => "989 598","real_id" =>3,),
"4"=>array("name_ru"=>"Турин","name_en"=>"Turin","name_href" => "it/population-of-turin","count" => "899 291","real_id" =>4,),
"5"=>array("name_ru"=>"Палермо","name_en"=>"Palermo","name_href" => "it/population-of-palermo","count" => "676 527","real_id" =>5,),
"6"=>array("name_ru"=>"Генуя","name_en"=>"Genoa","name_href" => "it/population-of-genoa","count" => "594 254","real_id" =>6,),
"7"=>array("name_ru"=>"Болонья","name_en"=>"Bologna","name_href" => "it/population-of-bologna","count" => "385 435","real_id" =>7,),
"8"=>array("name_ru"=>"Флоренция","name_en"=>"Florence","name_href" => "it/population-of-florence","count" => "379 102","real_id" =>8,),
"9"=>array("name_ru"=>"Бари","name_en"=>"Bari","name_href" => "it/population-of-bari","count" => "321 687","real_id" =>9,),
"10"=>array("name_ru"=>"Катания","name_en"=>"Catania","name_href" => "it/population-of-catania","count" => "315 052","real_id" =>10,),
"11"=>array("name_ru"=>"Венеция","name_en"=>"Venice","name_href" => "it/population-of-venice","count" => "264 919","real_id" =>11,),
"12"=>array("name_ru"=>"Верона","name_en"=>"Verona","name_href" => "it/population-of-verona","count" => "259 941","real_id" =>12,),
"13"=>array("name_ru"=>"Мессина","name_en"=>"Messina","name_href" => "it/population-of-messina","count" => "240 725","real_id" =>13,),
"14"=>array("name_ru"=>"Падуя","name_en"=>"Padua","name_href" => "it/population-of-padua","count" => "210 494","real_id" =>14,),
"15"=>array("name_ru"=>"Триест","name_en"=>"Trieste","name_href" => "it/population-of-trieste","count" => "205 555","real_id" =>15,),
"16"=>array("name_ru"=>"Таранто","name_en"=>"Taranto","name_href" => "it/population-of-taranto","count" => "202 297","real_id" =>16,),
"17"=>array("name_ru"=>"Брешиа","name_en"=>"Brescia","name_href" => "it/population-of-brescia","count" => "195 193","real_id" =>17,),
"18"=>array("name_ru"=>"Прато","name_en"=>"Prato","name_href" => "it/population-of-prato","count" => "190 698","real_id" =>18,),
"19"=>array("name_ru"=>"Парма","name_en"=>"Parma","name_href" => "it/population-of-parma","count" => "189 151","real_id" =>19,),
"20"=>array("name_ru"=>"Модена","name_en"=>"Modena","name_href" => "it/population-of-modena","count" => "185 041","real_id" =>20,),
"21"=>array("name_ru"=>"Реджо-ди-Калабрия","name_en"=>"Reggio di Calabria","name_href" => "it/population-of-reggio-di-calabria","count" => "184 708","real_id" =>21,),
"22"=>array("name_ru"=>"Реджо-нель-Эмилия","name_en"=>"Reggio Emilia","name_href" => "it/population-of-reggio-emilia","count" => "172 028","real_id" =>22,),
"23"=>array("name_ru"=>"Перуджа","name_en"=>"Perugia","name_href" => "it/population-of-perugia","count" => "166 169","real_id" =>23,),
"24"=>array("name_ru"=>"Ливорно","name_en"=>"Livorno","name_href" => "it/population-of-livorno","count" => "160 520","real_id" =>24,),
"25"=>array("name_ru"=>"Равенна","name_en"=>"Ravenna","name_href" => "it/population-of-ravenna","count" => "158 976","real_id" =>25,),
"26"=>array("name_ru"=>"Кальяри","name_en"=>"Cagliari","name_href" => "it/population-of-cagliari","count" => "154 637","real_id" =>26,),
"27"=>array("name_ru"=>"Фоджа","name_en"=>"Foggia","name_href" => "it/population-of-foggia","count" => "152 879","real_id" =>27,),
"28"=>array("name_ru"=>"Римини","name_en"=>"Rimini","name_href" => "it/population-of-rimini","count" => "147 500","real_id" =>28,),
"29"=>array("name_ru"=>"Феррара","name_en"=>"Ferrara","name_href" => "it/population-of-ferrara","count" => "133 967","real_id" =>29,),
"30"=>array("name_ru"=>"Салерно","name_en"=>"Salerno","name_href" => "it/population-of-salerno","count" => "133 429","real_id" =>30,),
"31"=>array("name_ru"=>"Сассари","name_en"=>"Sassari","name_href" => "it/population-of-sassari","count" => "127 711","real_id" =>31,),
"32"=>array("name_ru"=>"Латина","name_en"=>"Latina","name_href" => "it/population-of-latina","count" => "125 185","real_id" =>32,),
"33"=>array("name_ru"=>"Монца","name_en"=>"Monza","name_href" => "it/population-of-monza","count" => "122 639","real_id" =>33,),
"34"=>array("name_ru"=>"Сиракуза","name_en"=>"Siracusa","name_href" => "it/population-of-siracusa","count" => "122 286","real_id" =>34,),
"35"=>array("name_ru"=>"Пескара","name_en"=>"Pescara","name_href" => "it/population-of-pescara","count" => "121 303","real_id" =>35,),
"36"=>array("name_ru"=>"Джульяно-ин-Кампанья","name_en"=>"Giugliano in Campania","name_href" => "it/population-of-giugliano-in-campania","count" => "121 129","real_id" =>36,),
"37"=>array("name_ru"=>"Бергамо","name_en"=>"Bergamo","name_href" => "it/population-of-bergamo","count" => "118 691","real_id" =>37,),
"38"=>array("name_ru"=>"Форли","name_en"=>"Forli","name_href" => "it/population-of-forli","count" => "118 250","real_id" =>38,),
"39"=>array("name_ru"=>"Тренто","name_en"=>"Trento","name_href" => "it/population-of-trento","count" => "117 287","real_id" =>39,),
"40"=>array("name_ru"=>"Виченца","name_en"=>"Vicenza","name_href" => "it/population-of-vicenza","count" => "113 674","real_id" =>40,),
"41"=>array("name_ru"=>"Терни","name_en"=>"Terni","name_href" => "it/population-of-terni","count" => "112 184","real_id" =>41,),
"42"=>array("name_ru"=>"Больцано","name_en"=>"Bolzano","name_href" => "it/population-of-bolzano","count" => "105 974","real_id" =>42,),
"43"=>array("name_ru"=>"Новара","name_en"=>"Novara","name_href" => "it/population-of-novara","count" => "104 586","real_id" =>43,),
"44"=>array("name_ru"=>"Пьяченца","name_en"=>"Piacenza","name_href" => "it/population-of-piacenza","count" => "102 384","real_id" =>44,),
"45"=>array("name_ru"=>"Анкона","name_en"=>"Ancona","name_href" => "it/population-of-ancona","count" => "101 484","real_id" =>45,),
"46"=>array("name_ru"=>"Андрия","name_en"=>"Andria","name_href" => "it/population-of-andria","count" => "100 416","real_id" =>46,),
"47"=>array("name_ru"=>"Рим","name_en"=>"Rome","name_href" => "it/population-of-rome","count" => "2 870 493","real_id" =>47,),
"48"=>array("name_ru"=>"Милан","name_en"=>"Milan","name_href" => "it/population-of-milan","count" => "1 331 586","real_id" =>48,),
"49"=>array("name_ru"=>"Неаполь","name_en"=>"Naples","name_href" => "it/population-of-naples","count" => "989 598","real_id" =>49,),
"50"=>array("name_ru"=>"Турин","name_en"=>"Turin","name_href" => "it/population-of-turin","count" => "899 291","real_id" =>50,),
"51"=>array("name_ru"=>"Палермо","name_en"=>"Palermo","name_href" => "it/population-of-palermo","count" => "676 527","real_id" =>51,)
);

?>