<?php
//Израиль 75
$libil = array ( 
"1"=>array("name_ru"=>"Иерусалим","name_en"=>"Jerusalem","name_href" => "il/population-of-jerusalem","count" => "901 302","real_id" =>1,),
"2"=>array("name_ru"=>"Тель-Авив","name_en"=>"Tel Aviv","name_href" => "il/population-of-tel-aviv","count" => "443 939","real_id" =>2,),
"3"=>array("name_ru"=>"Хайфа","name_en"=>"Haifa","name_href" => "il/population-of-haifa","count" => "281 087","real_id" =>3,),
"4"=>array("name_ru"=>"Петах-Тиква","name_en"=>"Petah Tikva","name_href" => "il/population-of-petah-tikva","count" => "240 357","real_id" =>4,),
"5"=>array("name_ru"=>"Ашдод","name_en"=>"Ashdod","name_href" => "il/population-of-ashdod","count" => "222 883","real_id" =>5,),
"6"=>array("name_ru"=>"Нетания","name_en"=>"Netanya","name_href" => "il/population-of-netanya","count" => "214 101","real_id" =>6,),
"7"=>array("name_ru"=>"Беэр-Шева","name_en"=>"Beersheba","name_href" => "il/population-of-beersheba","count" => "207 551","real_id" =>7,),
"8"=>array("name_ru"=>"Бней-Брак","name_en"=>"Bnei Brak","name_href" => "il/population-of-bnei-brak","count" => "193 774","real_id" =>8,),
"9"=>array("name_ru"=>"Холон","name_en"=>"Holon","name_href" => "il/population-of-holon","count" => "192 624","real_id" =>9,),
"10"=>array("name_ru"=>"Рамат-Ган","name_en"=>"Ramat Gan","name_href" => "il/population-of-ramat-gan","count" => "156 277","real_id" =>10,),
"11"=>array("name_ru"=>"Реховот","name_en"=>"Rehovot","name_href" => "il/population-of-rehovot","count" => "138 379","real_id" =>11,),
"12"=>array("name_ru"=>"Ашкелон","name_en"=>"Ashkelon","name_href" => "il/population-of-ashkelon","count" => "137 945","real_id" =>12,),
"13"=>array("name_ru"=>"Бат-Ям","name_en"=>"Bat Yam","name_href" => "il/population-of-bat-yam","count" => "128 655","real_id" =>13,),
"14"=>array("name_ru"=>"Бейт-Шемеш","name_en"=>"Beit Shemesh","name_href" => "il/population-of-beit-shemesh","count" => "114 371","real_id" =>14,),
"15"=>array("name_ru"=>"Кфар-Сава","name_en"=>"Kfar Saba","name_href" => "il/population-of-kfar-saba","count" => "100 039","real_id" =>15,),
"16"=>array("name_ru"=>"Герцлия","name_en"=>"Herzliya","name_href" => "il/population-of-herzliya","count" => "93 989","real_id" =>16,),
"17"=>array("name_ru"=>"Хадера","name_en"=>"Hadera","name_href" => "il/population-of-hadera","count" => "93 973","real_id" =>17,),
"18"=>array("name_ru"=>"Модиин-Маккабим-Реут","name_en"=>"Modi'in-Maccabim-Re'ut","name_href" => "il/population-of-modiin-maccabim-reut","count" => "91 328","real_id" =>18,),
"19"=>array("name_ru"=>"Назарет","name_en"=>"Nazareth","name_href" => "il/population-of-nazareth","count" => "76 551","real_id" =>19,),
"20"=>array("name_ru"=>"Рамла","name_en"=>"Ramla","name_href" => "il/population-of-ramla","count" => "75 668","real_id" =>20,),
"21"=>array("name_ru"=>"Лод","name_en"=>"Lod","name_href" => "il/population-of-lod","count" => "74 604","real_id" =>21,),
"22"=>array("name_ru"=>"Рахат","name_en"=>"Rahat","name_href" => "il/population-of-rahat","count" => "66 791","real_id" =>22,),
"23"=>array("name_ru"=>"Модиин-Илит","name_en"=>"Modi'in Illit","name_href" => "il/population-of-modiin-illit","count" => "64 179","real_id" =>23,),
"24"=>array("name_ru"=>"Ход-ха-Шарон","name_en"=>"Hod HaSharon","name_href" => "il/population-of-hod-hasharon","count" => "61 102","real_id" =>24,),
"25"=>array("name_ru"=>"Гиватаим","name_en"=>"Givatayim","name_href" => "il/population-of-givatayim","count" => "59 518","real_id" =>25,),
"26"=>array("name_ru"=>"Кирьят-Ата","name_en"=>"Kiryat Ata","name_href" => "il/population-of-kiryat-ata","count" => "57 518","real_id" =>26,),
"27"=>array("name_ru"=>"Нагария","name_en"=>"Nahariya","name_href" => "il/population-of-nahariya","count" => "56 071","real_id" =>27,),
"28"=>array("name_ru"=>"Кирьят-Гат","name_en"=>"Kiryat Gat","name_href" => "il/population-of-kiryat-gat","count" => "53 487","real_id" =>28,),
"29"=>array("name_ru"=>"Эйлат","name_en"=>"Eilat","name_href" => "il/population-of-eilat","count" => "50 724","real_id" =>29,),
"30"=>array("name_ru"=>"Рош-ха-Аин","name_en"=>"Rosh HaAyin","name_href" => "il/population-of-rosh-haayin","count" => "50 453","real_id" =>30,),
"31"=>array("name_ru"=>"Бейтар-Илит","name_en"=>"Beitar Illit","name_href" => "il/population-of-beitar-illit","count" => "49 343","real_id" =>31,),
"32"=>array("name_ru"=>"Афула","name_en"=>"Afula","name_href" => "il/population-of-afula","count" => "49 169","real_id" =>32,),
"33"=>array("name_ru"=>"Нес-Циона","name_en"=>"Ness Ziona","name_href" => "il/population-of-ness-ziona","count" => "49 108","real_id" =>33,),
"34"=>array("name_ru"=>"Акко","name_en"=>"Acre","name_href" => "il/population-of-acre","count" => "48 303","real_id" =>34,),
"35"=>array("name_ru"=>"Эльад","name_en"=>"El'ad","name_href" => "il/population-of-elad","count" => "46 896","real_id" =>35,),
"36"=>array("name_ru"=>"Рамат-ха-Шарон","name_en"=>"Ramat HaSharon","name_href" => "il/population-of-ramat-hasharon","count" => "46 019","real_id" =>36,),
"37"=>array("name_ru"=>"Кармиэль","name_en"=>"Karmiel","name_href" => "il/population-of-karmiel","count" => "45 919","real_id" =>37,),
"38"=>array("name_ru"=>"Явне","name_en"=>"Yavne","name_href" => "il/population-of-yavne","count" => "45 483","real_id" =>38,),
"39"=>array("name_ru"=>"Тверия","name_en"=>"Tiberias","name_href" => "il/population-of-tiberias","count" => "43 664","real_id" =>39,),
"40"=>array("name_ru"=>"Тайбе","name_en"=>"Tayibe","name_href" => "il/population-of-tayibe","count" => "42 401","real_id" =>40,),
"41"=>array("name_ru"=>"Шефарам","name_en"=>"Shefa-Amr","name_href" => "il/population-of-shefa-amr","count" => "41 024","real_id" =>41,),
"42"=>array("name_ru"=>"Нацрат-Иллит","name_en"=>"Nazareth Illit","name_href" => "il/population-of-nazareth-illit","count" => "40 596","real_id" =>42,),
"43"=>array("name_ru"=>"Кирьят-Бялик","name_en"=>"Kiryat Bialik","name_href" => "il/population-of-kiryat-bialik","count" => "39 582","real_id" =>43,),
"44"=>array("name_ru"=>"Кирьят-Оно","name_en"=>"Kiryat Ono","name_href" => "il/population-of-kiryat-ono","count" => "39 398","real_id" =>44,),
"45"=>array("name_ru"=>"Маале-Адумим","name_en"=>"Ma'ale Adumim","name_href" => "il/population-of-maale-adumim","count" => "37 525","real_id" =>45,),
"46"=>array("name_ru"=>"Ор-Йехуда","name_en"=>"Or Yehuda","name_href" => "il/population-of-or-yehuda","count" => "36 706","real_id" =>46,),
"47"=>array("name_ru"=>"Цфат","name_en"=>"Safed","name_href" => "il/population-of-safed","count" => "35 276","real_id" =>47,),
"48"=>array("name_ru"=>"Нетивот","name_en"=>"Netivot","name_href" => "il/population-of-netivot","count" => "33 779","real_id" =>48,),
"49"=>array("name_ru"=>"Димона","name_en"=>"Dimona","name_href" => "il/population-of-dimona","count" => "33 666","real_id" =>49,),
"50"=>array("name_ru"=>"Сахнин","name_en"=>"Sakhnin","name_href" => "il/population-of-sakhnin","count" => "30 548","real_id" =>50,),
"51"=>array("name_ru"=>"Йехуд-Моноссон","name_en"=>"Yehud-Monosson","name_href" => "il/population-of-yehud-monosson","count" => "29 689","real_id" =>51,),
"52"=>array("name_ru"=>"Бака-аль-Гарбия","name_en"=>"Baqa al-Gharbiyye","name_href" => "il/population-of-baqa-al-gharbiyye","count" => "29 035","real_id" =>52,),
"53"=>array("name_ru"=>"Офаким","name_en"=>"Ofakim","name_href" => "il/population-of-ofakim","count" => "27 771","real_id" =>53,),
"54"=>array("name_ru"=>"Гиват-Шмуэль","name_en"=>"Giv'at Shmuel","name_href" => "il/population-of-givat-shmuel","count" => "25 776","real_id" =>54,),
"55"=>array("name_ru"=>"Тира","name_en"=>"Tira","name_href" => "il/population-of-tira","count" => "25 721","real_id" =>55,),
"56"=>array("name_ru"=>"Мигдаль-ха-Эмек","name_en"=>"Migdal HaEmek","name_href" => "il/population-of-migdal-haemek","count" => "25 371","real_id" =>56,),
"57"=>array("name_ru"=>"Сдерот","name_en"=>"Sderot","name_href" => "il/population-of-sderot","count" => "25 138","real_id" =>57,),
"58"=>array("name_ru"=>"Ришон-ле-Цион","name_en"=>"Rishon LeZion","name_href" => "il/population-of-rishon-lezion","count" => "24 986","real_id" =>58,),
"59"=>array("name_ru"=>"Нешер","name_en"=>"Nesher","name_href" => "il/population-of-nesher","count" => "23 749","real_id" =>59,),
"60"=>array("name_ru"=>"Кирьят-Шмона","name_en"=>"Kiryat Shmona","name_href" => "il/population-of-kiryat-shmona","count" => "22 844","real_id" =>60,),
"61"=>array("name_ru"=>"Йокнеам","name_en"=>"Yokneam Illit","name_href" => "il/population-of-yokneam-illit","count" => "22 746","real_id" =>61,),
"62"=>array("name_ru"=>"Кафр-Касем","name_en"=>"Kafr Qasim","name_href" => "il/population-of-kafr-qasim","count" => "22 743","real_id" =>62,),
"63"=>array("name_ru"=>"Кирьят-Малахи","name_en"=>"Kiryat Malakhi","name_href" => "il/population-of-kiryat-malakhi","count" => "22 337","real_id" =>63,),
"64"=>array("name_ru"=>"Маалот-Таршиха","name_en"=>"Ma'alot-Tarshiha","name_href" => "il/population-of-maalot-tarshiha","count" => "21 267","real_id" =>64,),
"65"=>array("name_ru"=>"Тират-Кармель","name_en"=>"Tirat Carmel","name_href" => "il/population-of-tirat-carmel","count" => "21 256","real_id" =>65,),
"66"=>array("name_ru"=>"Ариэль","name_en"=>"Ariel","name_href" => "il/population-of-ariel","count" => "18 717","real_id" =>66,),
"67"=>array("name_ru"=>"Ор-Акива","name_en"=>"Or Akiva","name_href" => "il/population-of-or-akiva","count" => "17 759","real_id" =>67,),
"68"=>array("name_ru"=>"Бейт-Шеан","name_en"=>"Beit She'an","name_href" => "il/population-of-beit-shean","count" => "17 704","real_id" =>68,),
"69"=>array("name_ru"=>"Раанана","name_en"=>"Ra'anana","name_href" => "il/population-of-raanana","count" => "7 281","real_id" =>69,),
"70"=>array("name_ru"=>"Умм-эль-Фахм","name_en"=>"Umm al-Fahm","name_href" => "il/population-of-umm-al-fahm","count" => "5 424","real_id" =>70,),
"71"=>array("name_ru"=>"Кирьят-Моцкин","name_en"=>"Kiryat Motzkin","name_href" => "il/population-of-kiryat-motzkin","count" => "4 144","real_id" =>71,),
"72"=>array("name_ru"=>"Кирьят-Ям","name_en"=>"Kiryat Yam","name_href" => "il/population-of-kiryat-yam","count" => "3 971","real_id" =>72,),
"73"=>array("name_ru"=>"Тамра","name_en"=>"Tamra","name_href" => "il/population-of-tamra","count" => "3 338","real_id" =>73,),
"74"=>array("name_ru"=>"Арад","name_en"=>"Arad","name_href" => "il/population-of-arad","count" => "2 553","real_id" =>74,),
"75"=>array("name_ru"=>"Калансуа","name_en"=>"Qalansawe","name_href" => "il/population-of-qalansawe","count" => "2 237","real_id" =>75,),
"76"=>array("name_ru"=>"Иерусалим","name_en"=>"Jerusalem","name_href" => "il/population-of-jerusalem","count" => "901 302","real_id" =>76,),
"77"=>array("name_ru"=>"Тель-Авив","name_en"=>"Tel Aviv","name_href" => "il/population-of-tel-aviv","count" => "443 939","real_id" =>77,),
"78"=>array("name_ru"=>"Хайфа","name_en"=>"Haifa","name_href" => "il/population-of-haifa","count" => "281 087","real_id" =>78,),
"79"=>array("name_ru"=>"Петах-Тиква","name_en"=>"Petah Tikva","name_href" => "il/population-of-petah-tikva","count" => "240 357","real_id" =>79,),
"80"=>array("name_ru"=>"Ашдод","name_en"=>"Ashdod","name_href" => "il/population-of-ashdod","count" => "222 883","real_id" =>80,)
);

?>