<?php
//Индия 46 
$libin = array ( 
"1"=>array("name_ru"=>"Мумбаи","name_en"=>"Mumbai","name_href" =>"in/population-of-mumbai","count" =>"11 978 450","real_id" =>1,),
"2"=>array("name_ru"=>"Дели","name_en"=>"Delhi","name_href" =>"in/population-of-delhi","count" =>"9 879 172","real_id" =>2,),
"3"=>array("name_ru"=>"Бангалор","name_en"=>"Bangalore","name_href" =>"in/population-of-bangalore","count" =>"5 438 065","real_id" =>3,),
"4"=>array("name_ru"=>"Калькутта","name_en"=>"Kolkata","name_href" =>"in/population-of-kolkata","count" =>"4 572 876","real_id" =>4,),
"5"=>array("name_ru"=>"Ченнаи","name_en"=>"Chennai","name_href" =>"in/population-of-chennai","count" =>"4 343 645","real_id" =>5,),
"6"=>array("name_ru"=>"Хайдарабад","name_en"=>"Hyderabad","name_href" =>"in/population-of-hyderabad","count" =>"3 637 483","real_id" =>6,),
"7"=>array("name_ru"=>"Ахмедабад","name_en"=>"Ahmedabad","name_href" =>"in/population-of-ahmedabad","count" =>"3 520 085","real_id" =>7,),
"8"=>array("name_ru"=>"Канпур","name_en"=>"Kanpur","name_href" =>"in/population-of-kanpur","count" =>"2 551 337","real_id" =>8,),
"9"=>array("name_ru"=>"Пуна","name_en"=>"Pune","name_href" =>"in/population-of-pune","count" =>"2 538 473","real_id" =>9,),
"10"=>array("name_ru"=>"Сурат","name_en"=>"Surat","name_href" =>"in/population-of-surat","count" =>"2 433 835","real_id" =>10,),
"11"=>array("name_ru"=>"Джайпур","name_en"=>"Jaipur","name_href" =>"in/population-of-jaipur","count" =>"2 322 575","real_id" =>11,),
"12"=>array("name_ru"=>"Лакхнау","name_en"=>"Lucknow","name_href" =>"in/population-of-lucknow","count" =>"2 185 927","real_id" =>12,),
"13"=>array("name_ru"=>"Нагпур","name_en"=>"Nagpur","name_href" =>"in/population-of-nagpur","count" =>"2 052 066","real_id" =>13,),
"14"=>array("name_ru"=>"Индаур","name_en"=>"Indore","name_href" =>"in/population-of-indore","count" =>"1 474 968","real_id" =>14,),
"15"=>array("name_ru"=>"Бхопал","name_en"=>"Bhopal","name_href" =>"in/population-of-bhopal","count" =>"1 437 354","real_id" =>15,),
"16"=>array("name_ru"=>"Лудхияна","name_en"=>"Ludhiana","name_href" =>"in/population-of-ludhiana","count" =>"1 398 467","real_id" =>16,),
"17"=>array("name_ru"=>"Патна","name_en"=>"Patna","name_href" =>"in/population-of-patna","count" =>"1 366 444","real_id" =>17,),
"18"=>array("name_ru"=>"Вадодара","name_en"=>"Vadodara","name_href" =>"in/population-of-vadodara","count" =>"1 306 227","real_id" =>18,),
"19"=>array("name_ru"=>"Агра","name_en"=>"Agra","name_href" =>"in/population-of-agra","count" =>"1 275 134","real_id" =>19,),
"20"=>array("name_ru"=>"Тхане","name_en"=>"Thane","name_href" =>"in/population-of-thane","count" =>"1 262 551","real_id" =>20,),
"21"=>array("name_ru"=>"Васаи-Вирар","name_en"=>"Vasai-Virar","name_href" =>"in/population-of-vasai-virar","count" =>"1 221 233","real_id" =>21,),
"22"=>array("name_ru"=>"Кальян-Домбивли","name_en"=>"Hookah-Dombivli","name_href" =>"in/population-of-hookah-dombivli","count" =>"1 193 512","real_id" =>22,),
"23"=>array("name_ru"=>"Варанаси","name_en"=>"Varanasi","name_href" =>"in/population-of-varanasi","count" =>"1 091 918","real_id" =>23,),
"24"=>array("name_ru"=>"Насик","name_en"=>"Nasik","name_href" =>"in/population-of-nasik","count" =>"1 077 236","real_id" =>24,),
"25"=>array("name_ru"=>"Мератх","name_en"=>"Meerut","name_href" =>"in/population-of-meerut","count" =>"1 068 772","real_id" =>25,),
"26"=>array("name_ru"=>"Фаридабад","name_en"=>"Faridabad","name_href" =>"in/population-of-faridabad","count" =>"1 055 938","real_id" =>26,),
"27"=>array("name_ru"=>"Пимпри-Чинчвад","name_en"=>"Pimpri-Chinchwad","name_href" =>"in/population-of-pimpri-chinchwad","count" =>"1 012 472","real_id" =>27,),
"28"=>array("name_ru"=>"Хаура","name_en"=>"Howrah","name_href" =>"in/population-of-howrah","count" =>"1 007 532","real_id" =>28,),
"29"=>array("name_ru"=>"Вишакхапатнам","name_en"=>"Visakhapatnam","name_href" =>"in/population-of-visakhapatnam","count" =>"982 904","real_id" =>29,),
"30"=>array("name_ru"=>"Аллахабад","name_en"=>"Allahabad","name_href" =>"in/population-of-allahabad","count" =>"975 393","real_id" =>30,),
"31"=>array("name_ru"=>"Газиабад","name_en"=>"Ghaziabad","name_href" =>"in/population-of-ghaziabad","count" =>"968 256","real_id" =>31,),
"32"=>array("name_ru"=>"Раджкот","name_en"=>"Rajkot","name_href" =>"in/population-of-rajkot","count" =>"967 476","real_id" =>32,),
"33"=>array("name_ru"=>"Амритсар","name_en"=>"Amritsar","name_href" =>"in/population-of-amritsar","count" =>"966 862","real_id" =>33,),
"34"=>array("name_ru"=>"Джабалпур","name_en"=>"Jabalpur","name_href" =>"in/population-of-jabalpur","count" =>"932 484","real_id" =>34,),
"35"=>array("name_ru"=>"Коимбатур","name_en"=>"Coimbatore","name_href" =>"in/population-of-coimbatore","count" =>"930 882","real_id" =>35,),
"36"=>array("name_ru"=>"Мадурай","name_en"=>"Madurai","name_href" =>"in/population-of-madurai","count" =>"928 869","real_id" =>36,),
"37"=>array("name_ru"=>"Сринагар","name_en"=>"Srinagar","name_href" =>"in/population-of-srinagar","count" =>"898 440","real_id" =>37,),
"38"=>array("name_ru"=>"Аурангабад","name_en"=>"Aurangabad","name_href" =>"in/population-of-aurangabad","count" =>"873 311","real_id" =>38,),
"39"=>array("name_ru"=>"Виджаявада","name_en"=>"Vijayawada","name_href" =>"in/population-of-vijayawada","count" =>"851 282","real_id" =>39,),
"40"=>array("name_ru"=>"Джодхпур","name_en"=>"Jodhpur","name_href" =>"in/population-of-jodhpur","count" =>"851 051","real_id" =>40,),
"41"=>array("name_ru"=>"Ранчи","name_en"=>"Ranchi","name_href" =>"in/population-of-ranchi","count" =>"847 093","real_id" =>41,),
"42"=>array("name_ru"=>"Гвалиор","name_en"=>"Gwalior","name_href" =>"in/population-of-gwalior","count" =>"827 026","real_id" =>42,),
"43"=>array("name_ru"=>"Нави Мумбаи","name_en"=>"Navi Mumbai","name_href" =>"in/population-of-navi-mumbai","count" =>"704 002","real_id" =>43,),
"44"=>array("name_ru"=>"Кота","name_en"=>"Cat","name_href" =>"in/population-of-cat","count" =>"694 316","real_id" =>44,),
"45"=>array("name_ru"=>"Райпур","name_en"=>"Raipur","name_href" =>"in/population-of-raipur","count" =>"605 747","real_id" =>45,),
"46"=>array("name_ru"=>"Дханбад","name_en"=>"Dhanbad","name_href" =>"in/population-of-dhanbad","count" =>"99 258","real_id" =>46,),
"47"=>array("name_ru"=>"Мумбаи","name_en"=>"Mumbai","name_href" =>"in/population-of-mumbai","count" =>"11 978 450","real_id" =>47,),
"48"=>array("name_ru"=>"Дели","name_en"=>"Delhi","name_href" =>"in/population-of-delhi","count" =>"9 879 172","real_id" =>48,),
"49"=>array("name_ru"=>"Бангалор","name_en"=>"Bangalore","name_href" =>"in/population-of-bangalore","count" =>"5 438 065","real_id" =>49,),
"50"=>array("name_ru"=>"Калькутта","name_en"=>"Kolkata","name_href" =>"in/population-of-kolkata","count" =>"4 572 876","real_id" =>50,),
"51"=>array("name_ru"=>"Ченнаи","name_en"=>"Chennai","name_href" =>"in/population-of-chennai","count" =>"4 343 645","real_id" =>51,)
);

?>