<?php
//Иран 80 
$libir = array ( 
"1"=>array("name_ru"=>"Тегеран","name_en"=>"Tehran","name_href" => "ir/population-of-tehran","count" => "7 797 520","real_id" =>1,),
"2"=>array("name_ru"=>"Мешхед","name_en"=>"Mashad","name_href" => "ir/population-of-mashad","count" => "2 427 316","real_id" =>2,),
"3"=>array("name_ru"=>"Исфахан","name_en"=>"Isfahan","name_href" => "ir/population-of-isfahan","count" => "1 602 110","real_id" =>3,),
"4"=>array("name_ru"=>"Тебриз","name_en"=>"Tabriz","name_href" => "ir/population-of-tabriz","count" => "1 398 060","real_id" =>4,),
"5"=>array("name_ru"=>"Кередж","name_en"=>"Kerej","name_href" => "ir/population-of-kerej","count" => "1 386 030","real_id" =>5,),
"6"=>array("name_ru"=>"Шираз","name_en"=>"Shiraz","name_href" => "ir/population-of-shiraz","count" => "1 227 331","real_id" =>6,),
"7"=>array("name_ru"=>"Ахваз","name_en"=>"Ahvaz","name_href" => "ir/population-of-ahvaz","count" => "985 614","real_id" =>7,),
"8"=>array("name_ru"=>"Кум","name_en"=>"Kum","name_href" => "ir/population-of-kum","count" => "959 116","real_id" =>8,),
"9"=>array("name_ru"=>"Керманшах","name_en"=>"Kermanshah","name_href" => "ir/population-of-kermanshah","count" => "794 863","real_id" =>9,),
"10"=>array("name_ru"=>"Урмия","name_en"=>"Urmia","name_href" => "ir/population-of-urmia","count" => "583 255","real_id" =>10,),
"11"=>array("name_ru"=>"Захедан","name_en"=>"Zahedan","name_href" => "ir/population-of-zahedan","count" => "567 449","real_id" =>11,),
"12"=>array("name_ru"=>"Решт","name_en"=>"Rasht","name_href" => "ir/population-of-rasht","count" => "557 366","real_id" =>12,),
"13"=>array("name_ru"=>"Керман","name_en"=>"Kerman","name_href" => "ir/population-of-kerman","count" => "515 114","real_id" =>13,),
"14"=>array("name_ru"=>"Хамадан","name_en"=>"Hamadan","name_href" => "ir/population-of-hamadan","count" => "479 640","real_id" =>14,),
"15"=>array("name_ru"=>"Эрак","name_en"=>"Erak","name_href" => "ir/population-of-erak","count" => "446 760","real_id" =>15,),
"16"=>array("name_ru"=>"Йезд","name_en"=>"Yazd","name_href" => "ir/population-of-yazd","count" => "432 194","real_id" =>16,),
"17"=>array("name_ru"=>"Ардебиль","name_en"=>"Ardabil","name_href" => "ir/population-of-ardabil","count" => "418 262","real_id" =>17,),
"18"=>array("name_ru"=>"Бендер-Аббас","name_en"=>"Bender-Abbas","name_href" => "ir/population-of-bender-abbas","count" => "379 301","real_id" =>18,),
"19"=>array("name_ru"=>"Исламшехр","name_en"=>"Islamshir","name_href" => "ir/population-of-islamshir","count" => "357 389","real_id" =>19,),
"20"=>array("name_ru"=>"Казвин","name_en"=>"Qazvin","name_href" => "ir/population-of-qazvin","count" => "355 338","real_id" =>20,),
"21"=>array("name_ru"=>"Зенджан","name_en"=>"Zanjan","name_href" => "ir/population-of-zanjan","count" => "349 713","real_id" =>21,),
"22"=>array("name_ru"=>"Хорремабад","name_en"=>"Khorramabad","name_href" => "ir/population-of-khorramabad","count" => "333 945","real_id" =>22,),
"23"=>array("name_ru"=>"Сенендедж","name_en"=>"Senendage","name_href" => "ir/population-of-senendage","count" => "316 862","real_id" =>23,),
"24"=>array("name_ru"=>"Горган","name_en"=>"Gorgan","name_href" => "ir/population-of-gorgan","count" => "274 438","real_id" =>24,),
"25"=>array("name_ru"=>"Сари","name_en"=>"Sari","name_href" => "ir/population-of-sari","count" => "261 293","real_id" =>25,),
"26"=>array("name_ru"=>"Кашан","name_en"=>"Kashan","name_href" => "ir/population-of-kashan","count" => "253 509","real_id" =>26,),
"27"=>array("name_ru"=>"Дизфуль","name_en"=>"Dizfull","name_href" => "ir/population-of-dizfull","count" => "235 819","real_id" =>27,),
"28"=>array("name_ru"=>"Голестан","name_en"=>"Golestan","name_href" => "ir/population-of-golestan","count" => "231 905","real_id" =>28,),
"29"=>array("name_ru"=>"Кудс","name_en"=>"Quds","name_href" => "ir/population-of-quds","count" => "230 147","real_id" =>29,),
"30"=>array("name_ru"=>"Боруджерд","name_en"=>"Borucerd","name_href" => "ir/population-of-borucerd","count" => "229 541","real_id" =>30,),
"31"=>array("name_ru"=>"Малард","name_en"=>"Malard","name_href" => "ir/population-of-malard","count" => "228 713","real_id" =>31,),
"32"=>array("name_ru"=>"Хомейнишехр","name_en"=>"Khomeinihehr","name_href" => "ir/population-of-khomeinihehr","count" => "223 071","real_id" =>32,),
"33"=>array("name_ru"=>"Абадан","name_en"=>"Abadan","name_href" => "ir/population-of-abadan","count" => "219 772","real_id" =>33,),
"34"=>array("name_ru"=>"Себзевар","name_en"=>"Sebzevar","name_href" => "ir/population-of-sebzevar","count" => "214 582","real_id" =>34,),
"35"=>array("name_ru"=>"Варамин","name_en"=>"Varamin","name_href" => "ir/population-of-varamin","count" => "208 996","real_id" =>35,),
"36"=>array("name_ru"=>"Нишапур","name_en"=>"Nishapur","name_href" => "ir/population-of-nishapur","count" => "208 860","real_id" =>36,),
"37"=>array("name_ru"=>"Наджафабад","name_en"=>"Najafabad","name_href" => "ir/population-of-najafabad","count" => "208 647","real_id" =>37,),
"38"=>array("name_ru"=>"Баболь","name_en"=>"Babol","name_href" => "ir/population-of-babol","count" => "201 335","real_id" =>38,),
"39"=>array("name_ru"=>"Амоль","name_en"=>"Аmol","name_href" => "ir/population-of-аmol","count" => "199 698","real_id" =>39,),
"40"=>array("name_ru"=>"Шехрияр","name_en"=>"Shehriyar","name_href" => "ir/population-of-shehriyar","count" => "189 421","real_id" =>40,),
"41"=>array("name_ru"=>"Хой","name_en"=>"Hoi An","name_href" => "ir/population-of-hoi-an","count" => "181 465","real_id" =>41,),
"42"=>array("name_ru"=>"Саве","name_en"=>"Sava","name_href" => "ir/population-of-sava","count" => "180 548","real_id" =>42,),
"43"=>array("name_ru"=>"Боджнурд","name_en"=>"Bojnurd","name_href" => "ir/population-of-bojnurd","count" => "176 726","real_id" =>43,),
"44"=>array("name_ru"=>"Каэмшехр","name_en"=>"Kaamshahr","name_href" => "ir/population-of-kaamshahr","count" => "174 768","real_id" =>44,),
"45"=>array("name_ru"=>"Гарчак","name_en"=>"Garchak","name_href" => "ir/population-of-garchak","count" => "174 006","real_id" =>45,),
"46"=>array("name_ru"=>"Сирджан","name_en"=>"Sirjan","name_href" => "ir/population-of-sirjan","count" => "170 916","real_id" =>46,),
"47"=>array("name_ru"=>"Бушир","name_en"=>"Bushehr","name_href" => "ir/population-of-bushehr","count" => "169 966","real_id" =>47,),
"48"=>array("name_ru"=>"Бирдженд","name_en"=>"Birdland","name_href" => "ir/population-of-birdland","count" => "166 138","real_id" =>48,),
"49"=>array("name_ru"=>"Илам","name_en"=>"Ilam","name_href" => "ir/population-of-ilam","count" => "160 355","real_id" =>49,),
"50"=>array("name_ru"=>"Малайер","name_en"=>"Malayer","name_href" => "ir/population-of-malayer","count" => "156 289","real_id" =>50,),
"51"=>array("name_ru"=>"Букан","name_en"=>"Bukane","name_href" => "ir/population-of-bukane","count" => "150 703","real_id" =>51,),
"52"=>array("name_ru"=>"Мераге","name_en"=>"Merage","name_href" => "ir/population-of-merage","count" => "149 929","real_id" =>52,),
"53"=>array("name_ru"=>"Рафсанджан","name_en"=>"Rafsanjan","name_href" => "ir/population-of-rafsanjan","count" => "139 219","real_id" =>53,),
"54"=>array("name_ru"=>"Заболь","name_en"=>"Zabol","name_href" => "ir/population-of-zabol","count" => "136 956","real_id" =>54,),
"55"=>array("name_ru"=>"Несимшехр","name_en"=>"Nesimshehr","name_href" => "ir/population-of-nesimshehr","count" => "135 846","real_id" =>55,),
"56"=>array("name_ru"=>"Мехабад","name_en"=>"Mehabad","name_href" => "ir/population-of-mehabad","count" => "135 780","real_id" =>56,),
"57"=>array("name_ru"=>"Саккез","name_en"=>"Sakkez","name_href" => "ir/population-of-sakkez","count" => "133 331","real_id" =>57,),
"58"=>array("name_ru"=>"Шахруд","name_en"=>"Shahrud","name_href" => "ir/population-of-shahrud","count" => "132 379","real_id" =>58,),
"59"=>array("name_ru"=>"Шехре-Корд","name_en"=>"Shehre Kord","name_href" => "ir/population-of-shehre-kord","count" => "131 612","real_id" =>59,),
"60"=>array("name_ru"=>"Гомбеде-Кавус","name_en"=>"Gombede-Cavus","name_href" => "ir/population-of-gombede-cavus","count" => "129 167","real_id" =>60,),
"61"=>array("name_ru"=>"Шахиншехр","name_en"=>"Shahinshahr","name_href" => "ir/population-of-shahinshahr","count" => "127 412","real_id" =>61,),
"62"=>array("name_ru"=>"Пакдешт","name_en"=>"Pakdesht","name_href" => "ir/population-of-pakdesht","count" => "126 937","real_id" =>62,),
"63"=>array("name_ru"=>"Семнан","name_en"=>"Semnan","name_href" => "ir/population-of-semnan","count" => "126 780","real_id" =>63,),
"64"=>array("name_ru"=>"Хорремшехр","name_en"=>"Khorramshahr","name_href" => "ir/population-of-khorramshahr","count" => "125 859","real_id" =>64,),
"65"=>array("name_ru"=>"Марвдешт","name_en"=>"Marvdesht","name_href" => "ir/population-of-marvdesht","count" => "124 350","real_id" =>65,),
"66"=>array("name_ru"=>"Торбате-Хейдарийе","name_en"=>"Torbat-Heydariy","name_href" => "ir/population-of-torbat-heydariy","count" => "121 300","real_id" =>66,),
"67"=>array("name_ru"=>"Андимешк","name_en"=>"Andymeshk","name_href" => "ir/population-of-andymeshk","count" => "120 177","real_id" =>67,),
"68"=>array("name_ru"=>"Меренд","name_en"=>"Merend","name_href" => "ir/population-of-merend","count" => "114 841","real_id" =>68,),
"69"=>array("name_ru"=>"Миандоаб","name_en"=>"Miandoab","name_href" => "ir/population-of-miandoab","count" => "114 153","real_id" =>69,),
"70"=>array("name_ru"=>"Махшехр","name_en"=>"Mahshehr","name_href" => "ir/population-of-mahshehr","count" => "111 448","real_id" =>70,),
"71"=>array("name_ru"=>"Энзели","name_en"=>"Anzali","name_href" => "ir/population-of-anzali","count" => "110 643","real_id" =>71,),
"72"=>array("name_ru"=>"Шехреза","name_en"=>"Shehrez","name_href" => "ir/population-of-shehrez","count" => "109 601","real_id" =>72,),
"73"=>array("name_ru"=>"Масджид-Солейман","name_en"=>"Masjid-Soleiman","name_href" => "ir/population-of-masjid-soleiman","count" => "108 682","real_id" =>73,),
"74"=>array("name_ru"=>"Джехром","name_en"=>"Gehrom","name_href" => "ir/population-of-gehrom","count" => "105 285","real_id" =>74,),
"75"=>array("name_ru"=>"Изе","name_en"=>"Uze","name_href" => "ir/population-of-uze","count" => "104 364","real_id" =>75,),
"76"=>array("name_ru"=>"Кучан","name_en"=>"Kuchan","name_href" => "ir/population-of-kuchan","count" => "101 313","real_id" =>76,),
"77"=>array("name_ru"=>"Доруд","name_en"=>"Dorud","name_href" => "ir/population-of-dorud","count" => "101 219","real_id" =>77,),
"78"=>array("name_ru"=>"Бехбехан","name_en"=>"Behbehan","name_href" => "ir/population-of-behbehan","count" => "101 178","real_id" =>78,),
"79"=>array("name_ru"=>"Ираншехр","name_en"=>"Iranahshir","name_href" => "ir/population-of-iranahshir","count" => "100 642","real_id" =>79,),
"80"=>array("name_ru"=>"Ясудж","name_en"=>"Yasuj","name_href" => "ir/population-of-yasuj","count" => "100 544","real_id" =>80,),
"81"=>array("name_ru"=>"Тегеран","name_en"=>"Tehran","name_href" => "ir/population-of-tehran","count" => "7 797 520","real_id" =>81,),
"82"=>array("name_ru"=>"Мешхед","name_en"=>"Mashad","name_href" => "ir/population-of-mashad","count" => "2 427 316","real_id" =>82,),
"83"=>array("name_ru"=>"Исфахан","name_en"=>"Isfahan","name_href" => "ir/population-of-isfahan","count" => "1 602 110","real_id" =>83,),
"84"=>array("name_ru"=>"Тебриз","name_en"=>"Tabriz","name_href" => "ir/population-of-tabriz","count" => "1 398 060","real_id" =>84,),
"85"=>array("name_ru"=>"Кередж","name_en"=>"Kerej","name_href" => "ir/population-of-kerej","count" => "1 386 030","real_id" =>85,)
);

?>