<?php
//Ямайка 35
$libjm = array ( 
"1"=>array("name_ru"=>"Кингстон","name_en"=>"kingston","name_href" => "jm/population-of-kingston","count" => "587 798","real_id" =>1,),
"2"=>array("name_ru"=>"Монтего-Бей","name_en"=>"Montego Bay","name_href" => "jm/population-of-montego-bay","count" => "96 488","real_id" =>2,),
"3"=>array("name_ru"=>"Спаниш-Таун","name_en"=>"Spanish Town","name_href" => "jm/population-of-spanish-town","count" => "92 383","real_id" =>3,),
"4"=>array("name_ru"=>"Портмор","name_en"=>"Portmore","name_href" => "jm/population-of-portmore","count" => "90 138","real_id" =>4,),
"5"=>array("name_ru"=>"Мей-Пен","name_en"=>"Mei-Pen","name_href" => "jm/population-of-mei-pen","count" => "45 903","real_id" =>5,),
"6"=>array("name_ru"=>"Мандевилл","name_en"=>"Mandeville","name_href" => "jm/population-of-mandeville","count" => "39 945","real_id" =>6,),
"7"=>array("name_ru"=>"Хаф-Уэй-Три","name_en"=>"Half Way Tree","name_href" => "jm/population-of-half-way-tree","count" => "18 139","real_id" =>7,),
"8"=>array("name_ru"=>"Олд Харбор","name_en"=>"Old Harbor","name_href" => "jm/population-of-old-harbor","count" => "17 778","real_id" =>8,),
"9"=>array("name_ru"=>"Саванна-ла-Мар","name_en"=>"Savanna-la-Mar","name_href" => "jm/population-of-savanna-la-mar","count" => "16 553","real_id" =>9,),
"10"=>array("name_ru"=>"Линстед","name_en"=>"Linstead","name_href" => "jm/population-of-linstead","count" => "14 114","real_id" =>10,),
"11"=>array("name_ru"=>"Порт-Антонио","name_en"=>"Port Antonio","name_href" => "jm/population-of-port-antonio","count" => "13 246","real_id" =>11,),
"12"=>array("name_ru"=>"Констант Спринг","name_en"=>"Constant Spring","name_href" => "jm/population-of-constant-spring","count" => "12 369","real_id" =>12,),
"13"=>array("name_ru"=>"Сент-Анс-Бей","name_en"=>"St. Anse Bay","name_href" => "jm/population-of-st.-anse-bay","count" => "10 961","real_id" =>13,),
"14"=>array("name_ru"=>"Морант-Бей","name_en"=>"Morant Bay","name_href" => "jm/population-of-morant-bay","count" => "9 602","real_id" =>14,),
"15"=>array("name_ru"=>"Бог-Волк","name_en"=>"God-Wolf","name_href" => "jm/population-of-god-wolf","count" => "8 794","real_id" =>15,),
"16"=>array("name_ru"=>"Эвартон","name_en"=>"Evarton","name_href" => "jm/population-of-evarton","count" => "8 742","real_id" =>16,),
"17"=>array("name_ru"=>"Хейз","name_en"=>"Hayes","name_href" => "jm/population-of-hayes","count" => "8 447","real_id" =>17,),
"18"=>array("name_ru"=>"Стони-Хилл","name_en"=>"Stony Hill","name_href" => "jm/population-of-stony-hill","count" => "8 244","real_id" =>18,),
"19"=>array("name_ru"=>"Очо-Риос","name_en"=>"Ocho Rios","name_href" => "jm/population-of-ocho-rios","count" => "8 189","real_id" =>19,),
"20"=>array("name_ru"=>"Санта-Круз","name_en"=>"Santa Cruz","name_href" => "jm/population-of-santa-cruz","count" => "8 144","real_id" =>20,),
"21"=>array("name_ru"=>"Порт-Мария","name_en"=>"Port Maria","name_href" => "jm/population-of-port-maria","count" => "7 651","real_id" =>21,),
"22"=>array("name_ru"=>"Фалмут","name_en"=>"Falmouth","name_href" => "jm/population-of-falmouth","count" => "7 245","real_id" =>22,),
"23"=>array("name_ru"=>"Христиана","name_en"=>"Christian","name_href" => "jm/population-of-christian","count" => "7 235","real_id" =>23,),
"24"=>array("name_ru"=>"Яллас","name_en"=>"Yallas","name_href" => "jm/population-of-yallas","count" => "6 902","real_id" =>24,),
"25"=>array("name_ru"=>"Браунс-Таун","name_en"=>"Browns Town","name_href" => "jm/population-of-browns-town","count" => "6 762","real_id" =>25,),
"26"=>array("name_ru"=>"Грэндж-Хилл","name_en"=>"Grange Hill","name_href" => "jm/population-of-grange-hill","count" => "6 530","real_id" =>26,),
"27"=>array("name_ru"=>"Лусеа","name_en"=>"Luse","name_href" => "jm/population-of-luse","count" => "6 002","real_id" =>27,),
"28"=>array("name_ru"=>"Раневей-Бей","name_en"=>"Runaway Bay","name_href" => "jm/population-of-runaway-bay","count" => "5 655","real_id" =>28,),
"29"=>array("name_ru"=>"Аннотто-Бей","name_en"=>"Annotto Bay","name_href" => "jm/population-of-annotto-bay","count" => "5 468","real_id" =>29,),
"30"=>array("name_ru"=>"Хайгейт","name_en"=>"Highgate","name_href" => "jm/population-of-highgate","count" => "5 418","real_id" =>30,),
"31"=>array("name_ru"=>"Олд-Харбор-Бей","name_en"=>"Old Harbour Bay","name_href" => "jm/population-of-old-harbour-bay","count" => "5 405","real_id" =>31,),
"32"=>array("name_ru"=>"Порус","name_en"=>"Porus","name_href" => "jm/population-of-porus","count" => "5 095","real_id" =>32,),
"33"=>array("name_ru"=>"Лайонел-Таун","name_en"=>"Lionel Town","name_href" => "jm/population-of-lionel-town","count" => "4 669","real_id" =>33,),
"34"=>array("name_ru"=>"Блэк-Ривер","name_en"=>"Black River","name_href" => "jm/population-of-black-river","count" => "3 675","real_id" =>34,),
"35"=>array("name_ru"=>"Порт-Роял","name_en"=>"Port Royal","name_href" => "jm/population-of-port-royal","count" => "3 004","real_id" =>35,),
"37"=>array("name_ru"=>"Монтего-Бей","name_en"=>"Montego Bay","name_href" => "jm/population-of-montego-bay","count" => "96 488","real_id" =>37,),
"38"=>array("name_ru"=>"Спаниш-Таун","name_en"=>"Spanish Town","name_href" => "jm/population-of-spanish-town","count" => "92 383","real_id" =>38,),
"39"=>array("name_ru"=>"Портмор","name_en"=>"Portmore","name_href" => "jm/population-of-portmore","count" => "90 138","real_id" =>39,),
"40"=>array("name_ru"=>"Мей-Пен","name_en"=>"Mei-Pen","name_href" => "jm/population-of-mei-pen","count" => "45 903","real_id" =>40,)
);

?>