<?php
//Иордания 40 
$libjo = array ( 
"1"=>array("name_ru"=>"Амман","name_en"=>"Amman","name_href" => "jo/population-of-amman","count" => "1 036 330","real_id" =>1,),
"2"=>array("name_ru"=>"Эз-Зарка","name_en"=>"Zarqa","name_href" => "jo/population-of-zarqa","count" => "395 227","real_id" =>2,),
"3"=>array("name_ru"=>"Ирбид","name_en"=>"Irbid","name_href" => "jo/population-of-irbid","count" => "250 645","real_id" =>3,),
"4"=>array("name_ru"=>"Ар-Русайфа","name_en"=>"ar-Rusaifa","name_href" => "jo/population-of-ar-rusaifa","count" => "227 735","real_id" =>4,),
"5"=>array("name_ru"=>"Эль-Кувейсима","name_en"=>"al-Quwaisima","name_href" => "jo/population-of-al-quwaisima","count" => "135 500","real_id" =>5,),
"6"=>array("name_ru"=>"Вади ас-Сир","name_en"=>"Wadi as-Sir","name_href" => "jo/population-of-wadi-as-sir","count" => "122 032","real_id" =>6,),
"7"=>array("name_ru"=>"Тила эль-Али","name_en"=>"Tila al-Ali","name_href" => "jo/population-of-tila-al-ali","count" => "113 197","real_id" =>7,),
"8"=>array("name_ru"=>"Хурайбат ас-Сук","name_en"=>"Churaibat as-Suq","name_href" => "jo/population-of-churaibat-as-suq","count" => "84 975","real_id" =>8,),
"9"=>array("name_ru"=>"Акаба","name_en"=>"Aqaba","name_href" => "jo/population-of-aqaba","count" => "80 059","real_id" =>9,),
"10"=>array("name_ru"=>"Эс-Салт","name_en"=>"as-Salt","name_href" => "jo/population-of-as-salt","count" => "73 528","real_id" =>10,),
"11"=>array("name_ru"=>"Эр-Рамта","name_en"=>"ar-Ramtha","name_href" => "jo/population-of-ar-ramtha","count" => "71 433","real_id" =>11,),
"12"=>array("name_ru"=>"Мадаба","name_en"=>"Madaba","name_href" => "jo/population-of-madaba","count" => "70 338","real_id" =>12,),
"13"=>array("name_ru"=>"Эль-Джубейха","name_en"=>"al-Dschubaiha","name_href" => "jo/population-of-al-dschubaiha","count" => "64 200","real_id" =>13,),
"14"=>array("name_ru"=>"Эль-Бака","name_en"=>"al-Baq’a","name_href" => "jo/population-of-al-baq’a","count" => "62 508","real_id" =>14,),
"15"=>array("name_ru"=>"Сувайлих","name_en"=>"Suwailih","name_href" => "jo/population-of-suwailih","count" => "61 949","real_id" =>15,),
"16"=>array("name_ru"=>"Эль-Мафрак","name_en"=>"al-Mafraq","name_href" => "jo/population-of-al-mafraq","count" => "47 764","real_id" =>16,),
"17"=>array("name_ru"=>"Сахаб","name_en"=>"Sahab","name_href" => "jo/population-of-sahab","count" => "43 909","real_id" =>17,),
"18"=>array("name_ru"=>"Мучаям Хеттен","name_en"=>"Muchayyam Hetten","name_href" => "jo/population-of-muchayyam-hetten","count" => "38 501","real_id" =>18,),
"19"=>array("name_ru"=>"Айн эль-Баша","name_en"=>"Ain al-Bascha","name_href" => "jo/population-of-ain-al-bascha","count" => "37 222","real_id" =>19,),
"20"=>array("name_ru"=>"Ум Кес","name_en"=>"Umm Qusair","name_href" => "jo/population-of-umm-qusair","count" => "36 785","real_id" =>20,),
"21"=>array("name_ru"=>"Джараш","name_en"=>"Jerash","name_href" => "jo/population-of-jerash","count" => "31 652","real_id" =>21,),
"22"=>array("name_ru"=>"Мардш эль-Хамам","name_en"=>"Mardsch al-Hamam","name_href" => "jo/population-of-mardsch-al-hamam","count" => "30 173","real_id" =>22,),
"23"=>array("name_ru"=>"Ад-Дулайл","name_en"=>"ad-Dulail","name_href" => "jo/population-of-ad-dulail","count" => "27 643","real_id" =>23,),
"24"=>array("name_ru"=>"Маан","name_en"=>"Ma’an","name_href" => "jo/population-of-ma’an","count" => "26 461","real_id" =>24,),
"25"=>array("name_ru"=>"Эль-Хасимия","name_en"=>"al-Hasimiya","name_href" => "jo/population-of-al-hasimiya","count" => "25 475","real_id" =>25,),
"26"=>array("name_ru"=>"Аскан Абу Нусайр","name_en"=>"Askan Abu Nusair","name_href" => "jo/population-of-askan-abu-nusair","count" => "24 680","real_id" =>26,),
"27"=>array("name_ru"=>"Эт-Тафила","name_en"=>"at-Tafilah","name_href" => "jo/population-of-at-tafilah","count" => "23 512","real_id" =>27,),
"28"=>array("name_ru"=>"Куфриндша","name_en"=>"Kufrindscha","name_href" => "jo/population-of-kufrindscha","count" => "21 734","real_id" =>28,),
"29"=>array("name_ru"=>"Ас-Хусун","name_en"=>"al-Husun","name_href" => "jo/population-of-al-husun","count" => "20 485","real_id" =>29,),
"30"=>array("name_ru"=>"Эль-Карак","name_en"=>"al-Karak","name_href" => "jo/population-of-al-karak","count" => "20 280","real_id" =>30,),
"31"=>array("name_ru"=>"Ас-Сарих","name_en"=>"as-Sarih","name_href" => "jo/population-of-as-sarih","count" => "19 210","real_id" =>31,),
"32"=>array("name_ru"=>"Айдун","name_en"=>"Aidun","name_href" => "jo/population-of-aidun","count" => "18 586","real_id" =>32,),
"33"=>array("name_ru"=>"Эль-Машарика","name_en"=>"al-Maschariqa","name_href" => "jo/population-of-al-maschariqa","count" => "18 282","real_id" =>33,),
"34"=>array("name_ru"=>"Байт Рас","name_en"=>"Bait Ras","name_href" => "jo/population-of-bait-ras","count" => "18 023","real_id" =>34,),
"35"=>array("name_ru"=>"Аджлун","name_en"=>"Ajlun","name_href" => "jo/population-of-ajlun","count" => "17 618","real_id" =>35,),
"36"=>array("name_ru"=>"Гавр аш-Шафи","name_en"=>"Gawr asch-Schafi","name_href" => "jo/population-of-gawr-asch-schafi","count" => "16 756","real_id" =>36,),
"37"=>array("name_ru"=>"Азми эль-Муфти","name_en"=>"Azmi al-Mufti","name_href" => "jo/population-of-azmi-al-mufti","count" => "16 615","real_id" =>37,),
"38"=>array("name_ru"=>"Кураима","name_en"=>"Kurayyima","name_href" => "jo/population-of-kurayyima","count" => "15 733","real_id" =>38,),
"39"=>array("name_ru"=>"Наур","name_en"=>"Na’ur","name_href" => "jo/population-of-na’ur","count" => "15 439","real_id" =>39,),
"40"=>array("name_ru"=>"Шафа Бадран","name_en"=>"Schafa Badran","name_href" => "jo/population-of-schafa-badran","count" => "15 333","real_id" =>40,),
"41"=>array("name_ru"=>"Амман","name_en"=>"Amman","name_href" => "jo/population-of-amman","count" => "1 036 330","real_id" =>41,),
"42"=>array("name_ru"=>"Эз-Зарка","name_en"=>"Zarqa","name_href" => "jo/population-of-zarqa","count" => "395 227","real_id" =>42,),
"43"=>array("name_ru"=>"Ирбид","name_en"=>"Irbid","name_href" => "jo/population-of-irbid","count" => "250 645","real_id" =>43,),
"44"=>array("name_ru"=>"Ар-Русайфа","name_en"=>"ar-Rusaifa","name_href" => "jo/population-of-ar-rusaifa","count" => "227 735","real_id" =>44,),
"45"=>array("name_ru"=>"Эль-Кувейсима","name_en"=>"al-Quwaisima","name_href" => "jo/population-of-al-quwaisima","count" => "135 500","real_id" =>45,)
);

?>