<?php
//Казахстан 87 
$libkz = array ( 
"1"=>array("name_ru"=>"Алма-Ата","name_en"=>"Alma-Ata","name_href" => "kz/population-of-alma-ata","count" => "1 534 353","real_id" =>1,),
"2"=>array("name_ru"=>"Астана","name_en"=>"Astana","name_href" => "kz/population-of-astana","count" => "844 930","real_id" =>2,),
"3"=>array("name_ru"=>"Шымкент","name_en"=>"Shymkent","name_href" => "kz/population-of-shymkent","count" => "704 983","real_id" =>3,),
"4"=>array("name_ru"=>"Караганда","name_en"=>"Karaganda","name_href" => "kz/population-of-karaganda","count" => "489 355","real_id" =>4,),
"5"=>array("name_ru"=>"Актюбинск","name_en"=>"Aqtobe","name_href" => "kz/population-of-aqtobe","count" => "385 438","real_id" =>5,),
"6"=>array("name_ru"=>"Тараз","name_en"=>"Taraz","name_href" => "kz/population-of-taraz","count" => "355 682","real_id" =>6,),
"7"=>array("name_ru"=>"Павлодар","name_en"=>"Pavlodar","name_href" => "kz/population-of-pavlodar","count" => "332 062","real_id" =>7,),
"8"=>array("name_ru"=>"Усть-Каменогорск","name_en"=>"Ust-Kamenogorsk","name_href" => "kz/population-of-ust-kamenogorsk","count" => "316 093","real_id" =>8,),
"9"=>array("name_ru"=>"Семея","name_en"=>"Families","name_href" => "kz/population-of-families","count" => "312 986","real_id" =>9,),
"10"=>array("name_ru"=>"Уральск","name_en"=>"Uralsk","name_href" => "kz/population-of-uralsk","count" => "230 354","real_id" =>10,),
"11"=>array("name_ru"=>"Костанай","name_en"=>"Kostanay","name_href" => "kz/population-of-kostanay","count" => "225 464","real_id" =>11,),
"12"=>array("name_ru"=>"Кызылорд","name_en"=>"Kyzylorda","name_href" => "kz/population-of-kyzylorda","count" => "218 300","real_id" =>12,),
"13"=>array("name_ru"=>"Петропавловск","name_en"=>"Petropavlovsk","name_href" => "kz/population-of-petropavlovsk","count" => "208 979","real_id" =>13,),
"14"=>array("name_ru"=>"Атырау","name_en"=>"Atyrau","name_href" => "kz/population-of-atyrau","count" => "202 026","real_id" =>14,),
"15"=>array("name_ru"=>"Актау","name_en"=>"Aktau","name_href" => "kz/population-of-aktau","count" => "182 033","real_id" =>15,),
"16"=>array("name_ru"=>"Темиртау","name_en"=>"Temirtau","name_href" => "kz/population-of-temirtau","count" => "176 865","real_id" =>16,),
"17"=>array("name_ru"=>"Туркестан","name_en"=>"Turkistan","name_href" => "kz/population-of-turkistan","count" => "157 399","real_id" =>17,),
"18"=>array("name_ru"=>"Кокшетау","name_en"=>"Kokshetau","name_href" => "kz/population-of-kokshetau","count" => "141 396","real_id" =>18,),
"19"=>array("name_ru"=>"Талдыкорган","name_en"=>"Taldykorgan","name_href" => "kz/population-of-taldykorgan","count" => "137 654","real_id" =>19,),
"20"=>array("name_ru"=>"Экибастуз","name_en"=>"Ekibastuz","name_href" => "kz/population-of-ekibastuz","count" => "132 075","real_id" =>20,),
"21"=>array("name_ru"=>"Рудного","name_en"=>"Ore","name_href" => "kz/population-of-ore","count" => "114 725","real_id" =>21,),
"22"=>array("name_ru"=>"Жанаозен","name_en"=>"Zhanaozen","name_href" => "kz/population-of-zhanaozen","count" => "110 272","real_id" =>22,),
"23"=>array("name_ru"=>"Жезказган","name_en"=>"Zhezkazgan","name_href" => "kz/population-of-zhezkazgan","count" => "84 977","real_id" =>23,),
"24"=>array("name_ru"=>"Байконур","name_en"=>"Baikonur","name_href" => "kz/population-of-baikonur","count" => "73 464","real_id" =>24,),
"25"=>array("name_ru"=>"Балхаш","name_en"=>"Balkhash","name_href" => "kz/population-of-balkhash","count" => "71 339","real_id" =>25,),
"26"=>array("name_ru"=>"Кентау","name_en"=>"Kentau","name_href" => "kz/population-of-kentau","count" => "64 682","real_id" =>26,),
"27"=>array("name_ru"=>"Каскелен","name_en"=>"Kaskelen","name_href" => "kz/population-of-kaskelen","count" => "64 416","real_id" =>27,),
"28"=>array("name_ru"=>"Сатпаев","name_en"=>"Satpayev","name_href" => "kz/population-of-satpayev","count" => "61 816","real_id" =>28,),
"29"=>array("name_ru"=>"Кульсары","name_en"=>"Kulsary","name_href" => "kz/population-of-kulsary","count" => "55 742","real_id" =>29,),
"30"=>array("name_ru"=>"Риддер","name_en"=>"Ridder","name_href" => "kz/population-of-ridder","count" => "49 574","real_id" =>30,),
"31"=>array("name_ru"=>"Талгар","name_en"=>"Talgar","name_href" => "kz/population-of-talgar","count" => "48 107","real_id" =>31,),
"32"=>array("name_ru"=>"Степногорск","name_en"=>"Stepnogorsk","name_href" => "kz/population-of-stepnogorsk","count" => "47 045","real_id" =>32,),
"33"=>array("name_ru"=>"Щучинск","name_en"=>"Shchuchinsk","name_href" => "kz/population-of-shchuchinsk","count" => "45 963","real_id" =>33,),
"34"=>array("name_ru"=>"Капчагай","name_en"=>"Kapchagai","name_href" => "kz/population-of-kapchagai","count" => "43 618","real_id" =>34,),
"35"=>array("name_ru"=>"Сарани","name_en"=>"Saranj","name_href" => "kz/population-of-saranj","count" => "43 164","real_id" =>35,),
"36"=>array("name_ru"=>"Жаркент","name_en"=>"Zharkent","name_href" => "kz/population-of-zharkent","count" => "42 809","real_id" =>36,),
"37"=>array("name_ru"=>"Аксу","name_en"=>"Aksu","name_href" => "kz/population-of-aksu","count" => "42 519","real_id" =>37,),
"38"=>array("name_ru"=>"Арыс","name_en"=>"Arys","name_href" => "kz/population-of-arys","count" => "42 286","real_id" =>38,),
"39"=>array("name_ru"=>"Сарыагаш","name_en"=>"Saryagash","name_href" => "kz/population-of-saryagash","count" => "39 758","real_id" =>39,),
"40"=>array("name_ru"=>"Шахтинск","name_en"=>"Shakhtinsk","name_href" => "kz/population-of-shakhtinsk","count" => "38 468","real_id" =>40,),
"41"=>array("name_ru"=>"Есик","name_en"=>"Esik","name_href" => "kz/population-of-esik","count" => "38 440","real_id" =>41,),
"42"=>array("name_ru"=>"Зыряновск","name_en"=>"Zyryanovsk","name_href" => "kz/population-of-zyryanovsk","count" => "37 806","real_id" =>42,),
"43"=>array("name_ru"=>"Аягуз","name_en"=>"Ayaguz","name_href" => "kz/population-of-ayaguz","count" => "37 392","real_id" =>43,),
"44"=>array("name_ru"=>"Лисаковск","name_en"=>"Lisakovsk","name_href" => "kz/population-of-lisakovsk","count" => "36 848","real_id" =>44,),
"45"=>array("name_ru"=>"Шу","name_en"=>"Shu","name_href" => "kz/population-of-shu","count" => "35 929","real_id" =>45,),
"46"=>array("name_ru"=>"Житикар","name_en"=>"Jitikara","name_href" => "kz/population-of-jitikara","count" => "35 132","real_id" =>46,),
"47"=>array("name_ru"=>"Аксай","name_en"=>"Aksai","name_href" => "kz/population-of-aksai","count" => "33 589","real_id" =>47,),
"48"=>array("name_ru"=>"Кандыагаш","name_en"=>"Kandyagash","name_href" => "kz/population-of-kandyagash","count" => "32 102","real_id" =>48,),
"49"=>array("name_ru"=>"Аральск","name_en"=>"Aralsk","name_href" => "kz/population-of-aralsk","count" => "31 768","real_id" =>49,),
"50"=>array("name_ru"=>"Чардара","name_en"=>"Chardara","name_href" => "kz/population-of-chardara","count" => "30 850","real_id" =>50,),
"51"=>array("name_ru"=>"Текели","name_en"=>"Tekeli","name_href" => "kz/population-of-tekeli","count" => "30 079","real_id" =>51,),
"52"=>array("name_ru"=>"Жетысай","name_en"=>"Zhetysai","name_href" => "kz/population-of-zhetysai","count" => "29 688","real_id" =>52,),
"53"=>array("name_ru"=>"Атбасар","name_en"=>"Atbasar","name_href" => "kz/population-of-atbasar","count" => "29 673","real_id" =>53,),
"54"=>array("name_ru"=>"Аркалык","name_en"=>"Arkalyk","name_href" => "kz/population-of-arkalyk","count" => "28 968","real_id" =>54,),
"55"=>array("name_ru"=>"Абай","name_en"=>"Abay","name_href" => "kz/population-of-abay","count" => "27 954","real_id" =>55,),
"56"=>array("name_ru"=>"Шалкар","name_en"=>"Shalkar","name_href" => "kz/population-of-shalkar","count" => "27 703","real_id" =>56,),
"57"=>array("name_ru"=>"Каратау","name_en"=>"Karatau","name_href" => "kz/population-of-karatau","count" => "27 667","real_id" =>57,),
"58"=>array("name_ru"=>"Хромтау","name_en"=>"Khromtau","name_href" => "kz/population-of-khromtau","count" => "25 198","real_id" =>58,),
"59"=>array("name_ru"=>"Уштобе","name_en"=>"Ushtobe","name_href" => "kz/population-of-ushtobe","count" => "24 743","real_id" =>59,),
"60"=>array("name_ru"=>"Ленгер","name_en"=>"Lenger","name_href" => "kz/population-of-lenger","count" => "24 302","real_id" =>60,),
"61"=>array("name_ru"=>"Жанатас","name_en"=>"Zhanatas","name_href" => "kz/population-of-zhanatas","count" => "21 658","real_id" =>61,),
"62"=>array("name_ru"=>"Алги","name_en"=>"Alga","name_href" => "kz/population-of-alga","count" => "19 997","real_id" =>62,),
"63"=>array("name_ru"=>"Шемонаиха","name_en"=>"Shemonaikha","name_href" => "kz/population-of-shemonaikha","count" => "18 211","real_id" =>63,),
"64"=>array("name_ru"=>"Учарал","name_en"=>"Ucharal","name_href" => "kz/population-of-ucharal","count" => "17 523","real_id" =>64,),
"65"=>array("name_ru"=>"Макинск","name_en"=>"Makinsk","name_href" => "kz/population-of-makinsk","count" => "17 205","real_id" =>65,),
"66"=>array("name_ru"=>"Зайсан","name_en"=>"Zaisan","name_href" => "kz/population-of-zaisan","count" => "15 712","real_id" =>66,),
"67"=>array("name_ru"=>"Сарканд","name_en"=>"Sarkand","name_href" => "kz/population-of-sarkand","count" => "13 914","real_id" =>67,),
"68"=>array("name_ru"=>"Акколь","name_en"=>"Akkol","name_href" => "kz/population-of-akkol","count" => "13 708","real_id" =>68,),
"69"=>array("name_ru"=>"Приозёрск","name_en"=>"Priozersk","name_href" => "kz/population-of-priozersk","count" => "13 367","real_id" =>69,),
"70"=>array("name_ru"=>"Курчатов","name_en"=>"Kurchatov","name_href" => "kz/population-of-kurchatov","count" => "11 810","real_id" =>70,),
"71"=>array("name_ru"=>"Эмба","name_en"=>"Emba","name_href" => "kz/population-of-emba","count" => "11 735","real_id" =>71,),
"72"=>array("name_ru"=>"Тайынш","name_en"=>"Tayinsha","name_href" => "kz/population-of-tayinsha","count" => "11 437","real_id" =>72,),
"73"=>array("name_ru"=>"Есил","name_en"=>"Yesil","name_href" => "kz/population-of-yesil","count" => "10 895","real_id" =>73,),
"74"=>array("name_ru"=>"Ерейментау","name_en"=>"Ereimentau","name_href" => "kz/population-of-ereimentau","count" => "10 349","real_id" =>74,),
"75"=>array("name_ru"=>"Каражалы","name_en"=>"Karazhal","name_href" => "kz/population-of-karazhal","count" => "9 569","real_id" =>75,),
"76"=>array("name_ru"=>"Серебрянск","name_en"=>"Serebryansk","name_href" => "kz/population-of-serebryansk","count" => "9 071","real_id" =>76,),
"77"=>array("name_ru"=>"Каркаралинск","name_en"=>"Karkaralinsk","name_href" => "kz/population-of-karkaralinsk","count" => "8 633","real_id" =>77,),
"78"=>array("name_ru"=>"Шар","name_en"=>"Ball","name_href" => "kz/population-of-ball","count" => "7 710","real_id" =>78,),
"79"=>array("name_ru"=>"Булаево","name_en"=>"Bulaevo","name_href" => "kz/population-of-bulaevo","count" => "7 606","real_id" =>79,),
"80"=>array("name_ru"=>"Сергеевка","name_en"=>"Sergeevka","name_href" => "kz/population-of-sergeevka","count" => "7 374","real_id" =>80,),
"81"=>array("name_ru"=>"Мамлютка","name_en"=>"Mamlutka","name_href" => "kz/population-of-mamlutka","count" => "7 238","real_id" =>81,),
"82"=>array("name_ru"=>"Казалинск","name_en"=>"Kazalinsk","name_href" => "kz/population-of-kazalinsk","count" => "7 214","real_id" =>82,),
"83"=>array("name_ru"=>"Державинск","name_en"=>"Derzhavinsk","name_href" => "kz/population-of-derzhavinsk","count" => "6 307","real_id" =>83,),
"84"=>array("name_ru"=>"Форт-Шевченко","name_en"=>"Fort Shevchenko","name_href" => "kz/population-of-fort-shevchenko","count" => "5 362","real_id" =>84,),
"85"=>array("name_ru"=>"Степняк","name_en"=>"Stepnyak","name_href" => "kz/population-of-stepnyak","count" => "3 844","real_id" =>85,),
"86"=>array("name_ru"=>"Темир","name_en"=>"Temir","name_href" => "kz/population-of-temir","count" => "2 520","real_id" =>86,),
"87"=>array("name_ru"=>"Жем","name_en"=>"Gem","name_href" => "kz/population-of-gem","count" => "2 033","real_id" =>87,),
"88"=>array("name_ru"=>"Алма-Ата","name_en"=>"Alma-Ata","name_href" => "kz/population-of-alma-ata","count" => "1 534 353","real_id" =>88,),
"89"=>array("name_ru"=>"Астана","name_en"=>"Astana","name_href" => "kz/population-of-astana","count" => "844 930","real_id" =>89,),
"90"=>array("name_ru"=>"Шымкент","name_en"=>"Shymkent","name_href" => "kz/population-of-shymkent","count" => "704 983","real_id" =>90,),
"91"=>array("name_ru"=>"Караганда","name_en"=>"Karaganda","name_href" => "kz/population-of-karaganda","count" => "489 355","real_id" =>91,),
"92"=>array("name_ru"=>"Актюбинск","name_en"=>"Aqtobe","name_href" => "kz/population-of-aqtobe","count" => "385 438","real_id" =>92,)
);

?>