<?php
// Всего 15 королевст
$libkingdom = array ( 
"1"=>array("name_country_ru"=>"Таиланд","name_country_en"=>"Thailand","name_country_href" => "th/population-of-thailand","count" => "71 037 513","country_flag" => "flag_of_thailand.png","count_city_country" => "20","rate_city_country"  =>"th/list-of-cities-in-thailand-by-population","country_iso"  =>"th","name_country_ru_zz" =>"Таиланда","real_id" =>1,),
"2"=>array("name_country_ru"=>"Англия","name_country_en"=>"England","name_country_href" => "eng/population-of-england","count" => "55 619 400","country_flag" => "flag_of_england.png","count_city_country" => "194","rate_city_country"  =>"eng/list-of-cities-in-england-by-population","country_iso"  =>"eng","name_country_ru_zz" =>"Англии","real_id" =>2,),
"3"=>array("name_country_ru"=>"Испания","name_country_en"=>"Spain","name_country_href" => "es/population-of-spain","count" => "46 528 966","country_flag" => "flag_of_spain.png","count_city_country" => "29","rate_city_country"  =>"es/list-of-cities-in-spain-by-population","country_iso"  =>"es","name_country_ru_zz" =>"Испании","real_id" =>3,),
"4"=>array("name_country_ru"=>"Саудовская Аравия","name_country_en"=>"Saudi Arabia","name_country_href" => "sa/population-of-saudi-arabia","count" => "42 248 200","country_flag" => "flag_of_saudi_arabia.png","count_city_country" => "27","rate_city_country"  =>"sa/list-of-cities-in-saudi-arabia-by-population","country_iso"  =>"sa","name_country_ru_zz" =>"Саудовской Аравии","real_id" =>4,),
"5"=>array("name_country_ru"=>"Марокко","name_country_en"=>"Morocco","name_country_href" => "ma/population-of-morocco","count" => "35 340 000","country_flag" => "flag_of_morocco.png","count_city_country" => "70","rate_city_country"  =>"ma/list-of-cities-in-morocco-by-population","country_iso"  =>"ma","name_country_ru_zz" =>"Марокко","real_id" =>5,),
"6"=>array("name_country_ru"=>"Камбоджа","name_country_en"=>"Cambodia","name_country_href" => "kh/population-of-cambodia","count" => "24 827 241","country_flag" => "flag_of_cambodia.png","count_city_country" => "25","rate_city_country"  =>"kh/list-of-cities-in-cambodia-by-population","country_iso"  =>"kh","name_country_ru_zz" =>"Камбоджа","real_id" =>6,),
"7"=>array("name_country_ru"=>"Бельгия","name_country_en"=>"Belgium","name_country_href" => "be/population-of-belgium","count" => "11 838 158","country_flag" => "flag_of_belgium.png","count_city_country" => "135","rate_city_country"  =>"be/list-of-cities-in-belgium-by-population","country_iso"  =>"be","name_country_ru_zz" =>"Бельгии","real_id" =>7,),
"8"=>array("name_country_ru"=>"Швеция","name_country_en"=>"Sweden","name_country_href" => "se/population-of-sweden","count" => "10 005 673","country_flag" => "flag_of_sweden.png","count_city_country" => "96","rate_city_country"  =>"se/list-of-cities-in-sweden-by-population","country_iso"  =>"se","name_country_ru_zz" =>"Швеции","real_id" =>8,),
"9"=>array("name_country_ru"=>"Дания","name_country_en"=>"Denmark","name_country_href" => "dk/population-of-denmark","count" => "5 668 743","country_flag" => "flag_of_denmark.png","count_city_country" => "56","rate_city_country"  =>"dk/list-of-cities-in-denmark-by-population","country_iso"  =>"dk","name_country_ru_zz" =>"Дании","real_id" =>9,),
"10"=>array("name_country_ru"=>"Норвегия","name_country_en"=>"Norway","name_country_href" => "no/population-of-norway","count" => "5 405 200","country_flag" => "flag_of_norway.png","count_city_country" => "101","rate_city_country"  =>"no/list-of-cities-in-norway-by-population","country_iso"  =>"no","name_country_ru_zz" =>"Норвегии","real_id" =>10,),
"11"=>array("name_country_ru"=>"Лесото","name_country_en"=>"Lesotho","name_country_href" => "ls/population-of-lesotho","count" => "2 160 309","country_flag" => "flag_of_lesotho.png","count_city_country" => "11","rate_city_country"  =>"ls/list-of-cities-in-lesotho-by-population","country_iso"  =>"ls","name_country_ru_zz" =>"Лесото","real_id" =>11,),
"12"=>array("name_country_ru"=>"Бахрейн","name_country_en"=>"Bahrain","name_country_href" => "bh/population-of-bahrain","count" => "1 451 200","country_flag" => "flag_of_bahrain.png","count_city_country" => "11","rate_city_country"  =>"bh/list-of-cities-in-bahrain-by-population","country_iso"  =>"bh","name_country_ru_zz" =>"Бахрейна","real_id" =>12,),
"13"=>array("name_country_ru"=>"Свазиленд","name_country_en"=>"Swaziland","name_country_href" => "sz/population-of-swaziland","count" => "1 367 254","country_flag" => "flag_of_swaziland.png","count_city_country" => "20","rate_city_country"  =>"sz/list-of-cities-in-swaziland-by-population","country_iso"  =>"sz","name_country_ru_zz" =>"Свазиленда","real_id" =>13,),
"14"=>array("name_country_ru"=>"Бутан","name_country_en"=>"Butane","name_country_href" => "bt/population-of-butane","count" => "784 103","country_flag" => "flag_of_bhutan.png","count_city_country" => "24","rate_city_country"  =>"bt/list-of-cities-in-butane-by-population","country_iso"  =>"bt","name_country_ru_zz" =>"Бутана","real_id" =>14,),
"15"=>array("name_country_ru"=>"Тонга","name_country_en"=>"Tonga","name_country_href" => "to/population-of-tonga","count" => "106 915","country_flag" => "flag_of_tonga.png","count_city_country" => "9","rate_city_country"  =>"to/list-of-cities-in-tonga-by-population","country_iso"  =>"to","name_country_ru_zz" =>"Тонга","real_id" =>15,),
);

?>