<?php
//Кения 50 
$libke = array ( 
"1"=>array("name_ru"=>"Найроби","name_en"=>"Nairobi","name_href" => "ke/population-of-nairobi","count" => "3 476 632","real_id" =>1,),
"2"=>array("name_ru"=>"Момбаса","name_en"=>"Mombasa","name_href" => "ke/population-of-mombasa","count" => "966 413","real_id" =>2,),
"3"=>array("name_ru"=>"Накуру","name_en"=>"Nakuru","name_href" => "ke/population-of-nakuru","count" => "284 840","real_id" =>3,),
"4"=>array("name_ru"=>"Элдорет","name_en"=>"Eldoret","name_href" => "ke/population-of-eldoret","count" => "269 574","real_id" =>4,),
"5"=>array("name_ru"=>"Кисуму","name_en"=>"Kisumu","name_href" => "ke/population-of-kisumu","count" => "236 394","real_id" =>5,),
"6"=>array("name_ru"=>"Руиру","name_en"=>"Kiserian","name_href" => "ke/population-of-kiserian","count" => "182 598","real_id" =>6,),
"7"=>array("name_ru"=>"Тайка","name_en"=>"Taika","name_href" => "ke/population-of-taika","count" => "110 336","real_id" =>7,),
"8"=>array("name_ru"=>"Малинди","name_en"=>"Malindi","name_href" => "ke/population-of-malindi","count" => "88 209","real_id" =>8,),
"9"=>array("name_ru"=>"Китале","name_en"=>"Kitale","name_href" => "ke/population-of-kitale","count" => "84 526","real_id" =>9,),
"10"=>array("name_ru"=>"Бунгома","name_en"=>"Bungoma","name_href" => "ke/population-of-bungoma","count" => "84 042","real_id" =>10,),
"11"=>array("name_ru"=>"Какамега","name_en"=>"Kakamega","name_href" => "ke/population-of-kakamega","count" => "73 567","real_id" =>11,),
"12"=>array("name_ru"=>"Килифи","name_en"=>"Kilifi","name_href" => "ke/population-of-kilifi","count" => "72 715","real_id" =>12,),
"13"=>array("name_ru"=>"Гарисса","name_en"=>"Garissa","name_href" => "ke/population-of-garissa","count" => "67 357","real_id" =>13,),
"14"=>array("name_ru"=>"Мумиас","name_en"=>"Mumias","name_href" => "ke/population-of-mumias","count" => "62 522","real_id" =>14,),
"15"=>array("name_ru"=>"Нарок","name_en"=>"Narok","name_href" => "ke/population-of-narok","count" => "53 709","real_id" =>15,),
"16"=>array("name_ru"=>"Меру","name_en"=>"Measure","name_href" => "ke/population-of-measure","count" => "53 004","real_id" =>16,),
"17"=>array("name_ru"=>"Бусиа","name_en"=>"Busia","name_href" => "ke/population-of-busia","count" => "51 193","real_id" =>17,),
"18"=>array("name_ru"=>"Мандера","name_en"=>"Mandera","name_href" => "ke/population-of-mandera","count" => "50 576","real_id" =>18,),
"19"=>array("name_ru"=>"Ньери","name_en"=>"Nyeri","name_href" => "ke/population-of-nyeri","count" => "49 639","real_id" =>19,),
"20"=>array("name_ru"=>"Ронгэй","name_en"=>"Rongai","name_href" => "ke/population-of-rongai","count" => "49 503","real_id" =>20,),
"21"=>array("name_ru"=>"Хома-Бей","name_en"=>"Homa Bay","name_href" => "ke/population-of-homa-bay","count" => "44 504","real_id" =>21,),
"22"=>array("name_ru"=>"Найваша","name_en"=>"Naivasha","name_href" => "ke/population-of-naivasha","count" => "43 839","real_id" =>22,),
"23"=>array("name_ru"=>"Ваджир","name_en"=>"Wajir","name_href" => "ke/population-of-wajir","count" => "43 832","real_id" =>23,),
"24"=>array("name_ru"=>"Ньяхуруру","name_en"=>"Nyahururu","name_href" => "ke/population-of-nyahururu","count" => "42 165","real_id" =>24,),
"25"=>array("name_ru"=>"Керико","name_en"=>"Carico","name_href" => "ke/population-of-carico","count" => "40 847","real_id" =>25,),
"26"=>array("name_ru"=>"Нанюки","name_en"=>"Nanyuki","name_href" => "ke/population-of-nanyuki","count" => "40 009","real_id" =>26,),
"27"=>array("name_ru"=>"Мигори","name_en"=>"Mihintale","name_href" => "ke/population-of-mihintale","count" => "38 482","real_id" =>27,),
"28"=>array("name_ru"=>"Эмбу","name_en"=>"Embu","name_href" => "ke/population-of-embu","count" => "37 781","real_id" =>28,),
"29"=>array("name_ru"=>"Исиоло","name_en"=>"Isiolo","name_href" => "ke/population-of-isiolo","count" => "36 476","real_id" =>29,),
"30"=>array("name_ru"=>"Ламу","name_en"=>"Lama","name_href" => "ke/population-of-lama","count" => "36 213","real_id" =>30,),
"31"=>array("name_ru"=>"Моло","name_en"=>"Molo","name_href" => "ke/population-of-molo","count" => "36 068","real_id" =>31,),
"32"=>array("name_ru"=>"Мачакос","name_en"=>"Machakos","name_href" => "ke/population-of-machakos","count" => "35 882","real_id" =>32,),
"33"=>array("name_ru"=>"Гилгил","name_en"=>"Gilgil","name_href" => "ke/population-of-gilgil","count" => "33 865","real_id" =>33,),
"34"=>array("name_ru"=>"Капсабет","name_en"=>"Kitale","name_href" => "ke/population-of-kitale","count" => "31 201","real_id" =>34,),
"35"=>array("name_ru"=>"Кизий","name_en"=>"City","name_href" => "ke/population-of-city","count" => "31 173","real_id" =>35,),
"36"=>array("name_ru"=>"Киамбу","name_en"=>"Kiambu","name_href" => "ke/population-of-kiambu","count" => "29 723","real_id" =>36,),
"37"=>array("name_ru"=>"Вебуай","name_en"=>"WebUI","name_href" => "ke/population-of-webui","count" => "27 894","real_id" =>37,),
"38"=>array("name_ru"=>"Мавоко","name_en"=>"Mavoko","name_href" => "ke/population-of-mavoko","count" => "27 531","real_id" =>38,),
"39"=>array("name_ru"=>"Вихига","name_en"=>"Vihiga","name_href" => "ke/population-of-vihiga","count" => "27 127","real_id" =>39,),
"40"=>array("name_ru"=>"Маралал","name_en"=>"Maralal","name_href" => "ke/population-of-maralal","count" => "26 384","real_id" =>40,),
"41"=>array("name_ru"=>"Элбургон","name_en"=>"Elburgon","name_href" => "ke/population-of-elburgon","count" => "25 495","real_id" =>41,),
"42"=>array("name_ru"=>"Макуени","name_en"=>"Makueni","name_href" => "ke/population-of-makueni","count" => "23 211","real_id" =>42,),
"43"=>array("name_ru"=>"Лодвар","name_en"=>"Lodwar","name_href" => "ke/population-of-lodwar","count" => "23 103","real_id" =>43,),
"44"=>array("name_ru"=>"Вои","name_en"=>"Voi","name_href" => "ke/population-of-voi","count" => "22 647","real_id" =>44,),
"45"=>array("name_ru"=>"Карури","name_en"=>"Karuri","name_href" => "ke/population-of-karuri","count" => "20 869","real_id" =>45,),
"46"=>array("name_ru"=>"Тана-Ривер","name_en"=>"Tana River","name_href" => "ke/population-of-tana-river","count" => "20 676","real_id" =>46,),
"47"=>array("name_ru"=>"Кутус","name_en"=>"Kutus","name_href" => "ke/population-of-kutus","count" => "19 735","real_id" =>47,),
"48"=>array("name_ru"=>"Китуи","name_en"=>"Kitui","name_href" => "ke/population-of-kitui","count" => "19 685","real_id" =>48,),
"49"=>array("name_ru"=>"Мояле","name_en"=>"Mayola","name_href" => "ke/population-of-mayola","count" => "19 243","real_id" =>49,),
"50"=>array("name_ru"=>"Капенгуриа","name_en"=>"Kapenguria","name_href" => "ke/population-of-kapenguria","count" => "17 638","real_id" =>50,),
"51"=>array("name_ru"=>"Найроби","name_en"=>"Nairobi","name_href" => "ke/population-of-nairobi","count" => "3 476 632","real_id" =>51,),
"52"=>array("name_ru"=>"Момбаса","name_en"=>"Mombasa","name_href" => "ke/population-of-mombasa","count" => "966 413","real_id" =>52,),
"53"=>array("name_ru"=>"Накуру","name_en"=>"Nakuru","name_href" => "ke/population-of-nakuru","count" => "284 840","real_id" =>53,),
"54"=>array("name_ru"=>"Элдорет","name_en"=>"Eldoret","name_href" => "ke/population-of-eldoret","count" => "269 574","real_id" =>54,),
"55"=>array("name_ru"=>"Кисуму","name_en"=>"Kisumu","name_href" => "ke/population-of-kisumu","count" => "236 394","real_id" =>55,)
);

?>