<?php
//Южная Корея 84 
$libkr = array ( 
"1"=>array("name_ru"=>"Сеул","name_en"=>"Seoul","name_href" =>"kr/population-of-seoul","count" =>"10 063 197","real_id" =>1,),
"2"=>array("name_ru"=>"Пусан","name_en"=>"Busan","name_href" =>"kr/population-of-busan","count" =>"3 393 191","real_id" =>2,),
"3"=>array("name_ru"=>"Инчхон","name_en"=>"Incheon","name_href" =>"kr/population-of-incheon","count" =>"2 632 035","real_id" =>3,),
"4"=>array("name_ru"=>"Тэгу","name_en"=>"Daegu","name_href" =>"kr/population-of-daegu","count" =>"2 431 774","real_id" =>4,),
"5"=>array("name_ru"=>"Тэджон","name_en"=>"Daejeon","name_href" =>"kr/population-of-daejeon","count" =>"1 490 158","real_id" =>5,),
"6"=>array("name_ru"=>"Кванджу","name_en"=>"Gwangju","name_href" =>"kr/population-of-gwangju","count" =>"1 466 143","real_id" =>6,),
"7"=>array("name_ru"=>"Ульсан","name_en"=>"Ulsan","name_href" =>"kr/population-of-ulsan","count" =>"1 071 673","real_id" =>7,),
"8"=>array("name_ru"=>"Сувон","name_en"=>"Suwon","name_href" =>"kr/population-of-suwon","count" =>"1 054 053","real_id" =>8,),
"9"=>array("name_ru"=>"Чханвон","name_en"=>"Changwon","name_href" =>"kr/population-of-changwon","count" =>"1 047 488","real_id" =>9,),
"10"=>array("name_ru"=>"Соннам","name_en"=>"Seongnam","name_href" =>"kr/population-of-seongnam","count" =>"936 267","real_id" =>10,),
"11"=>array("name_ru"=>"Коян","name_en"=>"Goyang","name_href" =>"kr/population-of-goyang","count" =>"897 222","real_id" =>11,),
"12"=>array("name_ru"=>"Йонъин","name_en"=>"Yongin","name_href" =>"kr/population-of-yongin","count" =>"847 138","real_id" =>12,),
"13"=>array("name_ru"=>"Пучхон","name_en"=>"Bucheon","name_href" =>"kr/population-of-bucheon","count" =>"842 482","real_id" =>13,),
"14"=>array("name_ru"=>"Ансан","name_en"=>"Ansan","name_href" =>"kr/population-of-ansan","count" =>"699 063","real_id" =>14,),
"15"=>array("name_ru"=>"Чхонджу","name_en"=>"Cheongju","name_href" =>"kr/population-of-cheongju","count" =>"662 102","real_id" =>15,),
"16"=>array("name_ru"=>"Чонджу","name_en"=>"Jeonju","name_href" =>"kr/population-of-jeonju","count" =>"646 512","real_id" =>16,),
"17"=>array("name_ru"=>"Анян","name_en"=>"Anyang","name_href" =>"kr/population-of-anyang","count" =>"596 772","real_id" =>17,),
"18"=>array("name_ru"=>"Чхонан","name_en"=>"Cheonan","name_href" =>"kr/population-of-cheonan","count" =>"565 201","real_id" =>18,),
"19"=>array("name_ru"=>"Намъянджу","name_en"=>"Namyangju","name_href" =>"kr/population-of-namyangju","count" =>"526 639","real_id" =>19,),
"20"=>array("name_ru"=>"Пхохан","name_en"=>"Pohang","name_href" =>"kr/population-of-pohang","count" =>"508 736","real_id" =>20,),
"21"=>array("name_ru"=>"Кимхэ","name_en"=>"Gimhae","name_href" =>"kr/population-of-gimhae","count" =>"484 244","real_id" =>21,),
"22"=>array("name_ru"=>"Хвасон","name_en"=>"Hwaseong","name_href" =>"kr/population-of-hwaseong","count" =>"474 161","real_id" =>22,),
"23"=>array("name_ru"=>"Ыйджонбу","name_en"=>"Uijeongbu","name_href" =>"kr/population-of-uijeongbu","count" =>"415 171","real_id" =>23,),
"24"=>array("name_ru"=>"Куми","name_en"=>"Kumi","name_href" =>"kr/population-of-kumi","count" =>"399 019","real_id" =>24,),
"25"=>array("name_ru"=>"Чеджу","name_en"=>"Jeju","name_href" =>"kr/population-of-jeju","count" =>"398 677","real_id" =>25,),
"26"=>array("name_ru"=>"Сихын","name_en"=>"Siheung","name_href" =>"kr/population-of-siheung","count" =>"393 293","real_id" =>26,),
"27"=>array("name_ru"=>"Пхёнтхэк","name_en"=>"Pyeongtaek","name_href" =>"kr/population-of-pyeongtaek","count" =>"381 731","real_id" =>27,),
"28"=>array("name_ru"=>"Чинджу","name_en"=>"Chinju","name_href" =>"kr/population-of-chinju","count" =>"335 297","real_id" =>28,),
"29"=>array("name_ru"=>"Кванмён","name_en"=>"Gwangmyeong","name_href" =>"kr/population-of-gwangmyeong","count" =>"326 418","real_id" =>29,),
"30"=>array("name_ru"=>"Пхаджу","name_en"=>"Paju","name_href" =>"kr/population-of-paju","count" =>"323 955","real_id" =>30,),
"31"=>array("name_ru"=>"Вонджу","name_en"=>"Wonju","name_href" =>"kr/population-of-wonju","count" =>"309 803","real_id" =>31,),
"32"=>array("name_ru"=>"Иксан","name_en"=>"Iksan","name_href" =>"kr/population-of-iksan","count" =>"294 479","real_id" =>32,),
"33"=>array("name_ru"=>"Чхунчхон","name_en"=>"Chuncheon","name_href" =>"kr/population-of-chuncheon","count" =>"274 221","real_id" =>33,),
"34"=>array("name_ru"=>"Кунпхо","name_en"=>"Gunpo","name_href" =>"kr/population-of-gunpo","count" =>"274 198","real_id" =>34,),
"35"=>array("name_ru"=>"Асан","name_en"=>"Asanas","name_href" =>"kr/population-of-asanas","count" =>"272 282","real_id" =>35,),
"36"=>array("name_ru"=>"Йосу","name_en"=>"Yeosu","name_href" =>"kr/population-of-yeosu","count" =>"268 727","real_id" =>36,),
"37"=>array("name_ru"=>"Кёнсан","name_en"=>"Gyeongsang","name_href" =>"kr/population-of-gyeongsang","count" =>"260 643","real_id" =>37,),
"38"=>array("name_ru"=>"Кунсан","name_en"=>"Gunsan","name_href" =>"kr/population-of-gunsan","count" =>"258 845","real_id" =>38,),
"39"=>array("name_ru"=>"Сунчхон","name_en"=>"Suncheon","name_href" =>"kr/population-of-suncheon","count" =>"257 801","real_id" =>39,),
"40"=>array("name_ru"=>"Кёнджу","name_en"=>"Gyeongju","name_href" =>"kr/population-of-gyeongju","count" =>"252 751","real_id" =>40,),
"41"=>array("name_ru"=>"Янсан","name_en"=>"Yangsan","name_href" =>"kr/population-of-yangsan","count" =>"249 529","real_id" =>41,),
"42"=>array("name_ru"=>"Мокпхо","name_en"=>"Mokpo","name_href" =>"kr/population-of-mokpo","count" =>"248 694","real_id" =>42,),
"43"=>array("name_ru"=>"Кодже","name_en"=>"Kyosai","name_href" =>"kr/population-of-kyosai","count" =>"225 014","real_id" =>43,),
"44"=>array("name_ru"=>"Кванджу","name_en"=>"Gwangju","name_href" =>"kr/population-of-gwangju","count" =>"224 269","real_id" =>44,),
"45"=>array("name_ru"=>"Каннын","name_en"=>"Gangneung","name_href" =>"kr/population-of-gangneung","count" =>"217 481","real_id" =>45,),
"46"=>array("name_ru"=>"Кимпхо","name_en"=>"Gimpo","name_href" =>"kr/population-of-gimpo","count" =>"217 281","real_id" =>46,),
"47"=>array("name_ru"=>"Чхунджу","name_en"=>"Chungju","name_href" =>"kr/population-of-chungju","count" =>"201 361","real_id" =>47,),
"48"=>array("name_ru"=>"Ичхон","name_en"=>"Icheon","name_href" =>"kr/population-of-icheon","count" =>"192 918","real_id" =>48,),
"49"=>array("name_ru"=>"Кури","name_en"=>"Khoury","name_href" =>"kr/population-of-khoury","count" =>"184 503","real_id" =>49,),
"50"=>array("name_ru"=>"Янджу","name_en"=>"Yangju","name_href" =>"kr/population-of-yangju","count" =>"183 673","real_id" =>50,),
"51"=>array("name_ru"=>"Осан","name_en"=>"Osan","name_href" =>"kr/population-of-osan","count" =>"180 996","real_id" =>51,),
"52"=>array("name_ru"=>"Ансон","name_en"=>"Anson","name_href" =>"kr/population-of-anson","count" =>"175 824","real_id" =>52,),
"53"=>array("name_ru"=>"Чинхэ","name_en"=>"Jinhae","name_href" =>"kr/population-of-jinhae","count" =>"171 407","real_id" =>53,),
"54"=>array("name_ru"=>"Андон","name_en"=>"Andong","name_href" =>"kr/population-of-andong","count" =>"165 399","real_id" =>54,),
"55"=>array("name_ru"=>"Сосан","name_en"=>"Seosan","name_href" =>"kr/population-of-seosan","count" =>"155 082","real_id" =>55,),
"56"=>array("name_ru"=>"Танджин","name_en"=>"Dangjin","name_href" =>"kr/population-of-dangjin","count" =>"149 469","real_id" =>56,),
"57"=>array("name_ru"=>"Ыйван","name_en"=>"Uiwang","name_href" =>"kr/population-of-uiwang","count" =>"143 378","real_id" =>57,),
"58"=>array("name_ru"=>"Ханам","name_en"=>"Khans","name_href" =>"kr/population-of-khans","count" =>"137 569","real_id" =>58,),
"59"=>array("name_ru"=>"Кванъян","name_en"=>"Gwangyang","name_href" =>"kr/population-of-gwangyang","count" =>"137 101","real_id" =>59,),
"60"=>array("name_ru"=>"Пхочхон","name_en"=>"Pocheon","name_href" =>"kr/population-of-pocheon","count" =>"136 581","real_id" =>60,),
"61"=>array("name_ru"=>"Чечхонгн","name_en"=>"Chechen","name_href" =>"kr/population-of-chechen","count" =>"133 626","real_id" =>61,),
"62"=>array("name_ru"=>"Согвипхо","name_en"=>"Seogwipo","name_href" =>"kr/population-of-seogwipo","count" =>"129 734","real_id" =>62,),
"63"=>array("name_ru"=>"Тхонъён","name_en"=>"Tongyeong","name_href" =>"kr/population-of-tongyeong","count" =>"127 896","real_id" =>63,),
"64"=>array("name_ru"=>"Кимчхон","name_en"=>"Gimcheon","name_href" =>"kr/population-of-gimcheon","count" =>"126 823","real_id" =>64,),
"65"=>array("name_ru"=>"Конджу","name_en"=>"Kongju","name_href" =>"kr/population-of-kongju","count" =>"120 661","real_id" =>65,),
"66"=>array("name_ru"=>"Нонсан","name_en"=>"Nonsan","name_href" =>"kr/population-of-nonsan","count" =>"117 686","real_id" =>66,),
"67"=>array("name_ru"=>"Чонып","name_en"=>"Jeongeup","name_href" =>"kr/population-of-jeongeup","count" =>"109 458","real_id" =>67,),
"68"=>array("name_ru"=>"Йонджу","name_en"=>"Yeongju","name_href" =>"kr/population-of-yeongju","count" =>"108 268","real_id" =>68,),
"69"=>array("name_ru"=>"Сачхон","name_en"=>"Sacheon","name_href" =>"kr/population-of-sacheon","count" =>"106 175","real_id" =>69,),
"70"=>array("name_ru"=>"Мирян","name_en"=>"Laity","name_href" =>"kr/population-of-laity","count" =>"98 564","real_id" =>70,),
"71"=>array("name_ru"=>"Санджу","name_en"=>"Sanju","name_href" =>"kr/population-of-sanju","count" =>"97 559","real_id" =>71,),
"72"=>array("name_ru"=>"Порён","name_en"=>"Boryeong","name_href" =>"kr/population-of-boryeong","count" =>"97 091","real_id" =>72,),
"73"=>array("name_ru"=>"Йончхон","name_en"=>"Yeongcheon","name_href" =>"kr/population-of-yeongcheon","count" =>"94 351","real_id" =>73,),
"74"=>array("name_ru"=>"Тондучхон","name_en"=>"Dongducheon","name_href" =>"kr/population-of-dongducheon","count" =>"90 433","real_id" =>74,),
"75"=>array("name_ru"=>"Тонхэ","name_en"=>"Donghae","name_href" =>"kr/population-of-donghae","count" =>"90 321","real_id" =>75,),
"76"=>array("name_ru"=>"Кимдже","name_en"=>"Gimje","name_href" =>"kr/population-of-gimje","count" =>"82 739","real_id" =>76,),
"77"=>array("name_ru"=>"Сокчхо","name_en"=>"Sokcho","name_href" =>"kr/population-of-sokcho","count" =>"80 505","real_id" =>77,),
"78"=>array("name_ru"=>"Намвон","name_en"=>"Namwon","name_href" =>"kr/population-of-namwon","count" =>"78 425","real_id" =>78,),
"79"=>array("name_ru"=>"Наджу","name_en"=>"Naju","name_href" =>"kr/population-of-naju","count" =>"77 825","real_id" =>79,),
"80"=>array("name_ru"=>"Мунгён","name_en"=>"Mungyeong","name_href" =>"kr/population-of-mungyeong","count" =>"68 692","real_id" =>80,),
"81"=>array("name_ru"=>"Самчхок","name_en"=>"Samcheok","name_href" =>"kr/population-of-samcheok","count" =>"67 131","real_id" =>81,),
"82"=>array("name_ru"=>"Квачхон","name_en"=>"Gwacheon","name_href" =>"kr/population-of-gwacheon","count" =>"66 319","real_id" =>82,),
"83"=>array("name_ru"=>"Тхэбэк","name_en"=>"Taebaek","name_href" =>"kr/population-of-taebaek","count" =>"51 412","real_id" =>83,),
"84"=>array("name_ru"=>"Керён","name_en"=>"Keren","name_href" =>"kr/population-of-keren","count" =>"41 395","real_id" =>84,),
"85"=>array("name_ru"=>"Сеул","name_en"=>"Seoul","name_href" =>"kr/population-of-seoul","count" =>"10 063 197","real_id" =>85,),
"86"=>array("name_ru"=>"Пусан","name_en"=>"Busan","name_href" =>"kr/population-of-busan","count" =>"3 393 191","real_id" =>86,),
"87"=>array("name_ru"=>"Инчхон","name_en"=>"Incheon","name_href" =>"kr/population-of-incheon","count" =>"2 632 035","real_id" =>87,),
"88"=>array("name_ru"=>"Тэгу","name_en"=>"Daegu","name_href" =>"kr/population-of-daegu","count" =>"2 431 774","real_id" =>88,),
"89"=>array("name_ru"=>"Тэджон","name_en"=>"Daejeon","name_href" =>"kr/population-of-daejeon","count" =>"1 490 158","real_id" =>89,)
);

?>