<?php
//Литва 103
$liblt = array (


"1"=>array("name_ru"=>"Вильнюс","name_en"=>"Vilnius","name_href" => "lt/population-of-vilnius","count" => "539 939","real_id" =>1,),
"2"=>array("name_ru"=>"Каунас","name_en"=>"Kaunas","name_href" => "lt/population-of-kaunas","count" => "297 669","real_id" =>2,),
"3"=>array("name_ru"=>"Клайпеда","name_en"=>"Klaipeda","name_href" => "lt/population-of-klaipeda","count" => "157 350","real_id" =>3,),
"4"=>array("name_ru"=>"Шяуляй","name_en"=>"Šiauliai","name_href" => "lt/population-of-šiauliai","count" => "107 875","real_id" =>4,),
"5"=>array("name_ru"=>"Панявежис","name_en"=>"Panevezys","name_href" => "lt/population-of-panevezys","count" => "97 343","real_id" =>5,),
"6"=>array("name_ru"=>"Алитус","name_en"=>"Alytus","name_href" => "lt/population-of-alytus","count" => "57 281","real_id" =>6,),
"7"=>array("name_ru"=>"Мариямполе","name_en"=>"Marijampolė","name_href" => "lt/population-of-marijampolė","count" => "44 910","real_id" =>7,),
"8"=>array("name_ru"=>"Мажейкяй","name_en"=>"Mažeikiai","name_href" => "lt/population-of-mažeikiai","count" => "40 172","real_id" =>8,),
"9"=>array("name_ru"=>"Йонава","name_en"=>"Jonava","name_href" => "lt/population-of-jonava","count" => "34 056","real_id" =>9,),
"10"=>array("name_ru"=>"Тельшяй","name_en"=>"Telšiai","name_href" => "lt/population-of-telšiai","count" => "29 119","real_id" =>10,),
"11"=>array("name_ru"=>"Утяна","name_en"=>"Utena","name_href" => "lt/population-of-utena","count" => "28 391","real_id" =>11,),
"12"=>array("name_ru"=>"Укмярге","name_en"=>"Ukmerge","name_href" => "lt/population-of-ukmerge","count" => "26 974","real_id" =>12,),
"13"=>array("name_ru"=>"Таураге","name_en"=>"Taurage","name_href" => "lt/population-of-taurage","count" => "26 444","real_id" =>13,),
"14"=>array("name_ru"=>"Кедайняй","name_en"=>"Kėdainiai","name_href" => "lt/population-of-kėdainiai","count" => "25 654","real_id" =>14,),
"15"=>array("name_ru"=>"Плунге","name_en"=>"Plungė","name_href" => "lt/population-of-plungė","count" => "22 832","real_id" =>15,),
"16"=>array("name_ru"=>"Крятинга","name_en"=>"Creating","name_href" => "lt/population-of-creating","count" => "20 962","real_id" =>16,),
"17"=>array("name_ru"=>"Шилуте","name_en"=>"Silute","name_href" => "lt/population-of-silute","count" => "20 809","real_id" =>17,),
"18"=>array("name_ru"=>"Висагинас","name_en"=>"Visaginas","name_href" => "lt/population-of-visaginas","count" => "19 632","real_id" =>18,),
"19"=>array("name_ru"=>"Радвилишкис","name_en"=>"Radviliškis","name_href" => "lt/population-of-radviliškis","count" => "18 816","real_id" =>19,),
"20"=>array("name_ru"=>"Гаргждай","name_en"=>"Gargždai","name_href" => "lt/population-of-gargždai","count" => "16 433","real_id" =>20,),
"21"=>array("name_ru"=>"Друскининкай","name_en"=>"Druskininkai","name_href" => "lt/population-of-druskininkai","count" => "16 107","real_id" =>21,),
"22"=>array("name_ru"=>"Паланга","name_en"=>"Palanga","name_href" => "lt/population-of-palanga","count" => "15 732","real_id" =>22,),
"23"=>array("name_ru"=>"Рокишкис","name_en"=>"Rokiskis","name_href" => "lt/population-of-rokiskis","count" => "15 325","real_id" =>23,),
"24"=>array("name_ru"=>"Биржай","name_en"=>"Birzai","name_href" => "lt/population-of-birzai","count" => "13 762","real_id" =>24,),
"25"=>array("name_ru"=>"Гарлява","name_en"=>"Garliava","name_href" => "lt/population-of-garliava","count" => "13 368","real_id" =>25,),
"26"=>array("name_ru"=>"Куршенай","name_en"=>"Kursenai","name_href" => "lt/population-of-kursenai","count" => "13 057","real_id" =>26,),
"27"=>array("name_ru"=>"Юрбаркас","name_en"=>"Jurbarkas","name_href" => "lt/population-of-jurbarkas","count" => "12 972","real_id" =>27,),
"28"=>array("name_ru"=>"Расейняй","name_en"=>"Raseiniai","name_href" => "lt/population-of-raseiniai","count" => "11 824","real_id" =>28,),
"29"=>array("name_ru"=>"Лянтварис","name_en"=>"Lentvaris","name_href" => "lt/population-of-lentvaris","count" => "11 408","real_id" =>29,),
"30"=>array("name_ru"=>"Аникщяй","name_en"=>"Anykščiai","name_href" => "lt/population-of-anykščiai","count" => "11 391","real_id" =>30,),
"31"=>array("name_ru"=>"Вилкавишкис","name_en"=>"Vilkaviskis","name_href" => "lt/population-of-vilkaviskis","count" => "11 177","real_id" =>31,),
"32"=>array("name_ru"=>"Григишкес","name_en"=>"Grigiskes","name_href" => "lt/population-of-grigiskes","count" => "11 128","real_id" =>32,),
"33"=>array("name_ru"=>"Пренай","name_en"=>"Prienai","name_href" => "lt/population-of-prienai","count" => "10 719","real_id" =>33,),
"34"=>array("name_ru"=>"Варена","name_en"=>"Varena","name_href" => "lt/population-of-varena","count" => "10 106","real_id" =>34,),
"35"=>array("name_ru"=>"Йонишкис","name_en"=>"Joniškis","name_href" => "lt/population-of-joniškis","count" => "9 899","real_id" =>35,),
"36"=>array("name_ru"=>"Кяльме","name_en"=>"Kelmė","name_href" => "lt/population-of-kelmė","count" => "9 876","real_id" =>36,),
"37"=>array("name_ru"=>"Кайшядорис","name_en"=>"Kaisiadorys","name_href" => "lt/population-of-kaisiadorys","count" => "9 524","real_id" =>37,),
"38"=>array("name_ru"=>"Науйойи-Акмяне","name_en"=>"Naujoji Akmene","name_href" => "lt/population-of-naujoji-akmene","count" => "9 300","real_id" =>38,),
"39"=>array("name_ru"=>"Купишкис","name_en"=>"Kupiškis","name_href" => "lt/population-of-kupiškis","count" => "7 918","real_id" =>39,),
"40"=>array("name_ru"=>"Пасвалис","name_en"=>"Pasvalys","name_href" => "lt/population-of-pasvalys","count" => "7 077","real_id" =>40,),
"41"=>array("name_ru"=>"Скуодас","name_en"=>"Skuodas","name_href" => "lt/population-of-skuodas","count" => "7 036","real_id" =>41,),
"42"=>array("name_ru"=>"Зарасай","name_en"=>"Zarasai","name_href" => "lt/population-of-zarasai","count" => "6 966","real_id" =>42,),
"43"=>array("name_ru"=>"Молетай","name_en"=>"Molėtai","name_href" => "lt/population-of-molėtai","count" => "6 831","real_id" =>43,),
"44"=>array("name_ru"=>"Ширвинтос","name_en"=>"Sirvintos","name_href" => "lt/population-of-sirvintos","count" => "6 790","real_id" =>44,),
"45"=>array("name_ru"=>"Казлу Руда","name_en"=>"Kazlu Ruda","name_href" => "lt/population-of-kazlu-ruda","count" => "6 635","real_id" =>45,),
"46"=>array("name_ru"=>"Шальчининкай","name_en"=>"Šalčininkai","name_href" => "lt/population-of-šalčininkai","count" => "6 491","real_id" =>46,),
"47"=>array("name_ru"=>"Шакяй","name_en"=>"Sakiai","name_href" => "lt/population-of-sakiai","count" => "6 377","real_id" =>47,),
"48"=>array("name_ru"=>"Кибартай","name_en"=>"Kybartai","name_href" => "lt/population-of-kybartai","count" => "6 173","real_id" =>48,),
"49"=>array("name_ru"=>"Швенчёнеляй","name_en"=>"Svencioneliai","name_href" => "lt/population-of-svencioneliai","count" => "6 162","real_id" =>49,),
"50"=>array("name_ru"=>"Пабраде","name_en"=>"Pabrade","name_href" => "lt/population-of-pabrade","count" => "6 121","real_id" =>50,),
"51"=>array("name_ru"=>"Нямянчине","name_en"=>"Nemencine","name_href" => "lt/population-of-nemencine","count" => "5 816","real_id" =>51,),
"52"=>array("name_ru"=>"Игналина","name_en"=>"Ignalina","name_href" => "lt/population-of-ignalina","count" => "5 635","real_id" =>52,),
"53"=>array("name_ru"=>"Пакруойис","name_en"=>"Pakruojis","name_href" => "lt/population-of-pakruojis","count" => "5 628","real_id" =>53,),
"54"=>array("name_ru"=>"Швянчёнис","name_en"=>"Shvenchenis","name_href" => "lt/population-of-shvenchenis","count" => "5 512","real_id" =>54,),
"55"=>array("name_ru"=>"Шилале","name_en"=>"Silale","name_href" => "lt/population-of-silale","count" => "5 459","real_id" =>55,),
"56"=>array("name_ru"=>"Тракай","name_en"=>"Trakai","name_href" => "lt/population-of-trakai","count" => "4 933","real_id" =>56,),
"57"=>array("name_ru"=>"Вевис","name_en"=>"Vievis","name_href" => "lt/population-of-vievis","count" => "4 915","real_id" =>57,),
"58"=>array("name_ru"=>"Калвария","name_en"=>"Kalvarija","name_href" => "lt/population-of-kalvarija","count" => "4 888","real_id" =>58,),
"59"=>array("name_ru"=>"Лаздияй","name_en"=>"Lazdijai","name_href" => "lt/population-of-lazdijai","count" => "4 793","real_id" =>59,),
"60"=>array("name_ru"=>"Ретавас","name_en"=>"Rietavas","name_href" => "lt/population-of-rietavas","count" => "3 799","real_id" =>60,),
"61"=>array("name_ru"=>"Жежмаряй","name_en"=>"Between žiežmariai","name_href" => "lt/population-of-between-žiežmariai","count" => "3 698","real_id" =>61,),
"62"=>array("name_ru"=>"Няринга","name_en"=>"Neringa","name_href" => "lt/population-of-neringa","count" => "3 682","real_id" =>62,),
"63"=>array("name_ru"=>"Эйшишкес","name_en"=>"Eišiškės","name_href" => "lt/population-of-eišiškės","count" => "3 575","real_id" =>63,),
"64"=>array("name_ru"=>"Арёгала","name_en"=>"Ariogala","name_href" => "lt/population-of-ariogala","count" => "3 332","real_id" =>64,),
"65"=>array("name_ru"=>"Шядува","name_en"=>"Sadowa","name_href" => "lt/population-of-sadowa","count" => "3 115","real_id" =>65,),
"66"=>array("name_ru"=>"Вянта","name_en"=>"Venta","name_href" => "lt/population-of-venta","count" => "2 867","real_id" =>66,),
"67"=>array("name_ru"=>"Титувенай","name_en"=>"Tytuvėnėliai","name_href" => "lt/population-of-tytuvėnėliai","count" => "2 614","real_id" =>67,),
"68"=>array("name_ru"=>"Бирштонас","name_en"=>"Birštonas","name_href" => "lt/population-of-birštonas","count" => "2 554","real_id" =>68,),
"69"=>array("name_ru"=>"Акмяне","name_en"=>"Akmenė","name_href" => "lt/population-of-akmenė","count" => "2 493","real_id" =>69,),
"70"=>array("name_ru"=>"Рудишкес","name_en"=>"Rūdiškės","name_href" => "lt/population-of-rūdiškės","count" => "2 414","real_id" =>70,),
"71"=>array("name_ru"=>"Вилькия","name_en"=>"Wilkie","name_href" => "lt/population-of-wilkie","count" => "2 232","real_id" =>71,),
"72"=>array("name_ru"=>"Векшняй","name_en"=>"Vekshnyay","name_href" => "lt/population-of-vekshnyay","count" => "2 183","real_id" =>72,),
"73"=>array("name_ru"=>"Пагегяй","name_en"=>"Pagėgiai","name_href" => "lt/population-of-pagėgiai","count" => "2 143","real_id" =>73,),
"74"=>array("name_ru"=>"Жагаре","name_en"=>"Zagare","name_href" => "lt/population-of-zagare","count" => "2 065","real_id" =>74,),
"75"=>array("name_ru"=>"Эжярелис","name_en"=>"Ezerelis","name_href" => "lt/population-of-ezerelis","count" => "1 959","real_id" =>75,),
"76"=>array("name_ru"=>"Кудиркос Науместис","name_en"=>"Kudirkos Naumiestis","name_href" => "lt/population-of-kudirkos-naumiestis","count" => "1 911","real_id" =>76,),
"77"=>array("name_ru"=>"Скаудвиле","name_en"=>"Skeldon","name_href" => "lt/population-of-skeldon","count" => "1 884","real_id" =>77,),
"78"=>array("name_ru"=>"Гялгаудушкис","name_en"=>"Gelgaudiskis","name_href" => "lt/population-of-gelgaudiskis","count" => "1 879","real_id" =>78,),
"79"=>array("name_ru"=>"Салантай","name_en"=>"Salantai","name_href" => "lt/population-of-salantai","count" => "1 767","real_id" =>79,),
"80"=>array("name_ru"=>"Симнас","name_en"=>"Simnas","name_href" => "lt/population-of-simnas","count" => "1 736","real_id" =>80,),
"81"=>array("name_ru"=>"Линкува","name_en"=>"Linkuva","name_href" => "lt/population-of-linkuva","count" => "1 731","real_id" =>81,),
"82"=>array("name_ru"=>"Прекуле","name_en"=>"Priekulė","name_href" => "lt/population-of-priekulė","count" => "1 644","real_id" =>82,),
"83"=>array("name_ru"=>"Рамигала","name_en"=>"Ramygala","name_href" => "lt/population-of-ramygala","count" => "1 581","real_id" =>83,),
"84"=>array("name_ru"=>"Вейсеяй","name_en"=>"Veisiejai","name_href" => "lt/population-of-veisiejai","count" => "1 546","real_id" =>84,),
"85"=>array("name_ru"=>"Даугай","name_en"=>"Daugai","name_href" => "lt/population-of-daugai","count" => "1 396","real_id" =>85,),
"86"=>array("name_ru"=>"Езнас","name_en"=>"Jieznas","name_href" => "lt/population-of-jieznas","count" => "1 261","real_id" =>86,),
"87"=>array("name_ru"=>"Вирбалис","name_en"=>"Virbalis","name_href" => "lt/population-of-virbalis","count" => "1 205","real_id" =>87,),
"88"=>array("name_ru"=>"Йонишкелис","name_en"=>"Joniskelis","name_href" => "lt/population-of-joniskelis","count" => "1 201","real_id" =>88,),
"89"=>array("name_ru"=>"Варняй","name_en"=>"Region","name_href" => "lt/population-of-region","count" => "1 178","real_id" =>89,),
"90"=>array("name_ru"=>"Сяда","name_en"=>"Saga","name_href" => "lt/population-of-saga","count" => "1 161","real_id" =>90,),
"91"=>array("name_ru"=>"Вабальнинкас","name_en"=>"Vabalninkas","name_href" => "lt/population-of-vabalninkas","count" => "1 086","real_id" =>91,),
"92"=>array("name_ru"=>"Обяляй","name_en"=>"Obeliai","name_href" => "lt/population-of-obeliai","count" => "1 074","real_id" =>92,),
"93"=>array("name_ru"=>"Субачюс","name_en"=>"Abacus","name_href" => "lt/population-of-abacus","count" => "1 068","real_id" =>93,),
"94"=>array("name_ru"=>"Балтойи-Воке","name_en"=>"Baltoyi-Wok","name_href" => "lt/population-of-baltoyi-wok","count" => "1 058","real_id" =>94,),
"95"=>array("name_ru"=>"Панделис","name_en"=>"Pandelys","name_href" => "lt/population-of-pandelys","count" => "921","real_id" =>95,),
"96"=>array("name_ru"=>"Дукштас","name_en"=>"Dūkštas","name_href" => "lt/population-of-dūkštas","count" => "888","real_id" =>96,),
"97"=>array("name_ru"=>"Ужвянтис","name_en"=>"Uzventis","name_href" => "lt/population-of-uzventis","count" => "811","real_id" =>97,),
"98"=>array("name_ru"=>"Дусятос","name_en"=>"Dusetos","name_href" => "lt/population-of-dusetos","count" => "794","real_id" =>98,),
"99"=>array("name_ru"=>"Каварскас","name_en"=>"Kavarskas","name_href" => "lt/population-of-kavarskas","count" => "678","real_id" =>99,),
"100"=>array("name_ru"=>"Эляктренай","name_en"=>"Elektrenai","name_href" => "lt/population-of-elektrenai","count" => "651","real_id" =>100,),
"101"=>array("name_ru"=>"Смалининкай","name_en"=>"Smalininkai","name_href" => "lt/population-of-smalininkai","count" => "601","real_id" =>101,),
"102"=>array("name_ru"=>"Трошкунай","name_en"=>"Troškūnai","name_href" => "lt/population-of-troskunai","count" => "486","real_id" =>102,),
"103"=>array("name_ru"=>"Панямуне","name_en"=>"Panemune","name_href" => "lt/population-of-panemune","count" => "294","real_id" =>103,),
"104"=>array("name_ru"=>"Вильнюс","name_en"=>"Vilnius","name_href" => "lt/population-of-vilnius","count" => "539 939","real_id" =>104,),
"105"=>array("name_ru"=>"Каунас","name_en"=>"Kaunas","name_href" => "lt/population-of-kaunas","count" => "297 669","real_id" =>105,),
"106"=>array("name_ru"=>"Клайпеда","name_en"=>"Klaipeda","name_href" => "lt/population-of-klaipeda","count" => "157 350","real_id" =>106,),
"107"=>array("name_ru"=>"Шяуляй","name_en"=>"Šiauliai","name_href" => "lt/population-of-šiauliai","count" => "107 875","real_id" =>107,),
"108"=>array("name_ru"=>"Панявежис","name_en"=>"Panevezys","name_href" => "lt/population-of-panevezys","count" => "97 343","real_id" =>108,)


);

?>