<?php
//Шри Ланка 41 
$liblk = array ( 
"1"=>array("name_ru"=>"Коломбо","name_en"=>"Colombo","name_href" => "lk/population-of-colombo","count" => "685 246","real_id" =>1,),
"2"=>array("name_ru"=>"Дехивала-Маунт-Лавиния","name_en"=>"Dehiwala-Mount Lavinia","name_href" => "lk/population-of-dehiwala-mount-lavinia","count" => "234 559","real_id" =>2,),
"3"=>array("name_ru"=>"Моратува","name_en"=>"Moratuwa","name_href" => "lk/population-of-moratuwa","count" => "204 849","real_id" =>3,),
"4"=>array("name_ru"=>"Джафна","name_en"=>"Jaffna","name_href" => "lk/population-of-jaffna","count" => "184 416","real_id" =>4,),
"5"=>array("name_ru"=>"Негомбо","name_en"=>"Negombo","name_href" => "lk/population-of-negombo","count" => "144 995","real_id" =>5,),
"6"=>array("name_ru"=>"Шри-Джаяварденепура-Котте","name_en"=>"Sri Jayawardenepura Kotte","name_href" => "lk/population-of-sri-jayawardenepura-kotte","count" => "119364","real_id" =>6,),
"7"=>array("name_ru"=>"Тринкомали","name_en"=>"Trincomalee","name_href" => "lk/population-of-trincomalee","count" => "126 902","real_id" =>7,),
"8"=>array("name_ru"=>"Канди","name_en"=>"Kandy","name_href" => "lk/population-of-kandy","count" => "120 087","real_id" =>8,),
"9"=>array("name_ru"=>"Вавуния","name_en"=>"Vavuniya","name_href" => "lk/population-of-vavuniya","count" => "108 834","real_id" =>9,),
"10"=>array("name_ru"=>"Калмунай","name_en"=>"Kalmunai","name_href" => "lk/population-of-kalmunai","count" => "104 985","real_id" =>10,),
"11"=>array("name_ru"=>"Галле","name_en"=>"Halle","name_href" => "lk/population-of-halle","count" => "97 807","real_id" =>11,),
"12"=>array("name_ru"=>"Баттикалоа","name_en"=>"Batticaloa","name_href" => "lk/population-of-batticaloa","count" => "97 648","real_id" =>12,),
"13"=>array("name_ru"=>"Катунаяка","name_en"=>"Katunayaka","name_href" => "lk/population-of-katunayaka","count" => "92 469","real_id" =>13,),
"14"=>array("name_ru"=>"Вальветтитурай","name_en"=>"Valvettituray","name_href" => "lk/population-of-valvettituray","count" => "86 305","real_id" =>14,),
"15"=>array("name_ru"=>"Баттарамулла","name_en"=>"Battaramulla","name_href" => "lk/population-of-battaramulla","count" => "85 348","real_id" =>15,),
"16"=>array("name_ru"=>"Дамбулла","name_en"=>"Dambulla","name_href" => "lk/population-of-dambulla","count" => "77 148","real_id" =>16,),
"17"=>array("name_ru"=>"Махарагама","name_en"=>"Maharagama","name_href" => "lk/population-of-maharagama","count" => "75 127","real_id" =>17,),
"18"=>array("name_ru"=>"Далугума","name_en"=>"Daluguma","name_href" => "lk/population-of-daluguma","count" => "74 428","real_id" =>18,),
"19"=>array("name_ru"=>"Котикаватта","name_en"=>"Kotikavatta","name_href" => "lk/population-of-kotikavatta","count" => "72 858","real_id" =>19,),
"20"=>array("name_ru"=>"Анурадхапура","name_en"=>"Anuradhapura","name_href" => "lk/population-of-anuradhapura","count" => "68 244","real_id" =>20,),
"21"=>array("name_ru"=>"Колоннава","name_en"=>"Kolonnava","name_href" => "lk/population-of-kolonnava","count" => "64 707","real_id" =>21,),
"22"=>array("name_ru"=>"Хендала","name_en"=>"Hyundai","name_href" => "lk/population-of-hyundai","count" => "57 591","real_id" =>22,),
"23"=>array("name_ru"=>"Ратнапура","name_en"=>"Ratnapura","name_href" => "lk/population-of-ratnapura","count" => "51 230","real_id" =>23,),
"24"=>array("name_ru"=>"Путталам ","name_en"=>"Puttalam","name_href" => "lk/population-of-puttalam","count" => "50 615","real_id" =>24,),
"25"=>array("name_ru"=>"Бадулла","name_en"=>"Badulla","name_href" => "lk/population-of-badulla","count" => "47 288","real_id" =>25,),
"26"=>array("name_ru"=>"Кеселватта","name_en"=>"Keselvatta","name_href" => "lk/population-of-keselvatta","count" => "46 129","real_id" =>26,),
"27"=>array("name_ru"=>"Матара","name_en"=>"Matara","name_href" => "lk/population-of-matara","count" => "45 684","real_id" =>27,),
"28"=>array("name_ru"=>"Велисара","name_en"=>"Belisarius","name_href" => "lk/population-of-belisarius","count" => "41 750","real_id" =>28,),
"29"=>array("name_ru"=>"Матале","name_en"=>"Matale","name_href" => "lk/population-of-matale","count" => "40 247","real_id" =>29,),
"30"=>array("name_ru"=>"Хомагама","name_en"=>"Homagama","name_href" => "lk/population-of-homagama","count" => "39 116","real_id" =>30,),
"31"=>array("name_ru"=>"Каттанкуди","name_en"=>"Kattankudi","name_href" => "lk/population-of-kattankudi","count" => "38 837","real_id" =>31,),
"32"=>array("name_ru"=>"Калутара","name_en"=>"Kalutara","name_href" => "lk/population-of-kalutara","count" => "38 342","real_id" =>32,),
"33"=>array("name_ru"=>"Муллериява","name_en"=>"Mulleriyawa","name_href" => "lk/population-of-mulleriyawa","count" => "37 848","real_id" =>33,),
"34"=>array("name_ru"=>"Маннар","name_en"=>"Mannar","name_href" => "lk/population-of-mannar","count" => "36 442","real_id" =>34,),
"35"=>array("name_ru"=>"Берувала","name_en"=>"Beruwala","name_href" => "lk/population-of-beruwala","count" => "35 068","real_id" =>35,),
"36"=>array("name_ru"=>"Рагама","name_en"=>"Ragama","name_href" => "lk/population-of-ragama","count" => "34 682","real_id" =>36,),
"37"=>array("name_ru"=>"Кандана","name_en"=>"Candau","name_href" => "lk/population-of-candau","count" => "33 784","real_id" =>37,),
"38"=>array("name_ru"=>"Панадура","name_en"=>"Panadura","name_href" => "lk/population-of-panadura","count" => "33 879","real_id" =>38,),
"39"=>array("name_ru"=>"Джаэла","name_en"=>"Dzhaela","name_href" => "lk/population-of-dzhaela","count" => "30 654","real_id" =>39,),
"40"=>array("name_ru"=>"Ваттала","name_en"=>"Wattala","name_href" => "lk/population-of-wattala","count" => "30 168","real_id" =>40,),
"41"=>array("name_ru"=>"Пелиягода","name_en"=>"Peliyagoda","name_href" => "lk/population-of-peliyagoda","count" => "28 784","real_id" =>41,),
"42"=>array("name_ru"=>"Коломбо","name_en"=>"Colombo","name_href" => "lk/population-of-colombo","count" => "685 246","real_id" =>42,),
"43"=>array("name_ru"=>"Дехивала-Маунт-Лавиния","name_en"=>"Dehiwala-Mount Lavinia","name_href" => "lk/population-of-dehiwala-mount-lavinia","count" => "234 559","real_id" =>43,),
"44"=>array("name_ru"=>"Моратува","name_en"=>"Moratuwa","name_href" => "lk/population-of-moratuwa","count" => "204 849","real_id" =>44,),
"45"=>array("name_ru"=>"Джафна","name_en"=>"Jaffna","name_href" => "lk/population-of-jaffna","count" => "184 416","real_id" =>45,),
"46"=>array("name_ru"=>"Негомбо","name_en"=>"Negombo","name_href" => "lk/population-of-negombo","count" => "144 995","real_id" =>46,)
);

?>