<?php
//Латвия 55
$liblv = array (
"1"=>array("name_ru"=>"Лудза","name_en"=>"Ludza","name_href" =>"lv/population-of-ludza","count" =>"8 300","real_id" =>1,),
"2"=>array("name_ru"=>"Гулбене","name_en"=>"Gulbene","name_href" =>"lv/population-of-gulbene","count" =>"7 843","real_id" =>2,),
"3"=>array("name_ru"=>"Мадона","name_en"=>"Madona","name_href" =>"lv/population-of-madona","count" =>"7 515","real_id" =>3,),
"4"=>array("name_ru"=>"Ливаны","name_en"=>"Livani","name_href" =>"lv/population-of-livani","count" =>"7 511","real_id" =>4,),
"5"=>array("name_ru"=>"Лимбажи","name_en"=>"Limbazi","name_href" =>"lv/population-of-limbazi","count" =>"7 470","real_id" =>5,),
"6"=>array("name_ru"=>"Айзкраукле","name_en"=>"Aizkraukle","name_href" =>"lv/population-of-aizkraukle","count" =>"7 315","real_id" =>6,),
"7"=>array("name_ru"=>"Алуксне","name_en"=>"Alūksne","name_href" =>"lv/population-of-alūksne","count" =>"7 295","real_id" =>7,),
"8"=>array("name_ru"=>"Прейли","name_en"=>"Preiļi","name_href" =>"lv/population-of-preiļi","count" =>"6 729","real_id" =>8,),
"9"=>array("name_ru"=>"Балвы","name_en"=>"Balvi","name_href" =>"lv/population-of-balvi","count" =>"6 659","real_id" =>9,),
"10"=>array("name_ru"=>"Икшкиле","name_en"=>"Ikšķile","name_href" =>"lv/population-of-ikšķile","count" =>"6 508","real_id" =>10,),
"11"=>array("name_ru"=>"Баложи","name_en"=>"Baloži","name_href" =>"lv/population-of-baloži","count" =>"6 246","real_id" =>11,),
"12"=>array("name_ru"=>"Лиелварде","name_en"=>"Lielvarde","name_href" =>"lv/population-of-lielvarde","count" =>"6 089","real_id" =>12,),
"13"=>array("name_ru"=>"Смилтене","name_en"=>"Smiltene","name_href" =>"lv/population-of-smiltene","count" =>"5 416","real_id" =>13,),
"14"=>array("name_ru"=>"Валка","name_en"=>"Roll","name_href" =>"lv/population-of-roll","count" =>"4 966","real_id" =>14,),
"15"=>array("name_ru"=>"Айзпуте","name_en"=>"Aizpute","name_href" =>"lv/population-of-aizpute","count" =>"4 389","real_id" =>15,),
"16"=>array("name_ru"=>"Гробиня","name_en"=>"Grobina","name_href" =>"lv/population-of-grobina","count" =>"3 769","real_id" =>16,),
"17"=>array("name_ru"=>"Кандава","name_en"=>"Kandava","name_href" =>"lv/population-of-kandava","count" =>"3 769","real_id" =>17,),
"18"=>array("name_ru"=>"Вангажи","name_en"=>"Vangazi","name_href" =>"lv/population-of-vangazi","count" =>"3 453","real_id" =>18,),
"19"=>array("name_ru"=>"Плявиняс","name_en"=>"Pļaviņas","name_href" =>"lv/population-of-pļaviņas","count" =>"3 219","real_id" =>19,),
"20"=>array("name_ru"=>"Виляны","name_en"=>"Vilani","name_href" =>"lv/population-of-vilani","count" =>"3 004","real_id" =>20,),
"21"=>array("name_ru"=>"Саулкрасты","name_en"=>"Saulkrasti","name_href" =>"lv/population-of-saulkrasti","count" =>"2 978","real_id" =>21,),
"22"=>array("name_ru"=>"Руйиена","name_en"=>"Rujiena","name_href" =>"lv/population-of-rujiena","count" =>"2 960","real_id" =>22,),
"23"=>array("name_ru"=>"Броцены","name_en"=>"Brocēni","name_href" =>"lv/population-of-brocēni","count" =>"2 881","real_id" =>23,),
"24"=>array("name_ru"=>"Салацгрива","name_en"=>"Salacgrīva","name_href" =>"lv/population-of-salacgrīva","count" =>"2 841","real_id" =>24,),
"25"=>array("name_ru"=>"Илуксте","name_en"=>"Ilukste","name_href" =>"lv/population-of-ilukste","count" =>"2 459","real_id" =>25,),
"26"=>array("name_ru"=>"Ауце","name_en"=>"Auce","name_href" =>"lv/population-of-auce","count" =>"2 418","real_id" =>26,),
"27"=>array("name_ru"=>"Балдоне","name_en"=>"Baldone","name_href" =>"lv/population-of-baldone","count" =>"2 305","real_id" =>27,),
"28"=>array("name_ru"=>"Кегумс","name_en"=>"Ķegums","name_href" =>"lv/population-of-ķegums","count" =>"2 229","real_id" =>28,),
"29"=>array("name_ru"=>"Дагда","name_en"=>"Dagda","name_href" =>"lv/population-of-dagda","count" =>"2 165","real_id" =>29,),
"30"=>array("name_ru"=>"Карсава","name_en"=>"Kārsava","name_href" =>"lv/population-of-kārsava","count" =>"2 081","real_id" =>30,),
"31"=>array("name_ru"=>"Скрунда","name_en"=>"Skrunda","name_href" =>"lv/population-of-skrunda","count" =>"2 081","real_id" =>31,),
"32"=>array("name_ru"=>"Приекуле","name_en"=>"Priekule","name_href" =>"lv/population-of-priekule","count" =>"2 034","real_id" =>32,),
"33"=>array("name_ru"=>"Яунелгава","name_en"=>"Jaunjelgava","name_href" =>"lv/population-of-jaunjelgava","count" =>"1 973","real_id" =>33,),
"34"=>array("name_ru"=>"Варакляны","name_en"=>"Varaklani","name_href" =>"lv/population-of-varaklani","count" =>"1 887","real_id" =>34,),
"35"=>array("name_ru"=>"Лубана","name_en"=>"Lubāna","name_href" =>"lv/population-of-lubāna","count" =>"1 674","real_id" =>35,),
"36"=>array("name_ru"=>"Стенде","name_en"=>"The stand","name_href" =>"lv/population-of-the stand","count" =>"1 671","real_id" =>36,),
"37"=>array("name_ru"=>"Виесите","name_en"=>"Viesite","name_href" =>"lv/population-of-viesite","count" =>"1 663","real_id" =>37,),
"38"=>array("name_ru"=>"Зилупе","name_en"=>"Zilupe","name_href" =>"lv/population-of-zilupe","count" =>"1 555","real_id" =>38,),
"39"=>array("name_ru"=>"Цесвайне","name_en"=>"Cesvaine","name_href" =>"lv/population-of-cesvaine","count" =>"1 477","real_id" =>39,),
"40"=>array("name_ru"=>"Сабиле","name_en"=>"Sabile","name_href" =>"lv/population-of-sabile","count" =>"1 467","real_id" =>40,),
"41"=>array("name_ru"=>"Виляка","name_en"=>"Vilaka","name_href" =>"lv/population-of-vilaka","count" =>"1 370","real_id" =>41,),
"42"=>array("name_ru"=>"Валдемарпилс","name_en"=>"Valdemarpils","name_href" =>"lv/population-of-valdemarpils","count" =>"1 287","real_id" =>42,),
"43"=>array("name_ru"=>"Седа","name_en"=>"Seda","name_href" =>"lv/population-of-seda","count" =>"1 233","real_id" =>43,),
"44"=>array("name_ru"=>"Мазсалаца","name_en"=>"Mazsalaca","name_href" =>"lv/population-of-mazsalaca","count" =>"1 215","real_id" =>44,),
"45"=>array("name_ru"=>"Стренчи","name_en"=>"Strenci","name_href" =>"lv/population-of-strenci","count" =>"1 184","real_id" =>45,),
"46"=>array("name_ru"=>"Алоя","name_en"=>"Aloja","name_href" =>"lv/population-of-aloja","count" =>"1 174","real_id" =>46,),
"47"=>array("name_ru"=>"Акнисте","name_en"=>"Akniste","name_href" =>"lv/population-of-akniste","count" =>"1 074","real_id" =>47,),
"48"=>array("name_ru"=>"Лигатне","name_en"=>"Ligatne","name_href" =>"lv/population-of-ligatne","count" =>"1 068","real_id" =>48,),
"49"=>array("name_ru"=>"Пилтене","name_en"=>"Piltene","name_href" =>"lv/population-of-piltene","count" =>"995","real_id" =>49,),
"50"=>array("name_ru"=>"Стайцеле","name_en"=>"Staicele","name_href" =>"lv/population-of-staicele","count" =>"953","real_id" =>50,),
"51"=>array("name_ru"=>"Павилоста","name_en"=>"Pavilosta","name_href" =>"lv/population-of-pavilosta","count" =>"936","real_id" =>51,),
"52"=>array("name_ru"=>"Апе","name_en"=>"APE","name_href" =>"lv/population-of-ape","count" =>"927","real_id" =>52,),
"53"=>array("name_ru"=>"Айнажи","name_en"=>"Ainazi","name_href" =>"lv/population-of-ainazi","count" =>"770","real_id" =>53,),
"54"=>array("name_ru"=>"Субате","name_en"=>"Subate","name_href" =>"lv/population-of-subate","count" =>"660","real_id" =>54,),
"55"=>array("name_ru"=>"Дурбе","name_en"=>"Durbe","name_href" =>"lv/population-of-durbe","count" =>"526","real_id" =>55,),
"56"=>array("name_ru"=>"Лудза","name_en"=>"Ludza","name_href" =>"lv/population-of-ludza","count" =>"8 300","real_id" =>56,),
"57"=>array("name_ru"=>"Гулбене","name_en"=>"Gulbene","name_href" =>"lv/population-of-gulbene","count" =>"7 843","real_id" =>57,),
"58"=>array("name_ru"=>"Мадона","name_en"=>"Madona","name_href" =>"lv/population-of-madona","count" =>"7 515","real_id" =>58,),
"59"=>array("name_ru"=>"Ливаны","name_en"=>"Livani","name_href" =>"lv/population-of-livani","count" =>"7 511","real_id" =>59,),
"60"=>array("name_ru"=>"Лимбажи","name_en"=>"Limbazi","name_href" =>"lv/population-of-limbazi","count" =>"7 470","real_id" =>60,)


);

?>