<?php
//Молдавия 59
$libmd = array (


"1"=>array("name_ru"=>"Кишинёв","name_en"=>"Chisinau","name_href" => "md/population-of-chisinau","count" => "6 745","real_id" =>1,),
"2"=>array("name_ru"=>"Бельцы","name_en"=>"Balti","name_href" => "md/population-of-balti","count" => "1 449","real_id" =>2,),
"3"=>array("name_ru"=>"Тирасполь","name_en"=>"Tiraspol","name_href" => "md/population-of-tiraspol","count" => "1 338","real_id" =>3,),
"4"=>array("name_ru"=>"Бендеры","name_en"=>"Bender","name_href" => "md/population-of-bender","count" => "919","real_id" =>4,),
"5"=>array("name_ru"=>"Рыбница","name_en"=>"Rybnitsa","name_href" => "md/population-of-rybnitsa","count" => "479","real_id" =>5,),
"6"=>array("name_ru"=>"Кагул","name_en"=>"Cahul","name_href" => "md/population-of-cahul","count" => "409","real_id" =>6,),
"7"=>array("name_ru"=>"Унгень","name_en"=>"Ungheni","name_href" => "md/population-of-ungheni","count" => "384","real_id" =>7,),
"8"=>array("name_ru"=>"Сороки","name_en"=>"Magpies","name_href" => "md/population-of-magpies","count" => "375","real_id" =>8,),
"9"=>array("name_ru"=>"Орхей","name_en"=>"Orhei","name_href" => "md/population-of-orhei","count" => "336","real_id" =>9,),
"10"=>array("name_ru"=>"Дубоссары","name_en"=>"Dubossary","name_href" => "md/population-of-dubossary","count" => "251","real_id" =>10,),
"11"=>array("name_ru"=>"Чадыр-Лунга","name_en"=>"Ceadir-Lunga","name_href" => "md/population-of-ceadir-lunga","count" => "228","real_id" =>11,),
"12"=>array("name_ru"=>"Страшены","name_en"=>"Straseni","name_href" => "md/population-of-straseni","count" => "214","real_id" =>12,),
"13"=>array("name_ru"=>"Дрокия","name_en"=>"Drochia","name_href" => "md/population-of-drochia","count" => "205","real_id" =>13,),
"14"=>array("name_ru"=>"Единец","name_en"=>"Edinet","name_href" => "md/population-of-edinet","count" => "202","real_id" =>14,),
"15"=>array("name_ru"=>"Каушаны","name_en"=>"Kaushany","name_href" => "md/population-of-kaushany","count" => "199","real_id" =>15,),
"16"=>array("name_ru"=>"Фалешты","name_en"=>"Făleşti","name_href" => "md/population-of-făleşti","count" => "182","real_id" =>16,),
"17"=>array("name_ru"=>"Хынчешты","name_en"=>"Hincesti","name_href" => "md/population-of-hincesti","count" => "174","real_id" =>17,),
"18"=>array("name_ru"=>"Калараш","name_en"=>"Călărași","name_href" => "md/population-of-călărași","count" => "167","real_id" =>18,),
"19"=>array("name_ru"=>"Чимишлия","name_en"=>"Cimislia","name_href" => "md/population-of-cimislia","count" => "163","real_id" =>19,),
"20"=>array("name_ru"=>"Яловены","name_en"=>"Ialoveni","name_href" => "md/population-of-ialoveni","count" => "162","real_id" =>20,),
"21"=>array("name_ru"=>"Сынжерея","name_en"=>"Singerei","name_href" => "md/population-of-singerei","count" => "155","real_id" =>21,),
"22"=>array("name_ru"=>"Флорешты","name_en"=>"Floresti","name_href" => "md/population-of-floresti","count" => "155","real_id" =>22,),
"23"=>array("name_ru"=>"Резина","name_en"=>"Rubber","name_href" => "md/population-of-rubber","count" => "152","real_id" =>23,),
"24"=>array("name_ru"=>"Слободзея","name_en"=>"Slobozia","name_href" => "md/population-of-slobozia","count" => "146","real_id" =>24,),
"25"=>array("name_ru"=>"Рышканы","name_en"=>"The rîşcani","name_href" => "md/population-of-the-rîşcani","count" => "145","real_id" =>25,),
"26"=>array("name_ru"=>"Ниспорены","name_en"=>"Nisporeni","name_href" => "md/population-of-nisporeni","count" => "144","real_id" =>26,),
"27"=>array("name_ru"=>"Бессарабка","name_en"=>"Bessarabka","name_href" => "md/population-of-bessarabka","count" => "125","real_id" =>27,),
"28"=>array("name_ru"=>"Новые Анены","name_en"=>"Anenii Noi","name_href" => "md/population-of-anenii-noi","count" => "119","real_id" =>28,),
"29"=>array("name_ru"=>"Глодяны","name_en"=>"Glodeni","name_href" => "md/population-of-glodeni","count" => "118","real_id" =>29,),
"30"=>array("name_ru"=>"Леова","name_en"=>"Leova","name_href" => "md/population-of-leova","count" => "109","real_id" =>30,),
"31"=>array("name_ru"=>"Дондюшаны","name_en"=>"Donduseni","name_href" => "md/population-of-donduseni","count" => "106","real_id" =>31,),
"32"=>array("name_ru"=>"Днестровск","name_en"=>"Dnestrovsk","name_href" => "md/population-of-dnestrovsk","count" => "104","real_id" =>32,),
"33"=>array("name_ru"=>"Бричаны","name_en"=>"Brichany","name_href" => "md/population-of-brichany","count" => "99","real_id" =>33,),
"34"=>array("name_ru"=>"Теленешты","name_en"=>"Telenesti","name_href" => "md/population-of-telenesti","count" => "99","real_id" =>34,),
"35"=>array("name_ru"=>"Криулень","name_en"=>"Criuleni","name_href" => "md/population-of-criuleni","count" => "98","real_id" =>35,),
"36"=>array("name_ru"=>"Окница","name_en"=>"Ocnita","name_href" => "md/population-of-ocnita","count" => "95","real_id" =>36,),
"37"=>array("name_ru"=>"Григориополь","name_en"=>"Grigoriopol","name_href" => "md/population-of-grigoriopol","count" => "94","real_id" =>37,),
"38"=>array("name_ru"=>"Купчинь","name_en"=>"Roaming","name_href" => "md/population-of-roaming","count" => "93","real_id" =>38,),
"39"=>array("name_ru"=>"Каменка","name_en"=>"Kamenka","name_href" => "md/population-of-kamenka","count" => "89","real_id" =>39,),
"40"=>array("name_ru"=>"Штефан-Водэ","name_en"=>"Stefan Voda","name_href" => "md/population-of-stefan-voda","count" => "86","real_id" =>40,),
"41"=>array("name_ru"=>"Фрунзе","name_en"=>"Frunze","name_href" => "md/population-of-frunze","count" => "84","real_id" =>41,),
"42"=>array("name_ru"=>"Шолданешты","name_en"=>"Şoldăneşti","name_href" => "md/population-of-şoldăneşti","count" => "75","real_id" =>42,),
"43"=>array("name_ru"=>"Кантемир","name_en"=>"Cantemir","name_href" => "md/population-of-cantemir","count" => "58","real_id" =>43,),
"44"=>array("name_ru"=>"Твардица","name_en"=>"Tvardita","name_href" => "md/population-of-tvardita","count" => "58","real_id" =>44,),
"45"=>array("name_ru"=>"Липканы","name_en"=>"Lipcani","name_href" => "md/population-of-lipcani","count" => "55","real_id" =>45,),
"46"=>array("name_ru"=>"Каинары","name_en"=>"Canary","name_href" => "md/population-of-canary","count" => "48","real_id" =>46,),
"47"=>array("name_ru"=>"Яргара","name_en"=>"Sochi","name_href" => "md/population-of-sochi","count" => "48","real_id" =>47,),
"48"=>array("name_ru"=>"Костешты","name_en"=>"Costesti","name_href" => "md/population-of-costesti","count" => "44","real_id" =>48,),
"49"=>array("name_ru"=>"Бируинца","name_en"=>"Biruinţa","name_href" => "md/population-of-biruinţa","count" => "39","real_id" =>49,),
"50"=>array("name_ru"=>"Красное","name_en"=>"Red","name_href" => "md/population-of-red","count" => "36","real_id" =>50,),
"51"=>array("name_ru"=>"Корнешты","name_en"=>"The Cornesti","name_href" => "md/population-of-the-cornesti","count" => "33","real_id" =>51,),
"52"=>array("name_ru"=>"Комрат","name_en"=>"Comrat","name_href" => "md/population-of-comrat","count" => "26","real_id" =>52,),
"53"=>array("name_ru"=>"Гиндешты","name_en"=>"Gindesti","name_href" => "md/population-of-gindesti","count" => "21","real_id" =>53,),
"54"=>array("name_ru"=>"Маркулешты","name_en"=>"Marculesti","name_href" => "md/population-of-marculesti","count" => "21","real_id" =>54,),
"55"=>array("name_ru"=>"Быковец","name_en"=>"Bykovets","name_href" => "md/population-of-bykovets","count" => "18","real_id" =>55,),
"56"=>array("name_ru"=>"Вулканешты","name_en"=>"Vulcanesti","name_href" => "md/population-of-vulcanesti","count" => "17","real_id" =>56,),
"57"=>array("name_ru"=>"Тараклия","name_en"=>"Taraclia","name_href" => "md/population-of-taraclia","count" => "15","real_id" =>57,),
"58"=>array("name_ru"=>"Отачь","name_en"=>"Otaci","name_href" => "md/population-of-otaci","count" => "14","real_id" =>58,),
"59"=>array("name_ru"=>"Маяк","name_en"=>"Lighthouse","name_href" => "md/population-of-lighthouse","count" => "11","real_id" =>59,),
"60"=>array("name_ru"=>"Кишинёв","name_en"=>"Chisinau","name_href" => "md/population-of-chisinau","count" => "6 745","real_id" =>60,),
"61"=>array("name_ru"=>"Бельцы","name_en"=>"Balti","name_href" => "md/population-of-balti","count" => "1 449","real_id" =>61,),
"62"=>array("name_ru"=>"Тирасполь","name_en"=>"Tiraspol","name_href" => "md/population-of-tiraspol","count" => "1 338","real_id" =>62,),
"63"=>array("name_ru"=>"Бендеры","name_en"=>"Bender","name_href" => "md/population-of-bender","count" => "919","real_id" =>63,),
"64"=>array("name_ru"=>"Рыбница","name_en"=>"Rybnitsa","name_href" => "md/population-of-rybnitsa","count" => "479","real_id" =>64,)


);

?>