<?php
//Марокко 70
$libma = array (


"1"=>array("name_ru"=>"Касабланка","name_en"=>"Casablanca","name_href" => "ma/population-of-casablanca","count" => "3 356 337","real_id" =>1,),
"2"=>array("name_ru"=>"Рабат","name_en"=>"Discount","name_href" => "ma/population-of-discount","count" => "1 884 917","real_id" =>2,),
"3"=>array("name_ru"=>"Фес","name_en"=>"Fes","name_href" => "ma/population-of-fes","count" => "1 072 468","real_id" =>3,),
"4"=>array("name_ru"=>"Марракеш","name_en"=>"Marrakech","name_href" => "ma/population-of-marrakech","count" => "953 305","real_id" =>4,),
"5"=>array("name_ru"=>"Танжер","name_en"=>"Tangier","name_href" => "ma/population-of-tangier","count" => "793 776","real_id" =>5,),
"6"=>array("name_ru"=>"Мекнес","name_en"=>"Meknes","name_href" => "ma/population-of-meknes","count" => "616 110","real_id" =>6,),
"7"=>array("name_ru"=>"Агадир","name_en"=>"Agadir","name_href" => "ma/population-of-agadir","count" => "600 177","real_id" =>7,),
"8"=>array("name_ru"=>"Уджда","name_en"=>"Oujda","name_href" => "ma/population-of-oujda","count" => "435 378","real_id" =>8,),
"9"=>array("name_ru"=>"Кенитра","name_en"=>"Kenitra","name_href" => "ma/population-of-kenitra","count" => "418 222","real_id" =>9,),
"10"=>array("name_ru"=>"Тетуан","name_en"=>"Tetouan","name_href" => "ma/population-of-tetouan","count" => "363 031","real_id" =>10,),
"11"=>array("name_ru"=>"Сафи","name_en"=>"Safi","name_href" => "ma/population-of-safi","count" => "311 201","real_id" =>11,),
"12"=>array("name_ru"=>"Мохаммедия","name_en"=>"Mohammedia","name_href" => "ma/population-of-mohammedia","count" => "206 896","real_id" =>12,),
"13"=>array("name_ru"=>"Бени-Меллаль","name_en"=>"Beni Mellal","name_href" => "ma/population-of-beni-mellal","count" => "189 535","real_id" =>13,),
"14"=>array("name_ru"=>"Хурибга","name_en"=>"Khouribga","name_href" => "ma/population-of-khouribga","count" => "175 737","real_id" =>14,),
"15"=>array("name_ru"=>"Эль-Джадида","name_en"=>"El Jadida","name_href" => "ma/population-of-el-jadida","count" => "170 956","real_id" =>15,),
"16"=>array("name_ru"=>"Таза","name_en"=>"Pelvis","name_href" => "ma/population-of-pelvis","count" => "156 768","real_id" =>16,),
"17"=>array("name_ru"=>"Надор","name_en"=>"Nador","name_href" => "ma/population-of-nador","count" => "152 341","real_id" =>17,),
"18"=>array("name_ru"=>"Сеттат","name_en"=>"Settat","name_href" => "ma/population-of-settat","count" => "137 690","real_id" =>18,),
"19"=>array("name_ru"=>"Беррешид","name_en"=>"Berrechid","name_href" => "ma/population-of-berrechid","count" => "128 749","real_id" =>19,),
"20"=>array("name_ru"=>"Лараш","name_en"=>"Of larache","name_href" => "ma/population-of-of-larache","count" => "121 257","real_id" =>20,),
"21"=>array("name_ru"=>"Хемиссет","name_en"=>"Khemisset","name_href" => "ma/population-of-khemisset","count" => "118 546","real_id" =>21,),
"22"=>array("name_ru"=>"Эль-Ксар-эль-Кебир","name_en"=>"El-Ksar El-Kebir","name_href" => "ma/population-of-el-ksar-el-kebir","count" => "116 513","real_id" =>22,),
"23"=>array("name_ru"=>"Гулимин","name_en"=>"Golymin","name_href" => "ma/population-of-golymin","count" => "114 359","real_id" =>23,),
"24"=>array("name_ru"=>"Эр-Рашидия","name_en"=>"Errachidia","name_href" => "ma/population-of-errachidia","count" => "102 154","real_id" =>24,),
"25"=>array("name_ru"=>"Таурирт","name_en"=>"Taouirt","name_href" => "ma/population-of-taouirt","count" => "101 681","real_id" =>25,),
"26"=>array("name_ru"=>"Фких-Бен-Салах","name_en"=>"Fkih-Ben-Salah","name_href" => "ma/population-of-fkih-ben-salah","count" => "96 157","real_id" =>26,),
"27"=>array("name_ru"=>"Уэд-Зем","name_en"=>"Oued-ZEM","name_href" => "ma/population-of-oued-zem","count" => "91 231","real_id" =>27,),
"28"=>array("name_ru"=>"Сиди-Слиман","name_en"=>"Sidi Slimane","name_href" => "ma/population-of-sidi-slimane","count" => "88 559","real_id" =>28,),
"29"=>array("name_ru"=>"Беркан","name_en"=>"Berkan","name_href" => "ma/population-of-berkan","count" => "85 242","real_id" =>29,),
"30"=>array("name_ru"=>"Бен-Герир","name_en"=>"Ben-Guerir","name_href" => "ma/population-of-ben-guerir","count" => "84 290","real_id" =>30,),
"31"=>array("name_ru"=>"Эль-Келаа-Дес-Срагна","name_en"=>"El-Kelaa-Des-Sraghna","name_href" => "ma/population-of-el-kelaa-des-sraghna","count" => "83 931","real_id" =>31,),
"32"=>array("name_ru"=>"Тарудант","name_en"=>"Taroudant","name_href" => "ma/population-of-taroudant","count" => "83 259","real_id" =>32,),
"33"=>array("name_ru"=>"Хенифра","name_en"=>"Khenifra","name_href" => "ma/population-of-khenifra","count" => "82 740","real_id" =>33,),
"34"=>array("name_ru"=>"Сиди-Касем","name_en"=>"Sidi Kacem","name_href" => "ma/population-of-sidi-kacem","count" => "78 709","real_id" =>34,),
"35"=>array("name_ru"=>"Эс-Сувейра","name_en"=>"Essaouira","name_href" => "ma/population-of-essaouira","count" => "78 390","real_id" =>35,),
"36"=>array("name_ru"=>"Лекльяа","name_en"=>"Laclau","name_href" => "ma/population-of-laclau","count" => "75 227","real_id" =>36,),
"37"=>array("name_ru"=>"Сефру","name_en"=>"Sefrou","name_href" => "ma/population-of-sefrou","count" => "72 574","real_id" =>37,),
"38"=>array("name_ru"=>"Улад-Теима","name_en"=>"Oulad-Teima","name_href" => "ma/population-of-oulad-teima","count" => "71 588","real_id" =>38,),
"39"=>array("name_ru"=>"Тифлет","name_en"=>"Iaakien","name_href" => "ma/population-of-iaakien","count" => "69 746","real_id" =>39,),
"40"=>array("name_ru"=>"Юуссуфиа","name_en"=>"Youssoufia","name_href" => "ma/population-of-youssoufia","count" => "68 972","real_id" =>40,),
"41"=>array("name_ru"=>"Тан-Тан","name_en"=>"Tan-Tan","name_href" => "ma/population-of-tan-tan","count" => "68 843","real_id" =>41,),
"42"=>array("name_ru"=>"Тизнит","name_en"=>"Tiznit","name_href" => "ma/population-of-tiznit","count" => "65 600","real_id" =>42,),
"43"=>array("name_ru"=>"Уаззан","name_en"=>"Wazzan","name_href" => "ma/population-of-wazzan","count" => "63 102","real_id" =>43,),
"44"=>array("name_ru"=>"Уарзазат","name_en"=>"Ouarzazate","name_href" => "ma/population-of-ouarzazate","count" => "61 870","real_id" =>44,),
"45"=>array("name_ru"=>"Фнидк","name_en"=>"Fnidq","name_href" => "ma/population-of-fnidq","count" => "59 263","real_id" =>45,),
"46"=>array("name_ru"=>"Гуерсиф","name_en"=>"Guercif","name_href" => "ma/population-of-guercif","count" => "59 257","real_id" =>46,),
"47"=>array("name_ru"=>"Эль-Хосейма","name_en"=>"Al Hoceïma","name_href" => "ma/population-of-al-hoceïma","count" => "58 855","real_id" =>47,),
"48"=>array("name_ru"=>"Схират","name_en"=>"Skhirat","name_href" => "ma/population-of-skhirat","count" => "57 773","real_id" =>48,),
"49"=>array("name_ru"=>"Сук-эс-Сабт-Авлад-ан-Нама","name_en"=>"Suk-es-Sebt-Awlad an-Nama","name_href" => "ma/population-of-suk-es-sebt-awlad-an-nama","count" => "55 643","real_id" =>49,),
"50"=>array("name_ru"=>"Мдик","name_en"=>"Mdic","name_href" => "ma/population-of-mdic","count" => "54 868","real_id" =>50,),
"51"=>array("name_ru"=>"Азру","name_en"=>"Azrou","name_href" => "ma/population-of-azrou","count" => "53 199","real_id" =>51,),
"52"=>array("name_ru"=>"Бен-Слиман","name_en"=>"Ben Slimane","name_href" => "ma/population-of-ben-slimane","count" => "50 124","real_id" =>52,),
"53"=>array("name_ru"=>"Сук-эль-Арба","name_en"=>"Souk-El-Arba","name_href" => "ma/population-of-souk-el-arba","count" => "48 362","real_id" =>53,),
"54"=>array("name_ru"=>"Мидельт","name_en"=>"Midelt","name_href" => "ma/population-of-midelt","count" => "47 963","real_id" =>54,),
"55"=>array("name_ru"=>"Касба-Тадла","name_en"=>"Kasba Tadla","name_href" => "ma/population-of-kasba-tadla","count" => "44 579","real_id" =>55,),
"56"=>array("name_ru"=>"Сиди-Беннур","name_en"=>"Sidi Bennour","name_href" => "ma/population-of-sidi-bennour","count" => "44 344","real_id" =>56,),
"57"=>array("name_ru"=>"Мартиль","name_en"=>"Martil","name_href" => "ma/population-of-martil","count" => "43 165","real_id" =>57,),
"58"=>array("name_ru"=>"Джерада","name_en"=>"Jerada","name_href" => "ma/population-of-jerada","count" => "41 823","real_id" =>58,),
"59"=>array("name_ru"=>"Буджад","name_en"=>"Budged","name_href" => "ma/population-of-budged","count" => "41 531","real_id" =>59,),
"60"=>array("name_ru"=>"Аземмур","name_en"=>"Azemmour","name_href" => "ma/population-of-azemmour","count" => "41 128","real_id" =>60,),
"61"=>array("name_ru"=>"Биугра","name_en"=>"Biogra","name_href" => "ma/population-of-biogra","count" => "41 048","real_id" =>61,),
"62"=>array("name_ru"=>"Тингир","name_en"=>"Tinerhir","name_href" => "ma/population-of-tinerhir","count" => "39 768","real_id" =>62,),
"63"=>array("name_ru"=>"Эйн-эль-Ауда","name_en"=>"Ein El-Auda","name_href" => "ma/population-of-ein-el-auda","count" => "38 840","real_id" =>63,),
"64"=>array("name_ru"=>"Шефшауен","name_en"=>"Chefchaouen","name_href" => "ma/population-of-chefchaouen","count" => "38 684","real_id" =>64,),
"65"=>array("name_ru"=>"Эль-Аюн-Сиди-Меллук","name_en"=>"Laayoune-Sidi-Mellouk","name_href" => "ma/population-of-laayoune-sidi-mellouk","count" => "38 415","real_id" =>65,),
"66"=>array("name_ru"=>"Азилаль","name_en"=>"Azilal","name_href" => "ma/population-of-azilal","count" => "38 126","real_id" =>66,),
"67"=>array("name_ru"=>"Мрирт","name_en"=>"Mrirt","name_href" => "ma/population-of-mrirt","count" => "37 697","real_id" =>67,),
"68"=>array("name_ru"=>"Аль-Аруи","name_en"=>"Al-Arui","name_href" => "ma/population-of-al-arui","count" => "37 594","real_id" =>68,),
"69"=>array("name_ru"=>"Загора","name_en"=>"Zagora","name_href" => "ma/population-of-zagora","count" => "37 305","real_id" =>69,),
"70"=>array("name_ru"=>"Сиди-Таиби","name_en"=>"Sit-Taybi","name_href" => "ma/population-of-sit-taybi","count" => "36 741","real_id" =>70,),
"71"=>array("name_ru"=>"Касабланка","name_en"=>"Casablanca","name_href" => "ma/population-of-casablanca","count" => "3 356 337","real_id" =>71,),
"72"=>array("name_ru"=>"Рабат","name_en"=>"Discount","name_href" => "ma/population-of-discount","count" => "1 884 917","real_id" =>72,),
"73"=>array("name_ru"=>"Фес","name_en"=>"Fes","name_href" => "ma/population-of-fes","count" => "1 072 468","real_id" =>73,),
"74"=>array("name_ru"=>"Марракеш","name_en"=>"Marrakech","name_href" => "ma/population-of-marrakech","count" => "953 305","real_id" =>74,),
"75"=>array("name_ru"=>"Танжер","name_en"=>"Tangier","name_href" => "ma/population-of-tangier","count" => "793 776","real_id" =>75,)


);

?>