<?php
//Мьянма 
$libmm = array ( 
"1"=>array("name_ru"=>"Рангун","name_en"=>"Rangoon","name_href" => "mm/population-of-rangoon","count" => "7 360 703","real_id" =>1,),
"2"=>array("name_ru"=>"Мандалай","name_en"=>"Mandalay","name_href" => "mm/population-of-mandalay","count" => "1 034 000","real_id" =>2,),
"3"=>array("name_ru"=>"Моулмейн","name_en"=>"Mawlamyine","name_href" => "mm/population-of-mawlamyine","count" => "451 011","real_id" =>3,),
"4"=>array("name_ru"=>"Пегу","name_en"=>"Bago","name_href" => "mm/population-of-bago","count" => "248 899","real_id" =>4,),
"5"=>array("name_ru"=>"Бассейн","name_en"=>"Pool","name_href" => "mm/population-of-pool","count" => "241 624","real_id" =>5,),
"6"=>array("name_ru"=>"Моунъюа","name_en"=>"Monywa","name_href" => "mm/population-of-monywa","count" => "185 783","real_id" =>6,),
"7"=>array("name_ru"=>"Мейтхила","name_en"=>"Mathila","name_href" => "mm/population-of-mathila","count" => "181 744","real_id" =>7,),
"8"=>array("name_ru"=>"Акьяб","name_en"=>"Akyab","name_href" => "mm/population-of-akyab","count" => "181 172","real_id" =>8,),
"9"=>array("name_ru"=>"Мьей","name_en"=>"Myeik","name_href" => "mm/population-of-myeik","count" => "177 961","real_id" =>9,),
"10"=>array("name_ru"=>"Таунджи","name_en"=>"Taunggyi","name_href" => "mm/population-of-taunggyi","count" => "162 396","real_id" =>10,),
"11"=>array("name_ru"=>"Мьинджан","name_en"=>"Minjan","name_href" => "mm/population-of-minjan","count" => "145 150","real_id" =>11,),
"12"=>array("name_ru"=>"Тавой","name_en"=>"Dawei","name_href" => "mm/population-of-dawei","count" => "140 475","real_id" =>12,),
"13"=>array("name_ru"=>"Пьи","name_en"=>"Pyay","name_href" => "mm/population-of-pyay","count" => "137 814","real_id" =>13,),
"14"=>array("name_ru"=>"Хинтада","name_en"=>"Hinted","name_href" => "mm/population-of-hinted","count" => "137 530","real_id" =>14,),
"15"=>array("name_ru"=>"Лашо","name_en"=>"Lashio","name_href" => "mm/population-of-lashio","count" => "132 880","real_id" =>15,),
"16"=>array("name_ru"=>"Пакхоуку","name_en"=>"Pakkoku","name_href" => "mm/population-of-pakkoku","count" => "129 781","real_id" =>16,),
"17"=>array("name_ru"=>"Татон","name_en"=>"Thaton","name_href" => "mm/population-of-thaton","count" => "127 207","real_id" =>17,),
"18"=>array("name_ru"=>"Мемьо","name_en"=>"Pyin OO Lwin","name_href" => "mm/population-of-pyin-oo-lwin","count" => "120 149","real_id" =>18,),
"19"=>array("name_ru"=>"Енанджаун","name_en"=>"Anandrao","name_href" => "mm/population-of-anandrao","count" => "113 029","real_id" =>19,),
"20"=>array("name_ru"=>"Таунгу","name_en"=>"Taungoo","name_href" => "mm/population-of-taungoo","count" => "108 926","real_id" =>20,),
"21"=>array("name_ru"=>"Таемьо","name_en"=>"Teemo","name_href" => "mm/population-of-teemo","count" => "104 312","real_id" =>21,),
"22"=>array("name_ru"=>"Пьинмана","name_en"=>"Pyinmana","name_href" => "mm/population-of-pyinmana","count" => "99 773","real_id" =>22,),
"23"=>array("name_ru"=>"Магуэ","name_en"=>"Motswari","name_href" => "mm/population-of-motswari","count" => "99 126","real_id" =>23,),
"24"=>array("name_ru"=>"Могоу","name_en"=>"Mogo","name_href" => "mm/population-of-mogo","count" => "93 047","real_id" =>24,),
"25"=>array("name_ru"=>"Чау","name_en"=>"Chow","name_href" => "mm/population-of-chow","count" => "92 906","real_id" =>25,),
"26"=>array("name_ru"=>"Мьичина","name_en"=>"Myitkyina","name_href" => "mm/population-of-myitkyina","count" => "92 543","real_id" =>26,),
"27"=>array("name_ru"=>"Мудоун","name_en"=>"Mudon","name_href" => "mm/population-of-mudon","count" => "91 634","real_id" =>27,),
"28"=>array("name_ru"=>"Калемьо","name_en"=>"Kostroma","name_href" => "mm/population-of-kostroma","count" => "91 530","real_id" =>28,),
"29"=>array("name_ru"=>"Ньяунлебин","name_en"=>"Nyaunglebin","name_href" => "mm/population-of-nyaunglebin","count" => "91 287","real_id" =>29,),
"30"=>array("name_ru"=>"Шуэбо","name_en"=>"Shwebo","name_href" => "mm/population-of-shwebo","count" => "90 758","real_id" =>30,),
"31"=>array("name_ru"=>"Сагайн","name_en"=>"Sagaing","name_href" => "mm/population-of-sagaing","count" => "80 372","real_id" =>31,),
"32"=>array("name_ru"=>"Таундуинджи","name_en"=>"Taungdwingyi","name_href" => "mm/population-of-taungdwingyi","count" => "71 665","real_id" =>32,),
"33"=>array("name_ru"=>"Танхльин ","name_en"=>"Tanglin","name_href" => "mm/population-of-tanglin","count" => "70 490","real_id" =>33,),
"34"=>array("name_ru"=>"Чёнгтун","name_en"=>"Changchun","name_href" => "mm/population-of-changchun","count" => "70 438","real_id" =>34,),
"35"=>array("name_ru"=>"Богале","name_en"=>"Bogale","name_href" => "mm/population-of-bogale","count" => "70 257","real_id" =>35,),
"36"=>array("name_ru"=>"Пьяпон","name_en"=>"Between pyapon","name_href" => "mm/population-of-between-pyapon","count" => "66 857","real_id" =>36,),
"37"=>array("name_ru"=>"Яметин","name_en"=>"Amatin","name_href" => "mm/population-of-amatin","count" => "62 275","real_id" =>37,),
"38"=>array("name_ru"=>"Ракхайн","name_en"=>"Rakhine","name_href" => "mm/population-of-rakhine","count" => "60 809","real_id" =>38,),
"39"=>array("name_ru"=>"Allanmyo","name_en"=>"Allanmyo","name_href" => "mm/population-of-allanmyo","count" => "59 194","real_id" =>39,),
"40"=>array("name_ru"=>"Kanbe","name_en"=>"Kanbe","name_href" => "mm/population-of-kanbe","count" => "59 018","real_id" =>40,),
"41"=>array("name_ru"=>"Минбу","name_en"=>"Minbu","name_href" => "mm/population-of-minbu","count" => "58 628","real_id" =>41,),
"42"=>array("name_ru"=>"Е","name_en"=>"E","name_href" => "mm/population-of-e","count" => "57 248","real_id" =>42,),
"43"=>array("name_ru"=>"Tharrawaddy","name_en"=>"Tharrawaddy","name_href" => "mm/population-of-tharrawaddy","count" => "55 393","real_id" =>43,),
"44"=>array("name_ru"=>"Kyaiklat","name_en"=>"Kyaiklat","name_href" => "mm/population-of-kyaiklat","count" => "53 428","real_id" =>44,),
"45"=>array("name_ru"=>"Тоунгуа","name_en"=>"Tongue","name_href" => "mm/population-of-tongue","count" => "53 284","real_id" =>45,),
"46"=>array("name_ru"=>"Маубин","name_en"=>"Maubin","name_href" => "mm/population-of-maubin","count" => "52 316","real_id" =>46,),
"47"=>array("name_ru"=>"Kyaukse","name_en"=>"Kyaukse","name_href" => "mm/population-of-kyaukse","count" => "51 667","real_id" =>47,),
"48"=>array("name_ru"=>"Рангун","name_en"=>"Rangoon","name_href" => "mm/population-of-rangoon","count" => "7 360 703","real_id" =>48,),
"49"=>array("name_ru"=>"Мандалай","name_en"=>"Mandalay","name_href" => "mm/population-of-mandalay","count" => "1 034 000","real_id" =>49,),
"50"=>array("name_ru"=>"Моулмейн","name_en"=>"Mawlamyine","name_href" => "mm/population-of-mawlamyine","count" => "451 011","real_id" =>50,),
"51"=>array("name_ru"=>"Пегу","name_en"=>"Bago","name_href" => "mm/population-of-bago","count" => "248 899","real_id" =>51,),
"52"=>array("name_ru"=>"Бассейн","name_en"=>"Pool","name_href" => "mm/population-of-pool","count" => "241 624","real_id" =>52,)
);

?>