<?php
//Нигерия 40
$libng = array ( 
"1"=>array("name_ru"=>"Ибадан","name_en"=>"Ibadan","name_href" => "ng/population-of-ibadan","count" => "5 175 223","real_id" =>1,),
"2"=>array("name_ru"=>"Кано","name_en"=>"Kano","name_href" => "ng/population-of-kano","count" => "3 848 885","real_id" =>2,),
"3"=>array("name_ru"=>"Лагос","name_en"=>"Lagos","name_href" => "ng/population-of-lagos","count" => "13 123 000","real_id" =>3,),
"4"=>array("name_ru"=>"Бенин-Сити","name_en"=>"Benin City","name_href" => "ng/population-of-benin-city","count" => "2 406 697","real_id" =>4,),
"5"=>array("name_ru"=>"Порт-Харкорт","name_en"=>"Port Harcourt","name_href" => "ng/population-of-port-harcourt","count" => "2 100 711","real_id" =>5,),
"6"=>array("name_ru"=>"Кадуна","name_en"=>"Kaduna","name_href" => "ng/population-of-kaduna","count" => "2 061 175","real_id" =>6,),
"7"=>array("name_ru"=>"Аба","name_en"=>"ABA","name_href" => "ng/population-of-aba","count" => "1 597 296","real_id" =>7,),
"8"=>array("name_ru"=>"Абуджа","name_en"=>"Abuja","name_href" => "ng/population-of-abuja","count" => "1 352 679","real_id" =>8,),
"9"=>array("name_ru"=>"Майдугури","name_en"=>"Maiduguri","name_href" => "ng/population-of-maiduguri","count" => "1 126 195","real_id" =>9,),
"10"=>array("name_ru"=>"Илорин","name_en"=>"Ilorin","name_href" => "ng/population-of-ilorin","count" => "1 084 681","real_id" =>10,),
"11"=>array("name_ru"=>"Варри","name_en"=>"Warri","name_href" => "ng/population-of-warri","count" => "933 762","real_id" =>11,),
"12"=>array("name_ru"=>"Онича","name_en"=>"Onitsha","name_href" => "ng/population-of-onitsha","count" => "910 778","real_id" =>12,),
"13"=>array("name_ru"=>"Акуре","name_en"=>"Akure","name_href" => "ng/population-of-akure","count" => "847 903","real_id" =>13,),
"14"=>array("name_ru"=>"Абеокута","name_en"=>"Abeokuta","name_href" => "ng/population-of-abeokuta","count" => "801 282","real_id" =>14,),
"15"=>array("name_ru"=>"Энугу","name_en"=>"Enugu","name_href" => "ng/population-of-enugu","count" => "715 774","real_id" =>15,),
"16"=>array("name_ru"=>"Ошогбо","name_en"=>"Oshogbo","name_href" => "ng/population-of-oshogbo","count" => "678 265","real_id" =>16,),
"17"=>array("name_ru"=>"Зариа","name_en"=>"Zaria","name_href" => "ng/population-of-zaria","count" => "667 425","real_id" =>17,),
"18"=>array("name_ru"=>"Ифе","name_en"=>"IFE","name_href" => "ng/population-of-ife","count" => "635 196","real_id" =>18,),
"19"=>array("name_ru"=>"Джос","name_en"=>"Joes","name_href" => "ng/population-of-joes","count" => "622 802","real_id" =>19,),
"20"=>array("name_ru"=>"Ондо","name_en"=>"Ondo","name_href" => "ng/population-of-ondo","count" => "498 056","real_id" =>20,),
"21"=>array("name_ru"=>"Гбоко","name_en"=>"Gboko","name_href" => "ng/population-of-gboko","count" => "485 743","real_id" =>21,),
"22"=>array("name_ru"=>"Оверри","name_en"=>"Owerri","name_href" => "ng/population-of-owerri","count" => "474 750","real_id" =>22,),
"23"=>array("name_ru"=>"Джалинго","name_en"=>"Jalingo","name_href" => "ng/population-of-jalingo","count" => "438 971","real_id" =>23,),
"24"=>array("name_ru"=>"Асаба","name_en"=>"Asaba","name_href" => "ng/population-of-asaba","count" => "407 126","real_id" =>24,),
"25"=>array("name_ru"=>"Иджебу-Оде","name_en"=>"Ijebu-Ode","name_href" => "ng/population-of-ijebu-ode","count" => "403 836","real_id" =>25,),
"26"=>array("name_ru"=>"Ойо","name_en"=>"Oyo","name_href" => "ng/population-of-oyo","count" => "383 687","real_id" =>26,),
"27"=>array("name_ru"=>"Адо-Экити","name_en"=>"ADO-Ekiti","name_href" => "ng/population-of-ado-ekiti","count" => "378 519","real_id" =>27,),
"28"=>array("name_ru"=>"Илеша","name_en"=>"Ilesha","name_href" => "ng/population-of-ilesha","count" => "374 543","real_id" =>28,),
"29"=>array("name_ru"=>"Сокото","name_en"=>"Sokoto","name_href" => "ng/population-of-sokoto","count" => "360 486","real_id" =>29,),
"30"=>array("name_ru"=>"Минна","name_en"=>"Mine","name_href" => "ng/population-of-mine","count" => "322 163","real_id" =>30,),
"31"=>array("name_ru"=>"Уйо","name_en"=>"Uyo","name_href" => "ng/population-of-uyo","count" => "319 960","real_id" =>31,),
"32"=>array("name_ru"=>"Калабар","name_en"=>"Calabar","name_href" => "ng/population-of-calabar","count" => "318 390","real_id" =>32,),
"33"=>array("name_ru"=>"Баучи","name_en"=>"Bauchi","name_href" => "ng/population-of-bauchi","count" => "294 395","real_id" =>33,),
"34"=>array("name_ru"=>"Джимета","name_en"=>"Jimeta","name_href" => "ng/population-of-jimeta","count" => "270 836","real_id" =>34,),
"35"=>array("name_ru"=>"Огбомошо","name_en"=>"Ogbomosho","name_href" => "ng/population-of-ogbomosho","count" => "269 331","real_id" =>35,),
"36"=>array("name_ru"=>"Илобу","name_en"=>"Ilobu","name_href" => "ng/population-of-ilobu","count" => "264 389","real_id" =>36,),
"37"=>array("name_ru"=>"Абакалики","name_en"=>"Abakaliki","name_href" => "ng/population-of-abakaliki","count" => "242 801","real_id" =>37,),
"38"=>array("name_ru"=>"Сапеле","name_en"=>"Sapele","name_href" => "ng/population-of-sapele","count" => "218 391","real_id" =>38,),
"39"=>array("name_ru"=>"Кацина","name_en"=>"Katsina","name_href" => "ng/population-of-katsina","count" => "213 604","real_id" =>39,),
"40"=>array("name_ru"=>"Гомбе","name_en"=>"Gombe","name_href" => "ng/population-of-gombe","count" => "197 394","real_id" =>40,),
"41"=>array("name_ru"=>"Ибадан","name_en"=>"Ibadan","name_href" => "ng/population-of-ibadan","count" => "5 175 223","real_id" =>41,),
"42"=>array("name_ru"=>"Кано","name_en"=>"Kano","name_href" => "ng/population-of-kano","count" => "3 848 885","real_id" =>42,),
"43"=>array("name_ru"=>"Лагос","name_en"=>"Lagos","name_href" => "ng/population-of-lagos","count" => "13 123 000","real_id" =>43,),
"44"=>array("name_ru"=>"Бенин-Сити","name_en"=>"Benin City","name_href" => "ng/population-of-benin-city","count" => "2 406 697","real_id" =>44,),
"45"=>array("name_ru"=>"Порт-Харкорт","name_en"=>"Port Harcourt","name_href" => "ng/population-of-port-harcourt","count" => "2 100 711","real_id" =>45,)
);

?>