<?php
//Норвегия 101 
$libno = array ( 
"1"=>array("name_ru"=>"Осло","name_en"=>"Oslo","name_href" =>"no/population-of-oslo","count" =>"673 469","real_id" =>1,),
"2"=>array("name_ru"=>"Акерсхус","name_en"=>"Akershus","name_href" =>"no/population-of-akershus","count" =>"566 399","real_id" =>2,),
"3"=>array("name_ru"=>"Хордаланн","name_en"=>"Hordaland","name_href" =>"no/population-of-hordaland","count" =>"498 135","real_id" =>3,),
"4"=>array("name_ru"=>"Ругаланн","name_en"=>"Rogaland","name_href" =>"no/population-of-rogaland","count" =>"452 159","real_id" =>4,),
"5"=>array("name_ru"=>"Сёр-Трёнделаг","name_en"=>"SOR-Trondelag","name_href" =>"no/population-of-sor-trondelag","count" =>"302 755","real_id" =>5,),
"6"=>array("name_ru"=>"Эстфолл","name_en"=>"Østfold","name_href" =>"no/population-of-østfold","count" =>"282 000","real_id" =>6,),
"7"=>array("name_ru"=>"Берген","name_en"=>"Bergen","name_href" =>"no/population-of-bergen","count" =>"277 378","real_id" =>7,),
"8"=>array("name_ru"=>"Бускеруд","name_en"=>"Buskerud","name_href" =>"no/population-of-buskerud","count" =>"269 003","real_id" =>8,),
"9"=>array("name_ru"=>"Мёре-ог-Ромсдал","name_en"=>"Møre og Romsdal","name_href" =>"no/population-of-møre-og-romsdal","count" =>"259 404","real_id" =>9,),
"10"=>array("name_ru"=>"Нурланн","name_en"=>"Nordland","name_href" =>"no/population-of-nordland","count" =>"239 611","real_id" =>10,),
"11"=>array("name_ru"=>"Вестфолл","name_en"=>"Vestfold","name_href" =>"no/population-of-vestfold","count" =>"238 748","real_id" =>11,),
"12"=>array("name_ru"=>"Хедмарк","name_en"=>"Hedmark","name_href" =>"no/population-of-hedmark","count" =>"193 719","real_id" =>12,),
"13"=>array("name_ru"=>"Тронхейм","name_en"=>"Trondheim","name_href" =>"no/population-of-trondheim","count" =>"190 464","real_id" =>13,),
"14"=>array("name_ru"=>"Оппланн","name_en"=>"Oppland","name_href" =>"no/population-of-oppland","count" =>"187 254","real_id" =>14,),
"15"=>array("name_ru"=>"Вест-Агдер","name_en"=>"Vest-Agder","name_href" =>"no/population-of-vest-agder","count" =>"176 353","real_id" =>15,),
"16"=>array("name_ru"=>"Телемарк","name_en"=>"Telemark","name_href" =>"no/population-of-telemark","count" =>"170 902","real_id" =>16,),
"17"=>array("name_ru"=>"Тромс","name_en"=>"Troms","name_href" =>"no/population-of-troms","count" =>"160 418","real_id" =>17,),
"18"=>array("name_ru"=>"Нур-Трёнделаг","name_en"=>"Nord-Trondelag","name_href" =>"no/population-of-nord-trondelag","count" =>"134 443","real_id" =>18,),
"19"=>array("name_ru"=>"Ставангер","name_en"=>"Stavanger","name_href" =>"no/population-of-stavanger","count" =>"132 102","real_id" =>19,),
"20"=>array("name_ru"=>"Эуст-Агдер","name_en"=>"Aust-Agder","name_href" =>"no/population-of-aust-agder","count" =>"112 772","real_id" =>20,),
"21"=>array("name_ru"=>"Согн-ог-Фьюране","name_en"=>"Sogn og Fjordane","name_href" =>"no/population-of-sogn-og-fjordane","count" =>"108 700","real_id" =>21,),
"22"=>array("name_ru"=>"Саннвика","name_en"=>"Sandvika","name_href" =>"no/population-of-sandvika","count" =>"105 928","real_id" =>22,),
"23"=>array("name_ru"=>"Кристиансанн","name_en"=>"Kristiansand","name_href" =>"no/population-of-kristiansand","count" =>"80 748","real_id" =>23,),
"24"=>array("name_ru"=>"Фредрикстад","name_en"=>"Fredrikstad","name_href" =>"no/population-of-fredrikstad","count" =>"75 583","real_id" =>24,),
"25"=>array("name_ru"=>"Финнмарк","name_en"=>"Finnmark","name_href" =>"no/population-of-finnmark","count" =>"74 534","real_id" =>25,),
"26"=>array("name_ru"=>"Драммен","name_en"=>"Drammen","name_href" =>"no/population-of-drammen","count" =>"64 776","real_id" =>26,),
"27"=>array("name_ru"=>"Саннес","name_en"=>"Sandnes","name_href" =>"no/population-of-sandnes","count" =>"62 037","real_id" =>27,),
"28"=>array("name_ru"=>"Тромсё","name_en"=>"Tromso","name_href" =>"no/population-of-tromso","count" =>"59 590","real_id" =>28,),
"29"=>array("name_ru"=>"Сарпсборг","name_en"=>"Sarpsborg","name_href" =>"no/population-of-sarpsborg","count" =>"51 924","real_id" =>29,),
"30"=>array("name_ru"=>"Шиен","name_en"=>"Skien","name_href" =>"no/population-of-skien","count" =>"51 553","real_id" =>30,),
"31"=>array("name_ru"=>"Будё","name_en"=>"Bude","name_href" =>"no/population-of-bude","count" =>"46 495","real_id" =>31,),
"32"=>array("name_ru"=>"Олесунн","name_en"=>"Alesund","name_href" =>"no/population-of-alesund","count" =>"42 670","real_id" =>32,),
"33"=>array("name_ru"=>"Саннефьорд","name_en"=>"Sandefjord","name_href" =>"no/population-of-sandefjord","count" =>"42 333","real_id" =>33,),
"34"=>array("name_ru"=>"Ларвик","name_en"=>"Larvik","name_href" =>"no/population-of-larvik","count" =>"41 723","real_id" =>34,),
"35"=>array("name_ru"=>"Арендал","name_en"=>"Arendal","name_href" =>"no/population-of-arendal","count" =>"41 655","real_id" =>35,),
"36"=>array("name_ru"=>"Тёнсберг","name_en"=>"Tønsberg","name_href" =>"no/population-of-tønsberg","count" =>"39 021","real_id" =>36,),
"37"=>array("name_ru"=>"Порсгрунн","name_en"=>"Porsgrunn","name_href" =>"no/population-of-porsgrunn","count" =>"34 186","real_id" =>37,),
"38"=>array("name_ru"=>"Хёугесунн","name_en"=>"Haugesund","name_href" =>"no/population-of-haugesund","count" =>"32 956","real_id" =>38,),
"39"=>array("name_ru"=>"Мосс","name_en"=>"Moss","name_href" =>"no/population-of-moss","count" =>"30 988","real_id" =>39,),
"40"=>array("name_ru"=>"Халден","name_en"=>"Halden","name_href" =>"no/population-of-halden","count" =>"29 554","real_id" =>40,),
"41"=>array("name_ru"=>"Йёвик","name_en"=>"Gjøvik","name_href" =>"no/population-of-gjøvik","count" =>"28 672","real_id" =>41,),
"42"=>array("name_ru"=>"Хамар","name_en"=>"Hamar","name_href" =>"no/population-of-hamar","count" =>"28 217","real_id" =>42,),
"43"=>array("name_ru"=>"Хортен","name_en"=>"Horten","name_href" =>"no/population-of-horten","count" =>"26 734","real_id" =>43,),
"44"=>array("name_ru"=>"Лиллехаммер","name_en"=>"Lillehammer","name_href" =>"no/population-of-lillehammer","count" =>"26 206","real_id" =>44,),
"45"=>array("name_ru"=>"Молде","name_en"=>"Molde","name_href" =>"no/population-of-molde","count" =>"24 655","real_id" =>45,),
"46"=>array("name_ru"=>"Конгсберг","name_en"=>"Kongsberg","name_href" =>"no/population-of-kongsberg","count" =>"24 580","real_id" =>46,),
"47"=>array("name_ru"=>"Харстад","name_en"=>"Harstad","name_href" =>"no/population-of-harstad","count" =>"23 108","real_id" =>47,),
"48"=>array("name_ru"=>"Кристиансунн","name_en"=>"Kristiansund","name_href" =>"no/population-of-kristiansund","count" =>"22 661","real_id" =>48,),
"49"=>array("name_ru"=>"Стейнхьер","name_en"=>"Steinkjer","name_href" =>"no/population-of-steinkjer","count" =>"20 949","real_id" =>49,),
"50"=>array("name_ru"=>"Стьёрдал","name_en"=>"Stjoerdal","name_href" =>"no/population-of-stjoerdal","count" =>"20 616","real_id" =>50,),
"51"=>array("name_ru"=>"Гримстад","name_en"=>"Grimstad","name_href" =>"no/population-of-grimstad","count" =>"19 809","real_id" =>51,),
"52"=>array("name_ru"=>"Эльверум","name_en"=>"Elverum","name_href" =>"no/population-of-elverum","count" =>"19 465","real_id" =>52,),
"53"=>array("name_ru"=>"Левангер","name_en"=>"Levanger","name_href" =>"no/population-of-levanger","count" =>"18 355","real_id" =>53,),
"54"=>array("name_ru"=>"Нарвик","name_en"=>"Narvik","name_href" =>"no/population-of-narvik","count" =>"18 348","real_id" =>54,),
"55"=>array("name_ru"=>"Алта","name_en"=>"Alta","name_href" =>"no/population-of-alta","count" =>"18 347","real_id" =>55,),
"56"=>array("name_ru"=>"Му-и-Рана","name_en"=>"Mu-and-Wound","name_href" =>"no/population-of-mu-and-wound","count" =>"17 894","real_id" =>56,),
"57"=>array("name_ru"=>"Конгсвингер","name_en"=>"Kongsvinger","name_href" =>"no/population-of-kongsvinger","count" =>"17 361","real_id" =>57,),
"58"=>array("name_ru"=>"Йессхейм","name_en"=>"Jessheim","name_href" =>"no/population-of-jessheim","count" =>"15 349","real_id" =>58,),
"59"=>array("name_ru"=>"Хёнефосс","name_en"=>"Hønefoss","name_href" =>"no/population-of-hønefoss","count" =>"15 154","real_id" =>59,),
"60"=>array("name_ru"=>"Ашим","name_en"=>"Ashim","name_href" =>"no/population-of-ashim","count" =>"14 472","real_id" =>60,),
"61"=>array("name_ru"=>"Мандал","name_en"=>"Mandal","name_href" =>"no/population-of-mandal","count" =>"14 400","real_id" =>61,),
"62"=>array("name_ru"=>"Вердал","name_en"=>"Verdal","name_href" =>"no/population-of-verdal","count" =>"14 094","real_id" =>62,),
"63"=>array("name_ru"=>"Лиллестрём","name_en"=>"Lillestrom","name_href" =>"no/population-of-lillestrom","count" =>"14 000","real_id" =>63,),
"64"=>array("name_ru"=>"Намсус","name_en"=>"Namsos","name_href" =>"no/population-of-namsos","count" =>"12 607","real_id" =>64,),
"65"=>array("name_ru"=>"Дрёбак","name_en"=>"The drøbak","name_href" =>"no/population-of-the-drøbak","count" =>"12 239","real_id" =>65,),
"66"=>array("name_ru"=>"Нутодден","name_en"=>"Nutodden","name_href" =>"no/population-of-nutodden","count" =>"12 232","real_id" =>66,),
"67"=>array("name_ru"=>"Фёрде","name_en"=>"Førde","name_href" =>"no/population-of-førde","count" =>"11 650","real_id" =>67,),
"68"=>array("name_ru"=>"Крагерё","name_en"=>"Kragerø","name_href" =>"no/population-of-kragerø","count" =>"10 614","real_id" =>68,),
"69"=>array("name_ru"=>"Хаммерфест","name_en"=>"Hammerfest","name_href" =>"no/population-of-hammerfest","count" =>"10 109","real_id" =>69,),
"70"=>array("name_ru"=>"Холместранн","name_en"=>"Holmestrand","name_href" =>"no/population-of-holmestrand","count" =>"9 860","real_id" =>70,),
"71"=>array("name_ru"=>"Сортланд","name_en"=>"Sortland","name_href" =>"no/population-of-sortland","count" =>"9 732","real_id" =>71,),
"72"=>array("name_ru"=>"Мушёэн","name_en"=>"Mosjøen","name_href" =>"no/population-of-mosjøen","count" =>"9 629","real_id" =>72,),
"73"=>array("name_ru"=>"Брюне","name_en"=>"Brunet","name_href" =>"no/population-of-brunet","count" =>"9 627","real_id" =>73,),
"74"=>array("name_ru"=>"Фарсунн","name_en"=>"Farsund","name_href" =>"no/population-of-farsund","count" =>"9 392","real_id" =>74,),
"75"=>array("name_ru"=>"Лиллесанн","name_en"=>"Lillesand","name_href" =>"no/population-of-lillesand","count" =>"9 238","real_id" =>75,),
"76"=>array("name_ru"=>"Флеккефьорд","name_en"=>"Flekkefjord","name_href" =>"no/population-of-flekkefjord","count" =>"8 910","real_id" =>76,),
"77"=>array("name_ru"=>"Хокксунн","name_en"=>"In hokksund","name_href" =>"no/population-of-in-hokksund","count" =>"8 772","real_id" =>77,),
"78"=>array("name_ru"=>"Флурё","name_en"=>"Flour","name_href" =>"no/population-of-flour","count" =>"8 642","real_id" =>78,),
"79"=>array("name_ru"=>"Люнгдал","name_en"=>"Lyngdal","name_href" =>"no/population-of-lyngdal","count" =>"7 533","real_id" =>79,),
"80"=>array("name_ru"=>"Одда","name_en"=>"Odda","name_href" =>"no/population-of-odda","count" =>"7 107","real_id" =>80,),
"81"=>array("name_ru"=>"Йорпеланн","name_en"=>"Jorpeland","name_href" =>"no/population-of-jorpeland","count" =>"6 948","real_id" =>81,),
"82"=>array("name_ru"=>"Рисёр","name_en"=>"Riiser","name_href" =>"no/population-of-riiser","count" =>"6 888","real_id" =>82,),
"83"=>array("name_ru"=>"Оппдал","name_en"=>"Oppdal","name_href" =>"no/population-of-oppdal","count" =>"6 564","real_id" =>83,),
"84"=>array("name_ru"=>"Вадсё","name_en"=>"Vadsø","name_href" =>"no/population-of-vadsø","count" =>"6 125","real_id" =>84,),
"85"=>array("name_ru"=>"Рёрус","name_en"=>"Røros","name_href" =>"no/population-of-røros","count" =>"5 558","real_id" =>85,),
"86"=>array("name_ru"=>"Лангесунн","name_en"=>"Langesund","name_href" =>"no/population-of-langesund","count" =>"5 500","real_id" =>86,),
"87"=>array("name_ru"=>"Ульстейнвик","name_en"=>"Ulsteinvik","name_href" =>"no/population-of-ulsteinvik","count" =>"5 251","real_id" =>87,),
"88"=>array("name_ru"=>"Сёуда","name_en"=>"Saue","name_href" =>"no/population-of-saue","count" =>"4 734","real_id" =>88,),
"89"=>array("name_ru"=>"Брённёйсунн","name_en"=>"Brønnøysund","name_href" =>"no/population-of-brønnøysund","count" =>"4 506","real_id" =>89,),
"90"=>array("name_ru"=>"Киркенес","name_en"=>"Kirkenes","name_href" =>"no/population-of-kirkenes","count" =>"3 538","real_id" =>90,),
"91"=>array("name_ru"=>"Рьюкан","name_en"=>"Rjukan","name_href" =>"no/population-of-rjukan","count" =>"3 368","real_id" =>91,),
"92"=>array("name_ru"=>"Стокмаркнес","name_en"=>"Stokmarknes","name_href" =>"no/population-of-stokmarknes","count" =>"3 148","real_id" =>92,),
"93"=>array("name_ru"=>"Молёй","name_en"=>"Moles","name_href" =>"no/population-of-moles","count" =>"3 003","real_id" =>93,),
"94"=>array("name_ru"=>"Бревик","name_en"=>"Brevik","name_href" =>"no/population-of-brevik","count" =>"3 000","real_id" =>94,),
"95"=>array("name_ru"=>"Лекнес","name_en"=>"Leknes","name_href" =>"no/population-of-leknes","count" =>"2 661","real_id" =>95,),
"96"=>array("name_ru"=>"Хоннингсвог","name_en"=>"Honningsvåg","name_href" =>"no/population-of-honningsvåg","count" =>"2 436","real_id" =>96,),
"97"=>array("name_ru"=>"Ондалснес","name_en"=>"Åndalsnes","name_href" =>"no/population-of-åndalsnes","count" =>"2 231","real_id" =>97,),
"98"=>array("name_ru"=>"Свольвер","name_en"=>"Svolvær","name_href" =>"no/population-of-svolvær","count" =>"1 949","real_id" =>98,),
"99"=>array("name_ru"=>"Вардё","name_en"=>"Varde","name_href" =>"no/population-of-varde","count" =>"1 930","real_id" =>99,),
"100"=>array("name_ru"=>"Брекстад","name_en"=>"Brekstad","name_href" =>"no/population-of-brekstad","count" =>"1 888","real_id" =>100,),
"101"=>array("name_ru"=>"Утта","name_en"=>"Utta","name_href" =>"no/population-of-utta","count" =>"806","real_id" =>101,),
"102"=>array("name_ru"=>"Осло","name_en"=>"Oslo","name_href" =>"no/population-of-oslo","count" =>"673 469","real_id" =>102,),
"103"=>array("name_ru"=>"Акерсхус","name_en"=>"Akershus","name_href" =>"no/population-of-akershus","count" =>"566 399","real_id" =>103,),
"104"=>array("name_ru"=>"Хордаланн","name_en"=>"Hordaland","name_href" =>"no/population-of-hordaland","count" =>"498 135","real_id" =>104,),
"105"=>array("name_ru"=>"Ругаланн","name_en"=>"Rogaland","name_href" =>"no/population-of-rogaland","count" =>"452 159","real_id" =>105,),
"106"=>array("name_ru"=>"Сёр-Трёнделаг","name_en"=>"SOR-Trondelag","name_href" =>"no/population-of-sor-trondelag","count" =>"302 755","real_id" =>106,)
);

?>