<?php
//Новая Зеландия  44
$libnz = array ( 
"1"=>array("name_ru"=>"Окленд","name_en"=>"Auckland","name_href" => "nz/population-of-auckland","count" => "1 208 094","real_id" =>1,),
"2"=>array("name_ru"=>"Центральный Окленд","name_en"=>"Central Auckland","name_href" => "nz/population-of-central-auckland","count" => "395 982","real_id" =>2,),
"3"=>array("name_ru"=>"Южный Окленд","name_en"=>"South Auckland","name_href" => "nz/population-of-south-auckland","count" => "371 661","real_id" =>3,),
"4"=>array("name_ru"=>"Крайстчерч","name_en"=>"Christchurch","name_href" => "nz/population-of-christchurch","count" => "360 765","real_id" =>4,),
"5"=>array("name_ru"=>"Веллингтон","name_en"=>"Wellington","name_href" => "nz/population-of-wellington","count" => "360 624","real_id" =>5,),
"6"=>array("name_ru"=>"Манукау","name_en"=>"Manukau","name_href" => "nz/population-of-manukau","count" => "328 968","real_id" =>6,),
"7"=>array("name_ru"=>"Северный Окленд","name_en"=>"North Auckland","name_href" => "nz/population-of-north-auckland","count" => "248 112","real_id" =>7,),
"8"=>array("name_ru"=>"Норт-Шор","name_en"=>"North Shore","name_href" => "nz/population-of-north-shore","count" => "205 608","real_id" =>8,),
"9"=>array("name_ru"=>"Западный Окленд","name_en"=>"West Auckland","name_href" => "nz/population-of-west-auckland","count" => "192 339","real_id" =>9,),
"10"=>array("name_ru"=>"Уаитакере","name_en"=>"Waitakere","name_href" => "nz/population-of-waitakere","count" => "186 444","real_id" =>10,),
"11"=>array("name_ru"=>"Гамильтон","name_en"=>"Hamilton","name_href" => "nz/population-of-hamilton","count" => "184 905","real_id" =>11,),
"12"=>array("name_ru"=>"Данидин","name_en"=>"Dunedin","name_href" => "nz/population-of-dunedin","count" => "118 683","real_id" =>12,),
"13"=>array("name_ru"=>"Нейпир-Хейстингс","name_en"=>"Napier-Hastings","name_href" => "nz/population-of-napier-hastings","count" => "118 404","real_id" =>13,),
"14"=>array("name_ru"=>"Тауранга","name_en"=>"Tauranga","name_href" => "nz/population-of-tauranga","count" => "108 882","real_id" =>14,),
"15"=>array("name_ru"=>"Лоуэр-Хатт","name_en"=>"Lower Hutt","name_href" => "nz/population-of-lower-hutt","count" => "97 701","real_id" =>15,),
"16"=>array("name_ru"=>"Палмерстон-Норт","name_en"=>"Palmerston North","name_href" => "nz/population-of-palmerston-north","count" => "76 029","real_id" =>16,),
"17"=>array("name_ru"=>"Хейстингс","name_en"=>"Hastings","name_href" => "nz/population-of-hastings","count" => "62 118","real_id" =>17,),
"18"=>array("name_ru"=>"Нельсон","name_en"=>"Nelson","name_href" => "nz/population-of-nelson","count" => "56 367","real_id" =>18,),
"19"=>array("name_ru"=>"Нейпир","name_en"=>"Napier","name_href" => "nz/population-of-napier","count" => "56 286","real_id" =>19,),
"20"=>array("name_ru"=>"Роторуа","name_en"=>"Rotorua","name_href" => "nz/population-of-rotorua","count" => "53 766","real_id" =>20,),
"21"=>array("name_ru"=>"Инверкаргилл","name_en"=>"Invercargill","name_href" => "nz/population-of-invercargill","count" => "50 328","real_id" =>21,),
"22"=>array("name_ru"=>"Нью-Плимут","name_en"=>"New Plymouth","name_href" => "nz/population-of-new-plymouth","count" => "49 281","real_id" =>22,),
"23"=>array("name_ru"=>"Фангареи","name_en"=>"Whangarei","name_href" => "nz/population-of-whangarei","count" => "49 080","real_id" =>23,),
"24"=>array("name_ru"=>"Порируа","name_en"=>"Porirua","name_href" => "nz/population-of-porirua","count" => "48 546","real_id" =>24,),
"25"=>array("name_ru"=>"Уонгануи","name_en"=>"Wanganui","name_href" => "nz/population-of-wanganui","count" => "38 988","real_id" =>25,),
"26"=>array("name_ru"=>"Аппер-Хатт","name_en"=>"Upper Hutt","name_href" => "nz/population-of-upper-hutt","count" => "38 415","real_id" =>26,),
"27"=>array("name_ru"=>"Капити","name_en"=>"Kapiti","name_href" => "nz/population-of-kapiti","count" => "37 347","real_id" =>27,),
"28"=>array("name_ru"=>"Гисборн","name_en"=>"Gisborne","name_href" => "nz/population-of-gisborne","count" => "32 529","real_id" =>28,),
"29"=>array("name_ru"=>"Бленем","name_en"=>"Blenheim","name_href" => "nz/population-of-blenheim","count" => "28 527","real_id" =>29,),
"30"=>array("name_ru"=>"Тимару","name_en"=>"Timaru","name_href" => "nz/population-of-timaru","count" => "26 883","real_id" =>30,),
"31"=>array("name_ru"=>"Пукекохе","name_en"=>"Pukekohe","name_href" => "nz/population-of-pukekohe","count" => "22 518","real_id" =>31,),
"32"=>array("name_ru"=>"Таупо","name_en"=>"Taupo","name_href" => "nz/population-of-taupo","count" => "21 291","real_id" =>32,),
"33"=>array("name_ru"=>"Мастертон","name_en"=>"Masterton","name_href" => "nz/population-of-masterton","count" => "19 497","real_id" =>33,),
"34"=>array("name_ru"=>"Левин","name_en"=>"Levin","name_href" => "nz/population-of-levin","count" => "19 134","real_id" =>34,),
"35"=>array("name_ru"=>"Факатане","name_en"=>"Whakatane","name_href" => "nz/population-of-whakatane","count" => "18 207","real_id" =>35,),
"36"=>array("name_ru"=>"Ашбертон","name_en"=>"Ashburton","name_href" => "nz/population-of-ashburton","count" => "16 836","real_id" =>36,),
"37"=>array("name_ru"=>"Кеймбридж","name_en"=>"Cambridge","name_href" => "nz/population-of-cambridge","count" => "15 192","real_id" =>37,),
"38"=>array("name_ru"=>"Те-Авамуту","name_en"=>"Te Awamutu","name_href" => "nz/population-of-te-awamutu","count" => "14 454","real_id" =>38,),
"39"=>array("name_ru"=>"Филдинг","name_en"=>"Fielding","name_href" => "nz/population-of-fielding","count" => "13 887","real_id" =>39,),
"40"=>array("name_ru"=>"Токороа","name_en"=>"Tokoroa","name_href" => "nz/population-of-tokoroa","count" => "13 527","real_id" =>40,),
"41"=>array("name_ru"=>"Оамару","name_en"=>"Oamaru","name_href" => "nz/population-of-oamaru","count" => "12 681","real_id" =>41,),
"42"=>array("name_ru"=>"Хавера","name_en"=>"Khavera","name_href" => "nz/population-of-khavera","count" => "10 776","real_id" =>42,),
"43"=>array("name_ru"=>"Греймут","name_en"=>"Greymouth","name_href" => "nz/population-of-greymouth","count" => "9 672","real_id" =>43,),
"44"=>array("name_ru"=>"Гор","name_en"=>"Mountains","name_href" => "nz/population-of-mountains","count" => "9 648","real_id" =>44,),
"45"=>array("name_ru"=>"Окленд","name_en"=>"Auckland","name_href" => "nz/population-of-auckland","count" => "1 208 094","real_id" =>45,),
"46"=>array("name_ru"=>"Центральный Окленд","name_en"=>"Central Auckland","name_href" => "nz/population-of-central-auckland","count" => "395 982","real_id" =>46,),
"47"=>array("name_ru"=>"Южный Окленд","name_en"=>"South Auckland","name_href" => "nz/population-of-south-auckland","count" => "371 661","real_id" =>47,),
"48"=>array("name_ru"=>"Крайстчерч","name_en"=>"Christchurch","name_href" => "nz/population-of-christchurch","count" => "360 765","real_id" =>48,),
"49"=>array("name_ru"=>"Веллингтон","name_en"=>"Wellington","name_href" => "nz/population-of-wellington","count" => "360 624","real_id" =>49,)
);

?>