<?php
//Оман 43 
$libom = array ( 
"1"=>array("name_ru"=>"Сиб","name_en"=>"Sib","name_href" =>"om/population-of-sib","count" =>"286 121","real_id" =>1,),
"2"=>array("name_ru"=>"Матрах","name_en"=>"Matrah","name_href" =>"om/population-of-matrah","count" =>"214 901","real_id" =>2,),
"3"=>array("name_ru"=>"Баушар","name_en"=>"Bauer","name_href" =>"om/population-of-bauer","count" =>"190 930","real_id" =>3,),
"4"=>array("name_ru"=>"Салала","name_en"=>"Salalah","name_href" =>"om/population-of-salalah","count" =>"190 348","real_id" =>4,),
"5"=>array("name_ru"=>"Сувейк","name_en"=>"Suvak","name_href" =>"om/population-of-suvak","count" =>"128 165","real_id" =>5,),
"6"=>array("name_ru"=>"Сохар","name_en"=>"Sohar","name_href" =>"om/population-of-sohar","count" =>"125 508","real_id" =>6,),
"7"=>array("name_ru"=>"Ибри","name_en"=>"Ibri","name_href" =>"om/population-of-ibri","count" =>"118 674","real_id" =>7,),
"8"=>array("name_ru"=>"Сахм","name_en"=>"Sahm","name_href" =>"om/population-of-sahm","count" =>"105 513","real_id" =>8,),
"9"=>array("name_ru"=>"Барка","name_en"=>"Barca","name_href" =>"om/population-of-barca","count" =>"100 764","real_id" =>9,),
"10"=>array("name_ru"=>"Рустак","name_en"=>"Rustaq","name_href" =>"om/population-of-rustaq","count" =>"96 335","real_id" =>10,),
"11"=>array("name_ru"=>"Бурайми","name_en"=>"Buraimi","name_href" =>"om/population-of-buraimi","count" =>"91 569","real_id" =>11,),
"12"=>array("name_ru"=>"Сур","name_en"=>"Sur","name_href" =>"om/population-of-sur","count" =>"85 797","real_id" =>12,),
"13"=>array("name_ru"=>"Назва","name_en"=>"Title","name_href" =>"om/population-of-title","count" =>"84 749","real_id" =>13,),
"14"=>array("name_ru"=>"Мудейби","name_en"=>"Mugabe","name_href" =>"om/population-of-mugabe","count" =>"80 403","real_id" =>14,),
"15"=>array("name_ru"=>"Маснаа","name_en"=>"Masnaa","name_href" =>"om/population-of-masnaa","count" =>"79 124","real_id" =>15,),
"16"=>array("name_ru"=>"Бахла","name_en"=>"Bahla","name_href" =>"om/population-of-bahla","count" =>"64 997","real_id" =>16,),
"17"=>array("name_ru"=>"Бени-Бу-Али","name_en"=>"Beni-BU-Ali","name_href" =>"om/population-of-beni-bu-ali","count" =>"63 340","real_id" =>17,),
"18"=>array("name_ru"=>"Хабура","name_en"=>"Khabur","name_href" =>"om/population-of-khabur","count" =>"61 576","real_id" =>18,),
"19"=>array("name_ru"=>"Сумаил","name_en"=>"Sumail","name_href" =>"om/population-of-sumail","count" =>"57 997","real_id" =>19,),
"20"=>array("name_ru"=>"Шинас","name_en"=>"Shinas","name_href" =>"om/population-of-shinas","count" =>"55 949","real_id" =>20,),
"21"=>array("name_ru"=>"Курейят","name_en"=>"Qurayat","name_href" =>"om/population-of-qurayat","count" =>"51 389","real_id" =>21,),
"22"=>array("name_ru"=>"Амират","name_en"=>"Amirat","name_href" =>"om/population-of-amirat","count" =>"46 469","real_id" =>22,),
"23"=>array("name_ru"=>"Изки","name_en"=>"Izky","name_href" =>"om/population-of-izky","count" =>"41 418","real_id" =>23,),
"24"=>array("name_ru"=>"Биляд-Бени-Бу-Хасан","name_en"=>"To Bilad Beni BU Hassan","name_href" =>"om/population-of-to-bilad-beni-bu-hassan","count" =>"30 841","real_id" =>24,),
"25"=>array("name_ru"=>"Лива","name_en"=>"Liva","name_href" =>"om/population-of-liva","count" =>"29 918","real_id" =>25,),
"26"=>array("name_ru"=>"Ибра","name_en"=>"Ibra","name_href" =>"om/population-of-ibra","count" =>"29 060","real_id" =>26,),
"27"=>array("name_ru"=>"Маскат","name_en"=>"Muscat","name_href" =>"om/population-of-muscat","count" =>"25 785","real_id" =>27,),
"28"=>array("name_ru"=>"Бидбид","name_en"=>"Bidbid","name_href" =>"om/population-of-bidbid","count" =>"24 080","real_id" =>28,),
"29"=>array("name_ru"=>"Эль-Камиль-Валь-Вафи","name_en"=>"El-Camille-Val-Wafi","name_href" =>"om/population-of-el-camille-val-wafi","count" =>"23 958","real_id" =>29,),
"30"=>array("name_ru"=>"Бадийя","name_en"=>"Badia","name_href" =>"om/population-of-badia","count" =>"21 255","real_id" =>30,),
"31"=>array("name_ru"=>"Дима-Ват-Таиин","name_en"=>"Dima-Wat-Tain","name_href" =>"om/population-of-dima-wat-tain","count" =>"20 450","real_id" =>31,),
"32"=>array("name_ru"=>"Така","name_en"=>"Taka","name_href" =>"om/population-of-taka","count" =>"20 159","real_id" =>32,),
"33"=>array("name_ru"=>"Хамра","name_en"=>"Hamra","name_href" =>"om/population-of-hamra","count" =>"20 049","real_id" =>33,),
"34"=>array("name_ru"=>"Хасаб","name_en"=>"Khasab","name_href" =>"om/population-of-khasab","count" =>"19 887","real_id" =>34,),
"35"=>array("name_ru"=>"Адам","name_en"=>"Adam","name_href" =>"om/population-of-adam","count" =>"19 642","real_id" =>35,),
"36"=>array("name_ru"=>"Данк","name_en"=>"Dunk","name_href" =>"om/population-of-dunk","count" =>"19 047","real_id" =>36,),
"37"=>array("name_ru"=>"Нахаль","name_en"=>"Nahal","name_href" =>"om/population-of-nahal","count" =>"19 003","real_id" =>37,),
"38"=>array("name_ru"=>"Янкуль","name_en"=>"Yankul'","name_href" =>"om/population-of-yankul","count" =>"18 772","real_id" =>38,),
"39"=>array("name_ru"=>"Мирбат","name_en"=>"Mirbat","name_href" =>"om/population-of-mirbat","count" =>"17 305","real_id" =>39,),
"40"=>array("name_ru"=>"Кабиль","name_en"=>"The qabil","name_href" =>"om/population-of-the-qabil","count" =>"16 112","real_id" =>40,),
"41"=>array("name_ru"=>"Манах","name_en"=>"Manah","name_href" =>"om/population-of-manah","count" =>"14 632","real_id" =>41,),
"42"=>array("name_ru"=>"Вади-Эль-Маавиль","name_en"=>"Wadi El Mavil","name_href" =>"om/population-of-wadi-el-mavil","count" =>"13 136","real_id" =>42,),
"43"=>array("name_ru"=>"Аваби","name_en"=>"Awabi","name_href" =>"om/population-of-awabi","count" =>"12 151","real_id" =>43,),
"44"=>array("name_ru"=>"Сиб","name_en"=>"Sib","name_href" =>"om/population-of-sib","count" =>"286 121","real_id" =>44,),
"45"=>array("name_ru"=>"Матрах","name_en"=>"Matrah","name_href" =>"om/population-of-matrah","count" =>"214 901","real_id" =>45,),
"46"=>array("name_ru"=>"Баушар","name_en"=>"Bauer","name_href" =>"om/population-of-bauer","count" =>"190 930","real_id" =>46,),
"47"=>array("name_ru"=>"Салала","name_en"=>"Salalah","name_href" =>"om/population-of-salalah","count" =>"190 348","real_id" =>47,),
"48"=>array("name_ru"=>"Сувейк","name_en"=>"Suvak","name_href" =>"om/population-of-suvak","count" =>"128 165","real_id" =>48,)
);

?>