<?php
//Перу 80 
$libpe = array ( 
"1"=>array("name_ru"=>"Лима","name_en"=>"Lima","name_href" => "pe/population-of-lima","count" => "8 486 866","real_id" =>1,),
"2"=>array("name_ru"=>"Арекипа","name_en"=>"Arequipa","name_href" => "pe/population-of-arequipa","count" => "805 150","real_id" =>2,),
"3"=>array("name_ru"=>"Трухильо","name_en"=>"Trujillo","name_href" => "pe/population-of-trujillo","count" => "709 566","real_id" =>3,),
"4"=>array("name_ru"=>"Чиклайо","name_en"=>"Chiclayo","name_href" => "pe/population-of-chiclayo","count" => "526 010","real_id" =>4,),
"5"=>array("name_ru"=>"Пьюра","name_en"=>"Piura","name_href" => "pe/population-of-piura","count" => "421 648","real_id" =>5,),
"6"=>array("name_ru"=>"Икитос","name_en"=>"Iquitos","name_href" => "pe/population-of-iquitos","count" => "360 314","real_id" =>6,),
"7"=>array("name_ru"=>"Куско","name_en"=>"Cusco","name_href" => "pe/population-of-cusco","count" => "348 935","real_id" =>7,),
"8"=>array("name_ru"=>"Уанкайо","name_en"=>"Huancayo","name_href" => "pe/population-of-huancayo","count" => "336 349","real_id" =>8,),
"9"=>array("name_ru"=>"Чимботе","name_en"=>"Chimbote","name_href" => "pe/population-of-chimbote","count" => "320 240","real_id" =>9,),
"10"=>array("name_ru"=>"Пукальпа","name_en"=>"Pucallpa","name_href" => "pe/population-of-pucallpa","count" => "270 780","real_id" =>10,),
"11"=>array("name_ru"=>"Такна","name_en"=>"Tacna","name_href" => "pe/population-of-tacna","count" => "242 451","real_id" =>11,),
"12"=>array("name_ru"=>"Ика","name_en"=>"IKA","name_href" => "pe/population-of-ika","count" => "227 552","real_id" =>12,),
"13"=>array("name_ru"=>"Хулиака","name_en"=>"Juliaca","name_href" => "pe/population-of-juliaca","count" => "216 716","real_id" =>13,),
"14"=>array("name_ru"=>"Сульяна","name_en"=>"Sullana","name_href" => "pe/population-of-sullana","count" => "170 302","real_id" =>14,),
"15"=>array("name_ru"=>"Кахамарка","name_en"=>"Cajamarca","name_href" => "pe/population-of-cajamarca","count" => "161 215","real_id" =>15,),
"16"=>array("name_ru"=>"Чинча-Альта","name_en"=>"Chincha Alta","name_href" => "pe/population-of-chincha-alta","count" => "153 598","real_id" =>16,),
"17"=>array("name_ru"=>"Аякучо","name_en"=>"Ayacucho","name_href" => "pe/population-of-ayacucho","count" => "149 391","real_id" =>17,),
"18"=>array("name_ru"=>"Уануко","name_en"=>"Huanuco","name_href" => "pe/population-of-huanuco","count" => "146 750","real_id" =>18,),
"19"=>array("name_ru"=>"Уачо","name_en"=>"Huacho","name_href" => "pe/population-of-huacho","count" => "133 642","real_id" =>19,),
"20"=>array("name_ru"=>"Пуно","name_en"=>"Puno","name_href" => "pe/population-of-puno","count" => "119 116","real_id" =>20,),
"21"=>array("name_ru"=>"Тарапото","name_en"=>"Tarapoto","name_href" => "pe/population-of-tarapoto","count" => "115 168","real_id" =>21,),
"22"=>array("name_ru"=>"Уарас","name_en"=>"Huaraz","name_href" => "pe/population-of-huaraz","count" => "100 931","real_id" =>22,),
"23"=>array("name_ru"=>"Тумбес","name_en"=>"Tumbes","name_href" => "pe/population-of-tumbes","count" => "94 751","real_id" =>23,),
"24"=>array("name_ru"=>"Талара","name_en"=>"Talara","name_href" => "pe/population-of-talara","count" => "87 622","real_id" =>24,),
"25"=>array("name_ru"=>"Уараль","name_en"=>"Wral","name_href" => "pe/population-of-wral","count" => "79 001","real_id" =>25,),
"26"=>array("name_ru"=>"Пайта","name_en"=>"Paita","name_href" => "pe/population-of-paita","count" => "72 510","real_id" =>26,),
"27"=>array("name_ru"=>"Хаэн","name_en"=>"Jaen","name_href" => "pe/population-of-jaen","count" => "71 565","real_id" =>27,),
"28"=>array("name_ru"=>"Серро-де-Паско","name_en"=>"Cerro de Pasco","name_href" => "pe/population-of-cerro-de-pasco","count" => "66 860","real_id" =>28,),
"29"=>array("name_ru"=>"Ило","name_en"=>"ILO","name_href" => "pe/population-of-ilo","count" => "58 649","real_id" =>29,),
"30"=>array("name_ru"=>"Пуэрто-Мальдональдо","name_en"=>"Puerto Maldonado","name_href" => "pe/population-of-puerto-maldonado","count" => "56 382","real_id" =>30,),
"31"=>array("name_ru"=>"Чулуканас","name_en"=>"Chulucanas","name_href" => "pe/population-of-chulucanas","count" => "55 183","real_id" =>31,),
"32"=>array("name_ru"=>"Писко","name_en"=>"Pisco","name_href" => "pe/population-of-pisco","count" => "54 677","real_id" =>32,),
"33"=>array("name_ru"=>"Барранка","name_en"=>"Barranca","name_href" => "pe/population-of-barranca","count" => "54 463","real_id" =>33,),
"34"=>array("name_ru"=>"Могегуа","name_en"=>"Mohega","name_href" => "pe/population-of-mohega","count" => "52 430","real_id" =>34,),
"35"=>array("name_ru"=>"Абанкай","name_en"=>"Abancay","name_href" => "pe/population-of-abancay","count" => "51 462","real_id" =>35,),
"36"=>array("name_ru"=>"Тинго-Мария","name_en"=>"Tingo Maria","name_href" => "pe/population-of-tingo-maria","count" => "50 414","real_id" =>36,),
"37"=>array("name_ru"=>"Юримагуас","name_en"=>"Yurimaguas","name_href" => "pe/population-of-yurimaguas","count" => "49 087","real_id" =>37,),
"38"=>array("name_ru"=>"Ламбаеке","name_en"=>"Lambayeque","name_href" => "pe/population-of-lambayeque","count" => "48 273","real_id" =>38,),
"39"=>array("name_ru"=>"Чанкай","name_en"=>"The Cankaya","name_href" => "pe/population-of-the-cankaya","count" => "44 862","real_id" =>39,),
"40"=>array("name_ru"=>"Тарма","name_en"=>"Tarma","name_href" => "pe/population-of-tarma","count" => "43 169","real_id" =>40,),
"41"=>array("name_ru"=>"Мойобамба","name_en"=>"Moyobamba","name_href" => "pe/population-of-moyobamba","count" => "42 690","real_id" =>41,),
"42"=>array("name_ru"=>"Сикуани","name_en"=>"Sicuani","name_href" => "pe/population-of-sicuani","count" => "42 551","real_id" =>42,),
"43"=>array("name_ru"=>"Чепен","name_en"=>"Cepen","name_href" => "pe/population-of-cepen","count" => "41 358","real_id" =>43,),
"44"=>array("name_ru"=>"Уанкавелика","name_en"=>"Huancavelica","name_href" => "pe/population-of-huancavelica","count" => "41 331","real_id" =>44,),
"45"=>array("name_ru"=>"Сан-Висенте-де-Каньете","name_en"=>"San Vicente de Cañete","name_href" => "pe/population-of-san-vicente-de-cañete","count" => "37 512","real_id" =>45,),
"46"=>array("name_ru"=>"Виру","name_en"=>"Viru","name_href" => "pe/population-of-viru","count" => "36 029","real_id" =>46,),
"47"=>array("name_ru"=>"Ла-Уньон","name_en"=>"La Unión","name_href" => "pe/population-of-la-unión","count" => "35 411","real_id" =>47,),
"48"=>array("name_ru"=>"Империал","name_en"=>"Imperial","name_href" => "pe/population-of-imperial","count" => "33 728","real_id" =>48,),
"49"=>array("name_ru"=>"Гуаделупе","name_en"=>"Guadalupe","name_href" => "pe/population-of-guadalupe","count" => "33 422","real_id" =>49,),
"50"=>array("name_ru"=>"Сечура","name_en"=>"Secure","name_href" => "pe/population-of-secure","count" => "32 144","real_id" =>50,),
"51"=>array("name_ru"=>"Ферреньафе","name_en"=>"Ferrenafe","name_href" => "pe/population-of-ferrenafe","count" => "31 777","real_id" =>51,),
"52"=>array("name_ru"=>"Ла-Арена","name_en"=>"La Arena","name_href" => "pe/population-of-la-arena","count" => "31 494","real_id" =>52,),
"53"=>array("name_ru"=>"Уамачуко","name_en"=>"Huamachuco","name_href" => "pe/population-of-huamachuco","count" => "29 970","real_id" =>53,),
"54"=>array("name_ru"=>"Багуа-Гранде","name_en"=>"Bagua Grande","name_href" => "pe/population-of-bagua-grande","count" => "29 507","real_id" =>54,),
"55"=>array("name_ru"=>"Нуэва-Кахамарка","name_en"=>"Nueva Cajamarca","name_href" => "pe/population-of-nueva-cajamarca","count" => "28 874","real_id" =>55,),
"56"=>array("name_ru"=>"Каза-Гранде","name_en"=>"Casa Grande","name_href" => "pe/population-of-casa-grande","count" => "28 282","real_id" =>56,),
"57"=>array("name_ru"=>"Уанта","name_en"=>"The huanta","name_href" => "pe/population-of-the-huanta","count" => "27 966","real_id" =>57,),
"58"=>array("name_ru"=>"Парене","name_en"=>"The guy","name_href" => "pe/population-of-the-guy","count" => "27 463","real_id" =>58,),
"59"=>array("name_ru"=>"Андауайлас","name_en"=>"Andahuaylas","name_href" => "pe/population-of-andahuaylas","count" => "27 157","real_id" =>59,),
"60"=>array("name_ru"=>"Уаура","name_en"=>"Aura","name_href" => "pe/population-of-aura","count" => "26 937","real_id" =>60,),
"61"=>array("name_ru"=>"Кильябамба","name_en"=>"Quillabamba","name_href" => "pe/population-of-quillabamba","count" => "26 573","real_id" =>61,),
"62"=>array("name_ru"=>"Пичанаки","name_en"=>"Pichanaki","name_href" => "pe/population-of-pichanaki","count" => "26 335","real_id" =>62,),
"63"=>array("name_ru"=>"Пакасмайо","name_en"=>"Pacasmayo","name_href" => "pe/population-of-pacasmayo","count" => "26 105","real_id" =>63,),
"64"=>array("name_ru"=>"Мала","name_en"=>"Small","name_href" => "pe/population-of-small","count" => "25 631","real_id" =>64,),
"65"=>array("name_ru"=>"Багуа","name_en"=>"Bagua","name_href" => "pe/population-of-bagua","count" => "25 595","real_id" =>65,),
"66"=>array("name_ru"=>"Туман","name_en"=>"Fog","name_href" => "pe/population-of-fog","count" => "25 541","real_id" =>66,),
"67"=>array("name_ru"=>"Касма","name_en"=>"Casma","name_href" => "pe/population-of-casma","count" => "24 842","real_id" =>67,),
"68"=>array("name_ru"=>"Махес","name_en"=>"Makes","name_href" => "pe/population-of-makes","count" => "24 776","real_id" =>68,),
"69"=>array("name_ru"=>"Эспинар","name_en"=>"Espinar","name_href" => "pe/population-of-espinar","count" => "24 566","real_id" =>69,),
"70"=>array("name_ru"=>"Маркавелика","name_en"=>"Markaverich","name_href" => "pe/population-of-markaverich","count" => "24 462","real_id" =>70,),
"71"=>array("name_ru"=>"Хуанхуи","name_en"=>"Chuanhui","name_href" => "pe/population-of-chuanhui","count" => "24 085","real_id" =>71,),
"72"=>array("name_ru"=>"Наска","name_en"=>"Nazca","name_href" => "pe/population-of-nazca","count" => "23 710","real_id" =>72,),
"73"=>array("name_ru"=>"Чачапойас","name_en"=>"Chachapoyas","name_href" => "pe/population-of-chachapoyas","count" => "23 202","real_id" =>73,),
"74"=>array("name_ru"=>"Мольендо","name_en"=>"Mollendo","name_href" => "pe/population-of-mollendo","count" => "22 789","real_id" =>74,),
"75"=>array("name_ru"=>"Монсефу","name_en"=>"Moncef","name_href" => "pe/population-of-moncef","count" => "22 165","real_id" =>75,),
"76"=>array("name_ru"=>"Илаве","name_en"=>"Ilawa","name_href" => "pe/population-of-ilawa","count" => "22 153","real_id" =>76,),
"77"=>array("name_ru"=>"Рекена","name_en"=>"Requena","name_href" => "pe/population-of-requena","count" => "22 055","real_id" =>77,),
"78"=>array("name_ru"=>"Керекотильо","name_en"=>"Erectile","name_href" => "pe/population-of-erectile","count" => "21 916","real_id" =>78,),
"79"=>array("name_ru"=>"Сатипо","name_en"=>"Of satipo","name_href" => "pe/population-of-of-satipo","count" => "21 894","real_id" =>79,),
"80"=>array("name_ru"=>"Чанчамайо","name_en"=>"Chanchamayo","name_href" => "pe/population-of-chanchamayo","count" => "21 885","real_id" =>80,),
"81"=>array("name_ru"=>"Лима","name_en"=>"Lima","name_href" => "pe/population-of-lima","count" => "8 486 866","real_id" =>81,),
"82"=>array("name_ru"=>"Арекипа","name_en"=>"Arequipa","name_href" => "pe/population-of-arequipa","count" => "805 150","real_id" =>82,),
"83"=>array("name_ru"=>"Трухильо","name_en"=>"Trujillo","name_href" => "pe/population-of-trujillo","count" => "709 566","real_id" =>83,),
"84"=>array("name_ru"=>"Чиклайо","name_en"=>"Chiclayo","name_href" => "pe/population-of-chiclayo","count" => "526 010","real_id" =>84,),
"85"=>array("name_ru"=>"Пьюра","name_en"=>"Piura","name_href" => "pe/population-of-piura","count" => "421 648","real_id" =>85,)
);

?>