<?php
//Пакистан 200 
$libpk = array ( 
"1"=>array("name_ru"=>"Карачи","name_en"=>"Karachi","name_href" => "pk/population-of-karachi","count" => "11 234 942","real_id" =>1,),
"2"=>array("name_ru"=>"Лахор","name_en"=>"Lahore","name_href" => "pk/population-of-lahore","count" => "6 761 251","real_id" =>2,),
"3"=>array("name_ru"=>"Фейсалабад","name_en"=>"Faisalabad","name_href" => "pk/population-of-faisalabad","count" => "2 640 697","real_id" =>3,),
"4"=>array("name_ru"=>"Равалпинди","name_en"=>"Rawalpindi","name_href" => "pk/population-of-rawalpindi","count" => "1 853 175","real_id" =>4,),
"5"=>array("name_ru"=>"Мултан","name_en"=>"Multan","name_href" => "pk/population-of-multan","count" => "1 573 991","real_id" =>5,),
"6"=>array("name_ru"=>"Гуджранвала","name_en"=>"Gujranwala","name_href" => "pk/population-of-gujranwala","count" => "1 488 711","real_id" =>6,),
"7"=>array("name_ru"=>"Хайдарабад","name_en"=>"Hyderabad","name_href" => "pk/population-of-hyderabad","count" => "1 403 786","real_id" =>7,),
"8"=>array("name_ru"=>"Пешавар","name_en"=>"Peshawar","name_href" => "pk/population-of-peshawar","count" => "1 326 148","real_id" =>8,),
"9"=>array("name_ru"=>"Исламабад","name_en"=>"Islamabad","name_href" => "pk/population-of-islamabad","count" => "1 134 944","real_id" =>9,),
"10"=>array("name_ru"=>"Кветта","name_en"=>"Quetta","name_href" => "pk/population-of-quetta","count" => "865 136","real_id" =>10,),
"11"=>array("name_ru"=>"Саргодха","name_en"=>"Sargodha","name_href" => "pk/population-of-sargodha","count" => "602 631","real_id" =>11,),
"12"=>array("name_ru"=>"Сиялкот","name_en"=>"Sialkot","name_href" => "pk/population-of-sialkot","count" => "554 075","real_id" =>12,),
"13"=>array("name_ru"=>"Бахавалпур","name_en"=>"Bahawalpur","name_href" => "pk/population-of-bahawalpur","count" => "536 845","real_id" =>13,),
"14"=>array("name_ru"=>"Суккур","name_en"=>"Sukkur","name_href" => "pk/population-of-sukkur","count" => "403 671","real_id" =>14,),
"15"=>array("name_ru"=>"Джанг","name_en"=>"Jhang","name_href" => "pk/population-of-jhang","count" => "385 637","real_id" =>15,),
"16"=>array("name_ru"=>"Шекхупура","name_en"=>"Sheikhupura","name_href" => "pk/population-of-sheikhupura","count" => "368 413","real_id" =>16,),
"17"=>array("name_ru"=>"Мардан","name_en"=>"Mardan","name_href" => "pk/population-of-mardan","count" => "331 837","real_id" =>17,),
"18"=>array("name_ru"=>"Гуджрат","name_en"=>"Gujrat","name_href" => "pk/population-of-gujrat","count" => "330 987","real_id" =>18,),
"19"=>array("name_ru"=>"Ларкана","name_en"=>"Larkana","name_href" => "pk/population-of-larkana","count" => "325 153","real_id" =>19,),
"20"=>array("name_ru"=>"Касур","name_en"=>"Kasur","name_href" => "pk/population-of-kasur","count" => "322 481","real_id" =>20,),
"21"=>array("name_ru"=>"Рахимъярхан","name_en"=>"Rahim Yar Khan","name_href" => "pk/population-of-rahim-yar-khan","count" => "306 990","real_id" =>21,),
"22"=>array("name_ru"=>"Сахивал","name_en"=>"Sahiwal","name_href" => "pk/population-of-sahiwal","count" => "274 444","real_id" =>22,),
"23"=>array("name_ru"=>"Окара","name_en"=>"Okara","name_href" => "pk/population-of-okara","count" => "265 291","real_id" =>23,),
"24"=>array("name_ru"=>"Вах","name_en"=>"Wah","name_href" => "pk/population-of-wah","count" => "260 842","real_id" =>24,),
"25"=>array("name_ru"=>"Дера-Гази-Хан","name_en"=>"Dera Ghazi Khan","name_href" => "pk/population-of-dera-ghazi-khan","count" => "247 327","real_id" =>25,),
"26"=>array("name_ru"=>"Мингора","name_en"=>"Mingora","name_href" => "pk/population-of-mingora","count" => "235 417","real_id" =>26,),
"27"=>array("name_ru"=>"Чиниот","name_en"=>"Chiniot","name_href" => "pk/population-of-chiniot","count" => "222 525","real_id" =>27,),
"28"=>array("name_ru"=>"Мирпур-Хас","name_en"=>"Mirpur Khas","name_href" => "pk/population-of-mirpur-khas","count" => "221 913","real_id" =>28,),
"29"=>array("name_ru"=>"Навабшах","name_en"=>"Nawabshah","name_href" => "pk/population-of-nawabshah","count" => "220 283","real_id" =>29,),
"30"=>array("name_ru"=>"Камоке","name_en"=>"Kamoke","name_href" => "pk/population-of-kamoke","count" => "198 472","real_id" =>30,),
"31"=>array("name_ru"=>"Буревала","name_en"=>"Burewala","name_href" => "pk/population-of-burewala","count" => "196 991","real_id" =>31,),
"32"=>array("name_ru"=>"Джелам","name_en"=>"Jhelum","name_href" => "pk/population-of-jhelum","count" => "191 719","real_id" =>32,),
"33"=>array("name_ru"=>"Садикабад","name_en"=>"Sadiqabad","name_href" => "pk/population-of-sadiqabad","count" => "186 017","real_id" =>33,),
"34"=>array("name_ru"=>"Ханевал","name_en"=>"Khanewal","name_href" => "pk/population-of-khanewal","count" => "174 782","real_id" =>34,),
"35"=>array("name_ru"=>"Хафизабад","name_en"=>"Hafizabad","name_href" => "pk/population-of-hafizabad","count" => "171 172","real_id" =>35,),
"36"=>array("name_ru"=>"Кохат","name_en"=>"Kohat","name_href" => "pk/population-of-kohat","count" => "169 033","real_id" =>36,),
"37"=>array("name_ru"=>"Джейкобабад","name_en"=>"Jacobabad","name_href" => "pk/population-of-jacobabad","count" => "165 694","real_id" =>37,),
"38"=>array("name_ru"=>"Шикарпур","name_en"=>"Shikarpur","name_href" => "pk/population-of-shikarpur","count" => "160 312","real_id" =>38,),
"39"=>array("name_ru"=>"Музаффаргарх","name_en"=>"Muzaffargarh","name_href" => "pk/population-of-muzaffargarh","count" => "159 900","real_id" =>39,),
"40"=>array("name_ru"=>"Ханпур","name_en"=>"Khanpur","name_href" => "pk/population-of-khanpur","count" => "154 804","real_id" =>40,),
"41"=>array("name_ru"=>"Годжра","name_en"=>"Gojra","name_href" => "pk/population-of-gojra","count" => "151 127","real_id" =>41,),
"42"=>array("name_ru"=>"Бахавалнагар","name_en"=>"Bahawalnagar","name_href" => "pk/population-of-bahawalnagar","count" => "144 127","real_id" =>42,),
"43"=>array("name_ru"=>"Абботтабад","name_en"=>"Abbottabad","name_href" => "pk/population-of-abbottabad","count" => "143 028","real_id" =>43,),
"44"=>array("name_ru"=>"Муридке","name_en"=>"Muridke","name_href" => "pk/population-of-muridke","count" => "142 728","real_id" =>44,),
"45"=>array("name_ru"=>"Хуздар","name_en"=>"Khuzdar","name_href" => "pk/population-of-khuzdar","count" => "142 460","real_id" =>45,),
"46"=>array("name_ru"=>"Пакпаттан","name_en"=>"Pakpattan","name_href" => "pk/population-of-pakpattan","count" => "141 694","real_id" =>46,),
"47"=>array("name_ru"=>"Джаранвала","name_en"=>"Jaranwala","name_href" => "pk/population-of-jaranwala","count" => "135 801","real_id" =>47,),
"48"=>array("name_ru"=>"Чиштиан-Манди","name_en"=>"Chishtian","name_href" => "pk/population-of-chishtian","count" => "133 633","real_id" =>48,),
"49"=>array("name_ru"=>"Даска","name_en"=>"Daska","name_href" => "pk/population-of-daska","count" => "133 424","real_id" =>49,),
"50"=>array("name_ru"=>"Манди-Бахауддин","name_en"=>"Mandi Bahauddin","name_href" => "pk/population-of-mandi-bahauddin","count" => "127 956","real_id" =>50,),
"51"=>array("name_ru"=>"Ахмадпур-Ист","name_en"=>"Ahmadpur East","name_href" => "pk/population-of-ahmadpur-east","count" => "126 236","real_id" =>51,),
"52"=>array("name_ru"=>"Камалия","name_en"=>"Kamalia","name_href" => "pk/population-of-kamalia","count" => "125 262","real_id" =>52,),
"53"=>array("name_ru"=>"Тандо-Адам","name_en"=>"Tando Adam","name_href" => "pk/population-of-tando-adam","count" => "124 347","real_id" =>53,),
"54"=>array("name_ru"=>"Хайрпур","name_en"=>"Khairpur","name_href" => "pk/population-of-khairpur","count" => "122 933","real_id" =>54,),
"55"=>array("name_ru"=>"Дера-Исмаил-Хан","name_en"=>"Dera Ismail Khan","name_href" => "pk/population-of-dera-ismail-khan","count" => "121 922","real_id" =>55,),
"56"=>array("name_ru"=>"Вихари","name_en"=>"Vehari","name_href" => "pk/population-of-vehari","count" => "121 375","real_id" =>56,),
"57"=>array("name_ru"=>"Наушера","name_en"=>"Nowshera","name_href" => "pk/population-of-nowshera","count" => "120 668","real_id" =>57,),
"58"=>array("name_ru"=>"Даду","name_en"=>"Dadu, Pakistan","name_href" => "pk/population-of-dadu,-pakistan","count" => "118 587","real_id" =>58,),
"59"=>array("name_ru"=>"Вазирабад","name_en"=>"Wazirabad","name_href" => "pk/population-of-wazirabad","count" => "117 850","real_id" =>59,),
"60"=>array("name_ru"=>"Хушаб","name_en"=>"Khushab","name_href" => "pk/population-of-khushab","count" => "114 750","real_id" =>60,),
"61"=>array("name_ru"=>"Чарсадда","name_en"=>"Charsadda","name_href" => "pk/population-of-charsadda","count" => "113 691","real_id" =>61,),
"62"=>array("name_ru"=>"Сваби","name_en"=>"Swabi","name_href" => "pk/population-of-swabi","count" => "106 543","real_id" =>62,),
"63"=>array("name_ru"=>"Чаквал","name_en"=>"Chakwal","name_href" => "pk/population-of-chakwal","count" => "105 977","real_id" =>63,),
"64"=>array("name_ru"=>"Миянвали","name_en"=>"Mianwali","name_href" => "pk/population-of-mianwali","count" => "105 157","real_id" =>64,),
"65"=>array("name_ru"=>"Турбат","name_en"=>"Turbat","name_href" => "pk/population-of-turbat","count" => "103 952","real_id" =>65,),
"66"=>array("name_ru"=>"Тандо-Аллах-Яр","name_en"=>"Tando Allahyar","name_href" => "pk/population-of-tando-allahyar","count" => "103 526","real_id" =>66,),
"67"=>array("name_ru"=>"Кот-Адду","name_en"=>"Kot Adu","name_href" => "pk/population-of-kot-adu","count" => "103 918","real_id" =>67,),
"68"=>array("name_ru"=>"Чаман","name_en"=>"Chaman","name_href" => "pk/population-of-chaman","count" => "100 235","real_id" =>68,),
"69"=>array("name_ru"=>"Хуб","name_en"=>"Hub, Balochistan","name_href" => "pk/population-of-hub,-balochistan","count" => "97 602","real_id" =>69,),
"70"=>array("name_ru"=>"Арифвала","name_en"=>"Arifwala","name_href" => "pk/population-of-arifwala","count" => "95 161","real_id" =>70,),
"71"=>array("name_ru"=>"Чичаватни","name_en"=>"Chichawatni","name_href" => "pk/population-of-chichawatni","count" => "94 989","real_id" =>71,),
"72"=>array("name_ru"=>"Кхариян","name_en"=>"Kharian","name_href" => "pk/population-of-kharian","count" => "94 501","real_id" =>72,),
"73"=>array("name_ru"=>"Таксила","name_en"=>"Taxila","name_href" => "pk/population-of-taxila","count" => "94 341","real_id" =>73,),
"74"=>array("name_ru"=>"Леях","name_en"=>"Layyah","name_href" => "pk/population-of-layyah","count" => "92 374","real_id" =>74,),
"75"=>array("name_ru"=>"Хасилпур","name_en"=>"Hasilpur","name_href" => "pk/population-of-hasilpur","count" => "91 553","real_id" =>75,),
"76"=>array("name_ru"=>"Атток","name_en"=>"Attock","name_href" => "pk/population-of-attock","count" => "91 475","real_id" =>76,),
"77"=>array("name_ru"=>"Джалалпур","name_en"=>"Jalalpur","name_href" => "pk/population-of-jalalpur","count" => "90 351","real_id" =>77,),
"78"=>array("name_ru"=>"Бхаккар","name_en"=>"Bhakkar","name_href" => "pk/population-of-bhakkar","count" => "89 839","real_id" =>78,),
"79"=>array("name_ru"=>"Лодхран","name_en"=>"Lodhran","name_href" => "pk/population-of-lodhran","count" => "85 381","real_id" =>79,),
"80"=>array("name_ru"=>"Миян-Чаннун","name_en"=>"Mian Channu","name_href" => "pk/population-of-mian-channu","count" => "84 473","real_id" =>80,),
"81"=>array("name_ru"=>"Шоркот","name_en"=>"Shorkot","name_href" => "pk/population-of-shorkot","count" => "83 374","real_id" =>81,),
"82"=>array("name_ru"=>"Харунабад","name_en"=>"Harunabad","name_href" => "pk/population-of-harunabad","count" => "82 423","real_id" =>82,),
"83"=>array("name_ru"=>"Бхалвал","name_en"=>"Bhalwal","name_href" => "pk/population-of-bhalwal","count" => "80 274","real_id" =>83,),
"84"=>array("name_ru"=>"Кандхот","name_en"=>"Kandhkot","name_href" => "pk/population-of-kandhkot","count" => "80 273","real_id" =>84,),
"85"=>array("name_ru"=>"Лаламуса","name_en"=>"Lalamusa","name_href" => "pk/population-of-lalamusa","count" => "78 193","real_id" =>85,),
"86"=>array("name_ru"=>"Кот-Абдул-Малик","name_en"=>"Kot Abdul Malik","name_href" => "pk/population-of-kot-abdul-malik","count" => "77 330","real_id" =>86,),
"87"=>array("name_ru"=>"Тоба-Тек-Сингх","name_en"=>"Toba Tek Singh","name_href" => "pk/population-of-toba-tek-singh","count" => "77 117","real_id" =>87,),
"88"=>array("name_ru"=>"Паттоки","name_en"=>"Pattoki","name_href" => "pk/population-of-pattoki","count" => "76 588","real_id" =>88,),
"89"=>array("name_ru"=>"Кахрор-Пакка","name_en"=>"Kahror Pacca","name_href" => "pk/population-of-kahror-pacca","count" => "76 405","real_id" =>89,),
"90"=>array("name_ru"=>"Чухар-Кана","name_en"=>"Chuhar Kana","name_href" => "pk/population-of-chuhar-kana","count" => "75 718","real_id" =>90,),
"91"=>array("name_ru"=>"Гуджар-Хан","name_en"=>"Gujar Khan","name_href" => "pk/population-of-gujar-khan","count" => "75 128","real_id" =>91,),
"92"=>array("name_ru"=>"Наровал","name_en"=>"Narowal","name_href" => "pk/population-of-narowal","count" => "74 974","real_id" =>92,),
"93"=>array("name_ru"=>"Тандо-Мухаммад-Хан","name_en"=>"Tando Muhammad Khan","name_href" => "pk/population-of-tando-muhammad-khan","count" => "74 691","real_id" =>93,),
"94"=>array("name_ru"=>"Шуджабад","name_en"=>"Shujabad","name_href" => "pk/population-of-shujabad","count" => "74 541","real_id" =>94,),
"95"=>array("name_ru"=>"Сиби","name_en"=>"Sibi","name_href" => "pk/population-of-sibi","count" => "73 816","real_id" =>95,),
"96"=>array("name_ru"=>"Бадин","name_en"=>"Badin","name_href" => "pk/population-of-badin","count" => "73 747","real_id" =>96,),
"97"=>array("name_ru"=>"Котри","name_en"=>"Kotri","name_href" => "pk/population-of-kotri","count" => "73 540","real_id" =>97,),
"98"=>array("name_ru"=>"Дипалпур","name_en"=>"Dipalpur","name_href" => "pk/population-of-dipalpur","count" => "73 202","real_id" =>98,),
"99"=>array("name_ru"=>"Пано-Акил","name_en"=>"Pano Aqil","name_href" => "pk/population-of-pano-aqil","count" => "73 058","real_id" =>99,),
"100"=>array("name_ru"=>"Шабкадар","name_en"=>"Shabqadar","name_href" => "pk/population-of-shabqadar","count" => "72 320","real_id" =>100,),
"101"=>array("name_ru"=>"Шахдадкот","name_en"=>"Shahdadkot","name_href" => "pk/population-of-shahdadkot","count" => "71 983","real_id" =>101,),
"102"=>array("name_ru"=>"Бай-Феру","name_en"=>"Phool Nagar","name_href" => "pk/population-of-phool-nagar","count" => "71 931","real_id" =>102,),
"103"=>array("name_ru"=>"Моро","name_en"=>"Moro","name_href" => "pk/population-of-moro","count" => "71 364","real_id" =>103,),
"104"=>array("name_ru"=>"Ферозвала","name_en"=>"Ferozwala","name_href" => "pk/population-of-ferozwala","count" => "71 277","real_id" =>104,),
"105"=>array("name_ru"=>"Саммундри","name_en"=>"Sammundri","name_href" => "pk/population-of-sammundri","count" => "71 124","real_id" =>105,),
"106"=>array("name_ru"=>"Маилси","name_en"=>"Mailsi","name_href" => "pk/population-of-mailsi","count" => "71 114","real_id" =>106,),
"107"=>array("name_ru"=>"Шахдадпур","name_en"=>"Shahdadpur","name_href" => "pk/population-of-shahdadpur","count" => "70 739","real_id" =>107,),
"108"=>array("name_ru"=>"Маншехра","name_en"=>"Mansehra","name_href" => "pk/population-of-mansehra","count" => "70 294","real_id" =>108,),
"109"=>array("name_ru"=>"Камбар","name_en"=>"Qambar","name_href" => "pk/population-of-qambar","count" => "68 848","real_id" =>109,),
"110"=>array("name_ru"=>"Хавели","name_en"=>"Haveli Lakha","name_href" => "pk/population-of-haveli-lakha","count" => "68 015","real_id" =>110,),
"111"=>array("name_ru"=>"Жоб","name_en"=>"Zhob","name_href" => "pk/population-of-zhob","count" => "67 737","real_id" =>111,),
"112"=>array("name_ru"=>"Гвадар","name_en"=>"Gwadar","name_href" => "pk/population-of-gwadar","count" => "67 127","real_id" =>112,),
"113"=>array("name_ru"=>"Джампур","name_en"=>"Jampur","name_href" => "pk/population-of-jampur","count" => "67 075","real_id" =>113,),
"114"=>array("name_ru"=>"Тахт-и-Бахи","name_en"=>"Takht-i-Bahi","name_href" => "pk/population-of-takht-i-bahi","count" => "66 448","real_id" =>114,),
"115"=>array("name_ru"=>"Шакаргарх","name_en"=>"Shakargarh","name_href" => "pk/population-of-shakargarh","count" => "65 816","real_id" =>115,),
"116"=>array("name_ru"=>"Сангала-Хилл","name_en"=>"Sangla Hill","name_href" => "pk/population-of-sangla-hill","count" => "64 997","real_id" =>116,),
"117"=>array("name_ru"=>"Нанкана-Сахиб","name_en"=>"Nankana Sahib","name_href" => "pk/population-of-nankana-sahib","count" => "64 048","real_id" =>117,),
"118"=>array("name_ru"=>"Самбриал","name_en"=>"Sambrial","name_href" => "pk/population-of-sambrial","count" => "64 012","real_id" =>118,),
"119"=>array("name_ru"=>"Харипур","name_en"=>"Haripur, Pakistan","name_href" => "pk/population-of-haripur,-pakistan","count" => "63 772","real_id" =>119,),
"120"=>array("name_ru"=>"Банну","name_en"=>"Bannu","name_href" => "pk/population-of-bannu","count" => "63 278","real_id" =>120,),
"121"=>array("name_ru"=>"Худжра-Шах-Муким","name_en"=>"Hujra Shah Muqeem","name_href" => "pk/population-of-hujra-shah-muqeem","count" => "62 728","real_id" =>121,),
"122"=>array("name_ru"=>"Готки","name_en"=>"Ghotki","name_href" => "pk/population-of-ghotki","count" => "61 836","real_id" =>122,),
"123"=>array("name_ru"=>"Кабирвала","name_en"=>"Kabirwala","name_href" => "pk/population-of-kabirwala","count" => "60 816","real_id" =>123,),
"124"=>array("name_ru"=>"Сангхар","name_en"=>"Sanghar","name_href" => "pk/population-of-sanghar","count" => "60 462","real_id" =>124,),
"125"=>array("name_ru"=>"Чуниан","name_en"=>"Chunian","name_href" => "pk/population-of-chunian","count" => "59 879","real_id" =>125,),
"126"=>array("name_ru"=>"Гаккар","name_en"=>"Gakhars","name_href" => "pk/population-of-gakhars","count" => "59 779","real_id" =>126,),
"127"=>array("name_ru"=>"Тимергара","name_en"=>"Timergara","name_href" => "pk/population-of-timergara","count" => "59 066","real_id" =>127,),
"128"=>array("name_ru"=>"Дера-Мурад-Джамали","name_en"=>"Dera Murad Jamali","name_href" => "pk/population-of-dera-murad-jamali","count" => "57 814","real_id" =>128,),
"129"=>array("name_ru"=>"Пасрур","name_en"=>"Pasrur","name_href" => "pk/population-of-pasrur","count" => "57 787","real_id" =>129,),
"130"=>array("name_ru"=>"Дера-Аллах-Яр","name_en"=>"Dera Allah Yar","name_href" => "pk/population-of-dera-allah-yar","count" => "57 045","real_id" =>130,),
"131"=>array("name_ru"=>"Уста-Мухаммад","name_en"=>"Usta Mohammad","name_href" => "pk/population-of-usta-mohammad","count" => "56 886","real_id" =>131,),
"132"=>array("name_ru"=>"Раджанпур","name_en"=>"Rajanpur","name_href" => "pk/population-of-rajanpur","count" => "56 506","real_id" =>132,),
"133"=>array("name_ru"=>"Рабвах","name_en"=>"Rabwah","name_href" => "pk/population-of-rabwah","count" => "56 319","real_id" =>133,),
"134"=>array("name_ru"=>"Дуллевала","name_en"=>"Dullewala","name_href" => "pk/population-of-dullewala","count" => "54 277","real_id" =>134,),
"135"=>array("name_ru"=>"Кила-Дисар-Сингх","name_en"=>"Qila Didar Singh","name_href" => "pk/population-of-qila-didar-singh","count" => "53 821","real_id" =>135,),
"136"=>array("name_ru"=>"Рохри","name_en"=>"Rohri","name_href" => "pk/population-of-rohri","count" => "53 104","real_id" =>136,),
"137"=>array("name_ru"=>"Шахкот","name_en"=>"Shahkot, Pakistan","name_href" => "pk/population-of-shahkot,-pakistan","count" => "52 244","real_id" =>137,),
"138"=>array("name_ru"=>"Хадали","name_en"=>"Hadali","name_href" => "pk/population-of-hadali","count" => "52 217","real_id" =>138,),
"139"=>array("name_ru"=>"Джохарабад","name_en"=>"Jauharabad","name_href" => "pk/population-of-jauharabad","count" => "51 893","real_id" =>139,),
"140"=>array("name_ru"=>"Бат-Кхела","name_en"=>"Batkhela","name_href" => "pk/population-of-batkhela","count" => "51 574","real_id" =>140,),
"141"=>array("name_ru"=>"Алипур-Чатха","name_en"=>"Alipur Chatha","name_href" => "pk/population-of-alipur-chatha","count" => "51 255","real_id" =>141,),
"142"=>array("name_ru"=>"Кот-Радха-Кишан","name_en"=>"Kot Radha Kishan","name_href" => "pk/population-of-kot-radha-kishan","count" => "51 182","real_id" =>142,),
"143"=>array("name_ru"=>"Кахна-Нау","name_en"=>"Kahna Nau","name_href" => "pk/population-of-kahna-nau","count" => "51 161","real_id" =>143,),
"144"=>array("name_ru"=>"Дина","name_en"=>"Dina, Pakistan","name_href" => "pk/population-of-dina,-pakistan","count" => "50 737","real_id" =>144,),
"145"=>array("name_ru"=>"Матли","name_en"=>"Matli","name_href" => "pk/population-of-matli","count" => "50 520","real_id" =>145,),
"146"=>array("name_ru"=>"Джатой","name_en"=>"Jatoi, Pakistan","name_href" => "pk/population-of-jatoi,-pakistan","count" => "50 058","real_id" =>146,),
"147"=>array("name_ru"=>"Таунса","name_en"=>"Taunsa Sharif","name_href" => "pk/population-of-taunsa-sharif","count" => "50 026","real_id" =>147,),
"148"=>array("name_ru"=>"Абдул-Хаким","name_en"=>"Abdul Hakeem, Pakistan","name_href" => "pk/population-of-abdul-hakeem,-pakistan","count" => "49 717","real_id" =>148,),
"149"=>array("name_ru"=>"Хасан-Абдал","name_en"=>"Hasan Abdal","name_href" => "pk/population-of-hasan-abdal","count" => "49 675","real_id" =>149,),
"150"=>array("name_ru"=>"Мирпур-Матхело","name_en"=>"Mirpur Mathelo","name_href" => "pk/population-of-mirpur-mathelo","count" => "49 430","real_id" =>150,),
"151"=>array("name_ru"=>"Сарай-Аламгир","name_en"=>"Sarai Alamgir","name_href" => "pk/population-of-sarai-alamgir","count" => "48 982","real_id" =>151,),
"152"=>array("name_ru"=>"Лоралай","name_en"=>"Loralai","name_href" => "pk/population-of-loralai","count" => "48 872","real_id" =>152,),
"153"=>array("name_ru"=>"Камра","name_en"=>"Kamra","name_href" => "pk/population-of-kamra","count" => "48 810","real_id" =>153,),
"154"=>array("name_ru"=>"Мустафабад","name_en"=>"Mustafabad, Punjab","name_href" => "pk/population-of-mustafabad,-punjab","count" => "48 701","real_id" =>154,),
"155"=>array("name_ru"=>"Хала","name_en"=>"Hala, Sindh","name_href" => "pk/population-of-hala,-sindh","count" => "48 031","real_id" =>155,),
"156"=>array("name_ru"=>"Талаганг","name_en"=>"Talagang","name_href" => "pk/population-of-talagang","count" => "48 024","real_id" =>156,),
"157"=>array("name_ru"=>"Ратодеро","name_en"=>"Ratodero","name_href" => "pk/population-of-ratodero","count" => "47 935","real_id" =>157,),
"158"=>array("name_ru"=>"Басирпур","name_en"=>"Basirpur","name_href" => "pk/population-of-basirpur","count" => "47 128","real_id" =>158,),
"159"=>array("name_ru"=>"Халабат","name_en"=>"Khalabat Township","name_href" => "pk/population-of-khalabat-township","count" => "45 794","real_id" =>159,),
"160"=>array("name_ru"=>"Танк","name_en"=>"Tank, Pakistan","name_href" => "pk/population-of-tank,-pakistan","count" => "45 783","real_id" =>160,),
"161"=>array("name_ru"=>"Форт-Аббас","name_en"=>"Fort Abbas","name_href" => "pk/population-of-fort-abbas","count" => "45 295","real_id" =>161,),
"162"=>array("name_ru"=>"Кот-Моман","name_en"=>"Kot Moman","name_href" => "pk/population-of-kot-moman","count" => "45 053","real_id" =>162,),
"163"=>array("name_ru"=>"Наушера-Виркан","name_en"=>"Nowshera Virkan","name_href" => "pk/population-of-nowshera-virkan","count" => "44 490","real_id" =>163,),
"164"=>array("name_ru"=>"Тандлианвала","name_en"=>"Tandlianwala","name_href" => "pk/population-of-tandlianwala","count" => "44 481","real_id" =>164,),
"165"=>array("name_ru"=>"Татта","name_en"=>"Thatta","name_href" => "pk/population-of-thatta","count" => "44 409","real_id" =>165,),
"166"=>array("name_ru"=>"Лудхевала-Вараич","name_en"=>"Ludhewala Waraich","name_href" => "pk/population-of-ludhewala-waraich","count" => "44 326","real_id" =>166,),
"167"=>array("name_ru"=>"Динга","name_en"=>"Dinga","name_href" => "pk/population-of-dinga","count" => "43 624","real_id" =>167,),
"168"=>array("name_ru"=>"Кундиан","name_en"=>"Kundian","name_href" => "pk/population-of-kundian","count" => "42 863","real_id" =>168,),
"169"=>array("name_ru"=>"Пасни","name_en"=>"Pasni (city)","name_href" => "pk/population-of-pasni-(city)","count" => "42 824","real_id" =>169,),
"170"=>array("name_ru"=>"Чоук-Азам","name_en"=>"Chowk Azam","name_href" => "pk/population-of-chowk-azam","count" => "42 608","real_id" =>170,),
"171"=>array("name_ru"=>"Хавелиан","name_en"=>"Havelian","name_href" => "pk/population-of-havelian","count" => "42 353","real_id" =>171,),
"172"=>array("name_ru"=>"Рисалпур","name_en"=>"Risalpur","name_href" => "pk/population-of-risalpur","count" => "42 179","real_id" =>172,),
"173"=>array("name_ru"=>"Умеркот","name_en"=>"Umerkot","name_href" => "pk/population-of-umerkot","count" => "42 176","real_id" =>173,),
"174"=>array("name_ru"=>"Сахивал","name_en"=>"Sahiwal","name_href" => "pk/population-of-sahiwal","count" => "41 982","real_id" =>174,),
"175"=>array("name_ru"=>"Пабби","name_en"=>"Pabbi","name_href" => "pk/population-of-pabbi","count" => "41 757","real_id" =>175,),
"176"=>array("name_ru"=>"Джалалпур-Пирвала","name_en"=>"Jalalpur Pirwala","name_href" => "pk/population-of-jalalpur-pirwala","count" => "41 690","real_id" =>176,),
"177"=>array("name_ru"=>"Чак-Джумра","name_en"=>"Chak Jhumra","name_href" => "pk/population-of-chak-jhumra","count" => "41 490","real_id" =>177,),
"178"=>array("name_ru"=>"Лиакатпур","name_en"=>"Liaqauatpur","name_href" => "pk/population-of-liaqauatpur","count" => "41 404","real_id" =>178,),
"179"=>array("name_ru"=>"Ренала-Хурд","name_en"=>"Renala Khurd","name_href" => "pk/population-of-renala-khurd","count" => "41 376","real_id" =>179,),
"180"=>array("name_ru"=>"Сехван","name_en"=>"Sehwan Sharif","name_href" => "pk/population-of-sehwan-sharif","count" => "41 250","real_id" =>180,),
"181"=>array("name_ru"=>"Джахангира","name_en"=>"Jehangira","name_href" => "pk/population-of-jehangira","count" => "41 205","real_id" =>181,),
"182"=>array("name_ru"=>"Бхера","name_en"=>"Bhera","name_href" => "pk/population-of-bhera","count" => "40 934","real_id" =>182,),
"183"=>array("name_ru"=>"Лакки-Марват","name_en"=>"Lakki Marwat","name_href" => "pk/population-of-lakki-marwat","count" => "40 731","real_id" =>183,),
"184"=>array("name_ru"=>"Топи","name_en"=>"Topi, Khyber Pakhtunkhwa","name_href" => "pk/population-of-topi,-khyber-pakhtunkhwa","count" => "40 674","real_id" =>184,),
"185"=>array("name_ru"=>"Малаквал","name_en"=>"Malakwal","name_href" => "pk/population-of-malakwal","count" => "40 554","real_id" =>185,),
"186"=>array("name_ru"=>"Хангу","name_en"=>"Hangu, Pakistan","name_href" => "pk/population-of-hangu,-pakistan","count" => "40 461","real_id" =>186,),
"187"=>array("name_ru"=>"Читрал","name_en"=>"Chitral","name_href" => "pk/population-of-chitral","count" => "40 399","real_id" =>187,),
"188"=>array("name_ru"=>"Дахарки","name_en"=>"Daharki","name_href" => "pk/population-of-daharki","count" => "40 181","real_id" =>188,),
"189"=>array("name_ru"=>"Харан","name_en"=>"Kharan, Pakistan","name_href" => "pk/population-of-kharan,-pakistan","count" => "39 889","real_id" =>189,),
"190"=>array("name_ru"=>"Пирмахал","name_en"=>"Pir Mahal","name_href" => "pk/population-of-pir-mahal","count" => "39 404","real_id" =>190,),
"191"=>array("name_ru"=>"Хурианвала","name_en"=>"Khurrianwala","name_href" => "pk/population-of-khurrianwala","count" => "39 348","real_id" =>191,),
"192"=>array("name_ru"=>"Пиндигхеб","name_en"=>"Pindigheb","name_href" => "pk/population-of-pindigheb","count" => "39 221","real_id" =>192,),
"193"=>array("name_ru"=>"Пинди-Бхаттиан","name_en"=>"Pindi Bhattian","name_href" => "pk/population-of-pindi-bhattian","count" => "39 120","real_id" =>193,),
"194"=>array("name_ru"=>"Бадах","name_en"=>"Badah","name_href" => "pk/population-of-badah","count" => "38 949","real_id" =>194,),
"195"=>array("name_ru"=>"Наранг","name_en"=>"Narang, Gujrat","name_href" => "pk/population-of-narang,-gujrat","count" => "38 775","real_id" =>195,),
"196"=>array("name_ru"=>"Захир-Пир","name_en"=>"Zāhir Pīr","name_href" => "pk/population-of-zāhir-pīr","count" => "38 042","real_id" =>196,),
"197"=>array("name_ru"=>"Дуньяпур","name_en"=>"Dunyapur","name_href" => "pk/population-of-dunyapur","count" => "37 957","real_id" =>197,),
"198"=>array("name_ru"=>"Мастунг","name_en"=>"Mastung, Pakistan","name_href" => "pk/population-of-mastung,-pakistan","count" => "37 614","real_id" =>198,),
"199"=>array("name_ru"=>"Алипур","name_en"=>"Alipur Chatha","name_href" => "pk/population-of-alipur-chatha","count" => "37 463","real_id" =>199,),
"200"=>array("name_ru"=>"Лалиан","name_en"=>"Lalian","name_href" => "pk/population-of-lalian","count" => "37 159","real_id" =>200,),
"201"=>array("name_ru"=>"Карачи","name_en"=>"Karachi","name_href" => "pk/population-of-karachi","count" => "11 234 942","real_id" =>201,),
"202"=>array("name_ru"=>"Лахор","name_en"=>"Lahore","name_href" => "pk/population-of-lahore","count" => "6 761 251","real_id" =>202,),
"203"=>array("name_ru"=>"Фейсалабад","name_en"=>"Faisalabad","name_href" => "pk/population-of-faisalabad","count" => "2 640 697","real_id" =>203,),
"204"=>array("name_ru"=>"Равалпинди","name_en"=>"Rawalpindi","name_href" => "pk/population-of-rawalpindi","count" => "1 853 175","real_id" =>204,),
"205"=>array("name_ru"=>"Мултан","name_en"=>"Multan","name_href" => "pk/population-of-multan","count" => "1 573 991","real_id" =>205,)
);

?>