<?php
//Польша 59 
$libpl = array ( 
"1"=>array("name_ru"=>"Варшава","name_en"=>"Warszawa","name_href" => "pl/population-of-warszawa","count" => "1 720 398","real_id" =>1,),
"2"=>array("name_ru"=>"Краков","name_en"=>"Kraków","name_href" => "pl/population-of-kraków","count" => "756 183","real_id" =>2,),
"3"=>array("name_ru"=>"Лодзь","name_en"=>"Łódź","name_href" => "pl/population-of-łódź","count" => "737 098","real_id" =>3,),
"4"=>array("name_ru"=>"Вроцлав","name_en"=>"Wrocław","name_href" => "pl/population-of-wrocław","count" => "632 996","real_id" =>4,),
"5"=>array("name_ru"=>"Познань","name_en"=>"Poznań","name_href" => "pl/population-of-poznań","count" => "551 627","real_id" =>5,),
"6"=>array("name_ru"=>"Гданьск","name_en"=>"Gdańsk","name_href" => "pl/population-of-gdańsk","count" => "456 967","real_id" =>6,),
"7"=>array("name_ru"=>"Щецин","name_en"=>"Szczecin","name_href" => "pl/population-of-szczecin","count" => "405 606","real_id" =>7,),
"8"=>array("name_ru"=>"Быдгощ","name_en"=>"Bydgoszcz","name_href" => "pl/population-of-bydgoszcz","count" => "356 177","real_id" =>8,),
"9"=>array("name_ru"=>"Люблин","name_en"=>"Lublin","name_href" => "pl/population-of-lublin","count" => "348 450","real_id" =>9,),
"10"=>array("name_ru"=>"Катовице","name_en"=>"Katowice","name_href" => "pl/population-of-katowice","count" => "306 826","real_id" =>10,),
"11"=>array("name_ru"=>"Белосток","name_en"=>"Białystok","name_href" => "pl/population-of-białystok","count" => "295 198","real_id" =>11,),
"12"=>array("name_ru"=>"Гдыня","name_en"=>"Gdynia","name_href" => "pl/population-of-gdynia","count" => "247 324","real_id" =>12,),
"13"=>array("name_ru"=>"Ченстохова","name_en"=>"Częstochowa","name_href" => "pl/population-of-częstochowa","count" => "238 042","real_id" =>13,),
"14"=>array("name_ru"=>"Радом","name_en"=>"Radom","name_href" => "pl/population-of-radom","count" => "222 496","real_id" =>14,),
"15"=>array("name_ru"=>"Сосновец","name_en"=>"Sosnowiec","name_href" => "pl/population-of-sosnowiec","count" => "217 638","real_id" =>15,),
"16"=>array("name_ru"=>"Торунь","name_en"=>"Toruń","name_href" => "pl/population-of-toruń","count" => "205 312","real_id" =>16,),
"17"=>array("name_ru"=>"Кельце","name_en"=>"Kielce","name_href" => "pl/population-of-kielce","count" => "203 804","real_id" =>17,),
"18"=>array("name_ru"=>"Гливице","name_en"=>"Gliwice","name_href" => "pl/population-of-gliwice","count" => "195 472","real_id" =>18,),
"19"=>array("name_ru"=>"Забже","name_en"=>"Zabrze","name_href" => "pl/population-of-zabrze","count" => "186 913","real_id" =>19,),
"20"=>array("name_ru"=>"Бытом","name_en"=>"Bytom","name_href" => "pl/population-of-bytom","count" => "181 617","real_id" =>20,),
"21"=>array("name_ru"=>"Жешув","name_en"=>"Rzeszów","name_href" => "pl/population-of-rzeszów","count" => "178 227","real_id" =>21,),
"22"=>array("name_ru"=>"Ольштын","name_en"=>"Olsztyn","name_href" => "pl/population-of-olsztyn","count" => "176 463","real_id" =>22,),
"23"=>array("name_ru"=>"Бельско-Бяла","name_en"=>"Bielsko-Biała","name_href" => "pl/population-of-bielsko-biała","count" => "175 008","real_id" =>23,),
"24"=>array("name_ru"=>"Руда-Слёнска","name_en"=>"Ruda Śląska","name_href" => "pl/population-of-ruda-śląska","count" => "142 950","real_id" =>24,),
"25"=>array("name_ru"=>"Рыбник","name_en"=>"Rybnik","name_href" => "pl/population-of-rybnik","count" => "141 410","real_id" =>25,),
"26"=>array("name_ru"=>"Тыхы","name_en"=>"Tychy","name_href" => "pl/population-of-tychy","count" => "129 386","real_id" =>26,),
"27"=>array("name_ru"=>"Домброва-Гурнича","name_en"=>"Dąbrowa Górnicza","name_href" => "pl/population-of-dąbrowa-górnicza","count" => "127 431","real_id" =>27,),
"28"=>array("name_ru"=>"Плоцк","name_en"=>"Płock","name_href" => "pl/population-of-płock","count" => "126 061","real_id" =>28,),
"29"=>array("name_ru"=>"Эльблонг","name_en"=>"Elbląg","name_href" => "pl/population-of-elbląg","count" => "126 049","real_id" =>29,),
"30"=>array("name_ru"=>"Ополе","name_en"=>"Opole","name_href" => "pl/population-of-opole","count" => "125 710","real_id" =>30,),
"31"=>array("name_ru"=>"Гожув-Велькопольски","name_en"=>"Gorzów Wielkopolski","name_href" => "pl/population-of-gorzów-wielkopolski","count" => "125 394","real_id" =>31,),
"32"=>array("name_ru"=>"Валбжих","name_en"=>"Wałbrzych","name_href" => "pl/population-of-wałbrzych","count" => "120 197","real_id" =>32,),
"33"=>array("name_ru"=>"Зелёна-Гура","name_en"=>"Zielona Góra","name_href" => "pl/population-of-zielona-góra","count" => "117 699","real_id" =>33,),
"34"=>array("name_ru"=>"Влоцлавек","name_en"=>"Włocławek","name_href" => "pl/population-of-włocławek","count" => "116 914","real_id" =>34,),
"35"=>array("name_ru"=>"Тарнув","name_en"=>"Tarnów","name_href" => "pl/population-of-tarnów","count" => "114 635","real_id" =>35,),
"36"=>array("name_ru"=>"Хожув","name_en"=>"Chorzów","name_href" => "pl/population-of-chorzów","count" => "112 697","real_id" =>36,),
"37"=>array("name_ru"=>"Кошалин","name_en"=>"Koszalin","name_href" => "pl/population-of-koszalin","count" => "107 948","real_id" =>37,),
"38"=>array("name_ru"=>"Калиш","name_en"=>"Kalisz","name_href" => "pl/population-of-kalisz","count" => "106 664","real_id" =>38,),
"39"=>array("name_ru"=>"Легница","name_en"=>"Legnica","name_href" => "pl/population-of-legnica","count" => "103 892","real_id" =>39,),
"40"=>array("name_ru"=>"Грудзёндз","name_en"=>"Grudziądz","name_href" => "pl/population-of-grudziądz","count" => "98 757","real_id" =>40,),
"41"=>array("name_ru"=>"Слупск","name_en"=>"Słupsk","name_href" => "pl/population-of-słupsk","count" => "96 655","real_id" =>41,),
"42"=>array("name_ru"=>"Явожно","name_en"=>"Jaworzno","name_href" => "pl/population-of-jaworzno","count" => "94 807","real_id" =>42,),
"43"=>array("name_ru"=>"Ястшембе-Здруй","name_en"=>"Jastrzębie-Zdrój","name_href" => "pl/population-of-jastrzębie-zdrój","count" => "92 462","real_id" =>43,),
"44"=>array("name_ru"=>"Новы-Сонч","name_en"=>"Nowy Sącz","name_href" => "pl/population-of-nowy-sącz","count" => "84 537","real_id" =>44,),
"45"=>array("name_ru"=>"Еленя-Гура","name_en"=>"Jelenia Góra","name_href" => "pl/population-of-jelenia-góra","count" => "84 023","real_id" =>45,),
"46"=>array("name_ru"=>"Конин","name_en"=>"Konin","name_href" => "pl/population-of-konin","count" => "79 212","real_id" =>46,),
"47"=>array("name_ru"=>"Седльце","name_en"=>"Siedlce","name_href" => "pl/population-of-siedlce","count" => "77 392","real_id" =>47,),
"48"=>array("name_ru"=>"Петркув Трыбунальски","name_en"=>"Piotrków Trybunalski","name_href" => "pl/population-of-piotrków-trybunalski","count" => "77 383","real_id" =>48,),
"49"=>array("name_ru"=>"Иновроцлав","name_en"=>"Inowrocław","name_href" => "pl/population-of-inowrocław","count" => "75 802","real_id" =>49,),
"50"=>array("name_ru"=>"Мысловице","name_en"=>"Mysłowice","name_href" => "pl/population-of-mysłowice","count" => "74 865","real_id" =>50,),
"51"=>array("name_ru"=>"Пила","name_en"=>"Piła","name_href" => "pl/population-of-piła","count" => "74 550","real_id" =>51,),
"52"=>array("name_ru"=>"Любин","name_en"=>"Lubin","name_href" => "pl/population-of-lubin","count" => "74 045","real_id" =>52,),
"53"=>array("name_ru"=>"Острув Велькопольски","name_en"=>"Ostrów Wielkopolski","name_href" => "pl/population-of-ostrów-wielkopolski","count" => "72 382","real_id" =>53,),
"54"=>array("name_ru"=>"Островец Свентокшиски","name_en"=>"Ostrowiec Świętokrzyski","name_href" => "pl/population-of-ostrowiec-świętokrzyski","count" => "71 959","real_id" =>54,),
"55"=>array("name_ru"=>"Семяновице-Слёнске","name_en"=>"Siemianowice Śląskie","name_href" => "pl/population-of-siemianowice-śląskie","count" => "70 291","real_id" =>55,),
"56"=>array("name_ru"=>"Старгард Щецинского","name_en"=>"Stargard Szczeciński","name_href" => "pl/population-of-stargard-szczeciński","count" => "69 633","real_id" =>56,),
"57"=>array("name_ru"=>"Сувалки","name_en"=>"Suwałki","name_href" => "pl/population-of-suwałki","count" => "69 527","real_id" =>57,),
"58"=>array("name_ru"=>"Гнезно","name_en"=>"Gniezno","name_href" => "pl/population-of-gniezno","count" => "69 483","real_id" =>58,),
"59"=>array("name_ru"=>"Пабянице","name_en"=>"Pabianice","name_href" => "pl/population-of-pabianice","count" => "68 550","real_id" =>59,),
"60"=>array("name_ru"=>"Варшава","name_en"=>"Warszawa","name_href" => "pl/population-of-warszawa","count" => "1 720 398","real_id" =>60,),
"61"=>array("name_ru"=>"Краков","name_en"=>"Kraków","name_href" => "pl/population-of-kraków","count" => "756 183","real_id" =>61,),
"62"=>array("name_ru"=>"Лодзь","name_en"=>"Łódź","name_href" => "pl/population-of-łódź","count" => "737 098","real_id" =>62,),
"63"=>array("name_ru"=>"Вроцлав","name_en"=>"Wrocław","name_href" => "pl/population-of-wrocław","count" => "632 996","real_id" =>63,),
"64"=>array("name_ru"=>"Познань","name_en"=>"Poznań","name_href" => "pl/population-of-poznań","count" => "551 627","real_id" =>64,)
);

?>