<?php
//Папуа - новая гвинея 41 
$libpg = array ( 
"1"=>array("name_ru"=>"Порт-Морсби","name_en"=>"Port Moresby","name_href" => "pg/population-of-port-moresby","count" => "317 374","real_id" =>1,),
"2"=>array("name_ru"=>"Лаэ","name_en"=>"Lae","name_href" => "pg/population-of-lae","count" => "100 677","real_id" =>2,),
"3"=>array("name_ru"=>"Менди","name_en"=>"Mendi","name_href" => "pg/population-of-mendi","count" => "56 055","real_id" =>3,),
"4"=>array("name_ru"=>"Попондетта","name_en"=>"Popondetta","name_href" => "pg/population-of-popondetta","count" => "49 244","real_id" =>4,),
"5"=>array("name_ru"=>"Маунт-Хаген","name_en"=>"Mount Hagen","name_href" => "pg/population-of-mount-hagen","count" => "46 256","real_id" =>5,),
"6"=>array("name_ru"=>"Арава","name_en"=>"Arawa","name_href" => "pg/population-of-arawa","count" => "38 200","real_id" =>6,),
"7"=>array("name_ru"=>"Маданг","name_en"=>"Madang","name_href" => "pg/population-of-madang","count" => "29 460","real_id" =>7,),
"8"=>array("name_ru"=>"Кокопо","name_en"=>"Kokopo","name_href" => "pg/population-of-kokopo","count" => "29 241","real_id" =>8,),
"9"=>array("name_ru"=>"Кимбе","name_en"=>"Kimbe","name_href" => "pg/population-of-kimbe","count" => "27 205","real_id" =>9,),
"10"=>array("name_ru"=>"Булоло","name_en"=>"Bulolo","name_href" => "pg/population-of-bulolo","count" => "23 910","real_id" =>10,),
"11"=>array("name_ru"=>"Вевак","name_en"=>"Wewak","name_href" => "pg/population-of-wewak","count" => "21 792","real_id" =>11,),
"12"=>array("name_ru"=>"Горока","name_en"=>"Goroka","name_href" => "pg/population-of-goroka","count" => "21 507","real_id" =>12,),
"13"=>array("name_ru"=>"Дару","name_en"=>"Daru","name_href" => "pg/population-of-daru","count" => "20 053","real_id" =>13,),
"14"=>array("name_ru"=>"Киунга","name_en"=>"Kiunga","name_href" => "pg/population-of-kiunga","count" => "18 747","real_id" =>14,),
"15"=>array("name_ru"=>"Алотау","name_en"=>"Alotau","name_href" => "pg/population-of-alotau","count" => "15 939","real_id" =>15,),
"16"=>array("name_ru"=>"Кавиенг","name_en"=>"Kavieng","name_href" => "pg/population-of-kavieng","count" => "15 826","real_id" =>16,),
"17"=>array("name_ru"=>"Тари","name_en"=>"Tari","name_href" => "pg/population-of-tari","count" => "15 413","real_id" =>17,),
"18"=>array("name_ru"=>"Каинанту","name_en"=>"Kainantu","name_href" => "pg/population-of-kainantu","count" => "12 709","real_id" =>18,),
"19"=>array("name_ru"=>"Ванимо","name_en"=>"Vanimo","name_href" => "pg/population-of-vanimo","count" => "11 863","real_id" =>19,),
"20"=>array("name_ru"=>"Кундиава","name_en"=>"Kundiawa","name_href" => "pg/population-of-kundiawa","count" => "11 560","real_id" =>20,),
"21"=>array("name_ru"=>"Йалибу","name_en"=>"Ialibu","name_href" => "pg/population-of-ialibu","count" => "10 314","real_id" =>21,),
"22"=>array("name_ru"=>"Вау","name_en"=>"Wau","name_href" => "pg/population-of-wau","count" => "9 442","real_id" =>22,),
"23"=>array("name_ru"=>"Бука","name_en"=>"Buka","name_href" => "pg/population-of-buka","count" => "8 900","real_id" =>23,),
"24"=>array("name_ru"=>"Рабаул","name_en"=>"Rabaul","name_href" => "pg/population-of-rabaul","count" => "7 882","real_id" =>24,),
"25"=>array("name_ru"=>"Кокода","name_en"=>"Kokoda","name_href" => "pg/population-of-kokoda","count" => "7 446","real_id" =>25,),
"26"=>array("name_ru"=>"Айтапе","name_en"=>"Aitape","name_href" => "pg/population-of-aitape","count" => "6 931","real_id" =>26,),
"27"=>array("name_ru"=>"Керема","name_en"=>"Kerema","name_href" => "pg/population-of-kerema","count" => "6 551","real_id" =>27,),
"28"=>array("name_ru"=>"Лоренгау","name_en"=>"Lorengau","name_href" => "pg/population-of-lorengau","count" => "6 131","real_id" =>28,),
"29"=>array("name_ru"=>"Балимо","name_en"=>"Balimo","name_href" => "pg/population-of-balimo","count" => "4 274","real_id" =>29,),
"30"=>array("name_ru"=>"Киета","name_en"=>"Kieta","name_href" => "pg/population-of-kieta","count" => "3 496","real_id" =>30,),
"31"=>array("name_ru"=>"Вабаг","name_en"=>"Wabag","name_href" => "pg/population-of-wabag","count" => "3 485","real_id" =>31,),
"32"=>array("name_ru"=>"Пангуна","name_en"=>"Panguna","name_href" => "pg/population-of-panguna","count" => "2 974","real_id" =>32,),
"33"=>array("name_ru"=>"Морхед","name_en"=>"Morehead","name_href" => "pg/population-of-morehead","count" => "2 666","real_id" =>33,),
"34"=>array("name_ru"=>"Ангорам","name_en"=>"Angoram","name_href" => "pg/population-of-angoram","count" => "2 622","real_id" =>34,),
"35"=>array("name_ru"=>"Амбунти","name_en"=>"Ambunti","name_href" => "pg/population-of-ambunti","count" => "2 248","real_id" =>35,),
"36"=>array("name_ru"=>"Самарай","name_en"=>"Samarai","name_href" => "pg/population-of-samarai","count" => "1 706","real_id" =>36,),
"37"=>array("name_ru"=>"Поргера","name_en"=>"Porgera","name_href" => "pg/population-of-porgera","count" => "1 690","real_id" =>37,),
"38"=>array("name_ru"=>"Наматанаи","name_en"=>"Namatanai","name_href" => "pg/population-of-namatanai","count" => "1 630","real_id" =>38,),
"39"=>array("name_ru"=>"Кандриан","name_en"=>"Kandrian","name_href" => "pg/population-of-kandrian","count" => "1 264","real_id" =>39,),
"40"=>array("name_ru"=>"Финшхафен","name_en"=>"Finschhafen","name_href" => "pg/population-of-finschhafen","count" => "1 240","real_id" =>40,),
"41"=>array("name_ru"=>"Лаиагам","name_en"=>"Laiagam","name_href" => "pg/population-of-laiagam","count" => "986","real_id" =>41,),
"42"=>array("name_ru"=>"Порт-Морсби","name_en"=>"Port Moresby","name_href" => "pg/population-of-port-moresby","count" => "317 374","real_id" =>42,),
"43"=>array("name_ru"=>"Лаэ","name_en"=>"Lae","name_href" => "pg/population-of-lae","count" => "100 677","real_id" =>43,),
"44"=>array("name_ru"=>"Менди","name_en"=>"Mendi","name_href" => "pg/population-of-mendi","count" => "56 055","real_id" =>44,),
"45"=>array("name_ru"=>"Попондетта","name_en"=>"Popondetta","name_href" => "pg/population-of-popondetta","count" => "49 244","real_id" =>45,),
"46"=>array("name_ru"=>"Маунт-Хаген","name_en"=>"Mount Hagen","name_href" => "pg/population-of-mount-hagen","count" => "46 256","real_id" =>46,)
);

?>