<?php
//Португалия 155 
$libpt = array ( 
"1"=>array("name_ru"=>"Лиссабон ","name_en"=>"Lisbon","name_href" => "pt/population-of-lisbon","count" => "547733","real_id" =>1,),
"2"=>array("name_ru"=>"Порту ","name_en"=>"Port","name_href" => "pt/population-of-port","count" => "221800","real_id" =>2,),
"3"=>array("name_ru"=>"Лореш ","name_en"=>"Loures","name_href" => "pt/population-of-loures","count" => "205054","real_id" =>3,),
"4"=>array("name_ru"=>"Вила-Нова-ди-Гая ","name_en"=>"Vila Nova de Gaia","name_href" => "pt/population-of-vila-nova-de-gaia","count" => "178300","real_id" =>4,),
"5"=>array("name_ru"=>"Амадора ","name_en"=>"Amador","name_href" => "pt/population-of-amador","count" => "175135","real_id" =>5,),
"6"=>array("name_ru"=>"Брага","name_en"=>"Braga","name_href" => "pt/population-of-braga","count" => "173946","real_id" =>6,),
"7"=>array("name_ru"=>"Гондомар ","name_en"=>"Gondomar","name_href" => "pt/population-of-gondomar","count" => "171881","real_id" =>7,),
"8"=>array("name_ru"=>"Матозиньюш ","name_en"=>"Matosinhos","name_href" => "pt/population-of-matosinhos","count" => "169104","real_id" =>8,),
"9"=>array("name_ru"=>"Алмада ","name_en"=>"Almada","name_href" => "pt/population-of-almada","count" => "165363","real_id" =>9,),
"10"=>array("name_ru"=>"Сейшал ","name_en"=>"The Seixas","name_href" => "pt/population-of-the-seixas","count" => "164715","real_id" =>10,),
"11"=>array("name_ru"=>"Гимарайнш ","name_en"=>"Guimaraes","name_href" => "pt/population-of-guimaraes","count" => "162572","real_id" =>11,),
"12"=>array("name_ru"=>"Одивелаш","name_en"=>"Odivelas","name_href" => "pt/population-of-odivelas","count" => "144549","real_id" =>12,),
"13"=>array("name_ru"=>"Коимбра ","name_en"=>"Coimbra","name_href" => "pt/population-of-coimbra","count" => "143396","real_id" =>13,),
"14"=>array("name_ru"=>"Вила-Франка-ди-Шира ","name_en"=>"Vila Franca de Xira","name_href" => "pt/population-of-vila-franca-de-xira","count" => "136886","real_id" =>14,),
"15"=>array("name_ru"=>"Синиш ","name_en"=>"Sines","name_href" => "pt/population-of-sines","count" => "136130","real_id" =>15,),
"16"=>array("name_ru"=>"Санта-Мария-да-Фейра","name_en"=>"Santa-Maria-da-Feira","name_href" => "pt/population-of-santa-maria-da-feira","count" => "135964","real_id" =>16,),
"17"=>array("name_ru"=>"Вила-Нова-ди-Фамаликан ","name_en"=>"Vila Nova de Famalicão","name_href" => "pt/population-of-vila-nova-de-famalicão","count" => "127567","real_id" =>17,),
"18"=>array("name_ru"=>"Лейрия ","name_en"=>"Leiria","name_href" => "pt/population-of-leiria","count" => "125949","real_id" =>18,),
"19"=>array("name_ru"=>"Барселуш ","name_en"=>"Barcelos","name_href" => "pt/population-of-barcelos","count" => "123831","real_id" =>19,),
"20"=>array("name_ru"=>"Сетубал","name_en"=>"Setubal","name_href" => "pt/population-of-setubal","count" => "122554","real_id" =>20,),
"21"=>array("name_ru"=>"Майа","name_en"=>"Maya","name_href" => "pt/population-of-maya","count" => "120111","real_id" =>21,),
"22"=>array("name_ru"=>"Фуншал ","name_en"=>"Funchal","name_href" => "pt/population-of-funchal","count" => "111992","real_id" =>22,),
"23"=>array("name_ru"=>"Визеу ","name_en"=>"Viseu","name_href" => "pt/population-of-viseu","count" => "98167","real_id" =>23,),
"24"=>array("name_ru"=>"Валонгу ","name_en"=>"Valongo","name_href" => "pt/population-of-valongo","count" => "94344","real_id" =>24,),
"25"=>array("name_ru"=>"Виана-ду-Каштелу ","name_en"=>"Viana do Castelo","name_href" => "pt/population-of-viana-do-castelo","count" => "88628","real_id" =>25,),
"26"=>array("name_ru"=>"Паредеш","name_en"=>"Paredes","name_href" => "pt/population-of-paredes","count" => "85428","real_id" =>26,),
"27"=>array("name_ru"=>"Агуалва-Касен","name_en"=>"Cacem","name_href" => "pt/population-of-cacem","count" => "81845","real_id" =>27,),
"28"=>array("name_ru"=>"Баррейру","name_en"=>"Barreiro","name_href" => "pt/population-of-barreiro","count" => "78992","real_id" =>28,),
"29"=>array("name_ru"=>"Вила-ду-Конди ","name_en"=>"Vila do Conde","name_href" => "pt/population-of-vila-do-conde","count" => "74391","real_id" =>29,),
"30"=>array("name_ru"=>"Авейру ","name_en"=>"Aveiro","name_href" => "pt/population-of-aveiro","count" => "73559","real_id" =>30,),
"31"=>array("name_ru"=>"Торриш-Ведраш ","name_en"=>"Torres Vedras","name_href" => "pt/population-of-torres-vedras","count" => "72500","real_id" =>31,),
"32"=>array("name_ru"=>"Санту-Тирсу ","name_en"=>"Santo Tirso","name_href" => "pt/population-of-santo-tirso","count" => "72396","real_id" =>32,),
"33"=>array("name_ru"=>"Пенафиел ","name_en"=>"Penafiel","name_href" => "pt/population-of-penafiel","count" => "71801","real_id" =>33,),
"34"=>array("name_ru"=>"Оливейра-ди-Аземейш ","name_en"=>"Oliveira de azeméis","name_href" => "pt/population-of-oliveira-de-azeméis","count" => "71243","real_id" =>34,),
"35"=>array("name_ru"=>"Сантарен ","name_en"=>"Santarem","name_href" => "pt/population-of-santarem","count" => "63563","real_id" =>35,),
"36"=>array("name_ru"=>"Повуа-ди-Варзин ","name_en"=>"Póvoa de Varzim","name_href" => "pt/population-of-póvoa-de-varzim","count" => "63470","real_id" =>36,),
"37"=>array("name_ru"=>"Фигейра-да-Фош ","name_en"=>"Figueira da Foz","name_href" => "pt/population-of-figueira-da-foz","count" => "63372","real_id" =>37,),
"38"=>array("name_ru"=>"Лоле ","name_en"=>"Lola","name_href" => "pt/population-of-lola","count" => "62300","real_id" =>38,),
"39"=>array("name_ru"=>"Амаранти ","name_en"=>"Amarante","name_href" => "pt/population-of-amarante","count" => "61471","real_id" =>39,),
"40"=>array("name_ru"=>"Помбал ","name_en"=>"Pombal","name_href" => "pt/population-of-pombal","count" => "59471","real_id" =>40,),
"41"=>array("name_ru"=>"Фелгейраш ","name_en"=>"Felgueiras","name_href" => "pt/population-of-felgueiras","count" => "58922","real_id" =>41,),
"42"=>array("name_ru"=>"Фару ","name_en"=>"Faro","name_href" => "pt/population-of-faro","count" => "58664","real_id" =>42,),
"43"=>array("name_ru"=>"Эвора ","name_en"=>"Evora","name_href" => "pt/population-of-evora","count" => "55621","real_id" =>43,),
"44"=>array("name_ru"=>"Алкобаса","name_en"=>"Alcobaça","name_href" => "pt/population-of-alcobaça","count" => "55597","real_id" =>44,),
"45"=>array("name_ru"=>"Овар ","name_en"=>"Ovar","name_href" => "pt/population-of-ovar","count" => "55198","real_id" =>45,),
"46"=>array("name_ru"=>"Пасуш-ди-Феррейра","name_en"=>"PACOS-de-Ferreira","name_href" => "pt/population-of-pacos-de-ferreira","count" => "54801","real_id" =>46,),
"47"=>array("name_ru"=>"Каштелу-Бранку ","name_en"=>"Castelo Branco","name_href" => "pt/population-of-castelo-branco","count" => "54574","real_id" =>47,),
"48"=>array("name_ru"=>"Ковильян ","name_en"=>"Covilha","name_href" => "pt/population-of-covilha","count" => "54505","real_id" =>48,),
"49"=>array("name_ru"=>"Марку-ди-Канавезиш ","name_en"=>"Mark di Canaveses","name_href" => "pt/population-of-mark-di-canaveses","count" => "53961","real_id" =>49,),
"50"=>array("name_ru"=>"Фафи ","name_en"=>"Fafe","name_href" => "pt/population-of-fafe","count" => "53780","real_id" =>50,),
"51"=>array("name_ru"=>"Калдаш-да-Раинья ","name_en"=>"Caldas da Rainha","name_href" => "pt/population-of-caldas-da-rainha","count" => "52270","real_id" =>51,),
"52"=>array("name_ru"=>"Амора ","name_en"=>"Amor","name_href" => "pt/population-of-amor","count" => "50991","real_id" =>52,),
"53"=>array("name_ru"=>"Вила-Реал ","name_en"=>"Vila Real","name_href" => "pt/population-of-vila-real","count" => "49957","real_id" =>53,),
"54"=>array("name_ru"=>"Агеда ","name_en"=>"Agueda","name_href" => "pt/population-of-agueda","count" => "49912","real_id" =>54,),
"55"=>array("name_ru"=>"Риу-Тинту ","name_en"=>"Rio Tinto","name_href" => "pt/population-of-rio-tinto","count" => "47695","real_id" =>55,),
"56"=>array("name_ru"=>"Оурен","name_en"=>"Ourém","name_href" => "pt/population-of-ourém","count" => "46196","real_id" =>56,),
"57"=>array("name_ru"=>"Понта-Делгада ","name_en"=>"Ponta Delgada","name_href" => "pt/population-of-ponta-delgada","count" => "46102","real_id" =>57,),
"58"=>array("name_ru"=>"Эрмезинде","name_en"=>"Ermesinde","name_href" => "pt/population-of-ermesinde","count" => "45000","real_id" =>58,),
"59"=>array("name_ru"=>"Портиман ","name_en"=>"Portimao","name_href" => "pt/population-of-portimao","count" => "44818","real_id" =>59,),
"60"=>array("name_ru"=>"Гуарда ","name_en"=>"Guarda","name_href" => "pt/population-of-guarda","count" => "44264","real_id" =>60,),
"61"=>array("name_ru"=>"Шавиш ","name_en"=>"Chaves","name_href" => "pt/population-of-chaves","count" => "44186","real_id" =>61,),
"62"=>array("name_ru"=>"Томар ","name_en"=>"Tomar","name_href" => "pt/population-of-tomar","count" => "43007","real_id" =>62,),
"63"=>array("name_ru"=>"Ольян-да-Рештаурасан ","name_en"=>"Olhão-Yes-Restauracin","name_href" => "pt/population-of-olhão-yes-restauracin","count" => "40800","real_id" =>63,),
"64"=>array("name_ru"=>"Абрантиш ","name_en"=>"Abrantes","name_href" => "pt/population-of-abrantes","count" => "40700","real_id" =>64,),
"65"=>array("name_ru"=>"Ильяву ","name_en"=>"Ilhavo","name_href" => "pt/population-of-ilhavo","count" => "40349","real_id" =>65,),
"66"=>array("name_ru"=>"Трофа ","name_en"=>"In trofa","name_href" => "pt/population-of-in-trofa","count" => "40029","real_id" =>66,),
"67"=>array("name_ru"=>"Монтижу ","name_en"=>"Montijo","name_href" => "pt/population-of-montijo","count" => "39168","real_id" =>67,),
"68"=>array("name_ru"=>"Кантаньеди ","name_en"=>"Cantanhede","name_href" => "pt/population-of-cantanhede","count" => "38860","real_id" =>68,),
"69"=>array("name_ru"=>"Албуфейра ","name_en"=>"Albufeira","name_href" => "pt/population-of-albufeira","count" => "37244","real_id" =>69,),
"70"=>array("name_ru"=>"Торриш-Новаш ","name_en"=>"Torres Novas","name_href" => "pt/population-of-torres-novas","count" => "36908","real_id" =>70,),
"71"=>array("name_ru"=>"Ангра-ду-Эроишму","name_en"=>"Angra do heroísmo","name_href" => "pt/population-of-angra-do-heroísmo","count" => "35581","real_id" =>71,),
"72"=>array("name_ru"=>"Эшпозенди ","name_en"=>"Esposende","name_href" => "pt/population-of-esposende","count" => "35148","real_id" =>72,),
"73"=>array("name_ru"=>"Бежа","name_en"=>"Beja","name_href" => "pt/population-of-beja","count" => "34760","real_id" =>73,),
"74"=>array("name_ru"=>"Браганса ","name_en"=>"Braganca","name_href" => "pt/population-of-braganca","count" => "34628","real_id" =>74,),
"75"=>array("name_ru"=>"Камара-ди-Лобуш","name_en"=>"Câmara de Lobos","name_href" => "pt/population-of-câmara-de-lobos","count" => "34614","real_id" =>75,),
"76"=>array("name_ru"=>"Маринья-Гранди ","name_en"=>"Marinha Grande","name_href" => "pt/population-of-marinha-grande","count" => "34153","real_id" =>76,),
"77"=>array("name_ru"=>"Силвиш ","name_en"=>"Silves","name_href" => "pt/population-of-silves","count" => "33830","real_id" =>77,),
"78"=>array("name_ru"=>"Валбон ","name_en"=>"Valbom","name_href" => "pt/population-of-valbom","count" => "32567","real_id" =>78,),
"79"=>array("name_ru"=>"Фундан ","name_en"=>"Fundao","name_href" => "pt/population-of-fundao","count" => "31176","real_id" =>79,),
"80"=>array("name_ru"=>"Тондела ","name_en"=>"Tondela","name_href" => "pt/population-of-tondela","count" => "31152","real_id" =>80,),
"81"=>array("name_ru"=>"Эшпинью ","name_en"=>"Espinho","name_href" => "pt/population-of-espinho","count" => "30649","real_id" =>81,),
"82"=>array("name_ru"=>"Сантьягу-ду-Касен ","name_en"=>"Santiago do Cacem","name_href" => "pt/population-of-santiago-do-cacem","count" => "30200","real_id" =>82,),
"83"=>array("name_ru"=>"Санта-Круш ","name_en"=>"Santa Cruz","name_href" => "pt/population-of-santa-cruz","count" => "29721","real_id" =>83,),
"84"=>array("name_ru"=>"Алверка-ду-Рибатежу ","name_en"=>"Alverca do Ribatejo","name_href" => "pt/population-of-alverca-do-ribatejo","count" => "29086","real_id" =>84,),
"85"=>array("name_ru"=>"Рибейра-Гранде ","name_en"=>"Ribeira Grande","name_href" => "pt/population-of-ribeira-grande","count" => "28462","real_id" =>85,),
"86"=>array("name_ru"=>"Эштаррежа ","name_en"=>"There","name_href" => "pt/population-of-there","count" => "28332","real_id" =>86,),
"87"=>array("name_ru"=>"Сейя ","name_en"=>"Seiya","name_href" => "pt/population-of-seiya","count" => "28145","real_id" =>87,),
"88"=>array("name_ru"=>"Пениши ","name_en"=>"Peniche","name_href" => "pt/population-of-peniche","count" => "27315","real_id" =>88,),
"89"=>array("name_ru"=>"Лагуш ","name_en"=>"Lagos","name_href" => "pt/population-of-lagos","count" => "27040","real_id" =>89,),
"90"=>array("name_ru"=>"Сеньора-да-Ора ","name_en"=>"Senhora da Oura","name_href" => "pt/population-of-senhora-da-oura","count" => "26543","real_id" =>90,),
"91"=>array("name_ru"=>"Ламегу","name_en"=>"Lamego","name_href" => "pt/population-of-lamego","count" => "26484","real_id" =>91,),
"92"=>array("name_ru"=>"Келуш ","name_en"=>"Queluz","name_href" => "pt/population-of-queluz","count" => "26248","real_id" =>92,),
"93"=>array("name_ru"=>"Порталегри ","name_en"=>"Portalegre","name_href" => "pt/population-of-portalegre","count" => "25981","real_id" =>93,),
"94"=>array("name_ru"=>"Мирандела ","name_en"=>"Mirandela","name_href" => "pt/population-of-mirandela","count" => "25742","real_id" =>94,),
"95"=>array("name_ru"=>"Тавира ","name_en"=>"Tavira","name_href" => "pt/population-of-tavira","count" => "25000","real_id" =>95,),
"96"=>array("name_ru"=>"Вали-ди-Камбра ","name_en"=>"Wali di Cambra","name_href" => "pt/population-of-wali-di-cambra","count" => "24798","real_id" =>96,),
"97"=>array("name_ru"=>"Карташу","name_en"=>"Cartaxo","name_href" => "pt/population-of-cartaxo","count" => "24458","real_id" =>97,),
"98"=>array("name_ru"=>"Повуа-де-Санта-Ирия ","name_en"=>"Povoa de Santa Iria","name_href" => "pt/population-of-povoa-de-santa-iria","count" => "24277","real_id" =>98,),
"99"=>array("name_ru"=>"Лагоа ","name_en"=>"Lagoa","name_href" => "pt/population-of-lagoa","count" => "23835","real_id" =>99,),
"100"=>array("name_ru"=>"Сан-Мамеде-де-Инфешта ","name_en"=>"Sao Mamede de Infesta","name_href" => "pt/population-of-sao-mamede-de-infesta","count" => "23542","real_id" =>100,),
"101"=>array("name_ru"=>"Визела ","name_en"=>"Wiesel","name_href" => "pt/population-of-wiesel","count" => "23528","real_id" =>101,),
"102"=>array("name_ru"=>"Алмейрин ","name_en"=>"Almeirim","name_href" => "pt/population-of-almeirim","count" => "23376","real_id" =>102,),
"103"=>array("name_ru"=>"Элваш ","name_en"=>"Elvas","name_href" => "pt/population-of-elvas","count" => "22477","real_id" =>103,),
"104"=>array("name_ru"=>"Оливейра-ду-Ошпитал ","name_en"=>"Oliveira do Hospital","name_href" => "pt/population-of-oliveira-do-hospital","count" => "22112","real_id" =>104,),
"105"=>array("name_ru"=>"Машику ","name_en"=>"Machico","name_href" => "pt/population-of-machico","count" => "21747","real_id" =>105,),
"106"=>array("name_ru"=>"Оливейра-ду-Байру","name_en"=>"Oliveira do Bairro","name_href" => "pt/population-of-oliveira-do-bairro","count" => "21164","real_id" =>106,),
"107"=>array("name_ru"=>"Риу-Майор ","name_en"=>"Rio Maior","name_href" => "pt/population-of-rio-maior","count" => "21110","real_id" =>107,),
"108"=>array("name_ru"=>"Сан-Жуан-да-Мадейра ","name_en"=>"Sao Joao da Madeira","name_href" => "pt/population-of-sao-joao-da-madeira","count" => "21102","real_id" =>108,),
"109"=>array("name_ru"=>"Мангуалди ","name_en"=>"Mangualde","name_href" => "pt/population-of-mangualde","count" => "20990","real_id" =>109,),
"110"=>array("name_ru"=>"Энтронкаменту ","name_en"=>"Entroncamento","name_href" => "pt/population-of-entroncamento","count" => "20896","real_id" =>110,),
"111"=>array("name_ru"=>"Меальяда ","name_en"=>"Mealhada","name_href" => "pt/population-of-mealhada","count" => "20751","real_id" =>111,),
"112"=>array("name_ru"=>"Прая-да-Витория","name_en"=>"Praia da Vitoria","name_href" => "pt/population-of-praia-da-vitoria","count" => "20252","real_id" =>112,),
"113"=>array("name_ru"=>"Валпасуш ","name_en"=>"Valpacos","name_href" => "pt/population-of-valpacos","count" => "19512","real_id" =>113,),
"114"=>array("name_ru"=>"Сан-Педру-ду-Сул ","name_en"=>"Sao Pedro do Sul","name_href" => "pt/population-of-sao-pedro-do-sul","count" => "19083","real_id" =>114,),
"115"=>array("name_ru"=>"Монтемор-у-Нову ","name_en"=>"Montemor-o-Novo","name_href" => "pt/population-of-montemor-o-novo","count" => "18540","real_id" =>115,),
"116"=>array("name_ru"=>"Сакавен","name_en"=>"Sacavem","name_href" => "pt/population-of-sacavem","count" => "18469","real_id" =>116,),
"117"=>array("name_ru"=>"Маседу-ди-Кавалейруш ","name_en"=>"Macedo de cavaleiros","name_href" => "pt/population-of-macedo-de-cavaleiros","count" => "18449","real_id" =>117,),
"118"=>array("name_ru"=>"Понти-ди-Сор ","name_en"=>"Ponte de SOR","name_href" => "pt/population-of-ponte-de-sor","count" => "18140","real_id" =>118,),
"119"=>array("name_ru"=>"Вила-Реал-ди-Санту-Антониу ","name_en"=>"Vila real di Santo Antonio","name_href" => "pt/population-of-vila-real-di-santo-antonio","count" => "17956","real_id" =>119,),
"120"=>array("name_ru"=>"Пезу-да-Регуа","name_en"=>"The peso-da-Regua","name_href" => "pt/population-of-the-peso-da-regua","count" => "17492","real_id" =>120,),
"121"=>array("name_ru"=>"Серпа","name_en"=>"Sickle","name_href" => "pt/population-of-sickle","count" => "16180","real_id" =>121,),
"122"=>array("name_ru"=>"Картейра","name_en"=>"Quarteira","name_href" => "pt/population-of-quarteira","count" => "16131","real_id" =>122,),
"123"=>array("name_ru"=>"Эштремош ","name_en"=>"Estremoz","name_href" => "pt/population-of-estremoz","count" => "15673","real_id" =>123,),
"124"=>array("name_ru"=>"Говея ","name_en"=>"Gouveia","name_href" => "pt/population-of-gouveia","count" => "15628","real_id" =>124,),
"125"=>array("name_ru"=>"Орта ","name_en"=>"Orta","name_href" => "pt/population-of-orta","count" => "15063","real_id" =>125,),
"126"=>array("name_ru"=>"Валенса ","name_en"=>"Walesa","name_href" => "pt/population-of-walesa","count" => "14187","real_id" =>126,),
"127"=>array("name_ru"=>"Гафанья-да-Назарэ ","name_en"=>"Of Aveiro-de-Nazare","name_href" => "pt/population-of-of-aveiro-de-nazare","count" => "14021","real_id" =>127,),
"128"=>array("name_ru"=>"Сабугал ","name_en"=>"Sabugal","name_href" => "pt/population-of-sabugal","count" => "13769","real_id" =>128,),
"129"=>array("name_ru"=>"Алкасер-ду-Сал ","name_en"=>"Alcácer do Sal","name_href" => "pt/population-of-alcácer-do-sal","count" => "13354","real_id" =>129,),
"130"=>array("name_ru"=>"Самора-Коррейя ","name_en"=>"Samora Correia","name_href" => "pt/population-of-samora-correia","count" => "12826","real_id" =>130,),
"131"=>array("name_ru"=>"Санта-Комба-Дан","name_en"=>"Santa Comba Dão","name_href" => "pt/population-of-santa-comba-dão","count" => "12473","real_id" =>131,),
"132"=>array("name_ru"=>"Вендаш-Новаш","name_en"=>"Vendas Novas","name_href" => "pt/population-of-vendas-novas","count" => "11957","real_id" =>132,),
"133"=>array("name_ru"=>"Кошта-да-Капарика","name_en"=>"Costa da Caparica","name_href" => "pt/population-of-costa-da-caparica","count" => "11707","real_id" =>133,),
"134"=>array("name_ru"=>"Канису ","name_en"=>"Canico","name_href" => "pt/population-of-canico","count" => "11586","real_id" =>134,),
"135"=>array("name_ru"=>"Регенгуш-ди-Монсараш","name_en"=>"Of Sanxenxo di Monsaraz","name_href" => "pt/population-of-of-sanxenxo-di-monsaraz","count" => "11460","real_id" =>135,),
"136"=>array("name_ru"=>"Эшмориш ","name_en"=>"Esmoriz","name_href" => "pt/population-of-esmoriz","count" => "10993","real_id" =>136,),
"137"=>array("name_ru"=>"Транкозу ","name_en"=>"Trancoso","name_href" => "pt/population-of-trancoso","count" => "10889","real_id" =>137,),
"138"=>array("name_ru"=>"Ребордоза","name_en"=>"Rebordosa","name_href" => "pt/population-of-rebordosa","count" => "10813","real_id" =>138,),
"139"=>array("name_ru"=>"Вила-Нова-ди-Санту-Андре ","name_en"=>"Vila Nova de Santo andré","name_href" => "pt/population-of-vila-nova-de-santo-andré","count" => "10696","real_id" =>139,),
"140"=>array("name_ru"=>"Фатима","name_en"=>"Fatima","name_href" => "pt/population-of-fatima","count" => "10302","real_id" =>140,),
"141"=>array("name_ru"=>"Пиньел ","name_en"=>"Pingel","name_href" => "pt/population-of-pingel","count" => "10182","real_id" =>141,),
"142"=>array("name_ru"=>"Лороза ","name_en"=>"Larosa","name_href" => "pt/population-of-larosa","count" => "10000","real_id" =>142,),
"143"=>array("name_ru"=>"Сан-Салвадор-ди-Лорделу ","name_en"=>"San Salvador di Lordelo ","name_href" => "pt/population-of-san-salvador-di-lordelo-","count" => "9930","real_id" =>143,),
"144"=>array("name_ru"=>"Сантана ","name_en"=>"Santana","name_href" => "pt/population-of-santana","count" => "8804","real_id" =>144,),
"145"=>array("name_ru"=>"Фиайнш ","name_en"=>"Veins","name_href" => "pt/population-of-veins","count" => "8754","real_id" =>145,),
"146"=>array("name_ru"=>"Вила-Нова-ди-Фош-Коа ","name_en"=>"Vila Nova de Foz COA","name_href" => "pt/population-of-vila-nova-de-foz-coa","count" => "8494","real_id" =>146,),
"147"=>array("name_ru"=>"Тарока ","name_en"=>"Tarouca","name_href" => "pt/population-of-tarouca","count" => "8308","real_id" =>147,),
"148"=>array("name_ru"=>"Миранда-ду-Дору ","name_en"=>"Miranda do Douro","name_href" => "pt/population-of-miranda-do-douro","count" => "8048","real_id" =>148,),
"149"=>array("name_ru"=>"Борба ","name_en"=>"Borba","name_href" => "pt/population-of-borba","count" => "7540","real_id" =>149,),
"150"=>array("name_ru"=>"Фреамунде ","name_en"=>"Freamunde","name_href" => "pt/population-of-freamunde","count" => "7452","real_id" =>150,),
"151"=>array("name_ru"=>"Мора ","name_en"=>"Mora","name_href" => "pt/population-of-mora","count" => "5470","real_id" =>151,),
"152"=>array("name_ru"=>"Вила-Балейра ","name_en"=>"Vila Baleira","name_href" => "pt/population-of-vila-baleira","count" => "4474","real_id" =>152,),
"153"=>array("name_ru"=>"Лиша ","name_en"=>"Lisha","name_href" => "pt/population-of-lisha","count" => "4233","real_id" =>153,),
"154"=>array("name_ru"=>"Сагреш ","name_en"=>"Sagres","name_href" => "pt/population-of-sagres","count" => "1939","real_id" =>154,),
"155"=>array("name_ru"=>"Гандра ","name_en"=>"Gandra","name_href" => "pt/population-of-gandra","count" => "1 141","real_id" =>155,),
"156"=>array("name_ru"=>"Лиссабон ","name_en"=>"Lisbon","name_href" => "pt/population-of-lisbon","count" => "547733","real_id" =>156,),
"157"=>array("name_ru"=>"Порту ","name_en"=>"Port","name_href" => "pt/population-of-port","count" => "221800","real_id" =>157,),
"158"=>array("name_ru"=>"Лореш ","name_en"=>"Loures","name_href" => "pt/population-of-loures","count" => "205054","real_id" =>158,),
"159"=>array("name_ru"=>"Вила-Нова-ди-Гая ","name_en"=>"Vila Nova de Gaia","name_href" => "pt/population-of-vila-nova-de-gaia","count" => "178300","real_id" =>159,),
"160"=>array("name_ru"=>"Амадора ","name_en"=>"Amador","name_href" => "pt/population-of-amador","count" => "175135","real_id" =>160,)
);

?>