<?php
//Румыния 266
$libro = array ( 
"1"=>array("name_ru"=>"Бухарест","name_en"=>"Bucharest","name_href" => "ro/population-of-bucharest","count" => "2 354 510","real_id" =>1,),
"2"=>array("name_ru"=>"Яссы","name_en"=>"Iasi","name_href" => "ro/population-of-iasi","count" => "340 580","real_id" =>2,),
"3"=>array("name_ru"=>"Клуж-Напока","name_en"=>"Cluj-Napoca","name_href" => "ro/population-of-cluj-napoca","count" => "318 027","real_id" =>3,),
"4"=>array("name_ru"=>"Тимишоара","name_en"=>"Timisoara","name_href" => "ro/population-of-timisoara","count" => "317 651","real_id" =>4,),
"5"=>array("name_ru"=>"Констанца","name_en"=>"Constanta","name_href" => "ro/population-of-constanta","count" => "283 872","real_id" =>5,),
"6"=>array("name_ru"=>"Крайова","name_en"=>"Craiova","name_href" => "ro/population-of-craiova","count" => "302 622","real_id" =>6,),
"7"=>array("name_ru"=>"Галац","name_en"=>"Galati","name_href" => "ro/population-of-galati","count" => "298 584","real_id" =>7,),
"8"=>array("name_ru"=>"Брашов","name_en"=>"Brasov","name_href" => "ro/population-of-brasov","count" => "283 901","real_id" =>8,),
"9"=>array("name_ru"=>"Плоешти","name_en"=>"Ploiesti","name_href" => "ro/population-of-ploiesti","count" => "232 452","real_id" =>9,),
"10"=>array("name_ru"=>"Брэила","name_en"=>"Braila","name_href" => "ro/population-of-braila","count" => "216 929","real_id" =>10,),
"11"=>array("name_ru"=>"Орадя","name_en"=>"Oradea","name_href" => "ro/population-of-oradea","count" => "206 527","real_id" =>11,),
"12"=>array("name_ru"=>"Бакэу","name_en"=>"Bacau","name_href" => "ro/population-of-bacau","count" => "204 500","real_id" =>12,),
"13"=>array("name_ru"=>"Арад","name_en"=>"Arad","name_href" => "ro/population-of-arad","count" => "172 824","real_id" =>13,),
"14"=>array("name_ru"=>"Питешти","name_en"=>"Pitesti","name_href" => "ro/population-of-pitesti","count" => "168 756","real_id" =>14,),
"15"=>array("name_ru"=>"Сибиу","name_en"=>"Sibiu","name_href" => "ro/population-of-sibiu","count" => "155 045","real_id" =>15,),
"16"=>array("name_ru"=>"Тыргу-Муреш","name_en"=>"Târgu-Mureş","name_href" => "ro/population-of-târgu-mureş","count" => "149 577","real_id" =>16,),
"17"=>array("name_ru"=>"Бая-Маре","name_en"=>"Baia Mare","name_href" => "ro/population-of-baia-mare","count" => "137 976","real_id" =>17,),
"18"=>array("name_ru"=>"Бузэу","name_en"=>"Buzau","name_href" => "ro/population-of-buzau","count" => "133 116","real_id" =>18,),
"19"=>array("name_ru"=>"Сату-Маре","name_en"=>"Satu Mare","name_href" => "ro/population-of-satu-mare","count" => "115 630","real_id" =>19,),
"20"=>array("name_ru"=>"Ботошани","name_en"=>"Botosani","name_href" => "ro/population-of-botosani","count" => "115 344","real_id" =>20,),
"21"=>array("name_ru"=>"Рымнику-Вылча","name_en"=>"Râmnicu Vâlcea","name_href" => "ro/population-of-râmnicu-vâlcea","count" => "107 656","real_id" =>21,),
"22"=>array("name_ru"=>"Сучава","name_en"=>"Suceava","name_href" => "ro/population-of-suceava","count" => "106 138","real_id" =>22,),
"23"=>array("name_ru"=>"Пьятра-Нямц","name_en"=>"Piatra Neamţ","name_href" => "ro/population-of-piatra-neamţ","count" => "105 499","real_id" =>23,),
"24"=>array("name_ru"=>"Дробета-Турну-Северин","name_en"=>"Drobeta-Turnu Severin","name_href" => "ro/population-of-drobeta-turnu-severin","count" => "104 035","real_id" =>24,),
"25"=>array("name_ru"=>"Фокшаны","name_en"=>"Focsani","name_href" => "ro/population-of-focsani","count" => "103 219","real_id" =>25,),
"26"=>array("name_ru"=>"Тыргу-Жиу","name_en"=>"Târgu JIU","name_href" => "ro/population-of-târgu-jiu","count" => "96 562","real_id" =>26,),
"27"=>array("name_ru"=>"Тулча","name_en"=>"Tulcea","name_href" => "ro/population-of-tulcea","count" => "92 762","real_id" =>27,),
"28"=>array("name_ru"=>"Тырговиште","name_en"=>"Targovishte","name_href" => "ro/population-of-targovishte","count" => "89 429","real_id" =>28,),
"29"=>array("name_ru"=>"Решица","name_en"=>"Resita","name_href" => "ro/population-of-resita","count" => "83 985","real_id" =>29,),
"30"=>array("name_ru"=>"Бистрица","name_en"=>"Bistrita","name_href" => "ro/population-of-bistrita","count" => "81 467","real_id" =>30,),
"31"=>array("name_ru"=>"Слатина","name_en"=>"Slatina","name_href" => "ro/population-of-slatina","count" => "79 171","real_id" =>31,),
"32"=>array("name_ru"=>"Хунедоара","name_en"=>"Hunedoara","name_href" => "ro/population-of-hunedoara","count" => "71 380","real_id" =>32,),
"33"=>array("name_ru"=>"Васлуй","name_en"=>"Vaslui","name_href" => "ro/population-of-vaslui","count" => "70 267","real_id" =>33,),
"34"=>array("name_ru"=>"Кэлэраши","name_en"=>"Calarasi","name_href" => "ro/population-of-calarasi","count" => "70 046","real_id" =>34,),
"35"=>array("name_ru"=>"Джурджу","name_en"=>"Giurgiu","name_href" => "ro/population-of-giurgiu","count" => "69 587","real_id" =>35,),
"36"=>array("name_ru"=>"Роман","name_en"=>"Novel","name_href" => "ro/population-of-novel","count" => "69 483","real_id" =>36,),
"37"=>array("name_ru"=>"Дева","name_en"=>"Virgin","name_href" => "ro/population-of-virgin","count" => "69 390","real_id" =>37,),
"38"=>array("name_ru"=>"Бырлад","name_en"=>"Bârlad","name_href" => "ro/population-of-bârlad","count" => "69 183","real_id" =>38,),
"39"=>array("name_ru"=>"Алба-Юлия","name_en"=>"Alba Iulia","name_href" => "ro/population-of-alba-iulia","count" => "66 369","real_id" =>39,),
"40"=>array("name_ru"=>"Залэу","name_en"=>"Zalău","name_href" => "ro/population-of-zalău","count" => "63 642","real_id" =>40,),
"41"=>array("name_ru"=>"Сфынту-Георге","name_en"=>"Sfântu-Gheorghe","name_href" => "ro/population-of-sfântu-gheorghe","count" => "61 701","real_id" =>41,),
"42"=>array("name_ru"=>"Турда","name_en"=>"Turda","name_href" => "ro/population-of-turda","count" => "55 770","real_id" =>42,),
"43"=>array("name_ru"=>"Медиаш","name_en"=>"Mediaş","name_href" => "ro/population-of-mediaş","count" => "53 564","real_id" =>43,),
"44"=>array("name_ru"=>"Слобозия","name_en"=>"Slobozia","name_href" => "ro/population-of-slobozia","count" => "52 677","real_id" =>44,),
"45"=>array("name_ru"=>"Онешти","name_en"=>"Onesti","name_href" => "ro/population-of-onesti","count" => "51 681","real_id" =>45,),
"46"=>array("name_ru"=>"Александрия","name_en"=>"Alexandria","name_href" => "ro/population-of-alexandria","count" => "50 591","real_id" =>46,),
"47"=>array("name_ru"=>"Петрошани","name_en"=>"Petrosani","name_href" => "ro/population-of-petrosani","count" => "45 447","real_id" =>47,),
"48"=>array("name_ru"=>"Лугож","name_en"=>"Lugoj","name_href" => "ro/population-of-lugoj","count" => "44 571","real_id" =>48,),
"49"=>array("name_ru"=>"Меджидия","name_en"=>"Medgidia","name_href" => "ro/population-of-medgidia","count" => "43 867","real_id" =>49,),
"50"=>array("name_ru"=>"Пашкани","name_en"=>"Pascani","name_href" => "ro/population-of-pascani","count" => "42 172","real_id" =>50,),
"51"=>array("name_ru"=>"Текуч","name_en"=>"Fluid","name_href" => "ro/population-of-fluid","count" => "42 012","real_id" =>51,),
"52"=>array("name_ru"=>"Меркуря-Чук","name_en"=>"Miercurea-Ciuc","name_href" => "ro/population-of-miercurea-ciuc","count" => "41 852","real_id" =>52,),
"53"=>array("name_ru"=>"Сигету-Мармацией","name_en"=>"Sighetu Marmatiei","name_href" => "ro/population-of-sighetu-marmatiei","count" => "41 246","real_id" =>53,),
"54"=>array("name_ru"=>"Мангалия","name_en"=>"Mangalia","name_href" => "ro/population-of-mangalia","count" => "40 037","real_id" =>54,),
"55"=>array("name_ru"=>"Рымнику-Сэрат","name_en"=>"Ramnicu Sarat","name_href" => "ro/population-of-ramnicu-sarat","count" => "38 805","real_id" =>55,),
"56"=>array("name_ru"=>"Кымпина","name_en"=>"Campina","name_href" => "ro/population-of-campina","count" => "38 758","real_id" =>56,),
"57"=>array("name_ru"=>"Деж","name_en"=>"Dej","name_href" => "ro/population-of-dej","count" => "38 478","real_id" =>57,),
"58"=>array("name_ru"=>"Кымпулунг-Мусчел","name_en"=>"Câmpulung-Muscel","name_href" => "ro/population-of-câmpulung-muscel","count" => "38 285","real_id" =>58,),
"59"=>array("name_ru"=>"Одорхею-Секуйеск","name_en"=>"Odorheiu Secuiesc","name_href" => "ro/population-of-odorheiu-secuiesc","count" => "36 926","real_id" =>59,),
"60"=>array("name_ru"=>"Регин","name_en"=>"Regin","name_href" => "ro/population-of-regin","count" => "36 023","real_id" =>60,),
"61"=>array("name_ru"=>"Миовени","name_en"=>"Mioveni","name_href" => "ro/population-of-mioveni","count" => "35 849","real_id" =>61,),
"62"=>array("name_ru"=>"Фэгэраш","name_en"=>"Fagaras","name_href" => "ro/population-of-fagaras","count" => "35 759","real_id" =>62,),
"63"=>array("name_ru"=>"Каракал","name_en"=>"Caracal","name_href" => "ro/population-of-caracal","count" => "34 603","real_id" =>63,),
"64"=>array("name_ru"=>"Фетешти","name_en"=>"Fetesti","name_href" => "ro/population-of-fetesti","count" => "33 197","real_id" =>64,),
"65"=>array("name_ru"=>"Куртя-де-Арджеш","name_en"=>"Curtea de Arges","name_href" => "ro/population-of-curtea-de-arges","count" => "32 626","real_id" =>65,),
"66"=>array("name_ru"=>"Нэводари","name_en"=>"Năvodari","name_href" => "ro/population-of-năvodari","count" => "32 400","real_id" =>66,),
"67"=>array("name_ru"=>"Сигишоара","name_en"=>"Sighisoara","name_href" => "ro/population-of-sighisoara","count" => "32 287","real_id" =>67,),
"68"=>array("name_ru"=>"Рошиорий-де-Веде","name_en"=>"Rosiori de vede","name_href" => "ro/population-of-rosiori-de-vede","count" => "31 873","real_id" =>68,),
"69"=>array("name_ru"=>"Дорохой","name_en"=>"Dorohoi","name_href" => "ro/population-of-dorohoi","count" => "31 073","real_id" =>69,),
"70"=>array("name_ru"=>"Турну-Мэгуреле","name_en"=>"Turnu Magurele","name_href" => "ro/population-of-turnu-magurele","count" => "30 187","real_id" =>70,),
"71"=>array("name_ru"=>"Фэлтичени","name_en"=>"Falticeni","name_href" => "ro/population-of-falticeni","count" => "33 867","real_id" =>71,),
"72"=>array("name_ru"=>"Хуши","name_en"=>"Husi","name_href" => "ro/population-of-husi","count" => "33 320","real_id" =>72,),
"73"=>array("name_ru"=>"Вулкан","name_en"=>"The volcano","name_href" => "ro/population-of-the-volcano","count" => "33 186","real_id" =>73,),
"74"=>array("name_ru"=>"Рэдэуци","name_en"=>"Radauti","name_href" => "ro/population-of-radauti","count" => "32 151","real_id" =>74,),
"75"=>array("name_ru"=>"Олтеница","name_en"=>"Oltenita","name_href" => "ro/population-of-oltenita","count" => "31 434","real_id" =>75,),
"76"=>array("name_ru"=>"Лупени","name_en"=>"Lupeni","name_href" => "ro/population-of-lupeni","count" => "31 409","real_id" =>76,),
"77"=>array("name_ru"=>"Карансебеш","name_en"=>"Caransebes","name_href" => "ro/population-of-caransebes","count" => "31 199","real_id" =>77,),
"78"=>array("name_ru"=>"Куджир","name_en"=>"Cugir","name_href" => "ro/population-of-cugir","count" => "26 146","real_id" =>78,),
"79"=>array("name_ru"=>"Сэчеле","name_en"=>"Săcele","name_href" => "ro/population-of-săcele","count" => "31 796","real_id" =>79,),
"80"=>array("name_ru"=>"Кымпия-Турзи","name_en"=>"Kampia-Tursi","name_href" => "ro/population-of-kampia-tursi","count" => "29 852","real_id" =>80,),
"81"=>array("name_ru"=>"Тырнэвени","name_en"=>"Tirnaveni","name_href" => "ro/population-of-tirnaveni","count" => "29 828","real_id" =>81,),
"82"=>array("name_ru"=>"Себеш","name_en"=>"Sebes","name_href" => "ro/population-of-sebes","count" => "29 475","real_id" =>82,),
"83"=>array("name_ru"=>"Аюд","name_en"=>"Aiud","name_href" => "ro/population-of-aiud","count" => "28 909","real_id" =>83,),
"84"=>array("name_ru"=>"Петрила","name_en"=>"Petrila","name_href" => "ro/population-of-petrila","count" => "28 742","real_id" =>84,),
"85"=>array("name_ru"=>"Борша","name_en"=>"Borsa","name_href" => "ro/population-of-borsa","count" => "27 247","real_id" =>85,),
"86"=>array("name_ru"=>"Зэрнешти","name_en"=>"Zarnesti","name_href" => "ro/population-of-zarnesti","count" => "26 520","real_id" =>86,),
"87"=>array("name_ru"=>"Комэнешти","name_en"=>"Comanesti","name_href" => "ro/population-of-comanesti","count" => "26 237","real_id" =>87,),
"88"=>array("name_ru"=>"Мотру","name_en"=>"Motru","name_href" => "ro/population-of-motru","count" => "25 860","real_id" =>88,),
"89"=>array("name_ru"=>"Карей","name_en"=>"Brown","name_href" => "ro/population-of-brown","count" => "25 590","real_id" =>89,),
"90"=>array("name_ru"=>"Мойнешти","name_en"=>"Moinesti","name_href" => "ro/population-of-moinesti","count" => "25 532","real_id" =>90,),
"91"=>array("name_ru"=>"Кодля","name_en"=>"Codlea","name_href" => "ro/population-of-codlea","count" => "24 814","real_id" =>91,),
"92"=>array("name_ru"=>"Орэштие","name_en"=>"Orastie","name_href" => "ro/population-of-orastie","count" => "24 354","real_id" =>92,),
"93"=>array("name_ru"=>"Герла","name_en"=>"Gherla","name_href" => "ro/population-of-gherla","count" => "24 232","real_id" =>93,),
"94"=>array("name_ru"=>"Балш","name_en"=>"Bals","name_href" => "ro/population-of-bals","count" => "23 147","real_id" =>94,),
"95"=>array("name_ru"=>"Морени","name_en"=>"Moreni","name_href" => "ro/population-of-moreni","count" => "22 868","real_id" =>95,),
"96"=>array("name_ru"=>"Тыргу-Нямц","name_en"=>"Tirgu Neamt","name_href" => "ro/population-of-tirgu-neamt","count" => "22 634","real_id" =>96,),
"97"=>array("name_ru"=>"Дрэгэшани","name_en"=>"Dragasani","name_href" => "ro/population-of-dragasani","count" => "22 499","real_id" =>97,),
"98"=>array("name_ru"=>"Тыргу-Секуйеск","name_en"=>"Târgu Secuiesc","name_href" => "ro/population-of-târgu-secuiesc","count" => "22 251","real_id" =>98,),
"99"=>array("name_ru"=>"Бэйлешти","name_en"=>"Bailesti","name_href" => "ro/population-of-bailesti","count" => "22 231","real_id" =>99,),
"100"=>array("name_ru"=>"Бухуши","name_en"=>"Buhusi","name_href" => "ro/population-of-buhusi","count" => "21 993","real_id" =>100,),
"101"=>array("name_ru"=>"Корабия","name_en"=>"Corabia","name_href" => "ro/population-of-corabia","count" => "21 932","real_id" =>101,),
"102"=>array("name_ru"=>"Кымпулунг-Молдовенеск","name_en"=>"Câmpulung Moldovenesc","name_href" => "ro/population-of-câmpulung-moldovenesc","count" => "21 862","real_id" =>102,),
"103"=>array("name_ru"=>"Блаж","name_en"=>"Blessed","name_href" => "ro/population-of-blessed","count" => "21 819","real_id" =>103,),
"104"=>array("name_ru"=>"Георгени","name_en"=>"Gheorgheni","name_href" => "ro/population-of-gheorgheni","count" => "21 245","real_id" =>104,),
"105"=>array("name_ru"=>"Калафат","name_en"=>"Calafat","name_href" => "ro/population-of-calafat","count" => "21 227","real_id" =>105,),
"106"=>array("name_ru"=>"Аджуд","name_en"=>"Adjud","name_href" => "ro/population-of-adjud","count" => "20 776","real_id" =>106,),
"107"=>array("name_ru"=>"Чернаводэ","name_en"=>"Cernavoda","name_href" => "ro/population-of-cernavoda","count" => "20 514","real_id" =>107,),
"108"=>array("name_ru"=>"Бэйкой","name_en"=>"Baicoi","name_href" => "ro/population-of-baicoi","count" => "20 234","real_id" =>108,),
"109"=>array("name_ru"=>"Филиаши","name_en"=>"Filiasi","name_href" => "ro/population-of-filiasi","count" => "20 159","real_id" =>109,),
"110"=>array("name_ru"=>"Салонта","name_en"=>"Salonta","name_href" => "ro/population-of-salonta","count" => "20 006","real_id" =>110,),
"111"=>array("name_ru"=>"Буфтя","name_en"=>"Buftea","name_href" => "ro/population-of-buftea","count" => "19 617","real_id" =>111,),
"112"=>array("name_ru"=>"Урзичени","name_en"=>"Urziceni","name_href" => "ro/population-of-urziceni","count" => "19 088","real_id" =>112,),
"113"=>array("name_ru"=>"Бокша","name_en"=>"Bocsa","name_href" => "ro/population-of-bocsa","count" => "19 023","real_id" =>113,),
"114"=>array("name_ru"=>"Бряза","name_en"=>"Braza","name_href" => "ro/population-of-braza","count" => "18 863","real_id" =>114,),
"115"=>array("name_ru"=>"Маргита","name_en"=>"Margate","name_href" => "ro/population-of-margate","count" => "18 650","real_id" =>115,),
"116"=>array("name_ru"=>"Лудуш","name_en"=>"Ludus","name_href" => "ro/population-of-ludus","count" => "18 647","real_id" =>116,),
"117"=>array("name_ru"=>"Вишеу-де-Сус","name_en"=>"Viseu de SUS","name_href" => "ro/population-of-viseu-de-sus","count" => "18 444","real_id" =>117,),
"118"=>array("name_ru"=>"Брад","name_en"=>"Brad","name_href" => "ro/population-of-brad","count" => "18 075","real_id" =>118,),
"119"=>array("name_ru"=>"Ватра-Дорней","name_en"=>"Vatra Dornei","name_href" => "ro/population-of-vatra-dornei","count" => "17 864","real_id" =>119,),
"120"=>array("name_ru"=>"Чиснэдие","name_en"=>"Cisnadie","name_href" => "ro/population-of-cisnadie","count" => "17 204","real_id" =>120,),
"121"=>array("name_ru"=>"Мизил","name_en"=>"Mizil","name_href" => "ro/population-of-mizil","count" => "17 075","real_id" =>121,),
"122"=>array("name_ru"=>"Шимлеу-Силванией","name_en"=>"Simleu Silvaniei","name_href" => "ro/population-of-simleu-silvaniei","count" => "17 053","real_id" =>122,),
"123"=>array("name_ru"=>"Топлица","name_en"=>"Toplica","name_href" => "ro/population-of-toplica","count" => "16 839","real_id" =>123,),
"124"=>array("name_ru"=>"Зимнича","name_en"=>"Zimnicea","name_href" => "ro/population-of-zimnicea","count" => "16 787","real_id" =>124,),
"125"=>array("name_ru"=>"Гура-Хуморулуй","name_en"=>"Gura Humorului","name_href" => "ro/population-of-gura-humorului","count" => "16 740","real_id" =>125,),
"126"=>array("name_ru"=>"Гэешти","name_en"=>"Gaesti","name_href" => "ro/population-of-gaesti","count" => "16 598","real_id" =>126,),
"127"=>array("name_ru"=>"Пучиоаса","name_en"=>"Pucioasa","name_href" => "ro/population-of-pucioasa","count" => "16 489","real_id" =>127,),
"128"=>array("name_ru"=>"Негрешти-Оаш","name_en"=>"Negresti-OAS","name_href" => "ro/population-of-negresti-oas","count" => "16 356","real_id" =>128,),
"129"=>array("name_ru"=>"Рышнов","name_en"=>"Rasnov","name_href" => "ro/population-of-rasnov","count" => "16 242","real_id" =>129,),
"130"=>array("name_ru"=>"Авриг","name_en"=>"Avrig","name_href" => "ro/population-of-avrig","count" => "16 215","real_id" =>130,),
"131"=>array("name_ru"=>"Бая-Сприе","name_en"=>"Baia-Sprie","name_href" => "ro/population-of-baia-sprie","count" => "15 735","real_id" =>131,),
"132"=>array("name_ru"=>"Окна-Муреш","name_en"=>"Ocna Mures","name_href" => "ro/population-of-ocna-mures","count" => "15 697","real_id" =>132,),
"133"=>array("name_ru"=>"Оршова","name_en"=>"Orsova","name_href" => "ro/population-of-orsova","count" => "15 379","real_id" =>133,),
"134"=>array("name_ru"=>"Оравица","name_en"=>"Oraviţa","name_href" => "ro/population-of-oraviţa","count" => "15 222","real_id" =>134,),
"135"=>array("name_ru"=>"Молдова-Ноуэ","name_en"=>"Moldova-Noua","name_href" => "ro/population-of-moldova-noua","count" => "15 112","real_id" =>135,),
"136"=>array("name_ru"=>"Кэлан","name_en"=>"Kelan","name_href" => "ro/population-of-kelan","count" => "14 714","real_id" =>136,),
"137"=>array("name_ru"=>"Синая","name_en"=>"Sinai","name_href" => "ro/population-of-sinai","count" => "14 636","real_id" =>137,),
"138"=>array("name_ru"=>"Цэндэрей","name_en"=>"Candara","name_href" => "ro/population-of-candara","count" => "14 591","real_id" =>138,),
"139"=>array("name_ru"=>"Симерия","name_en"=>"Simeria","name_href" => "ro/population-of-simeria","count" => "14 571","real_id" =>139,),
"140"=>array("name_ru"=>"Дэрмэнешти","name_en"=>"Darmanesti","name_href" => "ro/population-of-darmanesti","count" => "14 232","real_id" =>140,),
"141"=>array("name_ru"=>"Тыргу-Окна","name_en"=>"Tîrgu Ocna","name_href" => "ro/population-of-tîrgu-ocna","count" => "14 184","real_id" =>141,),
"142"=>array("name_ru"=>"Тыргу-Лэпуш","name_en"=>"Târgu-Lapus","name_href" => "ro/population-of-târgu-lapus","count" => "14 139","real_id" =>142,),
"143"=>array("name_ru"=>"Вэлений-де-Мунте","name_en"=>"Valenii de Munte","name_href" => "ro/population-of-valenii-de-munte","count" => "13 898","real_id" =>143,),
"144"=>array("name_ru"=>"Тыргу-Фрумос","name_en"=>"Tirgu Frumos","name_href" => "ro/population-of-tirgu-frumos","count" => "13 763","real_id" =>144,),
"145"=>array("name_ru"=>"Скорничешти","name_en"=>"Scornicesti","name_href" => "ro/population-of-scornicesti","count" => "13 751","real_id" =>145,),
"146"=>array("name_ru"=>"Комарник","name_en"=>"Comarnic","name_href" => "ro/population-of-comarnic","count" => "13 532","real_id" =>146,),
"147"=>array("name_ru"=>"Овидиу","name_en"=>"Ovidiu","name_href" => "ro/population-of-ovidiu","count" => "13 458","real_id" =>147,),
"148"=>array("name_ru"=>"Дрэгэнешти-Олт","name_en"=>"Draganesti-OLT","name_href" => "ro/population-of-draganesti-olt","count" => "13 181","real_id" =>148,),
"149"=>array("name_ru"=>"Оцелу-Рошу","name_en"=>"Ouzel-Rosu","name_href" => "ro/population-of-ouzel-rosu","count" => "13 128","real_id" =>149,),
"150"=>array("name_ru"=>"Мэрэшешти","name_en"=>"Marasesti","name_href" => "ro/population-of-marasesti","count" => "13 070","real_id" =>150,),
"151"=>array("name_ru"=>"Сынниколау-Маре","name_en"=>"Sinnicolau Mare","name_href" => "ro/population-of-sinnicolau-mare","count" => "13 007","real_id" =>151,),
"152"=>array("name_ru"=>"Янка","name_en"=>"Janka","name_href" => "ro/population-of-janka","count" => "12 886","real_id" =>152,),
"153"=>array("name_ru"=>"Нехою","name_en"=>"Nehoiu","name_href" => "ro/population-of-nehoiu","count" => "12 650","real_id" =>153,),
"154"=>array("name_ru"=>"Ровинари","name_en"=>"Rovinari","name_href" => "ro/population-of-rovinari","count" => "12 603","real_id" =>154,),
"155"=>array("name_ru"=>"Стрехая","name_en"=>"Strehaia","name_href" => "ro/population-of-strehaia","count" => "12 564","real_id" =>155,),
"156"=>array("name_ru"=>"Хацег","name_en"=>"Hateg","name_href" => "ro/population-of-hateg","count" => "12 507","real_id" =>156,),
"157"=>array("name_ru"=>"Виделе","name_en"=>"Videle","name_href" => "ro/population-of-videle","count" => "12 498","real_id" =>157,),
"158"=>array("name_ru"=>"Ковасна","name_en"=>"Covasna","name_href" => "ro/population-of-covasna","count" => "12 306","real_id" =>158,),
"159"=>array("name_ru"=>"Жибоу","name_en"=>"Jibou","name_href" => "ro/population-of-jibou","count" => "12 283","real_id" =>159,),
"160"=>array("name_ru"=>"Хырлэу","name_en"=>"Hirlau","name_href" => "ro/population-of-hirlau","count" => "12 260","real_id" =>160,),
"161"=>array("name_ru"=>"Совата","name_en"=>"Sovata","name_href" => "ro/population-of-sovata","count" => "12 219","real_id" =>161,),
"162"=>array("name_ru"=>"Урикани","name_en"=>"Uricani","name_href" => "ro/population-of-uricani","count" => "12 177","real_id" =>162,),
"163"=>array("name_ru"=>"Агнита","name_en"=>"Agnita","name_href" => "ro/population-of-agnita","count" => "12 115","real_id" =>163,),
"164"=>array("name_ru"=>"Костешти","name_en"=>"Costesti","name_href" => "ro/population-of-costesti","count" => "12 091","real_id" =>164,),
"165"=>array("name_ru"=>"Беюш","name_en"=>"Beius","name_href" => "ro/population-of-beius","count" => "12 089","real_id" =>165,),
"166"=>array("name_ru"=>"Беклян","name_en"=>"Beklan","name_href" => "ro/population-of-beklan","count" => "12 033","real_id" =>166,),
"167"=>array("name_ru"=>"Дарабани","name_en"=>"Darabani","name_href" => "ro/population-of-darabani","count" => "12 002","real_id" =>167,),
"168"=>array("name_ru"=>"Бумбешти-Жиу","name_en"=>"Bumbesti-JIU","name_href" => "ro/population-of-bumbesti-jiu","count" => "11 882","real_id" =>168,),
"169"=>array("name_ru"=>"Урлаци","name_en"=>"Urlaţi","name_href" => "ro/population-of-urlaţi","count" => "11 858","real_id" =>169,),
"170"=>array("name_ru"=>"Мэчин","name_en"=>"Machin","name_href" => "ro/population-of-machin","count" => "11 803","real_id" =>170,),
"171"=>array("name_ru"=>"Буштени","name_en"=>"Buşteni","name_href" => "ro/population-of-buşteni","count" => "11 787","real_id" =>171,),
"172"=>array("name_ru"=>"Болдешти-Скэени","name_en"=>"Boldesti-Scaeni","name_href" => "ro/population-of-boldesti-scaeni","count" => "11 505","real_id" =>172,),
"173"=>array("name_ru"=>"Липова","name_en"=>"Lipova","name_href" => "ro/population-of-lipova","count" => "11 491","real_id" =>173,),
"174"=>array("name_ru"=>"Болинтин-Вале","name_en"=>"Bolintin Vale","name_href" => "ro/population-of-bolintin-vale","count" => "11 464","real_id" =>174,),
"175"=>array("name_ru"=>"Нэсэуд","name_en"=>"Nasaud","name_href" => "ro/population-of-nasaud","count" => "11 365","real_id" =>175,),
"176"=>array("name_ru"=>"Кристуру-Секуеск","name_en"=>"Cristur Secuiesc","name_href" => "ro/population-of-cristur-secuiesc","count" => "11 291","real_id" =>176,),
"177"=>array("name_ru"=>"Хыршова","name_en"=>"HIRSOVA","name_href" => "ro/population-of-hirsova","count" => "11 198","real_id" =>177,),
"178"=>array("name_ru"=>"Мурфатлар","name_en"=>"Murfatlar","name_href" => "ro/population-of-murfatlar","count" => "11 070","real_id" =>178,),
"179"=>array("name_ru"=>"Виктория","name_en"=>"Victoria","name_href" => "ro/population-of-victoria","count" => "10 896","real_id" =>179,),
"180"=>array("name_ru"=>"Бабадаг","name_en"=>"Babadag","name_href" => "ro/population-of-babadag","count" => "10 878","real_id" =>180,),
"181"=>array("name_ru"=>"Алешд","name_en"=>"Alesd","name_href" => "ro/population-of-alesd","count" => "10 852","real_id" =>181,),
"182"=>array("name_ru"=>"Титу","name_en"=>"Titus","name_href" => "ro/population-of-titus","count" => "10 711","real_id" =>182,),
"183"=>array("name_ru"=>"Сынджеорз-Бэй","name_en"=>"Town Bay","name_href" => "ro/population-of-town-bay","count" => "10 702","real_id" =>183,),
"184"=>array("name_ru"=>"Валя-луй-Михай","name_en"=>"Valea lui Mihai","name_href" => "ro/population-of-valea-lui-mihai","count" => "10 665","real_id" =>184,),
"185"=>array("name_ru"=>"Анина","name_en"=>"Anina","name_href" => "ro/population-of-anina","count" => "10 594","real_id" =>185,),
"186"=>array("name_ru"=>"Отопени","name_en"=>"Otopeni","name_href" => "ro/population-of-otopeni","count" => "10 515","real_id" =>186,),
"187"=>array("name_ru"=>"Жимболия","name_en"=>"Jimbolia","name_href" => "ro/population-of-jimbolia","count" => "10 497","real_id" =>187,),
"188"=>array("name_ru"=>"Негрешти","name_en"=>"Negresti","name_href" => "ro/population-of-negresti","count" => "10 481","real_id" =>188,),
"189"=>array("name_ru"=>"Бараолт","name_en"=>"Baraolt","name_href" => "ro/population-of-baraolt","count" => "10 464","real_id" =>189,),
"190"=>array("name_ru"=>"Инеу","name_en"=>"InEU","name_href" => "ro/population-of-ineu","count" => "10 416","real_id" =>190,),
"191"=>array("name_ru"=>"Тополовени","name_en"=>"Topoloveni","name_href" => "ro/population-of-topoloveni","count" => "10 329","real_id" =>191,),
"192"=>array("name_ru"=>"Тэшнад","name_en"=>"Tasnad","name_href" => "ro/population-of-tasnad","count" => "10 188","real_id" =>192,),
"193"=>array("name_ru"=>"Плопени","name_en"=>"Plopeni","name_href" => "ro/population-of-plopeni","count" => "10 083","real_id" =>193,),
"194"=>array("name_ru"=>"Сирет","name_en"=>"Siret","name_href" => "ro/population-of-siret","count" => "10 003","real_id" =>194,),
"195"=>array("name_ru"=>"Хуедин","name_en"=>"Huedin","name_href" => "ro/population-of-huedin","count" => "9 955","real_id" =>195,),
"196"=>array("name_ru"=>"Панчу","name_en"=>"Punch","name_href" => "ro/population-of-punch","count" => "9 834","real_id" =>196,),
"197"=>array("name_ru"=>"Ернут","name_en"=>"Arnot","name_href" => "ro/population-of-arnot","count" => "9 833","real_id" =>197,),
"198"=>array("name_ru"=>"Куртичи","name_en"=>"Curtici","name_href" => "ro/population-of-curtici","count" => "9 762","real_id" =>198,),
"199"=>array("name_ru"=>"Будешти","name_en"=>"Budesti","name_href" => "ro/population-of-budesti","count" => "9 596","real_id" =>199,),
"200"=>array("name_ru"=>"Штей","name_en"=>"Steiu","name_href" => "ro/population-of-steiu","count" => "9 466","real_id" =>200,),
"201"=>array("name_ru"=>"Сеини","name_en"=>"Seini","name_href" => "ro/population-of-seini","count" => "9 439","real_id" =>201,),
"202"=>array("name_ru"=>"Тыргу-Кэрбунешти","name_en"=>"Târgu-Carbunesti","name_href" => "ro/population-of-târgu-carbunesti","count" => "9 338","real_id" =>202,),
"203"=>array("name_ru"=>"Бэлан","name_en"=>"Balan","name_href" => "ro/population-of-balan","count" => "9 295","real_id" =>203,),
"204"=>array("name_ru"=>"Эфорие","name_en"=>"Eforie","name_href" => "ro/population-of-eforie","count" => "9 294","real_id" =>204,),
"205"=>array("name_ru"=>"Златна","name_en"=>"Zlatna","name_href" => "ro/population-of-zlatna","count" => "9 254","real_id" =>205,),
"206"=>array("name_ru"=>"Тэлмачу","name_en"=>"Telmaco","name_href" => "ro/population-of-telmaco","count" => "9 147","real_id" =>206,),
"207"=>array("name_ru"=>"Интросура-Бузэулуй","name_en"=>"Intasure Buzaului","name_href" => "ro/population-of-intasure-buzaului","count" => "9 081","real_id" =>207,),
"208"=>array("name_ru"=>"Кэлимэтешти-Кэчулата","name_en"=>"Qualimatest-Caciulata","name_href" => "ro/population-of-qualimatest-caciulata","count" => "8 923","real_id" =>208,),
"209"=>array("name_ru"=>"Биказ","name_en"=>"Bicaz","name_href" => "ro/population-of-bicaz","count" => "8 911","real_id" =>209,),
"210"=>array("name_ru"=>"Думбрэвени","name_en"=>"Dumbrăveni","name_href" => "ro/population-of-dumbrăveni","count" => "8 812","real_id" =>210,),
"211"=>array("name_ru"=>"Кишинеу-Криш","name_en"=>"Chişinău-Krish","name_href" => "ro/population-of-chişinău-krish","count" => "8 724","real_id" =>211,),
"212"=>array("name_ru"=>"Сегарча","name_en"=>"Search","name_href" => "ro/population-of-search","count" => "8 704","real_id" =>212,),
"213"=>array("name_ru"=>"Сэвени","name_en"=>"Savini","name_href" => "ro/population-of-savini","count" => "8 685","real_id" =>213,),
"214"=>array("name_ru"=>"Кымпени","name_en"=>"Kampani","name_href" => "ro/population-of-kampani","count" => "8 587","real_id" =>214,),
"215"=>array("name_ru"=>"Чеху-Силванией","name_en"=>"Czech-Sylvania","name_href" => "ro/population-of-czech-sylvania","count" => "8 468","real_id" =>215,),
"216"=>array("name_ru"=>"Нэдлак","name_en"=>"Nadlac","name_href" => "ro/population-of-nadlac","count" => "8 422","real_id" =>216,),
"217"=>array("name_ru"=>"Бузиаш","name_en"=>"Buziaş","name_href" => "ro/population-of-buziaş","count" => "8 128","real_id" =>217,),
"218"=>array("name_ru"=>"Фиени","name_en"=>"Fieni","name_href" => "ro/population-of-fieni","count" => "8 092","real_id" =>218,),
"219"=>array("name_ru"=>"Тыргу-Бужор","name_en"=>"Târgu Bujor","name_href" => "ro/population-of-târgu-bujor","count" => "8 044","real_id" =>219,),
"220"=>array("name_ru"=>"Одобешти","name_en"=>"Odobesti","name_href" => "ro/population-of-odobesti","count" => "7 985","real_id" =>220,),
"221"=>array("name_ru"=>"Погоанеле","name_en"=>"Pogonele","name_href" => "ro/population-of-pogonele","count" => "7 614","real_id" =>221,),
"222"=>array("name_ru"=>"Брезой","name_en"=>"Brezoi","name_href" => "ro/population-of-brezoi","count" => "7 589","real_id" =>222,),
"223"=>array("name_ru"=>"Тисмана","name_en"=>"Tismana","name_href" => "ro/population-of-tismana","count" => "7 578","real_id" =>223,),
"224"=>array("name_ru"=>"Фэджет","name_en"=>"Of the Faget","name_href" => "ro/population-of-of-the-faget","count" => "7 519","real_id" =>224,),
"225"=>array("name_ru"=>"Инсурэцей","name_en"=>"Insurace","name_href" => "ro/population-of-insurace","count" => "7 501","real_id" =>225,),
"226"=>array("name_ru"=>"Хорезу","name_en"=>"Horezu","name_href" => "ro/population-of-horezu","count" => "7 446","real_id" =>226,),
"227"=>array("name_ru"=>"Пынкота","name_en"=>"Pinata","name_href" => "ro/population-of-pinata","count" => "7 418","real_id" =>227,),
"228"=>array("name_ru"=>"Влэхица","name_en"=>"Vlahita","name_href" => "ro/population-of-vlahita","count" => "7 392","real_id" =>228,),
"229"=>array("name_ru"=>"Текиргёл","name_en"=>"Techirghiol","name_href" => "ro/population-of-techirghiol","count" => "7 388","real_id" =>229,),
"230"=>array("name_ru"=>"Теюш","name_en"=>"TEUs","name_href" => "ro/population-of-teus","count" => "7 338","real_id" =>230,),
"231"=>array("name_ru"=>"Слэник","name_en"=>"Slănic","name_href" => "ro/population-of-slănic","count" => "7 249","real_id" =>231,),
"232"=>array("name_ru"=>"Михэйлешти","name_en"=>"Mihailesti","name_href" => "ro/population-of-mihailesti","count" => "7 161","real_id" =>232,),
"233"=>array("name_ru"=>"Вынжу-Маре","name_en"=>"Vinju Mare","name_href" => "ro/population-of-vinju-mare","count" => "7 074","real_id" =>233,),
"234"=>array("name_ru"=>"Дета","name_en"=>"Detail","name_href" => "ro/population-of-detail","count" => "7 059","real_id" =>234,),
"235"=>array("name_ru"=>"Себиш","name_en"=>"Sebes","name_href" => "ro/population-of-sebes","count" => "6 829","real_id" =>235,),
"236"=>array("name_ru"=>"Абруд","name_en"=>"Abrud","name_href" => "ro/population-of-abrud","count" => "6 803","real_id" =>236,),
"237"=>array("name_ru"=>"Предял","name_en"=>"Predeal","name_href" => "ro/population-of-predeal","count" => "6 735","real_id" =>237,),
"238"=>array("name_ru"=>"Лехлиу-Гарэ","name_en"=>"Lehliu-Gara","name_href" => "ro/population-of-lehliu-gara","count" => "6 667","real_id" =>238,),
"239"=>array("name_ru"=>"Пятра-Олт","name_en"=>"Piatra OLT","name_href" => "ro/population-of-piatra-olt","count" => "6 583","real_id" =>239,),
"240"=>array("name_ru"=>"Джеоаджу","name_en"=>"Geoagiu","name_href" => "ro/population-of-geoagiu","count" => "6 290","real_id" =>240,),
"241"=>array("name_ru"=>"Рупя","name_en"=>"Rupa","name_href" => "ro/population-of-rupa","count" => "6 246","real_id" =>241,),
"242"=>array("name_ru"=>"Фундуля","name_en"=>"Fundus","name_href" => "ro/population-of-fundus","count" => "6 217","real_id" =>242,),
"243"=>array("name_ru"=>"Новачи","name_en"=>"Novaci","name_href" => "ro/population-of-novaci","count" => "6 151","real_id" =>243,),
"244"=>array("name_ru"=>"Азуга","name_en"=>"Azuga","name_href" => "ro/population-of-azuga","count" => "6 119","real_id" =>244,),
"245"=>array("name_ru"=>"Аниноаса","name_en"=>"Aninoasa","name_href" => "ro/population-of-aninoasa","count" => "6 108","real_id" =>245,),
"246"=>array("name_ru"=>"Бэиле-Херкулане","name_en"=>"Băile Herculane","name_href" => "ro/population-of-băile-herculane","count" => "6 051","real_id" =>246,),
"247"=>array("name_ru"=>"Бая-де-Арамэ","name_en"=>"Baia de Arame","name_href" => "ro/population-of-baia-de-arame","count" => "5 724","real_id" =>247,),
"248"=>array("name_ru"=>"Исакча","name_en"=>"Of Isakcha","name_href" => "ro/population-of-of-isakcha","count" => "5 614","real_id" =>248,),
"249"=>array("name_ru"=>"Негру-Водэ","name_en"=>"Negru-Voda","name_href" => "ro/population-of-negru-voda","count" => "5 529","real_id" =>249,),
"250"=>array("name_ru"=>"Кавник","name_en"=>"Cavnic","name_href" => "ro/population-of-cavnic","count" => "5 494","real_id" =>250,),
"251"=>array("name_ru"=>"Слэник-Молдова","name_en"=>"Slănic-Moldova","name_href" => "ro/population-of-slănic-moldova","count" => "5 375","real_id" =>251,),
"252"=>array("name_ru"=>"Циклени","name_en"=>"Ticleni","name_href" => "ro/population-of-ticleni","count" => "5 205","real_id" =>252,),
"253"=>array("name_ru"=>"Копша-Микэ","name_en"=>"Copsa Mică","name_href" => "ro/population-of-copsa-mică","count" => "5 157","real_id" =>253,),
"254"=>array("name_ru"=>"Сулина","name_en"=>"Sulina","name_href" => "ro/population-of-sulina","count" => "5 140","real_id" =>254,),
"255"=>array("name_ru"=>"Бая-де-Арьеш","name_en"=>"Baia de Aries","name_href" => "ro/population-of-baia-de-aries","count" => "4 877","real_id" =>255,),
"256"=>array("name_ru"=>"Бэиле-Олэнешти","name_en"=>"Baile, Olanesti","name_href" => "ro/population-of-baile-olanesti","count" => "4 814","real_id" =>256,),
"257"=>array("name_ru"=>"Солка","name_en"=>"Salk","name_href" => "ro/population-of-salk","count" => "4 687","real_id" =>257,),
"258"=>array("name_ru"=>"Фэурей","name_en"=>"Feura","name_href" => "ro/population-of-feura","count" => "4 626","real_id" =>258,),
"259"=>array("name_ru"=>"Окна-Сибиулуй","name_en"=>"Ocna Sibiului","name_href" => "ro/population-of-ocna-sibiului","count" => "4 184","real_id" =>259,),
"260"=>array("name_ru"=>"Берешти","name_en"=>"Beresti","name_href" => "ro/population-of-beresti","count" => "3 926","real_id" =>260,),
"261"=>array("name_ru"=>"Окнеле-Мари","name_en"=>"Ocnele Mari","name_href" => "ro/population-of-ocnele-mari","count" => "3 591","real_id" =>261,),
"262"=>array("name_ru"=>"Бэиле-Говора","name_en"=>"Băile Dialect","name_href" => "ro/population-of-băile-dialect","count" => "3 147","real_id" =>262,),
"263"=>array("name_ru"=>"Борзек","name_en"=>"Borsec","name_href" => "ro/population-of-borsec","count" => "3 109","real_id" =>263,),
"264"=>array("name_ru"=>"Вашкэу","name_en"=>"Vascau","name_href" => "ro/population-of-vascau","count" => "3 032","real_id" =>264,),
"265"=>array("name_ru"=>"Нучет","name_en"=>"Nucet","name_href" => "ro/population-of-nucet","count" => "2 851","real_id" =>265,),
"266"=>array("name_ru"=>"Бэиле-Тушнад","name_en"=>"Băile Tuşnad","name_href" => "ro/population-of-băile-tuşnad","count" => "1 802","real_id" =>266,),
"267"=>array("name_ru"=>"Бухарест","name_en"=>"Bucharest","name_href" => "ro/population-of-bucharest","count" => "2 354 510","real_id" =>267,),
"268"=>array("name_ru"=>"Яссы","name_en"=>"Iasi","name_href" => "ro/population-of-iasi","count" => "340 580","real_id" =>268,),
"269"=>array("name_ru"=>"Клуж-Напока","name_en"=>"Cluj-Napoca","name_href" => "ro/population-of-cluj-napoca","count" => "318 027","real_id" =>269,),
"270"=>array("name_ru"=>"Тимишоара","name_en"=>"Timisoara","name_href" => "ro/population-of-timisoara","count" => "317 651","real_id" =>270,),
"271"=>array("name_ru"=>"Констанца","name_en"=>"Constanta","name_href" => "ro/population-of-constanta","count" => "283 872","real_id" =>271,)
);

?>