<?php
//Словения 47 
$libsi = array ( 
"1"=>array("name_ru"=>"Любляна","name_en"=>"Ljubljana","name_href" => "si/population-of-ljubljana","count" => "277 554","real_id" =>1,),
"2"=>array("name_ru"=>"Марибор","name_en"=>"Maribor","name_href" => "si/population-of-maribor","count" => "95 586","real_id" =>2,),
"3"=>array("name_ru"=>"Целе","name_en"=>"Celje","name_href" => "si/population-of-celje","count" => "37 628","real_id" =>3,),
"4"=>array("name_ru"=>"Крань","name_en"=>"Kranj","name_href" => "si/population-of-kranj","count" => "37 223","real_id" =>4,),
"5"=>array("name_ru"=>"Копер","name_en"=>"pile driver","name_href" => "si/population-of-pile-driver","count" => "25 775","real_id" =>5,),
"6"=>array("name_ru"=>"Веленье","name_en"=>"Velenje","name_href" => "si/population-of-velenje","count" => "25 329","real_id" =>6,),
"7"=>array("name_ru"=>"Ново-Место","name_en"=>"Novo Mesto","name_href" => "si/population-of-novo-mesto","count" => "23 275","real_id" =>7,),
"8"=>array("name_ru"=>"Птуй","name_en"=>"Ptuj","name_href" => "si/population-of-ptuj","count" => "17 870","real_id" =>8,),
"9"=>array("name_ru"=>"Трбовле","name_en"=>"Trbovlje","name_href" => "si/population-of-trbovlje","count" => "14 302","real_id" =>9,),
"10"=>array("name_ru"=>"Камник","name_en"=>"Kamnik","name_href" => "si/population-of-kamnik","count" => "13 685","real_id" =>10,),
"11"=>array("name_ru"=>"Есенице","name_en"=>"Jesenice","name_href" => "si/population-of-jesenice","count" => "13 217","real_id" =>11,),
"12"=>array("name_ru"=>"Нова-Горица","name_en"=>"Nova Gorica","name_href" => "si/population-of-nova-gorica","count" => "12 986","real_id" =>12,),
"13"=>array("name_ru"=>"Домжале","name_en"=>"Domžale","name_href" => "si/population-of-domžale","count" => "12 668","real_id" =>13,),
"14"=>array("name_ru"=>"Шкофья-Лока","name_en"=>"Škofja Loka","name_href" => "si/population-of-škofja-loka","count" => "11 822","real_id" =>14,),
"15"=>array("name_ru"=>"Мурска-Собота","name_en"=>"Murska Sobota","name_href" => "si/population-of-murska-sobota","count" => "11 347","real_id" =>15,),
"16"=>array("name_ru"=>"Изола","name_en"=>"Isola","name_href" => "si/population-of-isola","count" => "11 209","real_id" =>16,),
"17"=>array("name_ru"=>"Логатец","name_en"=>"Logatec","name_href" => "si/population-of-logatec","count" => "9 291","real_id" =>17,),
"18"=>array("name_ru"=>"Постойна","name_en"=>"Postojna","name_href" => "si/population-of-postojna","count" => "9 262","real_id" =>18,),
"19"=>array("name_ru"=>"Врхника","name_en"=>"Vrhnika","name_href" => "si/population-of-vrhnika","count" => "8 522","real_id" =>19,),
"20"=>array("name_ru"=>"Кочевье","name_en"=>"Kocevje","name_href" => "si/population-of-kocevje","count" => "8 462","real_id" =>20,),
"21"=>array("name_ru"=>"Словенска-Бистрица","name_en"=>"Slovenska Bistrica","name_href" => "si/population-of-slovenska-bistrica","count" => "7 669","real_id" =>21,),
"22"=>array("name_ru"=>"Словень-Градец","name_en"=>"Slovenj Gradec","name_href" => "si/population-of-slovenj-gradec","count" => "7 513","real_id" =>22,),
"23"=>array("name_ru"=>"Кршко","name_en"=>"Krsko","name_href" => "si/population-of-krsko","count" => "7 230","real_id" =>23,),
"24"=>array("name_ru"=>"Гросупле","name_en"=>"Grosuplje","name_href" => "si/population-of-grosuplje","count" => "7 165","real_id" =>24,),
"25"=>array("name_ru"=>"Равне-на-Корошкем","name_en"=>"Ravne na koroškem","name_href" => "si/population-of-ravne-na-koroškem","count" => "6 743","real_id" =>25,),
"26"=>array("name_ru"=>"Брежице","name_en"=>"Brežice","name_href" => "si/population-of-brežice","count" => "6 613","real_id" =>26,),
"27"=>array("name_ru"=>"Айдовшчина","name_en"=>"Ajdovščina","name_href" => "si/population-of-ajdovščina","count" => "6 574","real_id" =>27,),
"28"=>array("name_ru"=>"Лития","name_en"=>"Lithia","name_href" => "si/population-of-lithia","count" => "6 485","real_id" =>28,),
"29"=>array("name_ru"=>"Загорье-на-Саве","name_en"=>"Zagorje-on-Sava","name_href" => "si/population-of-zagorje-on-sava","count" => "6 295","real_id" =>29,),
"30"=>array("name_ru"=>"Менгеш","name_en"=>"Mengeš","name_href" => "si/population-of-mengeš","count" => "6 281","real_id" =>30,),
"31"=>array("name_ru"=>"Луция","name_en"=>"Lucius","name_href" => "si/population-of-lucius","count" => "6 032","real_id" =>31,),
"32"=>array("name_ru"=>"Радовлица","name_en"=>"Radovljica","name_href" => "si/population-of-radovljica","count" => "5 996","real_id" =>32,),
"33"=>array("name_ru"=>"Идрия","name_en"=>"Idrija","name_href" => "si/population-of-idrija","count" => "5 952","real_id" =>33,),
"34"=>array("name_ru"=>"Чрномель","name_en"=>"Črnomelj","name_href" => "si/population-of-črnomelj","count" => "5 717","real_id" =>34,),
"35"=>array("name_ru"=>"Сежана","name_en"=>"Sežana","name_href" => "si/population-of-sežana","count" => "5 619","real_id" =>35,),
"36"=>array("name_ru"=>"Храстник","name_en"=>"Hrastnik","name_href" => "si/population-of-hrastnik","count" => "5 329","real_id" =>36,),
"37"=>array("name_ru"=>"Блед","name_en"=>"Bled","name_href" => "si/population-of-bled","count" => "5 200","real_id" =>37,),
"38"=>array("name_ru"=>"Медводе","name_en"=>"Medvode","name_href" => "si/population-of-medvode","count" => "5 101","real_id" =>38,),
"39"=>array("name_ru"=>"Рогашка-Слатина","name_en"=>"Rogaska Slatina","name_href" => "si/population-of-rogaska-slatina","count" => "5 041","real_id" =>39,),
"40"=>array("name_ru"=>"Словенске-Конице","name_en"=>"Slovenske Konjice","name_href" => "si/population-of-slovenske-konjice","count" => "4 933","real_id" =>40,),
"41"=>array("name_ru"=>"Жалец","name_en"=>"Zalec","name_href" => "si/population-of-zalec","count" => "4 842","real_id" =>41,),
"42"=>array("name_ru"=>"Шентюр","name_en"=>"šentjur","name_href" => "si/population-of-šentjur","count" => "4 779","real_id" =>42,),
"43"=>array("name_ru"=>"Превалье","name_en"=>"Preval","name_href" => "si/population-of-preval","count" => "4 591","real_id" =>43,),
"44"=>array("name_ru"=>"Севница","name_en"=>"Sevnica","name_href" => "si/population-of-sevnica","count" => "4 536","real_id" =>44,),
"45"=>array("name_ru"=>"Илирска-Бистрица","name_en"=>"Ilirska Bistrica","name_href" => "si/population-of-ilirska-bistrica","count" => "4 485","real_id" =>45,),
"46"=>array("name_ru"=>"Руше","name_en"=>"Rouche","name_href" => "si/population-of-rouche","count" => "4 409","real_id" =>46,),
"47"=>array("name_ru"=>"Рибница","name_en"=>"Ribnica","name_href" => "si/population-of-ribnica","count" => "3 480","real_id" =>47,),
"48"=>array("name_ru"=>"Любляна","name_en"=>"Ljubljana","name_href" => "si/population-of-ljubljana","count" => "277 554","real_id" =>48,),
"49"=>array("name_ru"=>"Марибор","name_en"=>"Maribor","name_href" => "si/population-of-maribor","count" => "95 586","real_id" =>49,),
"50"=>array("name_ru"=>"Целе","name_en"=>"Celje","name_href" => "si/population-of-celje","count" => "37 628","real_id" =>50,),
"51"=>array("name_ru"=>"Крань","name_en"=>"Kranj","name_href" => "si/population-of-kranj","count" => "37 223","real_id" =>51,),
"52"=>array("name_ru"=>"Копер","name_en"=>"pile driver","name_href" => "si/population-of-pile-driver","count" => "25 775","real_id" =>52,)
);

?>