<?php
//Словакия 138
$libsk = array ( 
"1"=>array("name_ru"=>"Братислава","name_en"=>"Bratislava","name_href" => "sk/population-of-bratislava","count" => "413 192","real_id" =>1,),
"2"=>array("name_ru"=>"Кошице","name_en"=>"Kosice","name_href" => "sk/population-of-kosice","count" => "240 688","real_id" =>2,),
"3"=>array("name_ru"=>"Прешов","name_en"=>"Presov","name_href" => "sk/population-of-presov","count" => "91 638","real_id" =>3,),
"4"=>array("name_ru"=>"Жилина","name_en"=>"Zilina","name_href" => "sk/population-of-zilina","count" => "81 515","real_id" =>4,),
"5"=>array("name_ru"=>"Банска-Бистрица","name_en"=>"Banska Bystrica","name_href" => "sk/population-of-banska-bystrica","count" => "79 775","real_id" =>5,),
"6"=>array("name_ru"=>"Нитра","name_en"=>"Nitra","name_href" => "sk/population-of-nitra","count" => "78 875","real_id" =>6,),
"7"=>array("name_ru"=>"Трнава","name_en"=>"Trnava","name_href" => "sk/population-of-trnava","count" => "66 219","real_id" =>7,),
"8"=>array("name_ru"=>"Мартин","name_en"=>"Martin","name_href" => "sk/population-of-martin","count" => "57 300","real_id" =>8,),
"9"=>array("name_ru"=>"Тренчин","name_en"=>"Trencin","name_href" => "sk/population-of-trencin","count" => "55 832","real_id" =>9,),
"10"=>array("name_ru"=>"Попрад","name_en"=>"Poprad","name_href" => "sk/population-of-poprad","count" => "52 791","real_id" =>10,),
"11"=>array("name_ru"=>"Прьевидза","name_en"=>"Prievidza","name_href" => "sk/population-of-prievidza","count" => "48 866","real_id" =>11,),
"12"=>array("name_ru"=>"Зволен","name_en"=>"Zvolen","name_href" => "sk/population-of-zvolen","count" => "43 311","real_id" =>12,),
"13"=>array("name_ru"=>"Поважска-Бистрица","name_en"=>"Považská Bystrica","name_href" => "sk/population-of-považská-bystrica","count" => "41 153","real_id" =>13,),
"14"=>array("name_ru"=>"Михаловце","name_en"=>"Michalovce","name_href" => "sk/population-of-michalovce","count" => "39 989","real_id" =>14,),
"15"=>array("name_ru"=>"Нове Замки","name_en"=>"Nove Locks","name_href" => "sk/population-of-nove-locks","count" => "39 585","real_id" =>15,),
"16"=>array("name_ru"=>"Спишска Нова Вес","name_en"=>"Spisska Nova Ves","name_href" => "sk/population-of-spisska-nova-ves","count" => "37 948","real_id" =>16,),
"17"=>array("name_ru"=>"Гуменне","name_en"=>"Humenné","name_href" => "sk/population-of-humenné","count" => "34 921","real_id" =>17,),
"18"=>array("name_ru"=>"Левице","name_en"=>"Levice","name_href" => "sk/population-of-levice","count" => "34 649","real_id" =>18,),
"19"=>array("name_ru"=>"Комарно","name_en"=>"Komarno","name_href" => "sk/population-of-komarno","count" => "34 478","real_id" =>19,),
"20"=>array("name_ru"=>"Бардеёв","name_en"=>"Bardejov","name_href" => "sk/population-of-bardejov","count" => "33 625","real_id" =>20,),
"21"=>array("name_ru"=>"Липтовски-Микулаш","name_en"=>"Liptovsky Mikulas","name_href" => "sk/population-of-liptovsky-mikulas","count" => "31 928","real_id" =>21,),
"22"=>array("name_ru"=>"Лученец","name_en"=>"Lucenec","name_href" => "sk/population-of-lucenec","count" => "28 508","real_id" =>22,),
"23"=>array("name_ru"=>"Ружомберок","name_en"=>"Ruzomberok","name_href" => "sk/population-of-ruzomberok","count" => "28 364","real_id" =>23,),
"24"=>array("name_ru"=>"Пьештяны","name_en"=>"Piestany","name_href" => "sk/population-of-piestany","count" => "28 267","real_id" =>24,),
"25"=>array("name_ru"=>"Топольчаны","name_en"=>"Topolcany","name_href" => "sk/population-of-topolcany","count" => "27 124","real_id" =>25,),
"26"=>array("name_ru"=>"Дубница-над-Вагом","name_en"=>"Dubnica nad Vahom","name_href" => "sk/population-of-dubnica-nad-vahom","count" => "25 229","real_id" =>26,),
"27"=>array("name_ru"=>"Чадца","name_en"=>"Cadca","name_href" => "sk/population-of-cadca","count" => "24 921","real_id" =>27,),
"28"=>array("name_ru"=>"Римавска-Собота","name_en"=>"Rimavská Sobota","name_href" => "sk/population-of-rimavská-sobota","count" => "24 549","real_id" =>28,),
"29"=>array("name_ru"=>"Требишов","name_en"=>"Trebišov","name_href" => "sk/population-of-trebišov","count" => "24 472","real_id" =>29,),
"30"=>array("name_ru"=>"Партизанске","name_en"=>"Partizansk","name_href" => "sk/population-of-partizansk","count" => "24 006","real_id" =>30,),
"31"=>array("name_ru"=>"Шаля","name_en"=>"Sala","name_href" => "sk/population-of-sala","count" => "23 440","real_id" =>31,),
"32"=>array("name_ru"=>"Вранов-над-Топлёу","name_en"=>"Vranov nad Topľou","name_href" => "sk/population-of-vranov-nad-topľou","count" => "23 225","real_id" =>32,),
"33"=>array("name_ru"=>"Глоговец","name_en"=>"Hlohovec","name_href" => "sk/population-of-hlohovec","count" => "22 661","real_id" =>33,),
"34"=>array("name_ru"=>"Дунайска-Стреда","name_en"=>"Dunajska Streda","name_href" => "sk/population-of-dunajska-streda","count" => "22 486","real_id" =>34,),
"35"=>array("name_ru"=>"Брезно","name_en"=>"Brezno","name_href" => "sk/population-of-brezno","count" => "21 827","real_id" =>35,),
"36"=>array("name_ru"=>"Пезинок","name_en"=>"Pezinok","name_href" => "sk/population-of-pezinok","count" => "21 263","real_id" =>36,),
"37"=>array("name_ru"=>"Снина","name_en"=>"Snina","name_href" => "sk/population-of-snina","count" => "20 701","real_id" =>37,),
"38"=>array("name_ru"=>"Нове-Место-над-Вагом","name_en"=>"Nové Mesto nad Váhom","name_href" => "sk/population-of-nové-mesto-nad-váhom","count" => "20 360","real_id" =>38,),
"39"=>array("name_ru"=>"Сеница","name_en"=>"Senica","name_href" => "sk/population-of-senica","count" => "20 320","real_id" =>39,),
"40"=>array("name_ru"=>"Жьяр-над-Гроном","name_en"=>"Ziar nad Hronom","name_href" => "sk/population-of-ziar-nad-hronom","count" => "19 862","real_id" =>40,),
"41"=>array("name_ru"=>"Рожнява","name_en"=>"Roznava","name_href" => "sk/population-of-roznava","count" => "19 651","real_id" =>41,),
"42"=>array("name_ru"=>"Долны Кубин","name_en"=>"Dolny Kubin","name_href" => "sk/population-of-dolny-kubin","count" => "19 554","real_id" =>42,),
"43"=>array("name_ru"=>"Бановце-над-Бебравоу","name_en"=>"Banovce nad Bebravou","name_href" => "sk/population-of-banovce-nad-bebravou","count" => "19 503","real_id" =>43,),
"44"=>array("name_ru"=>"Пухов","name_en"=>"Pukhov","name_href" => "sk/population-of-pukhov","count" => "18 213","real_id" =>44,),
"45"=>array("name_ru"=>"Гандлова","name_en"=>"Handlova","name_href" => "sk/population-of-handlova","count" => "17 738","real_id" =>45,),
"46"=>array("name_ru"=>"Сенец","name_en"=>"Senec","name_href" => "sk/population-of-senec","count" => "17 289","real_id" =>46,),
"47"=>array("name_ru"=>"Малацки","name_en"=>"Malacky","name_href" => "sk/population-of-malacky","count" => "17 066","real_id" =>47,),
"48"=>array("name_ru"=>"Кежмарок","name_en"=>"Kežmarok","name_href" => "sk/population-of-kežmarok","count" => "16 843","real_id" =>48,),
"49"=>array("name_ru"=>"Стара Любовня","name_en"=>"Stara Lubovna","name_href" => "sk/population-of-stara-lubovna","count" => "16 334","real_id" =>49,),
"50"=>array("name_ru"=>"Середь","name_en"=>"Sered","name_href" => "sk/population-of-sered","count" => "16 214","real_id" =>50,),
"51"=>array("name_ru"=>"Кисуцке Нове Место","name_en"=>"Kysucké Nové Mesto","name_href" => "sk/population-of-kysucké-nové-mesto","count" => "15 652","real_id" =>51,),
"52"=>array("name_ru"=>"Галанта","name_en"=>"Galanta","name_href" => "sk/population-of-galanta","count" => "15 147","real_id" =>52,),
"53"=>array("name_ru"=>"Детва","name_en"=>"Detva","name_href" => "sk/population-of-detva","count" => "15 062","real_id" =>53,),
"54"=>array("name_ru"=>"Левоча","name_en"=>"Levoca","name_href" => "sk/population-of-levoca","count" => "14 796","real_id" =>54,),
"55"=>array("name_ru"=>"Скалица","name_en"=>"Skalica","name_href" => "sk/population-of-skalica","count" => "14 466","real_id" =>55,),
"56"=>array("name_ru"=>"Вельки-Кртиш","name_en"=>"Veľký krtíš","name_href" => "sk/population-of-veľký-krtíš","count" => "12 853","real_id" =>56,),
"57"=>array("name_ru"=>"Ревуца","name_en"=>"Revuca","name_href" => "sk/population-of-revuca","count" => "12 815","real_id" =>57,),
"58"=>array("name_ru"=>"Шаморин","name_en"=>"Samorin","name_href" => "sk/population-of-samorin","count" => "12 801","real_id" =>58,),
"59"=>array("name_ru"=>"Сабинов","name_en"=>"Sabinov","name_href" => "sk/population-of-sabinov","count" => "12 715","real_id" =>59,),
"60"=>array("name_ru"=>"Злате Моравце","name_en"=>"Zlate Moravce","name_href" => "sk/population-of-zlate-moravce","count" => "12 286","real_id" =>60,),
"61"=>array("name_ru"=>"Миява","name_en"=>"Myjava","name_href" => "sk/population-of-myjava","count" => "12 267","real_id" =>61,),
"62"=>array("name_ru"=>"Свидник","name_en"=>"Swidnik","name_href" => "sk/population-of-swidnik","count" => "11 602","real_id" =>62,),
"63"=>array("name_ru"=>"Нова Дубница","name_en"=>"Nová Dubnica","name_href" => "sk/population-of-nová-dubnica","count" => "11 469","real_id" =>63,),
"64"=>array("name_ru"=>"Битча","name_en"=>"Bytca","name_href" => "sk/population-of-bytca","count" => "11 313","real_id" =>64,),
"65"=>array("name_ru"=>"Голич","name_en"=>"Holic","name_href" => "sk/population-of-holic","count" => "11 218","real_id" =>65,),
"66"=>array("name_ru"=>"Молдава-над-Бодвоу","name_en"=>"Moldava nad Bodvou","name_href" => "sk/population-of-moldava-nad-bodvou","count" => "11 087","real_id" =>66,),
"67"=>array("name_ru"=>"Стропков","name_en"=>"Stropkov","name_href" => "sk/population-of-stropkov","count" => "10 905","real_id" =>67,),
"68"=>array("name_ru"=>"Штурово","name_en"=>"Sturovo","name_href" => "sk/population-of-sturovo","count" => "10 851","real_id" =>68,),
"69"=>array("name_ru"=>"Филяково","name_en"=>"Fiľakovo","name_href" => "sk/population-of-fiľakovo","count" => "10 801","real_id" =>69,),
"70"=>array("name_ru"=>"Коларово","name_en"=>"Kolarovo","name_href" => "sk/population-of-kolarovo","count" => "10 683","real_id" =>70,),
"71"=>array("name_ru"=>"Банска-Штьявница","name_en"=>"Banska Stiavnica","name_href" => "sk/population-of-banska-stiavnica","count" => "10 387","real_id" =>71,),
"72"=>array("name_ru"=>"Шураны","name_en"=>"Surany","name_href" => "sk/population-of-surany","count" => "10 155","real_id" =>72,),
"73"=>array("name_ru"=>"Вельке-Капушаны","name_en"=>"Veľké kapušany","name_href" => "sk/population-of-veľké-kapušany","count" => "9 371","real_id" =>73,),
"74"=>array("name_ru"=>"Тврдошин","name_en"=>"Tvrdosin","name_href" => "sk/population-of-tvrdosin","count" => "9 360","real_id" =>74,),
"75"=>array("name_ru"=>"Ступава","name_en"=>"Stupava","name_href" => "sk/population-of-stupava","count" => "9 345","real_id" =>75,),
"76"=>array("name_ru"=>"Стара-Тура","name_en"=>"Stara Tura","name_href" => "sk/population-of-stara-tura","count" => "9 338","real_id" =>76,),
"77"=>array("name_ru"=>"Врабле","name_en"=>"Vrable","name_href" => "sk/population-of-vrable","count" => "8 983","real_id" =>77,),
"78"=>array("name_ru"=>"Вельки Медер","name_en"=>"Velky Meder","name_href" => "sk/population-of-velky-meder","count" => "8 869","real_id" =>78,),
"79"=>array("name_ru"=>"Модра","name_en"=>"Modra","name_href" => "sk/population-of-modra","count" => "8 795","real_id" =>79,),
"80"=>array("name_ru"=>"Кромпахи","name_en"=>"Krompachy","name_href" => "sk/population-of-krompachy","count" => "8 776","real_id" =>80,),
"81"=>array("name_ru"=>"Сечовце","name_en"=>"Secovce","name_href" => "sk/population-of-secovce","count" => "8 249","real_id" =>81,),
"82"=>array("name_ru"=>"Крупина","name_en"=>"Krupina","name_href" => "sk/population-of-krupina","count" => "8 035","real_id" =>82,),
"83"=>array("name_ru"=>"Наместово","name_en"=>"Namestovo","name_href" => "sk/population-of-namestovo","count" => "7 945","real_id" =>83,),
"84"=>array("name_ru"=>"Гринёва","name_en"=>"Hrinova","name_href" => "sk/population-of-hrinova","count" => "7 802","real_id" =>84,),
"85"=>array("name_ru"=>"Турзовка","name_en"=>"Turzovka","name_href" => "sk/population-of-turzovka","count" => "7 772","real_id" =>85,),
"86"=>array("name_ru"=>"Гнуштя","name_en"=>"Hnúšťa","name_href" => "sk/population-of-hnúšťa","count" => "7 749","real_id" =>86,),
"87"=>array("name_ru"=>"Гурбаново","name_en"=>"Hurbanovo","name_href" => "sk/population-of-hurbanovo","count" => "7 740","real_id" =>87,),
"88"=>array("name_ru"=>"Кралёвски Хлмец","name_en"=>"Kralёvski Chlmec","name_href" => "sk/population-of-kralёvski-chlmec","count" => "7 685","real_id" =>88,),
"89"=>array("name_ru"=>"Шаги","name_en"=>"Steps","name_href" => "sk/population-of-steps","count" => "7 607","real_id" =>89,),
"90"=>array("name_ru"=>"Свит","name_en"=>"Sweet","name_href" => "sk/population-of-sweet","count" => "7 605","real_id" =>90,),
"91"=>array("name_ru"=>"Врутки","name_en"=>"Vrútky","name_href" => "sk/population-of-vrútky","count" => "7 579","real_id" =>91,),
"92"=>array("name_ru"=>"Нова Баня","name_en"=>"Nova Banja","name_href" => "sk/population-of-nova-banja","count" => "7 556","real_id" =>92,),
"93"=>array("name_ru"=>"Липтовски Градок","name_en"=>"Liptovsky Hradok","name_href" => "sk/population-of-liptovsky-hradok","count" => "7 555","real_id" =>93,),
"94"=>array("name_ru"=>"Трстена","name_en"=>"Trstena","name_href" => "sk/population-of-trstena","count" => "7 481","real_id" =>94,),
"95"=>array("name_ru"=>"Торналя","name_en"=>"tornaľa","name_href" => "sk/population-of-tornaľa","count" => "7 474","real_id" =>95,),
"96"=>array("name_ru"=>"Жельезовце","name_en"=>"Zeliezovce","name_href" => "sk/population-of-zeliezovce","count" => "7 166","real_id" =>96,),
"97"=>array("name_ru"=>"Красно-над-Кисуцоу","name_en"=>"Krasno nad Kysucou","name_href" => "sk/population-of-krasno-nad-kysucou","count" => "6 905","real_id" =>97,),
"98"=>array("name_ru"=>"Медзилаборце","name_en"=>"Medzilaborce","name_href" => "sk/population-of-medzilaborce","count" => "6 781","real_id" =>98,),
"99"=>array("name_ru"=>"Турчьянске Теплице","name_en"=>"Turčianske Teplice","name_href" => "sk/population-of-turčianske-teplice","count" => "6 679","real_id" =>99,),
"100"=>array("name_ru"=>"Жарновица","name_en"=>"Zarnovica","name_href" => "sk/population-of-zarnovica","count" => "6 476","real_id" =>100,),
"101"=>array("name_ru"=>"Липаны","name_en"=>"Lipany","name_href" => "sk/population-of-lipany","count" => "6 426","real_id" =>101,),
"102"=>array("name_ru"=>"Спишска Бела","name_en"=>"Spisska Bela","name_href" => "sk/population-of-spisska-bela","count" => "6 411","real_id" =>102,),
"103"=>array("name_ru"=>"Немшова","name_en"=>"Nemsova","name_href" => "sk/population-of-nemsova","count" => "6 269","real_id" =>103,),
"104"=>array("name_ru"=>"Гелница","name_en"=>"Gelnica","name_href" => "sk/population-of-gelnica","count" => "6 232","real_id" =>104,),
"105"=>array("name_ru"=>"Врбове","name_en"=>"Vrbove","name_href" => "sk/population-of-vrbove","count" => "6 212","real_id" =>105,),
"106"=>array("name_ru"=>"Собранце","name_en"=>"Sobrance","name_href" => "sk/population-of-sobrance","count" => "5 992","real_id" =>106,),
"107"=>array("name_ru"=>"Раец","name_en"=>"Rajec","name_href" => "sk/population-of-rajec","count" => "5 874","real_id" =>107,),
"108"=>array("name_ru"=>"Полтар","name_en"=>"Poltar","name_href" => "sk/population-of-poltar","count" => "5 794","real_id" =>108,),
"109"=>array("name_ru"=>"Добшина","name_en"=>"Dobsina","name_href" => "sk/population-of-dobsina","count" => "5 696","real_id" =>109,),
"110"=>array("name_ru"=>"Кремница","name_en"=>"Kremnica","name_href" => "sk/population-of-kremnica","count" => "5 571","real_id" =>110,),
"111"=>array("name_ru"=>"Сладковичово","name_en"=>"Sladkovicovo","name_href" => "sk/population-of-sladkovicovo","count" => "5 465","real_id" =>111,),
"112"=>array("name_ru"=>"Илава","name_en"=>"Iława","name_href" => "sk/population-of-iława","count" => "5 418","real_id" =>112,),
"113"=>array("name_ru"=>"Вельки Шариш","name_en"=>"Velky Saris","name_href" => "sk/population-of-velky-saris","count" => "5 404","real_id" =>113,),
"114"=>array("name_ru"=>"Светы Юр","name_en"=>"Svaty Jur","name_href" => "sk/population-of-svaty-jur","count" => "5 229","real_id" =>114,),
"115"=>array("name_ru"=>"Гбелы","name_en"=>"Gbely","name_href" => "sk/population-of-gbely","count" => "5 218","real_id" =>115,),
"116"=>array("name_ru"=>"Брезова-под-Брадлом","name_en"=>"Brezová pod Bradlom","name_href" => "sk/population-of-brezová-pod-bradlom","count" => "5 109","real_id" =>116,),
"117"=>array("name_ru"=>"Шаштин-Страже","name_en"=>"Sastin-Sentinel","name_href" => "sk/population-of-sastin-sentinel","count" => "5 102","real_id" =>117,),
"118"=>array("name_ru"=>"Слиач","name_en"=>"Sliač","name_href" => "sk/population-of-sliač","count" => "5 095","real_id" =>118,),
"119"=>array("name_ru"=>"Бойнице","name_en"=>"Bojnice","name_href" => "sk/population-of-bojnice","count" => "4 939","real_id" =>119,),
"120"=>array("name_ru"=>"Стражске","name_en"=>"Strazske","name_href" => "sk/population-of-strazske","count" => "4 404","real_id" =>120,),
"121"=>array("name_ru"=>"Тисовец","name_en"=>"Tisovec","name_href" => "sk/population-of-tisovec","count" => "4 309","real_id" =>121,),
"122"=>array("name_ru"=>"Новаки","name_en"=>"Novaky","name_href" => "sk/population-of-novaky","count" => "4 283","real_id" =>122,),
"123"=>array("name_ru"=>"Медзев","name_en"=>"Medzev","name_href" => "sk/population-of-medzev","count" => "4 276","real_id" =>123,),
"124"=>array("name_ru"=>"Высоке Татры","name_en"=>"Vysoke Tatry","name_href" => "sk/population-of-vysoke-tatry","count" => "4 222","real_id" =>124,),
"125"=>array("name_ru"=>"Леополдов","name_en"=>"Leopoldov","name_href" => "sk/population-of-leopoldov","count" => "4 164","real_id" =>125,),
"126"=>array("name_ru"=>"Тренчьянске Теплице","name_en"=>"Trenčianske Teplice","name_href" => "sk/population-of-trenčianske-teplice","count" => "4 161","real_id" =>126,),
"127"=>array("name_ru"=>"Гиралтовце","name_en"=>"Giraltovce","name_href" => "sk/population-of-giraltovce","count" => "4 160","real_id" =>127,),
"128"=>array("name_ru"=>"Спишске Подградье","name_en"=>"Spisske Podhradie","name_href" => "sk/population-of-spisske-podhradie","count" => "4 075","real_id" =>128,),
"129"=>array("name_ru"=>"Чьерна-над-Тисоу","name_en"=>"Cierna nad Tisou","name_href" => "sk/population-of-cierna-nad-tisou","count" => "3 861","real_id" =>129,),
"130"=>array("name_ru"=>"Тлмаче","name_en"=>"Tlmace","name_href" => "sk/population-of-tlmace","count" => "3 813","real_id" =>130,),
"131"=>array("name_ru"=>"Ганушовце-над-Топлёу","name_en"=>"Hanušovce nad topľou","name_href" => "sk/population-of-hanušovce-nad-topľou","count" => "3 747","real_id" =>131,),
"132"=>array("name_ru"=>"Спишске Влахи","name_en"=>"Spisske Vlachs","name_href" => "sk/population-of-spisske-vlachs","count" => "3 627","real_id" =>132,),
"133"=>array("name_ru"=>"Подолинец","name_en"=>"Podolinec","name_href" => "sk/population-of-podolinec","count" => "3 271","real_id" =>133,),
"134"=>array("name_ru"=>"Елшава","name_en"=>"jelšava","name_href" => "sk/population-of-jelšava","count" => "3 235","real_id" =>134,),
"135"=>array("name_ru"=>"Раецке-Теплице","name_en"=>"Rajecké Teplice","name_href" => "sk/population-of-rajecké-teplice","count" => "2 868","real_id" =>135,),
"136"=>array("name_ru"=>"Спишска Стара Вес","name_en"=>"Spisska Stara Weight","name_href" => "sk/population-of-spisska-stara-weight","count" => "2 270","real_id" =>136,),
"137"=>array("name_ru"=>"Модри Камень","name_en"=>"Modra Stone","name_href" => "sk/population-of-modra-stone","count" => "1 560","real_id" =>137,),
"138"=>array("name_ru"=>"Дудинце","name_en"=>"Dudince","name_href" => "sk/population-of-dudince","count" => "1 474","real_id" =>138,),
"139"=>array("name_ru"=>"Братислава","name_en"=>"Bratislava","name_href" => "sk/population-of-bratislava","count" => "413 192","real_id" =>139,),
"140"=>array("name_ru"=>"Кошице","name_en"=>"Kosice","name_href" => "sk/population-of-kosice","count" => "240 688","real_id" =>140,),
"141"=>array("name_ru"=>"Прешов","name_en"=>"Presov","name_href" => "sk/population-of-presov","count" => "91 638","real_id" =>141,),
"142"=>array("name_ru"=>"Жилина","name_en"=>"Zilina","name_href" => "sk/population-of-zilina","count" => "81 515","real_id" =>142,),
"143"=>array("name_ru"=>"Банска-Бистрица","name_en"=>"Banska Bystrica","name_href" => "sk/population-of-banska-bystrica","count" => "79 775","real_id" =>143,)
);

?>