<?php
//Сальвадор  44
$libsv = array ( 
"1"=>array("name_ru"=>"Сан-Сальвадор","name_en"=>"San Salvador","name_href" => "sv/population-of-san-salvador","count" => "507 700","real_id" =>1,),
"2"=>array("name_ru"=>"Сояпанго","name_en"=>"Soyapango","name_href" => "sv/population-of-soyapango","count" => "294 600","real_id" =>2,),
"3"=>array("name_ru"=>"Мехиканос","name_en"=>"Mexicanos","name_href" => "sv/population-of-mexicanos","count" => "188 700","real_id" =>3,),
"4"=>array("name_ru"=>"Сан-Мигель","name_en"=>"San Miguel","name_href" => "sv/population-of-san-miguel","count" => "183 200","real_id" =>4,),
"5"=>array("name_ru"=>"Санта-Ана","name_en"=>"Santa Ana","name_href" => "sv/population-of-santa-ana","count" => "178 600","real_id" =>5,),
"6"=>array("name_ru"=>"Апопа","name_en"=>"Apophis","name_href" => "sv/population-of-apophis","count" => "167 200","real_id" =>6,),
"7"=>array("name_ru"=>"Санта-Текла","name_en"=>"Santa Tecla","name_href" => "sv/population-of-santa-tecla","count" => "161 500","real_id" =>7,),
"8"=>array("name_ru"=>"Илопанго","name_en"=>"Ilopango","name_href" => "sv/population-of-ilopango","count" => "133 100","real_id" =>8,),
"9"=>array("name_ru"=>"Дельгадо","name_en"=>"Delgado","name_href" => "sv/population-of-delgado","count" => "87 700","real_id" =>9,),
"10"=>array("name_ru"=>"Сан-Мартин","name_en"=>"San Martin","name_href" => "sv/population-of-san-martin","count" => "74 000","real_id" =>10,),
"11"=>array("name_ru"=>"Кускатансинго","name_en"=>"Kuskatansingo","name_href" => "sv/population-of-kuskatansingo","count" => "67 900","real_id" =>11,),
"12"=>array("name_ru"=>"Сонсонате","name_en"=>"Sonsonate","name_href" => "sv/population-of-sonsonate","count" => "65 100","real_id" =>12,),
"13"=>array("name_ru"=>"Антиго-Кускатлан","name_en"=>"Antigen-Cuscatlan","name_href" => "sv/population-of-antigen-cuscatlan","count" => "55 300","real_id" =>13,),
"14"=>array("name_ru"=>"Сан-Маркос","name_en"=>"San Marcos","name_href" => "sv/population-of-san-marcos","count" => "54 100","real_id" =>14,),
"15"=>array("name_ru"=>"Кохутепеке","name_en"=>"Cojutepeque","name_href" => "sv/population-of-cojutepeque","count" => "47 500","real_id" =>15,),
"16"=>array("name_ru"=>"Усулутан","name_en"=>"Usulutan","name_href" => "sv/population-of-usulutan","count" => "45 300","real_id" =>16,),
"17"=>array("name_ru"=>"Аютухтепеке","name_en"=>"Ayutuhtepeke","name_href" => "sv/population-of-ayutuhtepeke","count" => "40 300","real_id" =>17,),
"18"=>array("name_ru"=>"Ауачапан","name_en"=>"Ahuachapán","name_href" => "sv/population-of-ahuachapán","count" => "38 100","real_id" =>18,),
"19"=>array("name_ru"=>"Чальчуапа","name_en"=>"Chalchuapa","name_href" => "sv/population-of-chalchuapa","count" => "35 600","real_id" =>19,),
"20"=>array("name_ru"=>"Сан-Висенте","name_en"=>"San Vicente","name_href" => "sv/population-of-san-vicente","count" => "34 600","real_id" =>20,),
"21"=>array("name_ru"=>"Сакатеколука","name_en"=>"ZACATECOLUCA","name_href" => "sv/population-of-zacatecoluca","count" => "33 800","real_id" =>21,),
"22"=>array("name_ru"=>"Кесальтепеке","name_en"=>"Kesaltepeke","name_href" => "sv/population-of-kesaltepeke","count" => "30 800","real_id" =>22,),
"23"=>array("name_ru"=>"Агиларес","name_en"=>"Aguilares","name_href" => "sv/population-of-aguilares","count" => "28 400","real_id" =>23,),
"24"=>array("name_ru"=>"Акахутла","name_en"=>"Acajutla","name_href" => "sv/population-of-acajutla","count" => "26 100","real_id" =>24,),
"25"=>array("name_ru"=>"Сонсакате","name_en"=>"Sonsakate","name_href" => "sv/population-of-sonsakate","count" => "25 600","real_id" =>25,),
"26"=>array("name_ru"=>"Ла-Унион","name_en"=>"La Union","name_href" => "sv/population-of-la-union","count" => "23 600","real_id" =>26,),
"27"=>array("name_ru"=>"Илобаско","name_en"=>"ilobasco","name_href" => "sv/population-of-ilobasco","count" => "22 200","real_id" =>27,),
"28"=>array("name_ru"=>"Исалько","name_en"=>"Izalco","name_href" => "sv/population-of-izalco","count" => "20 600","real_id" =>28,),
"29"=>array("name_ru"=>"Сарагоса","name_en"=>"Saragossa","name_href" => "sv/population-of-saragossa","count" => "20 300","real_id" =>29,),
"30"=>array("name_ru"=>"Ла-Либертад","name_en"=>"La Libertad","name_href" => "sv/population-of-la-libertad","count" => "20 100","real_id" =>30,),
"31"=>array("name_ru"=>"Санто-Томас","name_en"=>"Santo Tomas","name_href" => "sv/population-of-santo-tomas","count" => "19 600","real_id" =>31,),
"32"=>array("name_ru"=>"Метапан","name_en"=>"Metapán","name_href" => "sv/population-of-metapán","count" => "18 500","real_id" =>32,),
"33"=>array("name_ru"=>"Сенсунтепе","name_en"=>"Sensuntepe","name_href" => "sv/population-of-sensuntepe","count" => "16 900","real_id" =>33,),
"34"=>array("name_ru"=>"Чалатенанго","name_en"=>"Chalatenango","name_href" => "sv/population-of-chalatenango","count" => "16 200","real_id" =>34,),
"35"=>array("name_ru"=>"Сан-Антонио-дель-Монте","name_en"=>"San Antonio del Monte","name_href" => "sv/population-of-san-antonio-del-monte","count" => "14 600","real_id" =>35,),
"36"=>array("name_ru"=>"Сан-Франсиско","name_en"=>"San Francisco","name_href" => "sv/population-of-san-francisco","count" => "14 200","real_id" =>36,),
"37"=>array("name_ru"=>"Гуасапа","name_en"=>"guazapa","name_href" => "sv/population-of-guazapa","count" => "14 000","real_id" =>37,),
"38"=>array("name_ru"=>"Армения","name_en"=>"Armenia","name_href" => "sv/population-of-armenia","count" => "13 700","real_id" =>38,),
"39"=>array("name_ru"=>"Сантьяго-де-Мария","name_en"=>"Santiago de Maria","name_href" => "sv/population-of-santiago-de-maria","count" => "12 800","real_id" =>39,),
"40"=>array("name_ru"=>"Санта-Роза-де-Лима","name_en"=>"Santa Rosa de Lima","name_href" => "sv/population-of-santa-rosa-de-lima","count" => "12 000","real_id" =>40,),
"41"=>array("name_ru"=>"Сьюдад-Арсе","name_en"=>"Ciudad Arce","name_href" => "sv/population-of-ciudad-arce","count" => "11 000","real_id" =>41,),
"42"=>array("name_ru"=>"Сан-Луис Тальпа","name_en"=>"San Luis Talpa","name_href" => "sv/population-of-san-luis-talpa","count" => "10 500","real_id" =>42,),
"43"=>array("name_ru"=>"Хуахуа","name_en"=>"Huahua","name_href" => "sv/population-of-huahua","count" => "10 100","real_id" =>43,),
"44"=>array("name_ru"=>"Сьюдад-Барриос","name_en"=>"Ciudad Barrios","name_href" => "sv/population-of-ciudad-barrios","count" => "10 000","real_id" =>44,),
"45"=>array("name_ru"=>"Сан-Сальвадор","name_en"=>"San Salvador","name_href" => "sv/population-of-san-salvador","count" => "507 700","real_id" =>45,),
"46"=>array("name_ru"=>"Сояпанго","name_en"=>"Soyapango","name_href" => "sv/population-of-soyapango","count" => "294 600","real_id" =>46,),
"47"=>array("name_ru"=>"Мехиканос","name_en"=>"Mexicanos","name_href" => "sv/population-of-mexicanos","count" => "188 700","real_id" =>47,),
"48"=>array("name_ru"=>"Сан-Мигель","name_en"=>"San Miguel","name_href" => "sv/population-of-san-miguel","count" => "183 200","real_id" =>48,),
"49"=>array("name_ru"=>"Санта-Ана","name_en"=>"Santa Ana","name_href" => "sv/population-of-santa-ana","count" => "178 600","real_id" =>49,)
);

?>