<?php
//Судан 30 
$libsd = array ( 
"1"=>array("name_ru"=>"Омдурман","name_en"=>"Omdurman","name_href" => "sd/population-of-omdurman","count" => "2 805 396","real_id" =>1,),
"2"=>array("name_ru"=>"Хартум","name_en"=>"Khartoum","name_href" => "sd/population-of-khartoum","count" => "2 682 431","real_id" =>2,),
"3"=>array("name_ru"=>"Северный Хартум","name_en"=>"Khartoum North","name_href" => "sd/population-of-khartoum-north","count" => "936 349","real_id" =>3,),
"4"=>array("name_ru"=>"Порт-Судан","name_en"=>"Port Sudan","name_href" => "sd/population-of-port-sudan","count" => "585 090","real_id" =>4,),
"5"=>array("name_ru"=>"Кассала","name_en"=>"Kassala","name_href" => "sd/population-of-kassala","count" => "510 165","real_id" =>5,),
"6"=>array("name_ru"=>"Кости","name_en"=>"Bones","name_href" => "sd/population-of-bones","count" => "487 982","real_id" =>6,),
"7"=>array("name_ru"=>"Ньяла","name_en"=>"Nyala","name_href" => "sd/population-of-nyala","count" => "468 955","real_id" =>7,),
"8"=>array("name_ru"=>"Эль-Обейд","name_en"=>"El Obeid","name_href" => "sd/population-of-el-obeid","count" => "408 357","real_id" =>8,),
"9"=>array("name_ru"=>"Вад-Медани","name_en"=>"Wad Medani","name_href" => "sd/population-of-wad-medani","count" => "369 733","real_id" =>9,),
"10"=>array("name_ru"=>"Гедареф","name_en"=>"Gedaref","name_href" => "sd/population-of-gedaref","count" => "354 598","real_id" =>10,),
"11"=>array("name_ru"=>"Эль-Фашер","name_en"=>"El Fasher","name_href" => "sd/population-of-el-fasher","count" => "256 803","real_id" =>11,),
"12"=>array("name_ru"=>"Рабак","name_en"=>"Rabac","name_href" => "sd/population-of-rabac","count" => "202 166","real_id" =>12,),
"13"=>array("name_ru"=>"Эд-Даэйн","name_en"=>"Ed Daein","name_href" => "sd/population-of-ed-daein","count" => "188 577","real_id" =>13,),
"14"=>array("name_ru"=>"Эль-Генейна","name_en"=>"El Geneina","name_href" => "sd/population-of-el-geneina","count" => "168 946","real_id" =>14,),
"15"=>array("name_ru"=>"Эд-Дамазин","name_en"=>"Ed Damazin","name_href" => "sd/population-of-ed-damazin","count" => "146 759","real_id" =>15,),
"16"=>array("name_ru"=>"Эль-Менакил","name_en"=>"El Menaka","name_href" => "sd/population-of-el-menaka","count" => "137 739","real_id" =>16,),
"17"=>array("name_ru"=>"Сеннар","name_en"=>"Sennar","name_href" => "sd/population-of-sennar","count" => "135 581","real_id" =>17,),
"18"=>array("name_ru"=>"Эд-Дуэйм","name_en"=>"Ed dueim","name_href" => "sd/population-of-ed-dueim","count" => "133 644","real_id" =>18,),
"19"=>array("name_ru"=>"Атбара","name_en"=>"Atbara","name_href" => "sd/population-of-atbara","count" => "132 801","real_id" =>19,),
"20"=>array("name_ru"=>"Эд-Дамер","name_en"=>"Ad-Damir","name_href" => "sd/population-of-ad-damir","count" => "122 944","real_id" =>20,),
"21"=>array("name_ru"=>"Эн-Нухуд","name_en"=>"En Nahud","name_href" => "sd/population-of-en-nahud","count" => "110 741","real_id" =>21,),
"22"=>array("name_ru"=>"Хальфа-эль-Джадида","name_en"=>"Halfa El Jadida","name_href" => "sd/population-of-halfa-el-jadida","count" => "108 354","real_id" =>22,),
"23"=>array("name_ru"=>"Кадугли","name_en"=>"Kadugli","name_href" => "sd/population-of-kadugli","count" => "93 205","real_id" =>23,),
"24"=>array("name_ru"=>"Шенди","name_en"=>"Shandy","name_href" => "sd/population-of-shandy","count" => "60 023","real_id" =>24,),
"25"=>array("name_ru"=>"Умм-Руваба","name_en"=>"Umm Ruwaba","name_href" => "sd/population-of-umm-ruwaba","count" => "51 466","real_id" =>25,),
"26"=>array("name_ru"=>"Аль-Джазира-Аба","name_en"=>"Al Jazeera-Aba","name_href" => "sd/population-of-al-jazeera-aba","count" => "51 055","real_id" =>26,),
"27"=>array("name_ru"=>"Синджа","name_en"=>"Sinje","name_href" => "sd/population-of-sinje","count" => "42 256","real_id" =>27,),
"28"=>array("name_ru"=>"Хасм-эль-Кирба","name_en"=>"Hasmy al-Qirbi","name_href" => "sd/population-of-hasmy-al-qirbi","count" => "41 768","real_id" =>28,),
"29"=>array("name_ru"=>"Тендельти","name_en"=>"Tandalti","name_href" => "sd/population-of-tandalti","count" => "40 333","real_id" =>29,),
"30"=>array("name_ru"=>"Асалая","name_en"=>"Asal","name_href" => "sd/population-of-asal","count" => "39 995","real_id" =>30,),
"31"=>array("name_ru"=>"Омдурман","name_en"=>"Omdurman","name_href" => "sd/population-of-omdurman","count" => "2 805 396","real_id" =>31,),
"32"=>array("name_ru"=>"Хартум","name_en"=>"Khartoum","name_href" => "sd/population-of-khartoum","count" => "2 682 431","real_id" =>32,),
"33"=>array("name_ru"=>"Северный Хартум","name_en"=>"Khartoum North","name_href" => "sd/population-of-khartoum-north","count" => "936 349","real_id" =>33,),
"34"=>array("name_ru"=>"Порт-Судан","name_en"=>"Port Sudan","name_href" => "sd/population-of-port-sudan","count" => "585 090","real_id" =>34,),
"35"=>array("name_ru"=>"Кассала","name_en"=>"Kassala","name_href" => "sd/population-of-kassala","count" => "510 165","real_id" =>35,)
);

?>