<?php
//Восточный тимор 65 
$libtl = array ( 
"1"=>array("name_ru"=>"Дон-Алейшу","name_en"=>"Don-Aleixo","name_href" => "tl/population-of-don-aleixo","count" => "105 154","real_id" =>1,),
"2"=>array("name_ru"=>"Кристу-Рей","name_en"=>"Christa Rey","name_href" => "tl/population-of-christa-rey","count" => "54 936","real_id" =>2,),
"3"=>array("name_ru"=>"Баукау","name_en"=>"Baucau","name_href" => "tl/population-of-baucau","count" => "46 500","real_id" =>3,),
"4"=>array("name_ru"=>"Панте-Макассар","name_en"=>"Pante-Makassar","name_href" => "tl/population-of-pante-makassar","count" => "35 226","real_id" =>4,),
"5"=>array("name_ru"=>"Хатулья","name_en"=>"Hatula","name_href" => "tl/population-of-hatula","count" => "34 999","real_id" =>5,),
"6"=>array("name_ru"=>"Вера-Крус","name_en"=>"Vera Cruz","name_href" => "tl/population-of-vera-cruz","count" => "34 015","real_id" =>6,),
"7"=>array("name_ru"=>"Эрмера","name_en"=>"Ermera","name_href" => "tl/population-of-ermera","count" => "33 530","real_id" =>7,),
"8"=>array("name_ru"=>"Лоспалос","name_en"=>"Lospalos","name_href" => "tl/population-of-lospalos","count" => "29 236","real_id" =>8,),
"9"=>array("name_ru"=>"Саме","name_en"=>"Sama","name_href" => "tl/population-of-sama","count" => "27 554","real_id" =>9,),
"10"=>array("name_ru"=>"Наин-Фету","name_en"=>"Nain-FET","name_href" => "tl/population-of-nain-fet","count" => "26 592","real_id" =>10,),
"11"=>array("name_ru"=>"Мальяна","name_en"=>"Magliana","name_href" => "tl/population-of-magliana","count" => "25 234","real_id" =>11,),
"12"=>array("name_ru"=>"Суаи","name_en"=>"SUAI","name_href" => "tl/population-of-suai","count" => "25 164","real_id" =>12,),
"13"=>array("name_ru"=>"Викеке","name_en"=>"Viqueque","name_href" => "tl/population-of-viqueque","count" => "24 387","real_id" =>13,),
"14"=>array("name_ru"=>"Базартете","name_en"=>"The sub","name_href" => "tl/population-of-the-sub","count" => "23 955","real_id" =>14,),
"15"=>array("name_ru"=>"Бобонару","name_en"=>"Bobonaro","name_href" => "tl/population-of-bobonaro","count" => "23 854","real_id" =>15,),
"16"=>array("name_ru"=>"Маубиссе","name_en"=>"Maubisse","name_href" => "tl/population-of-maubisse","count" => "22 022","real_id" =>16,),
"17"=>array("name_ru"=>"Ликиса","name_en"=>"Liquica","name_href" => "tl/population-of-liquica","count" => "20 938","real_id" =>17,),
"18"=>array("name_ru"=>"Летефоху","name_en"=>"Letefoho","name_href" => "tl/population-of-letefoho","count" => "20 887","real_id" =>18,),
"19"=>array("name_ru"=>"Айлеу","name_en"=>"Aileu","name_href" => "tl/population-of-aileu","count" => "20 830","real_id" =>19,),
"20"=>array("name_ru"=>"Маубара","name_en"=>"Maubara","name_href" => "tl/population-of-maubara","count" => "18 510","real_id" =>20,),
"21"=>array("name_ru"=>"Атсабе","name_en"=>"Atsabe","name_href" => "tl/population-of-atsabe","count" => "17 264","real_id" =>21,),
"22"=>array("name_ru"=>"Уату-Лари","name_en"=>"The UAT-Gel","name_href" => "tl/population-of-the-uat-gel","count" => "16 972","real_id" =>22,),
"23"=>array("name_ru"=>"Келикай","name_en"=>"Celica","name_href" => "tl/population-of-celica","count" => "16 747","real_id" =>23,),
"24"=>array("name_ru"=>"Оссу","name_en"=>"Ossa","name_href" => "tl/population-of-ossa","count" => "15 612","real_id" =>24,),
"25"=>array("name_ru"=>"Айнару","name_en"=>"Ainaro","name_href" => "tl/population-of-ainaro","count" => "15 558","real_id" =>25,),
"26"=>array("name_ru"=>"Венилале","name_en"=>"Venilale","name_href" => "tl/population-of-venilale","count" => "15 542","real_id" =>26,),
"27"=>array("name_ru"=>"Балибу","name_en"=>"Balibo","name_href" => "tl/population-of-balibo","count" => "14 851","real_id" =>27,),
"28"=>array("name_ru"=>"Лага","name_en"=>"Lag","name_href" => "tl/population-of-lag","count" => "14 432","real_id" =>28,),
"29"=>array("name_ru"=>"Лаутен","name_en"=>"Lauten","name_href" => "tl/population-of-lauten","count" => "14 147","real_id" =>29,),
"30"=>array("name_ru"=>"Манатуту","name_en"=>"Manatuto","name_href" => "tl/population-of-manatuto","count" => "12 555","real_id" =>30,),
"31"=>array("name_ru"=>"Хату-Буилику","name_en"=>"Hut-Builico","name_href" => "tl/population-of-hut-builico","count" => "11 950","real_id" =>31,),
"32"=>array("name_ru"=>"Лаклубар","name_en"=>"Laclubar","name_href" => "tl/population-of-laclubar","count" => "11 682","real_id" =>32,),
"33"=>array("name_ru"=>"Зумалай","name_en"=>"Somali","name_href" => "tl/population-of-somali","count" => "11 639","real_id" =>33,),
"34"=>array("name_ru"=>"Нитибе","name_en"=>"Nitibe","name_href" => "tl/population-of-nitibe","count" => "11 366","real_id" =>34,),
"35"=>array("name_ru"=>"Атабаэ","name_en"=>"Atabae","name_href" => "tl/population-of-atabae","count" => "11 024","real_id" =>35,),
"36"=>array("name_ru"=>"Райлаку","name_en"=>"Railaco","name_href" => "tl/population-of-railaco","count" => "10 384","real_id" =>36,),
"37"=>array("name_ru"=>"Ремешиу","name_en"=>"Remexio","name_href" => "tl/population-of-remexio","count" => "10 055","real_id" =>37,),
"38"=>array("name_ru"=>"Кайлаку","name_en"=>"Kailako","name_href" => "tl/population-of-kailako","count" => "9 957","real_id" =>38,),
"39"=>array("name_ru"=>"Осилу","name_en"=>"Osilo","name_href" => "tl/population-of-osilo","count" => "9 861","real_id" =>39,),
"40"=>array("name_ru"=>"Хату-Уду","name_en"=>"Hatu-Udu","name_href" => "tl/population-of-hatu-udu","count" => "9 645","real_id" =>40,),
"41"=>array("name_ru"=>"Багия","name_en"=>"Bahia","name_href" => "tl/population-of-bahia","count" => "9 465","real_id" =>41,),
"42"=>array("name_ru"=>"Вемассе","name_en"=>"Vemasse","name_href" => "tl/population-of-vemasse","count" => "9 008","real_id" =>42,),
"43"=>array("name_ru"=>"Атауро","name_en"=>"Atauro","name_href" => "tl/population-of-atauro","count" => "8 602","real_id" =>43,),
"44"=>array("name_ru"=>"Лаклу","name_en"=>"Lalu","name_href" => "tl/population-of-lalu","count" => "7 618","real_id" =>44,),
"45"=>array("name_ru"=>"Пассабе","name_en"=>"Passabe","name_href" => "tl/population-of-passabe","count" => "7 572","real_id" =>45,),
"46"=>array("name_ru"=>"Уатукарбау","name_en"=>"Watukaru","name_href" => "tl/population-of-watukaru","count" => "7 212","real_id" =>46,),
"47"=>array("name_ru"=>"Илиомар","name_en"=>"Iliomar","name_href" => "tl/population-of-iliomar","count" => "7 201","real_id" =>47,),
"48"=>array("name_ru"=>"Алас","name_en"=>"Alas","name_href" => "tl/population-of-alas","count" => "7 179","real_id" =>48,),
"49"=>array("name_ru"=>"Лаулара","name_en"=>"Laulara","name_href" => "tl/population-of-laulara","count" => "7 173","real_id" =>49,),
"50"=>array("name_ru"=>"Лолоту","name_en"=>"Lolota","name_href" => "tl/population-of-lolota","count" => "7 129","real_id" =>50,),
"51"=>array("name_ru"=>"Тиломар","name_en"=>"Tilomar","name_href" => "tl/population-of-tilomar","count" => "7 043","real_id" =>51,),
"52"=>array("name_ru"=>"Турискай","name_en"=>"Turiscai","name_href" => "tl/population-of-turiscai","count" => "6 993","real_id" =>52,),
"53"=>array("name_ru"=>"Фатуберлиу","name_en"=>"Fatuberliu","name_href" => "tl/population-of-fatuberliu","count" => "6 902","real_id" =>53,),
"54"=>array("name_ru"=>"Маукатар","name_en"=>"Marketer","name_href" => "tl/population-of-marketer","count" => "6 291","real_id" =>54,),
"55"=>array("name_ru"=>"Лекидо","name_en"=>"Lucido","name_href" => "tl/population-of-lucido","count" => "6 267","real_id" =>55,),
"56"=>array("name_ru"=>"Лаклута","name_en"=>"Lacluta","name_href" => "tl/population-of-lacluta","count" => "5 853","real_id" =>56,),
"57"=>array("name_ru"=>"Луру","name_en"=>"Lure","name_href" => "tl/population-of-lure","count" => "5 367","real_id" =>57,),
"58"=>array("name_ru"=>"Барике","name_en"=>"Barika","name_href" => "tl/population-of-barika","count" => "4 768","real_id" =>58,),
"59"=>array("name_ru"=>"Метинару","name_en"=>"Metinaro","name_href" => "tl/population-of-metinaro","count" => "4 727","real_id" =>59,),
"60"=>array("name_ru"=>"Фохорен","name_en"=>"Fohoren","name_href" => "tl/population-of-fohoren","count" => "4 092","real_id" =>60,),
"61"=>array("name_ru"=>"Тутуала","name_en"=>"Tutuala","name_href" => "tl/population-of-tutuala","count" => "3 836","real_id" =>61,),
"62"=>array("name_ru"=>"Фатумеан","name_en"=>"Fatumean","name_href" => "tl/population-of-fatumean","count" => "3 332","real_id" =>62,),
"63"=>array("name_ru"=>"Лалейя","name_en"=>"Laleia","name_href" => "tl/population-of-laleia","count" => "3 089","real_id" =>63,),
"64"=>array("name_ru"=>"Сойбада","name_en"=>"Soibada","name_href" => "tl/population-of-soibada","count" => "3 030","real_id" =>64,),
"65"=>array("name_ru"=>"Фаталулик","name_en"=>"Fatally","name_href" => "tl/population-of-fatally","count" => "1 894","real_id" =>65,),
"66"=>array("name_ru"=>"Дон-Алейшу","name_en"=>"Don-Aleixo","name_href" => "tl/population-of-don-aleixo","count" => "105 154","real_id" =>66,),
"67"=>array("name_ru"=>"Кристу-Рей","name_en"=>"Christa Rey","name_href" => "tl/population-of-christa-rey","count" => "54 936","real_id" =>67,),
"68"=>array("name_ru"=>"Баукау","name_en"=>"Baucau","name_href" => "tl/population-of-baucau","count" => "46 500","real_id" =>68,),
"69"=>array("name_ru"=>"Панте-Макассар","name_en"=>"Pante-Makassar","name_href" => "tl/population-of-pante-makassar","count" => "35 226","real_id" =>69,),
"70"=>array("name_ru"=>"Хатулья","name_en"=>"Hatula","name_href" => "tl/population-of-hatula","count" => "34 999","real_id" =>70,)
);

?>