<?php
//Уругвай 40 
$libuy = array ( 
"1"=>array("name_ru"=>"Монтевидео","name_en"=>"Montevideo","name_href" => "uy/population-of-montevideo","count" => "1 304 687","real_id" =>1,),
"2"=>array("name_ru"=>"Сальто","name_en"=>"Flip","name_href" => "uy/population-of-flip","count" => "104 028","real_id" =>2,),
"3"=>array("name_ru"=>"Сьюдад-де-ла-Коста","name_en"=>"Ciudad de la Costa","name_href" => "uy/population-of-ciudad-de-la-costa","count" => "95 176","real_id" =>3,),
"4"=>array("name_ru"=>"Пайсанду","name_en"=>"Paysandu","name_href" => "uy/population-of-paysandu","count" => "76 412","real_id" =>4,),
"5"=>array("name_ru"=>"Лас-Пьедрас","name_en"=>"Las Piedras","name_href" => "uy/population-of-las-piedras","count" => "71 258","real_id" =>5,),
"6"=>array("name_ru"=>"Ривера","name_en"=>"Rivera","name_href" => "uy/population-of-rivera","count" => "64 465","real_id" =>6,),
"7"=>array("name_ru"=>"Мальдонадо","name_en"=>"Maldonado","name_href" => "uy/population-of-maldonado","count" => "62 590","real_id" =>7,),
"8"=>array("name_ru"=>"Такуарембо","name_en"=>"Tacuarembo","name_href" => "uy/population-of-tacuarembo","count" => "54 755","real_id" =>8,),
"9"=>array("name_ru"=>"Мело","name_en"=>"Melo","name_href" => "uy/population-of-melo","count" => "51 830","real_id" =>9,),
"10"=>array("name_ru"=>"Мерседес","name_en"=>"Mercedes","name_href" => "uy/population-of-mercedes","count" => "41 974","real_id" =>10,),
"11"=>array("name_ru"=>"Артигас","name_en"=>"Artigas","name_href" => "uy/population-of-artigas","count" => "40 657","real_id" =>11,),
"12"=>array("name_ru"=>"Минас","name_en"=>"Minas","name_href" => "uy/population-of-minas","count" => "38 446","real_id" =>12,),
"13"=>array("name_ru"=>"Сан-Хосе-де-Майо","name_en"=>"San José de Mayo","name_href" => "uy/population-of-san-josé-de-mayo","count" => "36 743","real_id" =>13,),
"14"=>array("name_ru"=>"Дурасно","name_en"=>"Durazno","name_href" => "uy/population-of-durazno","count" => "34 368","real_id" =>14,),
"15"=>array("name_ru"=>"Флорида","name_en"=>"Florida","name_href" => "uy/population-of-florida","count" => "33 639","real_id" =>15,),
"16"=>array("name_ru"=>"Баррос-Бланкос","name_en"=>"Barros Blancos","name_href" => "uy/population-of-barros-blancos","count" => "31 650","real_id" =>16,),
"17"=>array("name_ru"=>"Сьюдад-дель-Плата","name_en"=>"Ciudad del Plata","name_href" => "uy/population-of-ciudad-del-plata","count" => "31 145","real_id" =>17,),
"18"=>array("name_ru"=>"Сан-Карлос","name_en"=>"San Carlos","name_href" => "uy/population-of-san-carlos","count" => "27 471","real_id" =>18,),
"19"=>array("name_ru"=>"Колония-дель-Сакраменто","name_en"=>"Colonia del Sacramento","name_href" => "uy/population-of-colonia-del-sacramento","count" => "26 231","real_id" =>19,),
"20"=>array("name_ru"=>"Пандо","name_en"=>"Pando","name_href" => "uy/population-of-pando","count" => "25 947","real_id" =>20,),
"21"=>array("name_ru"=>"Трейнта-и-Трес","name_en"=>"Treinta y Tres","name_href" => "uy/population-of-treinta-y-tres","count" => "25 476","real_id" =>21,),
"22"=>array("name_ru"=>"Роча","name_en"=>"Rocha","name_href" => "uy/population-of-rocha","count" => "25 420","real_id" =>22,),
"23"=>array("name_ru"=>"Фрай-Бентос","name_en"=>"Fray Bentos","name_href" => "uy/population-of-fray-bentos","count" => "24 406","real_id" =>23,),
"24"=>array("name_ru"=>"Тринидад","name_en"=>"Trinidad","name_href" => "uy/population-of-trinidad","count" => "21 429","real_id" =>24,),
"25"=>array("name_ru"=>"Эль-Пинар","name_en"=>"El Pinar","name_href" => "uy/population-of-el-pinar","count" => "21 091","real_id" =>25,),
"26"=>array("name_ru"=>"Ла-Пас","name_en"=>"La Paz","name_href" => "uy/population-of-la-paz","count" => "20 524","real_id" =>26,),
"27"=>array("name_ru"=>"Канелонес","name_en"=>"Canelones","name_href" => "uy/population-of-canelones","count" => "19 865","real_id" =>27,),
"28"=>array("name_ru"=>"Кармело","name_en"=>"Carmelo","name_href" => "uy/population-of-carmelo","count" => "18 041","real_id" =>28,),
"29"=>array("name_ru"=>"Долорес","name_en"=>"Dolores","name_href" => "uy/population-of-dolores","count" => "17 174","real_id" =>29,),
"30"=>array("name_ru"=>"Янг","name_en"=>"Young","name_href" => "uy/population-of-young","count" => "16 756","real_id" =>30,),
"31"=>array("name_ru"=>"Санта-Лусия","name_en"=>"Santa Lucia","name_href" => "uy/population-of-santa-lucia","count" => "16 742","real_id" =>31,),
"32"=>array("name_ru"=>"Прогресо","name_en"=>"Progreso","name_href" => "uy/population-of-progreso","count" => "16 244","real_id" =>32,),
"33"=>array("name_ru"=>"Пасо-Карраско","name_en"=>"Paso Carrasco","name_href" => "uy/population-of-paso-carrasco","count" => "15 908","real_id" =>33,),
"34"=>array("name_ru"=>"Рио-Бранко","name_en"=>"Rio Branco","name_href" => "uy/population-of-rio-branco","count" => "14 604","real_id" =>34,),
"35"=>array("name_ru"=>"Пасо-де-лос-Торос","name_en"=>"Paso de los Toros","name_href" => "uy/population-of-paso-de-los-toros","count" => "12 985","real_id" =>35,),
"36"=>array("name_ru"=>"Хуан-Лакасе","name_en"=>"Juan Lacaze","name_href" => "uy/population-of-juan-lacaze","count" => "12 816","real_id" =>36,),
"37"=>array("name_ru"=>"Белья-Унион","name_en"=>"Bella Unión","name_href" => "uy/population-of-bella-unión","count" => "12 201","real_id" =>37,),
"38"=>array("name_ru"=>"Нуэва-Эльвесия","name_en"=>"Nueva helvecia","name_href" => "uy/population-of-nueva-helvecia","count" => "10 630","real_id" =>38,),
"39"=>array("name_ru"=>"Росарио","name_en"=>"Rosar","name_href" => "uy/population-of-rosar","count" => "10 085","real_id" =>39,),
"40"=>array("name_ru"=>"Чуй","name_en"=>"Chui","name_href" => "uy/population-of-chui","count" => "9 675","real_id" =>40,),
"41"=>array("name_ru"=>"Монтевидео","name_en"=>"Montevideo","name_href" => "uy/population-of-montevideo","count" => "1 304 687","real_id" =>41,),
"42"=>array("name_ru"=>"Сальто","name_en"=>"Flip","name_href" => "uy/population-of-flip","count" => "104 028","real_id" =>42,),
"43"=>array("name_ru"=>"Сьюдад-де-ла-Коста","name_en"=>"Ciudad de la Costa","name_href" => "uy/population-of-ciudad-de-la-costa","count" => "95 176","real_id" =>43,),
"44"=>array("name_ru"=>"Пайсанду","name_en"=>"Paysandu","name_href" => "uy/population-of-paysandu","count" => "76 412","real_id" =>44,),
"45"=>array("name_ru"=>"Лас-Пьедрас","name_en"=>"Las Piedras","name_href" => "uy/population-of-las-piedras","count" => "71 258","real_id" =>45,)
);

?>