<?php
//Вьетнам 75
$libvn = array ( 
"1"=>array("name_ru"=>"Хошимин","name_en"=>"Ho Chi Minh city","name_href" => "vn/population-of-ho-chi-minh-city","count" => "7 955 000","real_id" =>1,),
"2"=>array("name_ru"=>"Ханой","name_en"=>"Hanoi","name_href" => "vn/population-of-hanoi","count" => "6 448 837","real_id" =>2,),
"3"=>array("name_ru"=>"Хайфон","name_en"=>"Haiphong","name_href" => "vn/population-of-haiphong","count" => "1 837 302","real_id" =>3,),
"4"=>array("name_ru"=>"Кантхо","name_en"=>"Can tho","name_href" => "vn/population-of-can-tho","count" => "1 214 100","real_id" =>4,),
"5"=>array("name_ru"=>"Чавинь","name_en"=>"Tra Vinh","name_href" => "vn/population-of-tra-vinh","count" => "1 000 933","real_id" =>5,),
"6"=>array("name_ru"=>"Дананг","name_en"=>"Da Nang","name_href" => "vn/population-of-da-nang","count" => "887 069","real_id" =>6,),
"7"=>array("name_ru"=>"Бьенхоа","name_en"=>"Bien Hoa","name_href" => "vn/population-of-bien-hoa","count" => "784 398","real_id" =>7,),
"8"=>array("name_ru"=>"Куангчи","name_en"=>"Quang tri","name_href" => "vn/population-of-quang-tri","count" => "597 985","real_id" =>8,),
"9"=>array("name_ru"=>"Винь","name_en"=>"Vinh","name_href" => "vn/population-of-vinh","count" => "435 208","real_id" =>9,),
"10"=>array("name_ru"=>"Тханьхоа","name_en"=>"Thanh Hoa","name_href" => "vn/population-of-thanh-hoa","count" => "406 550","real_id" =>10,),
"11"=>array("name_ru"=>"Нячанг","name_en"=>"Nha Trang","name_href" => "vn/population-of-nha-trang","count" => "392 279","real_id" =>11,),
"12"=>array("name_ru"=>"Буонматхуот","name_en"=>"Buonmathuot","name_href" => "vn/population-of-buonmathuot","count" => "340 000","real_id" =>12,),
"13"=>array("name_ru"=>"Хюэ","name_en"=>"Hue","name_href" => "vn/population-of-hue","count" => "333 004","real_id" =>13,),
"14"=>array("name_ru"=>"Далат","name_en"=>"Dalat","name_href" => "vn/population-of-dalat","count" => "301 243","real_id" =>14,),
"15"=>array("name_ru"=>"Куинён","name_en"=>"Quy Nhon","name_href" => "vn/population-of-quy-nhon","count" => "280 900","real_id" =>15,),
"16"=>array("name_ru"=>"Туихоа","name_en"=>"Tuy hòa","name_href" => "vn/population-of-tuy-hòa","count" => "262 287","real_id" =>16,),
"17"=>array("name_ru"=>"Намдинь","name_en"=>"Nam Dinh","name_href" => "vn/population-of-nam-dinh","count" => "243 186","real_id" =>17,),
"18"=>array("name_ru"=>"Вунгтау","name_en"=>"Vung Tau","name_href" => "vn/population-of-vung-tau","count" => "240 000","real_id" =>18,),
"19"=>array("name_ru"=>"Ратьзя","name_en"=>"Rach Gia","name_href" => "vn/population-of-rach-gia","count" => "230 365","real_id" =>19,),
"20"=>array("name_ru"=>"Митхо","name_en"=>"My tho","name_href" => "vn/population-of-my-tho","count" => "215 000","real_id" =>20,),
"21"=>array("name_ru"=>"Фантхиет","name_en"=>"Phan Thiet","name_href" => "vn/population-of-phan-thiet","count" => "205 333","real_id" =>21,),
"22"=>array("name_ru"=>"Камау","name_en"=>"Kamau","name_href" => "vn/population-of-kamau","count" => "204 895","real_id" =>22,),
"23"=>array("name_ru"=>"Камфа","name_en"=>"Kamfa","name_href" => "vn/population-of-kamfa","count" => "195 800","real_id" =>23,),
"24"=>array("name_ru"=>"Хайзыонг","name_en"=>"Hai Duong","name_href" => "vn/population-of-hai-duong","count" => "187 405","real_id" =>24,),
"25"=>array("name_ru"=>"Тхузаумот","name_en"=>"Thudaumot","name_href" => "vn/population-of-thudaumot","count" => "187 379","real_id" =>25,),
"26"=>array("name_ru"=>"Уонгби","name_en"=>"Uongbi","name_href" => "vn/population-of-uongbi","count" => "174 678","real_id" =>26,),
"27"=>array("name_ru"=>"Лонгсюен","name_en"=>"Long Xuyen","name_href" => "vn/population-of-long-xuyen","count" => "168 376","real_id" =>27,),
"28"=>array("name_ru"=>"Танан","name_en"=>"Tanan","name_href" => "vn/population-of-tanan","count" => "166 419","real_id" =>28,),
"29"=>array("name_ru"=>"Фанранг-Тхаптям","name_en"=>"Phan Rang-Taptam","name_href" => "vn/population-of-phan-rang-taptam","count" => "161 730","real_id" =>29,),
"30"=>array("name_ru"=>"Каолань","name_en"=>"The capital","name_href" => "vn/population-of-the-capital","count" => "161 292","real_id" =>30,),
"31"=>array("name_ru"=>"Халонг","name_en"=>"Halong","name_href" => "vn/population-of-halong","count" => "158 171","real_id" =>31,),
"32"=>array("name_ru"=>"Хонггай","name_en"=>"Honggi","name_href" => "vn/population-of-honggi","count" => "158 171","real_id" =>32,),
"33"=>array("name_ru"=>"Тяудок","name_en"=>"Chau Doc","name_href" => "vn/population-of-chau-doc","count" => "157 298","real_id" =>33,),
"34"=>array("name_ru"=>"Бариа","name_en"=>"Baria","name_href" => "vn/population-of-baria","count" => "153 862","real_id" =>34,),
"35"=>array("name_ru"=>"Баолок","name_en"=>"Bao loc","name_href" => "vn/population-of-bao-loc","count" => "148 567","real_id" =>35,),
"36"=>array("name_ru"=>"Лангшон","name_en"=>"Lang son","name_href" => "vn/population-of-lang-son","count" => "148 000","real_id" =>36,),
"37"=>array("name_ru"=>"Плейку","name_en"=>"Pleiku","name_href" => "vn/population-of-pleiku","count" => "146 073","real_id" =>37,),
"38"=>array("name_ru"=>"Бенче","name_en"=>"Bench","name_href" => "vn/population-of-bench","count" => "143 639","real_id" =>38,),
"39"=>array("name_ru"=>"Контум","name_en"=>"Manda","name_href" => "vn/population-of-manda","count" => "143 467","real_id" =>39,),
"40"=>array("name_ru"=>"Тхайнгуен","name_en"=>"Thai Nguyen","name_href" => "vn/population-of-thai-nguyen","count" => "138 910","real_id" =>40,),
"41"=>array("name_ru"=>"Бакльеу","name_en"=>"BAC lieu","name_href" => "vn/population-of-bac-lieu","count" => "126 836","real_id" =>41,),
"42"=>array("name_ru"=>"Камрань","name_en"=>"Cam Ranh","name_href" => "vn/population-of-cam-ranh","count" => "125 311","real_id" =>42,),
"43"=>array("name_ru"=>"Шокчанг","name_en"=>"SOC Trang","name_href" => "vn/population-of-soc-trang","count" => "122 250","real_id" =>43,),
"44"=>array("name_ru"=>"Хойан","name_en"=>"Hoi an","name_href" => "vn/population-of-hoi-an","count" => "121 716","real_id" =>44,),
"45"=>array("name_ru"=>"Хоабинь","name_en"=>"Hoa Binh","name_href" => "vn/population-of-hoa-binh","count" => "121 309","real_id" =>45,),
"46"=>array("name_ru"=>"Йенбай","name_en"=>"Yen Bai","name_href" => "vn/population-of-yen-bai","count" => "118 629","real_id" =>46,),
"47"=>array("name_ru"=>"Хатинь","name_en"=>"Ha Tinh","name_href" => "vn/population-of-ha-tinh","count" => "117 546","real_id" =>47,),
"48"=>array("name_ru"=>"Туенкуанг","name_en"=>"Tuyen Quang","name_href" => "vn/population-of-tuyen-quang","count" => "110 119","real_id" =>48,),
"49"=>array("name_ru"=>"Шадек","name_en"=>"Sa Dec","name_href" => "vn/population-of-sa-dec","count" => "103 646","real_id" =>49,),
"50"=>array("name_ru"=>"Виньлонг","name_en"=>"Vinh long","name_href" => "vn/population-of-vinh-long","count" => "103 067","real_id" =>50,),
"51"=>array("name_ru"=>"Донгхой","name_en"=>"Dong Hoi","name_href" => "vn/population-of-dong-hoi","count" => "103 000","real_id" =>51,),
"52"=>array("name_ru"=>"Вьетчи","name_en"=>"Vetchi","name_href" => "vn/population-of-vetchi","count" => "99 147","real_id" =>52,),
"53"=>array("name_ru"=>"Лаокай","name_en"=>"Lao Cai","name_href" => "vn/population-of-lao-cai","count" => "98 363","real_id" =>53,),
"54"=>array("name_ru"=>"Витхань","name_en"=>"Within","name_href" => "vn/population-of-within","count" => "97 200","real_id" =>54,),
"55"=>array("name_ru"=>"Донгсоай","name_en"=>"Dongsi","name_href" => "vn/population-of-dongsi","count" => "95 820","real_id" =>55,),
"56"=>array("name_ru"=>"Виньиен","name_en"=>"Vignan","name_href" => "vn/population-of-vignan","count" => "94 294","real_id" =>56,),
"57"=>array("name_ru"=>"Каобанг","name_en"=>"Cao Bang","name_href" => "vn/population-of-cao-bang","count" => "84 421","real_id" =>57,),
"58"=>array("name_ru"=>"Монгкай","name_en"=>"Mongcai","name_href" => "vn/population-of-mongcai","count" => "80 000","real_id" =>58,),
"59"=>array("name_ru"=>"Дьенбьенфу","name_en"=>"Dien bien Phu","name_href" => "vn/population-of-dien-bien-phu","count" => "70 000","real_id" =>59,),
"60"=>array("name_ru"=>"Тамки","name_en"=>"Tamky","name_href" => "vn/population-of-tamky","count" => "59 097","real_id" =>60,),
"61"=>array("name_ru"=>"Баккан","name_en"=>"BAC Kan","name_href" => "vn/population-of-bac-kan","count" => "57 800","real_id" =>61,),
"62"=>array("name_ru"=>"Тэйнинь","name_en"=>"Tay Ninh","name_href" => "vn/population-of-tay-ninh","count" => "54 736","real_id" =>62,),
"63"=>array("name_ru"=>"Бакзянг","name_en"=>"BAC Giang","name_href" => "vn/population-of-bac-giang","count" => "53 925","real_id" =>63,),
"64"=>array("name_ru"=>"Хатьен","name_en"=>"Ha Tien","name_href" => "vn/population-of-ha-tien","count" => "47 039","real_id" =>64,),
"65"=>array("name_ru"=>"Тхайбинь","name_en"=>"In thái bình","name_href" => "vn/population-of-in-thái-bình","count" => "46 171","real_id" =>65,),
"66"=>array("name_ru"=>"Бакнинь","name_en"=>"Bakning","name_href" => "vn/population-of-bakning","count" => "43 793","real_id" =>66,),
"67"=>array("name_ru"=>"Хынгйен","name_en"=>"Hygien","name_href" => "vn/population-of-hygien","count" => "43 118","real_id" =>67,),
"68"=>array("name_ru"=>"Ниньбинь","name_en"=>"Ninh Binh","name_href" => "vn/population-of-ninh-binh","count" => "41 390","real_id" =>68,),
"69"=>array("name_ru"=>"Хазянг","name_en"=>"Ha Giang","name_href" => "vn/population-of-ha-giang","count" => "39 774","real_id" =>69,),
"70"=>array("name_ru"=>"Куангнгай","name_en"=>"Quang Ngai","name_href" => "vn/population-of-quang-ngai","count" => "33 301","real_id" =>70,),
"71"=>array("name_ru"=>"Нгиало","name_en"=>"Gialo","name_href" => "vn/population-of-gialo","count" => "27 336","real_id" =>71,),
"72"=>array("name_ru"=>"Лайтяу","name_en"=>"Lai Chau","name_href" => "vn/population-of-lai-chau","count" => "26 706","real_id" =>72,),
"73"=>array("name_ru"=>"Шонла","name_en"=>"Sonla","name_href" => "vn/population-of-sonla","count" => "22 368","real_id" =>73,),
"74"=>array("name_ru"=>"Донгха","name_en"=>"Dong Hoi","name_href" => "vn/population-of-dong-hoi","count" => "18 881","real_id" =>74,),
"75"=>array("name_ru"=>"Фули","name_en"=>"Fuli","name_href" => "vn/population-of-fuli","count" => "13 867","real_id" =>75,),
"76"=>array("name_ru"=>"Хошимин","name_en"=>"Ho Chi Minh city","name_href" => "vn/population-of-ho-chi-minh-city","count" => "7 955 000","real_id" =>76,),
"77"=>array("name_ru"=>"Ханой","name_en"=>"Hanoi","name_href" => "vn/population-of-hanoi","count" => "6 448 837","real_id" =>77,),
"78"=>array("name_ru"=>"Хайфон","name_en"=>"Haiphong","name_href" => "vn/population-of-haiphong","count" => "1 837 302","real_id" =>78,),
"79"=>array("name_ru"=>"Кантхо","name_en"=>"Can tho","name_href" => "vn/population-of-can-tho","count" => "1 214 100","real_id" =>79,),
"80"=>array("name_ru"=>"Чавинь","name_en"=>"Tra Vinh","name_href" => "vn/population-of-tra-vinh","count" => "1 000 933","real_id" =>80,)
);

?>