<?php
//Йемен 36
$libye = array ( 
"1"=>array("name_ru"=>"Сана","name_en"=>"Sana","name_href" => "ye/population-of-sana","count" => "2 575 347","real_id" =>1,),
"2"=>array("name_ru"=>"Таиз","name_en"=>"Taiz","name_href" => "ye/population-of-taiz","count" => "615 467","real_id" =>2,),
"3"=>array("name_ru"=>"Ходейда","name_en"=>"Hodeidah","name_href" => "ye/population-of-hodeidah","count" => "402 560","real_id" =>3,),
"4"=>array("name_ru"=>"Ибб","name_en"=>"IBB","name_href" => "ye/population-of-ibb","count" => "350 864","real_id" =>4,),
"5"=>array("name_ru"=>"Дуран","name_en"=>"Duran","name_href" => "ye/population-of-duran","count" => "230 839","real_id" =>5,),
"6"=>array("name_ru"=>"Дамар","name_en"=>"Damar","name_href" => "ye/population-of-damar","count" => "198 920","real_id" =>6,),
"7"=>array("name_ru"=>"Эль-Мукалла","name_en"=>"Al-Mukalla","name_href" => "ye/population-of-al-mukalla","count" => "176 942","real_id" =>7,),
"8"=>array("name_ru"=>"Амран","name_en"=>"Amran","name_href" => "ye/population-of-amran","count" => "92 763","real_id" =>8,),
"9"=>array("name_ru"=>"Аден","name_en"=>"Aden","name_href" => "ye/population-of-aden","count" => "80 000","real_id" =>9,),
"10"=>array("name_ru"=>"Сайвун","name_en"=>"Dali","name_href" => "ye/population-of-dali","count" => "75 700","real_id" =>10,),
"11"=>array("name_ru"=>"Саада","name_en"=>"Saad","name_href" => "ye/population-of-saad","count" => "70 203","real_id" =>11,),
"12"=>array("name_ru"=>"Баджиль","name_en"=>"Bagel","name_href" => "ye/population-of-bagel","count" => "69 435","real_id" =>12,),
"13"=>array("name_ru"=>"Ярим","name_en"=>"Yarim","name_href" => "ye/population-of-yarim","count" => "68 879","real_id" =>13,),
"14"=>array("name_ru"=>"Тарим","name_en"=>"Tarim","name_href" => "ye/population-of-tarim","count" => "59 964","real_id" =>14,),
"15"=>array("name_ru"=>"Рада","name_en"=>"Rada","name_href" => "ye/population-of-rada","count" => "57 212","real_id" =>15,),
"16"=>array("name_ru"=>"Эш-Шихр","name_en"=>"Ash-Shihr","name_href" => "ye/population-of-ash-shihr","count" => "47 663","real_id" =>16,),
"17"=>array("name_ru"=>"Байт-эль-Факих","name_en"=>"Bayt al-Faqih","name_href" => "ye/population-of-bayt-al-faqih","count" => "39 445","real_id" =>17,),
"18"=>array("name_ru"=>"Эль-Бейда","name_en"=>"El-Beida","name_href" => "ye/population-of-el-beida","count" => "34 419","real_id" =>18,),
"19"=>array("name_ru"=>"Хадджа","name_en"=>"Ḩajjah","name_href" => "ye/population-of-ḩajjah","count" => "34 136","real_id" =>19,),
"20"=>array("name_ru"=>"Джаар","name_en"=>"Jaar","name_href" => "ye/population-of-jaar","count" => "29 495","real_id" =>20,),
"21"=>array("name_ru"=>"Лахдж","name_en"=>"The lahj","name_href" => "ye/population-of-the-lahj","count" => "25 881","real_id" =>21,),
"22"=>array("name_ru"=>"Маабар","name_en"=>"Maabar","name_href" => "ye/population-of-maabar","count" => "24 707","real_id" =>22,),
"23"=>array("name_ru"=>"Зинджибар","name_en"=>"Zinjibar","name_href" => "ye/population-of-zinjibar","count" => "23 707","real_id" =>23,),
"24"=>array("name_ru"=>"Мариб","name_en"=>"Marib","name_href" => "ye/population-of-marib","count" => "17 000","real_id" =>24,),
"25"=>array("name_ru"=>"Джибла","name_en"=>"Jibla","name_href" => "ye/population-of-jibla","count" => "15 431","real_id" =>25,),
"26"=>array("name_ru"=>"Мокка","name_en"=>"Mocha","name_href" => "ye/population-of-mocha","count" => "14 562","real_id" =>26,),
"27"=>array("name_ru"=>"Эль-Гайда","name_en"=>"El Gaida","name_href" => "ye/population-of-el-gaida","count" => "13 987","real_id" =>27,),
"28"=>array("name_ru"=>"Шибам","name_en"=>"Shibam","name_href" => "ye/population-of-shibam","count" => "13 316","real_id" =>28,),
"29"=>array("name_ru"=>"Каатаба","name_en"=>"Kataba","name_href" => "ye/population-of-kataba","count" => "10 604","real_id" =>29,),
"30"=>array("name_ru"=>"Эль-Турба","name_en"=>"El-Turba","name_href" => "ye/population-of-el-turba","count" => "10 505","real_id" =>30,),
"31"=>array("name_ru"=>"Забид","name_en"=>"Zabid","name_href" => "ye/population-of-zabid","count" => "8 000","real_id" =>31,),
"32"=>array("name_ru"=>"Ахвар","name_en"=>"Ahwar","name_href" => "ye/population-of-ahwar","count" => "7 468","real_id" =>32,),
"33"=>array("name_ru"=>"Манаха","name_en"=>"Manākhah","name_href" => "ye/population-of-manākhah","count" => "7 455","real_id" =>33,),
"34"=>array("name_ru"=>"Хариб","name_en"=>"Harib","name_href" => "ye/population-of-harib","count" => "474","real_id" =>34,),
"35"=>array("name_ru"=>"Кэукэбани","name_en"=>"Kawkabani","name_href" => "ye/population-of-kawkabani","count" => "100","real_id" =>35,),
"36"=>array("name_ru"=>"Шабва","name_en"=>"Shabwa","name_href" => "ye/population-of-shabwa","count" => "28","real_id" =>36,),
"37"=>array("name_ru"=>"Сана","name_en"=>"Sana","name_href" => "ye/population-of-sana","count" => "2 575 347","real_id" =>37,),
"38"=>array("name_ru"=>"Таиз","name_en"=>"Taiz","name_href" => "ye/population-of-taiz","count" => "615 467","real_id" =>38,),
"39"=>array("name_ru"=>"Ходейда","name_en"=>"Hodeidah","name_href" => "ye/population-of-hodeidah","count" => "402 560","real_id" =>39,),
"40"=>array("name_ru"=>"Ибб","name_en"=>"IBB","name_href" => "ye/population-of-ibb","count" => "350 864","real_id" =>40,),
"41"=>array("name_ru"=>"Дуран","name_en"=>"Duran","name_href" => "ye/population-of-duran","count" => "230 839","real_id" =>41,)
);

?>