<?php
//Южная африка 50
$libza = array ( 
"1"=>array("name_ru"=>"Йоханнесбург","name_en"=>"Yohannesburg","name_href" => "za/population-of-yohannesburg","count" => "4 434 827","real_id" =>1,),
"2"=>array("name_ru"=>"Кейптаун","name_en"=>"Capetown","name_href" => "za/population-of-capetown","count" => "3 795 539","real_id" =>2,),
"3"=>array("name_ru"=>"Дурбан","name_en"=>"Durban","name_href" => "za/population-of-durban","count" => "3 720 953","real_id" =>3,),
"4"=>array("name_ru"=>"Соуэто","name_en"=>"Soweto","name_href" => "za/population-of-soweto","count" => "1 895 921","real_id" =>4,),
"5"=>array("name_ru"=>"Претория","name_en"=>"Pretoria","name_href" => "za/population-of-pretoria","count" => "1 815 889","real_id" =>5,),
"6"=>array("name_ru"=>"Порт-Элизабет","name_en"=>"Port Elizabeth","name_href" => "za/population-of-port-elizabeth","count" => "1 258 780","real_id" =>6,),
"7"=>array("name_ru"=>"Питермарицбург","name_en"=>"Pietermaritzburg","name_href" => "za/population-of-pietermaritzburg","count" => "1 035 116","real_id" =>7,),
"8"=>array("name_ru"=>"Бенони","name_en"=>"Benoni","name_href" => "za/population-of-benoni","count" => "729 952","real_id" =>8,),
"9"=>array("name_ru"=>"Велком","name_en"=>"Welkom","name_href" => "za/population-of-welkom","count" => "667 288","real_id" =>9,),
"10"=>array("name_ru"=>"Блумфонтейн","name_en"=>"Bloemfontein","name_href" => "za/population-of-bloemfontein","count" => "664 821","real_id" =>10,),
"11"=>array("name_ru"=>"Тембиза","name_en"=>"Tembiza","name_href" => "za/population-of-tembiza","count" => "655 693","real_id" =>11,),
"12"=>array("name_ru"=>"Сихлангу","name_en"=>"Sihlangu","name_href" => "za/population-of-sihlangu","count" => "525 100","real_id" =>12,),
"13"=>array("name_ru"=>"Боксбург","name_en"=>"Boksburg","name_href" => "za/population-of-boksburg","count" => "520 980","real_id" =>13,),
"14"=>array("name_ru"=>"Феринихинг","name_en"=>"Vereeniging","name_href" => "za/population-of-vereeniging","count" => "497 731","real_id" =>14,),
"15"=>array("name_ru"=>"Ист-Лондон","name_en"=>"East London","name_href" => "za/population-of-east-london","count" => "463 651","real_id" =>15,),
"16"=>array("name_ru"=>"Крюгерсдорп","name_en"=>"Krugersdorp","name_href" => "za/population-of-krugersdorp","count" => "453 719","real_id" =>16,),
"17"=>array("name_ru"=>"Ботшабело","name_en"=>"Botshabelo","name_href" => "za/population-of-botshabelo","count" => "447 603","real_id" =>17,),
"18"=>array("name_ru"=>"Бракпан","name_en"=>"Brakpan","name_href" => "za/population-of-brakpan","count" => "400 630","real_id" =>18,),
"19"=>array("name_ru"=>"Ричардс-Бей","name_en"=>"Richards Bay","name_href" => "za/population-of-richards-bay","count" => "367 984","real_id" =>19,),
"20"=>array("name_ru"=>"Эмалахлени","name_en"=>"Witbank","name_href" => "za/population-of-witbank","count" => "349 076","real_id" =>20,),
"21"=>array("name_ru"=>"Вервоердбург","name_en"=>"Vervoerdburg","name_href" => "za/population-of-vervoerdburg","count" => "335 905","real_id" =>21,),
"22"=>array("name_ru"=>"Эйтенхахе","name_en"=>"Uitenhage","name_href" => "za/population-of-uitenhage","count" => "305 844","real_id" =>22,),
"23"=>array("name_ru"=>"Джордж","name_en"=>"George","name_href" => "za/population-of-george","count" => "235 397","real_id" =>23,),
"24"=>array("name_ru"=>"Ембаленхле","name_en"=>"Embalenhle","name_href" => "za/population-of-embalenhle","count" => "229 414","real_id" =>24,),
"25"=>array("name_ru"=>"Фандербейлпак","name_en"=>"Fanderbeylpak","name_href" => "za/population-of-fanderbeylpak","count" => "225 621","real_id" =>25,),
"26"=>array("name_ru"=>"Сомерсет-Уэст","name_en"=>"Somerset West","name_href" => "za/population-of-somerset-west","count" => "217 329","real_id" =>26,),
"27"=>array("name_ru"=>"Альбертон","name_en"=>"Alberton","name_href" => "za/population-of-alberton","count" => "212 337","real_id" =>27,),
"28"=>array("name_ru"=>"Врайхайд","name_en"=>"Vryheid","name_href" => "za/population-of-vryheid","count" => "209 620","real_id" =>28,),
"29"=>array("name_ru"=>"Мидделбург","name_en"=>"Middelburg","name_href" => "za/population-of-middelburg","count" => "205 403","real_id" =>29,),
"30"=>array("name_ru"=>"Парл","name_en"=>"Parla","name_href" => "za/population-of-parla","count" => "200 341","real_id" =>30,),
"31"=>array("name_ru"=>"Вирджиния","name_en"=>"Virginia","name_href" => "za/population-of-virginia","count" => "196 320","real_id" =>31,),
"32"=>array("name_ru"=>"Кимберли","name_en"=>"Kimberly","name_href" => "za/population-of-kimberly","count" => "191 194","real_id" =>32,),
"33"=>array("name_ru"=>"Карлтонвилл","name_en"=>"Carletonville","name_href" => "za/population-of-carletonville","count" => "186 018","real_id" =>33,),
"34"=>array("name_ru"=>"Клерксдорп","name_en"=>"Klerksdorp","name_href" => "za/population-of-klerksdorp","count" => "185 646","real_id" =>34,),
"35"=>array("name_ru"=>"Мпумаланга","name_en"=>"Mpumalanga","name_href" => "za/population-of-mpumalanga","count" => "184 919","real_id" =>35,),
"36"=>array("name_ru"=>"Мидранд","name_en"=>"Midrand","name_href" => "za/population-of-midrand","count" => "181 411","real_id" =>36,),
"37"=>array("name_ru"=>"Спрингс","name_en"=>"Springs","name_href" => "za/population-of-springs","count" => "170 373","real_id" =>37,),
"38"=>array("name_ru"=>"Оркни","name_en"=>"Orkney","name_href" => "za/population-of-orkney","count" => "170 366","real_id" =>38,),
"39"=>array("name_ru"=>"Найджел[en][2]","name_en"=>"Nigel","name_href" => "za/population-of-nigel","count" => "166 266","real_id" =>39,),
"40"=>array("name_ru"=>"Вестонария","name_en"=>"Westonaria","name_href" => "za/population-of-westonaria","count" => "164 447","real_id" =>40,),
"41"=>array("name_ru"=>"Бетхал","name_en"=>"Bethal","name_href" => "za/population-of-bethal","count" => "157 073","real_id" =>41,),
"42"=>array("name_ru"=>"Куинстаун","name_en"=>"Queenstown","name_href" => "za/population-of-queenstown","count" => "154 617","real_id" =>42,),
"43"=>array("name_ru"=>"Делмас","name_en"=>"Delmas","name_href" => "za/population-of-delmas","count" => "153 026","real_id" =>43,),
"44"=>array("name_ru"=>"Бишо","name_en"=>"Bisho","name_href" => "za/population-of-bisho","count" => "150 995","real_id" =>44,),
"45"=>array("name_ru"=>"Воркестер","name_en"=>"Worcester","name_href" => "za/population-of-worcester","count" => "150 657","real_id" =>45,),
"46"=>array("name_ru"=>"Емнамбити","name_en"=>"Emnambiti","name_href" => "za/population-of-emnambiti","count" => "150 147","real_id" =>46,),
"47"=>array("name_ru"=>"Полокване","name_en"=>"Polokwane","name_href" => "za/population-of-polokwane","count" => "148 143","real_id" =>47,),
"48"=>array("name_ru"=>"Кутлванонг","name_en"=>"Kutlvanong","name_href" => "za/population-of-kutlvanong","count" => "144 213","real_id" =>48,),
"49"=>array("name_ru"=>"Пит-Ретиф","name_en"=>"Piet-Retief","name_href" => "za/population-of-piet-retief","count" => "143 619","real_id" =>49,),
"50"=>array("name_ru"=>"Рандфонтейн","name_en"=>"Randfontein","name_href" => "za/population-of-randfontein","count" => "140 454","real_id" =>50,),
"51"=>array("name_ru"=>"Йоханнесбург","name_en"=>"Yohannesburg","name_href" => "za/population-of-yohannesburg","count" => "4 434 827","real_id" =>51,),
"52"=>array("name_ru"=>"Кейптаун","name_en"=>"Capetown","name_href" => "za/population-of-capetown","count" => "3 795 539","real_id" =>52,),
"53"=>array("name_ru"=>"Дурбан","name_en"=>"Durban","name_href" => "za/population-of-durban","count" => "3 720 953","real_id" =>53,),
"54"=>array("name_ru"=>"Соуэто","name_en"=>"Soweto","name_href" => "za/population-of-soweto","count" => "1 895 921","real_id" =>54,),
"55"=>array("name_ru"=>"Претория","name_en"=>"Pretoria","name_href" => "za/population-of-pretoria","count" => "1 815 889","real_id" =>55,)
);

?>